#pragma once

#include "Arondight45_HardwareSensors.hpp"

#include <array>
#include <cstdint>
#include <cstring>

namespace fc {

// Exact firmware boundary consumed by production, physical S31 HIL and browser SIL.
// Nothing above this boundary is a flight-state shortcut: inputs are the same raw
// ICM register bytes, receiver frame bytes and NAV1 hardware-module frame bytes that
// the production adapter obtains from SPI/UART. The only output is the real ESC pulse
// command generated by StateRuntime/fc::Runtime.
struct HardwareFrame {
    uint64_t now_us{};
    uint32_t dt_us{kNominalDtUs};
    uint32_t missed_samples{};
    std::array<uint8_t, 14> imu_registers{};
    std::array<uint8_t, 25> sbus_frame{};
    hwcontract::NavigationWireFrame navigation_frame{};
    bool imu_present{};
    bool sbus_present{};
    bool navigation_present{};
};

class FirmwareRuntime {
public:
    FirmwareRuntime() { reset(); }

    void reset() {
        runtime_.reset();
        rc_snapshot_ = {};
        navigation_snapshot_ = {};
        navigation_us_ = 0;
        last_navigation_sequence_ = 0;
        have_navigation_sequence_ = false;
    }

    RuntimeOutput step(const HardwareFrame& hardware) {
        if (hardware.sbus_present) {
            RC decoded{};
            if (decode_sbus(hardware.sbus_frame.data(), decoded)) {
                decoded.us = hardware.now_us;
                rc_snapshot_ = decoded;
            }
        }

        if (hardware.navigation_present) {
            NavigationState decoded{};
            if (hwcontract::decode_navigation_wire(hardware.navigation_frame, decoded)) {
                // Reject an exact duplicate/out-of-order sequence at the firmware
                // boundary. A real UART retransmission must never refresh freshness.
                const uint16_t seq = hardware.navigation_frame.sequence;
                const bool newer = !have_navigation_sequence_ ||
                    static_cast<uint16_t>(seq - last_navigation_sequence_) < 0x8000u;
                if (newer && (!have_navigation_sequence_ || seq != last_navigation_sequence_)) {
                    navigation_snapshot_ = decoded;
                    navigation_us_ = hardware.now_us;
                    last_navigation_sequence_ = seq;
                    have_navigation_sequence_ = true;
                }
            }
        }

        Imu imu{};
        const bool imu_valid = hardware.imu_present &&
            hwcontract::decode_icm42688_registers(hardware.imu_registers.data(), imu);

        RC rc = rc_snapshot_;
        const bool rc_fresh = rc.valid && hardware.now_us >= rc.us &&
                              hardware.now_us - rc.us <= kRcTimeoutUs;

        NavigationState navigation = navigation_snapshot_;
        if (!have_navigation_sequence_ || hardware.now_us < navigation_us_ ||
            hardware.now_us - navigation_us_ > hwcontract::kNavigationTimeoutUs) {
            navigation.valid = false;
        }

        StateRuntimeInput input{};
        input.flight.raw = imu;
        input.flight.rc = rc;
        input.flight.now_us = hardware.now_us;
        input.flight.dt_us = hardware.dt_us;
        input.flight.missed_samples = hardware.missed_samples;
        input.flight.imu_valid = imu_valid;
        input.flight.rc_fresh = rc_fresh;
        input.navigation = navigation;
        return runtime_.step(input);
    }

    StateRuntime& state_runtime() { return runtime_; }
    const StateRuntime& state_runtime() const { return runtime_; }
    const RC& receiver_snapshot() const { return rc_snapshot_; }
    const NavigationState& navigation_snapshot() const { return navigation_snapshot_; }

private:
    StateRuntime runtime_{};
    RC rc_snapshot_{};
    NavigationState navigation_snapshot_{};
    uint64_t navigation_us_{};
    uint16_t last_navigation_sequence_{};
    bool have_navigation_sequence_{};
};

}  // namespace fc
