import puppeteer from "puppeteer-core";

const base=process.argv[2]||"http://127.0.0.1:4174",executablePath=process.env.CHROME_BIN;if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage();
const styleUrl="https://tiles.openfreemap.org/styles/liberty",vectorHost="tiles.openfreemap.org",demHost="tiles.mapterhorn.com",imageryPrefix="https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/";
const imageryTile=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64"),vectorTile=Buffer.from("1a0f0a086275696c64696e672880207802","hex"),demTile=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAG4ElEQVR42u3WMQEAMAyAMKTX+Wqi33LEABdNPQDgL4kAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAAAwAAGAAAAADAAAYAADAAAAABgAAMAAAgAEAAAwAAGAAAAADAAAYAADAAAAABgAAMAAAgAEAAAwAABgAAMAAAAAGAAAwAACAAQAADAAAYAAAAAMAABgAAMAAAAAGAAAwAACAAQAADAAAYAAAAAMAABgAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAGAAhAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAADAAIgAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAAAwAAGAAAAADAAAYAADAAAAABgAAMAAAgAEAAAwAAGAAAAADAAAYAADAAAAABgAAMAAAgAEAAAwAABgAAMAAAAAGAAAwAACAAQAADAAAYAAAAAMAABgAAMAAAAAGAAAwAACAAQAADAAAYAAAAAMAABgAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAGAAhAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAADAAIgAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAAAwAAGAAAAADAAAYAADAAAAABgAAMAAAgAEAAAwAAGAAAAADAAAYAADAAAAABgAAMAAAgAEAAAwAABgAAMAAAAAGAAAwAACAAQAADAAAYAAAAAMAABgAAMAAAAAGAAAwAACAAQAADAAAYAAAAAMAABgAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAGAAhAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAADAAIgAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAAAwAAGAAAAADAAAYAADAAAAABgAAMAAAgAEAAAwAAGAAAAADAAAYAADAAAAABgAAMAAAgAEAAAwAABgAAMAAAAAGAAAwAACAAQAADAAAYAAAAAMAABgAAMAAAAAGAAAwAACAAQAADAAAYAAAAAMAABgAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAGAAhAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAHcWtddZxTTuf5gAAAAASUVORK5CYII=","base64"),failed=[],consoleErrors=[];
const style={version:8,name:"Honor deterministic WORLD fixture",sources:{"fixture-vector":{type:"vector",tiles:["https://tiles.openfreemap.org/ci/{z}/{x}/{y}.pbf"],minzoom:0,maxzoom:14}},layers:[{id:"background",type:"background",paint:{"background-color":"#243440"}}]};
page.on("requestfailed",request=>failed.push(`${request.failure()?.errorText||"FAILED"} ${request.url()}`));page.on("pageerror",error=>consoleErrors.push(`PAGEERROR ${error.message}`));page.on("console",message=>{if(message.type()==="error"||message.type()==="warning")consoleErrors.push(`${message.type().toUpperCase()} ${message.text()}`);});
try{
  await page.setUserAgent("Mozilla/5.0 (Linux; Android 15; HONOR Magic7 Pro Build/HNBRP-Q1; wv) AppleWebKit/537.36 Chrome/140.0.0.0 Mobile Safari/537.36");await page.setViewport({width:390,height:844,deviceScaleFactor:3,isMobile:true,hasTouch:true});await browser.defaultBrowserContext().overridePermissions(base,["geolocation"]);await page.setGeolocation({latitude:39.5696,longitude:2.6502,accuracy:4});await page.setRequestInterception(true);
  page.on("request",request=>{const url=request.url(),parsed=new URL(url);if(["data:","blob:","about:"].includes(parsed.protocol)||["127.0.0.1","localhost"].includes(parsed.hostname)){request.continue();return;}if(url.startsWith(styleUrl)){request.respond({status:200,contentType:"application/json",headers:{"access-control-allow-origin":"*","cache-control":"no-store"},body:JSON.stringify(style)});return;}if(parsed.hostname===vectorHost&&parsed.pathname.endsWith(".pbf")){request.respond({status:200,contentType:"application/x-protobuf",headers:{"access-control-allow-origin":"*","cache-control":"no-store"},body:vectorTile});return;}if(parsed.hostname===demHost){request.respond({status:200,contentType:"image/png",headers:{"access-control-allow-origin":"*","cache-control":"no-store"},body:demTile});return;}if(url.startsWith(imageryPrefix)){request.respond({status:200,contentType:"image/png",headers:{"access-control-allow-origin":"*"},body:imageryTile});return;}request.abort();});
  await page.goto(`${base}/drone_simulator.html`,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready"),{timeout:30000});
  try{await page.waitForFunction(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld;return document.body.classList.contains("solo-flight")&&v?.dataset.autoWorldLocationSource==="startup-gps"&&v?.dataset.worldMode==="real"&&v?.dataset.worldTerrainStatus==="box3d-active"&&b?.active===true&&b?.loading===false&&b?.map&&b?.threeRenderer&&Number(v.dataset.worldThreeFrames||0)>=1&&Number(v.dataset.presentationDraws||0)>=10;},{timeout:30000});}
  catch(error){const diagnostics=await page.evaluate(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld;return{status:document.querySelector("#status")?.textContent||"",realWorldStatus:document.querySelector("#realWorldStatus")?.textContent||"",bodyClass:document.body.className,autoWorldLocationSource:v?.dataset.autoWorldLocationSource||"",worldMode:v?.dataset.worldMode||"",terrainStatus:v?.dataset.worldTerrainStatus||"",terrainTriangles:v?.dataset.worldTerrainTriangles||"",terrainSource:v?.dataset.worldTerrainSource||"",buildingStatus:v?.dataset.worldBuildingCollisionStatus||"",buildingSource:b?.buildingSourceId||"",map:Boolean(b?.map),mapLoaded:Boolean(b?.map?.loaded?.()),active:Boolean(b?.active),loading:Boolean(b?.loading),origin:[b?.originLon,b?.originLat],originElevation:b?.terrainOriginElevationM,worldFrames:v?.dataset.worldThreeFrames||"",presentationDraws:v?.dataset.presentationDraws||"",presentationBacklogMs:v?.dataset.presentationBacklogMs||"",presentationCadence:v?.dataset.presentationCadence||"",presentationQuality:v?.dataset.presentationQualityMode||"",simTime:document.querySelector("#simTime")?.textContent||"",mapStyle:b?.map?.getStyle?.()?.name||""};});throw new Error(`Honor WORLD completed-startup timeout: ${JSON.stringify({diagnostics,failed:failed.slice(-30),consoleErrors:consoleErrors.slice(-30)})}`,{cause:error});}
  const before=await page.evaluate(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld,flight=b.threeRenderer.domElement,map=b.map.getCanvas(),flightAttrs=b.threeRenderer.getContext().getContextAttributes(),mapGl=map.getContext("webgl2")||map.getContext("webgl"),mapAttrs=mapGl?.getContextAttributes?.()||{};return{platform:v.dataset.renderPlatform,stable:v.dataset.presentationStableBackbuffer,software:Boolean(globalThis.__arondightDiagnostics?.presentationSoftwareRaster),flightDesync:flightAttrs?.desynchronized===true,mapDesync:mapAttrs?.desynchronized===true,declaredFlight:v.dataset.presentationCanvasDesynchronized,declaredMap:v.dataset.worldMapCanvasDesynchronized,flightSize:[flight.width,flight.height],mapSize:[map.width,map.height],mapRatio:map.width/Math.max(1,map.clientWidth),ratio:b.threeRenderer.getPixelRatio(),resizes:Number(v.dataset.presentationBackbufferResizes||0),terrain:v.dataset.worldTerrainStatus,terrainTriangles:Number(v.dataset.worldTerrainTriangles||0),worldFrames:Number(v.dataset.worldThreeFrames||0),presentationDraws:Number(v.dataset.presentationDraws||0)};});
  await page.evaluate(async()=>{const b=globalThis.__arondightRealWorld;for(let i=0;i<80;i++){b.setPerfMode(i%3===0?"critical":i%3===1?"constrained":"nominal");dispatchEvent(new Event("resize"));}await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);});
  const after=await page.evaluate(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld,flight=b.threeRenderer.domElement,map=b.map.getCanvas();return{flightSize:[flight.width,flight.height],mapSize:[map.width,map.height],mapRatio:map.width/Math.max(1,map.clientWidth),ratio:b.threeRenderer.getPixelRatio(),resizes:Number(v.dataset.presentationBackbufferResizes||0),quality:v.dataset.presentationQualityMode,perf:v.dataset.worldPerfMode,worldFrames:Number(v.dataset.worldThreeFrames||0),presentationDraws:Number(v.dataset.presentationDraws||0)};});
  if(before.platform!=="android-stable"||before.stable!=="1"||before.declaredFlight!=="0"||before.declaredMap!=="0"||before.flightDesync||before.mapDesync)throw new Error(`Honor used an unsafe WebGL compositor path: ${JSON.stringify({before,after})}`);
  if(before.terrain!=="box3d-active"||before.terrainTriangles<4000||before.worldFrames<1||before.presentationDraws<10)throw new Error(`Honor WORLD did not reach DEM physics and a live presentation loop before compositor test: ${JSON.stringify(before)}`);
  const expectedFlightRatio=before.software ? .3 : 1,expectedMapRatio=before.software ? .5 : 1;if(Math.abs(before.ratio-expectedFlightRatio)>.001||Math.abs(after.ratio-expectedFlightRatio)>.001||Math.abs(before.mapRatio-expectedMapRatio)>.02||Math.abs(after.mapRatio-expectedMapRatio)>.02||JSON.stringify(before.flightSize)!==JSON.stringify(after.flightSize)||JSON.stringify(before.mapSize)!==JSON.stringify(after.mapSize)||after.resizes-before.resizes>1)throw new Error(`Honor drawing buffers were reallocated by FPS/resize churn: ${JSON.stringify({before,after})}`);
  console.log(`Honor Android render E2E passed after completed GPS WORLD activation: synchronized dual-WebGL compositor, deterministic DEM-backed WORLD, live presentation loop, fixed ${after.ratio.toFixed(1)} backbuffer, and idempotent resize under 80 FPS-mode/resize events.`);
}finally{await browser.close();}
