import puppeteer from "puppeteer-core";

const base=process.argv[2]||"http://127.0.0.1:4174",baseOrigin=new URL(base).origin,cacheTag=process.env.GITHUB_SHA?`?ci=${encodeURIComponent(process.env.GITHUB_SHA)}`:"",executablePath=process.env.CHROME_BIN;if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage();
const styleUrl="https://tiles.openfreemap.org/styles/liberty",imageryPrefix="https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/",tile=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64"),style={version:8,name:"Honor compositor fixture",sources:{},layers:[{id:"background",type:"background",paint:{"background-color":"#243440"}}]};
try{
  await page.setUserAgent("Mozilla/5.0 (Linux; Android 15; HONOR Magic7 Pro Build/HNBRP-Q1; wv) AppleWebKit/537.36 Chrome/140.0.0.0 Mobile Safari/537.36");await page.setViewport({width:390,height:844,deviceScaleFactor:3,isMobile:true,hasTouch:true});await browser.defaultBrowserContext().overridePermissions(baseOrigin,["geolocation"]);await page.setGeolocation({latitude:39.5696,longitude:2.6502,accuracy:4});await page.setRequestInterception(true);
  page.on("request",request=>{const url=request.url(),parsed=new URL(url);if(["data:","blob:","about:"].includes(parsed.protocol)||parsed.origin===baseOrigin){request.continue();return;}if(url.startsWith(styleUrl)){request.respond({status:200,contentType:"application/json",headers:{"access-control-allow-origin":"*"},body:JSON.stringify(style)});return;}if(url.startsWith(imageryPrefix)){request.respond({status:200,contentType:"image/png",headers:{"access-control-allow-origin":"*"},body:tile});return;}request.abort();});
  await page.goto(`${baseOrigin}/drone_simulator.html${cacheTag}`,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready"),{timeout:30000});await page.waitForFunction(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld;return document.body.classList.contains("solo-flight")&&v?.dataset.worldMode==="real"&&b?.map&&b?.threeRenderer&&Number(v.dataset.worldThreeFrames||0)>4;},{timeout:25000});
  const before=await page.evaluate(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld,flight=b.threeRenderer.domElement,map=b.map.getCanvas(),flightAttrs=b.threeRenderer.getContext().getContextAttributes(),mapGl=map.getContext("webgl2")||map.getContext("webgl"),mapAttrs=mapGl?.getContextAttributes?.()||{};return{platform:v.dataset.renderPlatform,stable:v.dataset.presentationStableBackbuffer,software:Boolean(globalThis.__arondightDiagnostics?.presentationSoftwareRaster),flightDesync:flightAttrs?.desynchronized===true,mapDesync:mapAttrs?.desynchronized===true,declaredFlight:v.dataset.presentationCanvasDesynchronized,declaredMap:v.dataset.worldMapCanvasDesynchronized,flightSize:[flight.width,flight.height],mapSize:[map.width,map.height],mapRatio:map.width/Math.max(1,map.clientWidth),ratio:b.threeRenderer.getPixelRatio(),resizes:Number(v.dataset.presentationBackbufferResizes||0)};});
  const lateBuildingSpawn=await page.evaluate(()=>{
    const bridge=globalThis.__arondightRealWorld,viewport=document.querySelector("#viewport"),diagnostics=globalThis.__arondightDiagnostics,sink=bridge?.buildingCollisionSink;if(typeof sink!=="function")throw new Error("building collision sink unavailable");
    const far={buildingKey:"already-loaded",base:0,top:7,points:[[8,-1],[10,-1],[10,1],[8,1]]};
    sink({hash:"late-clear",footprintCount:1,prismCount:1,prisms:[far]});
    const phase1={relocated:viewport.dataset.worldLaunchRelocated,offset:Number(viewport.dataset.worldLaunchOffsetM),prisms:Number(diagnostics.worldBuildingCollisionPrisms)};
    const home={buildingKey:"late-home",base:0,top:8,points:[[-1.2,-1.2],[1.2,-1.2],[1.2,1.2],[-1.2,1.2]]};
    sink({hash:"late-home",footprintCount:2,prismCount:2,prisms:[far,home]});
    return{phase1,relocated:viewport.dataset.worldLaunchRelocated,offset:Number(viewport.dataset.worldLaunchOffsetM),x:Number(viewport.dataset.worldLaunchX),y:Number(viewport.dataset.worldLaunchY),prisms:Number(diagnostics.worldBuildingCollisionPrisms)};
  });
  if(lateBuildingSpawn.phase1.relocated!=="0"||Math.abs(lateBuildingSpawn.phase1.offset)>.01||lateBuildingSpawn.phase1.prisms!==1)throw new Error(`clear first building snapshot unexpectedly moved launch: ${JSON.stringify(lateBuildingSpawn)}`);
  if(lateBuildingSpawn.relocated!=="1"||!(lateBuildingSpawn.offset>1.2)||lateBuildingSpawn.prisms!==2||!Number.isFinite(lateBuildingSpawn.x)||!Number.isFinite(lateBuildingSpawn.y))throw new Error(`late-discovered home did not relocate launch outside all colliders: ${JSON.stringify(lateBuildingSpawn)}`);
  await page.evaluate(async()=>{const b=globalThis.__arondightRealWorld;for(let i=0;i<80;i++){b.setPerfMode(i%3===0?"critical":i%3===1?"constrained":"nominal");dispatchEvent(new Event("resize"));}await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);});
  const after=await page.evaluate(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld,flight=b.threeRenderer.domElement,map=b.map.getCanvas();return{flightSize:[flight.width,flight.height],mapSize:[map.width,map.height],mapRatio:map.width/Math.max(1,map.clientWidth),ratio:b.threeRenderer.getPixelRatio(),resizes:Number(v.dataset.presentationBackbufferResizes||0),quality:v.dataset.presentationQualityMode,perf:v.dataset.worldPerfMode};});
  if(before.platform!=="android-stable"||before.stable!=="1"||before.declaredFlight!=="0"||before.declaredMap!=="0"||before.flightDesync||before.mapDesync)throw new Error(`Honor used an unsafe WebGL compositor path: ${JSON.stringify({before,after})}`);
  const expectedFlightRatio=before.software?.3:.9,expectedMapRatio=before.software?.5:1;if(Math.abs(before.ratio-expectedFlightRatio)>.001||Math.abs(after.ratio-expectedFlightRatio)>.001||Math.abs(before.mapRatio-expectedMapRatio)>.02||Math.abs(after.mapRatio-expectedMapRatio)>.02||JSON.stringify(before.flightSize)!==JSON.stringify(after.flightSize)||JSON.stringify(before.mapSize)!==JSON.stringify(after.mapSize)||after.resizes-before.resizes>1)throw new Error(`Honor drawing buffers were reallocated by FPS/resize churn: ${JSON.stringify({before,after})}`);
  console.log(`Honor Android render E2E passed on ${baseOrigin}: synchronized dual-WebGL compositor, fixed ${after.ratio.toFixed(1)} backbuffer, and idempotent resize under 80 FPS-mode/resize events.`);
}finally{await browser.close();}
