import assert from "node:assert/strict";import {readFileSync} from "node:fs";
const fire=readFileSync("sim/flight_fire_fx.mjs","utf8"),walkFire=readFileSync("sim/walk_weapon_system.mjs","utf8"),physicsFire=readFileSync("sim/box3d_combat_world.mjs","utf8"),sim=readFileSync("sim/simulator.mjs","utf8"),world=readFileSync("sim/real_world_bootstrap.mjs","utf8"),xbox=readFileSync("sim/xbox_gamepad.mjs","utf8"),impact=readFileSync("sim/impact_explosion_overlay.mjs","utf8"),audio=readFileSync("sim/audio_settings.mjs","utf8");
for(const marker of ['fireAimMode="touch-1to1"','fireCrosshairMode="center-fixed"','const x=rotated?active.clientY-screenRect.top:active.clientX-screenRect.left','if(active?.source==="gamepad"){const x=rect.width*.5,y=rect.height*.5','viewport.dataset.fireAimMode=active.source==="gamepad"?"center-fixed":"touch-1to1"','onRecoil(.16)','hitConfirmSound','combat-damage-vignette','arondight:combat-hit-confirm','arondight:combat-damage','box3d-isBullet-ccd-v1'])assert.ok(fire.includes(marker),`missing combat marker: ${marker}`);
for(const marker of ['bodyDef.isBullet','def.isBullet=true','b3_kinematicBody','b3World_Step','getNumContactBeginEvents','getNumContactHitEvents','physics-bullet','real-bullets+cars+people+trees-v1'])assert.ok(physicsFire.includes(marker),`missing Box3D combat marker: ${marker}`);
assert.ok(!fire.includes('THREE.Raycaster().intersectObjects'),"flight gameplay hits regressed to Three ray candidate resolution");assert.ok(!walkFire.includes('intersectObjects('),"WALK gameplay hits regressed to Three ray candidate resolution");assert.ok(walkFire.includes('physics.fire(')&&walkFire.includes('box3d-isBullet-ccd-v1'),"WALK weapons are not routed to Box3D bullets");
for(const marker of ['const POOL_SIZE=12','const SPARKS=9','MutationObserver','flight-fire-impact','bullet-impact-explosion','fireImpactExplosions'])assert.ok(impact.includes(marker),`missing pooled impact explosion marker: ${marker}`);assert.ok(audio.includes('import "./impact_explosion_overlay.mjs";'),"impact explosion overlay is not loaded with flight fire FX");
for(const marker of ['onRecoil:addFireCameraKick','applyFireCameraShake(dt)','externalAirframeVisualRig.update','physics.render(presentationPose,presentationDt,visualPose)','this.visualGroup','fpvSelfCameraVisible'])assert.ok(sim.includes(marker),`missing simulator presentation marker: ${marker}`);
assert.ok(world.includes('window.dispatchEvent(new CustomEvent("arondight:combat-hit-confirm"'),"peer acknowledgement does not drive hit confirm");assert.ok(world.includes('window.dispatchEvent(new CustomEvent("arondight:combat-damage"'),"incoming hit does not drive damage indication");assert.ok(xbox.includes('fire:rightShoulder'),"Xbox RB is still gated behind LB aim");
console.log("Combat fire contract passed: real Box3D isBullet CCD projectiles, kinematic Box3D cars/targets, replicated bullet spawn, 1:1 touch fire, Xbox center fire, recoil and hit/damage feedback.");
