import puppeteer from "puppeteer-core";

const executablePath=process.env.CHROME_BIN;if(!executablePath)throw Error("CHROME_BIN required");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]});
const page=await browser.newPage();const pageErrors=[];page.on("pageerror",e=>pageErrors.push(String(e?.stack||e)));
try{
  await page.setUserAgent("Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148");await page.setViewport({width:844,height:390,deviceScaleFactor:1});
  const url=`https://kurzlernen.de/drone_simulator.html?handler-growth-diag=${Date.now()}`;await page.goto(url,{waitUntil:"load",timeout:30000});
  await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&globalThis.__arondightRealWorld?.threeScene,{timeout:30000});
  await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport");v.dataset.worldMode="real";b.active=true;b.originLon=9;b.originLat=47;});await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.worldProceduralPopulation==="1",{timeout:10000});

  const growth=await page.evaluate(async()=>{const b=globalThis.__arondightRealWorld,dummy={object:{userData:{},parent:null}},raf=()=>new Promise(r=>requestAnimationFrame(r));let prev=b.registerWorldPopulationHit,changes=0,combos={},maxCallMs=0,callErrors=[];for(let i=0;i<360;i++){await raf();const cur=b.registerWorldPopulationHit;if(cur!==prev){changes++;prev=cur;}const key=[cur?.__gameplayPolishLiteWrapper?1:0,cur?.__realityDamageTop?1:0,cur?.__playerVehicleHitRouterV2?1:0,cur?.__proceduralPopulationProvider?1:0,cur?.__worldLivelinessWrapper?1:0].join("");combos[key]=(combos[key]||0)+1;if(i%60===59){const t=performance.now();try{cur(dummy);}catch(e){callErrors.push(String(e?.stack||e));}maxCallMs=Math.max(maxCallMs,performance.now()-t);}}return{samples:360,changes,combos,maxCallMs,callErrors,finalMarkers:{polish:!!prev?.__gameplayPolishLiteWrapper,damage:!!prev?.__realityDamageTop,vehicle:!!prev?.__playerVehicleHitRouterV2,procedural:!!prev?.__proceduralPopulationProvider,liveliness:!!prev?.__worldLivelinessWrapper}};});
  console.log("TARGET_HANDLER_GROWTH",JSON.stringify(growth));

  const stress=await page.evaluate(async()=>{const b=globalThis.__arondightRealWorld,scene=b.threeScene,v=document.querySelector("#viewport"),seen=new Map();scene.traverse(node=>{const id=String(node?.userData?.worldPopulationId||""),kind=String(node?.userData?.worldPopulationKind||"");if(node?.isMesh&&id&&['person','car','bus'].includes(kind)&&!seen.has(id))seen.set(id,{id,kind,mesh:node});});const all=[...seen.values()],seq=[...all.filter(x=>x.kind==='person').slice(0,10).map(x=>[x,1]),...all.filter(x=>x.kind==='car').slice(0,6).map(x=>[x,6]),...all.filter(x=>x.kind==='bus').slice(0,3).map(x=>[x,13])];let calls=0,handled=0,maxMs=0,errors=[];for(const [rec,count] of seq){for(let i=0;i<count;i++){const p=rec.mesh.position.clone();rec.mesh.getWorldPosition?.(p);const t=performance.now();try{if(b.registerWorldPopulationHit({object:rec.mesh,point:p}))handled++;}catch(e){errors.push({target:rec.id,kind:rec.kind,hit:i+1,error:String(e?.stack||e)});}maxMs=Math.max(maxMs,performance.now()-t);calls++;if(errors.length)break;}if(errors.length)break;await new Promise(r=>setTimeout(r,0));}return{targets:seq.length,calls,handled,maxMs,errors,ragdollSpawns:Number(v.dataset.worldRagdollSpawns||0),ragdolls:Number(v.dataset.worldRagdolls||0),ragdollPool:Number(v.dataset.worldRagdollPool||0),ragdollMax:Number(v.dataset.worldRagdollMax||0),explosionSpawns:Number(v.dataset.worldCarExplosionSpawns||0),explosions:Number(v.dataset.worldCarExplosions||0),explosionPool:Number(v.dataset.worldCarExplosionPool||0),debris:Number(v.dataset.worldCarDebrisActive||0),populationHits:Number(v.dataset.worldPopulationHits||0),lifeHits:Number(v.dataset.worldLifeHits||0)};});
  console.log("TARGET_HANDLER_STRESS",JSON.stringify(stress));
  throw Error(`TARGET_DIAG_RESULT growth=${JSON.stringify(growth)} stress=${JSON.stringify(stress)} pageErrors=${JSON.stringify(pageErrors.slice(-4))}`);
}finally{await browser.close();}