import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html";const url=new URL(input,"http://127.0.0.1:4174");
const executablePath=process.env.CHROME_BIN;if(!executablePath)throw Error("CHROME_BIN required");if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);url.searchParams.set("natural-ray-diag",String(Date.now()));
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]});
const page=await browser.newPage(),pageErrors=[];page.on("pageerror",e=>pageErrors.push(String(e?.stack||e)));
try{
  await page.setUserAgent("Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148");await page.setViewport({width:844,height:390,deviceScaleFactor:1});await page.goto(url.href,{waitUntil:"load",timeout:30000});
  await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&globalThis.__arondightRealWorld?.threeScene&&globalThis.__arondightRealWorld?.threeCamera,{timeout:30000});
  await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport");v.dataset.worldMode="real";b.active=true;b.originLon=9;b.originLat=47;});await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.worldProceduralPopulation==="1",{timeout:10000});
  const setup=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,scene=b.threeScene,records=new Map();scene.updateMatrixWorld(true);scene.traverse(n=>{const id=String(n?.userData?.worldPopulationId||""),kind=String(n?.userData?.worldPopulationKind||"");if(!n?.isMesh||!id||!["person","car","bus"].includes(kind))return;let r=records.get(id);if(!r){r={id,kind,meshes:[]};records.set(id,r);}r.meshes.push(n);});globalThis.__naturalTargetDiag={records:[...records.values()],current:null,pointerDown:false};return{records:records.size,people:[...records.values()].filter(r=>r.kind==="person").length,cars:[...records.values()].filter(r=>r.kind==="car").length,buses:[...records.values()].filter(r=>r.kind==="bus").length};});console.log("NATURAL setup",JSON.stringify(setup));
  const attempt=async(index,worldActive)=>page.evaluate(async({index,worldActive})=>{const wait=ms=>new Promise(r=>setTimeout(r,ms)),d=globalThis.__naturalTargetDiag,b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport"),scene=b.threeScene,camera=b.threeCamera,rec=d.records[index];if(!rec)return{skip:"missing"};b.active=worldActive;scene.updateMatrixWorld(true);camera.updateMatrixWorld(true);const mesh=rec.meshes.find(m=>m.visible&&m.material?.visible!==false&&m.geometry&&!m.userData?.flightFireIgnore)||rec.meshes.find(m=>m.visible&&m.geometry);if(!mesh)return{id:rec.id,kind:rec.kind,skip:"no-visible-mesh"};mesh.geometry.computeBoundingSphere?.();if(!mesh.geometry.boundingSphere)return{id:rec.id,kind:rec.kind,skip:"no-sphere"};const originalIgnore=new Map();scene.traverse(n=>{if(n?.isMesh){originalIgnore.set(n,n.userData.flightFireIgnore);n.userData.flightFireIgnore=n!==mesh;}});const originalRaycast=mesh.raycast,ray={calls:0,hits:0,lastDistance:null};mesh.userData.flightFireIgnore=false;mesh.raycast=function(raycaster,intersections){const before=intersections.length;originalRaycast.call(this,raycaster,intersections);ray.calls++;for(let i=before;i<intersections.length;i++)if(intersections[i]?.object===this){ray.hits++;ray.lastDistance=Number(intersections[i].distance);}};scene.updateMatrixWorld(true);const center=mesh.geometry.boundingSphere.center.clone().applyMatrix4(mesh.matrixWorld);camera.lookAt(center);camera.updateMatrixWorld(true);const r=v.getBoundingClientRect(),aimX=v.clientWidth/2,aimY=v.clientHeight/2,rotated=v.dataset.soloOrientation==="css-landscape",clientX=rotated?r.right-aimY:r.left+aimX,clientY=rotated?r.top+aimX:r.top+aimY,before={shots:Number(v.dataset.fireShots||0),pop:Number(v.dataset.worldPopulationHits||0),routed:Number(v.dataset.fireVsHits||0)};await wait(105);camera.lookAt(center);camera.updateMatrixWorld(true);if(!d.pointerDown){v.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:94,pointerType:"touch",clientX,clientY,button:0,buttons:1,isPrimary:true}));d.pointerDown=true;}else v.dispatchEvent(new PointerEvent("pointermove",{bubbles:true,cancelable:true,pointerId:94,pointerType:"touch",clientX,clientY,button:-1,buttons:1,isPrimary:true}));await wait(35);const after={shots:Number(v.dataset.fireShots||0),pop:Number(v.dataset.worldPopulationHits||0),routed:Number(v.dataset.fireVsHits||0),source:v.dataset.fireInputSource||"",locked:v.dataset.fireCombatLocked||"",candidates:Number(v.dataset.fireCandidateCount||0)};mesh.raycast=originalRaycast;for(const[n,val]of originalIgnore)n.userData.flightFireIgnore=val;return{id:rec.id,kind:rec.kind,worldActive,before,after,ray,center:[center.x,center.y,center.z]};},{index,worldActive});
  let proof=null,samples=[];for(let i=0;i<Math.min(35,setup.records);i++){const on=await attempt(i,true);samples.push(on);console.log("NATURAL ON",i,JSON.stringify(on));const fired=on.after?.shots>on.before?.shots,intersected=on.ray?.hits>0,routed=on.after?.pop>on.before?.pop;if(fired&&intersected&&!routed){const off=await attempt(i,false);samples.push(off);console.log("NATURAL OFF",i,JSON.stringify(off));if(off.ray?.hits>0&&off.after?.pop>off.before?.pop){proof={index:i,on,off};break;}}}
  await page.evaluate(()=>{const d=globalThis.__naturalTargetDiag,v=document.querySelector("#viewport");if(d?.pointerDown)v.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:94,pointerType:"touch",button:0,buttons:0,isPrimary:true}));});
  throw Error(`NATURAL_TARGET_DECISION proof=${JSON.stringify(proof)} samples=${JSON.stringify(samples.slice(-10))} pageErrors=${JSON.stringify(pageErrors.slice(-4))}`);
}finally{await browser.close();}