/* Run with playwright available in NODE_PATH; optional CHROMIUM_PATH and PLANCK_LOCAL.
   Tests the shipped single HTML file. No application source is rewritten. */
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const {pathToFileURL}=require('node:url');
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:950}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 if(process.env.PLANCK_LOCAL)await page.route('**/planck.min.js',r=>r.fulfill({path:process.env.PLANCK_LOCAL,contentType:'application/javascript'}));
 await page.goto(process.env.EDITOR2D_URL||pathToFileURL(path.resolve(__dirname,'../editor2d.html')).href);
 await page.waitForFunction(()=>window.Editor2D?.scene.bodies.length>0);
 await page.waitForTimeout(150);
 let passed=0;
 async function check(name,fn){await fn();passed++;console.log('PASS',name)}
 await check('Initial view fits actual viewport, geometry valid',async()=>{const r=await page.evaluate(()=>({scale:Editor2D.views[0].camera.scale,errors:Editor2D.validate()}));assert.ok(r.scale>15);assert.deepEqual(r.errors,[])});
 await check('Native scene roundtrip keeps original contours and custom properties',async()=>{const r=await page.evaluate(()=>{const api=Editor2D,s=structuredClone(api.scene);s.bodies[0].customProperties=[{name:'material',string:'concrete'},{name:'alive',bool:true},{name:'home',vec2:{x:1,y:2}}];const d=api.loadDocument(JSON.parse(JSON.stringify(s)),'roundtrip.e2d');return {before:s.bodies,after:d.scene.bodies}});assert.deepEqual(r.after,r.before)});
 await check('RUBE hex floats, zero vector, split coordinates and defaults',async()=>{const r=await page.evaluate(()=>{const s=Editor2D.importRube({gravity:0,body:[{name:'same',type:2,position:{x:'3F800000',y:'40000000'},awake:true,fixture:[{circle:{radius:'3F000000',center:0},customProperties:[{name:'v',float:'3FC00000'}]}]},{name:'same',fixture:[{polygon:{vertices:{x:[0,1,0],y:[0,0,1]}}}]}]},'legacy');return {p:s.bodies[0].position,r:s.bodies[0].fixtures[0].radius,friction:s.bodies[0].fixtures[0].friction,mask:s.bodies[0].fixtures[0].maskBits,custom:s.bodies[0].fixtures[0].customProperties,unique:s.bodies[0].id!==s.bodies[1].id}});assert.deepEqual(r.p,{x:1,y:2});assert.equal(r.r,.5);assert.equal(r.friction,0);assert.equal(r.mask,65535);assert.equal(r.custom[0].float,1.5);assert.ok(r.unique)});
 await check('Concave decomposition preserves area, orientation and <=8 vertices',async()=>{const r=await page.evaluate(()=>{const p=[{x:0,y:0},{x:4,y:0},{x:4,y:4},{x:3,y:4},{x:3,y:1},{x:1,y:1},{x:1,y:4},{x:0,y:4}],parts=Editor2D.decompose(p),area=q=>q.reduce((sum,a,i)=>{const b=q[(i+1)%q.length];return sum+a.x*b.y-a.y*b.x},0)/2;return {area:area(p),sum:parts.reduce((n,p)=>n+area(p),0),sizes:parts.map(p=>p.length),areas:parts.map(area)}});assert.equal(r.area,r.sum);assert.ok(r.sizes.every(n=>n<=8));assert.ok(r.areas.every(n=>n>0))});
 await check('Self-intersection fails closed before export / physics',async()=>{assert.equal(await page.evaluate(()=>{try{Editor2D.decompose([{x:0,y:0},{x:2,y:2},{x:0,y:2},{x:2,y:0}]);return false}catch{return true}}),true)});
 await check('Import/export preserves unknown fields and typed properties',async()=>{const r=await page.evaluate(()=>{const raw=Editor2D.exportRube();raw.vendorExtension={secret:'keep'};raw.body[0].vendorTag='body-extra';raw.body[0].fixture[0].vendorTag={ok:true};const s=Editor2D.importRube(raw,'again');const out=Editor2D.exportRube(s);return {world:out.vendorExtension,body:out.body[0].vendorTag,fixture:out.body[0].fixture[0].vendorTag,custom:out.body[0].customProperties}});assert.deepEqual(r.world,{secret:'keep'});assert.equal(r.body,'body-extra');assert.deepEqual(r.fixture,{ok:true});assert.equal(r.custom[1].bool,true)});
 await check('Player runs 600 stable steps and never changes document state',async()=>{const r=await page.evaluate(()=>{Editor2D.loadDemo('mechanism');const s=Editor2D.scene,before=JSON.stringify(s),sim=Editor2D.buildWorld(s);for(let i=0;i<600;i++)sim.world.step(1/60);return {same:before===JSON.stringify(s),finite:[...sim.bodies.values()].every(b=>Number.isFinite(b.getPosition().x)&&Number.isFinite(b.getPosition().y)),dynamicAboveFloor:[...sim.bodies.values()].filter(b=>b.isDynamic()).every(b=>b.getPosition().y>-.8),count:sim.joints.size}});assert.ok(r.same&&r.finite&&r.dynamicAboveFloor);assert.equal(r.count,4)});
 await check('All eight joint types instantiate and simulate',async()=>{const r=await page.evaluate(()=>{Editor2D.loadDemo('joints');const s=Editor2D.scene,sim=Editor2D.buildWorld(s);for(let i=0;i<120;i++)sim.world.step(1/60);return {count:sim.joints.size,types:[...sim.joints.values()].map(j=>j.getType()),finite:[...sim.bodies.values()].every(b=>Number.isFinite(b.getAngle()))}});assert.equal(r.count,8);assert.equal(new Set(r.types).size,8);assert.ok(r.finite)});
 await page.evaluate(()=>{Editor2D.loadDemo('mechanism');Editor2D.select([Editor2D.scene.bodies.find(b=>b.name==='chassis').id],'body');Editor2D.setMode('body')});
 let canvas=page.locator('.view.focused canvas');await canvas.focus();await page.mouse.move(650,380);
 await check('B/F/V/J/I mode keys and independent selections',async()=>{for(const[k,m]of [['f','fixture'],['v','vertex'],['j','joint'],['i','image'],['b','body']]){await page.keyboard.press(k);assert.equal(await page.evaluate(()=>Editor2D.mode),m)}assert.equal(await page.evaluate(()=>Editor2D.documents.at(-1).selection.body.length),1)});
 const base=await page.evaluate(()=>{const b=Editor2D.scene.bodies.find(b=>b.name==='chassis');return {x:b.position.x,y:b.position.y}});
 await check('T X 2 Enter translates exactly +2 on x',async()=>{await page.keyboard.press('t');await page.keyboard.press('x');await page.keyboard.type('2');await page.keyboard.press('Enter');const p=await page.evaluate(()=>Editor2D.scene.bodies.find(b=>b.name==='chassis').position);assert.equal(p.x,base.x+2);assert.equal(p.y,base.y)});
 await check('Undo / redo restores transformation',async()=>{await page.keyboard.press('Control+z');assert.equal(await page.evaluate(()=>Editor2D.scene.bodies.find(b=>b.name==='chassis').position.x),base.x);await page.keyboard.press('Control+Shift+z');assert.equal(await page.evaluate(()=>Editor2D.scene.bodies.find(b=>b.name==='chassis').position.x),base.x+2)});
 await check('Escape cancels preview without leaving a partial change',async()=>{const before=await page.evaluate(()=>JSON.stringify(Editor2D.scene));await page.keyboard.press('g');await page.keyboard.press('y');await page.keyboard.type('10');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>JSON.stringify(Editor2D.scene)),before)});
 await check('R 90 Enter uses degrees; S scales fixtures',async()=>{await page.keyboard.press('r');await page.keyboard.type('90');await page.keyboard.press('Enter');assert.ok(Math.abs(await page.evaluate(()=>Editor2D.scene.bodies.find(b=>b.name==='chassis').angle)-Math.PI/2)<1e-8);await page.keyboard.press('s');await page.keyboard.type('2');await page.keyboard.press('Enter');assert.deepEqual(await page.evaluate(()=>Editor2D.validate()),[])});
 await check('C S moves cursor to selected body center',async()=>{await page.keyboard.press('c');await page.keyboard.press('s');const r=await page.evaluate(()=>({c:Editor2D.scene.cursor,p:Editor2D.scene.bodies.find(b=>b.name==='chassis').position}));assert.deepEqual(r.c,r.p)});
 await check('Shift+D clones connected bodies and remaps joints, Escape only cancels translation',async()=>{await page.evaluate(()=>{Editor2D.loadDemo('mechanism');const s=Editor2D.scene;Editor2D.select(s.bodies.filter(b=>['chassis','rear wheel','front wheel'].includes(b.name)).map(b=>b.id),'body');Editor2D.setMode('body')});await page.locator('.view.focused canvas').focus();const before=await page.evaluate(()=>({b:Editor2D.scene.bodies.length,j:Editor2D.scene.joints.length}));await page.keyboard.press('Shift+d');await page.keyboard.press('Escape');const r=await page.evaluate(()=>({b:Editor2D.scene.bodies.length,j:Editor2D.scene.joints.length,selected:Editor2D.documents.at(-1).selection.body,links:Editor2D.scene.joints.slice(-2)}));assert.equal(r.b,before.b+3);assert.equal(r.j,before.j+2);assert.ok(r.links.every(j=>r.selected.includes(j.bodyA)&&r.selected.includes(j.bodyB)));await page.keyboard.press('Control+z');assert.equal(await page.evaluate(()=>Editor2D.scene.bodies.length),before.b)});
 await check('Mirror structure preserves anchors, valid winding, limits and motor direction',async()=>{const r=await page.evaluate(()=>{const A=Editor2D;A.loadDemo('mechanism');A.select(A.scene.bodies.map(b=>b.id),'body');A.setMode('body');const before=structuredClone(A.scene);A.beginOperation('scale');A.operation.axis='x';A.operation.typed='-1';A.applyOperation({x:0,y:0});A.finishOperation(true);const s=A.scene,j=s.joints.find(j=>j.type==='revolute'),old=before.joints.find(k=>k.id===j.id),world=(p,b)=>({x:b.position.x+p.x*Math.cos(b.angle)-p.y*Math.sin(b.angle),y:b.position.y+p.x*Math.sin(b.angle)+p.y*Math.cos(b.angle)}),deltas=s.joints.filter(j=>j.type==='wheel'||j.type==='revolute').map(j=>{const a=world(j.anchorA,s.bodies.find(b=>b.id===j.bodyA)),b=world(j.anchorB,s.bodies.find(b=>b.id===j.bodyB));return Math.hypot(a.x-b.x,a.y-b.y)});return {errors:A.validate(),lower:j.lowerLimit,expect:-old.upperLimit,deltas,speed:s.joints[0].motorSpeed,oldSpeed:before.joints[0].motorSpeed}});assert.deepEqual(r.errors,[]);assert.equal(r.lower,r.expect);assert.ok(r.deltas.every(d=>d<1e-6));assert.equal(r.speed,-r.oldSpeed)});
 await check('Property edits are undoable and multi-select safe',async()=>{await page.evaluate(()=>{Editor2D.setMode('body');Editor2D.select(Editor2D.scene.bodies.filter(b=>b.type===2).slice(0,2).map(b=>b.id),'body')});const input=page.locator('[data-property="linearDamping"]');await input.fill('0.25');await input.press('Tab');assert.ok(await page.evaluate(()=>{const ids=Editor2D.documents.at(-1).selection.body;return Editor2D.scene.bodies.filter(b=>ids.includes(b.id)).every(b=>b.linearDamping===.25)}));await page.locator('.view.focused canvas').focus();await page.keyboard.press('Control+z');assert.ok(await page.evaluate(()=>{const ids=Editor2D.documents.at(-1).selection.body;return Editor2D.scene.bodies.filter(b=>ids.includes(b.id)).every(b=>b.linearDamping===0)}))});
 await check('Keyboard action menu opens, arrow navigation and Escape work',async()=>{await page.keyboard.press('Space');assert.equal(await page.locator('.popup').count(),1);await page.keyboard.press('ArrowRight');assert.ok(await page.getByRole('menuitem',{name:'Body'}).count());await page.keyboard.press('Escape');assert.equal(await page.locator('.popup').count(),0)});
 await check('PNG import embeds data; image movement, tracing and holes are supported',async()=>{const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=100;c.height=100;const g=c.getContext('2d');g.fillStyle='orange';g.fillRect(10,10,80,80);g.clearRect(35,35,30,30);return c.toDataURL().split(',')[1]});await page.locator('#imageFile').setInputFiles({name:'ring.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.waitForFunction(()=>Editor2D.scene.images.some(i=>i.name==='ring.png'));const r=await page.evaluate(()=>{const A=Editor2D,i=A.scene.images.at(-1),sample={...i,id:'sample',width:1,height:1,resolution:100,center:i.center,threshold:20,tolerance:.01};const output=A.composeSampler(sample,100);const contours=A.traceMask(output,sample);const area=p=>Math.abs(p.reduce((a,v,j)=>a+v.x*p[(j+1)%p.length].y-v.y*p[(j+1)%p.length].x,0)/2);return {embedded:i.src.startsWith('data:image/png'),count:contours.length,area:contours.reduce((n,p)=>n+area(p),0)}});assert.ok(r.embedded);assert.ok(r.count>=4);assert.ok(Math.abs(r.area-.55)<.04)});
 await check('Sampler tint preserves transparent pixels',async()=>{const r=await page.evaluate(()=>{const A=Editor2D,i=A.scene.images.at(-1),sample={...i,width:1,height:1,resolution:100,opacity:.5,colorTint:[128,128,128,255]};const c=A.composeSampler(sample,100).canvas,d=c.getContext('2d').getImageData(0,0,100,100).data;return {empty:d[3],hole:d[(50*100+50)*4+3],opaque:d[(20*100+20)*4+3]}});assert.equal(r.empty,0);assert.equal(r.hole,0);assert.ok(r.opaque>=126&&r.opaque<=129)});
 await check('Save downloads editable document and C++ export',async()=>{await page.locator('.view.focused canvas').focus();let wait=page.waitForEvent('download');await page.keyboard.press('Control+s');let dl=await wait;assert.ok(dl.suggestedFilename().endsWith('.e2d'));wait=page.waitForEvent('download');await page.evaluate(()=>Editor2D.exportCpp());dl=await wait;assert.ok(dl.suggestedFilename().endsWith('.cpp'));const cpp=fs.readFileSync(await dl.path(),'utf8');assert.ok(cpp.includes('b2WheelJointDef'));assert.ok(!cpp.includes('undefined'))});
 await check('Two editor views share document and player is independent',async()=>{await page.evaluate(()=>Editor2D.loadDemo('mechanism'));await page.locator('.view.focused canvas').focus();await page.keyboard.press('Control+Shift+c');await page.keyboard.press('Control+r');await page.waitForTimeout(200);assert.ok(await page.evaluate(()=>{const vs=Editor2D.views;const player=vs.at(-1);return vs.at(-2).doc===player.doc&&player.source!==player.doc.scene&&player.sim.steps>0}));await page.keyboard.press('Space');const step=await page.evaluate(()=>Editor2D.views.at(-1).sim.steps);await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>Editor2D.views.at(-1).sim.steps),step+1)});
 await page.evaluate(()=>{Editor2D.loadDemo('mechanism');});await page.waitForTimeout(100);await page.screenshot({path:process.env.EDITOR2D_SCREENSHOT||'/tmp/editor2d-desktop-verified.png'});
 await check('Mobile layout has reachable toolbar and no horizontal overflow',async()=>{await page.setViewportSize({width:390,height:844});await page.waitForTimeout(100);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByRole('button',{name:'Toggle Properties panel',exact:true}).click();assert.ok(await page.locator('#rightDock').evaluate(el=>el.classList.contains('mobile-open')));await page.getByRole('button',{name:'Toggle Properties panel',exact:true}).click();await page.screenshot({path:'/tmp/editor2d-mobile-verified.png'})});
 assert.deepEqual(errors,[],'No uncaught browser errors');console.log(`PASS ${passed} checks; no page errors`);await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
