import assert from 'node:assert/strict';
import fs from 'node:fs';

const html=fs.readFileSync(new URL('../editor3d.html',import.meta.url),'utf8');
const must=[
  ['Box3D inline runtime',/box3d\.js@0\.1\.1\/dist\/box3d\.inline\.mjs/],
  ['Three.js renderer',/three@0\.185\.1/],
  ['3D hull rendering',/ConvexGeometry/],
  ['RUBE-style menu bar',/data-menu="File"[\s\S]*data-menu="Edit"[\s\S]*data-menu="View"[\s\S]*data-menu="Scene"[\s\S]*data-menu="Window"[\s\S]*data-menu="Tools"[\s\S]*data-menu="Help"/],
  ['items dock',/id="itemsPanel"/],
  ['context dock',/id="contextPanel"/],
  ['undo dock',/id="undoPanel"/],
  ['properties dock',/id="propertiesPanel"/],
  ['message log dock',/id="logPanel"/],
  ['document + view model',/documents=\[\],views=\[\],activeView=null/],
  ['independent player source',/source:type==='player'\?clone\(source\|\|d\.scene\):null/],
  ['player Box3D world',/v\.sim=buildWorld\(v\.source\)/],
  ['editor modes',/body:'Body',fixture:'Fixture',vertex:'Vertex',joint:'Joint',image:'Image',sampler:'Sampler',world:'World'/],
  ['all current Box3D joint kinds',/\['revolute','distance','prismatic','wheel','spherical','weld','motor','parallel','filter'\]/],
  ['multi fixture bodies',/fixtures:\[\]/],
  ['Box3D transformed hull fixture',/b3CreateTransformedHullShape\(bodyId,sd,h,tr,\[1,1,1\]\)/],
  ['sphere fixture',/b3CreateSphereShape\(bodyId,sd/],
  ['capsule fixture',/b3CreateCapsuleShape\(bodyId,sd/],
  ['joint def mapping',/b3Default'\+j\.type\[0\]\.toUpperCase\(\)\+j\.type\.slice\(1\)\+'JointDef'/],
  ['X Y Z transform axes',/\['x','y','z'\]\.includes\(key\)/],
  ['typed transform input',/operation\.typed/],
  ['Space action menu',/openPopup\(actionMenu\(\)/],
  ['body fixture vertex joint image shortcuts',/const m=\{b:'body',f:'fixture',v:'vertex',j:'joint',i:'image'\}\[key\]/],
  ['duplicate remaps connected joints',/map\.has\(j\.bodyA\)&&map\.has\(j\.bodyB\)/],
  ['undo history',/d\.history\.push\(\{label,before,after\}\)/],
  ['clone view',/function cloneView\(\)/],
  ['tile views',/tiled=!tiled/],
  ['image alpha to 3D fixtures',/function traceImageToBoxes\(\)/],
  ['editable e3d format',/format:'editor3d',version:2/],
  ['kinematic mouse body',/bd\.type=b3\.b3BodyType\.b3_kinematicBody/],
  ['motor joint definition',/b3\.b3DefaultMotorJointDef\(\)/],
  ['motor joint creation',/b3\.b3CreateMotorJoint\(v\.sim\.world,jd\)/],
  ['local grab point',/b3\.b3Body_GetLocalPoint\(\[0,0,0\],pb,point\)/],
  ['official mouse spring hertz',/jd\.linearHertz=7\.5/],
  ['critical damping',/jd\.linearDampingRatio=1/],
  ['mass-scaled spring force',/jd\.maxSpringForce=100\*Math\.max\(\.001,b3\.b3Body_GetMass\(pb\)\)/],
  ['target-transform dragging',/b3\.b3Body_SetTargetTransform\(v\.grab\.mouseBody/],
  ['joint cleanup',/b3\.b3DestroyJoint\(g\.joint,true\)/],
  ['mouse-body cleanup',/b3\.b3DestroyBody\(g\.mouseBody\)/],
  ['selection suppression',/user-select:none/],
  ['iOS callout suppression',/-webkit-touch-callout:none/],
  ['canvas touch ownership',/touch-action:none/],
  ['selectstart prevention',/addEventListener\('selectstart',e=>e\.preventDefault\(\)\)/],
  ['pointer cancel cleanup',/addEventListener\('pointercancel',e=>endGrab\(v,e\)\)/],
  ['lost pointer capture cleanup',/addEventListener\('lostpointercapture',e=>endGrab\(v,e\)\)/],
];
for(const [name,re] of must)assert.match(html,re,`Editor3D contract missing: ${name}`);
assert.doesNotMatch(html,/user-select:text/,'Canvas/editor must never enable browser text selection');
assert.doesNotMatch(html,/(?:src|from)=["'][^"']*(?:planck|box2d)|import\s+[^;]*(?:planck|box2d)/i,'Editor3D must not import a 2D physics runtime');
console.log(`PASS editor3d parity contract (${must.length} invariants)`);
