const store=new Map();
globalThis.localStorage={getItem:key=>store.has(key)?store.get(key):null,setItem:(key,value)=>store.set(key,String(value)),removeItem:key=>store.delete(key)};
const {FlightLogbook,FLIGHT_LOGBOOK_KEY}=await import("../sim/flight_logbook.mjs");
const log=new FlightLogbook();
const sample=(overrides={})=>({simTime:0,x:0,y:0,z:2,vx:0,vy:0,vz:0,speed:0,yawDeg:0,agl:2,aglValid:true,batteryV:16.2,armed:false,navDegraded:false,worldMode:"training",disarmReason:"FC_DISARM",...overrides});
log.observe(sample());
if(log.active||log.entries.length)throw new Error("DISARMED telemetry must not create a flight");
log.observe(sample({simTime:1,armed:true}));
if(!log.active||log.entries.length)throw new Error("ARMED transition did not start exactly one active flight");
log.observe(sample({simTime:2,armed:true,x:1,vx:-1,speed:1,batteryV:15.9}));
log.observe(sample({simTime:3,armed:true,x:2,vx:-1,speed:1.2,aglValid:false,navDegraded:true,batteryV:15.7}));
log.observe(sample({simTime:4,armed:false,x:2.5,vx:-.2,speed:.2,batteryV:15.6,disarmReason:"ARM_OFF"}));
if(log.active||log.entries.length!==1)throw new Error("DISARM transition did not finish exactly one flight");
const entry=log.entries[0];
if(!(entry.durationS>=3&&entry.distanceM>2&&entry.maxSpeedMps>=1.2&&entry.maxForwardMps>=1&&entry.navDegradedS>=1&&entry.endReason==="ARM_OFF"))throw new Error(`flight metrics wrong: ${JSON.stringify(entry)}`);
const persisted=JSON.parse(store.get(FLIGHT_LOGBOOK_KEY)||"[]");
if(persisted.length!==1||persisted[0].id!==entry.id)throw new Error("finished flight did not persist locally");
log.observe(sample({simTime:5,armed:false}));
if(log.entries.length!==1)throw new Error("repeated DISARMED samples duplicated a logbook entry");
console.log("Flight logbook observer test passed: FC ARMED/DISARM transitions, metrics, NAV-degraded duration and persistence.");
