import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",url=new URL(input,"http://127.0.0.1:4174"),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage();
const pause=ms=>page.evaluate(delay=>new Promise(resolve=>setTimeout(resolve,delay)),ms);
try{
  await page.setViewport({width:844,height:390,deviceScaleFactor:1});await page.goto(url.href,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready"),{timeout:30000});await page.waitForFunction(()=>document.body.classList.contains("solo-flight")&&document.querySelector("#playerModeButton")&&document.querySelector("#footFire")&&document.querySelector("#soloLeft")&&document.querySelector("#soloRight"),{timeout:8000});
  const initial=await page.$eval("#viewport",v=>v.dataset.playerMode);if(initial!=="drone")throw new Error(`webdriver must preserve drone default: ${initial}`);
  await page.click("#playerModeButton");await page.waitForFunction(()=>document.body.classList.contains("on-foot-mode")&&document.querySelector("#viewport")?.dataset.playerMode==="foot",{timeout:3000});
  const ui=await page.evaluate(()=>({left:getComputedStyle(document.querySelector("#soloLeft")).display,right:getComputedStyle(document.querySelector("#soloRight")).display,leftLabel:document.querySelector("#soloLeft span")?.textContent,rightLabel:document.querySelector("#soloRight span")?.textContent,fire:getComputedStyle(document.querySelector("#footFire")).display,clearance:getComputedStyle(document.querySelector("#soloClearance")).display,life:Boolean(globalThis.__arondightRealWorld?.threeScene?.getObjectByName?.("WORLD_EXPERIENCE_LIFE"))}));
  if(ui.left==="none"||ui.right==="none"||ui.leftLabel!=="MOVE"||ui.rightLabel!=="LOOK"||ui.fire==="none"||ui.clearance!=="none"||ui.life)throw new Error(`dual-stick isolated WALK UI failed: ${JSON.stringify(ui)}`);
  const before=await page.$eval("#viewport",v=>({x:Number(v.dataset.footX),y:Number(v.dataset.footY),yaw:Number(v.dataset.footYaw||0),droneShots:Number(v.dataset.fireShots||0),footShots:Number(v.dataset.footShots||0)}));
  await page.evaluate(()=>{const el=document.querySelector("#soloLeft"),r=el.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;el.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:601,pointerType:"touch",clientX:x,clientY:y,button:0}));el.dispatchEvent(new PointerEvent("pointermove",{bubbles:true,cancelable:true,pointerId:601,pointerType:"touch",clientX:x,clientY:y-r.height*.30,button:0}));});await pause(350);await page.evaluate(()=>document.querySelector("#soloLeft").dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:601,pointerType:"touch",button:0})));
  const moved=await page.$eval("#viewport",v=>({x:Number(v.dataset.footX),y:Number(v.dataset.footY)}));if(Math.hypot(moved.x-before.x,moved.y-before.y)<.25)throw new Error(`left WALK stick did not move pedestrian: ${JSON.stringify({before,moved})}`);
  await page.evaluate(()=>{const el=document.querySelector("#soloRight"),r=el.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;el.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:602,pointerType:"touch",clientX:x,clientY:y,button:0}));el.dispatchEvent(new PointerEvent("pointermove",{bubbles:true,cancelable:true,pointerId:602,pointerType:"touch",clientX:x+r.width*.30,clientY:y,button:0}));});await pause(350);await page.evaluate(()=>document.querySelector("#soloRight").dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:602,pointerType:"touch",button:0})));
  const looked=await page.$eval("#viewport",v=>Number(v.dataset.footYaw||0));if(Math.abs(looked-before.yaw)<.12)throw new Error(`right WALK stick did not look: ${JSON.stringify({before:before.yaw,looked})}`);
  await page.evaluate(()=>{const v=document.querySelector("#viewport"),r=v.getBoundingClientRect();v.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:603,pointerType:"touch",clientX:r.left+r.width*.5,clientY:r.top+r.height*.5,button:0}));v.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:603,pointerType:"touch",button:0}));});await pause(180);const afterBackground=await page.$eval("#viewport",v=>Number(v.dataset.fireShots||0));if(afterBackground!==before.droneShots)throw new Error(`WALK background touch leaked into drone fire: ${before.droneShots} -> ${afterBackground}`);
  await page.evaluate(()=>{const b=document.querySelector("#footFire"),r=b.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;b.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:604,pointerType:"touch",clientX:x,clientY:y,button:0}));b.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:604,pointerType:"touch",clientX:x,clientY:y,button:0}));});await page.waitForFunction(n=>Number(document.querySelector("#viewport")?.dataset.footShots||0)>n,{timeout:3000},before.footShots);const afterFire=await page.$eval("#viewport",v=>({foot:Number(v.dataset.footShots||0),drone:Number(v.dataset.fireShots||0)}));if(afterFire.drone!==before.droneShots)throw new Error(`foot FIRE leaked into drone projectile system: ${JSON.stringify({before,afterFire})}`);
  await page.click("#playerModeButton");await page.waitForFunction(()=>!document.body.classList.contains("on-foot-mode")&&document.querySelector("#viewport")?.dataset.playerMode==="drone",{timeout:3000});
  console.log("Isolated WALK browser smoke passed: two visible sticks, left move, right look, explicit foot fire, no drone touch/fire leak, no duplicate life layer.");
}finally{await browser.close();}
