import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage(),cdp=await page.createCDPSession();
await page.evaluateOnNewDocument(()=>{
  const state={axes:[0,0,0,0],buttons:Array(17).fill(0)},pad={id:"Xbox Wireless Controller (Vendor: 045e Product: 0b13)",index:0,mapping:"standard",connected:true,timestamp:0,get axes(){return state.axes;},get buttons(){return state.buttons.map(value=>({pressed:value>.5,touched:value>0,value}));}};
  Object.defineProperty(navigator,"getGamepads",{configurable:true,value:()=>[pad]});globalThis.__fpsPad={axis(index,value){state.axes[index]=Math.max(-1,Math.min(1,Number(value)||0));},reset(){state.axes.fill(0);state.buttons.fill(0);}};
});
const pause=ms=>page.evaluate(delay=>new Promise(resolve=>setTimeout(resolve,delay)),ms),setAxes=(x,y)=>page.evaluate((a,b)=>{globalThis.__fpsPad.axis(2,a);globalThis.__fpsPad.axis(3,b);},x,y);

try{
  await page.setViewport({width:960,height:540,deviceScaleFactor:1,hasTouch:true});await page.goto(url.href,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&globalThis.__arondightWalkMode&&document.querySelector("#playerModeButton"),{timeout:30000});
  const cameraBeforeWalk=await page.evaluate(()=>{const button=document.querySelector("#soloCamera"),v=document.querySelector("#viewport");for(let i=0;i<3&&v?.dataset.cameraMode!=="fpv";i++)button?.click();return{mode:v?.dataset.cameraMode,stored:localStorage.getItem("arondight45CameraMode")};});
  if(cameraBeforeWalk.mode!=="fpv"||cameraBeforeWalk.stored!=="fpv")throw new Error(`could not establish FPV regression baseline: ${JSON.stringify(cameraBeforeWalk)}`);
  await page.evaluate(()=>document.querySelector('#soloTopbar .phone-settings-button[data-control-profiles="drone+first-person"]')?.click());await page.waitForFunction(()=>document.querySelector('.phone-settings-dialog[data-control-profiles="drone+first-person"]')?.open,{timeout:3000});
  const droneProfileDefault=await page.evaluate(()=>({profile:document.querySelector('select[data-control-profile]')?.value,left:document.querySelector('[data-slider="left"]')?.value,fpsRows:[...document.querySelectorAll("[data-first-person-control]")].every(row=>row.hidden)}));if(droneProfileDefault.profile!=="drone"||!droneProfileDefault.fpsRows)throw new Error(`settings did not open on DRONE profile: ${JSON.stringify(droneProfileDefault)}`);
  await page.$eval('[data-slider="left"]',el=>{el.value="8";el.dispatchEvent(new Event("input",{bubbles:true}));});await page.evaluate(()=>document.querySelector('.phone-settings-dialog [data-close]')?.click());
  await page.evaluate(()=>globalThis.__arondightWalkMode.setMode("foot",{persist:false}));await page.waitForFunction(()=>{const v=document.querySelector("#viewport");return v?.dataset.playerMode==="foot"&&v.dataset.playerVehicleMode==="human"&&v.dataset.cameraMode==="walk"&&v.dataset.presentationCameraMode==="walk"&&v.dataset.walkCameraBase==="player-eye-origin-v1"&&v.dataset.walkCameraRotationOrigin==="player-eye-v1"&&v.dataset.walkCameraPresentation==="owned-pose-provider-v1"&&v.dataset.droneCameraPreference==="fpv"&&v.dataset.playerCameraPolicy==="walk-owned-eye-origin-v1";},{timeout:5000});
  await page.evaluate(()=>document.querySelector('#soloTopbar .phone-settings-button[data-control-profiles="drone+first-person"]')?.click());await page.waitForFunction(()=>document.querySelector('.phone-settings-dialog[data-control-profiles="drone+first-person"]')?.open&&document.querySelector('select[data-control-profile]')?.value==="first-person",{timeout:3000});
  const fpsProfileDefault=await page.evaluate(()=>({profile:document.querySelector('select[data-control-profile]')?.value,left:document.querySelector('[data-slider="left"]')?.value,right:document.querySelector('[data-slider="right"]')?.value,horizontal:document.querySelector('[data-slider="look-horizontal"]')?.value,vertical:document.querySelector('[data-slider="look-vertical"]')?.value,deadzone:document.querySelector('[data-slider="look-deadzone"]')?.value,assist:document.querySelector('[data-slider="aim-assist"]')?.value,invertVertical:document.querySelector("[data-invert-right-vertical]")?.checked,droneRows:[...document.querySelectorAll("[data-drone-control]")].every(row=>row.hidden)}));if(JSON.stringify(fpsProfileDefault)!==JSON.stringify({profile:"first-person",left:"1",right:"6",horizontal:"100",vertical:"100",deadzone:"6",assist:"55",invertVertical:false,droneRows:true}))throw new Error(`FIRST PERSON defaults/profile visibility wrong: ${JSON.stringify(fpsProfileDefault)}`);
  await page.$eval('[data-slider="left"]',el=>{el.value="4";el.dispatchEvent(new Event("input",{bubbles:true}));});await page.$eval('[data-slider="look-horizontal"]',el=>{el.value="73";el.dispatchEvent(new Event("input",{bubbles:true}));});await page.$eval('[data-slider="aim-assist"]',el=>{el.value="42";el.dispatchEvent(new Event("input",{bubbles:true}));});await page.click('[data-invert-right-horizontal]');
  await page.$eval('select[data-control-profile]',el=>{el.value="drone";el.dispatchEvent(new Event("change",{bubbles:true}));});const droneAfterFpsEdit=await page.evaluate(()=>({left:document.querySelector('[data-slider="left"]')?.value,invertLeft:document.querySelector("[data-invert-left-horizontal]")?.checked,drone:JSON.parse(localStorage.getItem("arondight45PhoneControlSettingsV5")||"{}"),fps:JSON.parse(localStorage.getItem("arondight45FirstPersonControlSettingsV1")||"{}")}));if(droneAfterFpsEdit.left!=="8"||droneAfterFpsEdit.invertLeft!==false||droneAfterFpsEdit.drone.leftFineness!==8||droneAfterFpsEdit.fps.moveFineness!==4||droneAfterFpsEdit.fps.horizontalLookSensitivityPercent!==73||droneAfterFpsEdit.fps.aimAssistStrengthPercent!==42||droneAfterFpsEdit.fps.invertLookHorizontal!==true)throw new Error(`DRONE/FIRST PERSON storage crossed profiles: ${JSON.stringify(droneAfterFpsEdit)}`);
  await page.$eval('select[data-control-profile]',el=>{el.value="first-person";el.dispatchEvent(new Event("change",{bubbles:true}));});const fpsAfterRoundTrip=await page.evaluate(()=>({left:document.querySelector('[data-slider="left"]')?.value,horizontal:document.querySelector('[data-slider="look-horizontal"]')?.value,assist:document.querySelector('[data-slider="aim-assist"]')?.value,invert:document.querySelector("[data-invert-right-horizontal]")?.checked}));if(JSON.stringify(fpsAfterRoundTrip)!==JSON.stringify({left:"4",horizontal:"73",assist:"42",invert:true}))throw new Error(`FIRST PERSON profile did not survive dropdown round-trip: ${JSON.stringify(fpsAfterRoundTrip)}`);await page.click('.phone-settings-dialog [data-reset]');const resetIsolation=await page.evaluate(()=>({drone:JSON.parse(localStorage.getItem("arondight45PhoneControlSettingsV5")||"{}"),fps:JSON.parse(localStorage.getItem("arondight45FirstPersonControlSettingsV1")||"{}")}));if(resetIsolation.drone.leftFineness!==8||resetIsolation.fps.moveFineness!==1||resetIsolation.fps.aimAssistStrengthPercent!==55)throw new Error(`FIRST PERSON reset crossed into DRONE: ${JSON.stringify(resetIsolation)}`);await page.click('.phone-settings-dialog [data-close]');
  await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.walkControllerFamily==="xbox-standard",{timeout:2000});const contract=await page.$eval("#viewport",v=>({profile:v.dataset.walkControlProfile,settingsProfile:v.dataset.walkSettingsProfile,look:v.dataset.walkLookModel,curve:v.dataset.walkControllerCurve,integration:v.dataset.walkControllerIntegration,controllerFamily:v.dataset.walkControllerFamily,deadzone:Number(v.dataset.walkLookDeadzonePercent),assistPercent:Number(v.dataset.walkAimAssistPercent),assist:v.dataset.walkAimAssist,bob:v.dataset.walkViewBob,shake:v.dataset.walkCameraShake,pitchRange:v.dataset.walkPitchRange,pitchLimit:Number(v.dataset.walkPitchLimitDeg),altitude:v.dataset.walkAltitudeInput,altitudeLock:v.dataset.fpsAltitudeLock,camera:v.dataset.cameraMode,presentationCamera:v.dataset.presentationCameraMode,cameraBase:v.dataset.walkCameraBase,rotationOrigin:v.dataset.walkCameraRotationOrigin,cameraPresentation:v.dataset.walkCameraPresentation,cameraFov:Number(v.dataset.walkCameraFovDeg),cameraPreference:v.dataset.droneCameraPreference,cameraPolicy:v.dataset.playerCameraPolicy,storedCamera:localStorage.getItem("arondight45CameraMode")}));
  if(contract.profile!=="cod-dynamic-assist-bob-v7"||contract.settingsProfile!=="first-person-independent-v1"||contract.look!=="fps-balanced-dynamic-v7"||contract.curve!=="radial-precision-centre-fast-edge-v2"||contract.integration!=="analytic-wall-clock-catchup-v1"||contract.controllerFamily!=="xbox-standard"||contract.deadzone!==6||contract.assistPercent!==55||contract.assist!=="friction+input-tracking-xbox-touch-v2"||contract.bob!=="bounded-stride-v1"||contract.shake!=="shot-impulse-damped-v1"||contract.pitchRange!=="near-vertical-178deg-v1"||contract.pitchLimit<89||contract.altitude!=="locked-eye-height-v1"||contract.altitudeLock!=="eye-fixed-v1"||contract.camera!=="walk"||contract.presentationCamera!=="walk"||contract.cameraBase!=="player-eye-origin-v1"||contract.rotationOrigin!=="player-eye-v1"||contract.cameraPresentation!=="owned-pose-provider-v1"||contract.cameraFov<40||contract.cameraFov>80||contract.cameraPreference!=="fpv"||contract.cameraPolicy!=="walk-owned-eye-origin-v1"||contract.storedCamera!=="fpv")throw new Error(`FPS controller contract missing: ${JSON.stringify(contract)}`);

  await page.evaluate(()=>globalThis.__arondightWalkMode.setPose({x:0,y:0,yaw:0,pitch:-.65}));await page.waitForFunction(()=>{const v=document.querySelector("#viewport"),yaw=Number(v?.dataset.walkYaw),pitch=Number(v?.dataset.walkPitch);return Number.isFinite(yaw)&&Number.isFinite(pitch)&&Math.abs(yaw)<.01&&Math.abs(pitch+.65)<.02;},{timeout:2000});const deadzoneBefore=await page.$eval("#viewport",v=>({yaw:Number(v.dataset.walkYaw),pitch:Number(v.dataset.walkPitch)}));await setAxes(.04,.04);await pause(260);const deadzoneAfter=await page.$eval("#viewport",v=>({yaw:Number(v.dataset.walkYaw),pitch:Number(v.dataset.walkPitch)}));if(Math.hypot(deadzoneAfter.yaw-deadzoneBefore.yaw,deadzoneAfter.pitch-deadzoneBefore.pitch)>.018)throw new Error(`radial deadzone drifted: ${JSON.stringify({deadzoneBefore,deadzoneAfter})}`);

  const balancedBefore={...deadzoneAfter,startedAt:await page.evaluate(()=>performance.now())};await setAxes(.58,-.58);await page.waitForFunction(before=>{const v=document.querySelector("#viewport"),yaw=Math.abs(Number(v?.dataset.walkYaw)-before.yaw),pitch=Math.abs(Number(v?.dataset.walkPitch)-before.pitch);return yaw>=.45&&pitch>=.38;},{timeout:1200},balancedBefore);const balancedAfter=await page.$eval("#viewport",v=>({yaw:Number(v.dataset.walkYaw),pitch:Number(v.dataset.walkPitch),elapsedMs:performance.now()}));await setAxes(0,0);balancedAfter.elapsedMs-=balancedBefore.startedAt;const yawTravel=Math.abs(balancedAfter.yaw-balancedBefore.yaw),pitchTravel=Math.abs(balancedAfter.pitch-balancedBefore.pitch),ratio=pitchTravel/Math.max(.001,yawTravel);if(yawTravel<.45||pitchTravel<.38||ratio<.72||ratio>1.08||balancedAfter.elapsedMs>1200)throw new Error(`horizontal/vertical response is not balanced: ${JSON.stringify({balancedBefore,balancedAfter,yawTravel,pitchTravel,ratio})}`);await pause(180);const released=await page.$eval("#viewport",v=>({yaw:Number(v.dataset.walkYaw),pitch:Number(v.dataset.walkPitch)}));await pause(180);const releasedAgain=await page.$eval("#viewport",v=>({yaw:Number(v.dataset.walkYaw),pitch:Number(v.dataset.walkPitch)}));if(Math.hypot(releasedAgain.yaw-released.yaw,releasedAgain.pitch-released.pitch)>.055)throw new Error(`look acceleration did not stop after stick release: ${JSON.stringify({released,releasedAgain})}`);

  await page.evaluate(()=>globalThis.__arondightWalkMode.setPose({x:0,y:0,yaw:0,pitch:0}));const verticalBefore=await page.$eval("#viewport",v=>({z:Number((v.dataset.walkPosition||"").split(",")[2]),agl:Number(document.querySelector("#soloClearance")?.dataset.targetAglM)}));await setAxes(0,-1);await pause(850);const up=await page.$eval("#viewport",v=>({pitch:Number(v.dataset.walkPitch),z:Number((v.dataset.walkPosition||"").split(",")[2]),agl:Number(document.querySelector("#soloClearance")?.dataset.targetAglM),origin:v.dataset.walkCameraOrigin,direction:(v.dataset.walkCameraDirection||"").split(",").map(Number)}));await setAxes(0,1);await pause(1250);const down=await page.$eval("#viewport",v=>({pitch:Number(v.dataset.walkPitch),z:Number((v.dataset.walkPosition||"").split(",")[2]),agl:Number(document.querySelector("#soloClearance")?.dataset.targetAglM),origin:v.dataset.walkCameraOrigin,direction:(v.dataset.walkCameraDirection||"").split(",").map(Number)}));await setAxes(0,0);if(up.pitch<1.52||down.pitch> -1.52||up.direction[2]<.998||down.direction[2]>-.998||Math.abs(Number(up.origin.split(",")[2])-1.68)>.01||Math.abs(Number(down.origin.split(",")[2])-1.68)>.01||Math.abs(up.z-verticalBefore.z)>.001||Math.abs(down.z-verticalBefore.z)>.001||Math.abs(up.agl-verticalBefore.agl)>.001||Math.abs(down.agl-verticalBefore.agl)>.001)throw new Error(`vertical FPS eye-origin look changed altitude or failed to reach near-vertical limits: ${JSON.stringify({verticalBefore,up,down})}`);

  const target=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,scene=b.threeScene,v=document.querySelector("#viewport"),before=Number(v.dataset.playerSceneIndex||0),isolated=new Set();let source=null;globalThis.__fpsAimIsolation=[];scene.traverse(node=>{if(!source&&node.isMesh&&node.geometry&&node.material)source=node;const kind=String(node?.userData?.worldPopulationKind||"");if(!node?.isMesh||!(kind==="person"||kind==="police-drone"||kind==="vs-player"))return;const id=String(node.userData.worldPopulationId||node.userData.worldProceduralId||node.userData.vsPlayerId||"");let root=node;for(let current=node.parent;current&&current!==scene;current=current.parent){const data=current.userData||{},currentId=String(data.worldPopulationId||data.worldProceduralId||data.vsPlayerId||"");if((id&&currentId===id)||data.wantedPoliceDrone||data.vsHumanAvatar)root=current;}if(isolated.has(root))return;isolated.add(root);globalThis.__fpsAimIsolation.push({node:root,previous:root.userData.worldPopulationClone});root.userData.worldPopulationClone=true;});if(!source)throw new Error("no mesh available for aim target");const mesh=source.clone(false),angle=3.2*Math.PI/180,distance=18;mesh.name="FPS_AIM_ASSIST_TARGET";mesh.position.set(Math.sin(angle)*distance,Math.cos(angle)*distance,.44);mesh.rotation.set(0,0,0);mesh.scale.set(.65,.65,.65);mesh.visible=true;mesh.userData={worldPopulationKind:"person",worldPopulationId:"fps-assist-target",worldProceduralId:"fps-assist-target",worldPopulationClone:false};scene.add(mesh);b.buildingCollisionSnapshot=Object.freeze({hash:"fps-clear",footprintCount:0,prismCount:0,prisms:[]});return{before,isolated:globalThis.__fpsAimIsolation.length};});
  await page.waitForFunction(before=>Number(document.querySelector("#viewport")?.dataset.playerSceneIndex||0)>before,{timeout:6500},target.before);await page.evaluate(()=>globalThis.__arondightWalkMode.setPose({x:0,y:0,yaw:0,pitch:0}));await setAxes(.12,0);await page.waitForFunction(()=>{const v=document.querySelector("#viewport");return v?.dataset.walkAimAssistActive==="1"&&v.dataset.walkAimAssistTarget==="fps-assist-target";},{timeout:2500});const assisted=await page.$eval("#viewport",v=>({active:v.dataset.walkAimAssistActive,target:v.dataset.walkAimAssistTarget,strength:Number(v.dataset.walkAimAssistStrength),slowdown:Number(v.dataset.walkAimAssistSlowdown),tracking:Number(v.dataset.walkAimAssistTracking),yaw:Number(v.dataset.walkYaw)}));await setAxes(0,0);await pause(180);const idle=await page.$eval("#viewport",v=>({active:v.dataset.walkAimAssistActive,yaw:Number(v.dataset.walkYaw)}));if(assisted.active!=="1"||assisted.target!=="fps-assist-target"||assisted.strength<=0||!(assisted.slowdown<1)||assisted.tracking<=0||idle.active!=="0")throw new Error(`input-bound aim assist failed: ${JSON.stringify({target,assisted,idle})}`);

  await page.evaluate(()=>globalThis.__arondightWalkMode.setPose({x:0,y:0,yaw:0,pitch:0}));const touchBox=await page.$eval("#footLookZone",el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height};}),tx=touchBox.x+touchBox.w*.42,ty=touchBox.y+touchBox.h*.42;await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:tx,y:ty,id:921,radiusX:2,radiusY:2,force:1}]});await pause(30);await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:tx+10,y:ty,id:921,radiusX:2,radiusY:2,force:1}]});await page.waitForFunction(()=>{const v=document.querySelector("#viewport");return v?.dataset.walkTouchLookActive==="1"&&v.dataset.walkAimAssistInput==="touch-drag"&&v.dataset.walkAimAssistActive==="1";},{timeout:2500});const touchAssisted=await page.$eval("#viewport",v=>({source:v.dataset.walkAimAssistInput,active:v.dataset.walkAimAssistActive,touch:v.dataset.walkTouchLookActive,target:v.dataset.walkAimAssistTarget,strength:Number(v.dataset.walkAimAssistStrength),slowdown:Number(v.dataset.walkAimAssistSlowdown),tracking:Number(v.dataset.walkAimAssistTracking),look:v.dataset.walkLookInput,yaw:Number(v.dataset.walkYaw)}));await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await page.waitForFunction(()=>{const v=document.querySelector("#viewport");return v?.dataset.walkTouchLookActive==="0"&&v.dataset.walkAimAssistActive==="0";},{timeout:2500});const touchIdle=await page.$eval("#viewport",v=>({active:v.dataset.walkAimAssistActive,touch:v.dataset.walkTouchLookActive,yaw:Number(v.dataset.walkYaw)}));if(touchAssisted.source!=="touch-drag"||touchAssisted.active!=="1"||touchAssisted.touch!=="1"||touchAssisted.target!=="fps-assist-target"||touchAssisted.strength<=0||!(touchAssisted.slowdown<1)||touchAssisted.tracking<=0||touchAssisted.look!=="fps-touch-profiled-dynamic-v12"||touchIdle.active!=="0"||touchIdle.touch!=="0")throw new Error(`touch aim profile/assist failed: ${JSON.stringify({touchAssisted,touchIdle})}`);

  await page.evaluate(()=>{for(const item of globalThis.__fpsAimIsolation||[]){if(item.previous===undefined)delete item.node.userData.worldPopulationClone;else item.node.userData.worldPopulationClone=item.previous;}delete globalThis.__fpsAimIsolation;globalThis.__arondightWalkMode.setMode("drone",{persist:false});});await page.waitForFunction(()=>{const v=document.querySelector("#viewport");return v?.dataset.playerMode==="drone"&&v.dataset.cameraMode==="fpv"&&v.dataset.walkCameraBase==="drone-preference-v1"&&v.dataset.droneCameraPreference==="fpv"&&localStorage.getItem("arondight45CameraMode")==="fpv";},{timeout:3000});const cameraAfterWalk=await page.$eval("#viewport",v=>({mode:v.dataset.cameraMode,base:v.dataset.walkCameraBase,preference:v.dataset.droneCameraPreference,stored:localStorage.getItem("arondight45CameraMode")}));
  console.log(`FPS first-person browser smoke passed: independent DRONE/FIRST PERSON settings, Xbox radial deadzone/dynamic curve plus touch sensitivity, light input-only aim assist for Xbox and touch, owned player-eye camera origin independent of drone preference, balanced X/Y response, near-vertical pitch with fixed eye height, view-bob and shot-shake contracts: ${JSON.stringify({cameraBeforeWalk,droneProfileDefault,fpsProfileDefault,droneAfterFpsEdit,fpsAfterRoundTrip,resetIsolation,contract,yawTravel,pitchTravel,ratio,up,down,assisted,idle,touchAssisted,touchIdle,cameraAfterWalk})}`);
}finally{await browser.close();}
