import puppeteer from "puppeteer-core";

const executablePath=process.env.CHROME_BIN;if(!executablePath)throw Error("CHROME_BIN required");
const targetUrl=process.env.TARGET_URL||`https://kurzlernen.de/drone_simulator.html?fps-target-geometry-diag=${Date.now()}`;
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]});
const page=await browser.newPage(),pageErrors=[];page.on("pageerror",e=>{const t=String(e?.stack||e);pageErrors.push(t);console.error("PAGEERROR",t);});
const snap=()=>page.evaluate(()=>{const v=document.querySelector("#viewport"),w=globalThis.__arondightWalkMode;return{mode:w?.mode||"",dead:!!w?.dead,aim:v?.dataset.walkScreenAimActive||"",pointer:v?.dataset.walkScreenAimPointer||"",release:v?.dataset.walkScreenAimRelease||"",shots:Number(v?.dataset.walkEnhancedShots||0),bursts:Number(v?.dataset.walkAutoFireBursts||0),hits:Number(v?.dataset.worldPopulationHits||0),rag:Number(v?.dataset.worldRagdollSpawns||0),exp:Number(v?.dataset.worldCarExplosionSpawns||0),stars:Number(v?.dataset.wantedStars||0),assign:Number(v?.dataset.combatHitStackAssignments||0)};});
try{
  await page.setUserAgent("Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148");await page.setViewport({width:844,height:390,deviceScaleFactor:1,hasTouch:true,isMobile:true});
  await page.goto(targetUrl,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&globalThis.__arondightWalkMode&&globalThis.__arondightFootWeapons&&globalThis.__arondightRealWorld?.threeScene,{timeout:30000});
  await page.evaluate(()=>globalThis.__arondightWalkMode.setMode("foot",{persist:false}));await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.playerMode==="foot"&&document.querySelector("#footLookZone"),{timeout:5000});
  await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport");v.dataset.worldMode="real";b.active=true;b.originLon=9;b.originLat=47;});await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.worldProceduralPopulation==="1",{timeout:10000});
  const setup=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,scene=b.threeScene,seen=new Map();scene.traverse(node=>{if(!node?.isMesh)return;const id=String(node.userData?.worldPopulationId||""),kind=String(node.userData?.worldPopulationKind||"");if(id&&["person","car","bus"].includes(kind)&&!seen.has(id))seen.set(id,{id,kind,mesh:node});node.raycast=()=>{};});const all=[...seen.values()],sequence=[...all.filter(x=>x.kind==="person").slice(0,10),...all.filter(x=>x.kind==="car").slice(0,6),...all.filter(x=>x.kind==="bus").slice(0,3)];if(sequence.length!==19)throw Error(`inventory ${sequence.length}`);globalThis.__fpsGeom={sequence,current:null,moveTimer:0};b.active=false;return{count:sequence.length};});console.log("FPS_GEOM inventory",setup.count);
  const arm=index=>page.evaluate(index=>{const d=globalThis.__fpsGeom,b=globalThis.__arondightRealWorld,w=globalThis.__arondightWalkMode,scene=b.threeScene,v=document.querySelector("#viewport"),rec=d.sequence[index];if(d.current){scene.remove(d.current);d.current=null;}const target=rec.mesh.clone(false),cp=Math.cos(Number(w.pitch)||0),dx=Math.sin(Number(w.yaw)||0)*cp,dy=Math.cos(Number(w.yaw)||0)*cp,dz=Math.sin(Number(w.pitch)||0),ox=Number(w.position?.x)||0,oy=Number(w.position?.y)||0,oz=Number(w.position?.z)||1.68;target.name=`FPS_GEOM_${rec.kind}_${index}`;target.position.set(ox+dx*3,oy+dy*3,oz+dz*3);target.quaternion.identity();target.scale.setScalar(rec.kind==="person"?5:rec.kind==="car"?2:1.2);target.visible=true;target.frustumCulled=false;target.userData={...rec.mesh.userData,worldPopulationKind:rec.kind,worldPopulationId:rec.id,worldProceduralId:rec.id,flightFireIgnore:false};scene.add(target);target.updateMatrixWorld(true);d.current=target;const key=rec.kind==="person"?"worldRagdollSpawns":"worldCarExplosionSpawns";return{id:rec.id,kind:rec.kind,key,before:Number(v.dataset[key]||0),geom:String(target.geometry?.type||""),name:String(rec.mesh.name||"")};},index);
  let current=await arm(0),last=await snap();const p=await page.$eval("#footLookZone",el=>{const r=el.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2};});await page.$eval("#footLookZone",(el,p)=>{el.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:882,pointerType:"touch",button:0,buttons:1,isPrimary:true,clientX:p.x,clientY:p.y}));let n=0;globalThis.__fpsGeom.moveTimer=setInterval(()=>{n++;el.dispatchEvent(new PointerEvent("pointermove",{bubbles:true,cancelable:true,pointerId:882,pointerType:"touch",button:-1,buttons:1,isPrimary:true,clientX:p.x+(n%5)-2,clientY:p.y+((n*2)%5)-2}));},37);},p);
  for(let n=0;n<19;n++){if(n)current=await arm(n);const timeout=current.kind==="person"?2600:current.kind==="car"?4400:6200;try{await page.waitForFunction(({key,before})=>Number(document.querySelector("#viewport")?.dataset[key]||0)>before,{timeout},current);}catch{const s=await snap();throw Error(`FPS_GEOM STOP ${n+1}/19 ${JSON.stringify(current)} previous=${JSON.stringify(last)} state=${JSON.stringify(s)} errors=${JSON.stringify(pageErrors.slice(-5))}`);}const s=await snap();console.log(`FPS_GEOM OK ${n+1}/19 kind=${current.kind} geom=${current.geom} sourceName=${current.name} shots=${s.shots} bursts=${s.bursts} hits=${s.hits} aim=${s.aim}/${s.pointer} release=${s.release} errors=${pageErrors.length}`);if(s.shots<=last.shots||s.bursts<=last.bursts||s.aim!=="1"||!s.pointer)throw Error(`FPS_GEOM lifecycle stalled ${n+1}/19 prev=${JSON.stringify(last)} state=${JSON.stringify(s)}`);last=s;}
  const finalState=await snap();if(pageErrors.length)throw Error(`FPS_GEOM page errors ${JSON.stringify(pageErrors.slice(-5))}`);console.log("FPS_GEOM PASS",JSON.stringify(finalState));
}finally{try{await page.$eval("#footLookZone",el=>{const d=globalThis.__fpsGeom;if(d?.moveTimer)clearInterval(d.moveTimer);if(d?.current)d.current.parent?.remove(d.current);el.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:882,pointerType:"touch",button:0,buttons:0,isPrimary:true}));});}catch{}await browser.close();}
