import puppeteer from "puppeteer-core";

const executablePath=process.env.CHROME_BIN;if(!executablePath)throw Error("CHROME_BIN required");
const targetUrl=process.env.TARGET_URL||`https://kurzlernen.de/drone_simulator.html?fps-target-autofire-diag=${Date.now()}`;
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]});
const page=await browser.newPage(),pageErrors=[];page.on("pageerror",e=>{const text=String(e?.stack||e);pageErrors.push(text);console.error("PAGEERROR",text);});
const snap=()=>page.evaluate(()=>{const v=document.querySelector("#viewport"),w=globalThis.__arondightWalkMode,b=globalThis.__arondightRealWorld;return{mode:w?.mode||"",dead:!!w?.dead,screenAim:v?.dataset.walkScreenAimActive||"",screenPointer:v?.dataset.walkScreenAimPointer||"",fireResult:v?.dataset.walkTouchFireResult||"",bursts:Number(v?.dataset.walkAutoFireBursts||0),shots:Number(v?.dataset.walkEnhancedShots||0),populationHits:Number(v?.dataset.worldPopulationHits||0),ragdollSpawns:Number(v?.dataset.worldRagdollSpawns||0),ragdollPool:Number(v?.dataset.worldRagdollPool||0),explosionSpawns:Number(v?.dataset.worldCarExplosionSpawns||0),explosionPool:Number(v?.dataset.worldCarExplosionPool||0),assignments:Number(v?.dataset.combatHitStackAssignments||0),stableFrames:Number(v?.dataset.combatHitStackStableFrames||0),registry:v?.dataset.combatHitStackRegistry||"",stars:Number(v?.dataset.wantedStars||0),vsLocalDead:!!b?.vsLocalDead};});
try{
  await page.setUserAgent("Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148");
  await page.setViewport({width:844,height:390,deviceScaleFactor:1,hasTouch:true,isMobile:true});
  await page.goto(targetUrl,{waitUntil:"load",timeout:30000});
  await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&globalThis.__arondightWalkMode&&globalThis.__arondightFootWeapons&&globalThis.__arondightRealWorld?.threeScene,{timeout:30000});
  await page.evaluate(()=>globalThis.__arondightWalkMode.setMode("foot",{persist:false}));
  await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.playerMode==="foot"&&document.querySelector("#footLookZone"),{timeout:5000});
  await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport");v.dataset.worldMode="real";b.active=true;b.originLon=9;b.originLat=47;});
  await page.waitForFunction(()=>{const v=document.querySelector("#viewport");return v?.dataset.worldProceduralPopulation==="1"&&v?.dataset.combatHitStackRegistry==="marker-union-v2"&&Number(v?.dataset.combatHitStackStableFrames||0)>=12;},{timeout:10000});
  const setup=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,scene=b.threeScene,seen=new Map();scene.traverse(node=>{if(node?.isMesh)node.raycast=()=>{};const id=String(node?.userData?.worldPopulationId||""),kind=String(node?.userData?.worldPopulationKind||"");if(node?.isMesh&&id&&["person","car","bus"].includes(kind)&&!seen.has(id))seen.set(id,{id,kind,mesh:node});});const all=[...seen.values()],sequence=[...all.filter(x=>x.kind==="person").slice(0,10),...all.filter(x=>x.kind==="car").slice(0,6),...all.filter(x=>x.kind==="bus").slice(0,3)];if(sequence.length!==19)throw Error(`inventory ${JSON.stringify({person:all.filter(x=>x.kind==="person").length,car:all.filter(x=>x.kind==="car").length,bus:all.filter(x=>x.kind==="bus").length})}`);globalThis.__fpsTargetDiag={sequence,current:null,moveTimer:0};b.active=false;return{count:sequence.length};});
  console.log("FPS_TARGET inventory",JSON.stringify(setup));
  const arm=async index=>page.evaluate(index=>{globalThis.__arondightWantedSystem?.clear?.("diagnostic");globalThis.__arondightPlayerDamageModel?.reset?.();const d=globalThis.__fpsTargetDiag,v=document.querySelector("#viewport"),rec=d.sequence[index];if(!rec)throw Error(`missing target ${index}`);if(d.current)d.current.mesh.raycast=()=>{};const mesh=rec.mesh;mesh.userData.flightFireIgnore=false;mesh.visible=true;mesh.raycast=function(raycaster,intersections){const distance=.02,point=raycaster.ray.origin.clone().addScaledVector(raycaster.ray.direction,distance);intersections.push({distance,point,object:this,face:null,faceIndex:0});};d.current=rec;const key=rec.kind==="person"?"worldRagdollSpawns":"worldCarExplosionSpawns";return{id:rec.id,kind:rec.kind,key,before:Number(v.dataset[key]||0)};},index);
  let current=await arm(0),last=await snap();
  const point=await page.$eval("#footLookZone",el=>{const r=el.getBoundingClientRect();return{x:r.left+r.width*.55,y:r.top+r.height*.48};});
  await page.$eval("#footLookZone",(el,p)=>{const id=881;el.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",button:0,buttons:1,isPrimary:true,clientX:p.x,clientY:p.y}));let n=0;globalThis.__fpsTargetDiag.moveTimer=setInterval(()=>{n++;el.dispatchEvent(new PointerEvent("pointermove",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",button:-1,buttons:1,isPrimary:true,clientX:p.x+(n%7)-3,clientY:p.y+((n*3)%7)-3}));},37);},point);
  for(let n=0;n<19;n++){
    if(n)current=await arm(n);const timeout=current.kind==="person"?2200:current.kind==="car"?3600:current.kind==="bus"?5200:2500;
    try{await page.waitForFunction(({key,before})=>Number(document.querySelector("#viewport")?.dataset[key]||0)>before,{timeout},current);}catch{const state=await snap();throw Error(`FPS_TARGET STOP target=${n+1}/19 kind=${current.kind} id=${current.id} previous=${JSON.stringify(last)} state=${JSON.stringify(state)} pageErrors=${JSON.stringify(pageErrors.slice(-5))}`);}
    const state=await snap();console.log(`FPS_TARGET OK target=${n+1}/19 kind=${current.kind} shots=${state.shots} bursts=${state.bursts} popHits=${state.populationHits} rag=${state.ragdollSpawns}/${state.ragdollPool} exp=${state.explosionSpawns}/${state.explosionPool} errors=${pageErrors.length}`);if(state.mode!=="foot"||state.dead||state.vsLocalDead||state.screenAim!=="1"||!state.screenPointer)throw Error(`FPS_TARGET INPUT changed at ${n+1}/19 ${JSON.stringify(state)}`);if(state.shots<=last.shots||state.bursts<=last.bursts)throw Error(`FPS_TARGET cadence stalled at ${n+1}/19 previous=${JSON.stringify(last)} state=${JSON.stringify(state)}`);last=state;
  }
  const finalState=await snap();if(pageErrors.length)throw Error(`FPS_TARGET page errors after pass ${JSON.stringify(pageErrors.slice(-5))}`);console.log("FPS_TARGET PASS",JSON.stringify(finalState));
}finally{try{await page.$eval("#footLookZone",el=>{const d=globalThis.__fpsTargetDiag;if(d?.moveTimer)clearInterval(d.moveTimer);el.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:881,pointerType:"touch",button:0,buttons:0,isPrimary:true}));});}catch{}await browser.close();}
