import puppeteer from "puppeteer-core";
const input=process.argv[2]||"https://kurzlernen.de/drone_simulator.html";const executablePath=process.env.CHROME_BIN;if(!executablePath)throw Error("CHROME_BIN required");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage(),errors=[];page.on("pageerror",e=>errors.push(String(e?.stack||e)));const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const state=()=>page.evaluate(()=>{const v=document.querySelector("#viewport"),w=globalThis.__arondightWalkMode,p=globalThis.__arondightPlayerDamageModel,s=globalThis.__arondightWantedSystem?.state||{};return{walkDead:Boolean(w?.dead),hp:Number(p?.hp??-1),dead:Boolean(p?.dead),aim:v?.dataset.walkScreenAimActive||"",capture:v?.dataset.walkScreenAimCaptureState||"",fire:v?.dataset.walkTouchFireResult||"",bursts:Number(v?.dataset.walkAutoFireBursts||0),shots:Number(v?.dataset.walkEnhancedShots||0),hits:Number(v?.dataset.wantedPoliceHits||0),kills:Number(v?.dataset.wantedPoliceKills||s.policeKills||0),critical:Number(v?.dataset.wantedPoliceCritical||0),stars:Number(v?.dataset.wantedStars||s.stars||0),police:Number(v?.dataset.wantedPoliceActive||s.policeActive||0),damage:Number(v?.dataset.wantedPoliceDamage||0)};});
try{
 await page.setUserAgent("Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148");await page.setViewport({width:844,height:390,deviceScaleFactor:1,hasTouch:true,isMobile:true});await page.goto(input,{waitUntil:"load",timeout:40000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&globalThis.__arondightWantedSystem&&globalThis.__arondightFootWeapons&&globalThis.__arondightWalkMode,{timeout:40000});
 const setup=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,w=globalThis.__arondightWalkMode,v=document.querySelector("#viewport"),wanted=globalThis.__arondightWantedSystem;w.setMode?.("foot",{persist:false,reason:"police-target-drag-diag"});w.setPose?.({x:0,y:0,z:0,yaw:0,pitch:0});v.dataset.worldMode="real";b.active=true;b.originLon=9;b.originLat=47;for(let i=0;i<16;i++)wanted.reportCrime?.({id:`diag-crime-${i}`,kind:"person",severity:5,revealPlayer:true});const z=document.getElementById("footLookZone").getBoundingClientRect();return{x:z.left+z.width*.55,y:z.top+z.height*.48};});
 await page.waitForFunction(()=>Number(document.querySelector("#viewport")?.dataset.wantedPoliceActive||0)>0&&Number(document.querySelector("#viewport")?.dataset.wantedStars||0)>=4,{timeout:12000});
 const cdp=await page.createCDPSession();let dragging=true,step=0;await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:setup.x,y:setup.y,id:9,radiusX:4,radiusY:4,force:.7}]});const mover=(async()=>{while(dragging){step++;await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:setup.x+(step%5)-2,y:setup.y+((step*2)%5)-2,id:9,radiusX:4,radiusY:4,force:.7}]}).catch(()=>{});await sleep(34);}})();
 let failure=null,lastShots=(await state()).shots;
 for(let cycle=0;cycle<8;cycle++){
  const armed=await page.evaluate(()=>{const wanted=globalThis.__arondightWantedSystem,v=document.querySelector("#viewport"),drone=wanted?.drones?.find?.(d=>d?.active&&d?.root?.visible!==false);if(!drone)return null;let mesh=null;drone.root.traverse?.(n=>{if(!mesh&&n?.isMesh)mesh=n;});if(!mesh)return null;mesh.userData.flightFireIgnore=false;mesh.raycast=function(raycaster,out){const distance=.025,point=raycaster.ray.origin.clone().addScaledVector(raycaster.ray.direction,distance);out.push({distance,point,object:this,face:null,faceIndex:0});};return{index:drone.index,before:Number(v.dataset.wantedPoliceKills||wanted.state?.policeKills||0)};});
  if(!armed){await sleep(450);cycle--;continue;}const deadline=performance.now()+7000;let killed=false;while(performance.now()<deadline){await sleep(60);const s=await state();if(s.kills>armed.before){killed=true;console.log(`POLICE kill ${cycle+1}/8 ${JSON.stringify(s)}`);lastShots=s.shots;break;}if(errors.length||s.walkDead||s.dead||s.aim==="0"){failure={cycle:cycle+1,armed,state:s,errors:[...errors]};break;}if(s.shots===lastShots&&s.fire==="gated"){await sleep(260);const c=await state();if(c.shots===lastShots){failure={cycle:cycle+1,armed,state:c,errors:[...errors],gated:true};break;}}if(s.shots>lastShots)lastShots=s.shots;}if(failure)break;if(!killed){failure={cycle:cycle+1,armed,state:await state(),errors:[...errors],timeout:true};break;}
 }
 if(failure){const manual=await page.evaluate(()=>{const r=document.querySelector("#viewport").getBoundingClientRect();try{return{result:Boolean(globalThis.__arondightFootWeapons.fireAt({clientX:r.left+r.width*.15,clientY:r.top+r.height*.15,source:"police-diag-off-target"})),error:""};}catch(e){return{result:false,error:String(e?.stack||e)};}});failure.manual=manual;failure.after=await state();console.log(`POLICE_ROOT_FAILURE ${JSON.stringify(failure)}`);}else console.log(`POLICE_NO_FAILURE ${JSON.stringify(await state())}`);
 dragging=false;await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]}).catch(()=>{});await mover;if(errors.length)throw Error(`TARGET_EXCEPTION ${errors.join(" | ")}`);if(failure?.dead||failure?.state?.dead||failure?.state?.walkDead)throw Error(`PLAYER_DEATH ${JSON.stringify(failure)}`);if(failure)throw Error(`POLICE_TARGET_FAILURE ${JSON.stringify(failure)}`);throw Error(`police target path stayed alive: ${JSON.stringify(await state())}`);
}finally{await browser.close();}
