import puppeteer from "puppeteer-core";

const input=process.argv[2]||"https://kurzlernen.de/drone_simulator.html";
const executablePath=process.env.CHROME_BIN;if(!executablePath)throw Error("CHROME_BIN required");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]});
const page=await browser.newPage(),errors=[];page.on("pageerror",e=>errors.push(String(e?.stack||e)));const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const state=()=>page.evaluate(()=>{const v=document.querySelector("#viewport"),w=globalThis.__arondightWalkMode,p=globalThis.__arondightPlayerDamageModel,s=globalThis.__arondightWantedSystem?.state||{};return{walkDead:Boolean(w?.dead),hp:Number(p?.hp??-1),dead:Boolean(p?.dead),aim:v?.dataset.walkScreenAimActive||"",capture:v?.dataset.walkScreenAimCaptureState||"",release:v?.dataset.walkScreenAimRelease||"",fire:v?.dataset.walkTouchFireResult||"",bursts:Number(v?.dataset.walkAutoFireBursts||0),shots:Number(v?.dataset.walkEnhancedShots||0),populationHits:Number(v?.dataset.worldPopulationHits||0),ragdolls:Number(v?.dataset.worldRagdollSpawns||0),policeHits:Number(v?.dataset.wantedPoliceHits||0),policeKills:Number(v?.dataset.wantedPoliceKills||s.policeKills||0),stars:Number(v?.dataset.wantedStars||s.stars||0),police:Number(v?.dataset.wantedPoliceActive||s.policeActive||0),lastHitKind:v?.dataset.worldPopulationLastHit||"",fireVector:v?.dataset.walkWeaponFireVector||""};});
try{
 await page.setUserAgent("Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148");await page.setViewport({width:844,height:390,deviceScaleFactor:1,hasTouch:true,isMobile:true});await page.goto(input,{waitUntil:"load",timeout:40000});
 await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&globalThis.__arondightRealWorld?.threeScene&&globalThis.__arondightWalkMode&&globalThis.__arondightFootWeapons&&globalThis.__arondightWantedSystem,{timeout:40000});
 await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,w=globalThis.__arondightWalkMode,v=document.querySelector("#viewport");w.setMode?.("foot",{persist:false,reason:"actual-target-ray-diag"});v.dataset.worldMode="real";b.active=true;b.originLon=9;b.originLat=47;});
 await page.waitForFunction(()=>globalThis.__arondightWalkMode?.mode==="foot"&&document.querySelector("#viewport")?.dataset.worldProceduralPopulation==="1"&&Number(document.querySelector("#viewport")?.dataset.worldLifeVisible||0)>0,{timeout:12000});
 const populationIds=await page.evaluate(()=>{const scene=globalThis.__arondightRealWorld.threeScene,seen=new Map();scene.traverse(node=>{const id=String(node?.userData?.worldPopulationId||""),kind=String(node?.userData?.worldPopulationKind||"");if(id&&kind==="person"&&!seen.has(id))seen.set(id,{id,kind});});return[...seen.values()].slice(0,10);});
 if(populationIds.length<6)throw Error(`insufficient real person targets ${populationIds.length}`);
 const cdp=await page.createCDPSession();const viewRect=await page.$eval("#viewport",v=>{const r=v.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2};});
 let dragging=true,moveStep=0,currentTargetId=populationIds[0].id;
 const face=async(id,dist=4.5)=>page.evaluate(({id,dist})=>{const scene=globalThis.__arondightRealWorld.threeScene,w=globalThis.__arondightWalkMode;let root=null;scene.traverse(node=>{if(root)return;const own=String(node?.userData?.worldPopulationId||"");if(own===id){let r=node;while(r.parent&&String(r.parent?.userData?.worldPopulationId||"")===id)r=r.parent;root=r;}});if(!root||root.visible===false)return null;root.updateWorldMatrix?.(true,false);const p={x:0,y:0,z:0},wp=new (scene.constructor===Object?Object:globalThis.THREE?.Vector3||Object)();let x,y,z;if(root.getWorldPosition&&wp?.isVector3){root.getWorldPosition(wp);x=wp.x;y=wp.y;z=wp.z;}else{const q=root.position;x=Number(q?.x)||0;y=Number(q?.y)||0;z=Number(q?.z)||0;}const px=x,py=y-dist,pz=1.68,dx=x-px,dy=y-py,targetZ=z+.88,dz=targetZ-pz,yaw=Math.atan2(dx,dy),pitch=Math.atan2(dz,Math.hypot(dx,dy));w.setPose?.({x:px,y:py,yaw,pitch});return{id,x,y,z,px,py,pz,yaw,pitch,rootVisible:root.visible!==false};},{id,dist});
 // Avoid depending on THREE being exposed: target groups are world-root children, so local==world for procedural population.
 const faceSimple=async(id,dist=4.5)=>page.evaluate(({id,dist})=>{const scene=globalThis.__arondightRealWorld.threeScene,w=globalThis.__arondightWalkMode;let root=null;scene.traverse(node=>{if(root)return;const own=String(node?.userData?.worldPopulationId||"");if(own===id){let r=node;while(r.parent&&String(r.parent?.userData?.worldPopulationId||"")===id)r=r.parent;root=r;}});if(!root||root.visible===false)return null;root.updateWorldMatrix?.(true,false);const e=root.matrixWorld?.elements||[],x=Number(e[12]??root.position?.x)||0,y=Number(e[13]??root.position?.y)||0,z=Number(e[14]??root.position?.z)||0,px=x,py=y-dist,dx=x-px,dy=y-py,dz=z+.88-1.68,yaw=Math.atan2(dx,dy),pitch=Math.atan2(dz,Math.hypot(dx,dy));w.setPose?.({x:px,y:py,yaw,pitch});return{id,x,y,z,yaw,pitch,rootVisible:root.visible!==false};},{id,dist});
 await faceSimple(currentTargetId);
 await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:viewRect.x,y:viewRect.y,id:13,radiusX:4,radiusY:4,force:.7}]});
 const mover=(async()=>{while(dragging){moveStep++;await faceSimple(currentTargetId).catch(()=>{});await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:viewRect.x+(moveStep%3)-1,y:viewRect.y+((moveStep*2)%3)-1,id:13,radiusX:4,radiusY:4,force:.7}]}).catch(()=>{});await sleep(34);}})();
 let failure=null,lastShots=(await state()).shots;
 for(let i=0;i<populationIds.length;i++){
   currentTargetId=populationIds[i].id;const target=await faceSimple(currentTargetId);if(!target){failure={phase:"population",index:i+1,reason:"target-not-visible",state:await state(),errors:[...errors]};break;}
   const before=await state(),deadline=performance.now()+2200;let hit=false;
   while(performance.now()<deadline){await sleep(55);const s=await state();if(s.populationHits>before.populationHits){hit=true;console.log(`ACTUAL_POP_HIT ${i+1}/${populationIds.length} ${JSON.stringify({target,s})}`);lastShots=s.shots;break;}if(errors.length||s.dead||s.walkDead||s.aim==="0"){failure={phase:"population",index:i+1,reason:"runtime-state",target,state:s,errors:[...errors]};break;}if(s.shots===lastShots){await sleep(230);const c=await state();if(c.shots===lastShots){failure={phase:"population",index:i+1,reason:"shots-stopped",target,state:c,errors:[...errors]};break;}}if(s.shots>lastShots)lastShots=s.shots;}
   if(failure)break;if(!hit){failure={phase:"population",index:i+1,reason:"shots-but-no-hit",target,state:await state(),errors:[...errors]};break;}
 }
 if(!failure){await page.evaluate(()=>{const wanted=globalThis.__arondightWantedSystem;for(let i=0;i<18;i++)wanted.reportCrime?.({id:`actual-ray-police-${i}`,kind:"person",severity:5,revealPlayer:true});});await page.waitForFunction(()=>{const ds=globalThis.__arondightWantedSystem?.drones||[];return ds.some(d=>d?.active&&d?.root?.visible===true&&d?.hitbox?.visible===true);},{timeout:12000});
   for(let i=0;i<3;i++){
     const police=await page.evaluate(()=>{const ds=globalThis.__arondightWantedSystem?.drones||[],d=ds.find(x=>x?.active&&x?.root?.visible===true&&x?.hitbox?.visible===true&&!x?.critical);if(!d)return null;d.hitbox.updateWorldMatrix?.(true,false);const e=d.hitbox.matrixWorld?.elements||[],x=Number(e[12])||0,y=Number(e[13])||0,z=Number(e[14])||0,w=globalThis.__arondightWalkMode,px=x,py=y-5,dx=x-px,dy=y-py,dz=z-1.68,yaw=Math.atan2(dx,dy),pitch=Math.atan2(dz,Math.hypot(dx,dy));w.setPose?.({x:px,y:py,yaw,pitch});return{index:d.index,x,y,z,yaw,pitch,rootVisible:d.root.visible,hitboxVisible:d.hitbox.visible,hitboxIgnore:Boolean(d.hitbox.userData?.flightFireIgnore)};});
     if(!police){failure={phase:"police",index:i+1,reason:"no-active-hitbox",state:await state(),errors:[...errors]};break;}
     const before=await state(),deadline=performance.now()+2600;let hit=false;
     while(performance.now()<deadline){await sleep(55);const s=await state();if(s.policeHits>before.policeHits){hit=true;console.log(`ACTUAL_POLICE_HIT ${i+1}/3 ${JSON.stringify({police,s})}`);lastShots=s.shots;break;}if(errors.length||s.dead||s.walkDead||s.aim==="0"){failure={phase:"police",index:i+1,reason:"runtime-state",police,state:s,errors:[...errors]};break;}if(s.shots>lastShots)lastShots=s.shots;}
     if(failure)break;if(!hit){failure={phase:"police",index:i+1,reason:"shots-but-no-hit",police,state:await state(),errors:[...errors]};break;}
   }
 }
 dragging=false;await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]}).catch(()=>{});await mover;
 const final=await state();if(failure){console.log(`ACTUAL_RAY_FAILURE ${JSON.stringify(failure)}`);throw Error(`ACTUAL_RAY_FAILURE ${JSON.stringify(failure)}`);}console.log(`ACTUAL_RAY_NO_FAILURE ${JSON.stringify(final)}`);throw Error(`actual real ray did not reproduce failure: ${JSON.stringify(final)}`);
}finally{await browser.close();}
