import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage();
await page.evaluateOnNewDocument(()=>{const state={axes:[0,0,0,0],buttons:Array(17).fill(0)},pad={id:"Xbox Wireless Controller (Vendor: 045e Product: 0b13)",index:0,mapping:"standard",connected:true,timestamp:0,get axes(){return state.axes;},get buttons(){return state.buttons.map(value=>({pressed:value>.5,touched:value>0,value}));}};Object.defineProperty(navigator,"getGamepads",{configurable:true,value:()=>[pad]});globalThis.__fpsPad={axis(index,value){state.axes[index]=Math.max(-1,Math.min(1,Number(value)||0));},button(index,value){state.buttons[index]=Math.max(0,Math.min(1,Number(value)||0));},reset(){state.axes.fill(0);state.buttons.fill(0);}};});
const pause=ms=>page.evaluate(delay=>new Promise(resolve=>setTimeout(resolve,delay)),ms),setAxes=(x,y)=>page.evaluate((a,b)=>{globalThis.__fpsPad.axis(2,a);globalThis.__fpsPad.axis(3,b);},x,y);

try{
  await page.setViewport({width:960,height:540,deviceScaleFactor:1,hasTouch:true});await page.goto(url.href,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&globalThis.__arondightWalkMode&&document.querySelector("#playerModeButton"),{timeout:30000});
  await page.evaluate(()=>globalThis.__arondightWalkMode.setMode("foot",{persist:false}));await page.waitForFunction(()=>{const v=document.querySelector("#viewport");return v?.dataset.playerMode==="foot"&&v.dataset.cameraMode==="walk"&&v.dataset.presentationCameraMode==="walk"&&document.querySelector("#footMove")&&document.querySelector("#footLookZone");},{timeout:5000});

  await page.evaluate(()=>document.querySelector('#soloTopbar .phone-settings-button[data-control-profiles="drone+first-person"]')?.click());await page.waitForFunction(()=>document.querySelector("dialog.phone-settings-dialog")?.open&&document.querySelector('dialog.phone-settings-dialog')?.dataset.stackedControls==="1",{timeout:3000});
  const layout=await page.evaluate(()=>{const dialog=document.querySelector("dialog.phone-settings-dialog"),legacy=dialog?.querySelector("select[data-control-profile]");return{legacyHidden:legacy?getComputedStyle(legacy).display==="none"||legacy.offsetParent===null:true,drone:Boolean(dialog?.querySelector('[data-profile-section="drone"]')),fps:Boolean(dialog?.querySelector('[data-profile-section="first-person"]')),vehicle:Boolean(dialog?.querySelector('[data-profile-section="vehicle"]')),hardware:Boolean(dialog?.querySelector(".player-control-hardware")),audioFoot:Boolean(dialog?.querySelector('[data-audio-slider="footsteps"]')),audioVehicle:Boolean(dialog?.querySelector('[data-audio-slider="vehicle"]'))};});if(!layout.legacyHidden||!layout.drone||!layout.fps||!layout.vehicle||!layout.hardware||!layout.audioFoot||!layout.audioVehicle)throw new Error(`stacked settings contract failed: ${JSON.stringify(layout)}`);
  await page.$eval('[data-profile-section="drone"] [data-setting="leftFineness"]',el=>{el.value="8";el.dispatchEvent(new Event("input",{bubbles:true}));});await page.$eval('[data-profile-section="first-person"] [data-setting="moveFineness"]',el=>{el.value="4";el.dispatchEvent(new Event("input",{bubbles:true}));});await page.$eval('[data-profile-section="first-person"] [data-setting="horizontalLookSensitivityPercent"]',el=>{el.value="73";el.dispatchEvent(new Event("input",{bubbles:true}));});await page.$eval('[data-profile-section="first-person"] [data-setting="aimAssistStrengthPercent"]',el=>{el.value="42";el.dispatchEvent(new Event("input",{bubbles:true}));});await page.click('[data-profile-section="first-person"] [data-setting="invertLookHorizontal"]');await pause(100);
  const isolated=await page.evaluate(()=>({drone:JSON.parse(localStorage.getItem("arondight45PhoneControlSettingsV5")||"{}"),fps:JSON.parse(localStorage.getItem("arondight45FirstPersonControlSettingsV1")||"{}"),droneVolume:+document.querySelector('[data-audio-slider="drone"]')?.value,fxVolume:+document.querySelector('[data-audio-slider="fx"]')?.value,footstepsVolume:+document.querySelector('[data-audio-slider="footsteps"]')?.value}));if(isolated.drone.leftFineness!==8||isolated.fps.moveFineness!==4||isolated.fps.horizontalLookSensitivityPercent!==73||isolated.fps.aimAssistStrengthPercent!==42||isolated.fps.invertLookHorizontal!==true||!(isolated.droneVolume<isolated.fxVolume)||!(isolated.footstepsVolume<isolated.fxVolume))throw new Error(`independent control/audio settings failed: ${JSON.stringify(isolated)}`);await page.evaluate(()=>document.querySelector("dialog.phone-settings-dialog [data-close]")?.click());

  await page.waitForFunction(()=>{const v=document.querySelector("#viewport");return v?.dataset.walkControllerFamily==="xbox-standard"&&v.dataset.walkControlProfile==="cod-dynamic-assist-bob-v7"&&v.dataset.walkLookModel==="fps-balanced-dynamic-v7"&&v.dataset.walkCameraBase==="player-eye-origin-v1"&&v.dataset.walkCameraRotationOrigin==="player-eye-v1"&&v.dataset.walkCameraPresentation==="owned-pose-provider-v1";},{timeout:3000});
  const before=await page.$eval("#viewport",v=>({yaw:Number(v.dataset.walkYaw),pitch:Number(v.dataset.walkPitch)}));await setAxes(.62,-.58);await page.waitForFunction(baseline=>{const v=document.querySelector("#viewport"),yaw=Number(v?.dataset.walkYaw),pitch=Number(v?.dataset.walkPitch);return Number.isFinite(yaw)&&Number.isFinite(pitch)&&Math.abs(yaw-baseline.yaw)>=.12&&Math.abs(pitch-baseline.pitch)>=.10;},{timeout:5000,polling:50},before);const after=await page.$eval("#viewport",v=>({yaw:Number(v.dataset.walkYaw),pitch:Number(v.dataset.walkPitch),stick:v.dataset.walkControllerStick,elapsed:v.dataset.walkControllerElapsedMs}));await setAxes(0,0);if(Math.abs(after.yaw-before.yaw)<.12||Math.abs(after.pitch-before.pitch)<.10)throw new Error(`Xbox first-person look did not respond: ${JSON.stringify({before,after})}`);

  await page.$eval("#footMove",el=>{const r=el.getBoundingClientRect(),id=773,down=new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",clientX:r.left+r.width/2,clientY:r.top+r.height/2}),move=new PointerEvent("pointermove",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",clientX:r.right-2,clientY:r.top+r.height/2});el.dispatchEvent(down);el.dispatchEvent(move);});await pause(80);const magnitude=Number(await page.$eval("#viewport",v=>v.dataset.walkMoveStickMagnitude||0));if(magnitude<.94)throw new Error(`left stick cannot reach full radial range: ${magnitude}`);await page.evaluate(()=>window.dispatchEvent(new Event("blur")));await page.waitForFunction(()=>{const v=document.querySelector("#viewport");return Boolean(v?.dataset.walkMoveStickRecovery)&&String(v.dataset.walkMove||"").startsWith("0.000,0.000");},{timeout:2000});

  await page.waitForFunction(()=>{const fire=document.querySelector("#footFire"),r=fire?.getBoundingClientRect();return fire&&getComputedStyle(fire).display!=="none"&&r.width>40&&r.height>40&&document.querySelector("#viewport")?.dataset.walkMuzzleDepth==="depth-tested-behind-viewmodel-v2";},{timeout:3000});
  const enhancedBefore=Number(await page.$eval("#viewport",v=>v.dataset.walkEnhancedShots||0));await page.$eval("#footLookZone",el=>{const r=el.getBoundingClientRect(),id=991,x=r.left+r.width*.72,y=r.top+r.height*.39;el.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",button:0,buttons:1,clientX:x,clientY:y}));el.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",button:0,buttons:0,clientX:x,clientY:y}));});await page.waitForFunction(before=>{const v=document.querySelector("#viewport");return Number(v?.dataset.walkEnhancedShots||0)>before&&v.dataset.walkTouchFire==="screen-point-raycast-v2"&&v.dataset.walkPistolTracer==="world-ray-muzzle-origin-v2";},{timeout:2000},enhancedBefore);
  const weaponBefore=await page.$eval("#viewport",v=>v.dataset.walkWeapon);await page.click("#footWeaponToggle");await page.waitForFunction(before=>document.querySelector("#viewport")?.dataset.walkWeapon!==before,{timeout:2000},weaponBefore);

  const explosionBefore=Number(await page.$eval("#viewport",v=>v.dataset.explosionLastDamaged||0));await page.evaluate(()=>dispatchEvent(new CustomEvent("arondight:world-explosion",{detail:{position:[999,999,20],id:"fps-smoke-blast",radiusM:4,maxDamage:20}})));await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.explosionPhysics==="box3d-radial-impulse+damage-falloff-v2",{timeout:2000});
  const muzzleInvariant=await page.evaluate(()=>{const scene=globalThis.__arondightRealWorld?.threeScene,gun=scene?.getObjectByName?.("WALK_PISTOL_3D"),flash=gun?.getObjectByName?.("FINAL_MUZZLE_FLASH")||gun?.getObjectByName?.("WALK_MUZZLE_FLASH"),slide=gun?.getObjectByName?.("WALK_VM_SLIDE");let depthTest=true,meshCount=0;flash?.traverse?.(node=>{if(!node?.isMesh)return;meshCount++;for(const mat of(Array.isArray(node.material)?node.material:[node.material]))if(mat?.depthTest!==true)depthTest=false;});return{depthTest,meshCount,flashOrder:Number(flash?.renderOrder)||0,slideOrder:Number(slide?.renderOrder)||0};});if(!muzzleInvariant.depthTest||muzzleInvariant.meshCount<1||!(muzzleInvariant.flashOrder<muzzleInvariant.slideOrder))throw new Error(`muzzle rendering invariant failed: ${JSON.stringify(muzzleInvariant)}`);
  const final=await page.$eval("#viewport",v=>({touch:v.dataset.walkTouchFire,tracer:v.dataset.walkPistolTracer,muzzle:v.dataset.walkMuzzleDepth,recovery:v.dataset.walkMoveStickRelease,pedestrians:v.dataset.pedestrianAnimation,explosion:v.dataset.explosionPhysics,occlusion:v.dataset.explosionOcclusion,satellite:v.dataset.worldSatelliteDefault,weapon:v.dataset.walkWeapon,controller:v.dataset.weaponSwitchInputs,runtime:v.dataset.gameplayFinalRuntime}));if(final.touch!=="screen-point-raycast-v2"||final.tracer!=="world-ray-muzzle-origin-v2"||!String(final.recovery).includes("lostcapture")||final.pedestrians!=="procedural-arm-leg-walkcycle-v2"||final.explosion!=="box3d-radial-impulse+damage-falloff-v2"||final.occlusion!=="building-prism-los-v2"||final.satellite!=="off"||final.runtime!=="weapons+blast+pedestrians+input-v2")throw new Error(`final FPS gameplay contract failed: ${JSON.stringify({final,muzzleInvariant})}`);
  console.log(`FPS first-person browser smoke passed: stacked independent settings, Xbox look, full-range/recovering left stick, v2 touch-point fire, real muzzle-origin tracer/depth ordering, weapon switching, pedestrian walkcycle and wall-aware Box3D explosion contract: ${JSON.stringify({layout,isolated,magnitude,weaponBefore,final,muzzleInvariant,explosionBefore})}`);
}finally{await browser.close();}
