import puppeteer from "puppeteer-core";

const executablePath=process.env.CHROME_BIN;if(!executablePath)throw Error("CHROME_BIN required");
const targetUrl=process.env.TARGET_URL||`https://kurzlernen.de/drone_simulator.html?fps-trusted-touch-diag=${Date.now()}`;
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]});
const page=await browser.newPage(),pageErrors=[];page.on("pageerror",e=>{const text=String(e?.stack||e);pageErrors.push(text);console.error("PAGEERROR",text);});
const cdp=await page.createCDPSession();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const snap=()=>page.evaluate(()=>{const v=document.querySelector("#viewport"),w=globalThis.__arondightWalkMode,b=globalThis.__arondightRealWorld,z=document.querySelector("#footLookZone"),id=Number(v?.dataset.walkScreenAimPointer);return{mode:w?.mode||"",dead:!!w?.dead,screenAim:v?.dataset.walkScreenAimActive||"",screenPointer:v?.dataset.walkScreenAimPointer||"",release:v?.dataset.walkScreenAimRelease||"",capture:Number.isFinite(id)&&!!z?.hasPointerCapture?.(id),bursts:Number(v?.dataset.walkAutoFireBursts||0),shots:Number(v?.dataset.walkEnhancedShots||0),hits:Number(v?.dataset.worldPopulationHits||0),rag:Number(v?.dataset.worldRagdollSpawns||0),exp:Number(v?.dataset.worldCarExplosionSpawns||0),stars:Number(v?.dataset.wantedStars||0),phase:v?.dataset.wantedPhase||"",police:Number(v?.dataset.wantedPoliceActive||0),hp:Number(v?.dataset.playerHp||v?.dataset.walkPlayerHp||100),fireLocked:v?.dataset.fireLockedByDeath||"",vsLocalDead:!!b?.vsLocalDead,assign:Number(v?.dataset.combatHitStackAssignments||0),worldActive:!!b?.active,events:(globalThis.__fpsTrustedEvents||[]).slice(-8)};});
try{
  await page.setUserAgent("Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148");await page.setViewport({width:844,height:390,deviceScaleFactor:1,hasTouch:true,isMobile:true});
  await page.goto(targetUrl,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&globalThis.__arondightWalkMode&&globalThis.__arondightFootWeapons&&globalThis.__arondightRealWorld?.threeScene,{timeout:30000});
  await page.evaluate(()=>globalThis.__arondightWalkMode.setMode("foot",{persist:false}));await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.playerMode==="foot"&&document.querySelector("#footLookZone"),{timeout:5000});
  await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport");v.dataset.worldMode="real";b.active=true;b.originLon=9;b.originLat=47;globalThis.__fpsTrustedEvents=[];for(const type of["pointerdown","pointerup","pointercancel","lostpointercapture","gotpointercapture"]){window.addEventListener(type,e=>{if(e.pointerType==="touch")globalThis.__fpsTrustedEvents.push({type,id:e.pointerId,target:e.target?.id||e.target?.className||"",t:performance.now().toFixed(1)});},true);}});await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.worldProceduralPopulation==="1",{timeout:10000});
  const count=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,scene=b.threeScene,seen=new Map();scene.traverse(node=>{if(node?.isMesh)node.raycast=()=>{};const id=String(node?.userData?.worldPopulationId||""),kind=String(node?.userData?.worldPopulationKind||"");if(node?.isMesh&&id&&["person","car","bus"].includes(kind)&&!seen.has(id))seen.set(id,{id,kind,mesh:node});});const all=[...seen.values()],sequence=[...all.filter(x=>x.kind==="person").slice(0,10),...all.filter(x=>x.kind==="car").slice(0,6),...all.filter(x=>x.kind==="bus").slice(0,3)];if(sequence.length!==19)throw Error(`inventory ${sequence.length}`);globalThis.__fpsTargetDiag={sequence,current:null};return sequence.length;});console.log("FPS_TRUSTED_TOUCH inventory",count);
  const arm=index=>page.evaluate(index=>{const d=globalThis.__fpsTargetDiag,v=document.querySelector("#viewport"),rec=d.sequence[index];if(d.current)d.current.mesh.raycast=()=>{};rec.mesh.userData.flightFireIgnore=false;rec.mesh.visible=true;rec.mesh.raycast=function(raycaster,intersections){const distance=.02,point=raycaster.ray.origin.clone().addScaledVector(raycaster.ray.direction,distance);intersections.push({distance,point,object:this,face:null,faceIndex:0});};d.current=rec;const key=rec.kind==="person"?"worldRagdollSpawns":"worldCarExplosionSpawns";return{id:rec.id,kind:rec.kind,key,before:Number(v.dataset[key]||0)};},index);
  let current=await arm(0),last=await snap();const r=await page.$eval("#footLookZone",el=>{const x=el.getBoundingClientRect();return{left:x.left,top:x.top,width:x.width,height:x.height};});let x=r.left+r.width*.30,y=r.top+r.height*.42,moving=true,n=0;
  await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x,y,id:0,radiusX:3,radiusY:3,force:1}]});await sleep(80);const began=await snap();if(began.screenAim!=="1"||!began.screenPointer||!began.capture)throw Error(`trusted touch did not capture: ${JSON.stringify(began)}`);
  const mover=setInterval(()=>{if(!moving)return;n++;const p=(n%80)/79,q=p<=.5?p*2:(1-p)*2;x=r.left+r.width*(.18+.64*q);y=r.top+r.height*(.28+.42*((n%53)/52));void cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x,y,id:0,radiusX:3,radiusY:3,force:1}]}).catch(()=>{});},37);
  for(let i=0;i<19;i++){
    if(i)current=await arm(i);const timeout=current.kind==="person"?3000:current.kind==="car"?4800:6800;
    try{await page.waitForFunction(({key,before})=>Number(document.querySelector("#viewport")?.dataset[key]||0)>before,{timeout},current);}catch{const s=await snap();throw Error(`FPS_TRUSTED_TOUCH STOP ${i+1}/19 ${current.kind} previous=${JSON.stringify(last)} state=${JSON.stringify(s)} errors=${JSON.stringify(pageErrors.slice(-5))}`);}const s=await snap();console.log(`FPS_TRUSTED_TOUCH OK ${i+1}/19 kind=${current.kind} shots=${s.shots} hits=${s.hits} stars=${s.stars} police=${s.police} hp=${s.hp} aim=${s.screenAim}/${s.screenPointer} capture=${s.capture} release=${s.release}`);if(s.shots<=last.shots||s.screenAim!=="1"||!s.screenPointer||!s.capture)throw Error(`FPS_TRUSTED_TOUCH lifecycle ${i+1}/19 previous=${JSON.stringify(last)} state=${JSON.stringify(s)}`);if(s.dead||s.fireLocked==="1"||s.vsLocalDead)throw Error(`FPS_TRUSTED_TOUCH player death/lock ${i+1}/19 ${JSON.stringify(s)}`);last=s;
  }
  moving=false;clearInterval(mover);await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await sleep(80);const finalState=await snap();if(pageErrors.length)throw Error(`FPS_TRUSTED_TOUCH page errors ${JSON.stringify(pageErrors.slice(-5))}`);console.log("FPS_TRUSTED_TOUCH PASS",JSON.stringify(finalState));
}finally{try{await cdp.send("Input.dispatchTouchEvent",{type:"touchCancel",touchPoints:[]});}catch{}await browser.close();}
