import fs from "node:fs";
import puppeteer from "puppeteer-core";

const executablePath=process.env.CHROME_BIN;if(!executablePath)throw Error("CHROME_BIN required");
const root=process.cwd(),fixture=`<!doctype html><meta charset="utf-8"><style>html,body,#viewport{margin:0;width:100%;height:100%;overflow:hidden}#footLookZone{position:absolute;inset:0;touch-action:none}#footReticle{position:absolute}</style><div id="viewport" data-walk-yaw="0" data-walk-pitch="0"><div id="footLookZone"></div><div id="footReticle"></div></div><script>globalThis.__arondightWalkMode={mode:"foot",dead:false,setPose(){},beginTouchLook(){},endTouchLook(){}};globalThis.__arondightFootWeapons={mode:"pistol",fireAt(){const v=document.querySelector("#viewport");v.dataset.fixtureShots=String((Number(v.dataset.fixtureShots)||0)+1);return true;}};</script><script type="module" src="../sim/foot_look_capture.mjs"></script>`;fs.writeFileSync(`${root}/tests/fps_capture_loss_fixture.html`,fixture);
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage"]}),page=await browser.newPage(),cdp=await page.createCDPSession(),sleep=ms=>new Promise(r=>setTimeout(r,ms));
try{
  await page.setViewport({width:844,height:390,deviceScaleFactor:1,hasTouch:true,isMobile:true});await page.goto("http://127.0.0.1:4174/tests/fps_capture_loss_fixture.html",{waitUntil:"load",timeout:15000});
  await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.walkScreenAimReleasePolicy==="terminal-events-only-v2",{timeout:5000});
  await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:420,y:180,id:0,radiusX:3,radiusY:3,force:1}]});
  await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.walkScreenAimActive==="1"&&Number(document.querySelector("#viewport")?.dataset.fixtureShots||0)>=1,{timeout:3000});
  const before=await page.evaluate(()=>{const v=document.querySelector("#viewport"),z=document.querySelector("#footLookZone"),id=Number(v.dataset.walkScreenAimPointer);return{id,shots:Number(v.dataset.fixtureShots||0),capture:z.hasPointerCapture(id),active:v.dataset.walkScreenAimActive,release:v.dataset.walkScreenAimRelease};});if(!before.capture)throw Error(`fixture failed to capture pointer: ${JSON.stringify(before)}`);
  await page.evaluate(()=>{const v=document.querySelector("#viewport"),z=document.querySelector("#footLookZone"),id=Number(v.dataset.walkScreenAimPointer);z.releasePointerCapture(id);});await sleep(80);
  const lost=await page.evaluate(()=>{const v=document.querySelector("#viewport"),z=document.querySelector("#footLookZone"),id=Number(v.dataset.walkScreenAimPointer);return{id,shots:Number(v.dataset.fixtureShots||0),capture:z.hasPointerCapture(id),active:v.dataset.walkScreenAimActive,release:v.dataset.walkScreenAimRelease,state:v.dataset.walkScreenAimCaptureState,losses:Number(v.dataset.walkScreenAimCaptureLosses||0)};});if(lost.active!=="1"||lost.release!=="held"||lost.capture||lost.state!=="lost-await-terminal"||lost.losses<1)throw Error(`capture loss incorrectly terminated screen fire: ${JSON.stringify(lost)}`);
  await sleep(520);const afterHold=await page.$eval("#viewport",v=>({shots:Number(v.dataset.fixtureShots||0),active:v.dataset.walkScreenAimActive,release:v.dataset.walkScreenAimRelease}));if(afterHold.shots<=lost.shots||afterHold.active!=="1"||afterHold.release!=="held")throw Error(`autofire stopped after capture loss: ${JSON.stringify({lost,afterHold})}`);
  await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:510,y:215,id:0,radiusX:3,radiusY:3,force:1}]});await sleep(100);const recovered=await page.evaluate(()=>{const v=document.querySelector("#viewport"),z=document.querySelector("#footLookZone"),id=Number(v.dataset.walkScreenAimPointer);return{capture:z.hasPointerCapture(id),active:v.dataset.walkScreenAimActive,state:v.dataset.walkScreenAimCaptureState,recoveries:Number(v.dataset.walkScreenAimCaptureRecoveries||0),shots:Number(v.dataset.fixtureShots||0)};});if(!recovered.capture||recovered.active!=="1"||recovered.state!=="captured"||recovered.recoveries<1)throw Error(`screen capture did not recover on move: ${JSON.stringify(recovered)}`);
  await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.walkScreenAimActive==="0",{timeout:2000});const ended=await page.$eval("#viewport",v=>({active:v.dataset.walkScreenAimActive,release:v.dataset.walkScreenAimRelease,shots:Number(v.dataset.fixtureShots||0)}));console.log("FPS_CAPTURE_LOSS_FIX PASS",JSON.stringify({before,lost,afterHold,recovered,ended}));
}finally{await browser.close();try{fs.unlinkSync(`${root}/tests/fps_capture_loss_fixture.html`);}catch{}}
