import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage();
await page.evaluateOnNewDocument(()=>{const state={axes:[0,0,0,0],buttons:Array(17).fill(0)},pad={id:"Xbox Wireless Controller (Vendor: 045e Product: 0b13)",index:0,mapping:"standard",connected:true,timestamp:0,get axes(){return state.axes;},get buttons(){return state.buttons.map(value=>({pressed:value>.5,touched:value>0,value}));}};Object.defineProperty(navigator,"getGamepads",{configurable:true,value:()=>[pad]});globalThis.__fpsPad={axis(index,value){state.axes[index]=Math.max(-1,Math.min(1,Number(value)||0));},button(index,value){state.buttons[index]=Math.max(0,Math.min(1,Number(value)||0));},reset(){state.axes.fill(0);state.buttons.fill(0);}};});
const pause=ms=>page.evaluate(delay=>new Promise(resolve=>setTimeout(resolve,delay)),ms),setAxes=(x,y)=>page.evaluate((a,b)=>{globalThis.__fpsPad.axis(2,a);globalThis.__fpsPad.axis(3,b);},x,y);
const gripProjection=()=>page.evaluate(()=>{const scene=globalThis.__arondightRealWorld?.threeScene,camera=globalThis.__arondightRealWorld?.threeCamera,gun=scene?.getObjectByName?.("WALK_PISTOL_3D"),mode=String(globalThis.__arondightFootWeapons?.mode||"pistol"),pivot=mode==="smg"?gun?.getObjectByName?.("WALK_SMG_PISTOL_GRIP"):gun?.getObjectByName?.("WALK_VM_GRIP"),v=document.querySelector("#viewport");if(!gun||!pivot||!camera)return null;camera.updateMatrixWorld?.(true);gun.updateMatrixWorld?.(true);const p=pivot.getWorldPosition(pivot.position.clone()).project(camera);return{x:p.x,y:p.y,scale:gun.scale.x,latch:v?.dataset.walkWeaponGripLatchActive||"0",continuity:Number(v?.dataset.walkWeaponAimStartContinuityM||NaN),drift:Number(v?.dataset.walkWeaponAnchorDriftM||NaN),policy:v?.dataset.walkWeaponTranslationPolicy||""};});

try{
  await page.setViewport({width:960,height:540,deviceScaleFactor:1,hasTouch:true});await page.goto(url.href,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&globalThis.__arondightWalkMode&&document.querySelector("#playerModeButton"),{timeout:30000});
  await page.evaluate(()=>globalThis.__arondightWalkMode.setMode("foot",{persist:false}));await page.waitForFunction(()=>{const v=document.querySelector("#viewport");return v?.dataset.playerMode==="foot"&&v.dataset.cameraMode==="walk"&&v.dataset.presentationCameraMode==="walk"&&document.querySelector("#footMove")&&document.querySelector("#footLook")&&document.querySelector("#footLookZone");},{timeout:5000});

  await page.evaluate(()=>document.querySelector('#soloTopbar .phone-settings-button[data-control-profiles="drone+first-person"]')?.click());await page.waitForFunction(()=>document.querySelector("dialog.phone-settings-dialog")?.open&&document.querySelector('dialog.phone-settings-dialog')?.dataset.stackedControls==="1",{timeout:3000});
  const layout=await page.evaluate(()=>{const dialog=document.querySelector("dialog.phone-settings-dialog"),legacy=dialog?.querySelector("select[data-control-profile]");return{legacyHidden:legacy?getComputedStyle(legacy).display==="none"||legacy.offsetParent===null:true,drone:Boolean(dialog?.querySelector('[data-profile-section="drone"]')),fps:Boolean(dialog?.querySelector('[data-profile-section="first-person"]')),vehicle:Boolean(dialog?.querySelector('[data-profile-section="vehicle"]')),hardware:Boolean(dialog?.querySelector(".player-control-hardware")),audioFoot:Boolean(dialog?.querySelector('[data-audio-slider="footsteps"]')),audioVehicle:Boolean(dialog?.querySelector('[data-audio-slider="vehicle"]'))};});if(!layout.legacyHidden||!layout.drone||!layout.fps||!layout.vehicle||!layout.hardware||!layout.audioFoot||!layout.audioVehicle)throw new Error(`stacked settings contract failed: ${JSON.stringify(layout)}`);
  await page.$eval('[data-profile-section="drone"] [data-setting="leftFineness"]',el=>{el.value="8";el.dispatchEvent(new Event("input",{bubbles:true}));});await page.$eval('[data-profile-section="first-person"] [data-setting="moveFineness"]',el=>{el.value="4";el.dispatchEvent(new Event("input",{bubbles:true}));});await page.$eval('[data-profile-section="first-person"] [data-setting="horizontalLookSensitivityPercent"]',el=>{el.value="73";el.dispatchEvent(new Event("input",{bubbles:true}));});await page.$eval('[data-profile-section="first-person"] [data-setting="aimAssistStrengthPercent"]',el=>{el.value="42";el.dispatchEvent(new Event("input",{bubbles:true}));});await page.click('[data-profile-section="first-person"] [data-setting="invertLookHorizontal"]');await pause(100);
  const isolated=await page.evaluate(()=>({drone:JSON.parse(localStorage.getItem("arondight45PhoneControlSettingsV5")||"{}"),fps:JSON.parse(localStorage.getItem("arondight45FirstPersonControlSettingsV1")||"{}"),droneVolume:+document.querySelector('[data-audio-slider="drone"]')?.value,fxVolume:+document.querySelector('[data-audio-slider="fx"]')?.value,footstepsVolume:+document.querySelector('[data-audio-slider="footsteps"]')?.value}));if(isolated.drone.leftFineness!==8||isolated.fps.moveFineness!==4||isolated.fps.horizontalLookSensitivityPercent!==73||isolated.fps.aimAssistStrengthPercent!==42||isolated.fps.invertLookHorizontal!==true||!(isolated.droneVolume<isolated.fxVolume)||!(isolated.footstepsVolume<isolated.fxVolume))throw new Error(`independent control/audio settings failed: ${JSON.stringify(isolated)}`);await page.evaluate(()=>document.querySelector("dialog.phone-settings-dialog [data-close]")?.click());

  await page.waitForFunction(()=>{const v=document.querySelector("#viewport");return v?.dataset.walkControllerFamily==="xbox-standard"&&v.dataset.walkControlProfile==="cod-dynamic-assist-bob-v7"&&v.dataset.walkLookModel==="fps-balanced-dynamic-v7"&&v.dataset.walkCameraBase==="player-eye-origin-v1"&&v.dataset.walkCameraRotationOrigin==="player-eye-v1"&&v.dataset.walkCameraPresentation==="owned-pose-provider-v1";},{timeout:3000});
  const before=await page.$eval("#viewport",v=>({yaw:Number(v.dataset.walkYaw),pitch:Number(v.dataset.walkPitch)}));await setAxes(.62,-.58);await page.waitForFunction(baseline=>{const v=document.querySelector("#viewport"),yaw=Number(v?.dataset.walkYaw),pitch=Number(v?.dataset.walkPitch);return Number.isFinite(yaw)&&Number.isFinite(pitch)&&Math.abs(yaw-baseline.yaw)>=.12&&Math.abs(pitch-baseline.pitch)>=.10;},{timeout:5000,polling:50},before);const after=await page.$eval("#viewport",v=>({yaw:Number(v.dataset.walkYaw),pitch:Number(v.dataset.walkPitch),stick:v.dataset.walkControllerStick,elapsed:v.dataset.walkControllerElapsedMs}));await setAxes(0,0);if(Math.abs(after.yaw-before.yaw)<.12||Math.abs(after.pitch-before.pitch)<.10)throw new Error(`Xbox first-person look did not respond: ${JSON.stringify({before,after})}`);

  await page.$eval("#footMove",el=>{const r=el.getBoundingClientRect(),id=773,down=new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",button:0,buttons:1,clientX:r.left+r.width/2,clientY:r.top+r.height/2}),move=new PointerEvent("pointermove",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",button:0,buttons:1,clientX:r.right-2,clientY:r.top+r.height/2});el.dispatchEvent(down);el.dispatchEvent(move);});await pause(100);
  const magnitude=Number(await page.$eval("#viewport",v=>v.dataset.walkMoveStickMagnitude||0));if(magnitude<.94)throw new Error(`left stick cannot reach full radial range: ${magnitude}`);
  await page.$eval("#footLook",el=>el.dispatchEvent(new PointerEvent("lostpointercapture",{bubbles:true,cancelable:false,pointerId:991,pointerType:"touch"})));await pause(120);
  const heldAfterForeignCapture=await page.$eval("#viewport",v=>({move:v.dataset.walkMove,owner:v.dataset.walkMoveStickOwner,foreign:v.dataset.walkMoveStickForeignCapture}));if(String(heldAfterForeignCapture.move||"").startsWith("0.000,0.000")||heldAfterForeignCapture.owner!=="773")throw new Error(`foreign pointer capture interrupted held left stick: ${JSON.stringify(heldAfterForeignCapture)}`);

  await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.walkMuzzleDepth==="depth-tested-behind-viewmodel-occlusion-v2",{timeout:3000});
  const noDragBefore=await page.$eval("#viewport",v=>({yaw:Number(v.dataset.walkYaw),pitch:Number(v.dataset.walkPitch)})),enhancedBefore=Number(await page.$eval("#viewport",v=>v.dataset.walkEnhancedShots||0)),hipGrip=await gripProjection();if(!hipGrip)throw new Error("hip grip projection unavailable");
  await page.$eval("#footLookZone",el=>{const r=el.getBoundingClientRect(),id=992,x=r.left+r.width*.72,y=r.top+r.height*.39;el.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",button:0,buttons:1,clientX:x,clientY:y}));});
  await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.walkWeaponGripLatchActive==="1",{timeout:2000});await pause(80);const aimGripStart=await gripProjection();if(!aimGripStart)throw new Error("aim-start grip projection unavailable");
  const startJump=Math.hypot(aimGripStart.x-hipGrip.x,aimGripStart.y-hipGrip.y);if(startJump>.012||Math.abs(aimGripStart.scale-hipGrip.scale)>.001||!(aimGripStart.continuity<=.002)||aimGripStart.policy!=="latch-current-hip-grip+rotation-about-pivot-v4")throw new Error(`aim-start grip jumped from hip pose: ${JSON.stringify({hipGrip,aimGripStart,startJump})}`);
  await page.$eval("#footLookZone",el=>{const r=el.getBoundingClientRect(),id=992,x=r.left+r.width*.72-90,y=r.top+r.height*.39+70;el.dispatchEvent(new PointerEvent("pointermove",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",button:0,buttons:1,clientX:x,clientY:y}));});await pause(80);const aimGripMoved=await gripProjection();if(!aimGripMoved)throw new Error("dragged grip projection unavailable");const dragAnchorError=Math.hypot(aimGripMoved.x-hipGrip.x,aimGripMoved.y-hipGrip.y);if(dragAnchorError>.012||!(aimGripMoved.drift<=.003))throw new Error(`drag moved fixed hip-grip pivot: ${JSON.stringify({hipGrip,aimGripMoved,dragAnchorError})}`);
  await page.$eval("#footLookZone",el=>{const r=el.getBoundingClientRect(),id=992,x=r.left+r.width*.72-90,y=r.top+r.height*.39+70;el.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:id,pointerType:"touch",button:0,buttons:0,clientX:x,clientY:y}));});
  await page.waitForFunction(before=>Number(document.querySelector("#viewport")?.dataset.walkEnhancedShots||0)>before,{timeout:2000},enhancedBefore);await pause(180);
  const noDragAfter=await page.$eval("#viewport",v=>({yaw:Number(v.dataset.walkYaw),pitch:Number(v.dataset.walkPitch),ownership:v.dataset.walkTouchOwnership,touch:v.dataset.walkTouchFire,move:v.dataset.walkMove,owner:v.dataset.walkMoveStickOwner}));
  if(Math.abs(noDragAfter.yaw-noDragBefore.yaw)>.015||Math.abs(noDragAfter.pitch-noDragBefore.pitch)>.015)throw new Error(`mobile screen drag changed look instead of fire-only: ${JSON.stringify({noDragBefore,noDragAfter})}`);
  if(noDragAfter.ownership!=="left-move+right-look+screen-fire-no-drag-v2")throw new Error(`mobile FPS ownership contract wrong: ${JSON.stringify(noDragAfter)}`);
  if(String(noDragAfter.move||"").startsWith("0.000,0.000")||noDragAfter.owner!=="773")throw new Error(`screen fire interrupted held left stick: ${JSON.stringify(noDragAfter)}`);

  const mobileUi=await page.evaluate(()=>({fireDisplay:getComputedStyle(document.querySelector("#footFire")).display,reticleDisplay:getComputedStyle(document.querySelector("#footReticle")).display,hud:document.querySelector("#viewport")?.dataset.mobileLandscapeHud}));if(mobileUi.fireDisplay!=="none"||mobileUi.reticleDisplay!=="none"||mobileUi.hud!=="compact-real-estate-v1")throw new Error(`mobile FPS HUD should use screen fire + right stick without fire/reticle clutter: ${JSON.stringify(mobileUi)}`);
  const weaponBefore=await page.$eval("#viewport",v=>v.dataset.walkWeapon);await page.click("#footWeaponToggle");await page.waitForFunction(before=>document.querySelector("#viewport")?.dataset.walkWeapon!==before,{timeout:2000},weaponBefore);

  await page.evaluate(()=>window.dispatchEvent(new Event("blur")));await page.waitForFunction(()=>{const v=document.querySelector("#viewport");return Boolean(v?.dataset.walkMoveStickRecovery)&&String(v.dataset.walkMove||"").startsWith("0.000,0.000");},{timeout:2000});
  const explosionBefore=Number(await page.$eval("#viewport",v=>v.dataset.explosionLastDamaged||0));await page.evaluate(()=>dispatchEvent(new CustomEvent("arondight:world-explosion",{detail:{position:[999,999,20],id:"fps-smoke-blast",radiusM:4,maxDamage:20}})));await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.explosionPhysics==="box3d-radial-impulse+damage-falloff-v2",{timeout:2000});
  const muzzleInvariant=await page.evaluate(()=>{const scene=globalThis.__arondightRealWorld?.threeScene,gun=scene?.getObjectByName?.("WALK_PISTOL_3D"),flash=gun?.getObjectByName?.("FINAL_MUZZLE_FLASH")||gun?.getObjectByName?.("WALK_MUZZLE_FLASH"),slide=gun?.getObjectByName?.("WALK_VM_SLIDE");let depthTest=true,meshCount=0;flash?.traverse?.(node=>{if(!node?.isMesh)return;meshCount++;for(const mat of(Array.isArray(node.material)?node.material:[node.material]))if(mat?.depthTest!==true)depthTest=false;});return{depthTest,meshCount,flashOrder:Number(flash?.renderOrder)||0,slideOrder:Number(slide?.renderOrder)||0};});if(!muzzleInvariant.depthTest||muzzleInvariant.meshCount<1||!(muzzleInvariant.flashOrder<muzzleInvariant.slideOrder))throw new Error(`muzzle rendering invariant failed: ${JSON.stringify(muzzleInvariant)}`);
  const final=await page.$eval("#viewport",v=>({touch:v.dataset.walkTouchFire,tracer:v.dataset.walkPistolTracer,muzzle:v.dataset.walkMuzzleDepth,recovery:v.dataset.walkMoveStickRelease,pedestrians:v.dataset.pedestrianAnimation,explosion:v.dataset.explosionPhysics,occlusion:v.dataset.explosionOcclusion,satellite:v.dataset.worldSatelliteDefault,weapon:v.dataset.walkWeapon,controller:v.dataset.weaponSwitchInputs,runtime:v.dataset.gameplayFinalRuntime,ownership:v.dataset.walkTouchOwnership,inputGuard:v.dataset.walkInputLifecycleGuard,hud:v.dataset.mobileLandscapeHud}));if(final.touch!=="screen-point-raycast-v2"||final.tracer!=="world-ray-muzzle-origin-v2"||!String(final.recovery).includes("lostcapture")||final.pedestrians!=="procedural-arm-leg-walkcycle-v2"||final.explosion!=="box3d-radial-impulse+damage-falloff-v2"||final.occlusion!=="building-prism-los-v2"||final.satellite!=="off"||final.runtime!=="weapons+blast+pedestrians+input-v2"||final.ownership!=="left-move+right-look+screen-fire-no-drag-v2"||final.inputGuard!=="exclusive-move-pointer-v3"||final.hud!=="compact-real-estate-v1")throw new Error(`final FPS gameplay contract failed: ${JSON.stringify({final,muzzleInvariant})}`);
  console.log(`FPS first-person browser smoke passed: stacked independent settings, Xbox/right-stick look, isolated held left stick, zero-jump hip-grip latch across aim start + drag, screen-point shooting without drag-look, compact mobile HUD, real muzzle-origin tracer/depth ordering, weapon switching, pedestrian walkcycle and wall-aware Box3D explosion contract: ${JSON.stringify({layout,isolated,magnitude,heldAfterForeignCapture,noDragBefore,noDragAfter,hipGrip,aimGripStart,aimGripMoved,startJump,dragAnchorError,mobileUi,weaponBefore,final,muzzleInvariant,explosionBefore})}`);
}finally{await browser.close();}
