import puppeteer from "puppeteer-core";
const input=process.argv[2]||"https://kurzlernen.de/drone_simulator.html";const executablePath=process.env.CHROME_BIN;if(!executablePath)throw Error("CHROME_BIN required");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage(),errors=[];page.on("pageerror",e=>errors.push(String(e?.stack||e)));const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const state=()=>page.evaluate(()=>{const v=document.querySelector("#viewport"),w=globalThis.__arondightWalkMode,p=globalThis.__arondightPlayerDamageModel,s=globalThis.__arondightWantedSystem?.state||{};return{walkDead:Boolean(w?.dead),hp:Number(p?.hp??-1),dead:Boolean(p?.dead),aim:v?.dataset.walkScreenAimActive||"",capture:v?.dataset.walkScreenAimCaptureState||"",fire:v?.dataset.walkTouchFireResult||"",bursts:Number(v?.dataset.walkAutoFireBursts||0),shots:Number(v?.dataset.walkEnhancedShots||0),hits:Number(v?.dataset.wantedPoliceHits||0),kills:Number(v?.dataset.wantedPoliceKills||s.policeKills||0),critical:Number(v?.dataset.wantedPoliceCritical||0),stars:Number(v?.dataset.wantedStars||s.stars||0),police:Number(v?.dataset.wantedPoliceActive||s.policeActive||0),damage:Number(v?.dataset.wantedPoliceDamage||0)};});
try{
 await page.setUserAgent("Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148");await page.setViewport({width:844,height:390,deviceScaleFactor:1,hasTouch:true,isMobile:true});await page.goto(input,{waitUntil:"load",timeout:40000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&globalThis.__arondightWantedSystem&&globalThis.__arondightFootWeapons&&globalThis.__arondightWalkMode,{timeout:40000});
 const setup=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,w=globalThis.__arondightWalkMode,v=document.querySelector("#viewport"),wanted=globalThis.__arondightWantedSystem;w.setMode?.("foot",{persist:false,reason:"police-target-drag-diag"});w.setPose?.({x:0,y:0,z:0,yaw:0,pitch:0});v.dataset.worldMode="real";b.active=true;b.originLon=9;b.originLat=47;for(let i=0;i<16;i++)wanted.reportCrime?.({id:`diag-crime-${i}`,kind:"person",severity:5,revealPlayer:true});const z=document.getElementById("footLookZone").getBoundingClientRect();return{x:z.left+z.width*.55,y:z.top+z.height*.48};});
 await page.waitForFunction(()=>Number(document.querySelector("#viewport")?.dataset.wantedPoliceActive||0)>0&&Number(document.querySelector("#viewport")?.dataset.wantedStars||0)>=4,{timeout:12000});
 const beforeContract=await page.evaluate(()=>{const drone=globalThis.__arondightWantedSystem?.drones?.find?.(d=>d?.active);return{active:!!drone,rootVisible:drone?.root?.visible,hitboxVisible:drone?.hitbox?.visible,hitboxKind:drone?.hitbox?.userData?.worldPopulationKind||"",hitboxMaterialVisible:drone?.hitbox?.material?.visible};});console.log("POLICE_HITBOX_BEFORE",JSON.stringify(beforeContract));if(beforeContract.hitboxVisible!==false||beforeContract.hitboxKind!=="police-drone")throw Error(`unexpected baseline ${JSON.stringify(beforeContract)}`);
 const cdp=await page.createCDPSession();let dragging=true,step=0;await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:setup.x,y:setup.y,id:9,radiusX:4,radiusY:4,force:.7}]});const mover=(async()=>{while(dragging){step++;await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:setup.x+(step%5)-2,y:setup.y+((step*2)%5)-2,id:9,radiusX:4,radiusY:4,force:.7}]}).catch(()=>{});await sleep(34);}})();
 let failure=null,lastShots=(await state()).shots;
 for(let cycle=0;cycle<3;cycle++){
  const armed=await page.evaluate(()=>{const wanted=globalThis.__arondightWantedSystem,v=document.querySelector("#viewport"),drone=wanted?.drones?.find?.(d=>d?.active&&d?.root?.visible!==false&&!d?.critical);if(!drone?.hitbox)return null;const mesh=drone.hitbox;mesh.visible=true;mesh.userData.flightFireIgnore=false;mesh.raycast=function(raycaster,out){const distance=.025,point=raycaster.ray.origin.clone().addScaledVector(raycaster.ray.direction,distance);out.push({distance,point,object:this,face:null,faceIndex:0});};return{index:drone.index,before:Number(v.dataset.wantedPoliceKills||wanted.state?.policeKills||0),hitsBefore:Number(v.dataset.wantedPoliceHits||0),hitboxVisible:mesh.visible};});
  if(!armed){await sleep(450);cycle--;continue;}const deadline=performance.now()+5000;let killed=false;while(performance.now()<deadline){await sleep(60);const s=await state();if(s.kills>armed.before){killed=true;console.log(`POLICE_AB kill ${cycle+1}/3 ${JSON.stringify({armed,s})}`);lastShots=s.shots;break;}if(errors.length||s.walkDead||s.dead||s.aim==="0"){failure={cycle:cycle+1,armed,state:s,errors:[...errors]};break;}if(s.shots>lastShots)lastShots=s.shots;}
  if(failure)break;if(!killed){failure={cycle:cycle+1,armed,state:await state(),errors:[...errors],timeout:true};break;}
 }
 const final=await state();console.log("POLICE_HITBOX_AFTER",JSON.stringify(final));dragging=false;await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]}).catch(()=>{});await mover;
 if(errors.length)throw Error(`TARGET_EXCEPTION ${errors.join(" | ")}`);if(failure)throw Error(`POLICE_AB_FAILURE ${JSON.stringify(failure)}`);if(final.hits<3||final.kills<3)throw Error(`POLICE_AB_NOT_PROVEN ${JSON.stringify(final)}`);console.log(`ROOT_CAUSE_PROVEN hidden-hitbox visibility contract: ${JSON.stringify({beforeContract,final})}`);
}finally{await browser.close();}
