import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader","--autoplay-policy=no-user-gesture-required"]}),page=await browser.newPage(),sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));

try{
  await page.setViewport({width:844,height:390,deviceScaleFactor:1});await page.goto(url.href,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&document.body.classList.contains("solo-flight")&&globalThis.__arondightGameplayDirector&&globalThis.__arondightWantedSystem&&document.querySelector("#gameplayContractButton"),{timeout:30000});
  await page.evaluate(()=>{const api=globalThis.__arondightGameplayDirector;let guard=0;while(api.state.contract.id!=="hot-escape"&&guard++<8)api.cycleContract();api.record({type:"reset"});});
  const initial=await page.evaluate(()=>{const v=document.querySelector("#viewport"),card=document.querySelector("#gameplayContractHud").getBoundingClientRect(),bar=document.querySelector("#soloTopbar").getBoundingClientRect(),left=document.querySelector("#soloLeft").getBoundingClientRect();return{loop:v.dataset.gameplayLoop,ethics:v.dataset.gameplayRewardEthics,flow:v.dataset.gameplayFlowAssist,contract:v.dataset.gameplayContract,scoreParent:document.querySelector("#gameplayScorePill")?.parentElement?.id,scoreText:document.querySelector("#gameplayScorePill")?.textContent,card:{left:card.left,top:card.top,right:card.right,bottom:card.bottom},topbar:{bottom:bar.bottom},left:{top:left.top}};});
  if(initial.loop!=="skill-risk-bank-contracts-v1"||initial.ethics!=="guaranteed-progress+no-near-miss+no-monetization-v1"||initial.flow!=="comeback-only-never-above-baseline-v1"||initial.contract!=="hot-escape"||initial.scoreParent!=="soloTopbarStatus"||!initial.scoreText?.includes("S 0")||initial.card.left<0||initial.card.right>844||initial.card.top<initial.topbar.bottom-1||initial.card.bottom>initial.left.top+1)throw new Error(`fun-loop HUD/layout contract failed: ${JSON.stringify(initial)}`);

  await page.evaluate(()=>dispatchEvent(new CustomEvent("arondight:world-kill",{detail:{id:"fun-car-1",kind:"car",network:true}})));await page.waitForFunction(()=>Number(document.querySelector("#viewport")?.dataset.gameplayAtRisk||0)>0&&Number(document.querySelector("#viewport")?.dataset.gameplayCombo||0)===1,{timeout:3000});const first=await page.evaluate(()=>{const v=document.querySelector("#viewport");return{risk:Number(v.dataset.gameplayAtRisk),combo:Number(v.dataset.gameplayCombo),momentum:Number(v.dataset.gameplayMomentum),pill:document.querySelector("#gameplayScorePill")?.textContent||""};});if(first.risk<140||first.combo!==1||first.momentum!==1||!first.pill.includes("R "))throw new Error(`first skill reward was not readable: ${JSON.stringify(first)}`);

  await page.click("#gameplayContractButton");const sampleBefore=Number(await page.$eval("#viewport",v=>v.dataset.combatAudioSamplePlays||0));await page.evaluate(()=>{const api=globalThis.__arondightGameplayDirector;api.record({type:"worldKill",kind:"car",stars:2});api.record({type:"worldKill",kind:"bus",stars:2});api.record({type:"policeKill",stars:2});});await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.gameplayOverdrive==="1"&&Number(document.querySelector("#viewport")?.dataset.gameplayAtRisk||0)>1000,{timeout:3000});await sleep(120);const surge=await page.evaluate(before=>{const v=document.querySelector("#viewport"),hot=[...document.querySelectorAll("#gameplayMomentum>i.hot")].length;return{risk:Number(v.dataset.gameplayAtRisk),combo:Number(v.dataset.gameplayCombo),overdrive:v.dataset.gameplayOverdrive,multiplier:Number(v.dataset.gameplayMultiplier),momentum:Number(v.dataset.gameplayMomentum),hot,toast:Boolean(document.querySelector("#gameplayToast.active")),bank:v.dataset.combatAudioBank,oscillators:Number(v.dataset.combatAudioRuntimeOscillators||0),samples:Number(v.dataset.combatAudioSamplePlays||0),sampleBefore:before};},sampleBefore);if(surge.overdrive!=="1"||surge.combo!==4||surge.multiplier<2.4||surge.hot!==4||surge.risk<1000||surge.bank!=="prebaked-pcm-buffer-bank-v1"||surge.oscillators!==0||surge.samples<=surge.sampleBefore)throw new Error(`guaranteed momentum/overdrive reward failed: ${JSON.stringify(surge)}`);

  await page.evaluate(()=>globalThis.__arondightWantedSystem.reportCrime({id:"fun-hot-escape",kind:"bus",severity:5}));await page.waitForFunction(()=>Number(document.querySelector("#viewport")?.dataset.wantedStars||0)>=2,{timeout:3000});await page.evaluate(()=>globalThis.__arondightWantedSystem.clear("escaped"));await page.waitForFunction(()=>Number(document.querySelector("#viewport")?.dataset.gameplayAtRisk||0)===0&&Number(document.querySelector("#viewport")?.dataset.gameplayScore||0)>0,{timeout:3000});const banked=await page.evaluate(()=>{const v=document.querySelector("#viewport"),s=globalThis.__arondightGameplayDirector.state;return{score:Number(v.dataset.gameplayScore),risk:Number(v.dataset.gameplayAtRisk),contract:s.contract.id,complete:s.contractComplete,completed:s.contractsCompleted,high:Number(v.dataset.gameplayHighScore)};});if(banked.score<1500||banked.risk!==0||banked.high<banked.score)throw new Error(`escape did not bank the risk/reward run: ${JSON.stringify(banked)}`);

  await page.evaluate(()=>globalThis.__arondightWalkMode.setMode("foot",{persist:false}));await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.playerMode==="foot",{timeout:3000});const beforeCycle=await page.evaluate(()=>({shots:Number(document.querySelector("#viewport")?.dataset.walkShots||0),contract:globalThis.__arondightGameplayDirector.state.contract.id}));await page.click("#gameplayContractButton");await sleep(120);const afterCycle=await page.evaluate(()=>({shots:Number(document.querySelector("#viewport")?.dataset.walkShots||0),contract:globalThis.__arondightGameplayDirector.state.contract.id}));if(afterCycle.contract===beforeCycle.contract||afterCycle.shots!==beforeCycle.shots)throw new Error(`contract choice fired the FPS weapon or did not change: ${JSON.stringify({beforeCycle,afterCycle})}`);

  await page.evaluate(()=>dispatchEvent(new CustomEvent("arondight:drone-destroyed",{detail:{source:"fun-smoke"}})));await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.gameplayPoliceDamageScale==="0.88",{timeout:2000});const comeback=await page.evaluate(()=>({scale:Number(document.querySelector("#viewport")?.dataset.gameplayPoliceDamageScale),hint:document.querySelector("#gameplayRiskHint")?.textContent||"",mercy:globalThis.__arondightGameplayDirector.state.mercy}));if(comeback.scale!==.88||comeback.mercy!==1||!comeback.hint.includes("COMEBACK"))throw new Error(`transparent comeback-only assistance failed: ${JSON.stringify(comeback)}`);
  console.log(`Gameplay fun browser smoke passed: compact HUD, player-chosen contracts, skill combo, guaranteed overdrive, risk/bank escape payout, buffered reward audio, FPS-safe UI and comeback-only assist: ${JSON.stringify({initial,first,surge,banked,beforeCycle,afterCycle,comeback})}`);
}finally{await browser.close();}
