import puppeteer from "puppeteer-core";
import {mkdir} from "node:fs/promises";

const input=process.argv[2]||"https://kurzlernen.de/drone_simulator.html",base=new URL(input),executablePath=process.env.CHROME_BIN;
if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader","--autoplay-policy=no-user-gesture-required"]});
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function bounded(promise,ms,label){let timer=0;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(`${label} timed out after ${ms} ms`)),ms);})]);}finally{clearTimeout(timer);}}
async function makePhone(label){const context=await browser.createBrowserContext(),page=await context.newPage(),url=new URL(base.href);url.searchParams.set("multiplayer-phone",label);await page.evaluateOnNewDocument(()=>{globalThis.__vsLiveEvents=[];addEventListener("arondight45:vs-network",event=>{const d=event?.detail||{};globalThis.__vsLiveEvents.push({stage:String(d.stage||""),transport:String(d.transport||""),roomId:String(d.roomId||""),peerCount:Number(d.peerCount)||0,reason:String(d.reason||""),error:String(d.error||"")});if(globalThis.__vsLiveEvents.length>50)globalThis.__vsLiveEvents.splice(0,globalThis.__vsLiveEvents.length-50);});});await page.setUserAgent(`Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Mobile/15E148 Safari/604.1 ${label}`);await page.setViewport({width:844,height:390,deviceScaleFactor:1,isMobile:true,hasTouch:true});await bounded(page.goto(url.href,{waitUntil:"load",timeout:45000}),50000,`${label} goto`);await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&globalThis.__arondightRealWorld&&document.querySelector("#mobileGameplayMultiplayer")&&document.querySelector("#lanVsButton"),{timeout:45000});const ui=await bounded(page.evaluate(()=>{const mobile=document.querySelector("#mobileGameplayMultiplayer"),source=document.querySelector("#lanVsButton"),topbar=document.querySelector("#soloTopbar"),v=document.querySelector("#viewport");return{mobileDisplay:getComputedStyle(mobile).display,sourceExists:Boolean(source),topbarDisplay:getComputedStyle(topbar).display,mobileUi:v?.dataset.mobileMultiplayerUi,state:v?.dataset.mobileMultiplayerState};}),5000,`${label} ui snapshot`);if(ui.mobileDisplay==="none"||!ui.sourceExists||ui.topbarDisplay!=="none"||ui.mobileUi!=="visible-v1")throw new Error(`${label} mobile multiplayer entry is not restored: ${JSON.stringify(ui)}`);return{context,page,label};}
async function snapshot(page){return bounded(page.evaluate(()=>{const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport"),button=document.querySelector("#mobileGameplayMultiplayer"),status=document.querySelector("#mobileGameplayMultiplayerStatus"),finder=b?.vsSession,active=finder?.active||finder;let currentTaggedPeers=0,remoteHumans=0,visibleRemoteHumans=0;b?.threeScene?.traverse?.(node=>{if(node.userData?.vsMultiplayerPeer&&node.visible!==false)currentTaggedPeers++;if(node.userData?.vsHumanAvatar&&!node.userData?.localHumanAvatar){remoteHumans++;if(node.visible!==false)visibleRemoteHumans++;}});const legacy=b?.vsPeerMesh,legacyPeerVisible=Boolean(legacy?.parent&&legacy.visible),markers=[...document.querySelectorAll(".vs-player-marker")],visibleMarkers=markers.filter(el=>getComputedStyle(el).display!=="none"&&getComputedStyle(el).visibility!=="hidden").length,poseAge=Number(v?.dataset.vsPoseAgeMs),remoteVisuals=(legacyPeerVisible?1:0)+visibleRemoteHumans+currentTaggedPeers+visibleMarkers;return{connected:Boolean(b?.vsConnected),starting:Boolean(b?.vsStarting),hasSession:Boolean(finder),vsPlayers:Number(v?.dataset.vsPlayerCount)||0,vsPeers:Number(v?.dataset.vsPeerCount)||0,mobileState:v?.dataset.mobileMultiplayerState||"",mobilePlayers:Number(v?.dataset.mobileMultiplayerPlayers)||0,intent:v?.dataset.mobileMultiplayerIntent||"",recovery:v?.dataset.mobileMultiplayerRecovery||"",retryCount:Number(v?.dataset.mobileMultiplayerRetryCount)||0,buttonText:button?.textContent?.trim()||"",buttonState:button?.dataset.state||"",statusText:status?.textContent?.trim()||"",statusDisplay:status?getComputedStyle(status).display:"none",legacyPeerVisible,legacyPeerTag:legacy?.userData?.vsPeer===true,remoteHumans,visibleRemoteHumans,currentTaggedPeers,visibleMarkers,remoteVisuals,poseAge:Number.isFinite(poseAge)?poseAge:null,poseMode:v?.dataset.vsPoseMode||"",poseFrame:v?.dataset.vsPoseFrame||"",frameMismatch:Number(v?.dataset.vsPoseFrameMismatch)||0,roomIds:Array.isArray(finder?.roomIds)?finder.roomIds.slice():[],stageRoomIds:Array.isArray(finder?.stageRoomIds)?finder.stageRoomIds.slice():[],activeRoom:String(active?.roomId||""),transport:String(active?.transportName||""),networkEvents:(globalThis.__vsLiveEvents||[]).slice(-20)};}),5000,"multiplayer snapshot");}
async function waitConnected(page,label,timeout=75000){const end=Date.now()+timeout;let last=null;while(Date.now()<end){last=await snapshot(page);const poseRendered=last.remoteVisuals>=1&&(last.legacyPeerVisible||last.poseAge!==null||last.visibleRemoteHumans>=1||last.currentTaggedPeers>=1);if(last.connected&&last.mobileState==="connected"&&last.mobilePlayers>=2&&last.vsPlayers>=2&&last.vsPeers>=1&&poseRendered&&last.buttonState==="connected"&&last.statusDisplay!=="none")return last;await pause(300);}throw new Error(`${label} did not reach connected two-player rendered state: ${JSON.stringify(last)}`);}
async function closeSafely(item){if(!item?.context)return;try{await bounded(item.context.close(),3000,`${item.label} context close`);}catch{}}

let a,b;
try{
  [a,b]=await bounded(Promise.all([makePhone("phone-a"),makePhone("phone-b")]),65000,"create two mobile clients");
  await bounded(Promise.all([a.page.click("#mobileGameplayMultiplayer"),b.page.click("#mobileGameplayMultiplayer")]),5000,"start multiplayer on both phones");
  await pause(150);
  const finding=await Promise.all([snapshot(a.page),snapshot(b.page)]);
  if(finding.some(x=>!x.hasSession&&x.mobileState!=="finding"))throw new Error(`MULTI button did not enter the real VS discovery path: ${JSON.stringify(finding)}`);
  const [sa,sb]=await bounded(Promise.all([waitConnected(a.page,"phone-a"),waitConnected(b.page,"phone-b")]),80000,"dual-phone connection");
  if(!(sa.buttonText.includes("2P")&&sb.buttonText.includes("2P")&&sa.statusText.includes("P 2")&&sb.statusText.includes("P 2")))throw new Error(`connected mobile multiplayer status is incomplete: ${JSON.stringify({sa,sb})}`);
  if(!(sa.remoteVisuals>=1&&sb.remoteVisuals>=1))throw new Error(`both clients must render a remote multiplayer participant: ${JSON.stringify({sa,sb})}`);
  await mkdir("artifacts",{recursive:true});
  await bounded(Promise.all([a.page.screenshot({path:"artifacts/mobile-multiplayer-a.png",captureBeyondViewport:false}),b.page.screenshot({path:"artifacts/mobile-multiplayer-b.png",captureBeyondViewport:false})]),15000,"multiplayer screenshots");
  await bounded(Promise.all([a.page.click("#mobileGameplayMultiplayer"),b.page.click("#mobileGameplayMultiplayer")]),5000,"stop multiplayer on both phones");
  await pause(500);
  const stopped=await Promise.all([snapshot(a.page),snapshot(b.page)]);
  if(stopped.some(x=>x.hasSession||x.connected||x.mobileState!=="offline"||x.intent!=="off"))throw new Error(`mobile multiplayer did not stop cleanly: ${JSON.stringify(stopped)}`);
  console.log(`Dual-mobile live multiplayer passed. ${JSON.stringify({phoneA:sa,phoneB:sb,stopped})}`);
}catch(error){let diagnostic={};try{diagnostic={phoneA:a?await snapshot(a.page):null,phoneB:b?await snapshot(b.page):null};}catch{}console.error(`Dual-mobile multiplayer diagnostic: ${JSON.stringify(diagnostic)}`);throw error;
}finally{
  await Promise.allSettled([closeSafely(a),closeSafely(b)]);
  try{await bounded(browser.close(),4000,"browser close");}catch{try{browser.process()?.kill("SIGKILL");}catch{}}
}
