import puppeteer from "puppeteer-core";
import {mkdir} from "node:fs/promises";

const input=process.argv[2]||"https://kurzlernen.de/drone_simulator.html",url=new URL(input),executablePath=process.env.CHROME_BIN;
// This smoke covers the drone start; the game itself starts on foot by default.
if(!url.searchParams.has("start"))url.searchParams.set("start","drone");
if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage(),cdp=await page.createCDPSession();
await page.setUserAgent("Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Mobile/15E148 Safari/604.1");
const pause=ms=>page.evaluate(delay=>new Promise(resolve=>setTimeout(resolve,delay)),ms);
const touch=(p,id=1)=>({x:p.x,y:p.y,radiusX:2,radiusY:2,force:1,id});
async function drag(selector,screenDirection,scale=.45,holdMs=120){const points=await page.$eval(selector,(el,args)=>{const r=el.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,span=Math.min(r.width,r.height)*args.scale;return{start:{x:cx,y:cy},end:args.dir==="up"?{x:cx+span,y:cy}:args.dir==="right"?{x:cx,y:cy+span}:{x:cx,y:cy}};},{dir:screenDirection,scale});await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[touch(points.start)]});await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[touch(points.end)]});await pause(holdMs);const snapshot=await page.$eval("#viewport",v=>({move:v.dataset.walkMove,yaw:Number(v.dataset.walkYaw),pitch:Number(v.dataset.walkPitch),contract:v.dataset.walkTouchContract,semantics:v.dataset.walkStickSemantics,aimCoordinates:v.dataset.walkAimStickCoordinates}));await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await pause(60);return snapshot;}
async function armDroneAtomically(timeout=30000){const deadline=Date.now()+timeout;while(Date.now()<deadline){const state=await page.evaluate(()=>{const b=document.querySelector("#soloArm"),fc=document.querySelector("#soloState")?.textContent?.trim(),mode=document.querySelector("#viewport")?.dataset.playerMode,ui=document.querySelector("#mobileGameplayMode")?.textContent?.trim();if(fc==="ARMED")return{armed:true,clicked:false,disabled:Boolean(b?.disabled),fc,mode,ui};if(mode==="drone"&&ui==="DRONE"&&b&&!b.disabled&&b.textContent.trim()==="ARM"){b.click();return{armed:false,clicked:true,disabled:false,fc,mode,ui};}return{armed:false,clicked:false,disabled:Boolean(b?.disabled),fc,mode,ui};});if(state.armed)return state;if(state.clicked){try{await page.waitForFunction(()=>document.querySelector("#soloState")?.textContent?.trim()==="ARMED",{timeout:10000});return await page.evaluate(()=>({armed:true,clicked:true,disabled:Boolean(document.querySelector("#soloArm")?.disabled),fc:document.querySelector("#soloState")?.textContent?.trim(),mode:document.querySelector("#viewport")?.dataset.playerMode,ui:document.querySelector("#mobileGameplayMode")?.textContent?.trim()}));}catch{}}await pause(100);}throw new Error(`drone did not become atomically armable: ${JSON.stringify(await page.evaluate(()=>({destroyed:Boolean(globalThis.__arondightDroneDamageModel?.destroyed),canDeploy:Boolean(globalThis.__arondightDroneDamageModel?.canDeploy),disabled:Boolean(document.querySelector("#soloArm")?.disabled),button:document.querySelector("#soloArm")?.textContent?.trim(),fc:document.querySelector("#soloState")?.textContent?.trim(),mode:document.querySelector("#viewport")?.dataset.playerMode,ui:document.querySelector("#mobileGameplayMode")?.textContent?.trim()})))}`);}

try{
  await page.setViewport({width:390,height:844,deviceScaleFactor:1,isMobile:true,hasTouch:true});
  await page.goto(url.href,{waitUntil:"load",timeout:45000});
  await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&globalThis.__arondightWalkMode&&document.querySelector("#mobileGameplayDock"),{timeout:90000});
  await page.waitForFunction(()=>document.querySelector("#soloArm")&&!document.querySelector("#soloArm").disabled,{timeout:30000});
  await page.evaluate(()=>globalThis.__arondightWalkMode.setMode("foot",{persist:false}));
  await page.waitForFunction(()=>{const v=document.querySelector("#viewport");return v?.dataset.playerMode==="foot"&&v.dataset.soloOrientation==="css-landscape"&&v.dataset.mobileGameplayUi==="flight-first-v1"&&v.dataset.walkTouchContract==="drone-normalized-pointer-origin-v2"&&document.querySelector("#footMove")&&document.querySelector("#footLook");},{timeout:8000});

  const up=await drag("#footMove","up"),right=await drag("#footMove","right"),parse=value=>String(value||"").split(",").map(Number),upMove=parse(up.move),rightMove=parse(right.move);
  if(!(upMove[1]<-.45&&Math.abs(upMove[0])<.22))throw new Error(`visual UP must be FPV forward: ${JSON.stringify({up,upMove})}`);
  if(!(rightMove[0]>.45&&Math.abs(rightMove[1])<.22))throw new Error(`visual RIGHT must be FPV strafe-right: ${JSON.stringify({right,rightMove})}`);
  if(up.semantics!=="drone-normalizedPointer-v1"||right.semantics!=="drone-normalizedPointer-v1")throw new Error(`FPV left stick is not using drone pointer semantics: ${JSON.stringify({up,right})}`);
  await page.waitForFunction(()=>{const v=document.querySelector("#viewport");return v?.dataset.walkCollision==="box3d-capsule-mover-v2"&&v.dataset.walkCollisionShape==="capsule";},{timeout:5000});

  await page.evaluate(()=>globalThis.__arondightWalkMode.setPose({yaw:0,pitch:0}));
  const look=await drag("#footLook","right",.72,260);
  if(!(look.yaw>.08&&Math.abs(look.pitch)<.08))throw new Error(`right-stick visual RIGHT must yaw right without pitching: ${JSON.stringify(look)}`);
  if(look.semantics!=="drone-normalizedPointer-v1"||look.aimCoordinates!=="drone-normalizedPointer-v2")throw new Error(`FPV right stick is not using the authoritative drone pointer semantics: ${JSON.stringify(look)}`);

  const multiPoints=await page.evaluate(()=>{const move=document.querySelector("#footMove"),view=document.querySelector("#viewport"),r=move.getBoundingClientRect(),v=view.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,span=Math.min(r.width,r.height)*.62;return{moveStart:{x:cx,y:cy},moveForward:{x:cx+span,y:cy},fire:{x:v.left+v.width*.52,y:v.top+v.height*.46}};});
  const shotsBeforeMulti=await page.$eval("#viewport",v=>Number(v.dataset.walkEnhancedShots)||0);
  await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[touch(multiPoints.moveStart,11)]});
  await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[touch(multiPoints.moveForward,11)]});await pause(90);
  const movingBeforeFire=await page.$eval("#viewport",v=>({move:v.dataset.walkMove,isolation:v.dataset.walkMultiTouchMoveIsolation}));
  await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[touch(multiPoints.moveForward,11),touch(multiPoints.fire,12)]});await pause(70);
  const movingWhileFiring=await page.$eval("#viewport",v=>({move:v.dataset.walkMove,shots:Number(v.dataset.walkEnhancedShots)||0,isolation:v.dataset.walkMultiTouchMoveIsolation}));
  await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[touch(multiPoints.fire,12)]});await pause(70);
  const movingAfterFireLift=await page.$eval("#viewport",v=>({move:v.dataset.walkMove,shots:Number(v.dataset.walkEnhancedShots)||0}));
  await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[touch(multiPoints.moveForward,11)]});await pause(80);
  for(const snap of[movingBeforeFire,movingWhileFiring,movingAfterFireLift]){const m=parse(snap.move);if(!(m[1]<-.42&&Math.abs(m[0])<.25))throw new Error(`second touch interrupted left-stick movement: ${JSON.stringify({movingBeforeFire,movingWhileFiring,movingAfterFireLift})}`);}
  if(!(movingWhileFiring.shots>shotsBeforeMulti&&movingAfterFireLift.shots>=movingWhileFiring.shots&&movingWhileFiring.isolation==="pointer-id-owned-v1"))throw new Error(`multitouch fire/move ownership contract failed: ${JSON.stringify({shotsBeforeMulti,movingBeforeFire,movingWhileFiring,movingAfterFireLift})}`);

  const before=await page.$eval("#viewport",v=>({yaw:Number(v.dataset.walkYaw),pitch:Number(v.dataset.walkPitch),shots:Number(v.dataset.walkEnhancedShots)||0}));
  const centre=await page.$eval("#viewport",v=>{const r=v.getBoundingClientRect();return{x:r.left+r.width*.52,y:r.top+r.height*.46};});
  await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[touch(centre)]});await pause(40);await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});
  await page.waitForFunction(()=>{const v=document.querySelector("#viewport"),weight=Number(v?.dataset.walkWeaponAimWeight),error=Number(v?.dataset.walkWeaponAimErrorDeg);return weight>=.999&&Number.isFinite(error)&&error<.5;},{timeout:1800});await pause(60);
  const after=await page.$eval("#viewport",v=>({yaw:Number(v.dataset.walkYaw),pitch:Number(v.dataset.walkPitch),shots:Number(v.dataset.walkEnhancedShots)||0,screen:v.dataset.walkScreenTouch,fireVector:v.dataset.walkWeaponFireVector,aimSource:v.dataset.walkWeaponAimSource,touchVector:v.dataset.walkWeaponTouchVector,alignment:v.dataset.walkWeaponVectorAlignment,aimWeight:Number(v.dataset.walkWeaponAimWeight),aimErrorDeg:Number(v.dataset.walkWeaponAimErrorDeg),handAnchor:v.dataset.walkWeaponHandAnchor}));
  if(Math.abs(after.yaw-before.yaw)>.015||Math.abs(after.pitch-before.pitch)>.015)throw new Error(`screen touch outside sticks moved camera: ${JSON.stringify({before,after})}`);
  if(!(after.shots>before.shots&&after.screen==="fire-only-v1"&&after.fireVector==="touch-screen-ray-v5"&&after.aimSource==="screen-touch"&&after.touchVector==="screen-ray+hand-anchor-v1"))throw new Error(`screen touch did not use the authoritative shot/vector path: ${JSON.stringify({before,after})}`);
  if(!(after.alignment==="exact-screen-ray-from-hand-anchor-v5"&&after.aimWeight>=.999&&after.aimErrorDeg<.5&&after.handAnchor==="position-fixed-rotation-only-v1"))throw new Error(`viewmodel barrel is not collinear with the shot ray: ${JSON.stringify(after)}`);

  const fpvUi=await page.evaluate(()=>{const contract=getComputedStyle(document.querySelector("#gameplayContractHud")),v=document.querySelector("#viewport"),buttons=[...document.querySelectorAll("#mobileGameplayDock button")],buttonLayout=buttons.map(b=>{const s=getComputedStyle(b);return{text:b.textContent.trim(),display:s.display,align:s.alignItems,justify:s.justifyContent,padTop:s.paddingTop,padBottom:s.paddingBottom,lineHeight:s.lineHeight};});return{fire:getComputedStyle(document.querySelector("#footFire")).display,fireContract:v?.dataset.walkFireButton,lookZone:getComputedStyle(document.querySelector("#footLookZone")).display,contractVisibility:contract.visibility,contractOpacity:contract.opacity,score:getComputedStyle(document.querySelector("#gameplayScorePill")).display,dock:buttons.map(b=>b.textContent.trim()),buttonLayout,spawnGuard:v?.dataset.spawnVisibilityGuard,collision:v?.dataset.walkCollision,collisionShape:v?.dataset.walkCollisionShape,collisionMask:v?.dataset.walkCollisionMask,collisionShots:v?.dataset.walkCollisionShots,collisionRadius:v?.dataset.walkCollisionRadiusM,collisionHeight:v?.dataset.walkCollisionHeightM};});
  if(fpvUi.fire!=="none"||fpvUi.fireContract!=="screen-touch-only-hidden-v1"||fpvUi.lookZone!=="none"||fpvUi.contractVisibility!=="hidden"||Number(fpvUi.contractOpacity)!==0||fpvUi.score!=="none")throw new Error(`flight-first FPV overlays still visible: ${JSON.stringify(fpvUi)}`);
  if(fpvUi.dock.length!==3||!fpvUi.dock.includes("SETTINGS")||fpvUi.dock.some(x=>x==="MENU"||x==="START"))throw new Error(`mobile dock is not mode/weapon/settings only: ${JSON.stringify(fpvUi.dock)}`);
  if(fpvUi.spawnGuard!=="people-hold+spawn-gate-presented-camera-v4")throw new Error(`spawn visibility guard is not active: ${JSON.stringify(fpvUi)}`);
  if(!(fpvUi.collision==="box3d-capsule-mover-v2"&&fpvUi.collisionShape==="capsule"&&fpvUi.collisionMask==="terrain-walls-only"&&fpvUi.collisionShots==="pass-through"&&Number(fpvUi.collisionRadius)>=.27&&Number(fpvUi.collisionHeight)>=1.7))throw new Error(`player is not using terrain-only Box3D capsule collision: ${JSON.stringify(fpvUi)}`);
  if(fpvUi.buttonLayout.some(b=>b.display!=="none"&&(b.display!=="flex"||b.align!=="center"||b.justify!=="center"||b.padTop!==b.padBottom)))throw new Error(`mobile button typography is not vertically centered: ${JSON.stringify(fpvUi.buttonLayout)}`);

  await page.click("#mobileGameplaySettings");await page.waitForFunction(()=>document.querySelector("dialog.phone-settings-dialog[open]"),{timeout:3000});
  const settings=await page.$eval("dialog.phone-settings-dialog[open]",d=>{const start=d.scrollTop;d.scrollTop=d.scrollHeight;return{clientHeight:d.clientHeight,scrollHeight:d.scrollHeight,scrollTop:d.scrollTop,overflowY:getComputedStyle(d).overflowY,touchAction:getComputedStyle(d).touchAction,start};});
  if(!(settings.clientHeight>120&&settings.scrollHeight>=settings.clientHeight&&settings.overflowY==="auto"&&settings.touchAction.includes("pan-y")&&(settings.scrollHeight===settings.clientHeight||settings.scrollTop>0)))throw new Error(`landscape settings are not fully scrollable: ${JSON.stringify(settings)}`);
  await page.$eval("dialog.phone-settings-dialog[open]",d=>d.close());

  const droneReset=await page.evaluate(()=>{const damage=globalThis.__arondightDroneDamageModel;const before={destroyed:Boolean(damage?.destroyed),canDeploy:Boolean(damage?.canDeploy)};damage?.reset?.();const mode=globalThis.__arondightWalkMode.setMode("drone",{persist:false,reason:"mobile-regression-return"});return{before,after:{destroyed:Boolean(damage?.destroyed),canDeploy:Boolean(damage?.canDeploy)},mode};});
  if(!(droneReset.after.destroyed===false&&droneReset.after.canDeploy===true&&droneReset.mode==="drone"))throw new Error(`drone reset/return path failed: ${JSON.stringify(droneReset)}`);
  await page.setViewport({width:844,height:390,deviceScaleFactor:1,isMobile:true,hasTouch:true});await pause(300);
  await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.playerMode==="drone"&&document.querySelector("#mobileGameplayMode")?.textContent==="DRONE",{timeout:10000});
  const droneUi=await page.evaluate(()=>{const contract=getComputedStyle(document.querySelector("#gameplayContractHud")),v=document.querySelector("#viewport");return{topbar:getComputedStyle(document.querySelector("#soloTopbar")).display,arm:getComputedStyle(document.querySelector("#soloArm")).display,armText:document.querySelector("#soloArm")?.textContent?.trim(),contractVisibility:contract.visibility,contractOpacity:contract.opacity,buttons:[...document.querySelectorAll("#mobileGameplayDock button")].map(b=>b.textContent.trim()),cameraExtra:v?.dataset.fpvViewExtraUpOffsetM||null,missileContract:v?.dataset.droneMissileContract,spawnGuard:v?.dataset.spawnVisibilityGuard};});
  if(droneUi.topbar!=="none"||droneUi.arm==="none"||droneUi.contractVisibility!=="hidden"||Number(droneUi.contractOpacity)!==0||droneUi.buttons.length!==3)throw new Error(`drone HUD is not flight-first: ${JSON.stringify(droneUi)}`);
  if(droneUi.missileContract!=="tap-ray-fixed-after-launch-v1"||droneUi.spawnGuard!=="people-hold+spawn-gate-presented-camera-v4")throw new Error(`drone direct-fire/spawn contracts missing: ${JSON.stringify(droneUi)}`);
  const armResult=await armDroneAtomically();await pause(250);
  const missile=await page.evaluate(()=>{const v=document.querySelector("#viewport"),r=v.getBoundingClientRect(),fired=globalThis.__arondightDroneWeapons?.fireMissile?.({clientX:r.left+r.width*.55,clientY:r.top+r.height*.44,source:"mobile-regression"});return{fired:Boolean(fired),guidance:v.dataset.droneMissileGuidance,direction:v.dataset.droneMissileDirection,active:Number(v.dataset.droneActiveMissiles)||0};});
  if(!(missile.fired&&missile.guidance==="fixed-screen-ray-no-homing-v1"&&missile.direction&&missile.active>=1))throw new Error(`missile is not fixed to the launch screen ray: ${JSON.stringify(missile)}`);
  await mkdir("artifacts",{recursive:true});await page.screenshot({path:"artifacts/mobile-gameplay.png",captureBeyondViewport:false});
  console.log(`Flight-first mobile regression passed. ${JSON.stringify({upMove,rightMove,look,movingBeforeFire,movingWhileFiring,movingAfterFireLift,before,after,fpvUi,settings,droneReset,droneUi,armResult,missile})}`);
}finally{await browser.close();}