import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage();
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
try{
  await page.setUserAgent("Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Mobile/15E148 Safari/604.1");
  await page.setViewport({width:844,height:390,deviceScaleFactor:1});await page.goto(url.href,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready"),{timeout:30000});await page.waitForFunction(()=>globalThis.__arondightWalkMode&&document.querySelector("#playerModeButton")&&document.querySelectorAll(".foot-stick").length===2,{timeout:8000});
  await page.click("#playerModeButton");await page.waitForFunction(()=>document.body.classList.contains("on-foot-mode")&&document.querySelector("#viewport")?.dataset.playerMode==="foot",{timeout:4000});
  const ui=await page.evaluate(()=>({sticks:[...document.querySelectorAll(".foot-stick")].map(el=>getComputedStyle(el).display),leftPointer:getComputedStyle(document.querySelector("#soloLeft")).pointerEvents,rightPointer:getComputedStyle(document.querySelector("#soloRight")).pointerEvents,architecture:document.querySelector("#viewport")?.dataset.walkArchitecture,lifeLayer:Boolean(document.querySelector('[name="WORLD_EXPERIENCE_LIFE"]'))||Boolean(globalThis.__arondightRealWorld?.threeScene?.getObjectByName?.("WORLD_EXPERIENCE_LIFE")),clones:(()=>{let n=0;globalThis.__arondightRealWorld?.threeScene?.traverse?.(x=>{if(x.userData?.worldPopulationClone)n++;});return n;})()}));
  if(ui.sticks.length!==2||ui.sticks.some(x=>x==="none")||ui.leftPointer!=="none"||ui.rightPointer!=="none"||ui.architecture!=="camera-input-overlay-v2"||ui.lifeLayer||ui.clones)throw new Error(`WALK isolation/UI contract failed: ${JSON.stringify(ui)}`);

  const beforeMove=await page.$eval("#viewport",v=>v.dataset.walkPosition||"");const moveBox=await page.$eval("#footMove",el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height};});await page.mouse.move(moveBox.x+moveBox.w/2,moveBox.y+moveBox.h/2);await page.mouse.down();await page.mouse.move(moveBox.x+moveBox.w/2,moveBox.y+moveBox.h*.12,{steps:4});await sleep(320);await page.mouse.up();const afterMove=await page.$eval("#viewport",v=>v.dataset.walkPosition||"");if(!beforeMove||beforeMove===afterMove)throw new Error(`left WALK stick did not move player: ${beforeMove} -> ${afterMove}`);

  const yawBefore=Number(await page.$eval("#viewport",v=>v.dataset.walkYaw||0)),lookBox=await page.$eval("#footLook",el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height};});await page.mouse.move(lookBox.x+lookBox.w/2,lookBox.y+lookBox.h/2);await page.mouse.down();await page.mouse.move(lookBox.x+lookBox.w*.88,lookBox.y+lookBox.h/2,{steps:4});await sleep(280);await page.mouse.up();const yawAfter=Number(await page.$eval("#viewport",v=>v.dataset.walkYaw||0));if(Math.abs(yawAfter-yawBefore)<.08)throw new Error(`right WALK stick did not control look: ${yawBefore} -> ${yawAfter}`);

  const before=await page.evaluate(()=>{const v=document.querySelector("#viewport");return{walk:Number(v.dataset.walkShots||0),drone:Number(v.dataset.fireShots||0)};});await page.click("#footFire");await page.waitForFunction(n=>Number(document.querySelector("#viewport")?.dataset.walkShots||0)>n,{timeout:3000},before.walk);const after=await page.evaluate(()=>{const v=document.querySelector("#viewport");return{walk:Number(v.dataset.walkShots||0),drone:Number(v.dataset.fireShots||0)};});if(after.drone!==before.drone)throw new Error(`WALK touch leaked into drone fire: ${before.drone} -> ${after.drone}`);

  const combat=await page.evaluate(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms)),waitFor=async(fn,timeout=8000)=>{const end=performance.now()+timeout;while(performance.now()<end){const v=fn();if(v)return v;await wait(30);}throw Error("walk combat wait timeout");};const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport");b.active=true;b.originLon=9;b.originLat=47;b.minimapFeatures=[{kind:"road",geometryType:"LineString",paths:[[[9,47],[9.0015,47],[9.003,47.0002]]]}];await waitFor(()=>Number(v.dataset.worldTrafficRoutes||0)>=1&&typeof b.registerWorldPopulationHit==="function");let mesh=null;b.threeScene.traverse(node=>{if(!mesh&&node?.isMesh&&node.visible!==false&&node.userData?.worldPopulationKind==="person"&&node.userData?.worldPopulationId)mesh=node;});if(!mesh)throw Error("native pedestrian missing for WALK shot");const p=new THREE.Vector3();mesh.getWorldPosition(p);const x=p.x,y=p.y-2.6,z=1.68,dx=p.x-x,dy=p.y-y,dz=p.z-z,yaw=Math.atan2(dx,dy),pitch=Math.atan2(dz,Math.hypot(dx,dy)),bloodBefore=Number(v.dataset.worldBloodFx||0),ragBefore=Number(v.dataset.worldRagdollSpawns||0);globalThis.__arondightWalkMode.setPose({x,y,yaw,pitch});globalThis.__arondightWalkMode.fire(performance.now()+500);await waitFor(()=>Number(v.dataset.worldBloodFx||0)>bloodBefore&&Number(v.dataset.worldRagdollSpawns||0)>ragBefore);let clones=0;b.threeScene.traverse(node=>{if(node.userData?.worldPopulationClone)clones++;});b.active=false;return{bloodBefore,blood:Number(v.dataset.worldBloodFx||0),ragBefore,rag:Number(v.dataset.worldRagdollSpawns||0),clones};});
  if(combat.blood<=combat.bloodBefore||combat.rag<=combat.ragBefore||combat.clones!==0)throw new Error(`WALK native population combat failed: ${JSON.stringify(combat)}`);
  console.log(`Player WALK browser smoke passed: two visible sticks, isolated drone touch, independent move/look, native pedestrian hit -> blood/ragdoll, zero clone population: ${JSON.stringify({beforeMove,afterMove,yawBefore,yawAfter,combat})}`);
}finally{await browser.close();}
