import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage(),sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));

try{
  await page.setViewport({width:844,height:390,deviceScaleFactor:1,hasTouch:true,isMobile:true});await page.goto(url.href,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&globalThis.__arondightPlayerVitals&&globalThis.__arondightWalkMode&&document.querySelector("#playerModeButton"),{timeout:30000});

  await page.evaluate(()=>{globalThis.__arondightPlayerVitals.player.reset();globalThis.__arondightPlayerVitals.drone.reset();globalThis.__arondightWalkMode.setMode("foot",{persist:false});});await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.playerMode==="foot"&&document.querySelector("#footMove"),{timeout:4000});
  const moveBox=await page.$eval("#footMove",el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height};}),beforeMove=await page.$eval("#viewport",v=>v.dataset.walkPosition||"");
  await page.mouse.move(moveBox.x+moveBox.w/2,moveBox.y+moveBox.h/2);await page.mouse.down();await page.mouse.move(moveBox.x+moveBox.w/2,Math.max(2,moveBox.y-moveBox.h*.8),{steps:5});await sleep(240);
  const fullMove=await page.$eval("#viewport",v=>({contract:v.dataset.walkMoveStick,magnitude:Number(v.dataset.walkMoveStickMagnitude||0),raw:v.dataset.walkMoveStickRaw,move:v.dataset.walkMove,position:v.dataset.walkPosition||"",pilotTargetZ:Number(globalThis.__arondightPlayerVitals?.damageTargets?.().find(target=>target.kind==="player")?.position?.z)}));await page.mouse.up();
  if(fullMove.contract!=="radial-projection-full-range-v2"||fullMove.magnitude<.999||!fullMove.raw?.includes("-1.000")||fullMove.position===beforeMove||fullMove.pilotTargetZ<1.55||fullMove.pilotTargetZ>1.80)throw new Error(`left move stick or first-person pilot target origin failed: ${JSON.stringify({beforeMove,fullMove})}`);

  const separated=await page.evaluate(()=>{const vitals=globalThis.__arondightPlayerVitals;vitals.player.reset();vitals.drone.reset();const start={player:vitals.player.hp,drone:vitals.drone.hp};dispatchEvent(new CustomEvent("arondight:drone-damage",{detail:{damage:35,source:"vitals-smoke"}}));const afterDrone={player:vitals.player.hp,drone:vitals.drone.hp};dispatchEvent(new CustomEvent("arondight:player-damage",{detail:{damage:10,source:"vitals-smoke"}}));return{start,afterDrone,afterPlayer:{player:vitals.player.hp,drone:vitals.drone.hp},contract:document.querySelector("#viewport")?.dataset.playerDroneVitals,hud:Boolean(document.querySelector("#playerVitalsHud"))};});
  if(JSON.stringify(separated.start)!==JSON.stringify({player:100,drone:100})||JSON.stringify(separated.afterDrone)!==JSON.stringify({player:100,drone:65})||JSON.stringify(separated.afterPlayer)!==JSON.stringify({player:90,drone:65})||separated.contract!=="separate-health+replacement-cooldown-v2"||!separated.hud)throw new Error(`pilot and drone health were not independent: ${JSON.stringify(separated)}`);

  await page.evaluate(()=>{const vitals=globalThis.__arondightPlayerVitals;vitals.player.reset();vitals.drone.reset();globalThis.__arondightWalkMode.setMode("drone",{persist:false});});await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.playerVehicleMode==="drone"&&document.querySelector("#viewport")?.dataset.localHumanAvatarVisible==="1"&&globalThis.__arondightPlayerVitals?.damageTargets?.().length===2,{timeout:4000});
  const simultaneous=await page.evaluate(()=>{const vitals=globalThis.__arondightPlayerVitals,vehicle=globalThis.__arondightPlayerVehicleRuntime,targets=vitals.damageTargets(),pilot=vehicle.humanMesh,airframe=vehicle.droneMesh;let pilotPart=null;pilot?.traverse?.(node=>{if(!pilotPart&&node.isMesh)pilotPart=node;});const pilotHandled=vitals.registerHit({object:pilotPart},{damage:10,source:"pilot-mesh-smoke"}),droneHandled=vitals.registerHit({object:airframe},{damage:15,source:"drone-mesh-smoke"}),view=document.querySelector("#viewport"),pilotTarget=targets.find(target=>target.kind==="player"),droneTarget=targets.find(target=>target.kind==="drone");return{targetKinds:targets.map(target=>target.kind).sort(),pilotTargetZ:Number(pilotTarget?.position?.z),droneTargetZ:Number(droneTarget?.position?.z),pilotTag:pilotPart?.userData?.localDamageTarget,droneTag:airframe?.userData?.localDamageTarget,pilotHandled,droneHandled,playerHp:vitals.player.hp,droneHp:vitals.drone.hp,routing:view.dataset.playerVehicleDamageRouting,count:Number(view.dataset.playerVehicleDamageTargetCount||0)};});
  if(JSON.stringify(simultaneous.targetKinds)!==JSON.stringify(["drone","player"])||simultaneous.pilotTargetZ<1.0||simultaneous.pilotTargetZ>1.25||!Number.isFinite(simultaneous.droneTargetZ)||simultaneous.pilotTag!=="player"||simultaneous.droneTag!=="drone"||!simultaneous.pilotHandled||!simultaneous.droneHandled||simultaneous.playerHp!==90||simultaneous.droneHp!==85||simultaneous.routing!=="mesh-tagged-pilot+drone-v1"||simultaneous.count!==2)throw new Error(`standing pilot and flying drone were not simultaneous independent damage targets: ${JSON.stringify(simultaneous)}`);

  await page.evaluate(()=>{globalThis.__arondightPlayerVitals.player.reset();globalThis.__arondightPlayerVitals.drone.reset();globalThis.__arondightWalkMode.setMode("drone",{persist:false});globalThis.__arondightPlayerVitals.drone.destroy("vitals-smoke");});await sleep(1050);
  const destroyed=await page.evaluate(()=>{const v=document.querySelector("#viewport"),walk=globalThis.__arondightWalkMode,drone=globalThis.__arondightPlayerVitals.drone,button=document.querySelector("#playerModeButton"),blocked=walk.setMode("drone",{persist:false});return{mode:walk.mode,blocked,player:globalThis.__arondightPlayerVitals.player.hp,drone:drone.hp,destroyed:drone.destroyed,remaining:drone.remainingMs,readyAt:drone.readyAt,buttonDisabled:Boolean(button?.disabled),buttonText:button?.textContent||"",contract:v.dataset.droneReplacementCooldownMs};});
  if(destroyed.mode!=="foot"||destroyed.blocked!=="foot"||destroyed.player!==100||destroyed.drone!==0||!destroyed.destroyed||destroyed.remaining<6200||destroyed.remaining>7300||!destroyed.buttonDisabled||!destroyed.buttonText.includes("NEW DRONE")||destroyed.contract!=="8000")throw new Error(`destroyed drone did not enter an independent replacement cooldown: ${JSON.stringify(destroyed)}`);
  await page.waitForFunction(()=>globalThis.__arondightPlayerVitals?.drone?.destroyed===false&&globalThis.__arondightPlayerVitals?.drone?.hp===100&&!document.querySelector("#playerModeButton")?.disabled,{timeout:9000});
  const replacement=await page.evaluate(()=>({mode:globalThis.__arondightWalkMode.setMode("drone",{persist:false}),hp:globalThis.__arondightPlayerVitals.drone.hp,ready:globalThis.__arondightPlayerVitals.drone.canDeploy}));if(replacement.mode!=="drone"||replacement.hp!==100||!replacement.ready)throw new Error(`replacement drone did not become deployable after cooldown: ${JSON.stringify(replacement)}`);

  await page.evaluate(()=>{globalThis.__arondightWalkMode.setMode("foot",{persist:false});globalThis.__arondightPlayerVitals.player.reset();});await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.playerMode==="foot",{timeout:3000});const deathBefore=await page.evaluate(()=>({shots:Number(document.querySelector("#viewport")?.dataset.walkShots||0),ragdolls:Number(document.querySelector("#viewport")?.dataset.worldRagdollSpawns||0)}));
  await page.evaluate(()=>globalThis.__arondightPlayerVitals.player.damage(100,"vitals-smoke"));await sleep(1100);const death=await page.evaluate(before=>{const v=document.querySelector("#viewport"),gun=globalThis.__arondightRealWorld?.threeScene?.getObjectByName?.("WALK_PISTOL_3D"),fire=globalThis.__arondightWalkMode.fire(performance.now()+2000);return{hp:globalThis.__arondightPlayerVitals.player.hp,dead:globalThis.__arondightWalkMode.dead,fire,shotsBefore:before.shots,shots:Number(v.dataset.walkShots||0),lock:v.dataset.walkDeadInputLock,fall:v.dataset.walkDeathFall,progress:Number(v.dataset.walkDeathFallProgress||0),cameraZ:Number((v.dataset.walkCameraOrigin||"").split(",")[2]),ragdollsBefore:before.ragdolls,ragdolls:Number(v.dataset.worldRagdollSpawns||0),weaponVisible:Boolean(gun?.visible),buttonDisabled:Boolean(document.querySelector("#playerModeButton")?.disabled)};},deathBefore);
  if(death.hp!==0||!death.dead||death.fire!==false||death.shots!==death.shotsBefore||death.lock!=="movement+look+fire-v1"||death.fall!=="camera+ragdoll-v1"||death.progress<.99||!Number.isFinite(death.cameraZ)||death.cameraZ>.48||death.ragdolls<=death.ragdollsBefore||death.weaponVisible||!death.buttonDisabled)throw new Error(`first-person death did not lock fire and physically fall: ${JSON.stringify(death)}`);
  console.log(`Player vitals browser smoke passed: full-range MOVE stick, simultaneous mesh-routed pilot/drone HP, 8 s replacement cooldown, and physical first-person death: ${JSON.stringify({fullMove,separated,simultaneous,destroyed,replacement,death})}`);
}finally{await page.evaluate(()=>globalThis.__arondightPlayerVitals?.player?.reset?.()).catch(()=>{});await sleep(50);await browser.close();}
