import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader","--autoplay-policy=no-user-gesture-required"]}),page=await browser.newPage(),cdp=await page.createCDPSession();
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
try{
  await page.setUserAgent("Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Mobile/15E148 Safari/604.1");
  await page.setViewport({width:844,height:390,deviceScaleFactor:1,hasTouch:true,isMobile:true});
  await page.goto(url.href,{waitUntil:"load",timeout:30000});
  await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&globalThis.__arondightWalkMode&&globalThis.__arondightPlayerVehicleRuntime&&document.querySelector("#playerModeButton"),{timeout:30000});
  await page.waitForFunction(()=>globalThis.__arondightVehicleRuntime&&document.querySelector("#viewport")?.dataset.droneVehicleRuntime==="box3d-reset-v2",{timeout:8000});
  const cameraBeforeWalk=await page.evaluate(()=>{const button=document.querySelector("#soloCamera"),v=document.querySelector("#viewport");for(let i=0;i<3&&v?.dataset.cameraMode!=="fpv";i++)button?.click();return{mode:v?.dataset.cameraMode,stored:localStorage.getItem("arondight45CameraMode")};});if(cameraBeforeWalk.mode!=="fpv"||cameraBeforeWalk.stored!=="fpv")throw new Error(`could not establish mobile FPV regression baseline: ${JSON.stringify(cameraBeforeWalk)}`);

  const heightBox=await page.$eval("#soloHeightPad",el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height};});await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:heightBox.x+heightBox.w/2,y:heightBox.y+heightBox.h*.12,id:817,radiusX:2,radiusY:2,force:1}]});await sleep(120);
  await page.click("#playerModeButton");
  await page.waitForFunction(()=>{const v=document.querySelector("#viewport");return v?.dataset.playerMode==="foot"&&v.dataset.playerVehicleMode==="human"&&v.dataset.droneVehicleState==="stowed"&&v.dataset.droneAudioSuppressed==="1"&&v.dataset.droneAudioHardMuted==="1"&&v.dataset.walkWeaponViewmodel==="compact-pistol-gloves-v2"&&v.dataset.cameraMode==="walk"&&v.dataset.presentationCameraMode==="walk"&&v.dataset.walkCameraBase==="player-eye-origin-v1"&&v.dataset.walkCameraRotationOrigin==="player-eye-v1"&&v.dataset.walkCameraPresentation==="owned-pose-provider-v1"&&v.dataset.droneCameraPreference==="fpv"&&v.dataset.playerCameraPolicy==="walk-owned-eye-origin-v1"&&document.querySelector("#footLookZone");},{timeout:5000});await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});
  const footState=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport");let air=null;b?.threeScene?.traverse?.(node=>{if(!air&&node.userData?.arondightAirframe)air=node;});const self=b?.threeScene?.getObjectByName?.("LOCAL_HUMAN_VR"),gun=b?.threeScene?.getObjectByName?.("WALK_PISTOL_3D"),fire=document.querySelector("#footFire"),fireRect=fire?.getBoundingClientRect(),fireStyle=fire?getComputedStyle(fire):null,lookRect=document.querySelector("#footLook")?.getBoundingClientRect();return{profile:v.dataset.walkControlProfile,look:v.dataset.walkLookModel,owner:v.dataset.walkControlProfileOwner,curve:v.dataset.walkControllerCurve,assist:v.dataset.walkAimAssist,bob:v.dataset.walkViewBob,shake:v.dataset.walkCameraShake,pitchRange:v.dataset.walkPitchRange,pitchLimit:Number(v.dataset.walkPitchLimitDeg),altitude:v.dataset.walkAltitudeInput,altitudeLock:v.dataset.fpsAltitudeLock,camera:v.dataset.cameraMode,presentationCamera:v.dataset.presentationCameraMode,cameraBase:v.dataset.walkCameraBase,rotationOrigin:v.dataset.walkCameraRotationOrigin,cameraPresentation:v.dataset.walkCameraPresentation,cameraFov:Number(v.dataset.walkCameraFovDeg),cameraPreference:v.dataset.droneCameraPreference,cameraPolicy:v.dataset.playerCameraPolicy,storedCamera:localStorage.getItem("arondight45CameraMode"),collision:v.dataset.walkCollisionProfile,pistol:v.dataset.walkPistolSound,viewmodel:v.dataset.walkWeaponViewmodel,weaponParts:Number(v.dataset.walkWeaponParts),weaponVisible:Boolean(gun?.visible),slide:Boolean(gun?.getObjectByName("WALK_VM_SLIDE")),barrel:Boolean(gun?.getObjectByName("WALK_VM_BARREL")),hands:Boolean(gun?.getObjectByName("WALK_VM_GLOVE_R")&&gun?.getObjectByName("WALK_VM_GLOVE_L")),arms:Boolean(gun?.getObjectByName("WALK_VM_SLEEVE_R")&&gun?.getObjectByName("WALK_VM_SLEEVE_L")),fire:{w:fireRect?.width||0,h:fireRect?.height||0,pointer:fireStyle?.pointerEvents},lookStick:{w:lookRect?.width||0,h:lookRect?.height||0},airVisible:air?.visible,hardMute:v.dataset.droneAudioHardMuted,audio:v.dataset.droneAudioSuppressed,selfVisible:self?.visible??false,perf:v.dataset.walkPerfProfile};});
  if(footState.profile!=="cod-dynamic-assist-bob-v7"||footState.look!=="fps-balanced-dynamic-v7"||footState.owner!=="walk-profile-contract-v2"||footState.curve!=="radial-precision-centre-fast-edge-v2"||footState.assist!=="friction+input-tracking-xbox-touch-v2"||footState.bob!=="bounded-stride-v1"||footState.shake!=="shot-impulse-damped-v1"||footState.pitchRange!=="near-vertical-178deg-v1"||footState.pitchLimit<89||footState.altitude!=="locked-eye-height-v1"||footState.altitudeLock!=="eye-fixed-v1"||footState.camera!=="walk"||footState.presentationCamera!=="walk"||footState.cameraBase!=="player-eye-origin-v1"||footState.rotationOrigin!=="player-eye-v1"||footState.cameraPresentation!=="owned-pose-provider-v1"||footState.cameraFov<35||footState.cameraFov>80||footState.cameraPreference!=="fpv"||footState.cameraPolicy!=="walk-owned-eye-origin-v1"||footState.storedCamera!=="fpv"||footState.collision!=="spatial-grid-cached-v2"||footState.pistol!=="procedural-synced-v2"||footState.viewmodel!=="compact-pistol-gloves-v2"||footState.weaponParts<20||!footState.weaponVisible||!footState.slide||!footState.barrel||!footState.hands||!footState.arms||footState.fire.w<92||footState.fire.h<92||footState.fire.pointer!=="auto"||footState.lookStick.w<140||footState.lookStick.h<140||footState.airVisible!==false||footState.hardMute!=="1"||footState.audio!=="1"||footState.selfVisible||footState.perf!=="cached-spatial-no-frame-traverse-v2")throw new Error(`human V2 contract failed: ${JSON.stringify(footState)}`);

  const altitudeLockedA=await page.evaluate(()=>({agl:Number(document.querySelector("#soloClearance")?.dataset.targetAglM),rate:Number(document.querySelector("#soloHeightPad")?.dataset.rateMps),z:Number((document.querySelector("#viewport")?.dataset.walkPosition||"").split(",")[2])}));await sleep(360);const altitudeLockedB=await page.evaluate(()=>({agl:Number(document.querySelector("#soloClearance")?.dataset.targetAglM),rate:Number(document.querySelector("#soloHeightPad")?.dataset.rateMps),z:Number((document.querySelector("#viewport")?.dataset.walkPosition||"").split(",")[2])}));if(!Number.isFinite(altitudeLockedA.agl)||altitudeLockedA.rate!==0||altitudeLockedB.rate!==0||Math.abs(altitudeLockedB.agl-altitudeLockedA.agl)>.001||Math.abs(altitudeLockedA.z-1.68)>.001||Math.abs(altitudeLockedB.z-1.68)>.001)throw new Error(`stale drone height input leaked into first person: ${JSON.stringify({altitudeLockedA,altitudeLockedB})}`);

  // Mobile blank-viewport look is true touch-drag, not a synthetic mouse proxy.
  const yawBefore=Number(await page.$eval("#viewport",v=>v.dataset.walkYaw||0)),lookBox=await page.$eval("#footLookZone",el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height};});
  const lx=lookBox.x+lookBox.w*.32,ly=lookBox.y+lookBox.h*.30;
  await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:lx,y:ly,id:818,radiusX:2,radiusY:2,force:1}]});await sleep(30);
  await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:lx+90,y:ly,id:818,radiusX:2,radiusY:2,force:1}]});await sleep(30);
  await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await sleep(100);
  const touchContract=await page.$eval("#viewport",v=>({look:v.dataset.walkLookInput,aimInput:v.dataset.walkAimAssistInput,touch:v.dataset.walkTouchLookActive})),yawAfterDrag=Number(await page.$eval("#viewport",v=>v.dataset.walkYaw||0));if(yawAfterDrag-yawBefore<.25)throw new Error(`mobile touch-drag look too weak: ${yawBefore} -> ${yawAfterDrag}`);if(touchContract.look!=="fps-touch-profiled-dynamic-v12"||touchContract.aimInput!=="touch-drag"||touchContract.touch!=="0")throw new Error(`mobile touch look bypassed the FPS input profile: ${JSON.stringify(touchContract)}`);

  await page.evaluate(()=>globalThis.__arondightWalkMode.setPose({pitch:0}));await sleep(60);const verticalLookBefore=await page.$eval("#viewport",v=>({pitch:Number(v.dataset.walkPitch),z:Number((v.dataset.walkPosition||"").split(",")[2]),agl:Number(document.querySelector("#soloClearance")?.dataset.targetAglM)})),vx=lookBox.x+lookBox.w*.55,vy=lookBox.y+lookBox.h*.72;await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:vx,y:vy,id:820,radiusX:2,radiusY:2,force:1}]});await sleep(30);await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:vx,y:lookBox.y+lookBox.h*.16,id:820,radiusX:2,radiusY:2,force:1}]});await sleep(30);await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await sleep(100);const verticalLookAfter=await page.$eval("#viewport",v=>({pitch:Number(v.dataset.walkPitch),z:Number((v.dataset.walkPosition||"").split(",")[2]),agl:Number(document.querySelector("#soloClearance")?.dataset.targetAglM)}));if(verticalLookAfter.pitch-verticalLookBefore.pitch<.55||Math.abs(verticalLookAfter.z-verticalLookBefore.z)>.001||Math.abs(verticalLookAfter.agl-verticalLookBefore.agl)>.001)throw new Error(`vertical touch look changed height instead of pitch: ${JSON.stringify({verticalLookBefore,verticalLookAfter})}`);

  // The visible LOOK control is an analog rate stick: edge hold keeps turning,
  // release stops it. This is intentionally different from free touch-drag.
  const stickBox=await page.$eval("#footLook",el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height};}),sx=stickBox.x+stickBox.w*.84,sy=stickBox.y+stickBox.h*.50;
  await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:sx,y:sy,id:819,radiusX:2,radiusY:2,force:1}]});await sleep(160);
  const yawHoldA=Number(await page.$eval("#viewport",v=>v.dataset.walkYaw||0));await sleep(260);const yawHoldB=Number(await page.$eval("#viewport",v=>v.dataset.walkYaw||0));
  if(yawHoldB-yawHoldA<.25)throw new Error(`LOOK stick did not continue turning while held at edge: ${yawHoldA} -> ${yawHoldB}`);
  const stickMode=await page.$eval("#viewport",v=>v.dataset.walkAimStickMode||"");if(stickMode!=="rate-edge-hold-v2")throw new Error(`LOOK stick rate contract missing: ${stickMode}`);
  await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await sleep(90);const yawReleaseA=Number(await page.$eval("#viewport",v=>v.dataset.walkYaw||0));await sleep(180);const yawReleaseB=Number(await page.$eval("#viewport",v=>v.dataset.walkYaw||0));if(Math.abs(yawReleaseB-yawReleaseA)>.08)throw new Error(`LOOK stick kept turning after release: ${yawReleaseA} -> ${yawReleaseB}`);
  await page.evaluate(()=>document.exitPointerLock?.());

  const beforeMove=await page.$eval("#viewport",v=>v.dataset.walkPosition||""),moveBox=await page.$eval("#footMove",el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height};});
  await page.mouse.move(moveBox.x+moveBox.w/2,moveBox.y+moveBox.h/2);await page.mouse.down();await page.mouse.move(moveBox.x+moveBox.w/2,moveBox.y+moveBox.h*.13,{steps:4});await sleep(330);const moveMotion=await page.$eval("#viewport",v=>({position:v.dataset.walkPosition||"",bobWeight:Number(v.dataset.walkViewBobWeight||0),bobOffset:v.dataset.walkViewBobOffset||""}));await page.mouse.up();const afterMove=moveMotion.position;if(!beforeMove||beforeMove===afterMove||moveMotion.bobWeight<.15||!moveMotion.bobOffset)throw new Error(`human movement/view-bob failed: ${JSON.stringify({beforeMove,moveMotion})}`);

  const fps=await page.evaluate(()=>new Promise(resolve=>{let n=0,start=performance.now(),last=start;const tick=t=>{n++;last=t;if(t-start>=1400)resolve(n*1000/(last-start));else requestAnimationFrame(tick);};requestAnimationFrame(tick);}));if(fps<10)throw new Error(`WALK presentation regressed toward 1 FPS: ${fps.toFixed(1)} fps`);
  const runtimeFps=Number(await page.$eval("#viewport",v=>v.dataset.walkRuntimeFps||0));if(runtimeFps&&runtimeFps<10)throw new Error(`WALK runtime FPS contract failed: ${runtimeFps}`);

  const shotBefore=await page.evaluate(()=>({shots:Number(document.querySelector("#viewport")?.dataset.walkShots||0),sounds:Number(document.querySelector("#viewport")?.dataset.walkShotSoundEvents||0)}));await page.click("#footFire");await page.waitForFunction(before=>{const v=document.querySelector("#viewport");return Number(v?.dataset.walkShots||0)>before.shots&&Number(v?.dataset.walkShotSoundEvents||0)>before.sounds&&v?.dataset.walkShotAudioVisualSync==="muzzle+recoil+sound"&&Number(v.dataset.walkCameraShakeShots||0)>0;},{timeout:3000},shotBefore);const shotMotion=await page.$eval("#viewport",v=>({shake:v.dataset.walkCameraShake,shots:Number(v.dataset.walkCameraShakeShots||0),energy:Number(v.dataset.walkCameraShakeEnergy||0)}));if(shotMotion.shake!=="shot-impulse-damped-v1"||shotMotion.shots<1)throw new Error(`first-person camera shake missing: ${JSON.stringify(shotMotion)}`);
  const humanBeforeDeploy=await page.evaluate(()=>{const p=globalThis.__arondightWalkMode.position;return{x:p.x,y:p.y,yaw:Number(document.querySelector("#viewport")?.dataset.walkYaw)||0};});

  await page.click("#playerModeButton");
  await page.waitForFunction(()=>{const v=document.querySelector("#viewport"),self=globalThis.__arondightRealWorld?.threeScene?.getObjectByName?.("LOCAL_HUMAN_VR");return v?.dataset.playerMode==="drone"&&v.dataset.playerVehicleMode==="drone"&&v.dataset.droneVehicleState==="deployed"&&v.dataset.droneAudioSuppressed==="0"&&v.dataset.droneAudioHardMuted==="0"&&v.dataset.localHumanAvatarVisible==="1"&&v.dataset.localHumanVr==="1"&&v.dataset.cameraMode==="fpv"&&v.dataset.walkCameraBase==="drone-preference-v1"&&v.dataset.droneCameraPreference==="fpv"&&self?.visible;},{timeout:5000});
  const deployed=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport"),anchor=globalThis.__arondightPlayerVehicleRuntime.humanAnchor,self=b.threeScene.getObjectByName("LOCAL_HUMAN_VR");let air=null;b.threeScene.traverse(node=>{if(!air&&node.userData?.arondightAirframe)air=node;});const headset=self.children.find(x=>x.geometry?.type==="BoxGeometry"&&Math.abs(x.position.z-1.61)<.02);return{anchor,self:{x:self.position.x,y:self.position.y,visible:self.visible,headset:Boolean(headset?.visible)},air:air?{x:air.position.x,y:air.position.y,z:air.position.z,visible:air.visible}:null,offset:Number(v.dataset.droneLaunchOffsetM||0),replication:v.dataset.playerVehicleReplication};});
  if(!deployed.air?.visible||!deployed.self.visible||!deployed.self.headset||deployed.replication!=="human+drone+audio+fx-v2"||Math.hypot(deployed.self.x-humanBeforeDeploy.x,deployed.self.y-humanBeforeDeploy.y)>.08||deployed.offset<.6||Math.hypot(deployed.air.x-deployed.anchor.x,deployed.air.y-deployed.anchor.y)<.55)throw new Error(`local standing VR human / drone launch contract failed: ${JSON.stringify({humanBeforeDeploy,deployed})}`);

  await page.evaluate(()=>{const p=globalThis.__arondightPlayerVehicleRuntime.humanAnchor,pose={p:[p.x+3,p.y,.04],q:[0,0,0,1],v:[0,0,0],t:performance.now(),f:"local-metric",pm:"drone",av:[p.x+2,p.y+1,0],ay:.35,avv:[0,0,0],vr:1};dispatchEvent(new CustomEvent("arondight45:vs-pose",{detail:{peerId:"vehicle-smoke-peer",pose}}));});
  await page.waitForFunction(()=>globalThis.__arondightRealWorld?.threeScene?.getObjectByName?.("VS_HUMAN_vehicle-smoke-peer")?.visible,{timeout:3000});
  const remote=await page.evaluate(()=>{const a=globalThis.__arondightRealWorld.threeScene.getObjectByName("VS_HUMAN_vehicle-smoke-peer"),headset=a.children.find(x=>x.geometry?.type==="BoxGeometry"&&Math.abs(x.position.z-1.61)<.02),hit=a.children.find(x=>x.userData?.vsPeerHitProxy);return{visible:a.visible,headset:Boolean(headset?.visible),hitId:hit?.userData?.vsPlayerId};});if(!remote.visible||!remote.headset||remote.hitId!=="vehicle-smoke-peer")throw new Error(`remote VR human missing: ${JSON.stringify(remote)}`);

  await page.click("#playerModeButton");await page.waitForFunction(()=>{const v=document.querySelector("#viewport"),self=globalThis.__arondightRealWorld?.threeScene?.getObjectByName?.("LOCAL_HUMAN_VR");return v?.dataset.playerMode==="foot"&&v.dataset.droneVehicleState==="stowed"&&v.dataset.droneAudioSuppressed==="1"&&v.dataset.droneAudioHardMuted==="1"&&v.dataset.cameraMode==="walk"&&v.dataset.presentationCameraMode==="walk"&&v.dataset.walkCameraBase==="player-eye-origin-v1"&&v.dataset.droneCameraPreference==="fpv"&&self?.visible===false;},{timeout:5000});
  console.log(`Player vehicle V2 smoke passed: owned player-eye camera origin independent of drone preference, fixed-height near-vertical touch aim, large FIRE target, compact pistol/glove viewmodel, rate-stick aim, bounded view-bob, damped shot shake, cached spatial collisions, >10 FPS, synchronized pistol sound, hard drone-audio isolation, visible local VR human while drone flies, physical launch offset, multiplayer VR avatar: ${JSON.stringify({cameraBeforeWalk,footState,touchContract,altitudeLockedA,altitudeLockedB,verticalLookBefore,verticalLookAfter,fps,runtimeFps,yawBefore,yawAfterDrag,yawHoldA,yawHoldB,yawReleaseA,yawReleaseB,beforeMove,afterMove,moveMotion,shotMotion,deployed,remote})}`);
}finally{await browser.close();}
