import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage(),cdp=await page.createCDPSession();
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
try{
  await page.setViewport({width:1000,height:620,deviceScaleFactor:1,hasTouch:true,isMobile:true});await page.goto(url.href,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready"),{timeout:30000});
  await page.waitForFunction(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld;return globalThis.__arondightWalkMode&&globalThis.__arondightPlayerVehicleRuntime&&b?.threeScene?.traverse?.__playerRuntimeHotfix&&Number(v?.dataset.playerSceneIndex||0)>=1&&v?.dataset.playerRuntimeHotfix?.includes("reset+selfhit+aim");},{timeout:12000});

  const base=await page.evaluate(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld;return{profile:v.dataset.walkAimProfile,nativeAim:v.dataset.walkNativeViewportAim,control:v.dataset.walkControlProfile,traversal:v.dataset.playerSceneTraversal,index:Number(v.dataset.playerSceneIndex||0),fireCandidates:Number(v.dataset.playerSceneFireCandidates||0),patched:Boolean(b.threeScene.traverse.__playerRuntimeHotfix)};});
  if(base.profile!=="window-pointerlock+drag-center-v7"||base.nativeAim!=="1"||base.traversal!=="cached-incremental-v4"||!base.patched||base.index<1||base.fireCandidates<1)throw new Error(`player hotfix runtime contract failed: ${JSON.stringify(base)}`);

  await page.evaluate(()=>globalThis.__arondightWalkMode.setMode("foot"));await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.playerMode==="foot"&&document.getElementById("footLookZone"));const yawBefore=Number(await page.$eval("#viewport",v=>v.dataset.walkYaw||0));
  const coverage=await page.evaluate(()=>{const v=document.querySelector("#viewport"),z=document.getElementById("footLookZone"),vr=v.getBoundingClientRect(),zr=z.getBoundingClientRect(),x=zr.left+zr.width*.22,y=zr.top+zr.height*.35,hit=document.elementFromPoint(x,y);return{viewportWidth:vr.width,zoneWidth:zr.width,leftGap:Math.abs(zr.left-vr.left),rightGap:Math.abs(zr.right-vr.right),x,y,hitId:hit?.id||"",hitInsideZone:Boolean(hit&&z.contains(hit))};});if(coverage.zoneWidth<coverage.viewportWidth*.95||coverage.leftGap>2||coverage.rightGap>2||!coverage.hitInsideZone)throw new Error(`first-person look zone does not cover free viewport: ${JSON.stringify(coverage)}`);
  await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:coverage.x,y:coverage.y,id:818,radiusX:2,radiusY:2,force:1}]});await sleep(30);await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:coverage.x+coverage.zoneWidth*.14,y:coverage.y,id:818,radiusX:2,radiusY:2,force:1}]});await sleep(30);await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await sleep(120);const yawAfter=Number(await page.$eval("#viewport",v=>v.dataset.walkYaw||0));if(!(yawAfter>yawBefore+.08))throw new Error(`real touch first-person viewport aim did not move yaw: ${yawBefore} -> ${yawAfter}; ${JSON.stringify(coverage)}`);
  await page.evaluate(()=>globalThis.__arondightWalkMode.fire(performance.now()+1000));

  await page.evaluate(()=>globalThis.__arondightWalkMode.setPose({x:37,y:-29,yaw:.7,pitch:.2}));const beforeReset=await page.evaluate(()=>({x:globalThis.__arondightWalkMode.position.x,y:globalThis.__arondightWalkMode.position.y}));await page.evaluate(()=>document.getElementById("reset")?.click());await sleep(260);const afterReset=await page.evaluate(()=>({x:globalThis.__arondightWalkMode.position.x,y:globalThis.__arondightWalkMode.position.y,marker:document.querySelector("#viewport")?.dataset.playerReset}));if(Math.hypot(afterReset.x-beforeReset.x,afterReset.y-beforeReset.y)<5||!afterReset.marker?.includes("foot"))throw new Error(`SIM reset did not reset WALK person: ${JSON.stringify({beforeReset,afterReset})}`);

  await page.evaluate(()=>globalThis.__arondightWalkMode.setMode("drone"));await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.selfHarm==="enabled-v2"&&document.querySelector("#viewport")?.dataset.selfHitRouting==="local-authoritative-v2",{timeout:5000});
  const selfHit=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport"),root=b.threeScene.children.find(node=>node?.userData?.localHumanAvatar||node?.name==="LOCAL_HUMAN_VR");let mesh=null;const stack=root?[root]:[];while(stack.length&&!mesh){const n=stack.pop();if(n?.isMesh)mesh=n;else for(const child of n?.children||[])stack.push(child);}if(!mesh)return{root:Boolean(root),mesh:false};b.vsLocalHealth=100;b.vsLocalDead=false;const before=Number(b.vsLocalHealth),handled=Boolean(b.registerVsHit({object:mesh,point:mesh.getWorldPosition(mesh.position.clone())}));return{root:Boolean(root),mesh:true,ignore:mesh.userData.flightFireIgnore,before,after:Number(b.vsLocalHealth),handled,selfHits:Number(v.dataset.selfHits||0)};});await sleep(80);const selfHp=Number(await page.evaluate(()=>globalThis.__arondightRealWorld?.vsLocalHealth));if(!selfHit.root||!selfHit.mesh||selfHit.ignore!==false||!selfHit.handled||selfHp>=selfHit.before||selfHit.selfHits<1)throw new Error(`self-hit contract failed: ${JSON.stringify({...selfHit,selfHp})}`);

  await page.evaluate(()=>{const v=document.querySelector("#viewport"),r=v.getBoundingClientRect(),x=r.left+r.width*.5,y=r.top+r.height*.75;v.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:919,pointerType:"touch",clientX:x,clientY:y,button:0}));setTimeout(()=>v.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:919,pointerType:"touch",clientX:x,clientY:y,button:0})),150);});
  await page.waitForFunction(()=>{const kinds=(document.querySelector("#viewport")?.dataset.playerSceneCachedKinds||"").split(",");return["vehicles","population","decor","fire"].every(kind=>kinds.includes(kind));},{timeout:6000});
  const cachedKinds=await page.$eval("#viewport",v=>v.dataset.playerSceneCachedKinds||"");

  console.log(`Player runtime hotfix browser smoke passed: reset person, real-touch full-viewport aim, self-hit and minification-safe cached scene traversal: ${JSON.stringify({base,coverage,cachedKinds,yawBefore,yawAfter,beforeReset,afterReset,selfHit:{...selfHit,selfHp}})}`);
}finally{await browser.close();}
