import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage();
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
try{
  await page.setViewport({width:1000,height:620,deviceScaleFactor:1});await page.goto(url.href,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready"),{timeout:30000});
  await page.waitForFunction(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld;return globalThis.__arondightWalkMode&&globalThis.__arondightPlayerVehicleRuntime&&b?.threeScene?.traverse?.__playerRuntimeHotfix&&Number(v?.dataset.playerSceneIndex||0)>=1&&v?.dataset.playerRuntimeHotfix?.includes("reset+selfhit+aim");},{timeout:12000});

  const base=await page.evaluate(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld;return{profile:v.dataset.walkAimProfile,traversal:v.dataset.playerSceneTraversal,index:Number(v.dataset.playerSceneIndex||0),fireCandidates:Number(v.dataset.playerSceneFireCandidates||0),patched:Boolean(b.threeScene.traverse.__playerRuntimeHotfix)};});
  if(base.profile!=="pointerlock+drag-center-v6"||base.traversal!=="cached-incremental-v3"||!base.patched||base.index<1||base.fireCandidates<1)throw new Error(`player hotfix runtime contract failed: ${JSON.stringify(base)}`);

  await page.evaluate(()=>globalThis.__arondightWalkMode.setMode("foot"));await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.playerMode==="foot");const yawBefore=Number(await page.$eval("#viewport",v=>v.dataset.walkYaw||0));
  await page.evaluate(()=>{const v=document.querySelector("#viewport"),target=v.querySelector("canvas")||v,r=v.getBoundingClientRect();target.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:818,pointerType:"touch",clientX:r.left+r.width*.52,clientY:r.top+r.height*.45}));target.dispatchEvent(new PointerEvent("pointermove",{bubbles:true,cancelable:true,pointerId:818,pointerType:"touch",clientX:r.left+r.width*.66,clientY:r.top+r.height*.45}));target.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:818,pointerType:"touch",clientX:r.left+r.width*.66,clientY:r.top+r.height*.45}));});await sleep(120);const yawAfter=Number(await page.$eval("#viewport",v=>v.dataset.walkYaw||0));if(!(yawAfter>yawBefore+.08))throw new Error(`first-person viewport aim did not move yaw: ${yawBefore} -> ${yawAfter}`);

  await page.evaluate(()=>globalThis.__arondightWalkMode.setPose({x:37,y:-29,yaw:.7,pitch:.2}));const beforeReset=await page.evaluate(()=>({x:globalThis.__arondightWalkMode.position.x,y:globalThis.__arondightWalkMode.position.y}));await page.evaluate(()=>document.getElementById("reset")?.click());await sleep(260);const afterReset=await page.evaluate(()=>({x:globalThis.__arondightWalkMode.position.x,y:globalThis.__arondightWalkMode.position.y,marker:document.querySelector("#viewport")?.dataset.playerReset}));if(Math.hypot(afterReset.x-beforeReset.x,afterReset.y-beforeReset.y)<5||!afterReset.marker?.includes("foot"))throw new Error(`SIM reset did not reset WALK person: ${JSON.stringify({beforeReset,afterReset})}`);

  await page.evaluate(()=>globalThis.__arondightWalkMode.setMode("drone"));await page.waitForFunction(()=>document.querySelector("#viewport")?.dataset.selfHarm==="enabled-v2"&&document.querySelector("#viewport")?.dataset.selfHitRouting==="local-authoritative-v2",{timeout:5000});
  const selfHit=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport"),root=b.threeScene.children.find(node=>node?.userData?.localHumanAvatar||node?.name==="LOCAL_HUMAN_VR");let mesh=null;const stack=root?[root]:[];while(stack.length&&!mesh){const n=stack.pop();if(n?.isMesh)mesh=n;else for(const child of n?.children||[])stack.push(child);}if(!mesh)return{root:Boolean(root),mesh:false};b.vsLocalHealth=100;b.vsLocalDead=false;const before=Number(b.vsLocalHealth),handled=Boolean(b.registerVsHit({object:mesh,point:mesh.getWorldPosition(mesh.position.clone())}));return{root:Boolean(root),mesh:true,ignore:mesh.userData.flightFireIgnore,before,after:Number(b.vsLocalHealth),handled,selfHits:Number(v.dataset.selfHits||0)};});await sleep(80);const selfHp=Number(await page.evaluate(()=>globalThis.__arondightRealWorld?.vsLocalHealth));if(!selfHit.root||!selfHit.mesh||selfHit.ignore!==false||!selfHit.handled||selfHp>=selfHit.before||selfHit.selfHits<1)throw new Error(`self-hit contract failed: ${JSON.stringify({...selfHit,selfHp})}`);

  console.log(`Player runtime hotfix browser smoke passed: reset person, viewport aim, self-hit and cached incremental scene traversal: ${JSON.stringify({base,yawBefore,yawAfter,beforeReset,afterReset,selfHit:{...selfHit,selfHp}})}`);
}finally{await browser.close();}
