import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage();
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
try{
  await page.setUserAgent("Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Mobile/15E148 Safari/604.1");
  await page.setViewport({width:844,height:390,deviceScaleFactor:1});await page.goto(url.href,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready"),{timeout:30000});
  const training=await page.evaluate(async()=>{const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld,end=performance.now()+8000;while(performance.now()<end&&!(v.dataset.worldProceduralPopulation==="1"&&v.dataset.worldPopulationMode==="training-physical"&&Number(v.dataset.worldPhysicsVehicles||0)>=17&&Number(v.dataset.worldPhysicsVehicleVisuals||0)>=17))await wait(40);const kinds={},positions=[];b.threeScene.traverse(node=>{const kind=String(node.userData?.worldPopulationKind||"");if(node.isGroup&&node.visible&&(kind==="car"||kind==="bus")&&node.userData?.worldProceduralId){kinds[kind]=(kinds[kind]||0)+1;const p=node.getWorldPosition(node.position.clone());positions.push({kind,x:p.x,y:p.y,z:p.z});}});return{mode:v.dataset.worldPopulationMode,architecture:v.dataset.worldPopulationArchitecture,grounding:v.dataset.worldVehicleGrounding,physics:v.dataset.worldRigidBodyPhysics,vehicles:Number(v.dataset.worldPhysicsVehicles||0),visuals:Number(v.dataset.worldPhysicsVehicleVisuals||0),lowest:Number(v.dataset.worldPhysicsVehicleLowestZ),kinds,positions};});
  if(training.mode!=="training-physical"||training.architecture!=="route+box3d-rigid-v3"||training.grounding!=="box3d-static-ground-contact-v1"||training.physics!=="box3d-dynamic-forces-v1"||training.vehicles<17||training.visuals<17||training.kinds.car<14||training.kinds.bus<3||!Number.isFinite(training.lowest)||training.lowest<-.16||training.positions.some(item=>item.z<-.16)||!training.positions.some(item=>item.kind==="car"&&Math.hypot(item.x,item.y)<48)||!training.positions.some(item=>item.kind==="bus"&&Math.hypot(item.x,item.y)<58))throw new Error(`training traffic was hidden, too distant, or fell through Box3D ground: ${JSON.stringify(training)}`);
  const initial=await page.evaluate(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms)),v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld;v.dataset.worldMode="real";b.active=true;b.originLon=9;b.originLat=47;const end=performance.now()+8000;while(performance.now()<end&&!(v.dataset.worldProceduralPopulation==="1"&&v.dataset.worldPopulationMode==="real-road-physical"&&v.dataset.worldProceduralBucket==="47.000:9.000"&&v.dataset.worldProceduralSeed&&Number(v.dataset.worldLifeVisible||0)>=40&&typeof b.registerWorldPopulationHit==="function"&&v.dataset.worldRigidBodyPhysics==="box3d-dynamic-forces-v1"&&Number(v.dataset.worldPhysicsVehicles||0)>=17))await wait(40);const snapshot=()=>{const ids=[],kinds={};b.threeScene.traverse(node=>{const id=String(node.userData?.worldProceduralId||"");if(!id||!node.isGroup||!node.visible)return;ids.push(id);const kind=String(node.userData?.worldPopulationKind||"");kinds[kind]=(kinds[kind]||0)+1;});return{ids:[...new Set(ids)].sort(),kinds,seed:v.dataset.worldProceduralSeed||"",bucket:v.dataset.worldProceduralBucket||"",architecture:v.dataset.worldPopulationArchitecture||"",visible:Number(v.dataset.worldLifeVisible||0),physics:v.dataset.worldRigidBodyPhysics,vehicles:Number(v.dataset.worldPhysicsVehicles||0),control:v.dataset.worldPhysicsControl,continuous:v.dataset.worldPhysicsContinuous};};return snapshot();});
  if(initial.bucket!=="47.000:9.000"||initial.architecture!=="route+box3d-rigid-v3"||!initial.seed||initial.kinds.car<14||initial.kinds.person<18||initial.kinds.bus<3||initial.kinds.bird<10||initial.physics!=="box3d-dynamic-forces-v1"||initial.vehicles<17||initial.control!=="force+torque+impulse"||initial.continuous!=="1")throw new Error(`procedural rigid population did not initialize: ${JSON.stringify(initial)}`);

  await page.evaluate(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld;v.dataset.worldMode="real";b.minimapFeatures=[];b.active=false;});await sleep(650);
  const duringGap=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport"),ids=[];b.threeScene.traverse(node=>{const id=String(node.userData?.worldProceduralId||"");if(id&&node.isGroup&&node.visible)ids.push(id);});return{ids:[...new Set(ids)].sort(),visible:Number(v.dataset.worldLifeVisible||0)};});
  if(JSON.stringify(duringGap.ids)!==JSON.stringify(initial.ids)||duringGap.visible!==initial.visible)throw new Error(`population changed during transient WORLD gap: ${JSON.stringify({initial:initial.ids.length,during:duringGap.ids.length,visible:[initial.visible,duringGap.visible]})}`);

  await page.evaluate(()=>{const b=globalThis.__arondightRealWorld;b.active=true;b.originLon=9.00005;b.originLat=47.00005;b.minimapFeatures=[{kind:"road",paths:[[[9,47],[9.002,47.001]]]}];});await sleep(2300);
  const afterChurn=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport"),ids=[];b.threeScene.traverse(node=>{const id=String(node.userData?.worldProceduralId||"");if(id&&node.isGroup&&node.visible)ids.push(id);});return{ids:[...new Set(ids)].sort(),seed:v.dataset.worldProceduralSeed||"",bucket:v.dataset.worldProceduralBucket||"",visible:Number(v.dataset.worldLifeVisible||0)};});
  if(afterChurn.bucket!==initial.bucket||afterChurn.seed!==initial.seed||JSON.stringify(afterChurn.ids)!==JSON.stringify(initial.ids)||afterChurn.visible!==initial.visible)throw new Error(`deterministic population changed after map/GPS churn: ${JSON.stringify({bucket:[initial.bucket,afterChurn.bucket],seed:[initial.seed,afterChurn.seed],count:[initial.ids.length,afterChurn.ids.length],visible:[initial.visible,afterChurn.visible]})}`);

  const hits=await page.evaluate(async()=>{const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport"),targets={};const hierarchyVisible=node=>{for(let n=node;n;n=n.parent)if(n.visible===false)return false;return true;};b.threeScene.traverse(node=>{const kind=String(node.userData?.worldPopulationKind||"");if(node.isMesh&&hierarchyVisible(node)&&node.userData?.worldProceduralId&&!targets[kind])targets[kind]=node;});const calls={person:1,car:6,bus:13,bird:1},result={};for(const kind of Object.keys(calls)){const node=targets[kind];result[kind]=[];for(let i=0;i<calls[kind];i++)result[kind].push(Boolean(node&&b.registerWorldPopulationHit({object:node,point:node.getWorldPosition(node.position.clone())})));}const warned={car:hierarchyVisible(targets.car),bus:hierarchyVisible(targets.bus),active:Number(v.dataset.worldCriticalDamageActive||0),model:v.dataset.worldCriticalDamageModel||""};const smokeDeadline=performance.now()+1200;while(performance.now()<smokeDeadline&&Number(v.dataset.worldCriticalSmokePuffs||0)<2)await wait(25);const explosionDeadline=performance.now()+2600;while(performance.now()<explosionDeadline&&(hierarchyVisible(targets.car)||hierarchyVisible(targets.bus)))await wait(25);const hidden={};for(const[kind,node]of Object.entries(targets))hidden[kind]=!hierarchyVisible(node);return{result,warned,hidden,smokePuffs:Number(v.dataset.worldCriticalSmokePuffs||0),criticalExplosions:Number(v.dataset.worldCriticalExplosions||0),lifeHits:Number(v.dataset.worldLifeHits||0),populationHits:Number(v.dataset.worldPopulationHits||0),provider:typeof b.__proceduralPopulationHit==="function",shotImpulses:Number(v.dataset.worldRigidBodyShotImpulses||0),lastImpulse:v.dataset.worldRigidBodyLastImpulse};});
  if(!hits.provider||Object.values(hits.result).flat().some(value=>!value)||!hits.warned.car||!hits.warned.bus||hits.warned.active<2||hits.warned.model!=="smoke-then-delayed-explosion-v1"||hits.smokePuffs<2||hits.criticalExplosions<2||["person","car","bus","bird"].some(kind=>!hits.hidden[kind])||hits.shotImpulses<19||hits.lastImpulse!=="bus")throw new Error(`procedural population rigid hit routing/critical warning failed: ${JSON.stringify(hits)}`);
  console.log(`Procedural population continuity smoke passed: training and real-world cars/buses remain grounded and visible under Box3D, with physical shot impulses and critical explosions. seed=${initial.seed} population=${initial.ids.length}`);
}finally{await browser.close();}
