import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage();
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
try{
  await page.setUserAgent("Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Mobile/15E148 Safari/604.1");
  await page.setViewport({width:844,height:390,deviceScaleFactor:1});await page.goto(url.href,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready"),{timeout:30000});
  const initial=await page.evaluate(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms)),v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld;v.dataset.worldMode="real";b.active=true;b.originLon=9;b.originLat=47;const end=performance.now()+8000;while(performance.now()<end&&!(v.dataset.worldProceduralPopulation==="1"&&Number(v.dataset.worldLifeVisible||0)>=40&&typeof b.registerWorldPopulationHit==="function"))await wait(40);const snapshot=()=>{const ids=[],kinds={};b.threeScene.traverse(node=>{const id=String(node.userData?.worldProceduralId||"");if(!id||!node.isGroup||!node.visible)return;ids.push(id);const kind=String(node.userData?.worldPopulationKind||"");kinds[kind]=(kinds[kind]||0)+1;});return{ids:[...new Set(ids)].sort(),kinds,seed:v.dataset.worldProceduralSeed||"",architecture:v.dataset.worldPopulationArchitecture||"",visible:Number(v.dataset.worldLifeVisible||0)};};return snapshot();});
  if(initial.architecture!=="procedural-deterministic-v1"||!initial.seed||initial.kinds.car<14||initial.kinds.person<18||initial.kinds.bus<3||initial.kinds.bird<10)throw new Error(`procedural population did not initialize: ${JSON.stringify(initial)}`);

  await page.evaluate(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld;v.dataset.worldMode="real";b.minimapFeatures=[];b.active=false;});await sleep(650);
  const duringGap=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport"),ids=[];b.threeScene.traverse(node=>{const id=String(node.userData?.worldProceduralId||"");if(id&&node.isGroup&&node.visible)ids.push(id);});return{ids:[...new Set(ids)].sort(),visible:Number(v.dataset.worldLifeVisible||0)};});
  if(JSON.stringify(duringGap.ids)!==JSON.stringify(initial.ids)||duringGap.visible!==initial.visible)throw new Error(`population changed during transient WORLD gap: ${JSON.stringify({initial:initial.ids.length,during:duringGap.ids.length,visible:[initial.visible,duringGap.visible]})}`);

  await page.evaluate(()=>{const b=globalThis.__arondightRealWorld;b.active=true;b.originLon=9.00005;b.originLat=47.00005;b.minimapFeatures=[{kind:"road",paths:[[[9,47],[9.002,47.001]]]}];});await sleep(2300);
  const afterChurn=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport"),ids=[];b.threeScene.traverse(node=>{const id=String(node.userData?.worldProceduralId||"");if(id&&node.isGroup&&node.visible)ids.push(id);});return{ids:[...new Set(ids)].sort(),seed:v.dataset.worldProceduralSeed||"",visible:Number(v.dataset.worldLifeVisible||0)};});
  if(afterChurn.seed!==initial.seed||JSON.stringify(afterChurn.ids)!==JSON.stringify(initial.ids)||afterChurn.visible!==initial.visible)throw new Error(`deterministic population changed after map/GPS churn: ${JSON.stringify({seed:[initial.seed,afterChurn.seed],count:[initial.ids.length,afterChurn.ids.length],visible:[initial.visible,afterChurn.visible]})}`);

  const hits=await page.evaluate(()=>{const b=globalThis.__arondightRealWorld,v=document.querySelector("#viewport"),targets={};const hierarchyVisible=node=>{for(let n=node;n;n=n.parent)if(n.visible===false)return false;return true;};b.threeScene.traverse(node=>{const kind=String(node.userData?.worldPopulationKind||"");if(node.isMesh&&hierarchyVisible(node)&&node.userData?.worldProceduralId&&!targets[kind])targets[kind]=node;});const calls={person:1,car:6,bus:13,bird:1},result={};for(const kind of Object.keys(calls)){const node=targets[kind];result[kind]=[];for(let i=0;i<calls[kind];i++)result[kind].push(Boolean(node&&b.registerWorldPopulationHit({object:node,point:node.getWorldPosition(node.position.clone())})));}const hidden={};for(const[kind,node]of Object.entries(targets))hidden[kind]=!hierarchyVisible(node);return{result,hidden,lifeHits:Number(v.dataset.worldLifeHits||0),populationHits:Number(v.dataset.worldPopulationHits||0),provider:typeof b.__proceduralPopulationHit==="function"};});
  if(!hits.provider||Object.values(hits.result).flat().some(value=>!value)||["person","car","bus","bird"].some(kind=>!hits.hidden[kind]))throw new Error(`procedural population hit routing failed: ${JSON.stringify(hits)}`);
  console.log(`Procedural population continuity smoke passed: stable deterministic humans/cars/buses/birds across WORLD gaps, map churn and GPS jitter; multi-hit vehicles and procedural deaths retained. seed=${initial.seed} population=${initial.ids.length}`);
}finally{await browser.close();}
