import puppeteer from "puppeteer-core";
const base=process.argv[2]||"http://127.0.0.1:4174";
const executablePath=process.env.CHROME_BIN;if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]});
const page=await browser.newPage(),external=[];page.on("request",request=>{const u=new URL(request.url());if(!["127.0.0.1","localhost"].includes(u.hostname))external.push(request.url());});
try{
  await page.setViewport({width:844,height:390,deviceScaleFactor:1});await page.goto(`${base}/drone_simulator.html`,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent.includes("SIM ready"),{timeout:30000});
  await page.click("#camSolo");await page.waitForFunction(()=>document.body.classList.contains("solo-flight"),{timeout:5000});
  const entry=await page.evaluate(()=>{const button=document.querySelector("#soloWorld"),settings=document.querySelector("#soloTopbar .phone-settings-button");return{world:!!button,worldText:button?.textContent||"",worldVisible:!!button&&getComputedStyle(button).display!=="none",settings:!!settings};});
  if(!entry.world||!entry.worldVisible||entry.worldText!=="WORLD"||!entry.settings)throw new Error(`REAL WORLD solo entry missing: ${JSON.stringify(entry)}`);
  await page.click("#soloTopbar .phone-settings-button");await page.waitForFunction(()=>document.querySelector(".phone-settings-dialog")?.open,{timeout:5000});
  const config=await page.evaluate(()=>({section:!!document.querySelector('[data-world-settings="openfreemap-osm-3d"]'),key:!!document.querySelector("[data-world-key]"),forget:!!document.querySelector("[data-world-forget]"),use:document.querySelector("[data-world-use]")?.textContent?.trim()||"",training:document.querySelector("[data-world-training]")?.textContent?.trim()||"",note:document.querySelector('[data-world-settings="openfreemap-osm-3d"]')?.textContent||""}));
  if(!config.section||config.key||config.forget||config.use!=="USE MY GPS LOCATION"||config.training!=="TRAINING RANGE"||!config.note.includes("No account, API key, billing setup, backend or proxy"))throw new Error(`REAL WORLD settings incomplete: ${JSON.stringify(config)}`);
  if(external.length)throw new Error(`training/settings path triggered external network: ${JSON.stringify(external)}`);await page.click('.phone-settings-dialog [data-close]');
  await page.evaluate(()=>{const bridge=globalThis.__arondightRealWorld;if(!bridge)throw new Error("real-world bridge missing");bridge.activate=async function(){globalThis.__worldActivateCalls=(globalThis.__worldActivateCalls||0)+1;this.loading=true;await Promise.resolve();this.loading=false;this.active=true;};bridge.deactivate=function(){globalThis.__worldDeactivateCalls=(globalThis.__worldDeactivateCalls||0)+1;this.active=false;this.loading=false;};});
  await page.click("#soloWorld");await page.waitForFunction(()=>document.querySelector("#soloWorld")?.dataset.active==="1",{timeout:5000});
  let state=await page.evaluate(()=>({calls:globalThis.__worldActivateCalls||0,text:document.querySelector("#soloWorld")?.textContent||"",active:document.querySelector("#soloWorld")?.dataset.active||""}));if(state.calls!==1||state.text!=="WORLD ✓"||state.active!=="1")throw new Error(`WORLD did not invoke geospatial bridge: ${JSON.stringify(state)}`);
  await page.click("#soloWorld");state=await page.evaluate(()=>({calls:globalThis.__worldDeactivateCalls||0,text:document.querySelector("#soloWorld")?.textContent||"",active:document.querySelector("#soloWorld")?.dataset.active||""}));if(state.calls!==1||state.text!=="WORLD"||state.active!=="0")throw new Error(`WORLD training fallback failed: ${JSON.stringify(state)}`);
  await page.click("#soloTopbar .phone-settings-button");await page.waitForFunction(()=>document.querySelector(".phone-settings-dialog")?.open,{timeout:5000});await page.click("[data-world-use]");await page.waitForFunction(()=>document.querySelector("#soloWorld")?.dataset.active==="1",{timeout:5000});
  const settingsActivation=await page.evaluate(()=>globalThis.__worldActivateCalls||0);if(settingsActivation!==2)throw new Error(`settings GPS action did not use bridge: ${settingsActivation}`);await page.click("[data-world-training]");
  if(external.length)throw new Error(`static-only UI smoke made external requests before real provider activation: ${JSON.stringify(external)}`);
  console.log("REAL WORLD no-key OpenFreeMap UI + one-tap bridge wiring smoke passed.");
}finally{await browser.close();}
