import assert from 'node:assert/strict';import{pathToFileURL}from'node:url';import{resolve}from'node:path';import{findSafeSpawn}from'../sim/safe_spawn.mjs';
const modulePath=process.argv[2];if(!modulePath)throw new Error('usage: node tests/safe_spawn_box3d_test.mjs <box3d.inline.mjs>');const imported=await import(pathToFileURL(resolve(modulePath)).href),b3=await imported.default(),worldDef=b3.b3DefaultWorldDef();worldDef.gravity=[0,0,-9.80665];worldDef.enableSleep=false;const world=b3.b3CreateWorld(worldDef);
const terrainDef=b3.b3DefaultBodyDef();terrainDef.position=[0,0,-.05];const terrain=b3.b3CreateBody(world,terrainDef),terrainShape=b3.b3DefaultShapeDef();terrainShape.filter={categoryBits:1n,maskBits:14n,groupIndex:0};b3.b3CreateBoxShape(terrain,terrainShape,150,150,.05);
const buildingDef=b3.b3DefaultBodyDef();buildingDef.position=[0,0,4];const building=b3.b3CreateBody(world,buildingDef),buildingShape=b3.b3DefaultShapeDef();buildingShape.filter={categoryBits:1n,maskBits:10n,groupIndex:0};b3.b3CreateBoxShape(building,buildingShape,4,4,4);
const cast=(category,x,y)=>{const filter=b3.b3DefaultQueryFilter();filter.categoryBits=category;filter.maskBits=1n;return b3.b3World_CastRayClosest(world,[x,y,100],[0,0,-150],filter);};
const probe=(x,y)=>{const ground=cast(4n,x,y),obstacle=cast(8n,x,y);if(!ground.hit||!obstacle.hit)return null;return{terrainZ:ground.point[2],obstructionZ:obstacle.point[2],normalZ:ground.normal[2]};};
const safe=findSafeSpawn({around:[0,0,0],mode:'initial',seed:7,clearanceRadiusM:.25,probe});assert.ok(safe,'safe spawn must exist');assert.ok(Math.abs(safe.x)>4.25||Math.abs(safe.y)>4.25,`spawn remained under/in building: ${JSON.stringify(safe)}`);assert.ok(safe.z>.04&&safe.z<.2,`spawn support height wrong: ${safe.z}`);
const respawn=findSafeSpawn({around:[30,20,3],mode:'respawn',seed:99,clearanceRadiusM:.25,probe});assert.ok(respawn);assert.ok(respawn.offsetM>=18,`respawn did not move away from death point: ${respawn.offsetM}`);assert.ok(Math.hypot(respawn.x-30,respawn.y-20)>=18);
b3.b3DestroyWorld(world);console.log(`Safe spawn Box3D passed: building rejected, initial ${safe.offsetM.toFixed(1)} m, combat respawn ${respawn.offsetM.toFixed(1)} m away.`);
