import fs from 'node:fs';
import assert from 'node:assert/strict';

const trend=JSON.parse(fs.readFileSync('stockstrend-data.json','utf8'));
const watch=JSON.parse(fs.readFileSync('watchlist-data.json','utf8'));
const intr=JSON.parse(fs.readFileSync('intrinsic-orcl.json','utf8'));
const source=JSON.parse(fs.readFileSync('intrinsic-orcl-input.json','utf8'));
const html=fs.readFileSync('stockstrend.html','utf8');
const methodik=fs.readFileSync('methodik.html','utf8');

const sw=trend.tick?.scrape_window;
assert(sw?.start && sw?.end);
assert(new Date(sw.start)<=new Date(sw.end),'scrape window reversed');

const o=watch.stocks?.ORCL, tail=o?.history?.at(-1);
assert(o&&tail);
assert.equal(o.latest.at,tail.at,'latest/history timestamp drift');
assert.equal(o.latest.signal,tail.signal,'latest/history signal drift');
assert.equal(o.latest.confidence,tail.confidence,'latest/history confidence drift');

assert(html.includes('return out;'));
assert(!html.includes('return out.length?out:arr.slice();'));
assert(html.includes('directionalPct'));
assert(html.includes('Investor-first compact view'),'compact investor UI missing');
assert(html.includes('TR-density main surface'),'TR-density main override missing');
assert(html.includes('.oracle-secondary,#orclWhy{display:none!important}'),'duplicate top sentiment/signal noise must stay hidden');
assert(html.includes('.shock-card{display:none!important}'),'price impulse card must stay off the main surface');
assert(html.includes('.value-status{display:none!important}'),'redundant valuation status line must stay hidden');
assert(html.includes('<title>alantu.de · Aktien</title>'),'alantu.de title branding missing');
assert(html.includes('<h1>alantu '),'compact alantu header branding missing');
assert(!html.includes('BotBot · Aktien'),'legacy BotBot visible branding must be gone');
assert(html.includes('href="methodik.html"'),'methodology info link missing');
assert(html.includes('href="methodik.html#intrinsic"'),'intrinsic methodology link missing');
assert(html.includes('class="hero-price" id="livePrice"'),'dominant live EUR price missing');
assert(html.includes("wss://streamer.finance.yahoo.com/?version=2"),'real-time Yahoo websocket missing');
assert(html.includes("subscribe:['ORCL','EURUSD=X']"),'ORCL+EURUSD live subscription missing');
assert(html.includes("style:'currency',currency:'EUR'"),'visible prices must format as EUR');
assert(html.includes('data-price-range="1m"')&&html.includes('data-sentiment-range="1m"')&&html.includes('data-magnitude-range="1m"'),'1M chart-local ranges missing');
assert(!html.includes('data-price-range="today"')&&!html.includes('data-sentiment-range="today"')&&!html.includes('data-magnitude-range="today"'),'Heute range should be removed');
assert(!html.includes('data-price-range="5m"')&&!html.includes('data-sentiment-range="5m"')&&!html.includes('data-magnitude-range="5m"'),'5M range should be removed');
assert(html.includes(">MAX</button>"),'MAX range missing');
assert(html.includes("function sentimentColor"),'sentiment threshold color missing');
assert(html.includes('function mixRgb(a,b,t)'),'continuous sentiment RGB interpolation missing');
assert(html.includes("return v<=50?mixRgb(red,neutral,v/50):mixRgb(neutral,green,(v-50)/50)"),'sentiment color must interpolate red-black-green continuously');
assert(html.includes('function sentimentSegmentGradient(ctx)'),'per-segment sentiment gradient missing');
assert(html.includes('ctx.chart.ctx.createLinearGradient(x0,py0,x1,py1)'),'sentiment gradient must follow actual segment x/y geometry');
assert(html.includes('g.addColorStop(0,c0);g.addColorStop(1,c1)'),'segment gradient endpoints missing');
assert(html.includes('Native browser overscroll/rubber-band when the platform supports it'),'native overscroll contract missing');
assert(html.includes('min-height:calc(100dvh + 1px)'),'native overscroll reserve missing');
assert(!html.includes('function initDesktopEdgeBounce()'),'custom desktop bounce must stay removed');
assert(!html.includes('edge-bounce-return'),'custom transform bounce must stay removed');
assert(html.includes("y:{min:-4,max:104"),'sentiment bounds need visual headroom');
assert(html.includes("scale.ticks=[{value:0},{value:50},{value:100}]"),'sentiment axis must still show semantic 0/50/100 ticks');
assert(html.includes("priceRangeColor"),'range price color missing');
assert(html.includes('#5dcb5b'),'TR reference green missing');
assert(!html.includes('#00c761')&&!html.includes('#00a94f'),'legacy custom green must stay out');
assert(html.includes('id="marketClock"'),'German market clock missing');
assert(html.includes('id="syncFooter"'),'sync footer missing');
assert(html.includes('id="syncNow"'),'manual sync button missing');
assert(html.includes("age>20*60*1000"),'stale sync threshold missing');
assert(html.includes('refreshFreshSignals'),'manual sync must perform real live signal refresh');
assert(html.includes('fetchTickerTick'),'browser live source fetch missing');
assert(html.includes('lastBrowserSyncAt=s.at'),'sync timestamp must only advance after fresh live signal calculation');
assert(!html.includes('lastBrowserSyncAt=new Date().toISOString()'),'loading a static snapshot must not fake a sync timestamp');
assert(html.includes("'Letzte Aktualisierung '+footerClock(lastAt)"),'last refresh timestamp missing');
assert(!html.includes('Sync-Fehler'),'sync error wording must stay off the main surface');
assert(!html.includes('Kurs nicht verfügbar'),'transient unavailable price wording must stay off the loading state');
assert(html.includes("btn.textContent=syncBusy?'↻ Aktualisiert …':'↻ Aktualisieren'"),'neutral refresh button wording missing');
assert(html.includes('market-clock-core.js'),'market clock core missing');
assert(!html.includes('positiv <span class="swatch neu"></span>neutral'),'persistent sentiment legend should stay off the TR-like main surface');
assert(html.includes('pointHoverRadius:4'),'line-chart hover marker missing');
assert(!html.includes('pointHoverRadius:0'),'hover marker must not be disabled');
assert(html.includes("label:'Innerer Wert'"),'German value label missing');
assert(html.includes("' · Kaufen < '+euro(buyAt,0)"),'compact buy-under price missing');
assert(html.includes('var buyAt=base!=null?base*0.75:null;'),'25 percent margin-of-safety calculation missing');
assert(!html.includes("' · Spanne '"),'value corridor must not be shown as a buy range');
assert(html.indexOf('id="ivChart"')>=0&&html.indexOf('id="ivChart"')<html.indexOf('Oracle · Stimmung'),'price/value chart must appear before sentiment chart');
assert(html.includes('href="methodik.html#sentiment"'),'sentiment info link missing');
assert(html.includes('id="sentimentSource"'),'sentiment source/count line missing');
assert(html.includes('id="sentimentRelation"'),'HDR relational sentiment line missing');
assert(html.includes('function hdrDailySentiment(rows)'),'HDR daily canonicalization missing');
assert(html.includes('function hdrRelationSeries(rows)'),'HDR relational engine missing');
assert(html.includes('daily.slice(0,i).filter'),'HDR relation must be past-only / no look-ahead');
assert(html.includes("cur.t-p.t<=366*864e5"),'HDR global baseline must be rolling one-year history');
assert(html.includes("prior.slice(-5)"),'HDR local neighborhood must use prior neighbors only');
assert(html.includes("Math.exp(-Math.LN2*(cur.t-p.t)/half)"),'HDR local neighbors must be time-distance weighted');
assert(html.includes("impact=Math.abs(cur.value-mean)/span"),'HDR proportional movement ratio missing');
assert(html.includes("deltas.filter(function(v){return v===dir;}).length"),'HDR neighbor direction confirmation missing');
assert(html.includes("if(visible.length>8)"),'HDR chart markers must stay visually sparse');
assert(html.includes("label:'Struktur'"),'HDR structural chart marker dataset missing');
assert(html.includes("parts.push('P'+h.percentile,'lokal '+z)"),'HDR current relation summary missing');
assert(html.includes("hdr.label+' · P'+hdr.percentile"),'HDR marker tooltip must expose relation details');
assert(!html.includes('sentiment3dToggle')&&!html.includes('hypeChart3d'),'3D sentiment view must stay out of realtime UI');
assert(!html.includes('sentimentReliability(h)')&&!html.includes('Z = Belastbarkeit'),'3D reliability rendering must stay removed for performance');
assert(html.includes('id="priceRange"'),'price-specific range controls missing');
assert(html.includes('id="sentimentRange"'),'sentiment-specific range controls missing');
assert(html.includes('id="magnitudeRange"'),'magnitude-specific range controls missing');
assert(html.includes('data-price-range="1d"')&&html.includes('data-price-range="all"'),'price range options incomplete');
assert(html.includes('data-sentiment-range="1d"')&&html.includes('data-sentiment-range="all"'),'sentiment range options incomplete');
assert(html.includes('data-magnitude-range="1d"')&&html.includes('data-magnitude-range="all"'),'magnitude range options incomplete');
assert(!html.includes('id="rangeBar"'),'global range bar must be removed');
assert(html.includes('class="mini-range"'),'compact chart-local ranges missing');
assert(html.includes("var priceRange=loadChartRange('price','1d')"),'independent price range state missing');
assert(html.includes("function berlinTradingWindowFor(value)"),'Berlin 1T window selector missing');
assert(html.includes("function latestBerlinTradingWindow(arr,getAt)"),'latest Berlin 1T window selector missing');
assert(html.includes("open:berlinZonedMs(p.year,p.month,p.day,8,0)"),'1T must start at 08:00 Europe/Berlin');
assert(html.includes("close:berlinZonedMs(p.year,p.month,p.day,22,0)"),'1T must end at 22:00 Europe/Berlin');
assert(html.includes("var end=isFinite(lastRow)?lastRow:session.open+60000"),'1T axis must end at latest available realtime/data point');
assert(html.includes("end=Math.min(session.close,Math.max(session.open+60000,end))"),'1T dynamic end must be capped at 22:00 Europe/Berlin');
assert(html.includes("liveMs>=session.open&&liveMs<=session.close"),'live quote must stay inside selected 08:00-22:00 window');
assert(html.includes("var sentimentRange=loadChartRange('sentiment','1m')"),'independent sentiment range state missing');
assert(html.includes("var magnitudeRange=loadChartRange('magnitude','1m')"),'independent magnitude range state missing');
assert(html.includes('id="sentimentHeroScore"'),'sentiment core metric missing');
assert(html.includes('id="sentimentHeroMeta"'),'sentiment core metric metadata missing');
assert(html.includes('function sentimentHeroMetaText(t)'),'compact sentiment hero meta missing');
assert(html.includes("count+' Signale'"),'sentiment hero should show compact signal count');
assert(html.includes('Paired core metrics'),'paired core metric layout missing');
assert(html.includes('grid-template-columns:minmax(0,1fr) minmax(0,1fr)'),'sentiment core metric must sit evenly beside live price');
assert(html.includes('.sentiment-hero-card{text-align:left'),'sentiment hero must left-align with live price');
assert(html.includes('id="sentimentHeroNumber"'),'sentiment hero number span missing');
assert(html.includes('class="sentiment-denom"> / 100</span>'),'sentiment denominator span missing');
assert(html.includes('.sentiment-denom{color:#151517!important}'),'sentiment denominator must stay black');
assert(html.includes("shn.textContent=sentimentScore!=null?String(sentimentScore):'—'"),'sentiment score must render independently from denominator');
assert(html.includes("CHART_OPEN_LS='alantu_chart_open_v1'"),'chart open-state storage missing');
assert(html.includes("function chartIsOpen(key){return chartOpenState[key]!==false;}"),'charts must default open');
assert(html.includes('data-chart-panel="price"')&&html.includes('data-chart-panel="sentiment"'),'main chart panels missing');
assert(html.includes('data-chart-panel="magnitude"')&&html.includes('data-chart-panel="opinions"'),'secondary chart panels missing');
assert(html.includes("localStorage.setItem(CHART_OPEN_LS,JSON.stringify(chartOpenState))"),'chart open-state persistence missing');
assert(html.includes("if(ch&&typeof ch.resize==='function')ch.resize();"),'chart reopen must resize in place');
assert(html.includes("b.textContent=open?'▴':'▾'"),'chart collapse affordance missing');
assert(html.includes('function sentimentSourceText'),'sentiment source renderer missing');
assert(html.includes('tickData.tick.live_sources'),'browser live source metadata missing');
assert(html.includes('SENTIMENT_HISTORY_LS'),'persistent browser sentiment history missing');
assert(html.includes('mergedSentimentHistory(x.orcl.history||[])'),'server/local sentiment history merge missing');
assert(html.includes('id="intrinsicToggle"'),'intrinsic visibility toggle missing');
assert(html.includes("INTRINSIC_VISIBLE_LS='alantu_intrinsic_visible_v1'"),'intrinsic toggle persistence missing');
assert(html.includes("ivChart.update('none')"),'intrinsic toggle must update in place');
assert(!html.includes('hypeChart.destroy'),'sentiment chart must not be destroyed on updates');
assert(!html.includes('ivChart.destroy'),'value chart must not be destroyed on updates');
assert(!html.includes('magChart.destroy'),'magnitude chart must not be destroyed on updates');
assert(html.includes('function updateLivePriceChart1d()'),'fast incremental 1T live updater missing');
assert(html.includes("var delay=priceRange==='1d'?180"),'1T live chart should update with low latency');
assert(html.includes("if(priceRange==='1d'&&updateLivePriceChart1d())return;"),'1T websocket ticks must avoid full chart rebuild');
assert(!html.includes('void p.offsetWidth'),'live price must not force synchronous layout on every tick');
assert(html.includes('id="marketFlow"'),'wave insight line missing from price chart');
assert(html.includes('function trendFit(points,getTime,getValue,windowMs)'),'multi-window wave vector missing');
assert(html.includes('function priceWave()'),'price wave component missing');
assert(html.includes('20*60000')&&html.includes('60*60000')&&html.includes('180*60000'),'price wave must use multiple horizons');
assert(html.includes('function volumeWave()'),'volume wave component missing');
assert(html.includes('windowFlow(30)')&&html.includes('windowFlow(90)'),'volume flow must use persistent multi-window pressure');
assert(html.includes('function sentimentWave()'),'sentiment wave component missing');
assert(html.includes('90*60000')&&html.includes('360*60000'),'sentiment wave must use slower multi-window timing');
assert(html.includes('function marketWaveVector()'),'wave phase classifier missing');
assert(html.includes("label='Welle baut sich auf'"),'wave build phase missing');
assert(html.includes("label='Welle bestätigt'"),'wave confirmation phase missing');
assert(html.includes("label='Welle dreht'"),'wave turn phase missing');
assert(html.includes("label='Welle läuft aus'"),'wave exhaustion phase missing');
assert(html.includes('if(evidence<2)'),'wave insight must fail closed without multi-dimensional evidence');
assert(html.includes('lastFlowRenderAt>=15000'),'wave interpretation must not thrash on every realtime tick');
assert(!html.includes('function livePricePace()')&&!html.includes('function marketFlowVector()'),'old short-term speed vector must stay removed');
assert(html.includes("if(kind==='price'){priceRange=r;saveChartRange(kind,r);syncRangeButtons();renderValueChart();}"),'price range must only rerender price chart');
assert(html.includes("else if(kind==='sentiment'){sentimentRange=r;saveChartRange(kind,r);syncRangeButtons();renderSentimentChart();renderOpinions();}"),'sentiment range must only rerender sentiment surface');
assert(html.includes("else if(kind==='magnitude'){magnitudeRange=r;saveChartRange(kind,r);syncRangeButtons();renderMagnitudeChart();}"),'magnitude range must only rerender magnitude chart');
assert(html.includes("T:ugc)',200"),'TickerTick UGC sample must request max 200');
assert(html.includes("(and E:oracle T:ugc)',200"),'second TickerTick entity UGC sample missing');
assert(html.includes('minSocial=50'),'minimum realtime social sample gate missing');
assert(html.includes("throw new Error('Zu wenig frische Social-Daten: '+social.length+'/'+minSocial)"),'social minimum must fail closed');
assert(html.includes('social_breakdown:s.socialBreakdown||{}'),'social source breakdown metadata missing');
assert(!html.includes('public.api.bsky.app'),'blocked Bluesky dependency must stay out of production');
assert(html.includes('function liveRecencyWeight(ms)'),'realtime recency weighting missing');
assert(html.includes('if(age<=2*3600e3)return 1.5'),'2h sentiment recency weight missing');
assert(html.includes('if(age<=8*3600e3)return 1.25'),'8h sentiment recency weight missing');
assert(html.includes('return 0.65'),'older sentiment decay missing');
assert(html.includes('justify-content:space-between;width:100%;margin:5px 0 0'),'TR-like flat bottom range layout missing');
assert(!html.includes(".mini-range{display:inline-flex;flex:0 0 auto;gap:1px;background:#f5f5f7"),'pill-style chart range regression');

assert(!html.includes('Berechnung & Grenzen'),'large inline value explainer should stay off the compact view');
assert(methodik.includes('Innerer Wert: exakte Berechnung'),'detailed intrinsic methodology page missing');
assert(methodik.includes('Owner Earnings ='),'owner earnings formula missing from methodology');
assert(methodik.includes('TickerTick API'),'live source documentation missing');
assert(methodik.includes('ApeWisdom'),'fallback Reddit source documentation missing');
assert(methodik.includes('Yahoo Finance WebSocket'),'live price source documentation missing');
assert(methodik.includes('Exakte SEC-Inputdatensätze'),'SEC input table missing');
assert(methodik.includes('Kaufen unter = Basis-Intrinsic-Value × (1 - 0,25)'),'25 percent margin-of-safety documentation missing');
assert(methodik.includes('Historischer Stimmungsverlauf'),'historical sentiment methodology missing');
assert(methodik.includes('18.08.2026'),'real sentiment history start disclosure missing');
assert(methodik.includes('exactLiveSources'),'methodology must use the same browser live/fallback source contract');
assert(methodik.includes('Aktueller Fallback-Datensatz (raw)'),'raw fallback dataset disclosure missing');
const methodikScripts=[...methodik.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)].map(x=>x[1]);
assert(methodikScripts.length,'methodology inline script missing');
new Function(methodikScripts.join('\n;\n'));
assert(!html.includes('keine Anlageberatung'),'disclaimer must stay removed');
assert(html.includes('aggregateForRange'),'range aggregation missing');
assert(html.includes("enabled:!isTouchChart()"),'mobile chart tooltip must be disabled');
assert(html.includes("function chartEvents(){return isTouchChart()?[]"),'mobile chart events must be disabled');
assert(html.includes("if(range==='1w'||range==='1m')mode='day'"),'1W/1M must aggregate daily');
assert(html.includes("else if(range==='year')mode='week'"),'1J must aggregate weekly');
assert(html.includes("else if(range==='5y'||range==='all')mode='month'"),'5J/MAX must aggregate monthly');
assert(!html.includes('wlRange'),'legacy shared range state must be gone');
assert(html.includes("fill:false"),'sentiment chart must not use filled fragments');
assert(!html.includes("{label:'Bullisch %',data:"),'bull line should not clutter primary chart');
assert(!html.includes("{label:'Bearisch %',data:"),'bear line should not clutter primary chart');
assert(html.includes("label:'Innerer Wert'"),'German intrinsic-value line missing');
assert(!html.includes("{label:'Konservativer Wert',data:"),'conservative line should not clutter primary chart');
assert(!html.includes("{label:'Obere Sensitivität',data:"),'upper line should not clutter primary chart');
assert(html.includes("type:'linear'"),'charts must use a real numeric time axis');
assert(html.includes('spanGaps:false'),'charts must not bridge missing data');
assert(html.includes('coverage<0.72||startsLate||endsEarly'),'adaptive chart bounds missing');
assert(html.includes("Daten verfügbar '+fmtAxisValue(stats.xs[0],range)"),'coverage hint missing');
assert(html.includes("axisX(agg"),'sentiment chart must use aggregated adaptive time bounds');
assert(html.includes("axisX(hist"),'magnitude chart must use adaptive time bounds');
assert(html.includes("priceAxisX(s.priceRows,s.session)"),'price chart must use NYSE-aware selected price rows');
assert(html.includes('data-price-range="5y"')&&html.includes('data-sentiment-range="5y"')&&html.includes('data-magnitude-range="5y"'),'5J chart-local ranges missing');
assert(html.includes("style:'currency',currency:'EUR'"),'UI must format money in EUR');
assert(html.includes('function usdToEur'),'USD to EUR conversion missing');
assert(html.includes('function fxAt'),'historical FX lookup missing');
assert(html.includes('Preisalarm aktivieren'),'alarm wording regression');
assert(!html.includes("+' · same-origin'"),'internal transport wording leaked to UI');
assert(!html.includes('query1.finance.yahoo.com'),'browser must not use Yahoo REST directly');
assert(!html.includes('query2.finance.yahoo.com'),'browser must not use Yahoo REST directly');
assert(html.includes("fetch('orcl-minute.json?t='"),'price shock fallback must be same-origin');
assert(html.includes("fetchJson('orcl-history.json'"),'long-range ORCL history feed missing');
assert(html.includes('orclDailyBars'),'daily ORCL chart series missing');
assert(html.includes("else if(orclDailyBars.length)"),'1M/1J/5J/MAX must prefer fresh daily ORCL prices');
assert(html.includes('function updateLivePriceChart1d()'),'live quote must use the incremental 1T price updater');
assert(html.includes("if(priceRange==='1d'&&updateLivePriceChart1d())return;"),'1T live quote must avoid full chart rebuild');
assert(html.includes(".chart-wrap canvas { max-height: none"),'chart canvases must not inherit 190px max-height clip');
assert(html.includes("grace:'8%'"),'price/value chart needs light y-grace');
assert(html.includes('Math.min(now,last+pad)'),'adaptive x-max must not run past now');
assert(html.includes("y:{min:-4,max:104"),'sentiment chart needs headroom while preserving semantic 0/50/100 ticks');

assert.equal(intr.currency_display,'USD');
assert.equal(intr.method,'buffett_owner_earnings_maintenance_capex_corridor');
assert(intr.latest.intrinsic_low_usd>0);
assert(intr.latest.intrinsic_low_usd<intr.latest.intrinsic_base_usd);
assert(intr.latest.intrinsic_base_usd<intr.latest.intrinsic_high_usd);
assert.equal(intr.latest.intrinsic_usd,intr.latest.intrinsic_base_usd);
assert(!('intrinsic_eur' in intr.latest));
assert.equal(intr.valuation_snapshots.length,source.filing_inputs.length);

const dcf=(ps)=>{
  const m=intr.model; let e=ps,pv=0;
  for(let y=1;y<=m.years;y++){e*=1+m.growth_10y;pv+=e/Math.pow(1+m.discount_rate,y);}
  return pv+(e*(1+m.terminal_growth)/(m.discount_rate-m.terminal_growth))/Math.pow(1+m.discount_rate,m.years);
};
for(const s of intr.valuation_snapshots){
  const base=s.operating_cash_flow_m-s.financing_like_customer_prepayments_m-s.stock_based_compensation_m-s.depreciation_m-s.preferred_dividends_m;
  assert.equal(Number(base.toFixed(1)),s.owner_earnings_m,s.label+' base owner earnings');
  assert(s.intrinsic_low_usd<=s.intrinsic_base_usd&&s.intrinsic_base_usd<=s.intrinsic_high_usd,s.label+' corridor order');
  assert(Math.abs(dcf(s.normalized_owner_earnings_ps_usd)-s.intrinsic_base_usd)<=0.02,s.label+' DCF');
}
assert(source.filing_inputs.find(x=>x.label==='FY2022').source.includes('000156459022023675'),'FY2022 must use FY2022 filing');
assert.equal(source.filing_inputs.find(x=>x.label==='FY2023').effective_at,'2023-06-21T00:00:00Z');
assert.equal(source.filing_inputs.find(x=>x.label==='FY2024').effective_at,'2024-06-21T00:00:00Z');
assert.equal(source.filing_inputs.find(x=>x.label==='FY2025').effective_at,'2025-06-20T00:00:00Z');
assert.equal(source.filing_inputs.find(x=>x.label==='FY2026').effective_at,'2026-06-23T00:00:00Z');
assert.equal(source.filing_inputs.find(x=>x.label==='TTM Q1 FY2027').effective_at,'2026-09-14T00:00:00Z');

for(const h of intr.history){
  if(!h.valuation_basis){
    assert.equal(h.intrinsic_base_usd,null);
    assert.equal(h.intrinsic_usd,null);
  }else{
    const s=intr.valuation_snapshots.find(x=>x.label===h.valuation_basis);
    assert(s);
    assert(new Date(s.effective_at)<=new Date(h.at),'look-ahead');
    assert.equal(h.intrinsic_base_usd,s.intrinsic_base_usd);
    assert.equal(h.intrinsic_usd,s.intrinsic_base_usd);
  }
}
// Critical no-look-ahead boundary checks.
assert.equal(intr.history.find(x=>x.at.startsWith('2026-09-11'))?.valuation_basis,'FY2026');
assert.equal(intr.history.find(x=>x.at.startsWith('2026-09-14'))?.valuation_basis,'TTM Q1 FY2027');


assert(!JSON.stringify(trend.tick?.sources||{}).includes('Apify'),'Apify source keys must be gone');
assert(!('user-Apify-Reddit' in (trend.tick?.sources||{})),'user-Apify-Reddit must be removed');
assert(!('user-Apify-TikTok' in (trend.tick?.sources||{})),'user-Apify-TikTok must be removed');
assert(trend.tick?.sources?.PublicReddit,'PublicReddit aggregator source missing');

console.log('stockstrend contract: OK');

// UI expects the deploy workflow to generate eurusd-history.json for EUR conversion.
