import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);
if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader","--autoplay-policy=no-user-gesture-required"]});
const page=await browser.newPage();
try{
  await page.setViewport({width:844,height:390,deviceScaleFactor:1});
  await page.goto(url.href,{waitUntil:"load",timeout:30000});
  await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready"),{timeout:30000});
  await page.waitForFunction(()=>document.body.classList.contains("solo-flight")&&globalThis.__arondightRealWorld?.threeScene&&globalThis.__arondightRealWorld?.threeCamera,{timeout:10000});
  const result=await page.evaluate(async()=>{
    const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
    const bridge=globalThis.__arondightRealWorld,viewport=document.querySelector("#viewport"),sent=[],poses=[];
    document.body.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,pointerType:"touch"}));await sleep(120);
    bridge.vsConnected=true;bridge.vsSession={setOrigin(){return true;},setPose(pose){poses.push(JSON.parse(JSON.stringify(pose)));return true;},sendCombat(packet){sent.push(JSON.parse(JSON.stringify(packet)));return true;},stop(){}};bridge.resetVsCombat(true);
    const own=bridge.airframeFor?.(bridge.threeScene)||bridge.airframe;if(!own?.position)throw new Error("local airframe missing");const ox=own.position.x,oy=own.position.y,oz=own.position.z;
    bridge.applyVsPose({p:[ox+10,oy,oz],q:[0,0,0,1]});
    let readable=null,hitbox=null;const visualDeadline=performance.now()+5000;
    while(performance.now()<visualDeadline){
      if(bridge.vsPeerMesh?.children?.length){readable=null;hitbox=null;bridge.vsPeerMesh.traverse(node=>{if(node.userData?.vsReadableVisual)readable=node;if(node.userData?.vsCombatHitbox)hitbox=node;});if(readable&&hitbox&&Number(viewport.dataset.vsPeerVisualScale)===12)break;}
      await sleep(50);
    }
    if(!bridge.vsPeerMesh?.children?.length)throw new Error("peer mesh missing after real pose path");
    if(!readable)throw new Error(`12x readable peer visual missing · scale=${viewport.dataset.vsPeerVisualScale||"unset"} · children=${bridge.vsPeerMesh.children.length}`);if(!hitbox)throw new Error(`visible-envelope peer hitbox missing · scale=${viewport.dataset.vsPeerHitboxScale||"unset"} · children=${bridge.vsPeerMesh.children.length}`);
    const marker=document.querySelector("#vsEnemyMarker"),distanceM=Number(viewport.dataset.vsEnemyDistanceM),hpFill=marker?.querySelector(".vs-enemy-hp>b"),reticle=marker?.querySelector(".vs-enemy-reticle"),reticleStyle=getComputedStyle(reticle);
    const hitboxScale=Number(viewport.dataset.vsPeerHitboxScale),visualScale=Number(viewport.dataset.vsPeerVisualScale),hitboxM=String(viewport.dataset.vsPeerHitboxM||"").split("x").map(Number);
    const markerBefore={exists:Boolean(marker),hidden:Boolean(marker?.hidden),text:marker?.textContent||"",mode:viewport.dataset.vsEnemyMarker||"",distanceM,expectedDistanceM:10,hpFill:Boolean(hpFill),hpTransform:hpFill?.style?.transform||"",emissiveIntensity:Number(readable?.material?.emissiveIntensity)||0,color:readable?.material?.color?.getHex?.()||0,audioReady:viewport.dataset.vsExplosionAudioReady||"",audioState:viewport.dataset.vsExplosionAudioState||"",visualScale,hitboxScale,hitboxM,reticleBorder:reticleStyle.borderTopWidth,reticleWidth:reticleStyle.width};
    const hitOk=bridge.registerVsHit({object:hitbox}),shot=sent.find(p=>p.type==="hit");if(!hitOk||!shot)throw new Error("visible-envelope peer hit was not emitted");
    bridge.applyVsCombat({type:"state",id:shot.id,hp:0,killed:true});await sleep(100);
    const killed={kills:bridge.vsKills,peerHp:bridge.vsPeerHealth,peerDead:bridge.vsPeerDead,explosion:Boolean(bridge.vsExplosion?.visible),peerVisible:bridge.vsPeerMesh.visible,hud:document.querySelector("#vsCombatHud")?.textContent||"",enemyMarker:marker?.textContent||"",respawnHud:document.querySelector("#vsRespawnHud")?.textContent||"",respawnHidden:Boolean(document.querySelector("#vsRespawnHud")?.hidden),respawnState:viewport.dataset.vsRespawnState||"",soundCount:Number(viewport.dataset.vsExplosionSoundCount)||0,audioStartedCount:Number(viewport.dataset.vsExplosionAudioStartedCount)||0,audioState:viewport.dataset.vsExplosionAudioState||"",flash:Boolean(document.querySelector("#vsExplosionFlash")?.classList.contains("pulse"))};
    bridge.applyVsCombat({type:"respawn",hp:100});bridge.applyVsPose({p:[ox+10,oy,oz],q:[0,0,0,1]});await sleep(100);const peerRespawn={peerHp:bridge.vsPeerHealth,peerDead:bridge.vsPeerDead,marker:marker?.textContent||"",respawnHidden:Boolean(document.querySelector("#vsRespawnHud")?.hidden),respawnState:viewport.dataset.vsRespawnState||""};
    bridge.applyVsCombat({type:"hit",id:"incoming-1",damage:25});const hpAfterFirst=bridge.vsLocalHealth;bridge.applyVsCombat({type:"hit",id:"incoming-1",damage:25});const hpAfterDuplicate=bridge.vsLocalHealth;const state=sent.find(p=>p.type==="state"&&p.id==="incoming-1");
    bridge.applyVsCombat({type:"hit",id:"incoming-2",damage:25});bridge.applyVsCombat({type:"hit",id:"incoming-3",damage:25});bridge.applyVsCombat({type:"hit",id:"incoming-4",damage:25});await sleep(80);
    const localAirframe=bridge.airframeFor?.(bridge.threeScene)||bridge.airframe,respawnButton=document.querySelector("#vsRespawnHud button");
    const localDeath={hp:bridge.vsLocalHealth,dead:bridge.vsLocalDead,deaths:bridge.vsDeaths,respawnHud:document.querySelector("#vsRespawnHud")?.textContent||"",respawnHidden:Boolean(document.querySelector("#vsRespawnHud")?.hidden),respawnState:viewport.dataset.vsRespawnState||"",resetButton:Boolean(respawnButton&&!respawnButton.hidden),resetText:respawnButton?.textContent||"",airframeVisible:Boolean(localAirframe?.visible),timer:bridge.vsRespawnTimer,soundCount:Number(viewport.dataset.vsExplosionSoundCount)||0,audioStartedCount:Number(viewport.dataset.vsExplosionAudioStartedCount)||0,audioState:viewport.dataset.vsExplosionAudioState||"",flashLocal:Boolean(document.querySelector("#vsExplosionFlash")?.classList.contains("local"))};
    respawnButton?.click();await sleep(160);bridge.updateVsPose?.();await sleep(30);const respawnAirframe=bridge.airframeFor?.(bridge.threeScene)||bridge.airframe,lastPose=poses.at(-1)||null,radius=Number(viewport.dataset.vsRespawnRadiusM);
    const localRespawn={hp:bridge.vsLocalHealth,dead:bridge.vsLocalDead,airframeVisible:Boolean(respawnAirframe?.visible),respawnHidden:Boolean(document.querySelector("#vsRespawnHud")?.hidden),respawnState:viewport.dataset.vsRespawnState||"",manual:Number(viewport.dataset.vsManualRespawns||0),radius,mode:viewport.dataset.vsRespawnMode||"",offset:viewport.dataset.vsRespawnOffsetM||"",lastPose,respawnPacket:sent.findLast?.(p=>p.type==="respawn")||[...sent].reverse().find(p=>p.type==="respawn")};
    const dataset={hp:viewport.dataset.vsLocalHealth,mate:viewport.dataset.vsPeerHealth,kills:viewport.dataset.vsKills,deaths:viewport.dataset.vsDeaths};bridge.stopVs();return{hitOk,shot,markerBefore,killed,peerRespawn,hpAfterFirst,hpAfterDuplicate,state,localDeath,localRespawn,dataset};
  });
  if(result.shot.damage!==25)throw new Error(`unexpected hit damage: ${JSON.stringify(result)}`);
  if(!result.markerBefore.exists||result.markerBefore.hidden||!result.markerBefore.text.includes("ENEMY")||!result.markerBefore.mode)throw new Error(`enemy HUD marker missing: ${JSON.stringify(result.markerBefore)}`);
  if(!Number.isFinite(result.markerBefore.distanceM)||Math.abs(result.markerBefore.distanceM-result.markerBefore.expectedDistanceM)>.25)throw new Error(`enemy distance is not drone-to-drone: ${JSON.stringify(result.markerBefore)}`);
  if(!result.markerBefore.hpFill||!result.markerBefore.hpTransform.includes("scaleX(1)"))throw new Error(`enemy HP bar missing: ${JSON.stringify(result.markerBefore)}`);
  if(result.markerBefore.emissiveIntensity<2||result.markerBefore.color===0||result.markerBefore.visualScale!==12||!(result.markerBefore.hitboxScale>result.markerBefore.visualScale)||result.markerBefore.hitboxM.length!==3||!result.markerBefore.hitboxM.every(v=>Number.isFinite(v)&&v>=.7))throw new Error(`enemy visual/hitbox envelope mismatch: ${JSON.stringify(result.markerBefore)}`);
  if(result.markerBefore.reticleBorder!=="1px"||Number.parseFloat(result.markerBefore.reticleWidth)>22)throw new Error(`enemy indicator is still too dominant: ${JSON.stringify(result.markerBefore)}`);
  if(result.markerBefore.audioReady!=="1"||result.markerBefore.audioState!=="running")throw new Error(`combat audio was not primed by a real user gesture: ${JSON.stringify(result.markerBefore)}`);
  if(result.killed.kills!==1||result.killed.peerHp!==0||!result.killed.peerDead||!result.killed.explosion||result.killed.peerVisible)throw new Error(`kill/explosion state failed: ${JSON.stringify(result.killed)}`);
  if(!result.killed.enemyMarker.includes("DOWN")||result.killed.respawnHidden||!result.killed.respawnHud.includes("ENEMY DESTROYED")||!result.killed.respawnHud.includes("WAITING FOR RESET")||result.killed.respawnState!=="enemy")throw new Error(`enemy destruction indication missing: ${JSON.stringify(result.killed)}`);
  if(result.killed.soundCount<1||result.killed.audioStartedCount<1||result.killed.audioState!=="running"||!result.killed.flash)throw new Error(`enemy explosion audio/visual feedback missing: ${JSON.stringify(result.killed)}`);
  if(result.peerRespawn.peerHp!==100||result.peerRespawn.peerDead||!result.peerRespawn.marker.includes("ENEMY")||!result.peerRespawn.respawnHidden||result.peerRespawn.respawnState!=="none")throw new Error(`enemy respawn presentation did not clear on authoritative respawn packet: ${JSON.stringify(result.peerRespawn)}`);
  if(result.hpAfterFirst!==75)throw new Error(`player health did not take damage: ${JSON.stringify(result)}`);if(result.hpAfterDuplicate!==75)throw new Error(`duplicate hit changed health twice: ${JSON.stringify(result)}`);if(result.state?.hp!==75||result.state?.killed!==false)throw new Error(`health acknowledgement missing: ${JSON.stringify(result.state)}`);
  if(result.localDeath.hp!==0||!result.localDeath.dead||result.localDeath.deaths!==1||result.localDeath.respawnHidden||result.localDeath.respawnState!=="local"||!result.localDeath.respawnHud.includes("DESTROYED")||!result.localDeath.respawnHud.includes("RESET SIM")||!result.localDeath.resetButton||result.localDeath.resetText.trim()!=="RESET SIM"||result.localDeath.airframeVisible||result.localDeath.timer!==0)throw new Error(`local death/reset latch failed: ${JSON.stringify(result.localDeath)}`);
  if(result.localDeath.soundCount<2||result.localDeath.audioStartedCount<2||result.localDeath.audioState!=="running"||!result.localDeath.flashLocal)throw new Error(`local destruction audio/visual feedback missing: ${JSON.stringify(result.localDeath)}`);
  if(result.localRespawn.hp!==100||result.localRespawn.dead||!result.localRespawn.airframeVisible||!result.localRespawn.respawnHidden||result.localRespawn.respawnState!=="none"||result.localRespawn.manual!==1||!(result.localRespawn.radius>=12&&result.localRespawn.radius<=30)||!["canonical-offset","world-origin"].includes(result.localRespawn.mode)||result.localRespawn.respawnPacket?.hp!==100)throw new Error(`manual nearby respawn failed: ${JSON.stringify(result.localRespawn)}`);
  if(result.localRespawn.mode==="canonical-offset"&&(!result.localRespawn.lastPose?.p||Math.hypot(Number(result.localRespawn.lastPose.p[0])||0,Number(result.localRespawn.lastPose.p[1])||0)<11.5))throw new Error(`training respawn offset was not carried into outgoing pose: ${JSON.stringify(result.localRespawn)}`);
  if(result.dataset.kills!=="1"||result.dataset.deaths!=="1")throw new Error(`combat score dataset failed: ${JSON.stringify(result.dataset)}`);
  console.log("VS combat browser smoke passed: 12x readable enemy, matching padded hitbox, restrained marker, explosion/disappear death state, centered RESET SIM and randomized 12-30 m manual respawn.");
}finally{await browser.close();}
