import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader","--autoplay-policy=no-user-gesture-required"]}),page=await browser.newPage();
try{
  await page.setViewport({width:844,height:390,deviceScaleFactor:1});await page.goto(url.href,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready"),{timeout:30000});await page.waitForFunction(()=>document.body.classList.contains("solo-flight")&&globalThis.__arondightRealWorld?.threeScene&&globalThis.__arondightRealWorld?.threeCamera,{timeout:10000});
  const result=await page.evaluate(async()=>{
    const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms)),waitFor=async(fn,timeout=7000)=>{const end=performance.now()+timeout;while(performance.now()<end){const value=fn();if(value)return value;await sleep(25);}throw Error("multiplayer browser wait timeout");};
    const bridge=globalThis.__arondightRealWorld,view=document.querySelector("#viewport"),sentGame=[],sentFx=[],sentCombat=[],peerIds=["peer-b","peer-c"];let authority="peer-a";
    bridge.vsConnected=true;bridge.ensureVsPeerMesh?.();
    const fake={primaryPeerId:"peer-b",getSelfId:()=>"peer-a",getAuthorityId:()=>authority,getPeerIds:()=>[...peerIds],setOrigin:()=>true,setPose:()=>true,sendCombat(packet,options={}){sentCombat.push({packet:structuredClone(packet),options:structuredClone(options)});return true;},sendGame(packet,options={}){sentGame.push({packet:structuredClone(packet),options:structuredClone(options)});return true;},sendFx(packet,options={}){sentFx.push({packet:structuredClone(packet),options:structuredClone(options)});return true;},stop(){}};
    bridge.vsSession=fake;
    dispatchEvent(new CustomEvent("arondight45:vs-peer",{detail:{type:"join",peerId:"peer-b",selfId:"peer-a",authorityId:"peer-a",peerIds:[...peerIds],transport:"Test"}}));
    dispatchEvent(new CustomEvent("arondight45:vs-peer",{detail:{type:"join",peerId:"peer-c",selfId:"peer-a",authorityId:"peer-a",peerIds:[...peerIds],transport:"Test"}}));
    const now=performance.now();dispatchEvent(new CustomEvent("arondight45:vs-pose",{detail:{peerId:"peer-b",pose:{p:[10,0,2],q:[0,0,0,1],v:[0,0,0],t:now,f:"local-metric"}}}));dispatchEvent(new CustomEvent("arondight45:vs-pose",{detail:{peerId:"peer-c",pose:{p:[-8,6,3],q:[0,0,.1,.995],v:[0,0,0],t:now+1,f:"local-metric"}}}));
    await waitFor(()=>view.dataset.vsPlayerCount==="3"&&document.querySelectorAll(".vs-player-marker").length===2&&bridge.threeScene.children.some(node=>node.userData?.vsMultiplayerPeer));await sleep(520);
    const colors=JSON.parse(view.dataset.vsPlayerColors||"{}"),colorValues=Object.values(colors),extra=bridge.threeScene.children.find(node=>node.userData?.vsMultiplayerPeer&&node.userData?.vsPlayerId==="peer-c"),extraHitbox=extra?.children?.find(node=>node.userData?.vsCombatHitbox),primary=bridge.vsPeerMesh,primaryHitbox=(()=>{let hit=null;primary?.traverse?.(node=>{if(node.userData?.vsCombatHitbox)hit=node;});return hit;})();
    if(colorValues.length!==3||new Set(colorValues).size!==3)throw Error(`player colors are not unique: ${JSON.stringify(colors)}`);if(!extra||!extraHitbox||!primary||!primaryHitbox)throw Error("multi-player meshes/hitboxes missing");if(String(extra.userData.vsPlayerColor)===String(primary.userData.vsPlayerColor))throw Error("remote meshes still share the same color");
    const hitAccepted=bridge.registerVsHit({object:extraHitbox});if(!hitAccepted)throw Error("second remote player hitbox was not accepted");await waitFor(()=>sentGame.some(item=>item.packet.type==="state"&&item.packet.playerId==="peer-c"&&item.packet.hp===75));
    dispatchEvent(new CustomEvent("arondight45:vs-fx",{detail:{peerId:"peer-b",packet:{type:"shot",id:"remote-shot",from:[2,1,2],dir:[1,0,0],speed:210,playerId:"peer-b",t:Date.now()}}}));dispatchEvent(new CustomEvent("arondight45:vs-fx",{detail:{peerId:"peer-c",packet:{type:"explosion",id:"remote-boom",p:[-4,3,2],playerId:"peer-c"}}}));await waitFor(()=>Number(view.dataset.vsRemoteShots||0)>=1&&Number(view.dataset.vsRemoteExplosions||0)>=1);
    const fireBefore=sentFx.length,rect=view.getBoundingClientRect();view.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,cancelable:true,pointerId:901,pointerType:"touch",clientX:rect.left+rect.width*.5,clientY:rect.top+rect.height*.5,button:0}));await waitFor(()=>sentFx.slice(fireBefore).some(item=>item.packet.type==="shot"),4000);view.dispatchEvent(new PointerEvent("pointerup",{bubbles:true,cancelable:true,pointerId:901,pointerType:"touch",button:0}));
    peerIds.splice(peerIds.indexOf("peer-b"),1);fake.primaryPeerId="peer-c";dispatchEvent(new CustomEvent("arondight45:vs-peer",{detail:{type:"leave",peerId:"peer-b",selfId:"peer-a",authorityId:"peer-a",peerIds:[...peerIds],transport:"Test"}}));await waitFor(()=>view.dataset.vsPeerCount==="1"&&bridge.vsPeerMesh?.userData?.vsPlayerId==="peer-c");if(!bridge.vsPeerMesh.parent)throw Error("legacy primary mesh was removed when primary peer changed");
    authority="peer-c";dispatchEvent(new CustomEvent("arondight45:vs-peer",{detail:{type:"join",peerId:"peer-c",selfId:"peer-a",authorityId:"peer-c",peerIds:[...peerIds],transport:"Test"}}));await waitFor(()=>sentGame.some(item=>item.packet.report===true&&item.packet.playerId==="peer-a"&&item.options?.target==="peer-c"));
    authority="peer-a";dispatchEvent(new CustomEvent("arondight45:vs-peer",{detail:{type:"join",peerId:"peer-c",selfId:"peer-a",authorityId:"peer-a",peerIds:[...peerIds],transport:"Test"}}));await waitFor(()=>view.dataset.vsAuthorityId==="peer-a");

    bridge.active=true;bridge.originLon=9;bridge.originLat=47;bridge.minimapFeatures=[{kind:"road",geometryType:"LineString",paths:[[[9,47],[9.0015,47],[9.003,47.0002]]]}];
    await waitFor(()=>Number(view.dataset.worldTrafficRoutes||0)>=1&&bridge.threeScene.children.some(node=>node.userData?.worldPopulationKind==="car"&&node.visible)&&bridge.threeScene.children.some(node=>node.userData?.worldPopulationKind==="person"&&node.visible),8000);
    let carMesh=null,personMesh=null;bridge.threeScene.traverse(node=>{if(node?.isMesh&&node.userData?.worldPopulationId){if(node.userData.worldPopulationKind==="car"&&!carMesh)carMesh=node;if(node.userData.worldPopulationKind==="person"&&!personMesh)personMesh=node;}});if(!carMesh||!personMesh)throw Error("WORLD population meshes were not shootable");
    const worldFxBefore=sentFx.length;if(!bridge.registerWorldPopulationHit?.({object:carMesh}))throw Error("car hit was not accepted");if(!bridge.registerWorldPopulationHit?.({object:personMesh}))throw Error("person hit was not accepted");await waitFor(()=>sentFx.slice(worldFxBefore).some(item=>item.packet.objectId&&item.packet.kind==="car"&&item.packet.type==="explosion")&&sentFx.slice(worldFxBefore).some(item=>item.packet.objectId&&item.packet.kind==="person"&&item.packet.type==="impact"));
    const world={routes:Number(view.dataset.worldTrafficRoutes||0),cars:Number(view.dataset.worldCars||0),people:Number(view.dataset.worldPeople||0),hits:Number(view.dataset.worldPopulationHits||0),lastHit:view.dataset.worldPopulationLastHit||""};bridge.active=false;
    return{colors,playerCount:Number(view.dataset.vsPlayerCount),peerCount:Number(view.dataset.vsPeerCount),remoteShots:Number(view.dataset.vsRemoteShots||0),remoteExplosions:Number(view.dataset.vsRemoteExplosions||0),state75:sentGame.some(item=>item.packet.type==="state"&&item.packet.playerId==="peer-c"&&item.packet.hp===75),localShotReplicated:sentFx.some(item=>item.packet.type==="shot"),authorityReport:sentGame.some(item=>item.packet.report===true&&item.options?.target==="peer-c"),primaryAlive:Boolean(bridge.vsPeerMesh?.parent),world};
  });
  if(result.playerCount<2||result.peerCount!==1||new Set(Object.values(result.colors)).size<3||!result.state75||!result.localShotReplicated||result.remoteShots<1||result.remoteExplosions<1||!result.authorityReport||!result.primaryAlive)throw new Error(`multi-player browser regression: ${JSON.stringify(result)}`);
  if(result.world.routes<1||result.world.cars<1||result.world.people<1||result.world.hits<2)throw new Error(`WORLD population regression: ${JSON.stringify(result.world)}`);
  console.log("VS multiplayer browser smoke passed: unique 3-player colors/meshes, replicated shots/explosions, primary+authority migration, and shootable road cars/people with car explosions.");
}finally{await browser.close();}
