import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage();
try{
  await page.setViewport({width:844,height:390,deviceScaleFactor:1});await page.goto(url.href,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready")&&document.body.classList.contains("solo-flight")&&globalThis.__arondightRealWorld?.threeScene,{timeout:30000});
  const result=await page.evaluate(async()=>{
    const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms)),errors=[],stages=[];const waitFor=async(label,fn,timeout=5000)=>{const end=performance.now()+timeout;while(performance.now()<end){if(fn()){stages.push(label);return;}await sleep(25);}throw Error(`VS boot stage timeout: ${label}`);};
    addEventListener("error",event=>errors.push(`error:${event.message||event.error||"unknown"}`));addEventListener("unhandledrejection",event=>errors.push(`rejection:${String(event.reason?.stack||event.reason||"unknown")}`));
    const bridge=globalThis.__arondightRealWorld,view=document.querySelector("#viewport"),peerIds=["peer-b","peer-c"],sentGame=[],sentFx=[];let authority="peer-a";
    bridge.vsConnected=true;bridge.ensureVsPeerMesh?.();bridge.vsSession={primaryPeerId:"peer-b",getSelfId:()=>"peer-a",getAuthorityId:()=>authority,getPeerIds:()=>[...peerIds],setOrigin:()=>true,setPose:()=>true,sendCombat:()=>true,sendGame(packet,options={}){sentGame.push({packet:structuredClone(packet),options:structuredClone(options)});return true;},sendFx(packet,options={}){sentFx.push({packet:structuredClone(packet),options:structuredClone(options)});return true;},stop(){}};
    for(const peerId of peerIds)dispatchEvent(new CustomEvent("arondight45:vs-peer",{detail:{type:"join",peerId,selfId:"peer-a",authorityId:"peer-a",peerIds:[...peerIds],transport:"Test"}}));
    const now=performance.now();for(const [i,peerId] of peerIds.entries())dispatchEvent(new CustomEvent("arondight45:vs-pose",{detail:{peerId,pose:{p:[10-i*18,i*6,2+i],q:[0,0,0,1],v:[0,0,0],t:now+i,f:"local-metric"}}}));
    await waitFor("peers+box3d",()=>view.dataset.vsPlayerCount==="3"&&Number(view.dataset.box3dCombatPeers)>=2&&Number(view.dataset.box3dVsCombatVisualScale)===7);
    await waitFor("primary-v3-owned-visible",()=>bridge.vsPeerMesh?.userData?.vsPlayerId==="peer-b"&&bridge.vsPeerMesh?.visible&&view.dataset.vsPrimaryRenderOwner==="multiplayer-v3");
    const extra=bridge.threeScene.children.find(node=>node.userData?.vsMultiplayerPeer&&node.userData?.vsPlayerId==="peer-c");let extraTarget=null;extra?.traverse?.(node=>{if(!extraTarget&&node?.isMesh)extraTarget=node;});if(!extraTarget)throw Error("VS boot extra visible mesh missing");
    if(!bridge.registerVsHit({object:extraTarget}))throw Error("VS boot visible-mesh hit rejected");await waitFor("authoritative-hit",()=>sentGame.some(item=>item.packet.type==="state"&&item.packet.playerId==="peer-c"&&item.packet.hp===75));
    dispatchEvent(new CustomEvent("arondight45:vs-fx",{detail:{peerId:"peer-c",packet:{type:"shot",id:"boot-shot",from:[1,2,3],dir:[1,0,0],speed:210,playerId:"peer-c",t:Date.now()}}}));dispatchEvent(new CustomEvent("arondight45:vs-fx",{detail:{peerId:"peer-c",packet:{type:"explosion",id:"boot-boom",p:[2,3,1],playerId:"peer-c"}}}));await waitFor("remote-fx",()=>Number(view.dataset.vsRemoteShots)>=1&&Number(view.dataset.vsRemoteExplosions)>=1);
    peerIds.splice(peerIds.indexOf("peer-b"),1);bridge.vsSession.primaryPeerId="peer-c";dispatchEvent(new CustomEvent("arondight45:vs-peer",{detail:{type:"leave",peerId:"peer-b",selfId:"peer-a",authorityId:"peer-a",peerIds:[...peerIds],transport:"Test"}}));await waitFor("primary-migration",()=>view.dataset.vsPeerCount==="1"&&bridge.vsPeerMesh?.userData?.vsPlayerId==="peer-c"&&bridge.vsPeerMesh?.visible);
    authority="peer-c";dispatchEvent(new CustomEvent("arondight45:vs-peer",{detail:{type:"join",peerId:"peer-c",selfId:"peer-a",authorityId:"peer-c",peerIds:[...peerIds],transport:"Test"}}));await waitFor("authority-report",()=>sentGame.some(item=>item.packet.report===true&&item.packet.playerId==="peer-a"&&item.options?.target==="peer-c"));
    const scenePeers=bridge.threeScene.children.filter(node=>node.userData?.vsMultiplayerPeer||node===bridge.vsPeerMesh).map(node=>({id:node.userData?.vsPlayerId||"",multi:Boolean(node.userData?.vsMultiplayerPeer),legacy:node===bridge.vsPeerMesh,visible:Boolean(node.visible),scale:[node.scale.x,node.scale.y,node.scale.z],combatScale:node.userData?.vsCombatVisualScale||null,kind:node.userData?.worldLifeKind||"",worldId:node.userData?.worldLifeId||"",children:node.children.length}));
    return{stages,self:view.dataset.vsSelfId||"",authority:view.dataset.vsAuthorityId||"",playerCount:view.dataset.vsPlayerCount||"",peerCount:view.dataset.vsPeerCount||"",owner:view.dataset.vsPrimaryRenderOwner||"",markers:[...document.querySelectorAll(".vs-player-marker")].map(el=>el.dataset.peerId),scenePeers,boxPeerCount:Number(globalThis.__arondightBox3dCombat?.peerCount??-1),boxDataset:Number(view.dataset.box3dCombatPeers??-1),boxVisualScale:Number(view.dataset.box3dVsCombatVisualScale??-1),boxPadding:Number(view.dataset.box3dVsHitboxPadding??-1),combatVisualScale:Number(view.dataset.vsCombatVisualScale??-1),remoteShots:Number(view.dataset.vsRemoteShots||0),remoteExplosions:Number(view.dataset.vsRemoteExplosions||0),errors:errors.slice(-8),sentGame:sentGame.slice(-8).map(x=>x.packet),sentFx:sentFx.slice(-4).map(x=>x.packet)};
  });
  if(result.owner!=="multiplayer-v3"||result.peerCount!=="1"||result.boxPeerCount<2||result.boxDataset<2||result.boxVisualScale!==7||result.combatVisualScale!==7||Math.abs(result.boxPadding-1.16)>.001||result.remoteShots<1||result.remoteExplosions<1||result.errors.length)throw new Error(`VS peer boot regression: ${JSON.stringify(result)}`);
  console.log(`VS peer boot passed: ${JSON.stringify(result)}`);
}finally{await browser.close();}
