import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage();
try{
  await page.setUserAgent("Mozilla/5.0 (iPad; CPU OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Mobile/15E148 Safari/604.1");
  await page.setViewport({width:1024,height:768,deviceScaleFactor:1});await page.goto(url.href,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready"),{timeout:30000});await page.waitForFunction(()=>globalThis.__arondightRealWorld?.threeScene,{timeout:10000});
  const result=await page.evaluate(async()=>{
    const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms)),waitFor=async(fn,timeout=8000)=>{const end=performance.now()+timeout;while(performance.now()<end){const value=fn();if(value)return value;await sleep(30);}throw Error("ragdoll wait timeout");};
    const bridge=globalThis.__arondightRealWorld,view=document.querySelector("#viewport");bridge.active=true;bridge.originLon=9;bridge.originLat=47;bridge.minimapFeatures=[{kind:"road",geometryType:"LineString",paths:[[[9,47],[9.0015,47],[9.003,47]]]}];
    await waitFor(()=>Number(view.dataset.worldTrafficRoutes||0)>=1&&typeof bridge.registerWorldPopulationHit==="function"&&bridge.threeScene.children.some(node=>node.userData?.worldPedestrianArticulated&&node.visible));
    const personGroup=bridge.threeScene.children.find(node=>node.userData?.worldPedestrianArticulated&&node.visible);if(!personGroup)throw Error("articulated visible pedestrian missing");personGroup.updateMatrixWorld(true);
    let personMesh=null,shirt=null,pants=null,skin=null,liveMinZ=Infinity;personGroup.traverse(node=>{if(!node?.isMesh)return;if(!personMesh&&node.userData?.worldPopulationId)personMesh=node;const kind=node.userData?.worldPopulationBodyPart;if(kind==="shirt"&&!Number.isFinite(shirt))shirt=node.material?.color?.getHex?.();if(kind==="pants"&&!Number.isFinite(pants))pants=node.material?.color?.getHex?.();if((kind==="skin"||kind==="head")&&!Number.isFinite(skin))skin=node.material?.color?.getHex?.();node.geometry?.computeBoundingBox?.();const box=node.geometry?.boundingBox?.clone?.();if(box){box.applyMatrix4(node.matrixWorld);liveMinZ=Math.min(liveMinZ,box.min.z);}});if(!personMesh)throw Error("shootable articulated pedestrian mesh missing");
    const personId=personMesh.userData.worldPopulationId,liveColors={shirt,pants,skin};if(liveMinZ<-.025)throw Error(`walking pedestrian is buried below ground: ${liveMinZ}`);if(!bridge.registerWorldPopulationHit({object:personMesh}))throw Error("pedestrian shot was not accepted");
    await waitFor(()=>Number(view.dataset.worldRagdolls||0)>=1&&Number(view.dataset.worldRagdollParts||0)>=16&&bridge.threeScene.children.some(node=>node.userData?.worldRagdollRoot&&node.visible));
    const root=bridge.threeScene.children.find(node=>node.userData?.worldRagdollRoot&&node.visible),parts=[];if(!root.userData?.worldRagdollHuman)throw Error("corpse is not a human articulated ragdoll");root.updateMatrixWorld(true);let ragMinZ=Infinity;root.traverse(node=>{if(!node?.userData?.worldRagdollPart)return;parts.push(node);node.geometry?.computeBoundingBox?.();const box=node.geometry?.boundingBox?.clone?.();if(box){box.applyMatrix4(node.matrixWorld);ragMinZ=Math.min(ragMinZ,box.min.z);}});if(parts.length<16)throw Error(`ragdoll has too few human body parts: ${parts.length}`);
    const colors=root.userData.worldRagdollColors||{};if(colors.shirt!==liveColors.shirt||colors.pants!==liveColors.pants||colors.skin!==liveColors.skin)throw Error(`ragdoll changed pedestrian colors: ${JSON.stringify({liveColors,colors})}`);if(ragMinZ<-.04)throw Error(`ragdoll body penetrated ground: ${ragMinZ}`);
    const before=parts.map(node=>[node.position.x,node.position.y,node.position.z]);await sleep(480);const after=parts.map(node=>[node.position.x,node.position.y,node.position.z]);let maxMove=0;for(let i=0;i<Math.min(before.length,after.length);i++)maxMove=Math.max(maxMove,Math.hypot(after[i][0]-before[i][0],after[i][1]-before[i][1],after[i][2]-before[i][2]));
    const visibleOriginal=Boolean(personGroup.visible),pool=Number(view.dataset.worldRagdollPool||0),maxPool=Number(view.dataset.worldRagdollMax||0),spawns=Number(view.dataset.worldRagdollSpawns||0),active=Number(view.dataset.worldRagdolls||0),partCount=Number(view.dataset.worldRagdollParts||0),lastId=view.dataset.worldRagdollLastId||"";bridge.active=false;return{personId,visibleOriginal,pool,maxPool,spawns,active,partCount,lastId,maxMove,liveMinZ,ragMinZ,liveColors,colors};
  });
  if(result.visibleOriginal)throw new Error(`shot pedestrian did not hand off to ragdoll: ${JSON.stringify(result)}`);if(result.maxPool!==6||result.pool!==6)throw new Error(`iPad ragdoll pool is not mobile-bounded to six: ${JSON.stringify(result)}`);if(result.spawns<1||result.active<1||result.partCount<16||result.lastId!==result.personId)throw new Error(`human articulated ragdoll did not spawn correctly: ${JSON.stringify(result)}`);if(!(result.maxMove>.05))throw new Error(`ragdoll did not react physically to shot/gravity: ${JSON.stringify(result)}`);
  console.log("WORLD pedestrian ragdoll browser smoke passed: grounded articulated pedestrian, exact color handoff, iPad pool=6, 16 human body parts and physical shot/gravity response.");
}finally{await browser.close();}
