import puppeteer from "puppeteer-core";

const input=process.argv[2]||"http://127.0.0.1:4174/drone_simulator.html",inputUrl=new URL(input,"http://127.0.0.1:4174"),url=inputUrl.pathname.endsWith("/drone_simulator.html")?new URL(inputUrl.href):new URL("/drone_simulator.html",inputUrl.origin),executablePath=process.env.CHROME_BIN;
if(process.env.GITHUB_SHA)url.searchParams.set("ci",process.env.GITHUB_SHA);if(!executablePath)throw new Error("CHROME_BIN must point to Chrome/Chromium");
const browser=await puppeteer.launch({headless:true,executablePath,args:["--no-sandbox","--disable-dev-shm-usage","--enable-webgl","--ignore-gpu-blocklist","--use-gl=angle","--use-angle=swiftshader"]}),page=await browser.newPage();
try{
  await page.setUserAgent("Mozilla/5.0 (iPad; CPU OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Mobile/15E148 Safari/604.1");
  await page.setViewport({width:1024,height:768,deviceScaleFactor:1});await page.goto(url.href,{waitUntil:"load",timeout:30000});await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.includes("SIM ready"),{timeout:30000});await page.waitForFunction(()=>globalThis.__arondightRealWorld?.threeScene,{timeout:10000});
  const result=await page.evaluate(async()=>{
    const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms)),waitFor=async(fn,timeout=10000)=>{const end=performance.now()+timeout;while(performance.now()<end){const value=fn();if(value)return value;await sleep(30);}throw Error("traffic wait timeout");};
    const bridge=globalThis.__arondightRealWorld,view=document.querySelector("#viewport"),sentFx=[],road=[[[9,47],[9.0015,47],[9.003,47]]];bridge.active=true;bridge.originLon=9;bridge.originLat=47;bridge.vsSession={sendFx(packet){sentFx.push(structuredClone(packet));return true;}};bridge.minimapFeatures=[{kind:"road",geometryType:"LineString",paths:road}];
    const car=await waitFor(()=>bridge.threeScene.children.find(node=>node.userData?.worldPopulationKind==="car"&&node.userData?.worldPopulationId&&node.visible));const id=car.userData.worldPopulationId,p0=car.position.clone();let body=null;car.traverse(node=>{if(!body&&node?.isMesh&&node.userData?.worldPopulationKind==="car")body=node;});if(!body)throw Error("shootable car body missing");const color=body.material?.color?.getHex?.();if(!(Math.abs(p0.y)>.65&&Math.abs(p0.y)<1.05))throw Error(`car is not centered in a real road lane: y=${p0.y}`);
    bridge.minimapFeatures=[];await sleep(2550);const sameAfterGap=bridge.threeScene.children.find(node=>node.userData?.worldPopulationId===id),p1=sameAfterGap?.position?.clone?.();if(!sameAfterGap?.visible||!p1)throw Error("car disappeared during temporary road-feature refresh gap");const gapMove=p1.distanceTo(p0);if(!(gapMove>.5&&gapMove<55))throw Error(`car continuity broke during route gap: ${gapMove}`);
    bridge.minimapFeatures=[{kind:"road",geometryType:"LineString",paths:[road[0].slice().reverse()]}];await sleep(2450);const sameAfterReverse=bridge.threeScene.children.find(node=>node.userData?.worldPopulationId===id),p2=sameAfterReverse?.position?.clone?.();if(!sameAfterReverse?.visible||!p2)throw Error("car disappeared when OSM road direction reversed");const reverseMove=p2.distanceTo(p1);if(!(reverseMove>.4&&reverseMove<55))throw Error(`road direction refresh teleported car: ${reverseMove}`);if(!(Math.abs(p2.y)>.65&&Math.abs(p2.y)<1.05))throw Error(`car drifted off lane after route refresh: y=${p2.y}`);
    if(!bridge.registerWorldPopulationHit?.({object:body}))throw Error("car shot was not accepted");await waitFor(()=>Number(view.dataset.worldCarWrecks||0)>=1&&Number(view.dataset.worldCarWreckParts||0)>=7&&bridge.threeScene.children.some(node=>node.userData?.worldCarWreckRoot&&node.visible));const wreck=bridge.threeScene.children.find(node=>node.userData?.worldCarWreckRoot&&node.visible);if(wreck.userData.worldCarWreckId!==id)throw Error("wrong car wreck identity");if(wreck.userData.worldCarWreckColor!==color)throw Error(`wreck paint changed: ${wreck.userData.worldCarWreckColor} != ${color}`);const parts=[];wreck.traverse(node=>{if(node?.userData?.worldCarWreckPart)parts.push(node);});if(parts.length!==7)throw Error(`expected 7 physical wreck parts, got ${parts.length}`);const before=parts.map(node=>[node.position.x,node.position.y,node.position.z]);await sleep(520);const after=parts.map(node=>[node.position.x,node.position.y,node.position.z]);let maxMove=0;for(let i=0;i<parts.length;i++)maxMove=Math.max(maxMove,Math.hypot(after[i][0]-before[i][0],after[i][1]-before[i][1],after[i][2]-before[i][2]));if(!(maxMove>.35))throw Error(`wreck debris did not move physically: ${maxMove}`);if(car.visible)throw Error("destroyed source car remained visible");const packet=sentFx.find(p=>p.type==="explosion"&&p.objectId===id);if(!packet||packet.color!==color||!Array.isArray(packet.impulse)||packet.impulse.length!==3||!Number.isFinite(packet.yaw))throw Error(`network explosion lacks deterministic wreck state: ${JSON.stringify(packet)}`);
    const result={id,gapMove,reverseMove,laneY:p2.y,color,wreckColor:wreck.userData.worldCarWreckColor,maxMove,pool:Number(view.dataset.worldCarWreckPool||0),maxPool:Number(view.dataset.worldCarWreckMax||0),parts:Number(view.dataset.worldCarWreckParts||0),stableRoutes:Number(view.dataset.worldTrafficStableRoutes||0),sentExplosion:Boolean(packet)};bridge.active=false;return result;
  });
  if(result.maxPool!==4||result.pool!==4)throw new Error(`iPad car wreck pool must stay bounded to four: ${JSON.stringify(result)}`);if(result.parts!==7||result.stableRoutes<1||!result.sentExplosion)throw new Error(`WORLD road traffic/car explosion regression: ${JSON.stringify(result)}`);
  console.log("WORLD traffic browser smoke passed: stable road/lane identity across refreshes, no random despawn/teleport, and deterministic 7-piece physical car wreck explosions on iPad.");
}finally{await browser.close();}
