import * as THREE from "three";
import Box3DFactory from "box3d.js/inline";
import {VS_FX_EVENT} from "./lan_vs.mjs";
import {createWorldBuildingCollisionBodies,destroyWorldBuildingCollisionBodies} from "./world_building_collision_physics.mjs";

const FIXED_DT=1/120;
const MAX_STEPS=6;
const BULLET_POOL=64;
const BULLET_TTL_MS=1800;
const BULLET_RADIUS=.018;
const CAT_WORLD=1n;
const CAT_CAR=2n;
const CAT_PERSON=4n;
const CAT_TREE=8n;
const CAT_OTHER=16n;
const CAT_BULLET=32n;
const TARGET_MASK=CAT_BULLET;
const BULLET_MASK=CAT_WORLD|CAT_CAR|CAT_PERSON|CAT_TREE|CAT_OTHER;
const FX_KIND="box3d-bullet-v1";
const VS_COMBAT_VISUAL_SCALE=7;
const VS_HITBOX_PADDING=1.16;

const b3=await Box3DFactory();
const worldDef=b3.b3DefaultWorldDef();
worldDef.gravity=[0,0,-9.80665];
worldDef.enableContinuous=true;
worldDef.maximumLinearSpeed=520;
worldDef.hitEventThreshold=.5;
const world=b3.b3CreateWorld(worldDef);

const targets=new Map(),shapeTargets=new Map(),bulletShapes=new Map(),seenFx=new Set(),treeBodies=[];
const tmpPos=new THREE.Vector3(),tmpQuat=new THREE.Quaternion(),tmpScale=new THREE.Vector3(),instanceMatrix=new THREE.Matrix4();
let installed=false,sceneRef=null,baseAdd=null,lastFrame=performance.now(),accumulator=0,lastBuildingHash="",buildingState=null,treeSource=null,treeMatrixVersion=-1,treeCount=-1,bulletCursor=0,activeBullets=0,patchedSession=null,lastPhysicsError="",physicsFrames=0;
const eventsBuffer=b3.createEventsBuffer(),touch=b3.createContactTouchEvent(),hitEvent=b3.createContactHitEvent();

function bridge(){return globalThis.__arondightRealWorld||null;}
function viewport(){return document.getElementById("viewport");}
function idKey(id){if(id==null)return"";if(typeof id==="number"||typeof id==="bigint"||typeof id==="string")return String(id);if(Array.isArray(id))return id.join(":");if(typeof id==="object")return`${id.index1??id.index??""}:${id.world0??id.world??""}:${id.generation??id.generation0??""}`;return String(id);}
function kindOf(node){if(node?.userData?.vsHumanAvatar)return"vs-player";const raw=String(node?.userData?.worldLifeKind||node?.userData?.worldPopulationKind||"");return raw.startsWith("life-")?raw.slice(5):raw;}
function idOf(node){return String(node?.userData?.worldLifeId||node?.userData?.worldPopulationId||node?.userData?.vsPlayerId||"");}
function hitMesh(root){let result=null;root?.traverse?.(n=>{if(!result&&n?.isMesh&&!n.userData?.flightFireIgnore)result=n;});if(!result)root?.traverse?.(n=>{if(!result&&n?.isMesh)result=n;});return result||root;}
function specFor(kind){if(kind==="car")return{cat:CAT_CAR,shape:"box",half:[1.82,.86,.72],z:.72};if(kind==="bus")return{cat:CAT_CAR,shape:"box",half:[4.05,1.20,1.18],z:1.18};if(kind==="person"||kind==="vs-player")return{cat:CAT_PERSON,shape:"capsule",radius:.25,halfHeight:.58,z:.88};if(kind==="vs-drone")return{cat:CAT_OTHER,shape:"box",half:[.16*VS_COMBAT_VISUAL_SCALE*VS_HITBOX_PADDING,.22*VS_COMBAT_VISUAL_SCALE*VS_HITBOX_PADDING,.05*VS_COMBAT_VISUAL_SCALE*VS_HITBOX_PADDING],z:0};if(kind==="bird")return{cat:CAT_OTHER,shape:"sphere",radius:.28,z:.25};return{cat:CAT_OTHER,shape:"box",half:[.45,.45,.45],z:.45};}
function notePhysicsError(stage,error){const message=`${stage}:${String(error?.message||error||"unknown")}`;const v=viewport();if(v){v.dataset.box3dPhysicsErrors=String((Number(v.dataset.box3dPhysicsErrors)||0)+1);v.dataset.box3dLastPhysicsError=message.slice(0,180);}if(message!==lastPhysicsError){lastPhysicsError=message;console.error("Box3D combat",stage,error);}}
function destroyTarget(record){if(!record)return;shapeTargets.delete(idKey(record.shape));targets.delete(record.id);try{if(record.body&&b3.b3Body_IsValid(record.body))b3.b3DestroyBody(record.body);}catch{}}
function createTarget(root){const id=idOf(root);if(!id)return null;const existing=targets.get(id);if(existing?.root===root)return existing;if(existing)destroyTarget(existing);const kind=kindOf(root)||"object",spec=specFor(kind);root.updateWorldMatrix?.(true,false);root.getWorldPosition(tmpPos);root.getWorldQuaternion(tmpQuat);const def=b3.b3DefaultBodyDef();def.type=b3.b3BodyType.b3_kinematicBody;def.position=[tmpPos.x,tmpPos.y,tmpPos.z+spec.z];def.rotation=[tmpQuat.x,tmpQuat.y,tmpQuat.z,tmpQuat.w];def.enableSleep=false;def.enableContactRecycling=false;const body=b3.b3CreateBody(world,def),sd=b3.b3DefaultShapeDef();sd.filter={categoryBits:spec.cat,maskBits:TARGET_MASK,groupIndex:0};sd.enableContactEvents=true;sd.enableHitEvents=true;sd.baseMaterial.friction=.55;sd.baseMaterial.restitution=.06;let shape;if(spec.shape==="capsule")shape=b3.b3CreateCapsuleShape(body,sd,{center1:[0,0,-spec.halfHeight],center2:[0,0,spec.halfHeight],radius:spec.radius});else if(spec.shape==="sphere")shape=b3.b3CreateSphereShape(body,sd,{center:[0,0,0],radius:spec.radius});else shape=b3.b3CreateBoxShape(body,sd,...spec.half);const record={id,kind,root,body,shape,spec,mesh:hitMesh(root),lastAt:performance.now(),enabled:true};targets.set(id,record);shapeTargets.set(idKey(shape),record);root.userData.box3dCombatBody=true;root.userData.box3dCombatKind=kind;return record;}
function trackedRoot(node){const kind=kindOf(node);return Boolean(node?.children?.length&&idOf(node)&&!node.userData?.worldPopulationClone&&["car","bus","person","bird","vs-player","vs-drone"].includes(kind));}
function indexNode(node){if(!node)return;if(trackedRoot(node))createTarget(node);if(node.name==="WORLD_LIVELINESS_TREES"){const source=node.children?.find?.(x=>x?.isInstancedMesh);if(source&&source!==treeSource){treeSource=source;treeMatrixVersion=-1;treeCount=-1;}}}
function indexSubtree(root){root?.traverse?.(indexNode);}
function registerTarget(root){if(!root)return null;indexSubtree(root);return targets.get(idOf(root))||null;}
function patchScene(scene){if(!scene||scene===sceneRef)return;sceneRef=scene;for(const record of [...targets.values()])destroyTarget(record);clearTrees();treeSource=null;treeMatrixVersion=-1;treeCount=-1;indexSubtree(scene);if(!scene.__box3dCombatAddPatched){baseAdd=scene.add;scene.add=function(...objects){const out=baseAdd.apply(this,objects);for(const object of objects)indexSubtree(object);return out;};scene.__box3dCombatAddPatched=true;}const v=viewport();if(v)v.dataset.box3dCombatIndex="scene-add+boot-v4";}
function updateTarget(record,now){const root=record.root;if(!root?.parent){destroyTarget(record);return;}if(root.visible===false){if(record.enabled){try{b3.b3Body_Disable(record.body);}catch{}record.enabled=false;}record.lastAt=now;return;}if(!record.enabled){try{b3.b3Body_Enable(record.body);}catch{}record.enabled=true;}root.updateWorldMatrix?.(true,false);root.getWorldPosition(tmpPos);root.getWorldQuaternion(tmpQuat);const dt=Math.max(.001,Math.min(.05,(now-record.lastAt)/1000)),position=[tmpPos.x,tmpPos.y,tmpPos.z+record.spec.z],rotation=[tmpQuat.x,tmpQuat.y,tmpQuat.z,tmpQuat.w];try{if(typeof b3.b3Body_SetTargetTransform==="function")b3.b3Body_SetTargetTransform(record.body,{position,quaternion:rotation},dt,true);else b3.b3Body_SetTransform(record.body,position,rotation);}catch{try{b3.b3Body_SetTransform(record.body,position,rotation);}catch{}}record.lastAt=now;}

function clearTrees(){for(const item of treeBodies){shapeTargets.delete(idKey(item.shape));try{if(item.body&&b3.b3Body_IsValid(item.body))b3.b3DestroyBody(item.body);}catch{}}treeBodies.length=0;}
function rebuildTrees(){if(!treeSource?.parent)return;const version=Number(treeSource.instanceMatrix?.version)||0,count=Math.max(0,Number(treeSource.count)||0);if(version===treeMatrixVersion&&count===treeCount&&treeBodies.length===count)return;treeMatrixVersion=version;treeCount=count;clearTrees();treeSource.updateWorldMatrix?.(true,false);for(let i=0;i<count;i++){treeSource.getMatrixAt(i,instanceMatrix);instanceMatrix.premultiply(treeSource.matrixWorld);instanceMatrix.decompose(tmpPos,tmpQuat,tmpScale);const def=b3.b3DefaultBodyDef();def.type=b3.b3BodyType.b3_staticBody;def.position=[tmpPos.x,tmpPos.y,tmpPos.z];def.rotation=[tmpQuat.x,tmpQuat.y,tmpQuat.z,tmpQuat.w];const body=b3.b3CreateBody(world,def),sd=b3.b3DefaultShapeDef();sd.filter={categoryBits:CAT_TREE,maskBits:TARGET_MASK,groupIndex:0};const shape=b3.b3CreateBoxShape(body,sd,Math.max(.12,.16*tmpScale.x),Math.max(.12,.16*tmpScale.y),Math.max(.85,1.15*tmpScale.z));const rec={id:`tree-${i}`,kind:"tree",root:treeSource,body,shape,spec:{z:0},mesh:treeSource};treeBodies.push(rec);shapeTargets.set(idKey(shape),rec);}const v=viewport();if(v)v.dataset.box3dTreeRebuilds=String((Number(v.dataset.box3dTreeRebuilds)||0)+1);}
function syncBuildings(){const snapshot=bridge()?.buildingCollisionSnapshot,hash=String(snapshot?.hash||"");if(hash===lastBuildingHash)return;lastBuildingHash=hash;destroyWorldBuildingCollisionBodies(b3,buildingState);buildingState=createWorldBuildingCollisionBodies(b3,world,snapshot,{categoryBits:CAT_WORLD,maskBits:CAT_BULLET,rangefinderCategoryBits:0n,projectileCategoryBits:CAT_BULLET,launchExclusionPoint:[Infinity,Infinity]});const v=viewport();if(v){v.dataset.box3dCombatBuildings=String(buildingState?.shapeCount||0);v.dataset.box3dCombatBuildingHash=hash;}}

const groundDef=b3.b3DefaultBodyDef();groundDef.type=b3.b3BodyType.b3_staticBody;groundDef.position=[0,0,-.08];const groundBody=b3.b3CreateBody(world,groundDef),groundShapeDef=b3.b3DefaultShapeDef();groundShapeDef.filter={categoryBits:CAT_WORLD,maskBits:CAT_BULLET,groupIndex:0};const groundShape=b3.b3CreateBoxShape(groundBody,groundShapeDef,10000,10000,.08);shapeTargets.set(idKey(groundShape),null);

const bulletPool=[];
function createBullet(index){const def=b3.b3DefaultBodyDef();def.type=b3.b3BodyType.b3_dynamicBody;def.position=[0,0,-999];def.gravityScale=1;def.enableSleep=false;def.enableContactRecycling=false;def.isBullet=true;def.isEnabled=false;def.linearDamping=0;def.angularDamping=0;const body=b3.b3CreateBody(world,def),sd=b3.b3DefaultShapeDef();sd.density=26;sd.filter={categoryBits:CAT_BULLET,maskBits:BULLET_MASK,groupIndex:0};sd.enableContactEvents=true;sd.enableHitEvents=true;sd.baseMaterial.friction=.04;sd.baseMaterial.restitution=.02;const shape=b3.b3CreateSphereShape(body,sd,{center:[0,0,0],radius:BULLET_RADIUS});const mesh=new THREE.Mesh(new THREE.SphereGeometry(BULLET_RADIUS*1.7,5,4),new THREE.MeshBasicMaterial({color:0xffd78c}));mesh.visible=false;mesh.userData.flightFireIgnore=true;mesh.userData.box3dBullet=true;const bullet={index,body,shape,mesh,active:false,id:"",born:0,source:"",weapon:"",damage:0,remote:false,scratch:[0,0,0]};bulletPool.push(bullet);bulletShapes.set(idKey(shape),bullet);return bullet;}
for(let i=0;i<BULLET_POOL;i++)createBullet(i);
function attachBulletMeshes(){const scene=bridge()?.threeScene;if(!scene)return;for(const bullet of bulletPool)if(!bullet.mesh.parent)scene.add(bullet.mesh);}
function deactivateBullet(bullet){if(!bullet?.active)return;bullet.active=false;bullet.mesh.visible=false;bullet.mesh.position.set(0,0,-999);activeBullets=Math.max(0,activeBullets-1);try{b3.b3Body_Disable(bullet.body);}catch{}const v=viewport();if(v)v.dataset.box3dActiveBullets=String(activeBullets);}
function bulletPosition(bullet,out=new THREE.Vector3()){b3.b3Body_GetPosition(bullet.scratch,bullet.body);return out.set(Number(bullet.scratch[0])||0,Number(bullet.scratch[1])||0,Number(bullet.scratch[2])||0);}
function spawnBullet({id="",origin,direction,speed=360,source="unknown",weapon="pistol",damage=50,remote=false,replicate=false}={}){if(!origin||!direction)return null;const o=Array.isArray(origin)?origin:[origin.x,origin.y,origin.z],d=Array.isArray(direction)?direction:[direction.x,direction.y,direction.z],len=Math.hypot(Number(d[0])||0,Number(d[1])||0,Number(d[2])||0)||1,ux=(Number(d[0])||0)/len,uy=(Number(d[1])||0)/len,uz=(Number(d[2])||0)/len,px=Number(o[0])||0,py=Number(o[1])||0,pz=Number(o[2])||0,bullet=bulletPool[bulletCursor++%bulletPool.length];if(bullet.active)deactivateBullet(bullet);bullet.id=String(id||`b3-${Date.now().toString(36)}-${bulletCursor.toString(36)}`);bullet.born=performance.now();bullet.source=source;bullet.weapon=weapon;bullet.damage=Number(damage)||0;bullet.remote=Boolean(remote);bullet.mesh.position.set(px,py,pz);try{b3.b3Body_SetTransform(bullet.body,[px,py,pz],[0,0,0,1]);b3.b3Body_SetLinearVelocity(bullet.body,[ux*speed,uy*speed,uz*speed]);b3.b3Body_SetAngularVelocity(bullet.body,[0,0,0]);b3.b3Body_SetBullet(bullet.body,true);b3.b3Body_Enable(bullet.body);}catch(error){bullet.mesh.visible=false;notePhysicsError("bullet-spawn",error);return null;}bullet.active=true;bullet.mesh.visible=true;activeBullets++;if(replicate)replicateBullet(bullet,[px,py,pz],[ux,uy,uz],speed);const v=viewport();if(v){v.dataset.box3dActiveBullets=String(activeBullets);v.dataset.box3dBulletSpawns=String((Number(v.dataset.box3dBulletSpawns)||0)+1);v.dataset.box3dBulletModel="dynamic-isBullet-ccd-v3";}return bullet;}
function replicateBullet(bullet,origin,dir,speed){const session=bridge()?.vsSession;if(!session?.sendFx)return;try{session.sendFx({type:"physics-bullet",kind:FX_KIND,id:bullet.id,from:[...origin],dir:[...dir],speed:Number(speed)||360,weapon:bullet.weapon,damage:bullet.damage,t:Date.now()});const v=viewport();if(v)v.dataset.box3dReplicatedBullets=String((Number(v.dataset.box3dReplicatedBullets)||0)+1);}catch{}}
function rememberFx(id){const key=String(id||"");if(!key||seenFx.has(key))return false;seenFx.add(key);if(seenFx.size>512){const first=seenFx.values().next().value;seenFx.delete(first);}return true;}
function onFx(event){const packet=event?.detail?.packet||event?.detail;if(packet?.type!=="physics-bullet"||packet?.kind!==FX_KIND||!rememberFx(packet.id))return;spawnBullet({id:packet.id,origin:packet.from,direction:packet.dir,speed:packet.speed,weapon:packet.weapon,damage:packet.damage,source:"remote",remote:true,replicate:false});}
function patchLegacyWalkReplication(){const session=bridge()?.vsSession;if(!session||session===patchedSession||typeof session.sendFx!=="function")return;const base=session.sendFx.bind(session);session.sendFx=(packet,...rest)=>{const legacyWalk=globalThis.__arondightWalkMode?.mode==="foot"&&viewport()?.dataset.walkProjectileModel?.startsWith("box3d-isBullet-ccd")&&packet?.type==="shot"&&packet?.kind==="pistol"&&String(packet?.id||"").startsWith("pistol-");if(legacyWalk){const v=viewport();if(v)v.dataset.box3dLegacyWalkFxSuppressed=String((Number(v.dataset.box3dLegacyWalkFxSuppressed)||0)+1);return Promise.resolve(false);}return base(packet,...rest);};session.__box3dPhysicsBulletReplication=true;patchedSession=session;}

function impactPointFor(bullet,p){if(Array.isArray(p)&&p.length>=3)return new THREE.Vector3(Number(p[0])||0,Number(p[1])||0,Number(p[2])||0);return bulletPosition(bullet,new THREE.Vector3());}
function processContact(shapeA,shapeB,p=null){const a=bulletShapes.get(idKey(shapeA)),b=bulletShapes.get(idKey(shapeB)),bullet=a||b;if(!bullet?.active)return false;const other=a?shapeB:shapeA,target=shapeTargets.get(idKey(other))||null,impact=impactPointFor(bullet,p);let handled=false;if(target){const hit={object:target.mesh,point:impact,distance:0};const br=bridge();if((target.kind==="vs-player"||target.kind==="vs-drone")&&typeof br?.registerVsHit==="function")handled=Boolean(br.registerVsHit(hit));if(!handled&&typeof br?.registerWorldPopulationHit==="function")handled=Boolean(br.registerWorldPopulationHit(hit));if(!handled)window.dispatchEvent(new CustomEvent("arondight:target-damage",{detail:{kind:target.kind,id:target.id,damage:bullet.damage,physics:true}}));}window.dispatchEvent(new CustomEvent("arondight:box3d-impact",{detail:{point:{x:impact.x,y:impact.y,z:impact.z},normal:{x:0,y:0,z:1},targetId:target?.id||"",targetKind:target?.kind||"world",handled,source:bullet.source,weapon:bullet.weapon,bulletId:bullet.id}}));const v=viewport();if(v){v.dataset.box3dBulletImpacts=String((Number(v.dataset.box3dBulletImpacts)||0)+1);v.dataset.box3dLastImpactKind=target?.kind||"world";}deactivateBullet(bullet);return true;}
function processEvents(){b3.getEvents(eventsBuffer,world);for(let i=0,n=b3.getNumContactHitEvents(eventsBuffer);i<n;i++){b3.getContactHitEventAt(hitEvent,eventsBuffer,i);processContact(hitEvent.shapeIdA,hitEvent.shapeIdB,hitEvent.point);}for(let i=0,n=b3.getNumContactBeginEvents(eventsBuffer);i<n;i++){b3.getContactBeginEventAt(touch,eventsBuffer,i);processContact(touch.shapeIdA,touch.shapeIdB,null);}}
function updateBulletVisuals(now){attachBulletMeshes();for(const bullet of bulletPool){if(!bullet.active)continue;if(now-bullet.born>BULLET_TTL_MS){deactivateBullet(bullet);continue;}try{bulletPosition(bullet,bullet.mesh.position);}catch(error){notePhysicsError("bullet-visual",error);deactivateBullet(bullet);}}}
function physicsFrame(now){requestAnimationFrame(physicsFrame);physicsFrames++;const dt=Math.min(.05,Math.max(0,(now-lastFrame)/1000));lastFrame=now;accumulator=Math.min(.06,accumulator+dt);const scene=bridge()?.threeScene;try{if(scene&&scene!==sceneRef)patchScene(scene);}catch(error){notePhysicsError("scene-index",error);}try{patchLegacyWalkReplication();}catch(error){notePhysicsError("legacy-fx-guard",error);}try{for(const record of [...targets.values()])updateTarget(record,now);}catch(error){notePhysicsError("target-sync",error);}try{rebuildTrees();}catch(error){notePhysicsError("tree-sync",error);}try{syncBuildings();}catch(error){notePhysicsError("building-sync",error);}let steps=0;while(accumulator>=FIXED_DT&&steps<MAX_STEPS){try{b3.b3World_Step(world,FIXED_DT,2);processEvents();}catch(error){notePhysicsError("world-step",error);accumulator=0;break;}accumulator-=FIXED_DT;steps++;}if(steps===MAX_STEPS)accumulator=Math.min(accumulator,FIXED_DT);try{updateBulletVisuals(now);}catch(error){notePhysicsError("bullet-sync",error);}const values=[...targets.values()],v=viewport();if(v){v.dataset.box3dCombatWorld="120hz-ccd-v4";v.dataset.box3dCombatTargets=String(values.length);v.dataset.box3dCombatCars=String(values.filter(x=>x.kind==="car"||x.kind==="bus").length);v.dataset.box3dCombatPeople=String(values.filter(x=>x.kind==="person"||x.kind==="vs-player").length);v.dataset.box3dCombatPeers=String(values.filter(x=>x.kind==="vs-drone").length);v.dataset.box3dCombatTrees=String(treeBodies.length);v.dataset.box3dBulletPoolSize=String(BULLET_POOL);v.dataset.box3dCarMotion="kinematic-target-transform-v1";v.dataset.box3dVsCombatVisualScale=String(VS_COMBAT_VISUAL_SCALE);v.dataset.box3dVsHitboxPadding=String(VS_HITBOX_PADDING);v.dataset.box3dPhysicsHeartbeat=String(Math.round(now));v.dataset.box3dPhysicsFrames=String(physicsFrames);}}

export function fireBox3dBullet({origin,direction,speed=360,source="unknown",weapon="pistol",damage=50,replicate=true,id=""}={}){return spawnBullet({id,origin,direction,speed,source,weapon,damage,replicate,remote:false});}
export function installBox3dCombatWorld(){if(installed)return globalThis.__arondightBox3dCombat;installed=true;addEventListener(VS_FX_EVENT,onFx);const scene=bridge()?.threeScene;if(scene)patchScene(scene);globalThis.__arondightBox3dCombat={fire:fireBox3dBullet,registerTarget,get activeBullets(){return activeBullets;},get targetCount(){return targets.size;},get carCount(){return[...targets.values()].filter(x=>x.kind==="car"||x.kind==="bus").length;},get peerCount(){return[...targets.values()].filter(x=>x.kind==="vs-drone").length;},get poolSize(){return BULLET_POOL;},syncBuildings,world,b3};const v=viewport();if(v){v.dataset.box3dCombat="real-bullets+cars+people+trees+peers-v4";v.dataset.box3dBulletPoolSize=String(BULLET_POOL);v.dataset.box3dBulletModel="dynamic-isBullet-ccd-v3";}requestAnimationFrame(physicsFrame);return globalThis.__arondightBox3dCombat;}

installBox3dCombatWorld();
