import * as THREE from "three";
import Box3DFactory from "box3d.js/dist/box3d.inline.mjs";
import {VS_FX_EVENT} from "./lan_vs.mjs";
import {createWorldBuildingCollisionBodies,destroyWorldBuildingCollisionBodies} from "./world_building_collision_physics.mjs";

const FIXED_DT=1/120;
const MAX_STEPS=6;
const BULLET_POOL=64;
const BULLET_TTL_MS=1800;
const BULLET_RADIUS=.018;
const CAT_WORLD=1n;
const CAT_CAR=2n;
const CAT_PERSON=4n;
const CAT_TREE=8n;
const CAT_OTHER=16n;
const CAT_BULLET=32n;
const TARGET_MASK=CAT_BULLET;
const BULLET_MASK=CAT_WORLD|CAT_CAR|CAT_PERSON|CAT_TREE|CAT_OTHER;
const FX_KIND="box3d-bullet-v1";

const b3=await Box3DFactory();
const worldDef=b3.b3DefaultWorldDef();
worldDef.gravity=[0,0,-9.80665];
worldDef.enableContinuous=true;
worldDef.maximumLinearSpeed=520;
const world=b3.b3CreateWorld(worldDef);
try{b3.b3World_SetHitEventThreshold?.(world,.5);}catch{}

const targets=new Map(),shapeTargets=new Map(),bulletShapes=new Map(),seenFx=new Set(),treeBodies=[];
const tmpPos=new THREE.Vector3(),tmpQuat=new THREE.Quaternion(),tmpScale=new THREE.Vector3(),instanceMatrix=new THREE.Matrix4();
let installed=false,sceneRef=null,baseAdd=null,lastFrame=performance.now(),accumulator=0,lastBuildingHash="",buildingState=null,treeSource=null,treeMatrixVersion=-1,treeSyncAt=-Infinity,bulletCursor=0,activeBullets=0;
const eventsBuffer=b3.createEventsBuffer?.()||null,touch=b3.createContactTouchEvent?.()||null,hitEvent=b3.createContactHitEvent?.()||null;

function bridge(){return globalThis.__arondightRealWorld||null;}
function viewport(){return document.getElementById("viewport");}
function idKey(id){if(id==null)return"";if(typeof id==="number"||typeof id==="bigint"||typeof id==="string")return String(id);if(typeof id==="object")return`${id.index1??id.index??""}:${id.world0??id.world??""}:${id.generation??id.generation0??""}`;return String(id);}
function yawQuat(yaw){const h=(Number(yaw)||0)*.5;return{v:{x:0,y:0,z:Math.sin(h)},s:Math.cos(h)};}
function kindOf(node){const raw=String(node?.userData?.worldLifeKind||node?.userData?.worldPopulationKind||"");return raw.startsWith("life-")?raw.slice(5):raw;}
function idOf(node){return String(node?.userData?.worldLifeId||node?.userData?.worldPopulationId||node?.userData?.vsPlayerId||"");}
function rootFor(node){let best=null;for(let n=node;n;n=n.parent){if(idOf(n)&&n.children?.length)best=n;}return best;}
function hitMesh(root){let result=null;root?.traverse?.(n=>{if(!result&&n?.isMesh&&!n.userData?.flightFireIgnore)result=n;});if(!result)root?.traverse?.(n=>{if(!result&&n?.isMesh)result=n;});return result||root;}
function specFor(kind){if(kind==="car")return{cat:CAT_CAR,shape:"box",half:[1.82,.86,.72],z:.72};if(kind==="bus")return{cat:CAT_CAR,shape:"box",half:[4.05,1.20,1.18],z:1.18};if(kind==="person"||kind==="vs-player")return{cat:CAT_PERSON,shape:"capsule",radius:.25,halfHeight:.58,z:.88};if(kind==="bird")return{cat:CAT_OTHER,shape:"sphere",radius:.28,z:.25};return{cat:CAT_OTHER,shape:"box",half:[.45,.45,.45],z:.45};}
function destroyTarget(record){if(!record)return;shapeTargets.delete(idKey(record.shape));targets.delete(record.id);try{if(record.body&&b3.b3Body_IsValid(record.body))b3.b3DestroyBody(record.body);}catch{}}
function createTarget(root){const id=idOf(root);if(!id||targets.has(id))return targets.get(id)||null;const kind=kindOf(root)||"object",spec=specFor(kind);root.updateWorldMatrix?.(true,false);root.getWorldPosition(tmpPos);const def=b3.b3DefaultBodyDef();def.type=b3.b3BodyType.b3_kinematicBody;def.position=[tmpPos.x,tmpPos.y,tmpPos.z+spec.z];def.rotation=yawQuat(root.rotation?.z||0);def.enableSleep=false;def.enableContactRecycling=false;const body=b3.b3CreateBody(world,def),sd=b3.b3DefaultShapeDef();sd.filter={categoryBits:spec.cat,maskBits:TARGET_MASK,groupIndex:0};sd.enableContactEvents=true;sd.enableHitEvents=true;sd.baseMaterial.friction=.55;sd.baseMaterial.restitution=.06;let shape;if(spec.shape==="capsule")shape=b3.b3CreateCapsuleShape(body,sd,{center1:[0,0,-spec.halfHeight],center2:[0,0,spec.halfHeight],radius:spec.radius});else if(spec.shape==="sphere")shape=b3.b3CreateSphereShape(body,sd,{center:[0,0,0],radius:spec.radius});else shape=b3.b3CreateBoxShape(body,sd,...spec.half);const record={id,kind,root,body,shape,spec,mesh:hitMesh(root),last:new THREE.Vector3().copy(tmpPos),lastAt:performance.now()};targets.set(id,record);shapeTargets.set(idKey(shape),record);root.userData.box3dCombatBody=true;root.userData.box3dCombatKind=kind;return record;}
function trackedRoot(node){const kind=kindOf(node);return Boolean(node?.children?.length&&idOf(node)&&["car","bus","person","bird","vs-player"].includes(kind));}
function indexNode(node){if(!node)return;if(trackedRoot(node))createTarget(node);if(node.name==="WORLD_LIVELINESS_TREES"){const source=node.children?.find?.(x=>x?.isInstancedMesh);if(source)treeSource=source;}}
function indexSubtree(root){root?.traverse?.(indexNode);}
function patchScene(scene){if(!scene||scene===sceneRef)return;sceneRef=scene;for(const record of [...targets.values()])destroyTarget(record);treeSource=null;indexSubtree(scene);if(!scene.__box3dCombatAddPatched){baseAdd=scene.add;scene.add=function(...objects){const out=baseAdd.apply(this,objects);for(const object of objects)indexSubtree(object);return out;};scene.__box3dCombatAddPatched=true;}const v=viewport();if(v)v.dataset.box3dCombatIndex="scene-add+boot-v1";}
function updateTarget(record,now){const root=record.root;if(!root?.parent){destroyTarget(record);return;}root.updateWorldMatrix?.(true,false);root.getWorldPosition(tmpPos);root.getWorldQuaternion(tmpQuat);const dt=Math.max(.001,(now-record.lastAt)/1000),vx=(tmpPos.x-record.last.x)/dt,vy=(tmpPos.y-record.last.y)/dt,vz=(tmpPos.z-record.last.z)/dt;const p=[tmpPos.x,tmpPos.y,tmpPos.z+record.spec.z],q={v:{x:tmpQuat.x,y:tmpQuat.y,z:tmpQuat.z},s:tmpQuat.w};try{b3.b3Body_SetTransform(record.body,p,q);b3.b3Body_SetLinearVelocity(record.body,[vx,vy,vz]);}catch{}record.last.copy(tmpPos);record.lastAt=now;}

function clearTrees(){for(const item of treeBodies){shapeTargets.delete(idKey(item.shape));try{if(item.body&&b3.b3Body_IsValid(item.body))b3.b3DestroyBody(item.body);}catch{}}treeBodies.length=0;}
function rebuildTrees(now){if(!treeSource?.parent)return;const version=Number(treeSource.instanceMatrix?.version)||0;if(version===treeMatrixVersion&&now-treeSyncAt<1500)return;treeMatrixVersion=version;treeSyncAt=now;clearTrees();treeSource.updateWorldMatrix?.(true,false);for(let i=0;i<treeSource.count;i++){treeSource.getMatrixAt(i,instanceMatrix);instanceMatrix.premultiply(treeSource.matrixWorld);instanceMatrix.decompose(tmpPos,tmpQuat,tmpScale);const def=b3.b3DefaultBodyDef();def.type=b3.b3BodyType.b3_staticBody;def.position=[tmpPos.x,tmpPos.y,tmpPos.z];def.rotation={v:{x:tmpQuat.x,y:tmpQuat.y,z:tmpQuat.z},s:tmpQuat.w};const body=b3.b3CreateBody(world,def),sd=b3.b3DefaultShapeDef();sd.filter={categoryBits:CAT_TREE,maskBits:TARGET_MASK,groupIndex:0};sd.enableContactEvents=true;sd.enableHitEvents=true;const shape=b3.b3CreateBoxShape(body,sd,Math.max(.12,.16*tmpScale.x),Math.max(.12,.16*tmpScale.y),Math.max(.85,1.15*tmpScale.z));const rec={id:`tree-${i}`,kind:"tree",root:treeSource,body,shape,spec:{z:0},mesh:treeSource};treeBodies.push(rec);shapeTargets.set(idKey(shape),rec);}}
function syncBuildings(){const snapshot=bridge()?.buildingCollisionSnapshot,hash=String(snapshot?.hash||"");if(hash===lastBuildingHash)return;lastBuildingHash=hash;destroyWorldBuildingCollisionBodies(b3,buildingState);buildingState=createWorldBuildingCollisionBodies(b3,world,snapshot,{categoryBits:CAT_WORLD,maskBits:CAT_BULLET,rangefinderCategoryBits:0n,projectileCategoryBits:CAT_BULLET,launchExclusionPoint:[Infinity,Infinity]});const v=viewport();if(v){v.dataset.box3dCombatBuildings=String(buildingState?.shapeCount||0);v.dataset.box3dCombatBuildingHash=hash;}}

const groundDef=b3.b3DefaultBodyDef();groundDef.type=b3.b3BodyType.b3_staticBody;groundDef.position=[0,0,-.08];const groundBody=b3.b3CreateBody(world,groundDef),groundShapeDef=b3.b3DefaultShapeDef();groundShapeDef.filter={categoryBits:CAT_WORLD,maskBits:CAT_BULLET,groupIndex:0};groundShapeDef.enableContactEvents=true;groundShapeDef.enableHitEvents=true;b3.b3CreateBoxShape(groundBody,groundShapeDef,10000,10000,.08);

const bulletPool=[];
function createBullet(index){const def=b3.b3DefaultBodyDef();def.type=b3.b3BodyType.b3_dynamicBody;def.position=[0,0,-999];def.gravityScale=1;def.enableSleep=false;def.isBullet=true;def.linearDamping=0;def.angularDamping=0;const body=b3.b3CreateBody(world,def),sd=b3.b3DefaultShapeDef();sd.density=26;sd.filter={categoryBits:CAT_BULLET,maskBits:BULLET_MASK,groupIndex:0};sd.enableContactEvents=true;sd.enableHitEvents=true;sd.baseMaterial.friction=.04;sd.baseMaterial.restitution=.02;const shape=b3.b3CreateSphereShape(body,sd,{center:[0,0,0],radius:BULLET_RADIUS});b3.b3Body_Disable?.(body);const mesh=new THREE.Mesh(new THREE.SphereGeometry(BULLET_RADIUS*1.7,5,4),new THREE.MeshBasicMaterial({color:0xffd78c}));mesh.visible=false;mesh.userData.flightFireIgnore=true;mesh.userData.box3dBullet=true;const bullet={index,body,shape,mesh,active:false,id:"",born:0,source:"",weapon:"",damage:0,remote:false};bulletPool.push(bullet);bulletShapes.set(idKey(shape),bullet);return bullet;}
for(let i=0;i<BULLET_POOL;i++)createBullet(i);
function attachBulletMeshes(){const scene=bridge()?.threeScene;if(!scene)return;for(const bullet of bulletPool)if(!bullet.mesh.parent)scene.add(bullet.mesh);}
function deactivateBullet(bullet){if(!bullet?.active)return;bullet.active=false;bullet.mesh.visible=false;activeBullets=Math.max(0,activeBullets-1);try{b3.b3Body_Disable?.(bullet.body);}catch{}const v=viewport();if(v)v.dataset.box3dActiveBullets=String(activeBullets);}
function bulletPosition(bullet,out=new THREE.Vector3()){const p=b3.b3Body_GetPosition(bullet.body);return out.set(Number(p?.x??p?.[0])||0,Number(p?.y??p?.[1])||0,Number(p?.z??p?.[2])||0);}
function spawnBullet({id="",origin,direction,speed=360,source="unknown",weapon="pistol",damage=50,remote=false,replicate=false}={}){if(!origin||!direction)return null;const o=Array.isArray(origin)?origin:[origin.x,origin.y,origin.z],d=Array.isArray(direction)?direction:[direction.x,direction.y,direction.z],len=Math.hypot(Number(d[0])||0,Number(d[1])||0,Number(d[2])||0)||1,bullet=bulletPool[bulletCursor++%bulletPool.length];if(bullet.active)deactivateBullet(bullet);bullet.id=String(id||`b3-${Date.now().toString(36)}-${bulletCursor.toString(36)}`);bullet.born=performance.now();bullet.source=source;bullet.weapon=weapon;bullet.damage=Number(damage)||0;bullet.remote=Boolean(remote);try{b3.b3Body_Enable?.(bullet.body);b3.b3Body_SetTransform(bullet.body,[Number(o[0])||0,Number(o[1])||0,Number(o[2])||0],{v:{x:0,y:0,z:0},s:1});b3.b3Body_SetLinearVelocity(bullet.body,[Number(d[0])/(len)*speed,Number(d[1])/(len)*speed,Number(d[2])/(len)*speed]);b3.b3Body_SetAngularVelocity?.(bullet.body,[0,0,0]);b3.b3Body_SetBullet?.(bullet.body,true);}catch{}bullet.active=true;bullet.mesh.visible=true;activeBullets++;if(replicate)replicateBullet(bullet,o,[Number(d[0])/len,Number(d[1])/len,Number(d[2])/len],speed);const v=viewport();if(v){v.dataset.box3dActiveBullets=String(activeBullets);v.dataset.box3dBulletSpawns=String((Number(v.dataset.box3dBulletSpawns)||0)+1);v.dataset.box3dBulletModel="dynamic-isBullet-ccd-v1";}return bullet;}
function replicateBullet(bullet,origin,dir,speed){const session=bridge()?.vsSession;if(!session?.sendFx)return;try{session.sendFx({type:"physics-bullet",kind:FX_KIND,id:bullet.id,from:[...origin],dir:[...dir],speed:Number(speed)||360,weapon:bullet.weapon,damage:bullet.damage,t:Date.now()});const v=viewport();if(v)v.dataset.box3dReplicatedBullets=String((Number(v.dataset.box3dReplicatedBullets)||0)+1);}catch{}}
function rememberFx(id){const key=String(id||"");if(!key||seenFx.has(key))return false;seenFx.add(key);if(seenFx.size>512){const first=seenFx.values().next().value;seenFx.delete(first);}return true;}
function onFx(event){const packet=event?.detail?.packet||event?.detail;if(packet?.type!=="physics-bullet"||packet?.kind!==FX_KIND||!rememberFx(packet.id))return;spawnBullet({id:packet.id,origin:packet.from,direction:packet.dir,speed:packet.speed,weapon:packet.weapon,damage:packet.damage,source:"remote",remote:true,replicate:false});}

function impactPointFor(bullet,point){if(point&&Number.isFinite(Number(point.x)))return new THREE.Vector3(Number(point.x),Number(point.y),Number(point.z));return bulletPosition(bullet,new THREE.Vector3());}
function processContact(shapeA,shapeB,point=null){const a=bulletShapes.get(idKey(shapeA)),b=bulletShapes.get(idKey(shapeB)),bullet=a||b;if(!bullet?.active)return false;const other=a?shapeB:shapeA,target=shapeTargets.get(idKey(other))||null,p=impactPointFor(bullet,point);let handled=false;if(target){const hit={object:target.mesh,point:p,distance:0};const br=bridge();if(target.kind==="vs-player"&&typeof br?.registerVsHit==="function")handled=Boolean(br.registerVsHit(hit));if(!handled&&typeof br?.registerWorldPopulationHit==="function")handled=Boolean(br.registerWorldPopulationHit(hit));if(!handled)window.dispatchEvent(new CustomEvent("arondight:target-damage",{detail:{kind:target.kind,id:target.id,damage:bullet.damage,physics:true}}));}window.dispatchEvent(new CustomEvent("arondight:box3d-impact",{detail:{point:{x:p.x,y:p.y,z:p.z},normal:{x:0,y:0,z:1},targetId:target?.id||"",targetKind:target?.kind||"world",handled,source:bullet.source,weapon:bullet.weapon,bulletId:bullet.id}}));const v=viewport();if(v){v.dataset.box3dBulletImpacts=String((Number(v.dataset.box3dBulletImpacts)||0)+1);v.dataset.box3dLastImpactKind=target?.kind||"world";}deactivateBullet(bullet);return true;}
function processEvents(){if(!eventsBuffer||!b3.getEvents)return;try{b3.getEvents(eventsBuffer,world);if(hitEvent&&b3.getNumContactHitEvents){for(let i=0,n=b3.getNumContactHitEvents(eventsBuffer);i<n;i++){b3.getContactHitEventAt(hitEvent,eventsBuffer,i);processContact(hitEvent.shapeIdA,hitEvent.shapeIdB,hitEvent.point);}}if(touch&&b3.getNumContactBeginEvents){for(let i=0,n=b3.getNumContactBeginEvents(eventsBuffer);i<n;i++){b3.getContactBeginEventAt(touch,eventsBuffer,i);processContact(touch.shapeIdA,touch.shapeIdB,null);}}}catch{}}
function updateBulletVisuals(now){attachBulletMeshes();for(const bullet of bulletPool){if(!bullet.active)continue;if(now-bullet.born>BULLET_TTL_MS){deactivateBullet(bullet);continue;}bulletPosition(bullet,bullet.mesh.position);}}
function physicsFrame(now){const dt=Math.min(.05,Math.max(0,(now-lastFrame)/1000));lastFrame=now;accumulator=Math.min(.06,accumulator+dt);const scene=bridge()?.threeScene;if(scene&&scene!==sceneRef)patchScene(scene);for(const record of [...targets.values()])updateTarget(record,now);rebuildTrees(now);syncBuildings();let steps=0;while(accumulator>=FIXED_DT&&steps<MAX_STEPS){b3.b3World_Step(world,FIXED_DT,2);processEvents();accumulator-=FIXED_DT;steps++;}if(steps===MAX_STEPS)accumulator=Math.min(accumulator,FIXED_DT);updateBulletVisuals(now);const v=viewport();if(v){v.dataset.box3dCombatWorld="120hz-ccd-v1";v.dataset.box3dCombatTargets=String(targets.size);v.dataset.box3dCombatCars=String([...targets.values()].filter(x=>x.kind==="car"||x.kind==="bus").length);v.dataset.box3dCombatPeople=String([...targets.values()].filter(x=>x.kind==="person"||x.kind==="vs-player").length);v.dataset.box3dCombatTrees=String(treeBodies.length);v.dataset.box3dBulletPoolSize=String(BULLET_POOL);}requestAnimationFrame(physicsFrame);}

export function fireBox3dBullet({origin,direction,speed=360,source="unknown",weapon="pistol",damage=50,replicate=true,id=""}={}){return spawnBullet({id,origin,direction,speed,source,weapon,damage,replicate,remote:false});}
export function installBox3dCombatWorld(){if(installed)return globalThis.__arondightBox3dCombat;installed=true;addEventListener(VS_FX_EVENT,onFx);const scene=bridge()?.threeScene;if(scene)patchScene(scene);globalThis.__arondightBox3dCombat={fire:fireBox3dBullet,get activeBullets(){return activeBullets;},get targetCount(){return targets.size;},get carCount(){return[...targets.values()].filter(x=>x.kind==="car"||x.kind==="bus").length;},get poolSize(){return BULLET_POOL;},syncBuildings,world,b3};const v=viewport();if(v){v.dataset.box3dCombat="real-bullets+cars+people+trees-v1";v.dataset.box3dBulletPoolSize=String(BULLET_POOL);}requestAnimationFrame(physicsFrame);return globalThis.__arondightBox3dCombat;}

installBox3dCombatWorld();
