import * as THREE from "three";
import {CameraBox3dSpring} from "./camera_box3d_spring.mjs";

let installed=false,wrapped=false,baseProvider=null,springEngine=null,lastSpringResult=null;
const springs=new Map(),anchor=new THREE.Vector3();
function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function physicsRuntime(){return globalThis.__arondightWorldRigidBodies||null;}
function cameraMode(){const drive=globalThis.__arondightVehicleDrive;if(drive?.active)return"vehicle";const walk=globalThis.__arondightWalkMode;if(walk?.mode==="foot")return"walk";return String(viewport()?.dataset?.cameraMode||"follow");}
function resolveAnchor(){const drive=globalThis.__arondightVehicleDrive;if(drive?.active&&drive.cameraAnchor){const a=drive.cameraAnchor;return anchor.set(Number(a.x)||0,Number(a.y)||0,Math.max(.45,Number(a.z)||0));}const walk=globalThis.__arondightWalkMode,p=walk?.position;if(walk?.mode==="foot"&&p)return anchor.set(Number(p.x)||0,Number(p.y)||0,Math.max(.34,(Number(p.z)||1.68)-.38));const b=bridge(),air=b?.threeScene?(b.airframeFor?.(b.threeScene)||b.airframe):b?.airframe;if(air?.position)return anchor.set(Number(air.position.x)||0,Number(air.position.y)||0,Math.max(.08,Number(air.position.z)||0));return null;}
function destroySprings(){for(const spring of springs.values())spring.destroy();springs.clear();lastSpringResult=null;}
function ensureSpring(mode){const engine=physicsRuntime()?.engine;if(!engine?.world||!engine?.b3)return null;if(engine!==springEngine){destroySprings();springEngine=engine;}const key=String(mode||"camera");let spring=springs.get(key);if(!spring){spring=new CameraBox3dSpring({b3:engine.b3,world:engine.world});springs.set(key,spring);}return spring;}
function physicalResolver(anchorValue,desiredValue){const mode=cameraMode(),spring=ensureSpring(mode),desired=Array.isArray(desiredValue)?desiredValue.map(Number):[],source=Array.isArray(anchorValue)?anchorValue.map(Number):[];if(!spring||desired.length!==3||!desired.every(Number.isFinite))return{position:desired.length===3?desired:[0,0,0],collided:false,compressionM:0,hitDistanceM:0,physics:"waiting-box3d"};const result=spring.update({anchor:source,desired,now:performance.now(),mode});lastSpringResult=result;const hitDistanceM=source.length===3&&source.every(Number.isFinite)?Math.hypot(result.position[0]-source[0],result.position[1]-source[1],result.position[2]-source[2]):0,v=viewport();if(v){v.dataset.playerCameraSpringBody="dynamic-bullet-box-v1";v.dataset.playerCameraSpringWorld="shared-world-rigid-body-v1";v.dataset.playerCameraSpringMode=mode;v.dataset.playerCameraSpringCompressionM=Number(result.compressionM||0).toFixed(3);v.dataset.playerCameraSpringPhysics=result.physics;v.dataset.playerCameraSpringBodies=String(springs.size);v.dataset.playerCameraSpringResets=String(result.resets||0);}return{...result,hitDistanceM};}
function ensureResolver(){const b=bridge();if(!b||typeof b.attachCameraCollisionResolver!=="function")return false;if(b.cameraCollisionResolver!==physicalResolver)b.attachCameraCollisionResolver(physicalResolver);return true;}
function constrain(args,result){const b=bridge(),camera=args?.camera,a=resolveAnchor();if(!camera?.position||!a)return result;const physicsReady=Boolean(ensureResolver()&&physicsRuntime()?.engine),collided=typeof b?.constrainCameraToPhysics==="function"?Boolean(b.constrainCameraToPhysics(a,camera)):false;const floor=.12;if(!physicsReady&&camera.position.z<floor)camera.position.z=floor;camera.near=Math.max(.045,Math.min(.08,Number(camera.near)||.06));camera.updateProjectionMatrix?.();camera.updateMatrixWorld?.(true);const view=viewport();if(view){view.dataset.playerCameraCollisionGuard="box3d-dynamic-spring-attachment-v1";view.dataset.playerCameraCollision=collided?"blocked":"clear";view.dataset.playerCameraFloorM=physicsReady?"physical":floor.toFixed(2);view.dataset.playerCameraSpringCompressionM=Number(lastSpringResult?.compressionM||0).toFixed(3);}return result;}
function tryWrap(){if(wrapped)return true;const b=bridge(),current=b?.presentationCameraProvider;if(!b||typeof b.attachPresentationCameraProvider!=="function"||!current||current.__collisionGuard)return false;baseProvider=current;const provider={__collisionGuard:true,__box3dCameraSpringGuard:true,isActive:()=>Boolean(baseProvider?.isActive?.()),apply:args=>constrain(args,baseProvider?.apply?.(args))};b.attachPresentationCameraProvider(provider);wrapped=true;return true;}
function frame(){ensureResolver();tryWrap();requestAnimationFrame(frame);}
export function installCameraCollisionGuard(){if(installed)return;installed=true;const view=viewport();if(view){view.dataset.playerCameraCollisionGuard="waiting-box3d-spring";view.dataset.playerCameraSpringBody="dynamic-bullet-box-v1";}requestAnimationFrame(frame);}
installCameraCollisionGuard();
