import * as THREE from "three";

let installed=false,wrapped=false,baseProvider=null,guardProvider=null,lastTelemetry=-Infinity,maintenanceTimer=0;
const anchor=new THREE.Vector3();
function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function resolveAnchor(){const drive=globalThis.__arondightVehicleDrive;if(drive?.active&&drive.cameraAnchor){const a=drive.cameraAnchor;return anchor.set(Number(a.x)||0,Number(a.y)||0,Math.max(.45,Number(a.z)||0));}const walk=globalThis.__arondightWalkMode,p=walk?.position;if(walk?.mode==="foot"&&p)return anchor.set(Number(p.x)||0,Number(p.y)||0,Math.max(.34,(Number(p.z)||1.68)-.38));return null;}
function constrain(args,result){const b=bridge(),camera=args?.camera,a=resolveAnchor();if(!camera?.position||!a)return result;let collided=false;if(typeof b?.constrainCameraToPhysics==="function")collided=Boolean(b.constrainCameraToPhysics(a,camera));const floor=.12;if(camera.position.z<floor){camera.position.z=floor;collided=true;}camera.near=Math.max(.045,Math.min(.08,Number(camera.near)||.06));camera.updateProjectionMatrix?.();camera.updateMatrixWorld?.(true);const now=performance.now();if(now-lastTelemetry>=250){lastTelemetry=now;const view=viewport();if(view){view.dataset.playerCameraCollisionGuard="box3d-ray+floor-clamp-v3";view.dataset.playerCameraCollision=collided?"blocked":"clear";view.dataset.playerCameraFloorM=floor.toFixed(2);view.dataset.playerCameraCollisionTelemetry="250ms";}}return result;}
function tryWrap(){const b=bridge(),current=b?.presentationCameraProvider;if(!b||typeof b.attachPresentationCameraProvider!=="function"||!current)return false;if(current===guardProvider||current.__collisionGuard){guardProvider=current;wrapped=true;return true;}baseProvider=current;guardProvider={__collisionGuard:true,isActive:()=>Boolean(baseProvider?.isActive?.()),apply:args=>constrain(args,baseProvider?.apply?.(args))};b.attachPresentationCameraProvider(guardProvider);wrapped=true;return true;}
function maintenance(){tryWrap();clearTimeout(maintenanceTimer);maintenanceTimer=setTimeout(maintenance,500);}
export function installCameraCollisionGuard(){if(installed)return;installed=true;const view=viewport();if(view){view.dataset.playerCameraCollisionGuard="waiting-provider";view.dataset.playerCameraCollisionMaintenance="500ms-no-raf";}tryWrap();maintenanceTimer=setTimeout(maintenance,500);}
installCameraCollisionGuard();
