const DEFAULT_ICE_SERVERS=[
  {urls:["stun:stun.cloudflare.com:3478","stun:stun.cloudflare.com:53"]},
  {urls:"stun:stun.l.google.com:19302"}
];
const POSE_BUFFER_LIMIT_BYTES=65536;
const DISCONNECT_GRACE_MS=4500;
const RESTART_TIMEOUT_MS=10000;
const READY_RETRY_MS=350;
const SIGNAL_RETRY_MS=1200;
const RESPAWN_AUTHORITY_MS=0;
const PING_TIMEOUT_MS=3000;
const MAX_SEEN_COMBAT=256;

function errorText(error){return String(error?.message||error||"unknown error");}
function candidateProtocol(candidate){const direct=String(candidate?.protocol||"").toLowerCase();if(direct)return direct;const parts=String(candidate?.candidate||candidate||"").trim().split(/\s+/);return String(parts[2]||"").toLowerCase();}
function channelOpen(channel){return Boolean(channel&&channel.readyState==="open");}
function safeParse(value){try{return JSON.parse(typeof value==="string"?value:new TextDecoder().decode(value instanceof ArrayBuffer?new Uint8Array(value):value));}catch{return null;}}
function packetId(){try{return globalThis.crypto?.randomUUID?.().replaceAll("-","")||`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;}catch{return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;}}
function validHit(packet){return Boolean(packet&&typeof packet.id==="string"&&packet.id.length>0&&packet.id.length<=64&&Number.isFinite(packet.damage)&&packet.damage>0&&packet.damage<=100);}
function validState(packet){return Boolean(packet&&typeof packet.id==="string"&&packet.id.length>0&&packet.id.length<=64&&Number.isFinite(packet.hp)&&packet.hp>=0&&packet.hp<=100&&typeof packet.killed==="boolean");}
function validRespawn(packet){return Boolean(packet&&Number.isFinite(packet.hp)&&packet.hp>=0&&packet.hp<=100);}
function rememberBounded(set,value){if(!value||set.has(value))return false;set.add(value);while(set.size>MAX_SEEN_COMBAT)set.delete(set.values().next().value);return true;}
function cloneSignal(signal){return signal&&typeof signal==="object"?JSON.parse(JSON.stringify(signal)):signal;}

export class DirectUdpPeer{
  constructor(options={}){
    this.localId=String(options.localId||"");this.peerId=String(options.peerId||"");if(!this.localId||!this.peerId||this.localId===this.peerId)throw Error("Direct UDP peer requires two distinct peer ids");
    this.isHost=this.localId<this.peerId;this.sendSignal=typeof options.sendSignal==="function"?options.sendSignal:()=>Promise.reject(Error("Direct UDP signaling unavailable"));this.onReady=options.onReady;this.onLeave=options.onLeave;this.onAction=options.onAction;this.onDiagnostic=options.onDiagnostic;
    this.RTC=options.RTCPeerConnectionCtor||globalThis.RTCPeerConnection;if(typeof this.RTC!=="function")throw Error("Direct UDP WebRTC unavailable");this.iceServers=Array.isArray(options.iceServers)?options.iceServers:DEFAULT_ICE_SERVERS;this.now=typeof options.now==="function"?options.now:()=>Date.now();
    this.pc=null;this.poseChannel=null;this.controlChannel=null;this.started=false;this.closed=false;this.ready=false;this.localChannelsReady=false;this.remoteReady=false;this.remoteAcked=false;this.offerStarted=false;this.restartInFlight=false;this.lastRemoteDescriptionKey="";
    this.pendingCandidates=[];this.localCandidates=[];this.pendingControl=[];this.pendingPose=null;this.pendingPings=new Map();this.readyTimer=0;this.offerTimer=0;this.disconnectTimer=0;this.restartTimer=0;
    this.peerHealth=100;this.peerKilledAt=0;this.authoritativeHits=new Map();this.seenHitRequests=new Set();
  }
  diag(stage,detail={}){const payload={stage,transport:"DirectP2PUDP",localId:this.localId,peerId:this.peerId,role:this.isHost?"host":"client",...detail};try{this.onDiagnostic?.(payload);}catch{}return payload;}
  async start(){if(this.started||this.closed)return;this.started=true;const pc=new this.RTC({iceServers:this.iceServers,iceTransportPolicy:"all",bundlePolicy:"max-bundle",rtcpMuxPolicy:"require",iceCandidatePoolSize:this.iceServers.length?2:0});this.pc=pc;pc.__a45HostAuthority=this.isHost;pc.__a45Transport="direct-p2p-udp";
    const pose=pc.createDataChannel("pose",{negotiated:true,id:0,ordered:false,maxRetransmits:0}),control=pc.createDataChannel("control",{negotiated:true,id:1,ordered:true});this.poseChannel=pose;this.controlChannel=control;pose.binaryType="arraybuffer";control.binaryType="arraybuffer";pose.bufferedAmountLowThreshold=0;control.bufferedAmountLowThreshold=0;
    pose.onopen=()=>this._channelsChanged();control.onopen=()=>this._channelsChanged();pose.onclose=()=>this._channelClosed("pose");control.onclose=()=>this._channelClosed("control");pose.onerror=()=>this.diag("pose-channel-error");control.onerror=()=>this.diag("control-channel-error");pose.onmessage=event=>this._receivePose(event.data);control.onmessage=event=>this._receiveControl(event.data);
    pc.onicecandidate=event=>this._localCandidate(event.candidate);pc.onconnectionstatechange=()=>this._connectionChanged();pc.oniceconnectionstatechange=()=>this._connectionChanged();
    this.diag("peer-engine-start",{pose:{ordered:pose.ordered,maxRetransmits:pose.maxRetransmits},control:{ordered:control.ordered,maxRetransmits:control.maxRetransmits}});if(this.isHost)await this._startOffer(false);
  }
  _localCandidate(candidate){if(!candidate)return;const protocol=candidateProtocol(candidate);if(protocol!=="udp"){this.diag("ice-candidate-rejected",{protocol:protocol||"unknown"});return;}const json=typeof candidate.toJSON==="function"?candidate.toJSON():{candidate:candidate.candidate,sdpMid:candidate.sdpMid,sdpMLineIndex:candidate.sdpMLineIndex,usernameFragment:candidate.usernameFragment};this.localCandidates.push(json);if(this.localCandidates.length>32)this.localCandidates.shift();Promise.resolve(this.sendSignal({kind:"candidate",candidate:json})).catch(error=>this.diag("signal-send-error",{kind:"candidate",error:errorText(error)}));}
  async _startOffer(iceRestart=false){if(this.closed||!this.pc||!this.isHost)return;if(!iceRestart)this.offerStarted=true;const offer=await this.pc.createOffer(iceRestart?{iceRestart:true}:{});await this.pc.setLocalDescription(offer);await this._sendDescription("offer",iceRestart);if(!this.offerTimer)this.offerTimer=setInterval(()=>{if(this.closed||(this.ready&&!this.restartInFlight)){clearInterval(this.offerTimer);this.offerTimer=0;return;}this._resendLocalSignal().catch(()=>{});},SIGNAL_RETRY_MS);this.diag(iceRestart?"ice-restart-offer":"direct-udp-offer");}
  async _sendDescription(expectedType,iceRestart=false){const description=this.pc?.localDescription;if(!description||description.type!==expectedType)return;await this.sendSignal({kind:"description",description:{type:description.type,sdp:description.sdp},iceRestart:Boolean(iceRestart)});}
  async _resendLocalSignal(){if(this.closed||!this.pc)return;const description=this.pc.localDescription;if(description?.type)await this.sendSignal({kind:"description",description:{type:description.type,sdp:description.sdp},retry:true,iceRestart:this.restartInFlight});for(const candidate of this.localCandidates)await this.sendSignal({kind:"candidate",candidate:cloneSignal(candidate),retry:true});}
  async handleSignal(signal){if(this.closed)return;const packet=signal&&typeof signal==="object"?signal:null;if(!packet||typeof packet.kind!=="string")return;if(!this.started)await this.start();
    if(packet.kind==="restart-needed"){if(this.isHost)await this.restartIce("peer-request");return;}
    if(packet.kind==="description"){const description=packet.description;if(!description||typeof description.type!=="string"||typeof description.sdp!=="string")return;const descriptionKey=`${description.type}\n${description.sdp}`;if(descriptionKey===this.lastRemoteDescriptionKey)return;try{await this.pc.setRemoteDescription(description);this.lastRemoteDescriptionKey=descriptionKey;await this._flushCandidates();if(description.type==="offer"){const answer=await this.pc.createAnswer();await this.pc.setLocalDescription(answer);await this._sendDescription("answer",Boolean(packet.iceRestart));this.diag(packet.iceRestart?"ice-restart-answer":"direct-udp-answer");}else if(description.type==="answer"&&this.isHost){this.restartInFlight=false;if(String(this.pc.connectionState||this.pc.iceConnectionState||"")==="connected"){clearTimeout(this.restartTimer);this.restartTimer=0;}}}catch(error){this.diag("description-error",{type:description.type,error:errorText(error)});throw error;}return;}
    if(packet.kind==="candidate"){const candidate=packet.candidate;if(!candidate||candidateProtocol(candidate)!=="udp")return;if(this.pc.remoteDescription)try{await this.pc.addIceCandidate(candidate);}catch(error){this.diag("ice-candidate-add-error",{error:errorText(error)});}else this.pendingCandidates.push(candidate);}
  }
  async _flushCandidates(){if(!this.pc?.remoteDescription)return;const queue=this.pendingCandidates.splice(0);for(const candidate of queue)try{await this.pc.addIceCandidate(candidate);}catch(error){this.diag("ice-candidate-add-error",{error:errorText(error)});}}
  _channelsChanged(){if(this.closed)return;const both=channelOpen(this.poseChannel)&&channelOpen(this.controlChannel);if(!both)return;if(!this.localChannelsReady){this.localChannelsReady=true;this.diag("channels-local-ready");}this._sendReady();if(!this.readyTimer)this.readyTimer=setInterval(()=>{if(this.closed||this.ready){clearInterval(this.readyTimer);this.readyTimer=0;return;}this._sendReady();},READY_RETRY_MS);this._maybeReady();}
  _sendReady(){if(!this.localChannelsReady||!channelOpen(this.controlChannel))return;this._sendControlRaw({a:"__ready",n:this.localId}).catch(()=>{});}
  _maybeReady(){if(this.closed||this.ready||!this.localChannelsReady||!this.remoteReady||!this.remoteAcked)return;this.ready=true;clearInterval(this.readyTimer);clearInterval(this.offerTimer);this.readyTimer=0;this.offerTimer=0;clearTimeout(this.restartTimer);this.restartTimer=0;this.restartInFlight=false;this.diag("direct-udp-ready",{pose:{ordered:this.poseChannel.ordered,maxRetransmits:this.poseChannel.maxRetransmits},control:{ordered:this.controlChannel.ordered,maxRetransmits:this.controlChannel.maxRetransmits}});try{this.onReady?.(this.peerId,{isHost:this.isHost,pc:this.pc});}catch(error){this.diag("ready-handler-error",{error:errorText(error)});}const pending=this.pendingControl.splice(0),pose=this.pendingPose;this.pendingPose=null;for(const packet of pending)this._deliverControlPacket(packet);if(pose)this._deliverAction("pose",pose);}
  _receivePose(data){const payload=safeParse(data);if(!payload)return;if(!this.ready){this.pendingPose=payload;return;}this._deliverAction("pose",payload);}
  _receiveControl(data){const packet=safeParse(data);if(!packet||typeof packet.a!=="string")return;if(packet.a==="__ready"){this.remoteReady=true;this._sendControlRaw({a:"__ready-ack",n:packet.n}).catch(()=>{});this._maybeReady();return;}if(packet.a==="__ready-ack"){this.remoteAcked=true;this._maybeReady();return;}if(packet.a==="__ping"){this._sendControlRaw({a:"__pong",n:packet.n}).catch(()=>{});return;}if(packet.a==="__pong"){const pending=this.pendingPings.get(packet.n);if(pending){this.pendingPings.delete(packet.n);pending.resolve(performance.now()-pending.started);}return;}if(!this.ready){this.pendingControl.push(packet);if(this.pendingControl.length>64)this.pendingControl.shift();return;}this._deliverControlPacket(packet);}
  _deliverControlPacket(packet){if(packet.a==="combat"){this._receiveCombatWire(packet.d);return;}this._deliverAction(packet.a,packet.d);}
  _deliverAction(action,data){try{this.onAction?.(String(action||""),data,{peerId:this.peerId,isHost:this.isHost});}catch(error){this.diag("action-handler-error",{action,error:errorText(error)});}}
  _sendControlRaw(packet){if(!channelOpen(this.controlChannel))return Promise.reject(Error("Direct UDP reliable channel unavailable"));try{this.controlChannel.send(JSON.stringify(packet));return Promise.resolve();}catch(error){return Promise.reject(error);}}
  _sendPose(data){if(!channelOpen(this.poseChannel))return Promise.reject(Error("Direct UDP pose channel unavailable"));if(this.poseChannel.bufferedAmount>POSE_BUFFER_LIMIT_BYTES){this.diag("pose-drop-backpressure",{bufferedAmount:this.poseChannel.bufferedAmount});return Promise.resolve();}try{this.poseChannel.send(JSON.stringify(data));return Promise.resolve();}catch(error){return Promise.reject(error);}}
  sendAction(action,data){if(!this.ready)return Promise.reject(Error("Direct UDP peer unavailable"));if(action==="pose")return this._sendPose(data);if(action==="combat")return this._sendCombat(data);return this._sendControlRaw({a:String(action||""),d:data});}
  _sendCombat(packet){if(!packet||typeof packet.type!=="string")return Promise.reject(Error("Invalid combat packet"));if(packet.type==="hit"){if(!validHit(packet))return Promise.reject(Error("Invalid hit packet"));if(this.isHost){const hp=Math.max(0,this.peerHealth-Math.round(packet.damage)),killed=hp===0;this.peerHealth=hp;if(killed)this.peerKilledAt=this.now();this.authoritativeHits.set(packet.id,{hp,killed,at:this.now()});while(this.authoritativeHits.size>MAX_SEEN_COMBAT)this.authoritativeHits.delete(this.authoritativeHits.keys().next().value);queueMicrotask(()=>this._deliverAction("combat",{type:"state",id:packet.id,hp,killed}));return this._sendControlRaw({a:"combat",d:{type:"hit",id:packet.id,damage:packet.damage,authority:"host"}});}return this._sendControlRaw({a:"combat",d:{type:"hit-request",id:packet.id,damage:packet.damage}});}
    if(packet.type==="state"){if(!validState(packet))return Promise.reject(Error("Invalid state packet"));return this.isHost?this._sendControlRaw({a:"combat",d:{...packet,authority:"host"}}):this._sendControlRaw({a:"combat",d:{type:"state-ack",id:packet.id,hp:packet.hp,killed:packet.killed}});}
    if(packet.type==="respawn"){if(!validRespawn(packet))return Promise.reject(Error("Invalid respawn packet"));if(this.isHost)return this._sendControlRaw({a:"combat",d:{type:"respawn",hp:packet.hp,authority:"host"}});return this._sendControlRaw({a:"combat",d:{type:"respawn-request",hp:packet.hp,requestedAt:this.now()}});}
    return Promise.reject(Error("Unsupported combat packet"));
  }
  _receiveCombatWire(packet){if(!packet||typeof packet.type!=="string")return;if(this.isHost){if(packet.type==="hit-request"){const hit={type:"hit",id:String(packet.id||""),damage:Number(packet.damage)};if(!validHit(hit)||!rememberBounded(this.seenHitRequests,hit.id))return;this._deliverAction("combat",hit);return;}if(packet.type==="state-ack"){const expected=this.authoritativeHits.get(String(packet.id||""));if(!expected)return;this.authoritativeHits.delete(String(packet.id||""));this.diag("authority-state-ack",{id:String(packet.id||""),reportedHp:Number(packet.hp),authoritativeHp:expected.hp});return;}if(packet.type==="respawn-request"){if(this.peerHealth!==0||this.now()-this.peerKilledAt<RESPAWN_AUTHORITY_MS){this.diag("authority-respawn-rejected",{peerHealth:this.peerHealth,elapsedMs:this.now()-this.peerKilledAt});return;}this.peerHealth=100;this.peerKilledAt=0;this._deliverAction("combat",{type:"respawn",hp:100});this._sendControlRaw({a:"combat",d:{type:"respawn-authorized",hp:100}}).catch(()=>{});return;}return;}
    if(packet.type==="hit"&&validHit(packet)){this._deliverAction("combat",{type:"hit",id:packet.id,damage:packet.damage});return;}if(packet.type==="state"&&validState(packet)){this._deliverAction("combat",{type:"state",id:packet.id,hp:packet.hp,killed:packet.killed});return;}if(packet.type==="respawn"&&validRespawn(packet)){this._deliverAction("combat",{type:"respawn",hp:packet.hp});return;}if(packet.type==="respawn-authorized"){this.diag("authority-respawn-authorized");}}
  async ping(){if(!this.ready)return Promise.reject(Error("Direct UDP peer unavailable"));const nonce=packetId();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pendingPings.delete(nonce);reject(Error("Direct UDP ping timeout"));},PING_TIMEOUT_MS);this.pendingPings.set(nonce,{started:performance.now(),resolve:value=>{clearTimeout(timer);resolve(value);},reject:error=>{clearTimeout(timer);reject(error);}});this._sendControlRaw({a:"__ping",n:nonce}).catch(error=>{clearTimeout(timer);this.pendingPings.delete(nonce);reject(error);});});}
  _connectionChanged(){if(this.closed||!this.pc)return;const state=String(this.pc.connectionState||this.pc.iceConnectionState||"");this.diag("direct-udp-state",{state,iceState:String(this.pc.iceConnectionState||"")});if(state==="connected"){clearTimeout(this.disconnectTimer);clearTimeout(this.restartTimer);this.disconnectTimer=0;this.restartTimer=0;this.restartInFlight=false;this._channelsChanged();return;}if(state==="disconnected"){if(!this.disconnectTimer)this.disconnectTimer=setTimeout(()=>{this.disconnectTimer=0;this._requestRecovery("disconnected");},DISCONNECT_GRACE_MS);return;}if(state==="failed"){this._requestRecovery("failed");return;}if(state==="closed")this.close("closed",true);}
  _requestRecovery(reason){if(this.closed||!this.pc)return;if(!this.restartTimer)this.restartTimer=setTimeout(()=>{this.restartTimer=0;if(!this.closed&&String(this.pc?.connectionState||this.pc?.iceConnectionState||"")!=="connected")this.close(`ice-restart-timeout:${reason}`,true);},RESTART_TIMEOUT_MS);if(this.isHost)this.restartIce(reason).catch(error=>this.diag("ice-restart-error",{error:errorText(error)}));else Promise.resolve(this.sendSignal({kind:"restart-needed",reason})).catch(error=>this.diag("signal-send-error",{kind:"restart-needed",error:errorText(error)}));}
  async restartIce(reason="manual"){if(this.closed||!this.pc||!this.isHost)return false;if(this.restartInFlight)return true;this.restartInFlight=true;try{await this._startOffer(true);this.diag("ice-restart-requested",{reason});return true;}catch(error){this.restartInFlight=false;throw error;}}
  _channelClosed(channel){if(this.closed)return;this.diag("direct-udp-channel-close",{channel});this.close(`${channel}-closed`,true);}
  debug(){return{ready:this.ready,isHost:this.isHost,localChannelsReady:this.localChannelsReady,remoteReady:this.remoteReady,remoteAcked:this.remoteAcked,peerHealth:this.peerHealth,pose:{readyState:this.poseChannel?.readyState||"",ordered:this.poseChannel?.ordered,maxRetransmits:this.poseChannel?.maxRetransmits,bufferedAmount:Number(this.poseChannel?.bufferedAmount||0)},control:{readyState:this.controlChannel?.readyState||"",ordered:this.controlChannel.ordered,maxRetransmits:this.controlChannel.maxRetransmits},connectionState:String(this.pc?.connectionState||""),iceConnectionState:String(this.pc?.iceConnectionState||"")};}
  close(reason="closed",notify=false){if(this.closed)return;this.closed=true;const wasReady=this.ready;this.ready=false;clearInterval(this.readyTimer);clearInterval(this.offerTimer);clearTimeout(this.disconnectTimer);clearTimeout(this.restartTimer);this.readyTimer=0;this.offerTimer=0;this.disconnectTimer=0;this.restartTimer=0;for(const pending of this.pendingPings.values())pending.reject?.(Error("Direct UDP peer closed"));this.pendingPings.clear();try{this.pc?.close?.();}catch{}this.diag("direct-udp-peer-left",{reason});if(notify&&wasReady)queueMicrotask(()=>this.onLeave?.(this.peerId,reason));}
}

export const DIRECT_UDP_DEFAULT_ICE_SERVERS=DEFAULT_ICE_SERVERS;
