import * as THREE from "three";
import {Box3dHitscanWorld} from "./box3d_hitscan.mjs";

const SPEED_MPS=31;
const MAX_RANGE_M=220;
const TTL_MS=7200;
const COOLDOWN_MS=950;
const BLAST_RADIUS_M=8;
const BLAST_MAX_DAMAGE=100;
const raycaster=new THREE.Raycaster(),ndc=new THREE.Vector2(),tmp=new THREE.Vector3(),axis=new THREE.Vector3(0,0,-1),boxHits=new Box3dHitscanWorld();
const missileBodyGeometry=new THREE.CylinderGeometry(.025,.032,.26,8),missileTipGeometry=new THREE.ConeGeometry(.034,.09,8),missileBodyMaterial=new THREE.MeshStandardMaterial({color:0xcfd7db,roughness:.35,metalness:.45}),missileTipMaterial=new THREE.MeshBasicMaterial({color:0xffaa4a});
const missiles=[],candidateNodes=[];
let installed=false,patchedApi=null,lastShot=-Infinity,lastFrame=performance.now(),candidateScene=null,lastCandidateScan=-Infinity;

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function walk(){return globalThis.__arondightWalkMode||null;}
function drive(){return globalThis.__arondightVehicleDrive||null;}
function isDrone(){return walk()?.mode!=="foot"&&!drive()?.active;}
function clamp(v,a,b){return Math.max(a,Math.min(b,Number(v)||0));}
function logicalPoint(clientX,clientY){const view=viewport(),screen=view?.getBoundingClientRect();if(!view||!screen)return null;const width=Math.max(1,view.clientWidth),height=Math.max(1,view.clientHeight),cx=Number.isFinite(Number(clientX))?Number(clientX):screen.left+screen.width/2,cy=Number.isFinite(Number(clientY))?Number(clientY):screen.top+screen.height/2,rotated=view.dataset.soloOrientation==="css-landscape",x=rotated?cy-screen.top:cx-screen.left,y=rotated?screen.right-cx:cy-screen.top;return{x:clamp(x,0,width),y:clamp(y,0,height),width,height};}
function screenRay(clientX,clientY){const camera=bridge()?.threeCamera,p=logicalPoint(clientX,clientY);if(!camera||!p)return null;ndc.set(p.x/p.width*2-1,1-p.y/p.height*2);camera.updateMatrixWorld?.(true);raycaster.setFromCamera(ndc,camera);return{origin:raycaster.ray.origin.clone(),direction:raycaster.ray.direction.clone().normalize(),point:p};}
function ignored(node){for(let n=node;n;n=n.parent){const u=n.userData||{};if(u.flightFireIgnore||u.walkWeaponPart||u.arondightAirframe||u.localHumanAvatar||u.directFireMissile)return true;}return false;}
function candidates(scene,force=false){const now=performance.now();if(scene!==candidateScene){candidateScene=scene;lastCandidateScan=-Infinity;candidateNodes.length=0;}if(!force&&now-lastCandidateScan<500)return candidateNodes;lastCandidateScan=now;candidateNodes.length=0;scene?.traverse?.(node=>{if(!node?.isMesh||node.visible===false||node.material?.visible===false||ignored(node))return;candidateNodes.push(node);});return candidateNodes;}
function nearestHit(origin,direction,maxDistance){const b=bridge(),scene=b?.threeScene;if(!scene)return null;raycaster.set(origin,direction);raycaster.near=.03;raycaster.far=maxDistance;const sceneHit=raycaster.intersectObjects(candidates(scene),false)[0]||null;let staticHit=null;if(b.active&&b.buildingCollisionSnapshot){const hit=boxHits.cast([origin.x,origin.y,origin.z],[direction.x,direction.y,direction.z],maxDistance,b.buildingCollisionSnapshot);if(hit)staticHit={distance:hit.distanceM,point:new THREE.Vector3(...hit.point)};}return staticHit&&(!sceneHit||staticHit.distance<sceneHit.distance)?staticHit:sceneHit;}
function makeMissile(scene,position,direction){const group=new THREE.Group(),body=new THREE.Mesh(missileBodyGeometry,missileBodyMaterial),tip=new THREE.Mesh(missileTipGeometry,missileTipMaterial);body.rotation.x=Math.PI/2;tip.rotation.x=Math.PI/2;tip.position.z=-.17;for(const node of[body,tip]){node.userData.flightFireIgnore=true;node.userData.directFireMissile=true;}group.userData.flightFireIgnore=true;group.userData.directFireMissile=true;group.add(body,tip);group.position.copy(position);group.quaternion.setFromUnitVectors(axis,direction);scene.add(group);return group;}
function explode(index,position){const missile=missiles[index];if(!missile)return;missile.scene.remove(missile.group);missiles.splice(index,1);window.dispatchEvent(new CustomEvent("arondight:world-explosion",{detail:{position:[position.x,position.y,position.z],radiusM:BLAST_RADIUS_M,maxDamage:BLAST_MAX_DAMAGE,kind:"missile",source:"fixed-screen-ray",targeted:false}}));const view=viewport();if(view){view.dataset.droneMissileLastDetonation="fixed-screen-ray";view.dataset.droneActiveMissiles=String(missiles.length);}}
function fireMissile({clientX,clientY,source="external"}={}){const now=performance.now(),view=viewport();if(!isDrone()||globalThis.__arondightDroneDamageModel?.destroyed||now-lastShot<COOLDOWN_MS||view?.dataset.fireArmed!=="1")return false;const ray=screenRay(clientX,clientY),scene=bridge()?.threeScene;if(!ray||!scene)return false;lastShot=now;candidates(scene,true);const hit=nearestHit(ray.origin,ray.direction,MAX_RANGE_M),targetDistance=clamp(Number(hit?.distance)||MAX_RANGE_M,.8,MAX_RANGE_M),start=ray.origin.clone().addScaledVector(ray.direction,.30),group=makeMissile(scene,start,ray.direction);missiles.push({group,scene,direction:ray.direction.clone(),born:now,travelled:0,targetDistance,source});if(view){view.dataset.droneWeapon="missile";view.dataset.droneMissiles=String((Number(view.dataset.droneMissiles)||0)+1);view.dataset.droneMissileGuidance="fixed-screen-ray-no-homing-v1";view.dataset.droneMissileInput=String(source);view.dataset.droneMissileDirection=`${ray.direction.x.toFixed(4)},${ray.direction.y.toFixed(4)},${ray.direction.z.toFixed(4)}`;view.dataset.droneActiveMissiles=String(missiles.length);}return true;}
function patchApi(){const api=globalThis.__arondightDroneWeapons;if(!api||api===patchedApi)return Boolean(api);api.fireMissile=fireMissile;patchedApi=api;const view=viewport();if(view)view.dataset.droneMissileContract="tap-ray-fixed-after-launch-v1";return true;}
function frame(now=performance.now()){const dt=clamp((now-lastFrame)/1000,0,.05);lastFrame=now;patchApi();for(let i=missiles.length-1;i>=0;i--){const m=missiles[i],step=SPEED_MPS*dt;if(now-m.born>TTL_MS||m.travelled>=m.targetDistance-.06){explode(i,m.group.position.clone());continue;}const remaining=Math.max(0,m.targetDistance-m.travelled),travel=Math.min(step,remaining),hit=nearestHit(m.group.position,m.direction,travel+.10);if(hit&&Number(hit.distance)<=travel+.06){explode(i,hit.point?.clone?.()||m.group.position.clone());continue;}m.group.position.addScaledVector(m.direction,travel);m.travelled+=travel;m.group.quaternion.setFromUnitVectors(axis,m.direction);}requestAnimationFrame(frame);}

export function installDirectFireMissiles(){if(installed)return;installed=true;patchApi();requestAnimationFrame(frame);}
installDirectFireMissiles();
