import * as THREE from "three";

const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
const shotCamera=new THREE.PerspectiveCamera(78,16/9,.01,500),raycaster=new THREE.Raycaster(),ndc=new THREE.Vector2(),forward=new THREE.Vector3(),target=new THREE.Vector3(),aimNdc=new THREE.Vector2();
const shotOrigin=new THREE.Vector3(),shotDirection=new THREE.Vector3(0,1,0),aimTargetWorld=new THREE.Vector3(),desiredSightDirection=new THREE.Vector3(),rearWorld=new THREE.Vector3(),frontWorld=new THREE.Vector3(),sightDirection=new THREE.Vector3();
const latchedPivotNdc=new THREE.Vector2(),latchedPivotCameraLocal=new THREE.Vector3(),desiredPivotCameraLocal=new THREE.Vector3(),desiredPivotWorld=new THREE.Vector3(),pivotWorld=new THREE.Vector3(),rootWorldPosition=new THREE.Vector3(),desiredRootWorldPosition=new THREE.Vector3(),anchorLocalCheck=new THREE.Vector3(),projectedPivot=new THREE.Vector3(),tempLocalPosition=new THREE.Vector3();
const baseWorldQuaternion=new THREE.Quaternion(),desiredWorldQuaternion=new THREE.Quaternion(),parentWorldQuaternion=new THREE.Quaternion(),inverseParentQuaternion=new THREE.Quaternion(),aimAdjust=new THREE.Quaternion();
const lastBasePosition=new THREE.Vector3(),lastOutputPosition=new THREE.Vector3(),lastHipPivotCameraLocal=new THREE.Vector3(),lastHipPivotNdc=new THREE.Vector2();
const lastBaseQuaternion=new THREE.Quaternion(),lastOutputQuaternion=new THREE.Quaternion();
const TOUCH_AIM_DISTANCE_M=180;
const PISTOL_PARTS=new Set(["WALK_VM_FRAME","WALK_VM_RAIL","WALK_VM_SLIDE","WALK_VM_SLIDE_TOP","WALK_VM_BARREL","WALK_VM_MUZZLE","WALK_VM_EJECTION_PORT","WALK_VM_GRIP","WALK_VM_MAG_BASE","WALK_VM_TRIGGER_GUARD","WALK_VM_TRIGGER","WALK_VM_REAR_SIGHT","WALK_VM_FRONT_SIGHT","WALK_VM_FRONT_DOT"]);
const AIM_HIDE_ALWAYS=new Set(["WALK_VM_SLEEVE_R","WALK_VM_CUFF_R","WALK_VM_SLEEVE_L","WALK_VM_CUFF_L"]);
const POST_FIRE_ALIGN_MS=150;
const TRANSFORM_EPSILON_M=1e-6,QUAT_DOT_EPSILON=1e-7;
let installed=false,lastScreenAimAt=-Infinity,lastScreenFireAt=-Infinity,lastSwitchAt=-Infinity,lastMode="",lastGun=null,screenAimActive=false,lastAimSource="center",hasPresentationSnapshot=false;
let aimPivotLatched=false,aimPivotMode="",latchedPivotDepthM=.7,lastLatchContinuityM=0,lastHipPivotValid=false,lastHipPivotMode="";
let hookedScene=null,renderHook=null,previousSceneOnBeforeRender=null;

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function walk(){return globalThis.__arondightWalkMode||null;}
function drive(){return globalThis.__arondightVehicleDrive||null;}
function footWeapons(){return globalThis.__arondightFootWeapons||null;}
function isFoot(){return walk()?.mode==="foot"&&!drive()?.active&&!walk()?.dead;}
function logicalPoint(clientX,clientY){const view=viewport(),screen=view?.getBoundingClientRect();if(!view||!screen)return null;const width=Math.max(1,view.clientWidth),height=Math.max(1,view.clientHeight),cx=Number.isFinite(clientX)?clientX:screen.left+screen.width/2,cy=Number.isFinite(clientY)?clientY:screen.top+screen.height/2,rotated=view.dataset.soloOrientation==="css-landscape",x=rotated?cy-screen.top:cx-screen.left,y=rotated?screen.right-cx:cy-screen.top;return{x:clamp(x,0,width),y:clamp(y,0,height),width,height};}
function shotRay(clientX,clientY){const w=walk(),p=logicalPoint(clientX,clientY);if(!w?.position||!p)return null;shotCamera.fov=clamp(Number(viewport()?.dataset.walkCameraFovDeg)||Number(bridge()?.threeCamera?.fov)||78,45,120);shotCamera.aspect=p.width/p.height;shotCamera.position.set(Number(w.position.x)||0,Number(w.position.y)||0,Number(w.position.z)||1.68);shotCamera.up.set(0,0,1);const cp=Math.cos(Number(w.pitch)||0);forward.set(Math.sin(Number(w.yaw)||0)*cp,Math.cos(Number(w.yaw)||0)*cp,Math.sin(Number(w.pitch)||0)).normalize();shotCamera.lookAt(target.copy(shotCamera.position).add(forward));shotCamera.updateProjectionMatrix();shotCamera.updateMatrixWorld(true);ndc.set(p.x/p.width*2-1,1-p.y/p.height*2);raycaster.setFromCamera(ndc,shotCamera);return{origin:raycaster.ray.origin.clone(),direction:raycaster.ray.direction.clone(),point:p};}
function material(options){return new THREE.MeshStandardMaterial({depthTest:true,depthWrite:true,...options});}
function mesh(name,geometry,mat,x,y,z,rx=0,ry=0,rz=0,order=9998){const m=new THREE.Mesh(geometry,mat);m.name=name;m.position.set(x,y,z);m.rotation.set(rx,ry,rz);m.renderOrder=order;m.frustumCulled=false;m.userData.flightFireIgnore=true;m.userData.walkWeaponPart=true;m.userData.walkSmgPart=true;return m;}
function ensureAimStyle(){if(document.querySelector("style[data-foot-ads-kimme-korn]"))return;const style=document.createElement("style");style.dataset.footAdsKimmeKorn="v7";style.textContent=`body.foot-ads-active #footReadout,body.foot-ads-active #footWeaponToggle{opacity:0!important;pointer-events:none!important}body.foot-ads-active #footReticle.screen-aim-active{opacity:1!important}`;document.head.appendChild(style);}
function ensureSmg(gun){
  let group=gun.getObjectByName?.("WALK_SMG_3D");if(group)return group;
  group=new THREE.Group();group.name="WALK_SMG_3D";group.position.set(.012,-.008,.015);group.userData.flightFireIgnore=true;group.userData.walkWeaponPart=true;group.userData.walkSmgViewmodel="dedicated-mp-mesh-v4";
  const steel=material({color:0x202a31,roughness:.30,metalness:.72}),upper=material({color:0x38444d,roughness:.27,metalness:.68}),polymer=material({color:0x0d1317,roughness:.72,metalness:.08}),rubber=material({color:0x080b0d,roughness:.90,metalness:0}),sight=new THREE.MeshBasicMaterial({color:0xbfefff,depthTest:true,depthWrite:false});
  group.add(mesh("WALK_SMG_RECEIVER",new THREE.BoxGeometry(.178,.132,.390),steel,0,-.010,-.300),mesh("WALK_SMG_UPPER",new THREE.BoxGeometry(.158,.060,.345),upper,0,.075,-.320),mesh("WALK_SMG_HANDGUARD",new THREE.BoxGeometry(.162,.145,.275),polymer,0,-.005,-.575),mesh("WALK_SMG_BARREL",new THREE.CylinderGeometry(.020,.020,.270,12),steel,0,.020,-.735,Math.PI/2,0,0),mesh("WALK_SMG_MUZZLE",new THREE.CylinderGeometry(.039,.034,.074,12),rubber,0,.020,-.875,Math.PI/2,0,0),mesh("WALK_SMG_PISTOL_GRIP",new THREE.BoxGeometry(.098,.220,.120),polymer,0,-.178,-.155,-.13,0,0),mesh("WALK_SMG_MAGAZINE",new THREE.BoxGeometry(.090,.255,.112),upper,0,-.225,-.315,-.08,0,0),mesh("WALK_SMG_MAG_BASE",new THREE.BoxGeometry(.104,.028,.122),rubber,0,-.352,-.307,-.08,0,0),mesh("WALK_SMG_REAR_BLOCK",new THREE.BoxGeometry(.162,.108,.110),polymer,0,-.020,-.060),mesh("WALK_SMG_BRACE",new THREE.BoxGeometry(.190,.084,.175),rubber,0,-.040,.082),mesh("WALK_SMG_TOP_RAIL",new THREE.BoxGeometry(.118,.024,.320),rubber,0,.120,-.330),mesh("WALK_SMG_REAR_SIGHT",new THREE.BoxGeometry(.070,.034,.032),rubber,0,.142,-.125),mesh("WALK_SMG_FRONT_SIGHT",new THREE.BoxGeometry(.032,.040,.028),rubber,0,.143,-.705),mesh("WALK_SMG_FRONT_DOT",new THREE.SphereGeometry(.0065,6,4),sight,0,.161,-.713,0,0,0,9999));
  const muzzleNode=new THREE.Object3D();muzzleNode.name="WALK_SMG_MUZZLE_NODE";muzzleNode.position.set(0,.020,-.915);muzzleNode.userData.flightFireIgnore=true;group.add(muzzleNode);gun.add(group);return group;
}
function setWeaponModeVisual(gun,mode){const smg=ensureSmg(gun),isSmg=mode==="smg";smg.visible=isSmg;const conversion=gun.getObjectByName?.("FINAL_SMG_CONVERSION");if(conversion)conversion.visible=false;gun.traverse?.(node=>{if(PISTOL_PARTS.has(node.name))node.visible=!isSmg;});const flash=gun.getObjectByName?.("FINAL_MUZZLE_FLASH")||gun.getObjectByName?.("WALK_MUZZLE_FLASH");if(flash){flash.position.z=isSmg?-.925:-.405;flash.position.y=isSmg?.020:.029;flash.traverse?.(node=>{if(node.isMesh&&node.material){node.material.depthTest=true;node.material.depthWrite=false;node.material.needsUpdate=true;}if(node.isMesh)node.renderOrder=9996;});}gun.userData.finalWeapon=mode;gun.userData.walkWeaponViewmodel=isSmg?"dedicated-mp-mesh-v4":"compact-pistol-gloves-v2";const view=viewport();if(view){view.dataset.walkWeapon=mode;view.dataset.walkWeaponViewmodel=gun.userData.walkWeaponViewmodel;view.dataset.walkSmgMesh=isSmg?"dedicated-receiver+barrel+magazine+brace-v4":"hidden";view.dataset.walkWeaponSwitch="single-owner-touch+q+dpad-v4";}}
function setAimCleanup(gun,active,mode){gun.traverse?.(node=>{if(AIM_HIDE_ALWAYS.has(node.name))node.visible=!active;if(node.name==="WALK_VM_GLOVE_L")node.visible=!(active&&mode==="pistol");});}
function sightNodes(gun,mode){if(mode==="smg")return{rear:gun.getObjectByName?.("WALK_SMG_REAR_SIGHT"),front:gun.getObjectByName?.("WALK_SMG_FRONT_DOT")||gun.getObjectByName?.("WALK_SMG_FRONT_SIGHT")};return{rear:gun.getObjectByName?.("WALK_VM_REAR_SIGHT"),front:gun.getObjectByName?.("WALK_VM_FRONT_DOT")||gun.getObjectByName?.("WALK_VM_FRONT_SIGHT")};}
function pivotNode(gun,mode){return mode==="smg"?gun.getObjectByName?.("WALK_SMG_PISTOL_GRIP"):gun.getObjectByName?.("WALK_VM_GRIP");}
function quaternionMatches(a,b){return 1-Math.abs(a.dot(b))<=QUAT_DOT_EPSILON;}
function restoreOrCaptureBase(gun){if(hasPresentationSnapshot&&gun===lastGun&&gun.position.distanceToSquared(lastOutputPosition)<=TRANSFORM_EPSILON_M*TRANSFORM_EPSILON_M&&quaternionMatches(gun.quaternion,lastOutputQuaternion)){gun.position.copy(lastBasePosition);gun.quaternion.copy(lastBaseQuaternion);}else{lastBasePosition.copy(gun.position);lastBaseQuaternion.copy(gun.quaternion);}hasPresentationSnapshot=true;}
function setWorldQuaternion(gun,quat){const parent=gun.parent;if(!parent){gun.quaternion.copy(quat);return;}parent.getWorldQuaternion(parentWorldQuaternion);inverseParentQuaternion.copy(parentWorldQuaternion).invert();gun.quaternion.copy(inverseParentQuaternion.multiply(quat)).normalize();}
function setWorldPosition(gun,position){const parent=gun.parent;if(!parent){gun.position.copy(position);return;}tempLocalPosition.copy(position);parent.worldToLocal(tempLocalPosition);gun.position.copy(tempLocalPosition);}
function keepPivotAt(gun,pivot,desired){gun.updateMatrixWorld(true);pivot.getWorldPosition(pivotWorld);gun.getWorldPosition(rootWorldPosition);desiredRootWorldPosition.copy(rootWorldPosition).add(desired).sub(pivotWorld);setWorldPosition(gun,desiredRootWorldPosition);gun.updateMatrixWorld(true);}
function releaseAimPivot(reason="inactive"){if(!aimPivotLatched)return;aimPivotLatched=false;aimPivotMode="";const view=viewport();if(view){view.dataset.walkWeaponGripLatchActive="0";view.dataset.walkWeaponGripLatchRelease=reason;}}
function latchAimPivot(gun,pivot,camera,mode){gun.updateMatrixWorld(true);camera.updateMatrixWorld?.(true);pivot.getWorldPosition(pivotWorld);const usePresented=lastHipPivotValid&&lastHipPivotMode===mode;if(usePresented){latchedPivotCameraLocal.copy(lastHipPivotCameraLocal);desiredPivotWorld.copy(latchedPivotCameraLocal);camera.localToWorld(desiredPivotWorld);projectedPivot.copy(desiredPivotWorld).project(camera);lastLatchContinuityM=0;}else{latchedPivotCameraLocal.copy(pivotWorld);camera.worldToLocal(latchedPivotCameraLocal);desiredPivotWorld.copy(latchedPivotCameraLocal);camera.localToWorld(desiredPivotWorld);projectedPivot.copy(pivotWorld).project(camera);lastLatchContinuityM=desiredPivotWorld.distanceTo(pivotWorld);}latchedPivotDepthM=Math.max(.05,-latchedPivotCameraLocal.z);latchedPivotNdc.set(projectedPivot.x,projectedPivot.y);desiredPivotCameraLocal.copy(latchedPivotCameraLocal);aimPivotLatched=true;aimPivotMode=mode;const view=viewport();if(view){view.dataset.walkWeaponGripLatchActive="1";view.dataset.walkWeaponGripLatchMode=mode;view.dataset.walkWeaponGripLatchSource=usePresented?"last-presented-hip-v1":"current-hip-fallback";view.dataset.walkWeaponGripLatchNdc=`${latchedPivotNdc.x.toFixed(4)},${latchedPivotNdc.y.toFixed(4)}`;view.dataset.walkWeaponGripLatchDepthM=latchedPivotDepthM.toFixed(4);view.dataset.walkWeaponAimStartContinuityM=lastLatchContinuityM.toFixed(6);}}
function capturePresentedHipPivot(gun,camera,mode){const pivot=pivotNode(gun,mode);if(!pivot||!camera)return false;gun.updateMatrixWorld(true);camera.updateMatrixWorld?.(true);pivot.getWorldPosition(pivotWorld);lastHipPivotCameraLocal.copy(pivotWorld);camera.worldToLocal(lastHipPivotCameraLocal);projectedPivot.copy(pivotWorld).project(camera);lastHipPivotNdc.set(projectedPivot.x,projectedPivot.y);lastHipPivotMode=mode;lastHipPivotValid=true;const view=viewport();if(view){view.dataset.walkWeaponHipGripNdc=`${lastHipPivotNdc.x.toFixed(4)},${lastHipPivotNdc.y.toFixed(4)}`;view.dataset.walkWeaponHipGripSource="last-presented-provider-frame-v1";}return true;}
function latchedPivotLocal(camera,out=desiredPivotCameraLocal){return out.copy(latchedPivotCameraLocal);}
function latchVisibleAimPivot(){const scene=bridge()?.threeScene,camera=bridge()?.threeCamera,gun=scene?.getObjectByName?.("WALK_PISTOL_3D"),mode=String(footWeapons()?.mode||"pistol"),pivot=gun?pivotNode(gun,mode):null;if(!gun||!camera||!pivot||gun.visible===false)return false;gun.updateMatrixWorld(true);camera.updateMatrixWorld?.(true);if(!aimPivotLatched||aimPivotMode!==mode){lastHipPivotValid=false;latchAimPivot(gun,pivot,camera,mode);}const view=viewport();if(view&&aimPivotLatched){view.dataset.walkWeaponAnchorDriftM="0.000000";view.dataset.walkWeaponTranslationPolicy="latch-current-hip-grip+rotation-about-pivot-v4";view.dataset.walkWeaponPresentationCamera="player-main-camera-only-v1";}return aimPivotLatched;}
function applyLatchedAimTransform(gun,camera,now=performance.now()){
  gun.scale.setScalar(1);restoreOrCaptureBase(gun);const fireAge=now-lastScreenFireAt,active=isFoot()&&(screenAimActive||(fireAge>=0&&fireAge<=POST_FIRE_ALIGN_MS)),mode=String(footWeapons()?.mode||"pistol");if(!active||!camera||gun.visible===false){setAimCleanup(gun,false,mode);releaseAimPivot(!isFoot()?"mode-inactive":"aim-release");lastOutputPosition.copy(gun.position);lastOutputQuaternion.copy(gun.quaternion);const view=viewport();if(view){view.dataset.walkWeaponAimMode="hip";view.dataset.walkWeaponAimActive="0";}return false;}
  const sights=sightNodes(gun,mode),pivot=pivotNode(gun,mode);if(!sights.rear||!sights.front||!pivot||shotDirection.lengthSq()<.5){lastOutputPosition.copy(gun.position);lastOutputQuaternion.copy(gun.quaternion);return false;}
  setAimCleanup(gun,false,mode);gun.scale.setScalar(1);gun.updateMatrixWorld(true);if(!aimPivotLatched||aimPivotMode!==mode)latchAimPivot(gun,pivot,camera,mode);
  latchedPivotLocal(camera,desiredPivotCameraLocal);desiredPivotWorld.copy(desiredPivotCameraLocal);camera.localToWorld(desiredPivotWorld);keepPivotAt(gun,pivot,desiredPivotWorld);
  sights.rear.getWorldPosition(rearWorld);sights.front.getWorldPosition(frontWorld);sightDirection.copy(frontWorld).sub(rearWorld).normalize();gun.getWorldQuaternion(baseWorldQuaternion);aimTargetWorld.copy(shotOrigin).addScaledVector(shotDirection,TOUCH_AIM_DISTANCE_M);desiredSightDirection.copy(aimTargetWorld).sub(rearWorld).normalize();aimAdjust.setFromUnitVectors(sightDirection,desiredSightDirection);desiredWorldQuaternion.copy(aimAdjust).multiply(baseWorldQuaternion).normalize();setWorldQuaternion(gun,desiredWorldQuaternion);keepPivotAt(gun,pivot,desiredPivotWorld);
  sights.rear.getWorldPosition(rearWorld);sights.front.getWorldPosition(frontWorld);sightDirection.copy(frontWorld).sub(rearWorld).normalize();desiredSightDirection.copy(aimTargetWorld).sub(rearWorld).normalize();const targetAngleError=Math.acos(clamp(sightDirection.dot(desiredSightDirection),-1,1))*180/Math.PI;pivot.getWorldPosition(pivotWorld);anchorLocalCheck.copy(pivotWorld);camera.worldToLocal(anchorLocalCheck);const anchorDrift=anchorLocalCheck.distanceTo(desiredPivotCameraLocal);
  lastOutputPosition.copy(gun.position);lastOutputQuaternion.copy(gun.quaternion);const view=viewport();if(view){view.dataset.walkWeaponVectorAlignment="hip-latched-grip+touch-ray-target-v13";view.dataset.walkWeaponAimMode="kimme-korn";view.dataset.walkWeaponAimActive=screenAimActive?"1":"0";view.dataset.walkWeaponAimSource=lastAimSource;view.dataset.walkWeaponAimVector=`${shotDirection.x.toFixed(4)},${shotDirection.y.toFixed(4)},${shotDirection.z.toFixed(4)}`;view.dataset.walkWeaponAimNdc=`${aimNdc.x.toFixed(3)},${aimNdc.y.toFixed(3)}`;view.dataset.walkWeaponSightTargetErrorDeg=targetAngleError.toFixed(5);view.dataset.walkWeaponAnchorDriftM=anchorDrift.toFixed(6);view.dataset.walkWeaponGripLatchNdc=`${latchedPivotNdc.x.toFixed(4)},${latchedPivotNdc.y.toFixed(4)}`;view.dataset.walkWeaponGripLatchDepthM=latchedPivotDepthM.toFixed(4);view.dataset.walkWeaponAimStartContinuityM=lastLatchContinuityM.toFixed(6);view.dataset.walkWeaponAimTargetDistanceM=String(TOUCH_AIM_DISTANCE_M);view.dataset.walkWeaponPresentationOwner="scene-before-render-hip-grip-latch-v8";view.dataset.walkWeaponTranslationPolicy="latch-current-hip-grip+rotation-about-pivot-v4";view.dataset.walkWeaponAimScale="1.00";view.dataset.walkWeaponAdsPose=mode==="smg"?"mp-from-current-hip-grip-v7":"pistol-from-current-hip-grip-v7";}return true;
}
function ensureRenderHook(){return false;}
function applyProviderPresentation({camera,scene,gun=null,now=performance.now()}={}){const root=gun||scene?.getObjectByName?.("WALK_PISTOL_3D");if(!camera||!root)return false;const mode=String(footWeapons()?.mode||"pistol");setWeaponModeVisual(root,mode);const applied=applyLatchedAimTransform(root,camera,now);if(!applied&&!screenAimActive)capturePresentedHipPivot(root,camera,mode);const view=viewport();if(view){view.dataset.walkWeaponPresentationCamera="walk-camera-provider-v2";view.dataset.walkWeaponPresentationOwner="walk-camera-provider+weapon-runtime-v2";}return applied;}
function updateScreenVector(detail,source,active=true){if(!isFoot())return false;const ray=shotRay(Number(detail?.clientX),Number(detail?.clientY));if(!ray)return false;shotOrigin.copy(ray.origin);shotDirection.copy(ray.direction).normalize();aimNdc.set(ray.point.x/ray.point.width*2-1,1-ray.point.y/ray.point.height*2);lastScreenAimAt=performance.now();screenAimActive=Boolean(active);lastAimSource=String(source||detail?.source||"screen");const view=viewport();if(view){view.dataset.walkWeaponAimVector=`${shotDirection.x.toFixed(4)},${shotDirection.y.toFixed(4)},${shotDirection.z.toFixed(4)}`;view.dataset.walkWeaponAimNdc=`${aimNdc.x.toFixed(3)},${aimNdc.y.toFixed(3)}`;view.dataset.walkWeaponAimActive=screenAimActive?"1":"0";view.dataset.walkWeaponAimSource=lastAimSource;}return true;}
function onScreenAim(event){const d=event?.detail||{};if(d.active===false){screenAimActive=false;document.body.classList.remove("foot-ads-active");lastAimSource=String(d.source||"release");const view=viewport();if(view){view.dataset.walkWeaponAimActive="0";view.dataset.walkWeaponAimSource=lastAimSource;}return;}latchVisibleAimPivot();if(updateScreenVector(d,d.source||"touch-screen-drag",true))document.body.classList.add("foot-ads-active");}
function onScreenFire(event){if(!isFoot())return;const d=event?.detail||{};if(!updateScreenVector(d,d.source||"screen-fire",screenAimActive))return;lastScreenFireAt=performance.now();const view=viewport();if(view){view.dataset.walkWeaponFireVector="shared-touch-ray-hip-grip-latch-v13";view.dataset.walkWeaponAimSource=String(d.source||"screen");}}
function reliableTouchSwitch(event){const button=event.target instanceof Element?event.target.closest("#footWeaponToggle"):null;if(!button||!isFoot())return;const now=performance.now();if(now-lastSwitchAt<170){event.preventDefault();event.stopImmediatePropagation();return;}const api=footWeapons();if(typeof api?.toggle!=="function")return;lastSwitchAt=now;button.dataset.weaponPointerToggleAt=String(now);event.preventDefault();event.stopImmediatePropagation();api.toggle();releaseAimPivot("weapon-switch");const view=viewport();if(view)view.dataset.walkWeaponSwitchLast="touch-pointerdown-v4";}
function suppressSyntheticClick(event){const button=event.target instanceof Element?event.target.closest("#footWeaponToggle"):null;if(!button)return;const at=Number(button.dataset.weaponPointerToggleAt)||-Infinity;if(performance.now()-at<750){event.preventDefault();event.stopImmediatePropagation();}}
function frame(now=performance.now()){ensureAimStyle();const scene=bridge()?.threeScene,gun=scene?.getObjectByName?.("WALK_PISTOL_3D"),mode=String(footWeapons()?.mode||"pistol");if(gun){if(gun!==lastGun){hasPresentationSnapshot=false;lastHipPivotValid=false;lastGun=gun;lastMode="";releaseAimPivot("weapon-root-change");}if(mode!==lastMode){lastMode=mode;hasPresentationSnapshot=false;lastHipPivotValid=false;releaseAimPivot("weapon-mode-change");}setWeaponModeVisual(gun,mode);const footActive=isFoot();gun.visible=footActive;if(!footActive){screenAimActive=false;releaseAimPivot("mode-inactive");document.body.classList.remove("foot-ads-active");gun.scale.setScalar(1);setAimCleanup(gun,false,mode);}}const button=document.getElementById("footWeaponToggle");if(button){button.textContent=mode==="smg"?"MP → PISTOL":"PISTOL → MP";button.setAttribute("aria-label",mode==="smg"?"Switch to pistol":"Switch to MP");}const view=viewport();if(view){view.dataset.walkWeaponRuntime="dedicated-pistol+mp+hip-grip-latched-aim-v14";view.dataset.walkViewmodelVehiclePolicy="hidden-while-driving-v1";view.dataset.walkTouchFire="screen-point-raycast-v5";view.dataset.walkWeaponAimFreshMs=Number.isFinite(lastScreenAimAt)?String(Math.max(0,Math.round(now-lastScreenAimAt))):"";}requestAnimationFrame(frame);}
export function installFirstPersonWeaponRuntimeV3(){if(installed)return;installed=true;globalThis.__arondightFootWeaponPresentationV1=Object.freeze({apply:applyProviderPresentation});ensureAimStyle();addEventListener("arondight:foot-screen-aim",onScreenAim);addEventListener("arondight:foot-screen-fire",onScreenFire);addEventListener("arondight:player-mode",()=>{if(!isFoot())screenAimActive=false;releaseAimPivot("player-mode");hasPresentationSnapshot=false;document.body.classList.remove("foot-ads-active");});addEventListener("arondight:vehicle-mode",event=>{if(event?.detail?.active){const gun=bridge()?.threeScene?.getObjectByName?.("WALK_PISTOL_3D");if(gun)gun.visible=false;screenAimActive=false;releaseAimPivot("vehicle-enter");document.body.classList.remove("foot-ads-active");}});window.addEventListener("pointerdown",reliableTouchSwitch,{capture:true,passive:false});window.addEventListener("click",suppressSyntheticClick,{capture:true,passive:false});requestAnimationFrame(frame);}
installFirstPersonWeaponRuntimeV3();
