import * as THREE from "three";
import {Box3dHitscanWorld} from "./box3d_hitscan.mjs";

const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
const shotCamera=new THREE.PerspectiveCamera(78,16/9,.01,500),raycaster=new THREE.Raycaster(),ndc=new THREE.Vector2(),forward=new THREE.Vector3(),lookTarget=new THREE.Vector3(),boxHits=new Box3dHitscanWorld();
const targetPoint=new THREE.Vector3(),anchorBefore=new THREE.Vector3(),anchorAfter=new THREE.Vector3(),muzzleBefore=new THREE.Vector3(),muzzleAfter=new THREE.Vector3(),currentAxis=new THREE.Vector3(),desiredAxis=new THREE.Vector3(),adjust=new THREE.Quaternion(),translation=new THREE.Vector3(),fallbackTarget=new THREE.Vector3();
let installed=false,lastShotAt=-Infinity,targetValid=false,lastClientX=NaN,lastClientY=NaN;
const HOLD_MS=720;

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function walk(){return globalThis.__arondightWalkMode||null;}
function drive(){return globalThis.__arondightVehicleDrive||null;}
function footWeapons(){return globalThis.__arondightFootWeapons||null;}
function isFoot(){return walk()?.mode==="foot"&&!drive()?.active&&!walk()?.dead;}
function logicalPoint(clientX,clientY){const view=viewport(),screen=view?.getBoundingClientRect();if(!view||!screen)return null;const width=Math.max(1,view.clientWidth),height=Math.max(1,view.clientHeight),cx=Number.isFinite(clientX)?clientX:screen.left+screen.width/2,cy=Number.isFinite(clientY)?clientY:screen.top+screen.height/2,rotated=view.dataset.soloOrientation==="css-landscape",x=rotated?cy-screen.top:cx-screen.left,y=rotated?screen.right-cx:cy-screen.top;return{x:clamp(x,0,width),y:clamp(y,0,height),width,height};}
function shotRay(clientX,clientY){const w=walk(),p=logicalPoint(clientX,clientY);if(!w?.position||!p)return null;shotCamera.fov=clamp(Number(viewport()?.dataset.walkCameraFovDeg)||Number(bridge()?.threeCamera?.fov)||78,45,120);shotCamera.aspect=p.width/p.height;shotCamera.near=.01;shotCamera.far=220;shotCamera.position.set(Number(w.position.x)||0,Number(w.position.y)||0,Number(w.position.z)||1.68);shotCamera.up.set(0,0,1);const cp=Math.cos(Number(w.pitch)||0);forward.set(Math.sin(Number(w.yaw)||0)*cp,Math.cos(Number(w.yaw)||0)*cp,Math.sin(Number(w.pitch)||0)).normalize();shotCamera.lookAt(lookTarget.copy(shotCamera.position).add(forward));shotCamera.updateProjectionMatrix();shotCamera.updateMatrixWorld(true);ndc.set(p.x/p.width*2-1,1-p.y/p.height*2);raycaster.setFromCamera(ndc,shotCamera);return{origin:raycaster.ray.origin.clone(),direction:raycaster.ray.direction.clone()};}
function effectiveVisible(node){for(let n=node;n;n=n.parent)if(n.visible===false)return false;return true;}
function candidates(scene){const list=[];scene?.traverse?.(node=>{if(!node?.isMesh||!effectiveVisible(node)||node.material?.visible===false)return;const u=node.userData||{};if(u.flightFireIgnore||u.walkWeaponPart||u.arondightAirframe||u.localHumanAvatar||u.worldPopulationClone)return;list.push(node);});return list;}
function resolveTarget(ray){const b=bridge(),scene=b?.threeScene;if(!ray||!scene)return null;scene.updateMatrixWorld?.(true);raycaster.set(ray.origin,ray.direction);raycaster.near=.01;raycaster.far=180;const sceneHit=raycaster.intersectObjects(candidates(scene),false)[0]||null;let staticHit=null;try{if(b.active){const hit=boxHits.cast([ray.origin.x,ray.origin.y,ray.origin.z],[ray.direction.x,ray.direction.y,ray.direction.z],180,b.buildingCollisionSnapshot);if(hit)staticHit={distance:hit.distanceM,point:new THREE.Vector3(...hit.point)};}}catch{}const hit=staticHit&&(!sceneHit||staticHit.distance<sceneHit.distance)?staticHit:sceneHit;if(hit?.point)return targetPoint.copy(hit.point);return targetPoint.copy(fallbackTarget.copy(ray.origin).addScaledVector(ray.direction,120));}
function activeNodes(gun){const smg=String(footWeapons()?.mode||"")==="smg",grip=gun.getObjectByName?.(smg?"WALK_SMG_PISTOL_GRIP":"WALK_VM_GRIP")||gun.getObjectByName?.("WALK_VM_GRIP"),muzzle=gun.getObjectByName?.(smg?"WALK_SMG_MUZZLE_NODE":"FINAL_MUZZLE_FLASH")||gun.getObjectByName?.("WALK_MUZZLE_FLASH")||gun.getObjectByName?.("WALK_VM_MUZZLE");return{grip,muzzle,smg};}
function alignGun(now=performance.now()){
  if(!targetValid||now-lastShotAt<0||now-lastShotAt>HOLD_MS||!isFoot())return false;
  const scene=bridge()?.threeScene,gun=scene?.getObjectByName?.("WALK_PISTOL_3D");if(!gun||gun.visible===false)return false;const{grip,muzzle}=activeNodes(gun);if(!grip||!muzzle)return false;
  gun.updateWorldMatrix?.(true,true);grip.getWorldPosition(anchorBefore);muzzle.getWorldPosition(muzzleBefore);currentAxis.copy(muzzleBefore).sub(anchorBefore);desiredAxis.copy(targetPoint).sub(anchorBefore);if(currentAxis.lengthSq()<1e-6||desiredAxis.lengthSq()<1e-6)return false;currentAxis.normalize();desiredAxis.normalize();adjust.setFromUnitVectors(currentAxis,desiredAxis);gun.quaternion.premultiply(adjust);gun.updateWorldMatrix?.(true,true);grip.getWorldPosition(anchorAfter);translation.copy(anchorBefore).sub(anchorAfter);gun.position.add(translation);gun.updateWorldMatrix?.(true,true);grip.getWorldPosition(anchorAfter);muzzle.getWorldPosition(muzzleAfter);currentAxis.copy(muzzleAfter).sub(anchorAfter).normalize();desiredAxis.copy(targetPoint).sub(anchorAfter).normalize();const errorDeg=currentAxis.angleTo(desiredAxis)*180/Math.PI,drift=anchorAfter.distanceTo(anchorBefore),view=viewport();if(view){view.dataset.walkWeaponVectorAlignment="grip-anchor-to-resolved-shot-v6";view.dataset.walkWeaponAimWeight="1.000";view.dataset.walkWeaponAimErrorDeg=errorDeg.toFixed(3);view.dataset.walkWeaponGripAnchorDriftM=drift.toFixed(5);view.dataset.walkWeaponHandAnchor="grip-world-fixed-v2";view.dataset.walkWeaponAimTarget=`${targetPoint.x.toFixed(3)},${targetPoint.y.toFixed(3)},${targetPoint.z.toFixed(3)}`;view.dataset.walkWeaponGeometryVector="grip-to-muzzle-to-shot-point-v1";}return true;
}
function onScreenFire(event){if(!isFoot())return;const d=event?.detail||{},x=Number(d.clientX),y=Number(d.clientY),ray=shotRay(x,y),target=ray&&resolveTarget(ray);if(!target)return;lastClientX=x;lastClientY=y;lastShotAt=performance.now();targetValid=true;const view=viewport();if(view){view.dataset.walkWeaponFireVector="touch-screen-ray-v6";view.dataset.walkWeaponAimSource=String(d.source||"screen");view.dataset.walkWeaponHandAnchor="grip-world-fixed-v2";}alignGun(lastShotAt);}
function frame(now=performance.now()){if(targetValid&&isFoot()){if(now-lastShotAt<=HOLD_MS)alignGun(now);else targetValid=false;}const view=viewport();if(view){view.dataset.walkWeaponAnchorRuntime="resolved-shot-grip-pivot-v4";view.dataset.walkWeaponLastTouch=Number.isFinite(lastClientX)?`${lastClientX.toFixed(1)},${lastClientY.toFixed(1)}`:"";}requestAnimationFrame(frame);}
export function installFirstPersonWeaponAnchorV4(){if(installed)return;installed=true;addEventListener("arondight:foot-screen-fire",onScreenFire);requestAnimationFrame(frame);}
installFirstPersonWeaponAnchorV4();
