export const FLIGHT_LOGBOOK_KEY="arondight45FlightLogbookV1";
const MAX_FLIGHTS=50,PATH_INTERVAL_S=.5,MAX_PATH_POINTS=600;
const finite=(...values)=>values.every(Number.isFinite);

function loadEntries(){try{const value=JSON.parse(localStorage.getItem(FLIGHT_LOGBOOK_KEY)||"[]");return Array.isArray(value)?value.slice(0,MAX_FLIGHTS):[];}catch{return[];}}
function saveEntries(entries){try{localStorage.setItem(FLIGHT_LOGBOOK_KEY,JSON.stringify(entries.slice(0,MAX_FLIGHTS)));}catch{}}
function durationText(seconds){const total=Math.max(0,Number(seconds)||0),m=Math.floor(total/60),s=total-m*60;return m?`${m}m ${s.toFixed(1)}s`:`${s.toFixed(1)}s`;}
function downloadJson(value){const blob=new Blob([JSON.stringify(value,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`arondight45-flight-logbook-${new Date().toISOString().replaceAll(":","-")}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function bodyVelocity(sample){const yaw=(Number(sample.yawDeg)||0)*Math.PI/180,c=Math.cos(yaw),s=Math.sin(yaw),vx=Number(sample.vx)||0,vy=Number(sample.vy)||0;return{forward:-c*vx-s*vy,right:-s*vx+c*vy};}

export class FlightLogbook{
  constructor({parent=null}={}){this.entries=loadEntries();this.active=null;this.lastArmed=false;this.button=null;this.dialog=null;this.list=null;this.mount(parent);}
  mount(parent){
    if(!parent||this.button)return;
    const button=document.createElement("button");button.id="soloLogbook";button.type="button";button.textContent="LOGBOOK";button.setAttribute("aria-label","Open flight logbook");parent.insertBefore(button,parent.querySelector("#soloCamera")||null);this.button=button;
    const dialog=document.createElement("dialog");dialog.id="flightLogbookDialog";dialog.className="flight-logbook-dialog";dialog.innerHTML='<h3>FLIGHT LOGBOOK</h3><p>Local telemetry sessions from the real FC ARMED state. Logging is observer-only and never feeds controls, sensors, motors or physics.</p><div class="flight-logbook-list" data-flight-logbook-list></div><div class="flight-logbook-actions"><button type="button" data-flight-export>EXPORT JSON</button><button type="button" data-flight-clear>CLEAR</button><button type="button" data-flight-close>CLOSE</button></div>';document.body.appendChild(dialog);this.dialog=dialog;this.list=dialog.querySelector("[data-flight-logbook-list]");
    const style=document.createElement("style");style.textContent=`.flight-logbook-dialog{width:min(94vw,580px);max-height:88dvh;overflow:auto;border:1px solid #ffffff44;border-radius:14px;background:#0b1420f7;color:#fff;padding:16px;box-shadow:0 20px 70px #000b}.flight-logbook-dialog::backdrop{background:#0009;backdrop-filter:blur(4px)}.flight-logbook-dialog h3{margin:0 0 4px}.flight-logbook-dialog>p{color:#9eb0c6;font:12px/1.4 system-ui}.flight-logbook-list{display:grid;gap:8px}.flight-logbook-empty{padding:18px;border:1px dashed #ffffff33;border-radius:10px;color:#91a4ba;text-align:center;font:800 12px system-ui}.flight-log-entry{padding:10px;border:1px solid #ffffff25;border-radius:10px;background:#101d2b}.flight-log-entry header{display:flex;justify-content:space-between;gap:10px}.flight-log-entry strong{font:850 12px system-ui}.flight-log-entry time{font:750 10px ui-monospace,monospace;color:#91a7bc}.flight-log-entry .stats{margin-top:5px;color:#c7d5e3;font:700 10px/1.5 ui-monospace,monospace}.flight-log-entry .reason{color:#ffd06d}.flight-logbook-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:14px}.flight-logbook-actions button{border:1px solid #ffffff44;border-radius:9px;background:#162437;color:#fff;padding:8px 12px;font-weight:800}body.solo-flight #soloLogbook{background:#263b51dd!important}`;document.head.appendChild(style);
    button.onclick=()=>{this.render();dialog.showModal();};dialog.querySelector("[data-flight-close]").onclick=()=>dialog.close();dialog.querySelector("[data-flight-export]").onclick=()=>downloadJson({schema:"arondight45-flight-logbook-v1",exportedAt:new Date().toISOString(),flights:this.entries});dialog.querySelector("[data-flight-clear]").onclick=()=>{this.entries=[];saveEntries(this.entries);this.render();};this.render();
  }
  render(){
    if(this.button)this.button.textContent=this.entries.length?`LOGBOOK · ${this.entries.length}`:"LOGBOOK";if(!this.list)return;this.list.replaceChildren();
    if(!this.entries.length){const empty=document.createElement("div");empty.className="flight-logbook-empty";empty.textContent="NO FLIGHTS LOGGED YET";this.list.appendChild(empty);return;}
    for(const entry of this.entries){const article=document.createElement("article");article.className="flight-log-entry";const header=document.createElement("header"),title=document.createElement("strong"),time=document.createElement("time"),stats=document.createElement("div");title.textContent=`${entry.worldMode==="real"?"WORLD":"TRAINING"} · ${durationText(entry.durationS)}`;time.textContent=new Date(entry.startedAt).toLocaleString();header.append(title,time);stats.className="stats";stats.textContent=`DIST ${entry.distanceM.toFixed(1)} m · MAX ${entry.maxSpeedMps.toFixed(1)} m/s · AGL ${entry.maxAglM.toFixed(1)} m · ALT ${entry.maxAltitudeM.toFixed(1)} m · FWD ${entry.maxForwardMps.toFixed(1)} · STR ${entry.maxRightMps.toFixed(1)} m/s · NAV DEG ${entry.navDegradedS.toFixed(1)} s · BAT ${entry.batteryStartV.toFixed(2)}→${entry.batteryEndV.toFixed(2)} V · `;const reason=document.createElement("span");reason.className="reason";reason.textContent=String(entry.endReason||"FC_DISARM").replaceAll("_"," ");stats.append(reason);article.append(header,stats);this.list.appendChild(article);}
  }
  begin(sample){const t=Number(sample.simTime)||0,z=Number(sample.z)||0,battery=Number(sample.batteryV)||0;this.active={id:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,startedAt:new Date().toISOString(),simStart:t,lastSim:t,lastPathSim:-Infinity,worldMode:sample.worldMode==="real"?"real":"training",worldOrigin:sample.worldOrigin||null,distanceM:0,maxSpeedMps:0,maxAglM:Math.max(0,Number(sample.agl)||0),maxAltitudeM:z,maxForwardMps:0,maxRightMps:0,navDegradedS:0,batteryStartV:battery,batteryEndV:battery,batteryMinV:battery,lastPosition:finite(Number(sample.x),Number(sample.y),z)?[Number(sample.x),Number(sample.y),z]:null,path:[],samples:0};this.record(sample,true);}
  record(sample,forcePath=false){const f=this.active;if(!f)return;const t=Number(sample.simTime)||0,x=Number(sample.x),y=Number(sample.y),z=Number(sample.z),speed=Math.max(0,Number(sample.speed)||0),agl=Math.max(0,Number(sample.agl)||0),battery=Number(sample.batteryV)||f.batteryEndV,dt=Math.max(0,t-f.lastSim);if(t+1e-6<f.lastSim){this.finish("SIM_RESET",sample);return;}if(sample.navDegraded)f.navDegradedS+=dt;if(finite(x,y,z)&&f.lastPosition){const step=Math.hypot(x-f.lastPosition[0],y-f.lastPosition[1],z-f.lastPosition[2]);if(step<25)f.distanceM+=step;f.lastPosition=[x,y,z];}else if(finite(x,y,z))f.lastPosition=[x,y,z];const body=bodyVelocity(sample);f.maxSpeedMps=Math.max(f.maxSpeedMps,speed);if(sample.aglValid!==false)f.maxAglM=Math.max(f.maxAglM,agl);f.maxAltitudeM=Math.max(f.maxAltitudeM,z);f.maxForwardMps=Math.max(f.maxForwardMps,Math.abs(body.forward));f.maxRightMps=Math.max(f.maxRightMps,Math.abs(body.right));f.batteryEndV=battery;f.batteryMinV=f.samples?Math.min(f.batteryMinV,battery):battery;f.samples++;f.lastSim=t;if(forcePath||t-f.lastPathSim>=PATH_INTERVAL_S){f.lastPathSim=t;if(f.path.length<MAX_PATH_POINTS)f.path.push({t:+(t-f.simStart).toFixed(2),x:+(x||0).toFixed(2),y:+(y||0).toFixed(2),z:+(z||0).toFixed(2),agl:sample.aglValid===false?null:+agl.toFixed(2),navDegraded:Boolean(sample.navDegraded)});}}
  observe(sample){const armed=Boolean(sample.armed);if(armed&&!this.lastArmed)this.begin(sample);if(armed&&this.active)this.record(sample);if(!armed&&this.lastArmed&&this.active)this.finish(sample.disarmReason||"FC_DISARM",sample);this.lastArmed=armed;}
  finish(reason="RUN_STOPPED",sample=null){if(!this.active){this.lastArmed=false;return null;}if(sample)this.record(sample,true);const f=this.active;f.endedAt=new Date().toISOString();f.durationS=Math.max(0,f.lastSim-f.simStart);f.endReason=String(reason||"FC_DISARM");for(const key of ["lastPosition","lastPathSim","lastSim","simStart"])delete f[key];for(const key of ["distanceM","maxSpeedMps","maxAglM","maxAltitudeM","maxForwardMps","maxRightMps","navDegradedS","batteryStartV","batteryEndV","batteryMinV"])f[key]=+(Number(f[key])||0).toFixed(3);this.entries=[{...f},...this.entries].slice(0,MAX_FLIGHTS);saveEntries(this.entries);this.active=null;this.lastArmed=false;this.render();return f;}
  snapshot(){return{active:this.active?structuredClone(this.active):null,entries:structuredClone(this.entries)};}
}
