import * as THREE from "three";
import {AUDIO_SETTINGS_EVENT,loadAudioSettings,normalizeAudioSettings} from "./audio_settings.mjs";

const SHOT_INTERVAL_MS=110;
const DECAL_POOL_SIZE=32;
const SCREEN_IMPACT_POOL_SIZE=8;
const PROJECTILE_POOL_SIZE=64;
const zAxis=new THREE.Vector3(0,0,1),normal=new THREE.Vector3(0,0,1),point=new THREE.Vector3(),projected=new THREE.Vector3(),pointerNdc=new THREE.Vector2();

export function installFlightFireFx({viewport,scene,camera,worldBridge,isEnabled=()=>true,isPointerEnabled=()=>true,onRecoil=()=>{}}={}){
  if(!viewport||!scene||!camera)return null;
  let active=null,fireTimer=0,nextShotAt=0,decalCursor=0,screenImpactCursor=0,audioCtx=null,audioSettings=normalizeAudioSettings(loadAudioSettings());
  const raycaster=new THREE.Raycaster();
  const decals=[];
  const decalGeometry=new THREE.CircleGeometry(.035,8),decalMaterial=new THREE.MeshBasicMaterial({color:0x171717,transparent:true,opacity:.9,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-4,side:THREE.DoubleSide});
  for(let i=0;i<DECAL_POOL_SIZE;i++){const mesh=new THREE.Mesh(decalGeometry,decalMaterial);mesh.visible=false;mesh.renderOrder=8;mesh.userData.flightFireIgnore=true;mesh.userData.flightFireDecal=true;mesh.userData.flightFireWorld=false;scene.add(mesh);decals.push(mesh);}

  const style=document.createElement("style");style.textContent=`#viewport{touch-action:none;overscroll-behavior:none}.flight-fire-impact{position:absolute;z-index:16;width:13px;height:13px;margin:-6.5px 0 0 -6.5px;border-radius:50%;border:1px solid #fff7c2;background:radial-gradient(circle,#fff9be 0 16%,#ffbf55 22%,#ff6d35aa 42%,transparent 68%);box-shadow:0 0 12px #ffb14a;pointer-events:none;display:none}.flight-fire-impact.active{display:block;animation:flightImpactFade .34s ease-out forwards}.xbox-crosshair{position:absolute;left:50%;top:50%;width:22px;height:22px;transform:translate(-50%,-50%);z-index:15;pointer-events:none;display:none}.xbox-crosshair:before,.xbox-crosshair:after{content:"";position:absolute;background:#f7fbff;box-shadow:0 0 3px #000}.xbox-crosshair:before{left:10px;top:2px;width:2px;height:18px}.xbox-crosshair:after{left:2px;top:10px;width:18px;height:2px}.combat-damage-vignette{position:absolute;inset:0;z-index:14;pointer-events:none;opacity:0;background:radial-gradient(circle,transparent 55%,#c91515aa 100%);transition:opacity .18s}.combat-damage-vignette.hit{opacity:1}@keyframes flightImpactFade{from{opacity:1;transform:scale(.65)}to{opacity:0;transform:scale(1.55)}}`;document.head.appendChild(style);
  const screenImpacts=Array.from({length:SCREEN_IMPACT_POOL_SIZE},()=>{const el=document.createElement("i");el.className="flight-fire-impact";el.addEventListener("animationend",()=>el.classList.remove("active"));viewport.appendChild(el);return el;});
  const gamepadCrosshair=document.createElement("div");gamepadCrosshair.className="xbox-crosshair";viewport.appendChild(gamepadCrosshair);
  const damageVignette=document.createElement("div");damageVignette.className="combat-damage-vignette";viewport.appendChild(damageVignette);
  let damageTimer=0;

  function combat(){return globalThis.__arondightBox3dCombat||null;}
  function flightMode(){return globalThis.__arondightWalkMode?.mode!=="foot"&&!document.body.classList.contains("on-foot-mode");}
  function blocked(target){return target instanceof Element&&Boolean(target.closest("button,input,select,textarea,dialog,#soloTopbar,#soloLeft,#soloRight,#soloClearance,#footHud,#worldLookHud"));}
  function syncAudio(next=loadAudioSettings()){audioSettings=normalizeAudioSettings(next);viewport.dataset.fireAudioEnabled=audioSettings.soundEnabled?"1":"0";viewport.dataset.fireShotsVolumePct=String(audioSettings.shotsVolume);viewport.dataset.fireFxVolumePct=String(audioSettings.fxVolume);}
  syncAudio();
  const audioSettingsListener=e=>syncAudio(e.detail);window.addEventListener(AUDIO_SETTINGS_EVENT,audioSettingsListener);
  function ensureAudio(){if(audioCtx)return audioCtx;const Ctx=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Ctx)return null;try{audioCtx=new Ctx({latencyHint:"interactive"});}catch{}return audioCtx;}
  function shotSound(){if(!audioSettings.soundEnabled||audioSettings.shotsVolume<=0)return;const ctx=ensureAudio();if(!ctx)return;try{if(ctx.state==="suspended")ctx.resume();const t=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter();o.type="square";o.frequency.setValueAtTime(235,t);o.frequency.exponentialRampToValueAtTime(60,t+.075);f.type="bandpass";f.frequency.value=850;g.gain.setValueAtTime(.075*audioSettings.shotsVolume/100,t);g.gain.exponentialRampToValueAtTime(.0001,t+.09);o.connect(f).connect(g).connect(ctx.destination);o.start(t);o.stop(t+.10);}catch{}}
  function hitConfirmSound(){if(!audioSettings.soundEnabled||audioSettings.fxVolume<=0)return;const ctx=ensureAudio();if(!ctx)return;try{if(ctx.state==="suspended")ctx.resume();const t=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain();o.type="sine";o.frequency.setValueAtTime(860,t);o.frequency.exponentialRampToValueAtTime(1180,t+.055);g.gain.setValueAtTime(.035*audioSettings.fxVolume/100,t);g.gain.exponentialRampToValueAtTime(.0001,t+.07);o.connect(g).connect(ctx.destination);o.start(t);o.stop(t+.08);}catch{}}
  function damageListener(){viewport.dataset.combatDamageFx=String((Number(viewport.dataset.combatDamageFx)||0)+1);damageVignette.classList.add("hit");clearTimeout(damageTimer);damageTimer=setTimeout(()=>damageVignette.classList.remove("hit"),180);}
  function hitConfirmListener(){viewport.dataset.combatHitConfirmFx=String((Number(viewport.dataset.combatHitConfirmFx)||0)+1);hitConfirmSound();}
  window.addEventListener("arondight:combat-damage",damageListener);window.addEventListener("arondight:combat-hit-confirm",hitConfirmListener);

  function addThreeDecal(detail){const mesh=decals[decalCursor++%decals.length],p=detail?.point||{};point.set(Number(p.x)||0,Number(p.y)||0,Number(p.z)||0);const n=detail?.normal||{};normal.set(Number(n.x)||0,Number(n.y)||0,Number(n.z)||1);if(normal.lengthSq()<1e-5)normal.set(0,0,1);normal.normalize();mesh.position.copy(point).addScaledVector(normal,.006);mesh.quaternion.setFromUnitVectors(zAxis,normal);mesh.visible=true;mesh.userData.flightFireWorld=Boolean(worldBridge?.active);viewport.dataset.fireDecalWrites=String((Number(viewport.dataset.fireDecalWrites)||0)+1);}
  function aimPoint(){const rect=viewport.getBoundingClientRect();if(active?.source==="gamepad"){const x=rect.width*.5,y=rect.height*.5;return{x,y,rect};}const screenRect=rect,rotated=viewport.dataset.soloOrientation==="css-landscape";const x=rotated?active.clientY-screenRect.top:active.clientX-screenRect.left;const y=rotated?screenRect.right-active.clientX:active.clientY-screenRect.top;return{x:Math.max(0,Math.min(viewport.clientWidth,x)),y:Math.max(0,Math.min(viewport.clientHeight,y)),rect};}
  function showScreenImpact(detail){const el=screenImpacts[screenImpactCursor++%screenImpacts.length],p=detail?.point;if(!p)return;projected.set(Number(p.x)||0,Number(p.y)||0,Number(p.z)||0).project(camera);if(!Number.isFinite(projected.x)||!Number.isFinite(projected.y)||projected.z<-1||projected.z>1)return;el.style.left=`${(projected.x*.5+.5)*viewport.clientWidth}px`;el.style.top=`${(-projected.y*.5+.5)*viewport.clientHeight}px`;el.classList.remove("active");void el.offsetWidth;el.classList.add("active");}
  function impactListener(event){const detail=event.detail||{};if(detail.source!=="drone"&&detail.source!=="gamepad")return;addThreeDecal(detail);showScreenImpact(detail);viewport.dataset.fireProjectileImpacts=String((Number(viewport.dataset.fireProjectileImpacts)||0)+1);viewport.dispatchEvent(new CustomEvent("flight-fire-impact",{detail}));}
  window.addEventListener("arondight:box3d-impact",impactListener);

  function fire(now=performance.now()){
    if(!active||!flightMode()||!isEnabled()||now+.25<nextShotAt)return false;nextShotAt=now+SHOT_INTERVAL_MS;const aim=aimPoint();pointerNdc.set(aim.x/Math.max(1,viewport.clientWidth)*2-1,-aim.y/Math.max(1,viewport.clientHeight)*2+1);raycaster.setFromCamera(pointerNdc,camera);const physics=combat();if(!physics?.fire)return false;physics.fire({origin:[raycaster.ray.origin.x,raycaster.ray.origin.y,raycaster.ray.origin.z],direction:[raycaster.ray.direction.x,raycaster.ray.direction.y,raycaster.ray.direction.z],speed:390,source:active.source==="gamepad"?"gamepad":"drone",weapon:"drone-gun",damage:50,replicate:true});shotSound();try{onRecoil(.16);}catch{}viewport.dataset.fireShots=String((Number(viewport.dataset.fireShots)||0)+1);viewport.dataset.fireAimX=aim.x.toFixed(2);viewport.dataset.fireAimY=aim.y.toFixed(2);viewport.dataset.fireAimMode=active.source==="gamepad"?"center-fixed":"touch-1to1";viewport.dataset.fireInputSource=active.source||"pointer";viewport.dataset.fireProjectileModel="box3d-isBullet-ccd-v1";return true;
  }
  function scheduleFire(){if(!active||fireTimer)return;const tick=()=>{fireTimer=0;if(!active)return;fire(performance.now());fireTimer=setTimeout(tick,Math.max(5,nextShotAt-performance.now()+1));};fireTimer=setTimeout(tick,Math.max(5,nextShotAt-performance.now()+1));}
  function stop(event){if(event&&active?.source!=="gamepad"&&event.pointerId!==active?.id)return;if(event&&active?.source!=="gamepad")try{viewport.releasePointerCapture?.(event.pointerId);}catch{}active=null;if(fireTimer){clearTimeout(fireTimer);fireTimer=0;}}
  function move(event){if(!active||active.source==="gamepad"||event.pointerId!==active.id)return;active.clientX=event.clientX;active.clientY=event.clientY;fire(performance.now());scheduleFire();event.preventDefault();}
  viewport.addEventListener("pointerdown",event=>{if(!flightMode()||!isEnabled()||!isPointerEnabled()||event.button!==0||blocked(event.target)||active)return;active={id:event.pointerId,source:"pointer",clientX:event.clientX,clientY:event.clientY};try{viewport.setPointerCapture?.(event.pointerId);}catch{}nextShotAt=0;fire(performance.now());scheduleFire();event.preventDefault();},{passive:false});
  viewport.addEventListener("pointermove",move,{passive:false});viewport.addEventListener("pointerup",stop,{passive:false});viewport.addEventListener("pointercancel",stop,{passive:false});
  function setGamepadAim(enabled){const on=Boolean(enabled)&&flightMode();gamepadCrosshair.style.display=on?"block":"none";viewport.dataset.xboxAimCrosshair=on?"1":"0";}
  function setGamepadFire(enabled){const on=Boolean(enabled)&&flightMode();if(on){if(!active||active.source!=="gamepad"){active={id:-1,source:"gamepad",clientX:0,clientY:0};nextShotAt=0;fire(performance.now());scheduleFire();}}else if(active?.source==="gamepad")stop();}

  viewport.dataset.fireAimMode="touch-1to1";viewport.dataset.fireCrosshairMode="center-fixed";viewport.dataset.fireDecalPoolSize=String(DECAL_POOL_SIZE);viewport.dataset.fireProjectilePoolSize=String(PROJECTILE_POOL_SIZE);viewport.dataset.fireDecalWrites=viewport.dataset.fireDecalWrites||"0";viewport.dataset.fireProjectileImpacts=viewport.dataset.fireProjectileImpacts||"0";viewport.dataset.fireProjectileModel="box3d-isBullet-ccd-v1";
  return{stop,setGamepadAim,setGamepadFire,get decalPoolSize(){return decals.length;},get decalWrites(){return Number(viewport.dataset.fireDecalWrites||0);},get projectilePoolSize(){return PROJECTILE_POOL_SIZE;},get activeProjectiles(){return Number(viewport.dataset.box3dActiveBullets||0);},dispose(){stop();window.removeEventListener("arondight:box3d-impact",impactListener);window.removeEventListener("arondight:combat-damage",damageListener);window.removeEventListener("arondight:combat-hit-confirm",hitConfirmListener);window.removeEventListener(AUDIO_SETTINGS_EVENT,audioSettingsListener);gamepadCrosshair.remove();damageVignette.remove();for(const el of screenImpacts)el.remove();for(const mesh of decals)mesh.parent?.remove(mesh);decalGeometry.dispose();decalMaterial.dispose();style.remove();try{audioCtx?.close();}catch{}}};
}
