import * as THREE from "three";
import {normalizedPointer,endPointerDrag,knobPercent} from "./control_semantics.mjs";
import {traceProjectileWorldSegment,createProjectileHit} from "./projectile_ballistics.mjs";

const MODE_KEY="arondight45PlayerModeV2";
const EYE_Z=1.68;
const WALK_MPS=4.4;
const SPRINT_MPS=6.8;
const LOOK_YAW_RAD_S=2.65;
const LOOK_PITCH_RAD_S=2.05;
const LOOK_DEADZONE=.055;
const FIRE_INTERVAL_MS=155;
const PLAYER_RADIUS=.28;
const MAX_SHOT_M=150;
const MAX_DECALS=20;

let installed=false,active=false,initialized=false,bridgeHooked=null,baseApplyLook=null,lastFrame=performance.now(),lastShot=-Infinity,fireHeld=false,xboxPrevY=false;
const position=new THREE.Vector3(0,0,EYE_Z),direction=new THREE.Vector3(),endPoint=new THREE.Vector3(),target=new THREE.Vector3(),normal=new THREE.Vector3(),decalForward=new THREE.Vector3(0,0,1);
const raycaster=new THREE.Raycaster(),worldHit=createProjectileHit();
const touch={move:{x:0,y:0},look:{x:0,y:0},movePointer:null,lookPointer:null};
const keys=new Set();
let yaw=0,pitch=0,decals=null,decalCursor=0,audio=null,weaponKickUntil=0;

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function clamp(v,lo,hi){return Math.max(lo,Math.min(hi,Number(v)||0));}
function axis(v,dz=.14){const x=clamp(v,-1,1),a=Math.abs(x);return a<=dz?0:Math.sign(x)*(a-dz)/(1-dz);}
function button(pad,index){const b=pad?.buttons?.[index];return clamp(typeof b==="number"?b:(b?.value??(b?.pressed?1:0)),0,1);}
function gamepad(){return Array.from(navigator.getGamepads?.()||[]).find(p=>p?.connected&&(p.mapping==="standard"||/xbox|xinput|045e/i.test(String(p.id||""))))||null;}
function pointInRing(x,y,ring){let inside=false;if(!Array.isArray(ring)||ring.length<3)return false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j],ax=Number(a?.[0]),ay=Number(a?.[1]),bx=Number(b?.[0]),by=Number(b?.[1]);if(![ax,ay,bx,by].every(Number.isFinite))continue;if((ay>y)!==(by>y)&&x<(bx-ax)*(y-ay)/((by-ay)||1e-12)+ax)inside=!inside;}return inside;}
function insideBuilding(x,y){for(const prism of bridge()?.buildingCollisionSnapshot?.prisms||[]){if(Number(prism?.top)<=.15||Number(prism?.base)>=EYE_Z||!Array.isArray(prism?.points))continue;if(pointInRing(x,y,prism.points))return true;}return false;}
function walkable(x,y){if(insideBuilding(x,y))return false;for(const [dx,dy] of [[PLAYER_RADIUS,0],[-PLAYER_RADIUS,0],[0,PLAYER_RADIUS],[0,-PLAYER_RADIUS]])if(insideBuilding(x+dx,y+dy))return false;return true;}
function safeSpawnNear(x,y){const candidates=[[0,-1.6],[0,1.6],[-1.6,0],[1.6,0],[0,0],[-2.5,-2.5],[2.5,-2.5],[-2.5,2.5],[2.5,2.5],[0,-4],[0,4],[-4,0],[4,0]];for(const [dx,dy] of candidates)if(walkable(x+dx,y+dy))return[x+dx,y+dy];return[x,y];}
function initialize(){if(initialized)return true;const b=bridge(),scene=b?.threeScene,airframe=scene?(b.airframeFor?.(scene)||b.airframe):null,p=airframe?.position;if(!p)return false;const [x,y]=safeSpawnNear(Number(p.x)||0,Number(p.y)||0);position.set(x,y,EYE_Z);yaw=0;pitch=0;initialized=true;const v=viewport();if(v){v.dataset.footX=x.toFixed(3);v.dataset.footY=y.toFixed(3);}return true;}
function dirFromAngles(){const cp=Math.cos(pitch);return direction.set(Math.sin(yaw)*cp,Math.cos(yaw)*cp,Math.sin(pitch)).normalize();}
function visibleInHierarchy(object){for(let n=object;n;n=n.parent)if(n.visible===false)return false;return true;}
function populationKind(object){for(let n=object;n;n=n.parent){const kind=String(n.userData?.worldPopulationKind||"");if(kind==="person"||kind==="car")return kind;}return"";}
function ensureDecals(){if(decals)return decals;const scene=bridge()?.threeScene;if(!scene)return null;const geometry=new THREE.CircleGeometry(.026,10),material=new THREE.MeshBasicMaterial({color:0x171717,transparent:true,opacity:.92,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-4,polygonOffsetUnits:-4,side:THREE.DoubleSide});decals=Array.from({length:MAX_DECALS},()=>{const mesh=new THREE.Mesh(geometry,material);mesh.visible=false;mesh.renderOrder=18;mesh.userData.flightFireIgnore=true;mesh.userData.footBulletDecal=true;scene.add(mesh);return mesh;});return decals;}
function addDecal(hit){const pool=ensureDecals();if(!pool||!hit?.point)return;const mesh=pool[decalCursor++%pool.length],n=hit.normal||hit.worldNormal;if(!n)return;normal.set(Number(n.x)||0,Number(n.y)||0,Number(n.z)||1).normalize();mesh.position.set(hit.point.x,hit.point.y,hit.point.z).addScaledVector(normal,.0035);mesh.quaternion.setFromUnitVectors(decalForward,normal);mesh.rotateZ((decalCursor*2.3999632297)%6.283185307);mesh.visible=true;const v=viewport();if(v)v.dataset.footDecals=String((Number(v.dataset.footDecals)||0)+1);}
function ensureAudio(){if(audio)return audio;const Ctx=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Ctx)return null;try{audio=new Ctx({latencyHint:"interactive"});return audio;}catch{return null;}}
function shotSound(){const ctx=ensureAudio();if(!ctx)return;try{if(ctx.state==="suspended")ctx.resume().catch(()=>{});const t=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain();o.type="triangle";o.frequency.setValueAtTime(185,t);o.frequency.exponentialRampToValueAtTime(65,t+.075);g.gain.setValueAtTime(.10,t);g.gain.exponentialRampToValueAtTime(.0001,t+.09);o.connect(g).connect(ctx.destination);o.start(t);o.stop(t+.10);}catch{}}
function fire(now=performance.now()){
  if(!active||now-lastShot<FIRE_INTERVAL_MS||!initialize())return false;lastShot=now;weaponKickUntil=now+105;shotSound();const b=bridge(),scene=b?.threeScene;if(!scene)return false;const dir=dirFromAngles().clone(),origin=position.clone(),far=endPoint.copy(origin).addScaledVector(dir,MAX_SHOT_M),candidates=[];scene.traverse(object=>{if(object?.isMesh&&visibleInHierarchy(object)&&populationKind(object)&&!object.userData?.worldRagdollPart)candidates.push(object);});raycaster.set(origin,dir);raycaster.far=MAX_SHOT_M;const sceneHit=raycaster.intersectObjects(candidates,false)[0]||null,world=traceProjectileWorldSegment(b.buildingCollisionSnapshot,origin,far,worldHit),sceneDistance=Number(sceneHit?.distance),worldDistance=Number(world?.distanceM),takePopulation=sceneHit&&Number.isFinite(sceneDistance)&&(!world||sceneDistance<=worldDistance+.02);let handled=false;if(takePopulation)handled=Boolean(b.registerWorldPopulationHit?.(sceneHit));else if(world)addDecal({point:world.point,normal:world.normal});const v=viewport();if(v){v.dataset.footShots=String((Number(v.dataset.footShots)||0)+1);if(handled)v.dataset.footPopulationHits=String((Number(v.dataset.footPopulationHits)||0)+1);}return true;
}
function applyCamera(camera){if(!active||!initialize())return false;camera.position.copy(position);camera.up.set(0,0,1);target.copy(position).addScaledVector(dirFromAngles(),4);camera.lookAt(target);camera.updateMatrixWorld?.(true);return true;}
function step(now=performance.now()){
  if(!active||!initialize()){lastFrame=now;return;}const dt=clamp((now-lastFrame)/1000,0,.05);lastFrame=now;let mx=touch.move.x,my=touch.move.y,lx=touch.look.x,ly=touch.look.y,sprint=keys.has("ShiftLeft")||keys.has("ShiftRight");mx+=(keys.has("KeyD")?1:0)-(keys.has("KeyA")?1:0);my+=(keys.has("KeyS")?1:0)-(keys.has("KeyW")?1:0);const pad=gamepad();if(pad){mx+=axis(pad.axes?.[0]);my+=axis(pad.axes?.[1]);lx+=axis(pad.axes?.[2]);ly+=axis(pad.axes?.[3]);sprint=sprint||button(pad,10)>.5;if(button(pad,7)>.55)fire(now);const y=button(pad,3)>.55;if(y&&!xboxPrevY){setActive(false);xboxPrevY=true;return;}xboxPrevY=y;}else xboxPrevY=false;
  if(Math.abs(lx)>LOOK_DEADZONE)yaw-=lx*LOOK_YAW_RAD_S*dt;if(Math.abs(ly)>LOOK_DEADZONE)pitch=clamp(pitch-ly*LOOK_PITCH_RAD_S*dt,-1.28,1.28);
  const len=Math.max(1,Math.hypot(mx,my)),forward=-my/len,strafe=mx/len,speed=sprint?SPRINT_MPS:WALK_MPS,dx=(Math.sin(yaw)*forward+Math.cos(yaw)*strafe)*speed*dt,dy=(Math.cos(yaw)*forward-Math.sin(yaw)*strafe)*speed*dt,nx=position.x+dx,ny=position.y+dy;if(walkable(nx,position.y))position.x=nx;if(walkable(position.x,ny))position.y=ny;position.z=EYE_Z;if(fireHeld)fire(now);const v=viewport();if(v){v.dataset.footX=position.x.toFixed(3);v.dataset.footY=position.y.toFixed(3);v.dataset.footYaw=yaw.toFixed(4);v.dataset.footPitch=pitch.toFixed(4);v.dataset.footCollision=walkable(position.x,position.y)?"clear":"blocked";}const weapon=document.getElementById("footWeapon");weapon?.classList.toggle("kick",now<weaponKickUntil);
}
function hookBridge(){const b=bridge();if(!b||b===bridgeHooked||typeof b.applyLookCamera!=="function")return false;if(bridgeHooked&&baseApplyLook)bridgeHooked.applyLookCamera=baseApplyLook;bridgeHooked=b;baseApplyLook=b.applyLookCamera.bind(b);b.applyLookCamera=(scene,camera)=>{if(active){step(performance.now());applyCamera(camera);return;}return baseApplyLook(scene,camera);};b.applyLookCamera.__isolatedFootMode=true;return true;}
function resetStick(kind){touch[kind].x=0;touch[kind].y=0;const el=document.getElementById(kind==="move"?"soloLeft":"soloRight"),knob=el?.querySelector(".solo-knob");if(knob){knob.style.left="50%";knob.style.top="50%";}}
function renderMode(){document.body.classList.toggle("on-foot-mode",active);globalThis.__arondightOnFootMode=active;const v=viewport();if(v)v.dataset.playerMode=active?"foot":"drone";const button=document.getElementById("playerModeButton");if(button)button.textContent=active?"WALK ✓":"DRONE ✓";const left=document.querySelector("#soloLeft span"),right=document.querySelector("#soloRight span");if(left)left.textContent=active?"MOVE":"FWD / STRAFE";if(right)right.textContent=active?"LOOK":"TURN / PITCH";}
export function setActive(value,{persist=true}={}){active=Boolean(value);if(persist)try{localStorage.setItem(MODE_KEY,active?"foot":"drone");}catch{}if(active){initialize();lastFrame=performance.now();for(const id of ["soloLeft","soloRight"]){const el=document.getElementById(id);try{el?.dispatchEvent(new PointerEvent("pointercancel",{pointerId:-1,bubbles:false,cancelable:true}));}catch{}}}else{fireHeld=false;resetStick("move");resetStick("look");}renderMode();return active;}
function mountUi(){const top=document.getElementById("soloTopbar"),v=viewport();if(!top||!v)return false;if(!document.getElementById("playerModeButton")){const button=document.createElement("button");button.id="playerModeButton";button.type="button";button.textContent="DRONE ✓";button.addEventListener("click",()=>setActive(!active));top.insertBefore(button,document.getElementById("soloCamera")||null);}if(!document.getElementById("footFire")){const fireButton=document.createElement("button");fireButton.id="footFire";fireButton.type="button";fireButton.textContent="FIRE";fireButton.addEventListener("pointerdown",event=>{if(!active)return;fireHeld=true;fire(performance.now());fireButton.setPointerCapture?.(event.pointerId);event.preventDefault();event.stopPropagation();});for(const type of ["pointerup","pointercancel","lostpointercapture"])fireButton.addEventListener(type,event=>{fireHeld=false;if(active){event.preventDefault();event.stopPropagation();}});v.appendChild(fireButton);const weapon=document.createElement("div");weapon.id="footWeapon";weapon.setAttribute("aria-hidden","true");weapon.innerHTML='<i class="foot-slide"></i><i class="foot-frame"></i><i class="foot-grip"></i><i class="foot-flash"></i>';v.appendChild(weapon);}renderMode();return true;}
function ownStick(id,kind){const el=document.getElementById(id);if(!el||el.dataset.footOwned)return;el.dataset.footOwned="1";let pointer=null;const apply=event=>{if(!active||event.pointerId!==pointer)return;const p=normalizedPointer(el,event);touch[kind].x=clamp(p.x,-1,1);touch[kind].y=clamp(p.y,-1,1);const knob=el.querySelector(".solo-knob");if(knob){knob.style.left=`${knobPercent(touch[kind].x)}%`;knob.style.top=`${knobPercent(touch[kind].y)}%`;}event.preventDefault();event.stopImmediatePropagation();};el.addEventListener("pointerdown",event=>{if(!active)return;pointer=event.pointerId;touch[kind+"Pointer"]=pointer;el.setPointerCapture?.(pointer);normalizedPointer(el,event);event.preventDefault();event.stopImmediatePropagation();},{capture:true,passive:false});el.addEventListener("pointermove",apply,{capture:true,passive:false});const release=event=>{if(!active||pointer===null||(event.pointerId!=null&&event.pointerId!==pointer))return;endPointerDrag(el,pointer);pointer=null;resetStick(kind);event.preventDefault();event.stopImmediatePropagation();};for(const type of ["pointerup","pointercancel","lostpointercapture"])el.addEventListener(type,release,{capture:true,passive:false});}
function installInput(){addEventListener("keydown",event=>{if(!active||event.metaKey||event.ctrlKey||event.altKey)return;if(["KeyW","KeyA","KeyS","KeyD","ShiftLeft","ShiftRight"].includes(event.code)){keys.add(event.code);event.preventDefault();}else if(event.code==="KeyV"){setActive(false);event.preventDefault();}else if(event.code==="Space"){fire(performance.now());event.preventDefault();}});addEventListener("keyup",event=>keys.delete(event.code));addEventListener("mousemove",event=>{if(!active||document.pointerLockElement!==viewport())return;yaw-=event.movementX*.0022;pitch=clamp(pitch-event.movementY*.0022,-1.28,1.28);});viewport()?.addEventListener("pointerdown",event=>{if(!active)return;const targetEl=event.target instanceof Element?event.target:null;if(targetEl?.closest("#soloTopbar,#soloLeft,#soloRight,#footFire,dialog,#worldLookHud"))return;if(event.pointerType==="mouse"&&document.pointerLockElement!==viewport())viewport()?.requestPointerLock?.();event.preventDefault();event.stopImmediatePropagation();},{capture:true,passive:false});}
function installStyle(){if(document.querySelector("style[data-foot-mode]"))return;const style=document.createElement("style");style.dataset.footMode="isolated-v1";style.textContent=`
#playerModeButton{background:#174f70dd!important}body.on-foot-mode #playerModeButton{background:#6a491bdd!important;border-color:#ffd37d!important}
#footFire,#footWeapon{display:none}body.on-foot-mode #footFire{display:block;position:absolute;z-index:12;right:max(30px,calc(var(--solo-safe-right) + min(25vw,150px) + 24px));bottom:max(34px,calc(var(--solo-safe-bottom) + 14px));width:72px;height:72px;border-radius:50%;border:2px solid #ffd37daa;background:#6a341ddd;color:#fff4db;font:900 12px system-ui;pointer-events:auto;touch-action:none;box-shadow:0 5px 20px #0008}
body.on-foot-mode #soloClearance,body.on-foot-mode #soloArm,body.on-foot-mode #soloKill{display:none!important}body.on-foot-mode .solo-stick{display:block!important;z-index:11}body.on-foot-mode #soloLeft,body.on-foot-mode #soloRight{pointer-events:auto!important;opacity:1!important}
body.on-foot-mode #footWeapon{display:block;position:absolute;z-index:10;right:10%;bottom:-8px;width:170px;height:135px;pointer-events:none;filter:drop-shadow(0 10px 12px #0008);transform-origin:75% 100%}#footWeapon i{position:absolute;display:block}.foot-slide{right:12px;top:14px;width:108px;height:34px;border-radius:6px;background:linear-gradient(#8492a1,#394754 55%,#202b35);border:1px solid #bbc6cf44}.foot-frame{right:25px;top:44px;width:84px;height:38px;border-radius:5px 8px;background:#17232d;border:1px solid #6d7b8633}.foot-grip{right:35px;top:70px;width:38px;height:67px;border-radius:5px 8px 12px;background:repeating-linear-gradient(155deg,#18232c 0 6px,#293843 6px 10px);transform:skewX(-12deg)}.foot-flash{right:-13px;top:13px;width:38px;height:38px;opacity:0;background:radial-gradient(circle,#fff9ce 0 15%,#ffd45b 18% 35%,#ff7d21 40% 58%,transparent 63%);border-radius:50%}#footWeapon.kick{transform:translate(-4px,6px) rotate(-3deg)}#footWeapon.kick .foot-flash{opacity:1}
@media(max-height:340px){body.on-foot-mode #footFire{width:58px;height:58px;right:max(22px,calc(var(--solo-safe-right) + min(22vw,128px) + 18px));bottom:max(20px,var(--solo-safe-bottom));font-size:10px}body.on-foot-mode #footWeapon{transform:scale(.82);right:8%}}
`;document.head.appendChild(style);}
function tick(){hookBridge();mountUi();ownStick("soloLeft","move");ownStick("soloRight","look");const solo=document.body.classList.contains("solo-flight");if(solo&&!viewport()?.dataset.footInitialModeApplied){viewport().dataset.footInitialModeApplied="1";let stored="foot";try{stored=localStorage.getItem(MODE_KEY)||"foot";}catch{}setActive(!navigator.webdriver&&stored!=="drone",{persist:false});}requestAnimationFrame(tick);}
export function installFootMode(){if(installed)return;installed=true;installStyle();installInput();globalThis.__arondightFootMode=Object.freeze({get active(){return active;},setActive,fire,get position(){return position;}});requestAnimationFrame(tick);}
installFootMode();
