let installed=false,lastGun=null,patched=0,postFrameQueued=false;
function viewport(){return document.getElementById("viewport");}
function patchMaterial(material){if(!material)return;const list=Array.isArray(material)?material:[material];for(const mat of list){if(!mat)continue;mat.depthTest=true;mat.depthWrite=false;mat.needsUpdate=true;}}
function patchWeaponDepth(){const scene=globalThis.__arondightRealWorld?.threeScene,gun=scene?.getObjectByName?.("WALK_PISTOL_3D");if(!gun)return false;const flash=gun.getObjectByName?.("FINAL_MUZZLE_FLASH")||gun.getObjectByName?.("WALK_MUZZLE_FLASH");if(!flash)return false;if(gun!==lastGun||!flash.userData?.finalDepthPatched){lastGun=gun;flash.userData.finalDepthPatched=true;flash.renderOrder=9996;flash.traverse?.(node=>{if(!node?.isMesh)return;node.renderOrder=9996;patchMaterial(node.material);});patched++;}const view=viewport();if(view){view.dataset.walkMuzzleDepth="depth-tested-behind-viewmodel-v2";view.dataset.walkMuzzleDepthPatches=String(patched);view.dataset.walkFireButton="compact-visible+world-tap-v2";}return true;}
function installStyle(){if(document.querySelector("style[data-gameplay-final-realism]"))return;const style=document.createElement("style");style.dataset.gameplayFinalRealism="v3";style.textContent=`
body.on-foot-mode #footFire{display:block!important;width:clamp(68px,9vw,80px)!important;height:clamp(68px,9vw,80px)!important;right:calc(max(10px,var(--solo-safe-right,env(safe-area-inset-right))) + min(25vw,148px) + 12px)!important;bottom:max(18px,calc(var(--solo-safe-bottom,env(safe-area-inset-bottom)) + 12px))!important;font-size:10px!important;z-index:7!important;opacity:.88!important}
@media(max-height:340px){body.on-foot-mode #footFire{width:62px!important;height:62px!important;right:calc(max(8px,var(--solo-safe-right,env(safe-area-inset-right))) + min(22vw,124px) + 9px)!important;bottom:max(10px,var(--solo-safe-bottom,env(safe-area-inset-bottom)))!important;font-size:9px!important}}
`;document.head.appendChild(style);}
function settleFrameContract(){postFrameQueued=false;patchWeaponDepth();}
function frame(){patchWeaponDepth();if(!postFrameQueued){postFrameQueued=true;setTimeout(settleFrameContract,0);}requestAnimationFrame(frame);}
export function installGameplayFinalRealismPatch(){if(installed)return;installed=true;installStyle();const view=viewport();if(view){view.dataset.gameplayFinalRealism="muzzle-depth+compact-fire-v3";view.dataset.walkFireButton="compact-visible+world-tap-v2";}requestAnimationFrame(frame);}
installGameplayFinalRealismPatch();
