import * as THREE from "three";
import {Box3dHitscanWorld} from "./box3d_hitscan.mjs";

const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
const MISSILE_TTL_MS=5200;
const MISSILE_SPEED_MPS=36;
const MISSILE_TURN_RESPONSE=8.5;
const MISSILE_RADIUS_M=8;
const RESERVED="#soloTopbar,#soloLeft,#soloRight,#soloClearance,.solo-action,.phone-settings-dialog,#wantedEmpButton,#droneWeaponToggle,dialog,button,input,select,textarea,a,label";
const raycaster=new THREE.Raycaster(),ndc=new THREE.Vector2(),boxHits=new Box3dHitscanWorld();
const tmp=new THREE.Vector3(),tmp2=new THREE.Vector3(),tmp3=new THREE.Vector3(),desiredDir=new THREE.Vector3(),currentDir=new THREE.Vector3(),leadPoint=new THREE.Vector3(),targetWorld=new THREE.Vector3();
const missiles=[];
const pedState=new WeakMap();
let installed=false,lastMissileAt=-Infinity,lastFrame=performance.now(),lastPedScan=-Infinity,pedestrians=[],recoverBlockedSince=-Infinity,recovering=false,recoverActive=false;

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function walk(){return globalThis.__arondightWalkMode||null;}
function drive(){return globalThis.__arondightVehicleDrive||null;}
function droneWeapons(){return globalThis.__arondightDroneWeapons||null;}
function isDrone(){return walk()?.mode!=="foot"&&!drive()?.active;}
function effectiveVisible(node){for(let n=node;n;n=n.parent)if(n.visible===false)return false;return true;}
function logicalPoint(clientX,clientY){const view=viewport(),r=view?.getBoundingClientRect();if(!view||!r)return null;const w=Math.max(1,view.clientWidth),h=Math.max(1,view.clientHeight),cx=Number.isFinite(clientX)?clientX:r.left+r.width/2,cy=Number.isFinite(clientY)?clientY:r.top+r.height/2,rotated=view.dataset.soloOrientation==="css-landscape",x=rotated?cy-r.top:cx-r.left,y=rotated?r.right-cx:cy-r.top;return{x:clamp(x,0,w),y:clamp(y,0,h),w,h};}
function droneRay(clientX,clientY){const camera=bridge()?.threeCamera,p=logicalPoint(clientX,clientY);if(!camera||!p)return null;ndc.set(p.x/p.w*2-1,1-p.y/p.h*2);raycaster.setFromCamera(ndc,camera);return{origin:raycaster.ray.origin.clone(),direction:raycaster.ray.direction.clone()};}
function sceneCandidates(scene){const out=[];scene?.traverse?.(node=>{if(!node?.isMesh||!effectiveVisible(node)||node.material?.visible===false)return;const u=node.userData||{};if(u.flightFireIgnore||u.walkWeaponPart||u.arondightAirframe||u.localHumanAvatar||u.guidedMissilePart)return;out.push(node);});return out;}
function nearestHit(ray,maxDistance=240){const b=bridge(),scene=b?.threeScene;if(!scene||!ray)return null;raycaster.set(ray.origin,ray.direction);raycaster.near=.01;raycaster.far=maxDistance;const sceneHit=raycaster.intersectObjects(sceneCandidates(scene),false)[0]||null;let staticHit=null;if(b.active){const hit=boxHits.cast([ray.origin.x,ray.origin.y,ray.origin.z],[ray.direction.x,ray.direction.y,ray.direction.z],maxDistance,b.buildingCollisionSnapshot);if(hit)staticHit={box3d:true,distance:hit.distanceM,point:new THREE.Vector3(...hit.point)};}return staticHit&&(!sceneHit||staticHit.distance<sceneHit.distance)?staticHit:sceneHit;}
function entityIdentity(node){for(let n=node;n;n=n.parent){const u=n.userData||{},id=String(u.worldPopulationId||u.worldLifeId||u.vsPlayerId||u.policeDroneId||"");if(id)return{id,node:n};}return null;}
function entityRoot(node){const identity=entityIdentity(node);if(!identity)return null;let root=identity.node;for(let n=identity.node.parent;n;n=n.parent){const u=n.userData||{},id=String(u.worldPopulationId||u.worldLifeId||u.vsPlayerId||u.policeDroneId||"");if(id===identity.id)root=n;else if(id)break;}return root;}
function targetForRay(ray){const hit=nearestHit(ray,240);if(!hit)return{point:tmp.copy(ray.origin).addScaledVector(ray.direction,140).clone(),root:null};if(hit.box3d)return{point:hit.point.clone(),root:null};const root=entityRoot(hit.object);return{point:hit.point?.clone?.()||tmp.copy(ray.origin).addScaledVector(ray.direction,140).clone(),root:root&&effectiveVisible(root)?root:null};}
function missileVisual(scene,origin,direction){const group=new THREE.Group(),body=new THREE.Mesh(new THREE.CylinderGeometry(.028,.034,.30,9),new THREE.MeshStandardMaterial({color:0xdbe2e6,roughness:.30,metalness:.52})),tip=new THREE.Mesh(new THREE.ConeGeometry(.038,.105,9),new THREE.MeshBasicMaterial({color:0xffa13b})),glow=new THREE.Mesh(new THREE.SphereGeometry(.026,6,4),new THREE.MeshBasicMaterial({color:0xff6f25,transparent:true,opacity:.9,depthWrite:false,blending:THREE.AdditiveBlending}));body.rotation.x=Math.PI/2;tip.rotation.x=Math.PI/2;tip.position.z=-.19;glow.position.z=.18;group.add(body,tip,glow);for(const node of[body,tip,glow]){node.userData.flightFireIgnore=true;node.userData.guidedMissilePart=true;}group.position.copy(origin).addScaledVector(direction,.36);group.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),direction);scene.add(group);return group;}
function explode(position,source="guided-missile-v4"){const b=bridge(),scene=b?.threeScene;if(scene){const flash=new THREE.Mesh(new THREE.SphereGeometry(.34,9,6),new THREE.MeshBasicMaterial({color:0xffa042,transparent:true,opacity:.92,depthWrite:false,blending:THREE.AdditiveBlending}));flash.position.copy(position);flash.userData.flightFireIgnore=true;scene.add(flash);const born=performance.now();const pulse=now=>{const t=clamp((now-born)/420,0,1);flash.scale.setScalar(.6+5.5*(1-(1-t)**3));flash.material.opacity=.92*(1-t);if(t<1)requestAnimationFrame(pulse);else{scene.remove(flash);flash.geometry.dispose();flash.material.dispose();}};requestAnimationFrame(pulse);}window.dispatchEvent(new CustomEvent("arondight:world-explosion",{detail:{position:[position.x,position.y,position.z],radiusM:MISSILE_RADIUS_M,maxDamage:100,kind:"missile",source}}));}
function launchGuidedMissile(clientX,clientY,source="pointer"){const now=performance.now(),view=viewport();if(!isDrone()||droneWeapons()?.mode!=="missile"||globalThis.__arondightDroneDamageModel?.destroyed||now-lastMissileAt<900||view?.dataset.fireArmed!=="1")return false;const ray=droneRay(clientX,clientY),scene=bridge()?.threeScene;if(!ray||!scene)return false;lastMissileAt=now;const lock=targetForRay(ray),group=missileVisual(scene,ray.origin,ray.direction),root=lock.root;let rootPosition=null;if(root?.getWorldPosition){rootPosition=new THREE.Vector3();root.getWorldPosition(rootPosition);}missiles.push({group,scene,velocity:ray.direction.clone().multiplyScalar(27),point:lock.point.clone(),root,lastRootPosition:rootPosition?.clone?.()||null,targetVelocity:new THREE.Vector3(),born:now,lastAt:now,source});if(view){view.dataset.droneMissileGuidance="entity-lock+predictive-lead+continuous-steering-v4";view.dataset.droneMissileLock=root?"entity":"point";view.dataset.droneMissiles=String((Number(view.dataset.droneMissiles)||0)+1);}return true;}
function removeMissile(index,position,targeted=false){const m=missiles[index];if(!m)return;m.scene.remove(m.group);missiles.splice(index,1);explode(position,m.source);const view=viewport();if(view){view.dataset.droneMissileLastDetonation=targeted?"locked-target":"world";view.dataset.droneMissileActive=String(missiles.length);}}
function updateMissiles(now,dt){for(let i=missiles.length-1;i>=0;i--){const m=missiles[i],age=now-m.born;if(age>MISSILE_TTL_MS){removeMissile(i,m.group.position.clone(),Boolean(m.root));continue;}let locked=false;if(m.root?.parent&&effectiveVisible(m.root)&&m.root.getWorldPosition){m.root.getWorldPosition(targetWorld);const sampleDt=clamp((now-m.lastAt)/1000,.001,.1);if(m.lastRootPosition){tmp.copy(targetWorld).sub(m.lastRootPosition).multiplyScalar(1/sampleDt);m.targetVelocity.lerp(tmp,.36);}m.lastRootPosition??=new THREE.Vector3();m.lastRootPosition.copy(targetWorld);m.lastAt=now;const distance=m.group.position.distanceTo(targetWorld),leadTime=clamp(distance/Math.max(20,m.velocity.length()),0,.75);leadPoint.copy(targetWorld).addScaledVector(m.targetVelocity,leadTime);m.point.lerp(leadPoint,.72);locked=true;}
    tmp.copy(m.point).sub(m.group.position);const distance=tmp.length();if(distance<.85){removeMissile(i,m.group.position.clone(),locked);continue;}desiredDir.copy(tmp).normalize();currentDir.copy(m.velocity).normalize();const steer=1-Math.exp(-MISSILE_TURN_RESPONSE*dt);currentDir.lerp(desiredDir,steer).normalize();const speed=THREE.MathUtils.lerp(m.velocity.length(),MISSILE_SPEED_MPS,1-Math.exp(-2.8*dt));m.velocity.copy(currentDir).multiplyScalar(speed);const step=Math.max(.01,speed*dt),hit=nearestHit({origin:m.group.position,direction:currentDir},step+.18);if(hit&&Number(hit.distance)<=step+.12){removeMissile(i,hit.point?.clone?.()||m.group.position.clone(),locked);continue;}m.group.position.addScaledVector(m.velocity,dt);m.group.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),currentDir);const view=viewport();if(view){view.dataset.droneMissileLock=locked?"entity":"last-known-point";view.dataset.droneMissileTurnResponse=MISSILE_TURN_RESPONSE.toFixed(1);view.dataset.droneMissileActive=String(missiles.length);}}
}
function interceptMissilePointer(event){if(event.type!=="pointerdown"||event.button!==0||!isDrone()||droneWeapons()?.mode!=="missile")return;const target=event.target instanceof Element?event.target:null;if(target?.closest(RESERVED))return;if(launchGuidedMissile(event.clientX,event.clientY,event.pointerType||"pointer")){event.preventDefault();event.stopImmediatePropagation();}}
function patchMissileApi(){const api=droneWeapons();if(!api||api.fireMissile?.__guidedV4)return;const fire=({clientX,clientY,source="external"}={})=>launchGuidedMissile(clientX,clientY,source);fire.__guidedV4=true;api.fireMissile=fire;}

function pointInPolygon(x,y,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if(((a[1]>y)!==(b[1]>y))&&(x<(b[0]-a[0])*(y-a[1])/((b[1]-a[1])||1e-9)+a[0]))inside=!inside;}return inside;}
function closestOnSegment(x,y,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],l=dx*dx+dy*dy;if(l<1e-9)return[a[0],a[1]];const t=clamp(((x-a[0])*dx+(y-a[1])*dy)/l,0,1);return[a[0]+dx*t,a[1]+dy*t];}
function resolveOutside(prism,x,y,clearance=.32){let best=null,bestD=Infinity;for(let i=0;i<prism.points.length;i++){const a=prism.points[i],b=prism.points[(i+1)%prism.points.length],q=closestOnSegment(x,y,a,b),d=Math.hypot(x-q[0],y-q[1]);if(d<bestD){bestD=d;best={q,a,b};}}if(!best)return[x,y];const dx=best.b[0]-best.a[0],dy=best.b[1]-best.a[1],len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len,c1=[best.q[0]+nx*clearance,best.q[1]+ny*clearance],c2=[best.q[0]-nx*clearance,best.q[1]-ny*clearance],out1=!pointInPolygon(c1[0],c1[1],prism.points),out2=!pointInPolygon(c2[0],c2[1],prism.points);if(out1&&!out2)return c1;if(out2&&!out1)return c2;return Math.hypot(c1[0]-x,c1[1]-y)<=Math.hypot(c2[0]-x,c2[1]-y)?c1:c2;}
function scanPedestrians(now){if(now-lastPedScan<700)return;lastPedScan=now;pedestrians=[];bridge()?.threeScene?.traverse?.(node=>{if(String(node.userData?.worldPopulationKind||node.userData?.worldLifeKind||"").replace(/^life-/,"")!=="person")return;const id=String(node.userData?.worldPopulationId||node.userData?.worldLifeId||"");if(!id||pedestrians.some(p=>p.id===id))return;let root=node;while(root.parent&&String(root.parent.userData?.worldPopulationId||root.parent.userData?.worldLifeId||"")===id)root=root.parent;pedestrians.push({id,root});});}
function guardPedestrians(now){scanPedestrians(now);const prisms=bridge()?.buildingCollisionSnapshot?.prisms||[];let corrected=0;for(const p of pedestrians){const root=p.root;if(!root?.parent||root.visible===false)continue;let s=pedState.get(root);if(!s){s={safe:root.position.clone()};pedState.set(root,s);}let blocking=null;for(const prism of prisms){if(root.position.z>Number(prism.top)+.3||root.position.z+1.8<Number(prism.base))continue;if(pointInPolygon(root.position.x,root.position.y,prism.points)){blocking=prism;break;}}if(blocking){const out=resolveOutside(blocking,root.position.x,root.position.y,.38);root.position.x=out[0];root.position.y=out[1];root.rotation.z+=Math.PI*.72;corrected++;}else s.safe.copy(root.position);}const view=viewport();if(view){view.dataset.pedestrianBuildingCollision="polygon-boundary-resolve-v1";view.dataset.pedestrianBuildingCorrections=String(corrected);}}

function recoveryEligible(now){const button=document.getElementById("soloArm"),state=String(document.getElementById("soloState")?.textContent||"").toUpperCase();if(!button||!document.body.classList.contains("solo-flight")||!isDrone()||globalThis.__arondightDroneDamageModel?.destroyed||button.classList.contains("arming")||state.includes("CALIBRAT")){recoverBlockedSince=-Infinity;return false;}if(!button.disabled){recoverBlockedSince=-Infinity;return false;}if(!Number.isFinite(recoverBlockedSince)||recoverBlockedSince<0)recoverBlockedSince=now;return now-recoverBlockedSince>1800;}
function waitAndArm(deadline=performance.now()+5500){const button=document.getElementById("soloArm"),state=String(document.getElementById("soloState")?.textContent||"").toUpperCase();if(!recovering)return;if(button&&!button.disabled&&!state.includes("CALIBRAT")){recovering=false;recoverActive=false;button.click();const view=viewport();if(view)view.dataset.droneRecoveryResult="recovered+arm-requested";return;}if(performance.now()>deadline){recovering=false;recoverActive=false;const view=viewport();if(view)view.dataset.droneRecoveryResult="recover-timeout";return;}setTimeout(()=>waitAndArm(deadline),120);}
function startRecovery(){if(recovering)return;recovering=true;recoverActive=false;recoverBlockedSince=-Infinity;const reset=document.getElementById("soloReset"),view=viewport();if(view){view.dataset.droneRecovery="soft-airframe-recover+auto-arm-v1";view.dataset.droneRecoveryResult="recovering";}reset?.click();setTimeout(()=>waitAndArm(),180);}
function interceptRecover(event){if(event.type!=="pointerdown"||!recoverActive)return;const button=event.target instanceof Element?event.target.closest("#soloArm"):null;if(!button)return;event.preventDefault();event.stopImmediatePropagation();startRecovery();}
function updateRecovery(now){const button=document.getElementById("soloArm");if(!button||recovering)return;recoverActive=recoveryEligible(now);if(recoverActive){button.disabled=false;button.textContent="RECOVER + ARM";button.classList.add("drone-recover-ready");}else button.classList.remove("drone-recover-ready");const view=viewport();if(view)view.dataset.droneRecoveryReady=recoverActive?"1":"0";}
function installStyle(){if(document.querySelector("style[data-gameplay-reliability-v4]"))return;const style=document.createElement("style");style.dataset.gameplayReliabilityV4="1";style.textContent=`body.on-foot-mode #footMove{z-index:42!important;pointer-events:auto!important;touch-action:none!important;isolation:isolate}body.on-foot-mode #footLook{z-index:40!important}body.on-foot-mode #footWeaponToggle{z-index:44!important;pointer-events:auto!important}body.on-foot-mode #footLookZone{z-index:1!important}.drone-recover-ready{background:#8a5b12!important;border-color:#ffd16a!important;box-shadow:0 0 0 4px #ffbb3d22,0 0 24px #ff9e2f77!important;animation:none!important}`;document.head.appendChild(style);}

function frame(now=performance.now()){const dt=clamp((now-lastFrame)/1000,.001,.05);lastFrame=now;patchMissileApi();updateMissiles(now,dt);guardPedestrians(now);updateRecovery(now);const view=viewport();if(view)view.dataset.gameplayReliabilityRuntime="guided-missile+ped-collision+recover-v4";requestAnimationFrame(frame);}
export function installGameplayReliabilityRuntimeV4(){if(installed)return;installed=true;installStyle();window.addEventListener("pointerdown",interceptMissilePointer,{capture:true,passive:false});window.addEventListener("pointerdown",interceptRecover,{capture:true,passive:false});requestAnimationFrame(frame);}
installGameplayReliabilityRuntimeV4();
