import {AUDIO_SETTINGS_EVENT,loadAudioSettings,normalizeAudioSettings} from "./audio_settings.mjs";
import {getSharedCombatAudioContext,playCombatAudio} from "./combat_audio_bank.mjs";
import {GAMEPLAY_COMBO_WINDOW_MS,GAMEPLAY_CONTRACTS,GAMEPLAY_FUN_VERSION,GAMEPLAY_MOMENTUM_TARGET,createGameplayState,gameplayContract,gameplayMultiplier,gameplayPoliceDamageScale,reduceGameplay} from "./gameplay_fun_logic.mjs";

const HIGH_SCORE_KEY="arondight45GameplayHighScoreV1";
const CONTRACT_KEY="arondight45GameplayContractV1";
const clamp=(value,min,max)=>Math.max(min,Math.min(max,Number(value)||0));
let installed=false,state=createGameplayState({contractIndex:readNumber(CONTRACT_KEY),highScore:readNumber(HIGH_SCORE_KEY)}),scorePill=null,hud=null,toast=null,lastRender=-Infinity,advanceTimer=0,toastTimer=0,toastQueue=[],audioSettings=loadAudioSettings();

function viewport(){return document.getElementById("viewport");}
function wanted(){return globalThis.__arondightWantedSystem||null;}
function readNumber(key){try{return Number(localStorage.getItem(key))||0;}catch{return 0;}}
function saveNumber(key,value){try{localStorage.setItem(key,String(Math.max(0,Math.floor(Number(value)||0))));}catch{}}
function currentStars(){return clamp(Number(wanted()?.state?.stars??viewport()?.dataset.wantedStars),0,5);}
function formatPoints(value){const n=Math.max(0,Math.round(Number(value)||0));return n>=100000?`${(n/1000).toFixed(n>=1000000?0:1)}k`:n.toLocaleString("en-US");}

function installStyle(){if(document.querySelector("style[data-gameplay-fun]"))return;const style=document.createElement("style");style.dataset.gameplayFun=GAMEPLAY_FUN_VERSION;style.textContent=`
#gameplayScorePill{font-variant-numeric:tabular-nums;letter-spacing:.025em;color:#ffe49b!important;border-color:#ffc85b55!important;background:linear-gradient(180deg,#2b2414d9,#151208d9)!important;min-width:132px}
#gameplayContractHud{display:none;position:absolute;z-index:18;left:max(12px,var(--solo-safe-left,env(safe-area-inset-left)));top:max(88px,calc(var(--solo-safe-top,env(safe-area-inset-top)) + 82px));width:172px;color:#eef8ff;font-family:system-ui,-apple-system,sans-serif;pointer-events:auto}
body.solo-flight #gameplayContractHud{display:block}#gameplayContractButton{display:block;width:100%;padding:8px 9px 7px;border:1px solid #72cfff66;border-radius:11px;background:linear-gradient(145deg,#0c2438ed,#07131fed);box-shadow:0 6px 20px #0008,inset 0 1px #ffffff12;color:#eef8ff;text-align:left;touch-action:manipulation}#gameplayContractButton:active{transform:scale(.975);filter:brightness(1.16)}#gameplayContractButton>small{display:block;font:850 6.5px/1 system-ui;letter-spacing:.13em;color:#70d7ff}#gameplayContractButton>strong{display:block;margin-top:4px;padding-right:36px;overflow:hidden;text-overflow:ellipsis;font:950 10px/1 system-ui;letter-spacing:.055em;white-space:nowrap}#gameplayContractProgress{position:absolute;right:9px;top:20px;font:950 10px/1 ui-monospace,SFMono-Regular,Menlo,monospace;color:#ffe083}#gameplayContractHint{display:block;margin-top:5px;overflow:hidden;text-overflow:ellipsis;font:800 6.5px/1.15 system-ui;letter-spacing:.035em;color:#b8cbd7;white-space:nowrap}#gameplayContractBar{display:block;height:3px;margin-top:6px;border-radius:99px;background:#ffffff18;overflow:hidden}#gameplayContractBar>i{display:block;width:0;height:100%;border-radius:inherit;background:linear-gradient(90deg,#35b9ff,#7ff0c5,#ffe36e);box-shadow:0 0 8px #58ddff;transition:width .22s ease}
#gameplayRiskHint{display:block;margin-top:4px;min-height:8px;font:900 6.5px/1.1 system-ui;letter-spacing:.06em;color:#ffbe72}#gameplayMomentum{display:flex;align-items:center;gap:4px;margin-top:5px;padding:0 2px}#gameplayMomentum>small{margin-right:auto;font:850 6px/1 system-ui;letter-spacing:.09em;color:#91aaba}#gameplayMomentum>i{width:13px;height:3px;border-radius:99px;background:#ffffff20;box-shadow:inset 0 0 2px #000}#gameplayMomentum>i.hot{background:#62e5ff;box-shadow:0 0 7px #32cfff}#gameplayContractHud[data-overdrive="1"] #gameplayMomentum>i{background:#ffe05c;box-shadow:0 0 9px #ffad2e}#gameplayContractHud[data-complete="1"] #gameplayContractButton{border-color:#7ff0c5aa;box-shadow:0 6px 20px #0008,0 0 24px #3fe0a344}
#gameplayToast{display:none;position:absolute;z-index:34;left:50%;top:34%;transform:translate(-50%,-50%);min-width:170px;padding:10px 16px;border:1px solid #ffe1848c;border-radius:13px;background:radial-gradient(circle at 50% 0,#4a3819ee,#0b1018f2 68%);box-shadow:0 10px 34px #000b,0 0 30px #ffba3544;color:#fff;text-align:center;pointer-events:none;font-family:system-ui,-apple-system,sans-serif}body.solo-flight #gameplayToast.active{display:block;animation:gameplayToast .78s cubic-bezier(.18,.82,.23,1) forwards}#gameplayToast strong{display:block;font:950 18px/1 system-ui;letter-spacing:.055em;color:#ffe58c;text-shadow:0 0 12px #ffb52e88}#gameplayToast small{display:block;margin-top:5px;font:850 8px/1.15 system-ui;letter-spacing:.08em;color:#d9efff}#gameplayToast[data-kind="fail"]{border-color:#ff7788aa;background:radial-gradient(circle at 50% 0,#541b28ee,#0b1018f2 68%)}#gameplayToast[data-kind="fail"] strong{color:#ff9aaa;text-shadow:0 0 12px #ff334f66}#gameplayToast[data-kind="bank"]{border-color:#72f0b9aa;background:radial-gradient(circle at 50% 0,#164c38ee,#0b1018f2 68%)}#gameplayToast[data-kind="bank"] strong{color:#8ff0c8;text-shadow:0 0 12px #30dd9366}@keyframes gameplayToast{0%{opacity:0;transform:translate(-50%,-40%) scale(.72)}18%{opacity:1;transform:translate(-50%,-50%) scale(1.08)}70%{opacity:1;transform:translate(-50%,-50%) scale(1)}100%{opacity:0;transform:translate(-50%,-58%) scale(.96)}}
body.solo-flight #viewport[data-world-mode="real"] #gameplayContractHud{left:max(148px,calc(var(--solo-safe-left,env(safe-area-inset-left)) + 140px));top:max(58px,calc(var(--solo-safe-top,env(safe-area-inset-top)) + 52px))}@media(max-height:340px){#gameplayScorePill{min-width:112px!important;font-size:7.5px!important}#gameplayContractHud{top:max(70px,calc(var(--solo-safe-top,env(safe-area-inset-top)) + 64px));width:154px}#gameplayContractButton{padding:6px 7px 5px}#gameplayContractButton>small{font-size:5.5px}#gameplayContractButton>strong{font-size:8.5px;margin-top:3px}#gameplayContractProgress{right:7px;top:16px;font-size:8.5px}#gameplayContractHint{font-size:5.5px;margin-top:4px}#gameplayRiskHint{font-size:5.5px;margin-top:3px}#gameplayMomentum{margin-top:4px}#gameplayMomentum>i{width:11px}body.solo-flight #viewport[data-world-mode="real"] #gameplayContractHud{left:max(128px,calc(var(--solo-safe-left,env(safe-area-inset-left)) + 120px));top:max(62px,calc(var(--solo-safe-top,env(safe-area-inset-top)) + 56px))}}
`;document.head.appendChild(style);}

function ensureHud(){const view=viewport();if(!view)return false;installStyle();const status=document.getElementById("soloTopbarStatus");if(status&&!scorePill){scorePill=document.createElement("span");scorePill.id="gameplayScorePill";scorePill.setAttribute("role","status");status.appendChild(scorePill);}if(!hud){hud=document.createElement("div");hud.id="gameplayContractHud";hud.className="gameplay-ui";hud.innerHTML=`<button id="gameplayContractButton" type="button" aria-label="Change gameplay contract"><small>CONTRACT · TAP TO CHANGE</small><strong id="gameplayContractName">HOT ESCAPE</strong><em id="gameplayContractProgress">0/1</em><span id="gameplayContractHint">REACH 2★ · BREAK SIGHT · ESCAPE</span><span id="gameplayContractBar"><i></i></span></button><span id="gameplayRiskHint"></span><div id="gameplayMomentum"><small>MOMENTUM</small>${Array.from({length:GAMEPLAY_MOMENTUM_TARGET},()=>"<i></i>").join("")}</div>`;view.appendChild(hud);const button=hud.querySelector("#gameplayContractButton");button.addEventListener("pointerdown",event=>event.stopPropagation());button.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();record({type:"cycleContract"});});}if(!toast){toast=document.createElement("div");toast.id="gameplayToast";toast.setAttribute("role","status");toast.setAttribute("aria-live","polite");toast.innerHTML="<strong></strong><small></small>";view.appendChild(toast);}return Boolean(scorePill&&hud&&toast);}

function effectCopy(effect){return effect?{...effect}:null;}
function toastFor(effect){
  if(effect.type==="contractComplete")return{title:"CONTRACT COMPLETE",detail:`${effect.name} · +${formatPoints(effect.reward)}`,kind:"bank",sound:"reward",gain:.36};
  if(effect.type==="bank")return{title:`BANKED +${formatPoints(effect.points)}`,detail:`ESCAPED ${effect.peakStars}★ · SCORE ${formatPoints(effect.score)}`,kind:"bank",sound:"reward",gain:.34};
  if(effect.type==="overdrive")return{title:"OVERDRIVE!",detail:`1.75× FOR ${(effect.durationMs/1000).toFixed(0)}s · +${formatPoints(effect.bonus)}`,kind:"bank",sound:"reward",gain:.40};
  if(effect.type==="award"&&effect.combo>=2)return{title:`+${formatPoints(effect.points)}`,detail:`${effect.label} · ${effect.combo} COMBO · ×${effect.multiplier.toFixed(2)}`,kind:"award",sound:"reward",gain:.19};
  if(effect.type==="comboBreak")return{title:"COMBO LOST",detail:`${effect.combo} STREAK ENDED`,kind:"fail",sound:"fail",gain:.17};
  if(effect.type==="setback")return{title:effect.label||"SETBACK",detail:`-${formatPoints(effect.lost)} · COMEBACK SHIELD ${effect.mercy}/2`,kind:"fail",sound:"fail",gain:.25};
  if(effect.type==="insurance")return{title:"SECOND CHANCE",detail:`SAVED ${formatPoints(effect.insured)} · LOST ${formatPoints(effect.lost)}`,kind:"fail",sound:"fail",gain:.29};
  return null;
}
function playReward(kind,gain){if(!audioSettings.soundEnabled||audioSettings.fxVolume<=0)return false;const context=getSharedCombatAudioContext({resume:true});return Boolean(context&&playCombatAudio(context,kind,{gain:gain*audioSettings.fxVolume/100,minIntervalMs:60}));}
function drainToast(){if(toastTimer||!toastQueue.length||!ensureHud())return;const item=toastQueue.shift();toast.classList.remove("active");void toast.offsetWidth;toast.dataset.kind=item.kind;toast.querySelector("strong").textContent=item.title;toast.querySelector("small").textContent=item.detail;toast.classList.add("active");playReward(item.sound,item.gain);toastTimer=setTimeout(()=>{toastTimer=0;toast.classList.remove("active");drainToast();},820);}
function queueEffects(effects){for(const effect of effects){const item=toastFor(effectCopy(effect));if(item)toastQueue.push(item);}if(toastQueue.length>5)toastQueue=toastQueue.slice(-5);drainToast();}

function scheduleContractAdvance(){if(!state.contractComplete||advanceTimer)return;const completedIndex=state.contractIndex;advanceTimer=setTimeout(()=>{advanceTimer=0;if(state.contractComplete&&state.contractIndex===completedIndex)record({type:"advanceContract"});},2400);}
function persist(){saveNumber(HIGH_SCORE_KEY,state.highScore);saveNumber(CONTRACT_KEY,state.contractIndex);}
function record(event={}){const enriched={...event,now:Number.isFinite(Number(event.now))?Number(event.now):performance.now(),stars:Number.isFinite(Number(event.stars))?Number(event.stars):currentStars()},result=reduceGameplay(state,enriched);state=result.state;persist();queueEffects(result.effects);scheduleContractAdvance();render(performance.now(),true);return{state:{...state},effects:result.effects.map(effectCopy)};}

function render(now=performance.now(),force=false){
  if(!force&&now-lastRender<100)return;lastRender=now;if(!ensureHud())return;const contract=gameplayContract(state),multiplier=gameplayMultiplier(state,{stars:currentStars(),now}),overdrive=now<state.overdriveUntil,remaining=Math.max(0,state.comboExpiresAt-now),progress=clamp(state.contractProgress/contract.target,0,1);scorePill.textContent=`S ${formatPoints(state.score)} · R ${formatPoints(state.atRisk)} · ×${multiplier.toFixed(2)}`;scorePill.dataset.risk=state.atRisk>0?"1":"0";scorePill.setAttribute("aria-label",`Banked score ${state.score}. ${state.atRisk} points at risk. Multiplier ${multiplier.toFixed(2)}.`);hud.dataset.complete=state.contractComplete?"1":"0";hud.dataset.overdrive=overdrive?"1":"0";hud.querySelector("#gameplayContractName").textContent=contract.name;hud.querySelector("#gameplayContractProgress").textContent=`${state.contractProgress}/${contract.target}`;hud.querySelector("#gameplayContractHint").textContent=state.contractComplete?`COMPLETE · +${formatPoints(contract.reward)}`:contract.hint;hud.querySelector("#gameplayContractBar>i").style.width=`${progress*100}%`;hud.querySelector("#gameplayRiskHint").textContent=state.atRisk>0&&currentStars()>0?`ESCAPE TO BANK ${formatPoints(state.atRisk)}`:state.mercy>0?`COMEBACK SHIELD · ${Math.round((1-gameplayPoliceDamageScale(state))*100)}% LESS DAMAGE`:state.highScore>0?`BEST ${formatPoints(state.highScore)}`:"BUILD MOMENTUM · SURVIVE · BANK";hud.querySelectorAll("#gameplayMomentum>i").forEach((node,index)=>node.classList.toggle("hot",overdrive||index<state.momentum));
  const view=viewport();view.dataset.gameplayLoop=GAMEPLAY_FUN_VERSION;view.dataset.gameplayScore=String(state.score);view.dataset.gameplayAtRisk=String(state.atRisk);view.dataset.gameplayHighScore=String(state.highScore);view.dataset.gameplayMultiplier=multiplier.toFixed(3);view.dataset.gameplayCombo=String(state.combo);view.dataset.gameplayComboRemainingMs=String(Math.max(0,Math.round(remaining)));view.dataset.gameplayMomentum=String(state.momentum);view.dataset.gameplayMomentumTarget=String(GAMEPLAY_MOMENTUM_TARGET);view.dataset.gameplayOverdrive=overdrive?"1":"0";view.dataset.gameplayContract=contract.id;view.dataset.gameplayContractProgress=String(state.contractProgress);view.dataset.gameplayContractTarget=String(contract.target);view.dataset.gameplayContractComplete=state.contractComplete?"1":"0";view.dataset.gameplayPoliceDamageScale=gameplayPoliceDamageScale(state).toFixed(2);view.dataset.gameplayRewardEthics="guaranteed-progress+no-near-miss+no-monetization-v1";view.dataset.gameplayFlowAssist="comeback-only-never-above-baseline-v1";
}
function frame(now=performance.now()){const stars=currentStars();if(stars!==state.stars||now>=state.comboExpiresAt&&state.combo>0){state=reduceGameplay(state,{type:"tick",now,stars}).state;}render(now);requestAnimationFrame(frame);}

function installEvents(){
  addEventListener("arondight:world-kill",event=>{const detail=event?.detail||{};if(detail.remote||detail.network===false)return;record({type:"worldKill",kind:String(detail.kind||"unknown")});});
  addEventListener("arondight:combat-hit-confirm",event=>{const detail=event?.detail||{};if(detail.killed&&!detail.self&&!detail.world&&!detail.police)record({type:"worldKill",kind:"player"});});
  addEventListener("arondight:police-drone-destroyed",event=>record({type:"policeKill",empDisabled:Boolean(event?.detail?.empDisabled)}));
  addEventListener("arondight:emp-blast",event=>record({type:"emp",affected:Number(event?.detail?.affected)||0}));
  addEventListener("arondight:wanted-cleared",event=>{if(event?.detail?.reason==="escaped"&&event.detail.hadWanted)record({type:"escape",stars:Number(event.detail.stars)||state.maxStars});});
  addEventListener("arondight:combat-damage",event=>{const detail=event?.detail||{};if(Number(detail.damage)>0)record({type:"damage",amount:Number(detail.damage),hp:Number(detail.hp),target:String(detail.target||"")});});
  addEventListener("arondight:drone-destroyed",()=>record({type:"droneDestroyed"}));addEventListener("arondight:player-death",()=>record({type:"playerDeath"}));
  addEventListener(AUDIO_SETTINGS_EVENT,event=>{audioSettings=normalizeAudioSettings(event.detail||loadAudioSettings());});const unlock=()=>getSharedCombatAudioContext({resume:true});addEventListener("pointerdown",unlock,{capture:true,passive:true});addEventListener("keydown",unlock,{capture:true});
  document.addEventListener("click",event=>{const target=event.target instanceof Element?event.target.closest("#reset,#soloReset"):null;if(target)record({type:"reset"});},{capture:true,passive:true});
}

export function installGameplayFunRuntime(){if(installed)return globalThis.__arondightGameplayDirector;installed=true;ensureHud();installEvents();const api={record,cycleContract:()=>record({type:"cycleContract"}),get state(){return{...state,contract:{...gameplayContract(state)}};},get multiplier(){return gameplayMultiplier(state,{stars:currentStars(),now:performance.now()});},get policeDamageScale(){return gameplayPoliceDamageScale(state);},contracts:GAMEPLAY_CONTRACTS};globalThis.__arondightGameplayDirector=api;requestAnimationFrame(frame);return api;}

installGameplayFunRuntime();
