import * as THREE from "three";
import {VS_FX_EVENT} from "./lan_vs.mjs";

const MOBILE_RE=/(?:android|iphone|ipad|ipod|macintosh.*mobile)/i;
const MOBILE=MOBILE_RE.test(globalThis.navigator?.userAgent||"");
const BLOOD_PARTICLES=MOBILE?14:22;
const AUDIO_SETTINGS_KEY="arondight45AudioSettingsV1";
const FLIGHT_UI_SELECTOR="button,input,select,textarea,a,label,dialog,#soloTopbar,#soloLeft,#soloRight,#soloClearance,.solo-action,#worldLookHud,#vsRespawnHud";
let installed=false,audioCtx=null,noiseBuffer=null,lastDead=false,lastFrame=performance.now(),wrappedWorldHit=null,blood=null;
const activePointers=new Set(),tmp=new THREE.Vector3();

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function activeSession(){const s=bridge()?.vsSession;return s?.active||s||null;}
function clamp(v,lo,hi){return Math.max(lo,Math.min(hi,Number(v)||0));}
function hashText(text){let h=2166136261;for(const c of String(text||"")){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function fxSettings(){try{const raw=localStorage.getItem(AUDIO_SETTINGS_KEY),v=raw?JSON.parse(raw):{};return{enabled:v.soundEnabled!==false,volume:clamp(v.fxVolume??100,0,100)/100};}catch{return{enabled:true,volume:1};}}

export function deterministicInitialSpawnOffset(selfId,peerIds=[]){
  const self=String(selfId||""),ids=[...new Set([self,...peerIds.map(String)].filter(Boolean))].sort();
  if(!self||ids.length<2)return{x:0,y:0,r:0,index:-1,count:ids.length};
  const index=Math.max(0,ids.indexOf(self)),count=ids.length;if(count===2)return{x:index===0?-12:12,y:0,r:12,index,count};
  const phase=(hashText(ids.join("|"))%6283)/1000,angle=phase+index*Math.PI*2/count,r=12+(hashText(self)%4);return{x:Math.cos(angle)*r,y:Math.sin(angle)*r,r,index,count};
}
export const GAMEPLAY_POLISH_DENSITY=Object.freeze({extraCars:0,extraPeople:0,mode:"original-world-population-only"});

function ensureAudio(){const Ctx=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Ctx)return null;try{audioCtx??=new Ctx({latencyHint:"interactive"});if(audioCtx.state==="suspended")audioCtx.resume().catch(()=>{});if(!noiseBuffer){const samples=Math.max(1,Math.floor(audioCtx.sampleRate*.75));noiseBuffer=audioCtx.createBuffer(1,samples,audioCtx.sampleRate);const d=noiseBuffer.getChannelData(0);for(let i=0;i<samples;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/samples,1.7);}return audioCtx;}catch{return null;}}
function playCarExplosionSound(){const s=fxSettings(),ctx=ensureAudio();if(!s.enabled||s.volume<=0||!ctx||ctx.state!=="running"||!noiseBuffer)return false;try{const t=ctx.currentTime,n=ctx.createBufferSource(),f=ctx.createBiquadFilter(),ng=ctx.createGain(),o=ctx.createOscillator(),og=ctx.createGain();n.buffer=noiseBuffer;f.type="lowpass";f.frequency.setValueAtTime(1750,t);f.frequency.exponentialRampToValueAtTime(80,t+.68);ng.gain.setValueAtTime(.32*s.volume,t);ng.gain.exponentialRampToValueAtTime(.0001,t+.72);o.type="sine";o.frequency.setValueAtTime(126,t);o.frequency.exponentialRampToValueAtTime(29,t+.58);og.gain.setValueAtTime(.45*s.volume,t);og.gain.exponentialRampToValueAtTime(.0001,t+.63);n.connect(f).connect(ng).connect(ctx.destination);o.connect(og).connect(ctx.destination);n.start(t);n.stop(t+.74);o.start(t);o.stop(t+.65);const v=viewport();if(v)v.dataset.worldCarExplosionSounds=String((Number(v.dataset.worldCarExplosionSounds)||0)+1);return true;}catch{return false;}}
function playPersonGroan(){const s=fxSettings(),ctx=ensureAudio();if(!s.enabled||s.volume<=0||!ctx||ctx.state!=="running")return false;try{const t=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain();o.type="sawtooth";o.frequency.setValueAtTime(145+Math.random()*28,t);o.frequency.exponentialRampToValueAtTime(72+Math.random()*16,t+.32);g.gain.setValueAtTime(.04*s.volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+.36);o.connect(g).connect(ctx.destination);o.start(t);o.stop(t+.38);const v=viewport();if(v)v.dataset.worldPersonGroans=String((Number(v.dataset.worldPersonGroans)||0)+1);return true;}catch{return false;}}

function ensureBlood(){if(blood)return blood;const scene=bridge()?.threeScene;if(!scene)return null;const positions=new Float32Array(BLOOD_PARTICLES*3),colors=new Float32Array(BLOOD_PARTICLES*3),geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.BufferAttribute(positions,3));geometry.setAttribute("color",new THREE.BufferAttribute(colors,3));geometry.setDrawRange(0,0);const material=new THREE.PointsMaterial({size:.10,vertexColors:true,transparent:true,opacity:.86,depthWrite:false,sizeAttenuation:true}),points=new THREE.Points(geometry,material);points.renderOrder=19;points.frustumCulled=false;points.userData.flightFireIgnore=true;scene.add(points);blood={points,geometry,positions,colors,particles:Array.from({length:BLOOD_PARTICLES},()=>({active:false,v:new THREE.Vector3(),expires:0})),cursor:0,count:0};return blood;}
function spawnBlood(position){const b=ensureBlood();if(!b||!position)return;const p=Array.isArray(position)?tmp.set(Number(position[0])||0,Number(position[1])||0,Number(position[2])||0):tmp.copy(position),now=performance.now();for(let i=0;i<6;i++){const idx=b.cursor++%BLOOD_PARTICLES,item=b.particles[idx],a=Math.random()*Math.PI*2,s=.45+Math.random()*1.1;item.active=true;item.v.set(Math.cos(a)*s,Math.sin(a)*s,.3+Math.random()*.9);item.expires=now+450+Math.random()*250;b.positions[idx*3]=p.x;b.positions[idx*3+1]=p.y;b.positions[idx*3+2]=p.z+.05;b.colors[idx*3]=.42+Math.random()*.18;b.colors[idx*3+1]=.01;b.colors[idx*3+2]=.01;}b.geometry.setDrawRange(0,BLOOD_PARTICLES);b.geometry.attributes.position.needsUpdate=true;b.geometry.attributes.color.needsUpdate=true;const v=viewport();if(v)v.dataset.worldBloodFx=String((Number(v.dataset.worldBloodFx)||0)+1);}
function updateBlood(now,dt){const b=blood;if(!b)return;let any=false;for(let i=0;i<b.particles.length;i++){const item=b.particles[i];if(!item.active)continue;if(now>=item.expires){item.active=false;b.positions[i*3+2]=-999;continue;}any=true;item.v.z-=3.5*dt;b.positions[i*3]+=item.v.x*dt;b.positions[i*3+1]+=item.v.y*dt;b.positions[i*3+2]=Math.max(.015,b.positions[i*3+2]+item.v.z*dt);}if(any||b.count){b.geometry.attributes.position.needsUpdate=true;b.count=any?1:0;}b.points.visible=Boolean(any);}

function nodeKind(hit){for(let n=hit?.object;n;n=n.parent){const kind=String(n.userData?.worldPopulationKind||"");if(kind)return{kind,node:n};}return{kind:"",node:null};}
function wrapWorldPopulationHits(){const b=bridge(),base=b?.registerWorldPopulationHit;if(typeof base!=="function"||base===wrappedWorldHit||base.__gameplayPolishLiteWrapper)return;const wrapper=hit=>{const info=nodeKind(hit);const handled=Boolean(base(hit));if(handled&&info.kind==="person"){const p=hit?.point||info.node?.getWorldPosition?.(tmp);spawnBlood(p);playPersonGroan();}return handled;};wrapper.__gameplayPolishLiteWrapper=true;wrappedWorldHit=wrapper;b.registerWorldPopulationHit=wrapper;const v=viewport();if(v)v.dataset.gameplayWorldHitAudio="1";}

function participantIds(session,self){try{return[...new Set([self,...(session?.getPeerIds?.()||[])].filter(Boolean).map(String))];}catch{return self?[self]:[];}}
function installGeoSpawnAdapter(currentBridge,session){if(!session||typeof session.setPose!=="function"||session.__gameplayInitialGeoSpawnAdapter)return;session.__gameplayInitialGeoSpawnAdapter=true;const base=session.setPose.bind(session);session.setPose=pose=>{const offset=currentBridge.__vsInitialGeoSpawnOffset;if(Array.isArray(pose?.g)&&pose.g.length===2&&Array.isArray(offset)&&(offset[0]||offset[1])){const lon=Number(pose.g[0]),lat=Number(pose.g[1]);if(Number.isFinite(lon)&&Number.isFinite(lat)){const earth=6378137,cos=Math.max(.01,Math.cos(lat*Math.PI/180));pose={...pose,g:[lon+offset[0]/(earth*cos)*180/Math.PI,lat+offset[1]/earth*180/Math.PI]};}}return base(pose);};}
function ensureInitialSpawnSeparation(){const b=bridge(),s=activeSession(),self=String(s?.getSelfId?.()||"");if(!b||!s||!self)return;const ids=participantIds(s,self);if(ids.length<2)return;const mode=b.active?"real":"training";if(mode==="training"&&!b.__vsRespawnOffsetAdapter)return;if(mode==="real")installGeoSpawnAdapter(b,s);const key=`${mode}:${ids.slice().sort().join("|")}`,offset=deterministicInitialSpawnOffset(self,ids.filter(id=>id!==self));if(b.__vsInitialSpawnSetKey===key)return;if(mode==="real")b.__vsInitialGeoSpawnOffset=[offset.x,offset.y];else b.__vsRespawnLocalOffset=[offset.x,offset.y];b.__vsInitialSpawnSetKey=key;const v=viewport();if(v){v.dataset.vsInitialSpawnSeparated="1";v.dataset.vsInitialSpawnMode=mode;v.dataset.vsInitialSpawnSet=key;v.dataset.vsInitialSpawnOffsetM=`${offset.x.toFixed(2)},${offset.y.toFixed(2)}`;v.dataset.vsInitialSpawnPairDistanceM=ids.length===2?"24.00":"ring";}}

function flightSurface(event){const t=event?.target;return t instanceof Element&&!t.closest(FLIGHT_UI_SELECTOR);}
function cancelActivePointers(){const v=viewport();if(!v)return;for(const pointerId of [...activePointers]){try{v.dispatchEvent(new PointerEvent("pointercancel",{pointerId,bubbles:false,cancelable:true}));}catch{}}activePointers.clear();}
function syncDeathFireLock(){const b=bridge(),dead=Boolean(b?.vsLocalDead),v=viewport();if(dead){globalThis.__arondightSettingsGamepadBlockUntilRelease=true;if(!lastDead)cancelActivePointers();}document.body?.classList.toggle("vs-combat-dead",dead);if(v)v.dataset.fireLockedByDeath=dead?"1":"0";lastDead=dead;}
function handleRemoteFx(event){queueMicrotask(()=>{const p=event?.detail?.packet;if(!p?.objectId)return;if(p.kind==="car"&&p.type==="explosion")playCarExplosionSound();else if(p.kind==="person"&&p.type==="impact"){playPersonGroan();if(Array.isArray(p.p))spawnBlood(p.p);}});}
function loop(now=performance.now()){const dt=Math.min(.05,Math.max(0,(now-lastFrame)/1000||0));lastFrame=now;wrapWorldPopulationHits();ensureInitialSpawnSeparation();syncDeathFireLock();updateBlood(now,dt);requestAnimationFrame(loop);}

export function installGameplayPolishLite(){if(installed)return;installed=true;const style=document.createElement("style");style.dataset.gameplayPolish="lite-v3";style.textContent=`body.vs-combat-dead .xbox-crosshair{display:none!important}body.vs-combat-dead #viewport{cursor:not-allowed}`;document.head.appendChild(style);const v=viewport();v?.addEventListener("pointerdown",event=>{ensureAudio();if(!flightSurface(event))return;if(bridge()?.vsLocalDead){event.preventDefault();event.stopImmediatePropagation();return;}activePointers.add(event.pointerId);},{capture:true,passive:false});for(const type of ["pointerup","pointercancel"])v?.addEventListener(type,event=>activePointers.delete(event.pointerId),{capture:true,passive:true});document.addEventListener("keydown",()=>ensureAudio(),{capture:true});globalThis.addEventListener(VS_FX_EVENT,handleRemoteFx);requestAnimationFrame(loop);if(v){v.dataset.gameplayPolish="lite-v3";v.dataset.gameplayExtraCarsTarget="0";v.dataset.gameplayExtraPeopleTarget="0";v.dataset.gameplayDensityMode="original-only";}}

installGameplayPolishLite();
