import "./gameplay_final_input_extras.mjs";

let installed=false;
function dockWeapon(){const button=document.getElementById("droneWeaponToggle"),top=document.getElementById("soloTopbarActions")||document.getElementById("soloTopbar");if(!button||!top)return false;if(button.parentElement!==top)top.appendChild(button);button.classList.add("final-drone-weapon-topbar");return true;}
function dockXboxToggle(){let changed=false;for(const dialog of document.querySelectorAll("dialog.phone-settings-dialog")){const hardware=dialog.querySelector(".player-control-hardware"),legacy=dialog.querySelector("[data-xbox-controller]"),mirror=hardware?.querySelector('[data-setting="xboxControllerEnabled"]');if(!hardware||!legacy)continue;const row=legacy.closest(".phone-settings-toggle");if(row&&row.parentElement!==hardware){const note=hardware.querySelector(".player-control-note");hardware.insertBefore(row,note||null);changed=true;}if(row){row.style.display="flex";row.dataset.nativeXboxControl="1";}const mirrorRow=mirror?.closest(".player-control-toggle");if(mirrorRow){mirrorRow.style.display="none";mirrorRow.setAttribute("aria-hidden","true");}hardware.dataset.xboxControlSource="native-reused-v1";}return changed;}
function installStyle(){if(document.querySelector("style[data-final-drone-weapon-dock]"))return;const style=document.createElement("style");style.dataset.finalDroneWeaponDock="v2";style.textContent=`#soloTopbarActions #droneWeaponToggle,#soloTopbar #droneWeaponToggle{position:static!important;inset:auto!important;transform:none!important;min-width:92px!important;width:auto!important;height:30px!important;padding:0 8px!important;margin:0!important;flex:0 1 auto!important;font-size:8px!important;z-index:auto!important}body.on-foot-mode #droneWeaponToggle{display:none!important}.player-control-hardware .phone-settings-toggle[data-native-xbox-control="1"]{display:flex!important;margin:4px 0 8px!important;border-top:0!important}`;document.head.appendChild(style);}
function frame(){dockWeapon();dockXboxToggle();requestAnimationFrame(frame);}
export function installGameplayFinalUiDock(){if(installed)return;installed=true;installStyle();requestAnimationFrame(frame);}
installGameplayFinalUiDock();
