import "./gameplay_final_input_extras.mjs";

let installed=false,footDownMode="",footDownAt=-Infinity,droneDownMode="",droneDownAt=-Infinity;
function weaponDock(){const view=document.getElementById("viewport");if(!view)return null;let dock=document.getElementById("weaponSwitchDock");if(!dock){dock=document.createElement("div");dock.id="weaponSwitchDock";dock.setAttribute("aria-label","Weapon switch");view.appendChild(dock);}return dock;}
function dockWeapon(){const button=document.getElementById("droneWeaponToggle"),dock=weaponDock();if(!button||!dock)return false;if(button.parentElement!==dock)dock.appendChild(button);button.classList.remove("final-drone-weapon-topbar");button.classList.add("final-drone-weapon-bottom");return true;}
function bindReliableButton(button,kind){if(!button||button.dataset.reliableWeaponButton==="1")return false;button.dataset.reliableWeaponButton="1";button.addEventListener("pointerdown",()=>{const api=kind==="foot"?globalThis.__arondightFootWeapons:globalThis.__arondightDroneWeapons;if(kind==="foot"){footDownMode=String(api?.mode||"");footDownAt=performance.now();}else{droneDownMode=String(api?.mode||"");droneDownAt=performance.now();}},{capture:true,passive:true});button.addEventListener("click",event=>{const api=kind==="foot"?globalThis.__arondightFootWeapons:globalThis.__arondightDroneWeapons;if(typeof api?.toggle!=="function")return;const before=kind==="foot"?footDownMode:droneDownMode,at=kind==="foot"?footDownAt:droneDownAt,current=String(api.mode||"");if(performance.now()-at<700&&before&&current!==before)return;event.preventDefault();event.stopPropagation();api.toggle();const view=document.getElementById("viewport");if(view)view.dataset.weaponButtonClickFallback="click-dedup-v1";});return true;}
function dockFootWeapon(){const button=document.getElementById("footWeaponToggle"),dock=weaponDock();if(!button||!dock)return false;if(button.parentElement!==dock)dock.appendChild(button);button.classList.remove("final-foot-weapon-hud");button.classList.add("final-foot-weapon-bottom");bindReliableButton(button,"foot");return true;}
function dockXboxToggle(){let changed=false;for(const dialog of document.querySelectorAll("dialog.phone-settings-dialog")){const hardware=dialog.querySelector(".player-control-hardware"),legacy=dialog.querySelector("[data-xbox-controller]"),mirror=hardware?.querySelector('[data-setting="xboxControllerEnabled"]');if(!hardware||!legacy)continue;const row=legacy.closest(".phone-settings-toggle");if(row&&row.parentElement!==hardware){const note=hardware.querySelector(".player-control-note");hardware.insertBefore(row,note||null);changed=true;}if(row){row.style.display="flex";row.dataset.nativeXboxControl="1";}const mirrorRow=mirror?.closest(".player-control-toggle");if(mirrorRow){mirrorRow.style.display="none";mirrorRow.setAttribute("aria-hidden","true");}hardware.dataset.xboxControlSource="native-reused-v1";}return changed;}
function installStyle(){if(document.querySelector("style[data-final-drone-weapon-dock]"))return;const style=document.createElement("style");style.dataset.finalDroneWeaponDock="v4";style.textContent=`#weaponSwitchDock{position:absolute;left:50%;bottom:max(12px,calc(var(--solo-safe-bottom,env(safe-area-inset-bottom)) + 8px));transform:translateX(-50%);z-index:10040;display:flex;align-items:center;justify-content:center;gap:6px;pointer-events:none;isolation:isolate}#weaponSwitchDock #droneWeaponToggle,#weaponSwitchDock #footWeaponToggle{position:static!important;inset:auto!important;transform:none!important;display:block;min-width:92px!important;width:auto!important;height:30px!important;padding:0 9px!important;margin:0!important;font-size:8px!important;z-index:auto!important;pointer-events:auto!important;touch-action:manipulation!important}body.on-foot-mode #weaponSwitchDock #droneWeaponToggle{display:none!important}body:not(.on-foot-mode) #weaponSwitchDock #footWeaponToggle{display:none!important}body.player-driving #weaponSwitchDock{bottom:max(54px,calc(var(--solo-safe-bottom,env(safe-area-inset-bottom)) + 50px))}#wantedEmpButton{z-index:10050!important;right:max(10px,var(--solo-safe-right,env(safe-area-inset-right)))!important;top:50%!important;width:72px!important;height:44px!important;padding:4px 5px!important;border-width:1px!important;border-radius:12px!important;gap:2px!important;transform:translateY(-50%)}#wantedEmpButton strong{font-size:15px!important}#wantedEmpButton small{font-size:6px!important;letter-spacing:.025em!important}#wantedEmpButton:not(:disabled):active{transform:translateY(-50%) scale(.94)!important}@media(max-height:340px){#wantedEmpButton{width:64px!important;height:38px!important;border-radius:10px!important}#wantedEmpButton strong{font-size:13px!important}#wantedEmpButton small{font-size:5.5px!important}}.player-control-hardware .phone-settings-toggle[data-native-xbox-control="1"]{display:flex!important;margin:4px 0 8px!important;border-top:0!important}`;document.head.appendChild(style);}
function frame(){dockWeapon();dockFootWeapon();bindReliableButton(document.getElementById("droneWeaponToggle"),"drone");dockXboxToggle();const view=document.getElementById("viewport");if(view)view.dataset.weaponSwitchDock="bottom-center-v1";requestAnimationFrame(frame);}
export function installGameplayFinalUiDock(){if(installed)return;installed=true;installStyle();requestAnimationFrame(frame);}
installGameplayFinalUiDock();
