import {AUDIO_SETTINGS_EVENT,loadAudioSettings,normalizeAudioSettings} from "./audio_settings.mjs";
import "./gameplay_final_runtime_v2.mjs";
import "./gameplay_final_ui_dock.mjs";
import "./gameplay_final_realism_patch.mjs";
import "./first_person_weapon_runtime_v3.mjs";
import "./gameplay_reliability_authority_v5.mjs";
import "./gameplay_reliability_runtime_v4.mjs";
import "./mobile_landscape_hud_compact.mjs";

let installed=false,ctx=null,master=null,engine=null,noiseBuffer=null,lastFrame=performance.now(),lastStepAt=-Infinity,lastWalkX=NaN,lastWalkY=NaN,settings=loadAudioSettings(),engineGear=1;
const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||0));
const ENGINE_RATIOS=[0,4.6,3.1,2.2,1.65,1.3],ENGINE_UPSHIFT=[0,8,14,21,30,Infinity],ENGINE_DOWNSHIFT=[0,0,6.4,11.8,18.5,27];
function viewport(){return document.getElementById("viewport");}
function ensure(){if(ctx)return ctx;const Ctx=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Ctx)return null;try{ctx=new Ctx({latencyHint:"interactive"});}catch{ctx=new Ctx();}master=ctx.createGain();master.gain.value=0;const limiter=ctx.createDynamicsCompressor();limiter.threshold.value=-12;limiter.ratio.value=4;limiter.attack.value=.003;limiter.release.value=.12;master.connect(limiter).connect(ctx.destination);noiseBuffer=ctx.createBuffer(1,ctx.sampleRate,ctx.sampleRate);const data=noiseBuffer.getChannelData(0);let s=0x43a17b29;for(let i=0;i<data.length;i++){s^=s<<13;s^=s>>>17;s^=s<<5;data[i]=((s>>>0)/2147483648)-1;}return ctx;}
async function unlock(){const c=ensure();if(!c)return;try{if(c.state!=="running")await c.resume();}catch{}syncMaster();}
function syncMaster(){if(!ctx||!master)return;master.gain.setTargetAtTime(settings.soundEnabled?1:0,ctx.currentTime,.03);}
function mix(category){const key=category==="footsteps"?"footstepsVolume":category==="vehicle"?"vehicleVolume":category==="ambient"?"ambientVolume":"fxVolume";return clamp(settings[key]??75,0,100)/100;}
function burst({gain=.03,low=80,high=900,duration=.12,pitch=100,category="fx"}={}){const volume=mix(category);if(!settings.soundEnabled||volume<=0||!ensure()||ctx.state!=="running")return;const now=ctx.currentTime,src=ctx.createBufferSource(),band=ctx.createBiquadFilter(),g=ctx.createGain(),thump=ctx.createOscillator(),tg=ctx.createGain();src.buffer=noiseBuffer;band.type="bandpass";band.frequency.value=(low+high)*.5;band.Q.value=.55;g.gain.setValueAtTime(gain*volume,now);g.gain.exponentialRampToValueAtTime(.0001,now+duration);src.connect(band).connect(g).connect(master);thump.type="sine";thump.frequency.setValueAtTime(pitch,now);thump.frequency.exponentialRampToValueAtTime(Math.max(35,pitch*.62),now+duration*.7);tg.gain.setValueAtTime(gain*.55*volume,now);tg.gain.exponentialRampToValueAtTime(.0001,now+duration);thump.connect(tg).connect(master);src.start(now,Math.random()*.6,duration);thump.start(now);thump.stop(now+duration+.02);}
function ensureEngine(){if(engine||!ensure())return engine;const low=ctx.createOscillator(),high=ctx.createOscillator(),lowGain=ctx.createGain(),highGain=ctx.createGain(),filter=ctx.createBiquadFilter(),texture=ctx.createBufferSource(),textureFilter=ctx.createBiquadFilter(),textureGain=ctx.createGain();low.type="sawtooth";high.type="triangle";low.frequency.value=48;high.frequency.value=96;lowGain.gain.value=0;highGain.gain.value=0;filter.type="lowpass";filter.frequency.value=900;texture.buffer=noiseBuffer;texture.loop=true;textureFilter.type="bandpass";textureFilter.frequency.value=700;textureFilter.Q.value=.8;textureGain.gain.value=0;low.connect(lowGain).connect(filter);high.connect(highGain).connect(filter);filter.connect(master);texture.connect(textureFilter).connect(textureGain).connect(master);low.start();high.start();texture.start();engine={low,high,lowGain,highGain,filter,texture,textureFilter,textureGain};return engine;}
function resolveEngineGear(speed){const value=Math.max(0,Number(speed)||0);while(engineGear<5&&value>ENGINE_UPSHIFT[engineGear])engineGear++;while(engineGear>1&&value<ENGINE_DOWNSHIFT[engineGear])engineGear--;return engineGear;}
function updateEngine(){const e=ensureEngine();if(!e||ctx.state!=="running")return;const drive=globalThis.__arondightVehicleDrive,active=Boolean(drive?.active),speed=Math.max(0,Number(drive?.speedMps)||0),throttle=clamp(Math.abs(Number(drive?.throttle)||0),0,1),gear=resolveEngineGear(speed),ratio=ENGINE_RATIOS[gear],baseRpm=clamp(850+speed*ratio*95+throttle*950,800,6500),now=ctx.currentTime,flutter=1+.012*Math.sin(now*13.7)+.006*Math.sin(now*21.1),rpm=baseRpm*flutter,volume=settings.soundEnabled?mix("vehicle"):0,target=active?volume:0;e.low.frequency.setTargetAtTime(34+rpm/35,now,.045);e.high.frequency.setTargetAtTime(68+rpm/18.5,now,.04);e.filter.frequency.setTargetAtTime(470+throttle*1500+rpm*.08,now,.055);e.textureFilter.frequency.setTargetAtTime(360+rpm*.16+throttle*420,now,.06);e.lowGain.gain.setTargetAtTime(target*(.018+.021*throttle),now,.04);e.highGain.gain.setTargetAtTime(target*(.005+.013*throttle),now,.04);e.textureGain.gain.setTargetAtTime(target*(.0025+.0065*throttle),now,.05);const view=viewport();if(view){view.dataset.vehicleAudioRpm=Math.round(baseRpm).toString();view.dataset.vehicleAudioGear=String(gear);view.dataset.vehicleAudioThrottle=throttle.toFixed(3);view.dataset.vehicleAudioLayer="gear-rpm+combustion-harmonics+load-texture-v4";view.dataset.vehicleAudioVolumePct=String(settings.vehicleVolume);}}
function updateFootsteps(now){const walk=globalThis.__arondightWalkMode,drive=globalThis.__arondightVehicleDrive;if(walk?.mode!=="foot"||drive?.active||walk?.dead||!walk.position){lastWalkX=lastWalkY=NaN;return;}const x=Number(walk.position.x)||0,y=Number(walk.position.y)||0;if(!Number.isFinite(lastWalkX)){lastWalkX=x;lastWalkY=y;return;}const dt=Math.max(.001,(now-lastFrame)/1000),speed=Math.hypot(x-lastWalkX,y-lastWalkY)/dt;lastWalkX=x;lastWalkY=y;if(speed<.65)return;const interval=speed>6?305:speed>4?390:485;if(now-lastStepAt<interval)return;lastStepAt=now;const alt=(Math.floor(now/interval)&1)?1.05:.95;burst({gain:.018*alt,low:75,high:980,duration:.095,pitch:88*alt,category:"footsteps"});const view=viewport();if(view){view.dataset.footstepAudio="filtered-impact-soft-v3";view.dataset.footstepVolumePct=String(settings.footstepsVolume);view.dataset.footstepCount=String((Number(view.dataset.footstepCount)||0)+1);}}
function frame(now=performance.now()){updateFootsteps(now);updateEngine();lastFrame=now;requestAnimationFrame(frame);}
function impact(event){const drive=globalThis.__arondightVehicleDrive,detail=event?.detail;if(!drive?.active||String(detail?.id||"")!==drive.vehicleId)return;const dv=Number(detail?.deltaVelocityMps)||0;if(dv<1.8)return;burst({gain:clamp(.015+dv*.004,.02,.07),low:55,high:560,duration:clamp(.09+dv*.012,.1,.22),pitch:65,category:"fx"});}
export function installImmersiveSoundscape(){if(installed)return;installed=true;addEventListener("pointerdown",unlock,{capture:true,passive:true});addEventListener("keydown",unlock,{capture:true});addEventListener(AUDIO_SETTINGS_EVENT,event=>{settings=normalizeAudioSettings(event.detail||loadAudioSettings());syncMaster();});addEventListener("arondight:world-physics-impact",impact);const view=viewport();if(view)view.dataset.soundscapeRuntime="drone+combat+footsteps+vehicle-mixer-v4";requestAnimationFrame(frame);}
installImmersiveSoundscape();
