let installed=false,lastMobileMode="";
function viewport(){return document.getElementById("viewport");}
function walk(){return globalThis.__arondightWalkMode||null;}
function footWeapons(){return globalThis.__arondightFootWeapons||null;}
function droneWeapons(){return globalThis.__arondightDroneWeapons||null;}
function compactWanted(){return (navigator.maxTouchPoints||0)>0;}
function currentWeaponName(onFoot){const api=onFoot?footWeapons():droneWeapons(),mode=String(api?.mode||"").trim();return(mode||"weapon").replaceAll("_"," ").toUpperCase();}
function clickSource(id){const el=document.getElementById(id);if(!el||el.disabled)return false;el.click();return true;}
function openSettings(){const buttons=[...document.querySelectorAll(".phone-settings-button")],button=buttons.at(-1)||buttons[0];if(!button)return false;button.click();return true;}
function restoreDroneFpv(){const button=document.getElementById("camFpv"),view=viewport();if(!button||button.disabled)return false;button.click();if(view){view.dataset.mobileDroneCameraRoute="fpv-direct-v1";view.dataset.mobileDroneCameraRequested="fpv";}return true;}
function setPlayerMode(next){const api=walk(),view=viewport();if(typeof api?.setMode==="function"){const result=api.setMode(next,{persist:true,reason:"mobile-dock-direct"});if(view)view.dataset.mobilePlayerModeRoute="walk-api-direct-v1";if(result==="drone")queueMicrotask(restoreDroneFpv);return result;}clickSource("playerModeButton");return api?.mode||"";}
function installEmpDirectRoute(){document.addEventListener("pointerdown",event=>{if(!compactWanted())return;const button=event.target?.closest?.("#wantedEmpButton");if(!button)return;const api=globalThis.__arondightWantedSystem;if(typeof api?.triggerEmp!=="function")return;event.preventDefault();event.stopImmediatePropagation();const result=api.triggerEmp(),view=viewport();if(view){view.dataset.mobileEmpRoute="wanted-api-direct-v1";view.dataset.mobileEmpResult=result?.activated?"activated":String(result?.reason||"gated");view.dataset.mobileEmpAffected=String(Number(result?.affected)||0);}},true);}
function installModeTransitionDisarmGuard(){document.addEventListener("click",event=>{const kill=event.target?.closest?.("#soloKill");if(!kill||event.isTrusted||walk()?.mode!=="foot")return;event.preventDefault();event.stopImmediatePropagation();const arm=document.getElementById("soloArm"),state=(document.getElementById("soloState")?.textContent||"").trim().toUpperCase(),active=state==="ARMED"||state==="ARMING"||arm?.classList.contains("armed")||arm?.classList.contains("arming");if(active)arm?.click?.();const view=viewport();if(view){view.dataset.droneStowDisarm="graceful-v1";view.dataset.droneStowEmergencyKill="0";}},true);}
function installStyle(){if(document.querySelector("style[data-mobile-gameplay-ui]"))return;const style=document.createElement("style");style.dataset.mobileGameplayUi="flight-first-v2";style.textContent=`
#mobileGameplayDock{display:none}
body.mobile-gameplay-compact.solo-flight #mobileGameplayDock{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:5px;position:absolute;top:max(5px,var(--solo-safe-top,env(safe-area-inset-top)));left:50%;transform:translateX(-50%);width:min(calc(100% - 18px),330px);z-index:46;pointer-events:auto;padding:4px;border:1px solid #7cccfb36;border-radius:11px;background:#071522d9;box-shadow:0 6px 18px #0007;backdrop-filter:blur(7px)}
body.mobile-gameplay-compact.solo-flight #mobileGameplayDock button{display:flex!important;align-items:center!important;justify-content:center!important;min-width:0;min-height:36px;margin:0;padding:0 7px!important;border-radius:8px;font-family:system-ui,-apple-system,"Segoe UI",sans-serif!important;font-size:9px!important;font-weight:900!important;line-height:1!important;text-align:center!important;letter-spacing:.035em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;touch-action:manipulation;-webkit-appearance:none;appearance:none}
body.mobile-gameplay-compact.solo-flight #mobileGameplayMode{background:#123b57!important;border-color:#5fc7ff88!important}body.mobile-gameplay-compact.solo-flight #mobileGameplayWeapon{background:#473312!important;border-color:#ffc56d88!important}body.mobile-gameplay-compact.solo-flight #mobileGameplaySettings{background:#202d42!important;border-color:#9db9dc66!important}
body.mobile-gameplay-compact.solo-flight #soloTopbar{display:none!important}
body.mobile-gameplay-compact.solo-flight #soloTopbarStatus,body.mobile-gameplay-compact.solo-flight #soloTopbarActions{display:none!important}
body.mobile-gameplay-compact.solo-flight #soloArm{display:flex!important;visibility:visible!important;pointer-events:auto!important;left:50%!important;right:auto!important;transform:translateX(-105%)!important;bottom:max(18px,calc(var(--solo-safe-bottom,env(safe-area-inset-bottom)) + 8px))!important;z-index:31!important}
body.mobile-gameplay-compact.solo-flight.on-foot-mode #soloArm{display:none!important}
body.mobile-gameplay-compact.solo-flight #soloKill{display:flex!important;left:50%!important;right:auto!important;transform:translateX(5%)!important;bottom:max(18px,calc(var(--solo-safe-bottom,env(safe-area-inset-bottom)) + 8px))!important;width:122px!important;min-width:122px!important;padding-inline:8px!important;font-size:8px!important;letter-spacing:.015em!important;white-space:nowrap!important;z-index:31!important}
body.mobile-gameplay-compact.solo-flight #soloArm,body.mobile-gameplay-compact.solo-flight #soloKill{align-items:center!important;justify-content:center!important;text-align:center!important;font-family:system-ui,-apple-system,"Segoe UI",sans-serif!important;font-weight:900!important;line-height:1!important;padding-top:0!important;padding-bottom:0!important}
body.mobile-gameplay-compact.solo-flight.on-foot-mode #soloKill{display:none!important}
body.mobile-gameplay-compact.solo-flight #droneWeaponToggle,body.mobile-gameplay-compact.solo-flight #footWeaponToggle{display:none!important}
@media(max-height:360px){body.mobile-gameplay-compact.solo-flight #mobileGameplayDock{width:min(calc(100% - 14px),300px);gap:3px;padding:3px}body.mobile-gameplay-compact.solo-flight #mobileGameplayDock button{min-height:32px;padding:0 5px!important;font-size:8px!important}body.mobile-gameplay-compact.solo-flight #soloArm,body.mobile-gameplay-compact.solo-flight #soloKill{bottom:max(12px,var(--solo-safe-bottom,env(safe-area-inset-bottom)))!important}}
`;document.head.appendChild(style);}
function mountDock(){const view=viewport();if(!view)return null;let dock=document.getElementById("mobileGameplayDock");if(dock)return dock;dock=document.createElement("div");dock.id="mobileGameplayDock";dock.setAttribute("role","toolbar");dock.setAttribute("aria-label","Mobile gameplay controls");dock.innerHTML='<button id="mobileGameplayMode" type="button">MODE</button><button id="mobileGameplayWeapon" type="button">WEAPON</button><button id="mobileGameplaySettings" type="button">SETTINGS</button>';view.appendChild(dock);const mode=dock.querySelector("#mobileGameplayMode"),weapon=dock.querySelector("#mobileGameplayWeapon"),settings=dock.querySelector("#mobileGameplaySettings");mode.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();const api=walk();setPlayerMode(api?.mode==="foot"?"drone":"foot");});weapon.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();const onFoot=walk()?.mode==="foot"||document.body.classList.contains("on-foot-mode"),api=onFoot?footWeapons():droneWeapons();api?.toggle?.();});settings.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();openSettings();});for(const button of[mode,weapon,settings])button.addEventListener("pointerdown",event=>event.stopPropagation());return dock;}
function sync(){const compact=compactWanted();document.body.classList.toggle("mobile-gameplay-compact",compact);const dock=mountDock(),view=viewport();if(!dock||!view){requestAnimationFrame(sync);return;}const onFoot=walk()?.mode==="foot"||document.body.classList.contains("on-foot-mode"),driving=document.body.classList.contains("player-driving"),currentMode=driving?"car":onFoot?"foot":"drone",mode=dock.querySelector("#mobileGameplayMode"),weapon=dock.querySelector("#mobileGameplayWeapon");if(compact&&currentMode==="drone"&&lastMobileMode!=="drone")queueMicrotask(restoreDroneFpv);lastMobileMode=currentMode;mode.textContent=driving?"CAR":onFoot?"ON FOOT":"DRONE";mode.disabled=driving;weapon.disabled=driving;weapon.textContent=`WEAPON · ${currentWeaponName(onFoot)}`;const kill=document.getElementById("soloKill");if(kill&&!onFoot){kill.textContent="EMERGENCY STOP";kill.setAttribute("aria-label","Emergency stop and disarm drone");}view.dataset.mobileGameplayUi=compact?"flight-first-v2":"desktop";view.dataset.mobileGameplayMode=currentMode;view.dataset.mobileGameplayWeapon=currentWeaponName(onFoot);requestAnimationFrame(sync);}
export function installMobileGameplayUi(){if(installed)return;installed=true;installStyle();installEmpDirectRoute();installModeTransitionDisarmGuard();requestAnimationFrame(sync);}
