import * as THREE from "three";
import {Box3dHitscanWorld} from "./box3d_hitscan.mjs";

const STORAGE_KEY="arondight45DroneWeaponExtendedV1";
const COOLDOWN_MS=4500;
const MAX_RANGE_M=360;
const BLAST_RADIUS_M=65;
const BLAST_MAX_DAMAGE=250;
const SHOCKWAVE_SPEED_MPS=343;
const SHOCKWAVE_MAX_M=280;
const MUSHROOM_LIFETIME_MS=26000;
const CAMERA_SHAKE_MAX_DISTANCE_M=240;
const raycaster=new THREE.Raycaster(),ndc=new THREE.Vector2(),boxHits=new Box3dHitscanWorld();
const tmp=new THREE.Vector3(),tmp2=new THREE.Vector3(),axis=new THREE.Vector3(0,-1,0),cameraWorld=new THREE.Vector3();
let installed=false,patchedApi=null,lastNuke=-Infinity,displayMode="gun",originalToggle=null,originalSetMode=null,originalFireMissile=null;
const warheads=[];
const impacts=[];

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function walk(){return globalThis.__arondightWalkMode||null;}
function drive(){return globalThis.__arondightVehicleDrive||null;}
function isDrone(){return walk()?.mode!=="foot"&&!drive()?.active;}
function clamp(v,a,b){return Math.max(a,Math.min(b,Number(v)||0));}
function persistedMode(){try{const value=localStorage.getItem(STORAGE_KEY);return ["gun","missile","nuke"].includes(value)?value:null;}catch{return null;}}
function saveMode(value){try{localStorage.setItem(STORAGE_KEY,value);}catch{}}
function logicalPoint(clientX,clientY){const view=viewport(),screen=view?.getBoundingClientRect();if(!view||!screen)return null;const width=Math.max(1,view.clientWidth),height=Math.max(1,view.clientHeight),cx=Number.isFinite(Number(clientX))?Number(clientX):screen.left+screen.width/2,cy=Number.isFinite(Number(clientY))?Number(clientY):screen.top+screen.height/2,rotated=view.dataset.soloOrientation==="css-landscape",x=rotated?cy-screen.top:cx-screen.left,y=rotated?screen.right-cx:cy-screen.top;return{x:clamp(x,0,width),y:clamp(y,0,height),width,height};}
function screenRay(clientX,clientY){const camera=bridge()?.threeCamera,p=logicalPoint(clientX,clientY);if(!camera||!p)return null;ndc.set(p.x/p.width*2-1,1-p.y/p.height*2);camera.updateMatrixWorld?.(true);raycaster.setFromCamera(ndc,camera);return{origin:raycaster.ray.origin.clone(),direction:raycaster.ray.direction.clone().normalize()};}
function ignored(node){for(let n=node;n;n=n.parent){const u=n.userData||{};if(u.flightFireIgnore||u.walkWeaponPart||u.arondightAirframe||u.localHumanAvatar||u.directFireMissile||u.nukeWeaponPart)return true;}return false;}
function candidates(scene){const out=[];scene?.traverse?.(node=>{if(!node?.isMesh||node.visible===false||node.material?.visible===false||ignored(node))return;out.push(node);});return out;}
function nearestHit(origin,direction,maxDistance){const b=bridge(),scene=b?.threeScene;if(!scene)return null;raycaster.set(origin,direction);raycaster.near=.03;raycaster.far=maxDistance;const sceneHit=raycaster.intersectObjects(candidates(scene),false)[0]||null;let staticHit=null;if(b.active&&b.buildingCollisionSnapshot){const hit=boxHits.cast([origin.x,origin.y,origin.z],[direction.x,direction.y,direction.z],maxDistance,b.buildingCollisionSnapshot);if(hit)staticHit={distance:hit.distanceM,point:new THREE.Vector3(...hit.point)};}return staticHit&&(!sceneHit||staticHit.distance<sceneHit.distance)?staticHit:sceneHit;}
function targetForRay(ray){const hit=nearestHit(ray.origin,ray.direction,MAX_RANGE_M);if(hit?.point)return hit.point.clone();const dz=ray.direction.z;if(Math.abs(dz)>.0001){const t=(0-ray.origin.z)/dz;if(t>1&&t<MAX_RANGE_M)return ray.origin.clone().addScaledVector(ray.direction,t);}return ray.origin.clone().addScaledVector(ray.direction,Math.min(120,MAX_RANGE_M));}

function ensureFlashOverlay(){const view=viewport();if(!view)return null;let el=document.getElementById("nukeFlashOverlay");if(el)return el;el=document.createElement("i");el.id="nukeFlashOverlay";el.setAttribute("aria-hidden","true");el.style.cssText="position:absolute;inset:0;z-index:80;pointer-events:none;background:radial-gradient(circle at 50% 50%,#fff 0%,#fffbe8 38%,#ffd89a 72%,#ff9f46 100%);opacity:0;mix-blend-mode:screen";view.appendChild(el);return el;}
function ensurePressureOverlay(){const view=viewport();if(!view)return null;let el=document.getElementById("nukePressureOverlay");if(el)return el;el=document.createElement("i");el.id="nukePressureOverlay";el.setAttribute("aria-hidden","true");el.style.cssText="position:absolute;inset:-8%;z-index:79;pointer-events:none;border:8px solid #fff8;border-radius:50%;opacity:0;box-shadow:inset 0 0 70px #fff7,0 0 80px #fff6";view.appendChild(el);return el;}
function flashScreen(){const el=ensureFlashOverlay();if(!el)return;el.getAnimations?.().forEach(a=>a.cancel());el.animate([{opacity:0},{opacity:1,offset:.025},{opacity:1,offset:.18},{opacity:.72,offset:.34},{opacity:.22,offset:.68},{opacity:0}],{duration:1750,easing:"cubic-bezier(.08,.7,.16,1)"});const view=viewport();if(view)view.dataset.nukeFlash="fullscreen-whiteout-v2";}
function pressurePulse(strength){const el=ensurePressureOverlay();if(!el)return;el.getAnimations?.().forEach(a=>a.cancel());const s=clamp(strength,0,1);el.animate([{opacity:.75*s,transform:"scale(.72)"},{opacity:.42*s,transform:"scale(1.05)",offset:.34},{opacity:0,transform:"scale(1.5)"}],{duration:520+420*s,easing:"cubic-bezier(.12,.78,.2,1)"});}
function material(color,opacity=1,additive=false){return new THREE.MeshBasicMaterial({color,transparent:opacity<1,opacity,depthWrite:false,blending:additive?THREE.AdditiveBlending:THREE.NormalBlending});}
function mark(group){group.traverse?.(node=>{node.userData.nukeWeaponPart=true;node.userData.flightFireIgnore=true;});group.userData.nukeWeaponPart=true;group.userData.flightFireIgnore=true;return group;}
function makeWarhead(scene,start,target,now){const group=new THREE.Group(),body=new THREE.Mesh(new THREE.CylinderGeometry(.055,.07,.42,10),new THREE.MeshStandardMaterial({color:0x6d735f,roughness:.55,metalness:.4})),nose=new THREE.Mesh(new THREE.ConeGeometry(.07,.16,10),new THREE.MeshStandardMaterial({color:0x343832,roughness:.5,metalness:.5}));nose.position.y=-.29;group.add(body,nose);group.position.copy(start);const direction=target.clone().sub(start).normalize();group.quaternion.setFromUnitVectors(axis,direction);mark(group);scene.add(group);const distance=start.distanceTo(target),duration=clamp(360+distance*5.2,520,1450);warheads.push({group,scene,start:start.clone(),target:target.clone(),born:now,duration,arc:clamp(distance*.035,.8,4.5)});return group;}
function sphere(scene,group,r,color,opacity=1,additive=false,segments=20){const mesh=new THREE.Mesh(new THREE.SphereGeometry(r,segments,Math.max(10,Math.round(segments*.6))),material(color,opacity,additive));group.add(mesh);return mesh;}
function cameraDistanceTo(position){const camera=bridge()?.threeCamera;if(!camera)return Infinity;camera.updateMatrixWorld?.(true);camera.getWorldPosition?.(cameraWorld);return cameraWorld.distanceTo(position);}
function shakeCamera(strength,distance){const view=viewport(),canvas=bridge()?.renderer?.domElement||view?.querySelector("canvas");if(!canvas?.animate)return;const s=clamp(strength,0,1),px=3+13*s,duration=520+780*s;canvas.getAnimations?.().filter(a=>a.effect?.getKeyframes?.().some?.(k=>String(k.transform||"").includes("translate"))).forEach(a=>a.cancel());canvas.animate([{transform:"translate3d(0,0,0)",filter:"brightness(1)"},{transform:`translate3d(${px}px,${-px*.55}px,0) rotate(${.45*s}deg)`,filter:`brightness(${1+.18*s})`,offset:.12},{transform:`translate3d(${-px*.8}px,${px*.35}px,0) rotate(${-0.35*s}deg)`,offset:.25},{transform:`translate3d(${px*.55}px,${px*.7}px,0) rotate(${.22*s}deg)`,offset:.39},{transform:`translate3d(${-px*.35}px,${-px*.45}px,0)`,offset:.56},{transform:"translate3d(0,0,0)",filter:"brightness(1)"}],{duration,easing:"cubic-bezier(.18,.72,.24,1)"});pressurePulse(s);if(view){view.dataset.nukeCameraShake="shockwave-arrival-v2";view.dataset.nukeCameraShakeStrength=s.toFixed(3);view.dataset.nukeCameraShakeDistanceM=Number(distance).toFixed(1);}}
function makeImpact(scene,position,now){const group=new THREE.Group();group.position.copy(position);mark(group);scene.add(group);
  const flash=sphere(scene,group,2.8,0xffffff,1,true,24),hot=sphere(scene,group,4.2,0xfff4bd,.98,true,24),fire=sphere(scene,group,6.4,0xff6a16,.94,true,24),fireOuter=sphere(scene,group,8.5,0xff3a08,.46,true,20);
  const shock=new THREE.Mesh(new THREE.RingGeometry(.985,1.015,96),material(0xfff7d6,.95,true));shock.position.z=.22;group.add(shock);
  const dust=new THREE.Mesh(new THREE.RingGeometry(.86,1.08,96),material(0xc9a06b,.38,false));dust.position.z=.12;group.add(dust);
  const stemMat=new THREE.MeshStandardMaterial({color:0x493e37,transparent:true,opacity:.0,roughness:1,depthWrite:false,emissive:0x190704,emissiveIntensity:.28}),capMat=new THREE.MeshStandardMaterial({color:0x574b43,transparent:true,opacity:.0,roughness:1,depthWrite:false,emissive:0x2b0b04,emissiveIntensity:.46});
  const stem=new THREE.Group(),cap=new THREE.Group();group.add(stem,cap);
  for(let i=0;i<11;i++){const puff=sphere(scene,stem,3.6+i*.34,0x4d4138,0,false,18);puff.material=stemMat.clone();puff.position.z=3.2+i*4.1;puff.scale.set(1.08,.96,1.42);puff.rotation.z=i*.57;}
  for(let i=0;i<18;i++){const a=i/18*Math.PI*2,rad=10.5+(i%4)*1.2,puff=sphere(scene,cap,5.8+(i%3)*.75,0x594b42,0,false,18);puff.material=capMat.clone();puff.position.set(Math.cos(a)*rad,Math.sin(a)*rad,47+(i%3)*1.9);puff.scale.set(1.55,1.55,.8);}
  const crown=sphere(scene,cap,10.8,0x5a4a41,0,false,22);crown.material=capMat.clone();crown.position.z=50.5;crown.scale.set(1.85,1.85,.72);
  const innerCrown=sphere(scene,cap,6.8,0xff6a1a,0,true,18);innerCrown.position.z=47.8;innerCrown.scale.set(1.6,1.6,.64);
  const light=new THREE.PointLight(0xffe0a0,420,420,1.12);light.position.z=18;group.add(light);
  const scorch=new THREE.Mesh(new THREE.CircleGeometry(22,64),new THREE.MeshBasicMaterial({color:0x110b08,transparent:true,opacity:.82,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-4,side:THREE.DoubleSide}));scorch.position.z=.035;group.add(scorch);
  impacts.push({group,scene,position:position.clone(),flash,hot,fire,fireOuter,shock,dust,stem,cap,innerCrown,light,scorch,born:now,until:now+MUSHROOM_LIFETIME_MS,shakeTriggered:false,shockRadius:0});
  flashScreen();
  window.dispatchEvent(new CustomEvent("arondight:world-explosion",{detail:{position:[position.x,position.y,position.z],radiusM:BLAST_RADIUS_M,maxDamage:BLAST_MAX_DAMAGE,kind:"nuke",source:"drone-nuke",targeted:true}}));
  window.dispatchEvent(new CustomEvent("arondight:nuke-impact",{detail:{position:[position.x,position.y,position.z],radiusM:BLAST_RADIUS_M,shockwaveSpeedMps:SHOCKWAVE_SPEED_MPS}}));
  const view=viewport();if(view){view.dataset.nukeImpacts=String((Number(view.dataset.nukeImpacts)||0)+1);view.dataset.nukeBlastRadius=String(BLAST_RADIUS_M);view.dataset.nukeEffect="flash-fireball-shockwave-mushroom-v1";view.dataset.nukeCinematic="whiteout+giant-fireball+physical-shockwave+mushroom+camera-shake-v2";view.dataset.nukeShockwaveSpeedMps=String(SHOCKWAVE_SPEED_MPS);view.dataset.nukeMushroomHeightM="58";}
}
function updateWarheads(now){for(let i=warheads.length-1;i>=0;i--){const item=warheads[i],t=clamp((now-item.born)/item.duration,0,1),e=t*t*(3-2*t);item.group.position.lerpVectors(item.start,item.target,e);item.group.position.z+=Math.sin(Math.PI*t)*item.arc;const dir=tmp.copy(item.target).sub(item.group.position).normalize();if(dir.lengthSq()>.001)item.group.quaternion.setFromUnitVectors(axis,dir);if(t>=1){item.scene.remove(item.group);warheads.splice(i,1);makeImpact(item.scene,item.target,now);}}}
function updateImpacts(now){for(let i=impacts.length-1;i>=0;i--){const item=impacts[i],age=now-item.born,t=clamp(age/MUSHROOM_LIFETIME_MS,0,1),blastT=clamp(age/1800,0,1),blastEase=1-(1-blastT)**3;
    item.flash.scale.setScalar(1+22*blastEase);item.hot.scale.setScalar(1+5.3*blastEase);item.fire.scale.setScalar(1+3.4*blastEase);item.fireOuter.scale.setScalar(1+2.7*blastEase);item.flash.material.opacity=Math.max(0,1-blastT*1.8);item.hot.material.opacity=.98*Math.max(.08,1-blastT*.72);item.fire.material.opacity=.94*Math.max(.06,1-blastT*.8);item.fireOuter.material.opacity=.46*Math.max(.04,1-blastT*.88);item.light.intensity=420*Math.max(0,1-blastT*.9);
    const shockRadius=Math.min(SHOCKWAVE_MAX_M,Math.max(1,age/1000*SHOCKWAVE_SPEED_MPS));item.shockRadius=shockRadius;item.shock.scale.setScalar(shockRadius);item.dust.scale.setScalar(shockRadius*.96);const shockFade=1-clamp(shockRadius/SHOCKWAVE_MAX_M,0,1);item.shock.material.opacity=.95*shockFade**.7;item.dust.material.opacity=.38*shockFade**.55;
    const cameraDistance=cameraDistanceTo(item.position);if(!item.shakeTriggered&&Number.isFinite(cameraDistance)&&shockRadius>=cameraDistance){item.shakeTriggered=true;const strength=clamp(1-cameraDistance/CAMERA_SHAKE_MAX_DISTANCE_M,.08,1);shakeCamera(strength,cameraDistance);const view=viewport();if(view)view.dataset.nukeShockArrivalMs=String(Math.round(age));}
    const cloudT=clamp((age-480)/7800,0,1),rise=1-(1-cloudT)**2;item.stem.visible=age>260;item.cap.visible=age>420;item.stem.position.z=rise*5.5;item.cap.position.z=rise*12.5;item.stem.scale.setScalar(.45+1.05*rise);item.cap.scale.setScalar(.32+1.18*rise);for(const mesh of item.stem.children)mesh.material.opacity=.88*Math.min(1,cloudT*3)*(1-t*.55);for(const mesh of item.cap.children){mesh.material.opacity=.9*Math.min(1,cloudT*3)*(1-t*.48);}item.innerCrown.material.opacity=.62*Math.min(1,cloudT*4)*Math.max(0,1-cloudT*.95);item.scorch.material.opacity=.82*(1-clamp((age-18000)/8000,0,1));
    const view=viewport();if(view){view.dataset.nukeShockwaveRadiusM=shockRadius.toFixed(1);view.dataset.nukeCloudProgress=cloudT.toFixed(3);}
    if(now>=item.until){item.scene.remove(item.group);impacts.splice(i,1);}}
}

function fireNuke({clientX,clientY,source="external"}={}){const now=performance.now(),view=viewport();if(displayMode!=="nuke"||!isDrone()||globalThis.__arondightDroneDamageModel?.destroyed||view?.dataset.fireArmed!=="1"||now-lastNuke<COOLDOWN_MS)return false;const ray=screenRay(clientX,clientY),scene=bridge()?.threeScene;if(!ray||!scene)return false;lastNuke=now;const target=targetForRay(ray),start=ray.origin.clone().addScaledVector(ray.direction,.45).add(new THREE.Vector3(0,0,-.08));makeWarhead(scene,start,target,now);if(view){view.dataset.droneWeapon="nuke";view.dataset.nukeLaunches=String((Number(view.dataset.nukeLaunches)||0)+1);view.dataset.nukeInput=String(source);view.dataset.nukeTarget=`${target.x.toFixed(2)},${target.y.toFixed(2)},${target.z.toFixed(2)}`;view.dataset.nukeContract="drone-targeted-fixed-impact-v1";}return true;}
function applyDisplayMode(next){if(!["gun","missile","nuke"].includes(next))return displayMode;displayMode=next;saveMode(displayMode);if(displayMode==="gun")originalSetMode?.("gun");else originalSetMode?.("missile");const view=viewport();if(view){view.dataset.droneExtendedWeapon=displayMode;view.dataset.nukeSelected=displayMode==="nuke"?"1":"0";}return displayMode;}
function cycle(){return applyDisplayMode(displayMode==="gun"?"missile":displayMode==="missile"?"nuke":"gun");}
function patchApi(){const api=globalThis.__arondightDroneWeapons;if(!api)return false;if(api===patchedApi)return true;patchedApi=api;originalToggle=api.toggle?.bind(api)||null;originalSetMode=api.setMode?.bind(api)||null;originalFireMissile=api.fireMissile?.bind(api)||null;displayMode=persistedMode()||String(api.mode||"gun");if(!["gun","missile","nuke"].includes(displayMode))displayMode="gun";api.toggle=cycle;api.setMode=mode=>applyDisplayMode(String(mode));api.fireNuke=fireNuke;api.fireMissile=args=>displayMode==="nuke"?fireNuke(args):Boolean(originalFireMissile?.(args));Object.defineProperty(api,"displayMode",{configurable:true,enumerable:true,get:()=>displayMode});applyDisplayMode(displayMode);const view=viewport();if(view)view.dataset.nukeWeapon="enabled-v2";return true;}
function frame(now=performance.now()){patchApi();updateWarheads(now);updateImpacts(now);requestAnimationFrame(frame);}

export function installNukeWeapon(){if(installed)return;installed=true;ensureFlashOverlay();ensurePressureOverlay();requestAnimationFrame(frame);}
installNukeWeapon();
