import * as THREE from "three";

const effects=[];
let installed=false;
const tmpCam=new THREE.Vector3(),tmpDir=new THREE.Vector3();

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function clamp(v,a,b){return Math.max(a,Math.min(b,Number(v)||0));}
function easeOut(t){t=clamp(t,0,1);return 1-Math.pow(1-t,3);}
function smooth(t){t=clamp(t,0,1);return t*t*(3-2*t);}
function tag(node,role){node.userData.nukeWeaponPart=true;node.userData.flightFireIgnore=true;node.userData.nukeOverkillPart=true;node.userData.nukeOverkillRole=role;return node;}
function basic(color,opacity=1,additive=false){return new THREE.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false,depthTest:true,blending:additive?THREE.AdditiveBlending:THREE.NormalBlending,side:THREE.DoubleSide});}
function sphere(group,r,color,opacity,additive,role,segments=28){const m=tag(new THREE.Mesh(new THREE.SphereGeometry(r,segments,Math.max(14,Math.floor(segments*.62))),basic(color,opacity,additive)),role);group.add(m);return m;}
function smokeMat(color,opacity=.86){return new THREE.MeshStandardMaterial({color,transparent:true,opacity,roughness:1,depthWrite:false,emissive:0x120503,emissiveIntensity:.32});}
function ensureOverlay(){const view=viewport();if(!view)return null;let el=document.getElementById("nukeOverkillOverlay");if(el)return el;el=document.createElement("i");el.id="nukeOverkillOverlay";el.setAttribute("aria-hidden","true");el.style.cssText="position:absolute;inset:-10%;z-index:88;pointer-events:none;opacity:0;background:radial-gradient(circle at 50% 52%,rgba(255,255,255,1) 0 14%,rgba(255,252,213,.98) 24%,rgba(255,166,48,.9) 48%,rgba(177,43,5,.66) 72%,rgba(22,0,0,.4) 100%)";view.appendChild(el);return el;}
function ensureVignette(){const view=viewport();if(!view)return null;let el=document.getElementById("nukeOverkillVignette");if(el)return el;el=document.createElement("i");el.id="nukeOverkillVignette";el.setAttribute("aria-hidden","true");el.style.cssText="position:absolute;inset:-5%;z-index:87;pointer-events:none;opacity:0;background:radial-gradient(circle at 50% 52%,transparent 24%,rgba(255,95,0,.18) 48%,rgba(102,15,0,.62) 74%,rgba(5,0,0,.9) 100%)";view.appendChild(el);return el;}
function ensureShockScreen(){const view=viewport();if(!view)return null;let el=document.getElementById("nukeOverkillShockScreen");if(el)return el;el=document.createElement("i");el.id="nukeOverkillShockScreen";el.setAttribute("aria-hidden","true");el.style.cssText="position:absolute;left:50%;top:52%;width:18vmin;aspect-ratio:1;border:5px solid rgba(255,250,225,.95);border-radius:50%;z-index:89;pointer-events:none;opacity:0;transform:translate(-50%,-50%) scale(.12);box-shadow:0 0 26px 9px rgba(255,179,75,.85),inset 0 0 28px rgba(255,255,255,.9)";view.appendChild(el);return el;}
function screenBlast(){const a=ensureOverlay(),v=ensureVignette(),s=ensureShockScreen();if(a){a.getAnimations?.().forEach(x=>x.cancel());a.animate([{opacity:0,filter:"brightness(1)"},{opacity:1,filter:"brightness(5)",offset:.018},{opacity:1,filter:"brightness(3.2)",offset:.16},{opacity:.92,filter:"brightness(1.9)",offset:.34},{opacity:.72,filter:"brightness(1.35)",offset:.62},{opacity:.34,filter:"brightness(1.1)",offset:.82},{opacity:0,filter:"brightness(1)"}],{duration:7200,easing:"cubic-bezier(.08,.72,.16,1)"});}if(v){v.getAnimations?.().forEach(x=>x.cancel());v.animate([{opacity:0},{opacity:.92,offset:.09},{opacity:.78,offset:.42},{opacity:.55,offset:.72},{opacity:0}],{duration:7600,easing:"ease-out"});}if(s){s.getAnimations?.().forEach(x=>x.cancel());s.animate([{opacity:0,transform:"translate(-50%,-50%) scale(.08)"},{opacity:1,transform:"translate(-50%,-50%) scale(.32)",offset:.04},{opacity:.9,transform:"translate(-50%,-50%) scale(1.1)",offset:.22},{opacity:.52,transform:"translate(-50%,-50%) scale(3.2)",offset:.5},{opacity:.12,transform:"translate(-50%,-50%) scale(6.6)",offset:.78},{opacity:0,transform:"translate(-50%,-50%) scale(8.4)"}],{duration:4200,easing:"cubic-bezier(.12,.72,.14,1)"});}}
function makeShock(group,role,color,opacity=.95){const ring=tag(new THREE.Mesh(new THREE.RingGeometry(.985,1.015,160),basic(color,opacity,true)),role);ring.position.z=.42;group.add(ring);return ring;}
function presentationAnchor(position){const camera=bridge()?.threeCamera;if(!camera)return new THREE.Vector3(position.x,position.y,Math.min(position.z,0));camera.updateMatrixWorld?.(true);camera.getWorldPosition(tmpCam);tmpDir.set(position.x-tmpCam.x,position.y-tmpCam.y,0);if(tmpDir.lengthSq()<.0001){camera.getWorldDirection(tmpDir);tmpDir.z=0;}if(tmpDir.lengthSq()<.0001)tmpDir.set(0,-1,0);tmpDir.normalize();const horizontal=Math.hypot(position.x-tmpCam.x,position.y-tmpCam.y),distance=clamp(horizontal,120,165),anchor=tmpCam.clone().addScaledVector(tmpDir,distance);anchor.z=0;return anchor;}
function spawn(position){const b=bridge(),scene=b?.threeScene;if(!scene)return;const group=tag(new THREE.Group(),"root"),anchor=presentationAnchor(position);group.position.copy(anchor);scene.add(group);
  const white=sphere(group,9,0xffffff,1,true,"white-core",36),yellow=sphere(group,15,0xfff2a1,.98,true,"yellow-core",36),orange=sphere(group,23,0xff7a12,.94,true,"orange-fireball",34),red=sphere(group,31,0xff2a05,.68,true,"red-fireball",30);for(const m of[white,yellow,orange,red])m.position.z=13;
  const shock1=makeShock(group,"shock-ring-1",0xffffff,1),shock2=makeShock(group,"shock-ring-2",0xffd18a,.92),shock3=makeShock(group,"shock-ring-3",0xff7a2e,.76);
  const dust=tag(new THREE.Mesh(new THREE.RingGeometry(.72,1.28,160),basic(0xb87842,.65,false)),"dust-ring");dust.position.z=.12;group.add(dust);
  const stem=tag(new THREE.Group(),"smoke-stem"),cap=tag(new THREE.Group(),"smoke-cap");group.add(stem,cap);const stemPuffs=[],capPuffs=[];
  for(let i=0;i<18;i++){const puff=sphere(stem,8.5+i*.32,0x443630,0,false,`stem-${i}`,20);puff.material=smokeMat(i<5?0x684438:0x3b3432,.92);puff.position.set(Math.sin(i*.8)*2.4,Math.cos(i*.63)*2,4+i*3.0);puff.scale.set(1.5,1.35,1.32);stemPuffs.push(puff);}
  for(let i=0;i<38;i++){const a=i/38*Math.PI*2,rad=29+(i%6)*2.8,puff=sphere(cap,11+(i%5)*1.35,0x4a3a34,0,false,`cap-${i}`,20);puff.material=smokeMat(i%4===0?0x70483a:0x403735,.94);puff.position.set(Math.cos(a)*rad,Math.sin(a)*rad,58+(i%4)*2.2);puff.scale.set(2.35,2.35,.72);capPuffs.push(puff);}
  const crown=sphere(cap,25,0x453735,0,false,"crown",30);crown.material=smokeMat(0x493632,.96);crown.position.z=65;crown.scale.set(3.05,3.05,.68);
  const hotCrown=sphere(cap,17,0xff5410,0,true,"hot-crown",26);hotCrown.position.z=60;hotCrown.scale.set(2.75,2.75,.56);
  const hotColumn=tag(new THREE.Mesh(new THREE.CylinderGeometry(7,16,58,36,1,true),basic(0xff5510,.82,true)),"hot-column");hotColumn.rotation.x=Math.PI/2;hotColumn.position.z=29;group.add(hotColumn);
  const halo=tag(new THREE.Mesh(new THREE.TorusGeometry(48,2.8,18,128),basic(0xffc76c,.9,true)),"halo");halo.position.z=48;group.add(halo);
  const light=new THREE.PointLight(0xffd69a,2400,980,1.0);light.position.z=30;group.add(light);
  effects.push({group,scene,born:performance.now(),white,yellow,orange,red,shock1,shock2,shock3,dust,stemPuffs,capPuffs,crown,hotCrown,hotColumn,halo,light,anchor});
  const view=viewport();if(view){view.dataset.nukeOverkill="screen-dominating-nuclear-v2";view.dataset.nukeOverkillParts=String(4+4+stemPuffs.length+capPuffs.length+4);view.dataset.nukeOverkillMushroomM="78";view.dataset.nukeOverkillFireballM="110";view.dataset.nukeOverkillAnchor=`${anchor.x.toFixed(2)},${anchor.y.toFixed(2)},${anchor.z.toFixed(2)}`;view.dataset.nukeOverkillComposition="grounded-wide-in-frame-v2";}
  screenBlast();
}
function update(item,now){const age=now-item.born,fireT=easeOut(age/2100),fade=1-clamp((age-6100)/4600,0,1),shockT=clamp(age/4300,0,1),cloudT=smooth((age-420)/4700),late=clamp((age-3500)/10000,0,1);
  item.white.scale.setScalar(.38+fireT*6.2);item.yellow.scale.setScalar(.42+fireT*5.6);item.orange.scale.setScalar(.46+fireT*4.7);item.red.scale.setScalar(.5+fireT*4.0);
  item.white.material.opacity=Math.max(0,(1-age/1900)*.99);item.yellow.material.opacity=Math.max(0,(1-age/3200)*.94);item.orange.material.opacity=Math.max(0,(1-age/5200)*.86);item.red.material.opacity=Math.max(0,(1-age/6800)*.58);
  const r1=34+shockT*500,r2=22+clamp((age-220)/4300,0,1)*450,r3=12+clamp((age-480)/4400,0,1)*390;item.shock1.scale.setScalar(r1);item.shock2.scale.setScalar(r2);item.shock3.scale.setScalar(r3);item.dust.scale.setScalar(20+shockT*320);item.shock1.material.opacity=.99*fade;item.shock2.material.opacity=.8*fade;item.shock3.material.opacity=.62*fade;item.dust.material.opacity=.5*fade;
  const cloudOpacity=clamp(cloudT*1.45,0,.98)*(1-late*.42);for(let i=0;i<item.stemPuffs.length;i++){const p=item.stemPuffs[i],rise=cloudT*(1+i*.026);p.material.opacity=cloudOpacity*(.74+i*.012);p.position.z=4+i*3+rise*(5+i*.24);p.scale.multiplyScalar(1.001);}for(let i=0;i<item.capPuffs.length;i++){const p=item.capPuffs[i];p.material.opacity=cloudOpacity*.91;p.position.z=58+(i%4)*2.2+cloudT*8;p.scale.multiplyScalar(1.00135);}
  item.crown.material.opacity=cloudOpacity*.94;item.crown.position.z=65+cloudT*9;item.crown.scale.set(3.05+cloudT*1.05,3.05+cloudT*1.05,.68+cloudT*.12);item.hotCrown.material.opacity=Math.max(0,.82-age/7600);item.hotColumn.material.opacity=Math.max(0,.8-age/8200);item.halo.material.opacity=Math.max(0,.86-age/6800);item.halo.scale.setScalar(1+cloudT*1.65);item.light.intensity=Math.max(0,2400*(1-age/7200));
  const view=viewport();if(view){view.dataset.nukeOverkillPhase=age<1100?"whiteout":age<3100?"fireball":age<6500?"shockwave+mushroom":"mushroom";view.dataset.nukeOverkillShockM=r1.toFixed(0);view.dataset.nukeOverkillCloud=cloudT.toFixed(3);}
  return age<30000;
}
function frame(now){for(let i=effects.length-1;i>=0;i--){const item=effects[i];if(update(item,now))continue;item.scene?.remove(item.group);item.group.traverse?.(n=>{n.geometry?.dispose?.();const mats=Array.isArray(n.material)?n.material:[n.material];mats.filter(Boolean).forEach(m=>m.dispose?.());});effects.splice(i,1);}requestAnimationFrame(frame);}
function install(){if(installed)return;installed=true;window.addEventListener("arondight:nuke-impact",event=>{const p=event?.detail?.position;if(!Array.isArray(p)||p.length<3)return;spawn(new THREE.Vector3(Number(p[0])||0,Number(p[1])||0,Number(p[2])||0));});requestAnimationFrame(frame);}
install();