import * as THREE from "three";
import {Box3dHitscanWorld} from "./box3d_hitscan.mjs";

const STORAGE_KEY="arondight45DroneWeaponExtendedV1";
const COOLDOWN_MS=4500;
const MAX_RANGE_M=360;
const GROUND_BURST_Z=0;
const BLAST_RADIUS_M=120;
const BLAST_MAX_DAMAGE=1000;
const SHOCKWAVE_SPEED_MPS=343;
const SHOCKWAVE_MAX_M=520;
const MUSHROOM_HEIGHT_M=108;
const MUSHROOM_LIFETIME_MS=32000;
const CAMERA_SHAKE_MAX_DISTANCE_M=400;
const CINEMATIC_GRACE_MS=4200;
const raycaster=new THREE.Raycaster(),ndc=new THREE.Vector2(),boxHits=new Box3dHitscanWorld();
const tmp=new THREE.Vector3(),axis=new THREE.Vector3(0,-1,0),cameraWorld=new THREE.Vector3();
let installed=false,patchedApi=null,lastNuke=-Infinity,displayMode="gun",originalToggle=null,originalSetMode=null,originalFireMissile=null;
const warheads=[];
const impacts=[];

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function walk(){return globalThis.__arondightWalkMode||null;}
function drive(){return globalThis.__arondightVehicleDrive||null;}
function isDrone(){return walk()?.mode!=="foot"&&!drive()?.active;}
function clamp(v,a,b){return Math.max(a,Math.min(b,Number(v)||0);}
function persistedMode(){try{const value=localStorage.getItem(STORAGE_KEY);return ["gun","missile","nuke"].includes(value)?value:null;}catch{return null;}}
function saveMode(value){try{localStorage.setItem(STORAGE_KEY,value);}catch{}}
function logicalPoint(clientX,clientY){const view=viewport(),screen=view?.getBoundingClientRect();if(!view||!screen)return null;const width=Math.max(1,view.clientWidth),height=Math.max(1,view.clientHeight),cx=Number.isFinite(Number(clientX))?Number(clientX):screen.left+screen.width/2,cy=Number.isFinite(Number(clientY))?Number(clientY):screen.top+screen.height/2,rotated=view.dataset.soloOrientation==="css-landscape",x=rotated?cy-screen.top:cx-screen.left,y=rotated?screen.right-cx:cy-screen.top;return{x:clamp(x,0,width),y:clamp(y,0,height),width,height};}
function screenRay(clientX,clientY){const camera=bridge()?.threeCamera,p=logicalPoint(clientX,clientY);if(!camera||!p)return null;ndc.set(p.x/p.width*2-1,1-p.y/p.height*2);camera.updateMatrixWorld?.(true);raycaster.setFromCamera(ndc,camera);return{origin:raycaster.ray.origin.clone(),direction:raycaster.ray.direction.clone().normalize()};}
function ignored(node){for(let n=node;n;n=n.parent){const u=n.userData||{};if(u.flightFireIgnore||u.walkWeaponPart||u.arondightAirframe||u.localHumanAvatar||u.directFireMissile||u.nukeWeaponPart)return true;}return false;}
function candidates(scene){const out=[];scene?.traverse?.(node=>{if(!node?.isMesh||node.visible===false||node.material?.visible===false||ignored(node))return;out.push(node);});return out;}
function nearestHit(origin,direction,maxDistance){const b=bridge(),scene=b?.threeScene;if(!scene)return null;raycaster.set(origin,direction);raycaster.near=.03;raycaster.far=maxDistance;const sceneHit=raycaster.intersectObjects(candidates(scene),false)[0]||null;let staticHit=null;if(b.active&&b.buildingCollisionSnapshot){const hit=boxHits.cast([origin.x,origin.y,origin.z],[direction.x,direction.y,direction.z],maxDistance,b.buildingCollisionSnapshot);if(hit)staticHit={distance:hit.distanceM,point:new THREE.Vector3(...hit.point)};}return staticHit&&(!sceneHit||staticHit.distance<sceneHit.distance)?staticHit:sceneHit;}
function groundBurstPoint(point){const target=point.clone();target.z=GROUND_BURST_Z;return target;}
function targetForRay(ray){const hit=nearestHit(ray.origin,ray.direction,MAX_RANGE_M);if(hit?.point)return groundBurstPoint(hit.point);const dz=ray.direction.z;if(Math.abs(dz)>.0001){const t=(GROUND_BURST_Z-ray.origin.z)/dz;if(t>1&&t<MAX_RANGE_M)return groundBurstPoint(ray.origin.clone().addScaledVector(ray.direction,t));}return groundBurstPoint(ray.origin.clone().addScaledVector(ray.direction,Math.min(140,MAX_RANGE_M)));}

function tag(node,role="part"){node.userData.nukeWeaponPart=true;node.userData.flightFireIgnore=true;node.userData.nukeRole=role;return node;}
function ensureFlashOverlay(){const view=viewport();if(!view)return null;let el=document.getElementById("nukeFlashOverlay");if(el)return el;el=document.createElement("i");el.id="nukeFlashOverlay";el.setAttribute("aria-hidden","true");el.style.cssText="position:absolute;inset:-2%;z-index:80;pointer-events:none;background:radial-gradient(circle at 50% 48%,#fff 0%,#fff 24%,#fff8d5 48%,#ffbf62 75%,#ff6a18 100%);opacity:0;mix-blend-mode:screen";view.appendChild(el);return el;}
function ensurePressureOverlay(){const view=viewport();if(!view)return null;let el=document.getElementById("nukePressureOverlay");if(el)return el;el=document.createElement("i");el.id="nukePressureOverlay";el.setAttribute("aria-hidden","true");el.style.cssText="position:absolute;inset:-12%;z-index:79;pointer-events:none;border:12px solid #fff9;border-radius:50%;opacity:0;box-shadow:inset 0 0 110px #fff9,0 0 120px #fff8";view.appendChild(el);return el;}
function flashScreen(){const el=ensureFlashOverlay();if(!el)return;el.getAnimations?.().forEach(a=>a.cancel());el.animate([{opacity:0},{opacity:1,offset:.018},{opacity:1,offset:.22},{opacity:.82,offset:.38},{opacity:.36,offset:.62},{opacity:0}],{duration:2600,easing:"cubic-bezier(.06,.7,.12,1)"});const view=viewport();if(view)view.dataset.nukeFlash="fullscreen-whiteout-v3";}
function pressurePulse(strength){const el=ensurePressureOverlay();if(!el)return;el.getAnimations?.().forEach(a=>a.cancel());const s=clamp(strength,0,1);el.animate([{opacity:.92*s,transform:"scale(.52)",filter:"blur(0px)"},{opacity:.55*s,transform:"scale(1.0)",filter:"blur(1px)",offset:.28},{opacity:.18*s,transform:"scale(1.35)",filter:"blur(2px)",offset:.58},{opacity:0,transform:"scale(1.8)",filter:"blur(3px)"}],{duration:780+620*s,easing:"cubic-bezier(.1,.78,.18,1)"});}
function material(color,opacity=1,additive=false){return new THREE.MeshBasicMaterial({color,transparent:opacity<1,opacity,depthWrite:false,blending:additive?THREE.AdditiveBlending:THREE.NormalBlending,side:THREE.DoubleSide});}
function sphere(group,r,color,opacity=1,additive=false,segments=20,role="part"){const mesh=tag(new THREE.Mesh(new THREE.SphereGeometry(r,segments,Math.max(10,Math.round(segments*.6))),material(color,opacity,additive)),role);group.add(mesh);return mesh;}
function makeWarhead(scene,start,target,now){const group=tag(new THREE.Group(),"warhead"),body=tag(new THREE.Mesh(new THREE.CylinderGeometry(.055,.07,.42,10),new THREE.MeshStandardMaterial({color:0x6d735f,roughness:.55,metalness:.4})),"warhead-body"),nose=tag(new THREE.Mesh(new THREE.ConeGeometry(.07,.16,10),new THREE.MeshStandardMaterial({color:0x343832,roughness:.5,metalness:.5})),"warhead-nose");nose.position.y=-.29;group.add(body,nose);group.position.copy(start);const direction=target.clone().sub(start).normalize();group.quaternion.setFromUnitVectors(axis,direction);scene.add(group);const distance=start.distanceTo(target),duration=clamp(360+distance*5.2,520,1450);warheads.push({group,scene,start:start.clone(),target:target.clone(),born:now,duration,arc:clamp(distance*.035,.8,4.5)});return group;}
function cameraDistanceTo(position){const camera=bridge()?.threeCamera;if(!camera)return Infinity;camera.updateMatrixWorld?.(true);camera.getWorldPosition?.(cameraWorld);return cameraWorld.distanceTo(position);}
function shakeCamera(strength,distance){const view=viewport(),canvas=bridge()?.renderer?.domElement||view?.querySelector("canvas");if(!canvas?.animate)return;const s=clamp(strength,0,1),px=5+22*s,duration=720+1050*s;canvas.getAnimations?.().filter(a=>a.effect?.getKeyframes?.().some?.(k=>String(k.transform||"").includes("translate"))).forEach(a=>a.cancel());canvas.animate([{transform:"translate3d(0,0,0)",filter:"brightness(1) contrast(1)"},{transform:`translate3d(${px}px,${-px*.62}px,0) rotate(${.7*s}deg)`,filter:`brightness(${1+.32*s}) contrast(${1+.15*s}) blur(${1.2*s}px)`,offset:.1},{transform:`translate3d(${-px*.9}px,${px*.42}px,0) rotate(${-0.56*s}deg)`,offset:.22},{transform:`translate3d(${px*.65}px,${px*.76}px,0) rotate(${.4*s}deg)`,offset:.36},{transform:`translate3d(${-px*.5}px,${-px*.58}px,0) rotate(${-0.25*s}deg)`,offset:.52},{transform:`translate3d(${px*.24}px,${-px*.18}px,0)`,offset:.72},{transform:"translate3d(0,0,0)",filter:"brightness(1) contrast(1) blur(0px)"}],{duration,easing:"cubic-bezier(.16,.72,.22,1)"});pressurePulse(s);if(view){view.dataset.nukeCameraShake="shockwave-arrival-v3";view.dataset.nukeCameraShakeStrength=s.toFixed(3);view.dataset.nukeCameraShakeDistanceM=Number(distance).toFixed(1);}}
function dispatchBlastDamage(item,age){if(item.damageTriggered)return;item.damageTriggered=true;window.dispatchEvent(new CustomEvent("arondight:world-explosion",{detail:{position:[item.position.x,item.position.y,item.position.z],radiusM:BLAST_RADIUS_M,maxDamage:BLAST_MAX_DAMAGE,kind:"nuke",source:"drone-nuke",targeted:true,cinematicGraceMs:CINEMATIC_GRACE_MS}}));const view=viewport();if(view){view.dataset.nukeDamageState="released-after-cinematic-v1";view.dataset.nukeDamageReleaseMs=String(Math.round(age));}}
function makeImpact(scene,position,now){const group=tag(new THREE.Group(),"impact-root");group.position.copy(position);scene.add(group);
  const flash=sphere(group,5.5,0xffffff,1,true,28,"flash-core"),hot=sphere(group,8.5,0xfff4bb,.99,true,28,"hot-core"),fire=sphere(group,12.5,0xff7118,.97,true,28,"fireball"),fireOuter=sphere(group,18,0xff3108,.58,true,24,"fireball-outer");
  const shock=tag(new THREE.Mesh(new THREE.RingGeometry(.992,1.008,128),material(0xfff8dc,.98,true)),"shockwave-ring");shock.position.z=.28;group.add(shock);
  const dust=tag(new THREE.Mesh(new THREE.RingGeometry(.88,1.12,128),material(0xd2a56e,.48,false)),"shockwave-dust");dust.position.z=.14;group.add(dust);
  const wall=tag(new THREE.Mesh(new THREE.CylinderGeometry(1,1,8,96,1,true),material(0xfff1c0,.28,true)),"shockwave-wall");wall.rotation.x=Math.PI/2;wall.position.z=4;group.add(wall);
  const stemMat=new THREE.MeshStandardMaterial({color:0x403832,transparent:true,opacity:0,roughness:1,depthWrite:false,emissive:0x1c0703,emissiveIntensity:.38}),capMat=new THREE.MeshStandardMaterial({color:0x4e443e,transparent:true,opacity:0,roughness:1,depthWrite:false,emissive:0x321008,emissiveIntensity:.54});
  const stem=tag(new THREE.Group(),"mushroom-stem"),cap=tag(new THREE.Group(),"mushroom-cap");group.add(stem,cap);
  let stemBase=null;
  for(let i=0;i<12;i++){const puff=sphere(stem,5.2+i*.48,0x463c35,0,false,18,i===0?"mushroom-stem-base":"mushroom-stem-puff");puff.material=stemMat.clone();puff.position.z=4+i*5.6;puff.position.x=Math.sin(i*.91)*1.3;puff.position.y=Math.cos(i*.74)*1.1;puff.scale.set(1.16,1.02,1.48);puff.rotation.z=i*.51;if(i===0)stemBase=puff;}
  for(let i=0;i<22;i++){const a=i/22*Math.PI*2,rad=18+(i%5)*1.7,puff=sphere(cap,9+(i%4)*1.05,0x554941,0,false,18,"mushroom-cap-puff");puff.material=capMat.clone();puff.position.set(Math.cos(a)*rad,Math.sin(a)*rad,82+(i%3)*2.6);puff.scale.set(1.72,1.72,.78);}
  const crown=sphere(cap,18.5,0x584941,0,false,24,"mushroom-crown");crown.material=capMat.clone();crown.position.z=88;crown.scale.set(2.15,2.15,.72);
  const innerCrown=sphere(cap,10.5,0xff6a18,0,true,20,"mushroom-hot-crown");innerCrown.position.z=83;innerCrown.scale.set(2.0,2.0,.7);
  const coreColumn=tag(new THREE.Mesh(new THREE.CylinderGeometry(4,9,76,24,1,true),material(0xff6a16,.72,true)),"mushroom-hot-column");coreColumn.rotation.x=Math.PI/2;coreColumn.position.z=38;group.add(coreColumn);
  const light=new THREE.PointLight(0xffe2a3,900,720,1.05);light.position.z=28;group.add(light);
  const scorch=tag(new THREE.Mesh(new THREE.CircleGeometry(42,72),new THREE.MeshBasicMaterial({color:0x100906,transparent:true,opacity:.9,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-4,side:THREE.DoubleSide})),"scorch");scorch.position.z=.04;group.add(scorch);
  impacts.push({group,scene,position:position.clone(),flash,hot,fire,fireOuter,shock,dust,wall,stem,stemBase,cap,crown,innerCrown,coreColumn,light,scorch,born:now,until:now+MUSHROOM_LIFETIME_MS,shakeTriggered:false,damageTriggered:false,shockRadius:0});
  flashScreen();
  window.dispatchEvent(new CustomEvent("arondight:nuke-impact",{detail:{position:[position.x,position.y,position.z],radiusM:BLAST_RADIUS_M,shockwaveSpeedMps:SHOCKWAVE_SPEED_MPS,mushroomHeightM:MUSHROOM_HEIGHT_M}}));
  const view=viewport();if(view){view.dataset.nukeImpacts=String((Number(view.dataset.nukeImpacts)||0)+1);view.dataset.nukeBlastRadius=String(BLAST_RADIUS_M);view.dataset.nukeEffect="whiteout-fireball-shockwave-mushroom-v3";view.dataset.nukeCinematic="whiteout+massive-fireball+physical-shockwave+giant-mushroom+delayed-damage-v3";view.dataset.nukeShockwaveSpeedMps=String(SHOCKWAVE_SPEED_MPS);view.dataset.nukeMushroomHeightM=String(MUSHROOM_HEIGHT_M);view.dataset.nukeDamageDelayMs=String(CINEMATIC_GRACE_MS);view.dataset.nukeDamageState="cinematic-grace";}
}
function updateWarheads(now){for(let i=warheads.length-1;i>=0;i--){const item=warheads[i],t=clamp((now-item.born)/item.duration,0,1),e=t*t*(3-2*t);item.group.position.lerpVectors(item.start,item.target,e);item.group.position.z+=Math.sin(Math.PI*t)*item.arc;const dir=tmp.copy(item.target).sub(item.group.position).normalize();if(dir.lengthSq()>.001)item.group.quaternion.setFromUnitVectors(axis,dir);if(t>=1){item.scene.remove(item.group);warheads.splice(i,1);makeImpact(item.scene,item.target,now);}}}
function updateImpacts(now){for(let i=impacts.length-1;i>=0;i--){const item=impacts[i],age=now-item.born,t=clamp(age/MUSHROOM_LIFETIME_MS,0,1),blastT=clamp(age/3200,0,1),blastEase=1-(1-blastT)**3;
    item.flash.scale.setScalar(1+20*blastEase);item.hot.scale.setScalar(1+6.2*blastEase);item.fire.scale.setScalar(1+4.1*blastEase);item.fireOuter.scale.setScalar(1+2.8*blastEase);item.flash.material.opacity=Math.max(0,1-blastT*1.55);item.hot.material.opacity=.99*Math.max(.12,1-blastT*.7);item.fire.material.opacity=.97*Math.max(.1,1-blastT*.76);item.fireOuter.material.opacity=.58*Math.max(.06,1-blastT*.84);item.light.intensity=900*Math.max(0,1-blastT*.92);item.coreColumn.material.opacity=.72*Math.max(0,1-blastT*.82);
    const shockRadius=Math.min(SHOCKWAVE_MAX_M,Math.max(1,age/1000*SHOCKWAVE_SPEED_MPS));item.shockRadius=shockRadius;item.shock.scale.setScalar(shockRadius);item.dust.scale.setScalar(shockRadius*.92);item.wall.scale.set(shockRadius,1,shockRadius);const shockFade=1-clamp(shockRadius/SHOCKWAVE_MAX_M,0,1);item.shock.material.opacity=.98*shockFade**.55;item.dust.material.opacity=.48*shockFade**.48;item.wall.material.opacity=.28*shockFade**.72;
    const cameraDistance=cameraDistanceTo(item.position);if(!item.shakeTriggered&&Number.isFinite(cameraDistance)&&shockRadius>=cameraDistance){item.shakeTriggered=true;const strength=clamp(1-cameraDistance/CAMERA_SHAKE_MAX_DISTANCE_M,.12,1);shakeCamera(strength,cameraDistance);const view=viewport();if(view)view.dataset.nukeShockArrivalMs=String(Math.round(age));}
    const cloudT=clamp((age-220)/6900,0,1),rise=1-(1-cloudT)**2;item.stem.visible=age>140;item.cap.visible=age>260;item.stem.position.z=rise*8;item.cap.position.z=rise*18;item.stem.scale.setScalar(.52+1.1*rise);item.cap.scale.setScalar(.3+1.18*rise);for(const mesh of item.stem.children)mesh.material.opacity=.94*Math.min(1,cloudT*4)*(1-t*.5);for(const mesh of item.cap.children)mesh.material.opacity=.96*Math.min(1,cloudT*4)*(1-t*.42);item.innerCrown.material.opacity=.78*Math.min(1,cloudT*5)*Math.max(0,1-cloudT*.88);item.scorch.material.opacity=.9*(1-clamp((age-23000)/9000,0,1));
    if(!item.damageTriggered&&age>=CINEMATIC_GRACE_MS)dispatchBlastDamage(item,age);
    const view=viewport();if(view){view.dataset.nukeShockwaveRadiusM=shockRadius.toFixed(1);view.dataset.nukeCloudProgress=cloudT.toFixed(3);view.dataset.nukeVisiblePhase=age<CINEMATIC_GRACE_MS?"cinematic":"aftermath";}
    if(now>=item.until){item.scene.remove(item.group);impacts.splice(i,1);}}
}

function fireNuke({clientX,clientY,source="external"}={}){const now=performance.now(),view=viewport();if(displayMode!=="nuke"||!isDrone()||globalThis.__arondightDroneDamageModel?.destroyed||view?.dataset.fireArmed!=="1"||now-lastNuke<COOLDOWN_MS)return false;const ray=screenRay(clientX,clientY),scene=bridge()?.threeScene;if(!ray||!scene)return false;lastNuke=now;const target=targetForRay(ray),start=ray.origin.clone().addScaledVector(ray.direction,.45).add(new THREE.Vector3(0,0,-.08));makeWarhead(scene,start,target,now);if(view){view.dataset.droneWeapon="nuke";view.dataset.nukeLaunches=String((Number(view.dataset.nukeLaunches)||0)+1);view.dataset.nukeInput=String(source);view.dataset.nukeTarget=`${target.x.toFixed(2)},${target.y.toFixed(2)},${target.z.toFixed(2)}`;view.dataset.nukeTargetResolver="ground-burst-xy-v1";view.dataset.nukeContract="drone-targeted-fixed-impact-v2";}return true;}
function applyDisplayMode(next){if(!["gun","missile","nuke"].includes(next))return displayMode;displayMode=next;saveMode(displayMode);if(displayMode==="gun")originalSetMode?.("gun");else originalSetMode?.("missile");const view=viewport();if(view){view.dataset.droneExtendedWeapon=displayMode;view.dataset.nukeSelected=displayMode==="nuke"?"1":"0";}return displayMode;}
function cycle(){return applyDisplayMode(displayMode==="gun"?"missile":displayMode==="missile"?"nuke":"gun");}
function patchApi(){const api=globalThis.__arondightDroneWeapons;if(!api)return false;if(api===patchedApi)return true;patchedApi=api;originalToggle=api.toggle?.bind(api)||null;originalSetMode=api.setMode?.bind(api)||null;originalFireMissile=api.fireMissile?.bind(api)||null;displayMode=persistedMode()||String(api.mode||"gun");if(!["gun","missile","nuke"].includes(displayMode))displayMode="gun";api.toggle=cycle;api.setMode=mode=>applyDisplayMode(String(mode));api.fireNuke=fireNuke;api.fireMissile=args=>displayMode==="nuke"?fireNuke(args):Boolean(originalFireMissile?.(args));Object.defineProperty(api,"displayMode",{configurable:true,enumerable:true,get:()=>displayMode});applyDisplayMode(displayMode);const view=viewport();if(view)view.dataset.nukeWeapon="enabled-v3";return true;}
function frame(now=performance.now()){patchApi();updateWarheads(now);updateImpacts(now);requestAnimationFrame(frame);}

export function installNukeWeapon(){if(installed)return;installed=true;ensureFlashOverlay();ensurePressureOverlay();requestAnimationFrame(frame);}
installNukeWeapon();