import * as THREE from "three";

const effects=[];
let installed=false;
const tmpCam=new THREE.Vector3(),tmpDir=new THREE.Vector3();
const NUKE_BLOCKED_SELECTOR="#soloTopbar,#soloLeft,#soloRight,#soloClearance,.solo-action,.phone-settings-dialog,#wantedEmpButton,#droneWeaponToggle,#mobileGameplayDock,dialog,button,input,select,textarea,a,label";

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function walk(){return globalThis.__arondightWalkMode||null;}
function drive(){return globalThis.__arondightVehicleDrive||null;}
function isDrone(){return walk()?.mode!=="foot"&&!drive()?.active;}
function clamp(v,a,b){return Math.max(a,Math.min(b,Number(v)||0));}
function easeOut(t){t=clamp(t,0,1);return 1-Math.pow(1-t,3);}
function smooth(t){t=clamp(t,0,1);return t*t*(3-2*t);}
function tag(node,role){node.userData.nukeWeaponPart=true;node.userData.flightFireIgnore=true;node.userData.nukeOverkillPart=true;node.userData.nukeOverkillRole=role;node.renderOrder=800;return node;}
function basic(color,opacity=1,additive=false){return new THREE.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false,depthTest:false,blending:additive?THREE.AdditiveBlending:THREE.NormalBlending,side:THREE.DoubleSide});}
function smokeMat(color,opacity=.8){return new THREE.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false,depthTest:false,side:THREE.DoubleSide});}
function sphere(group,r,color,opacity,additive,role,segments=22){const mesh=tag(new THREE.Mesh(new THREE.SphereGeometry(r,segments,Math.max(12,Math.floor(segments*.62))),basic(color,opacity,additive)),role);group.add(mesh);return mesh;}
function makeShock(group,role,color,opacity=.9){const ring=tag(new THREE.Mesh(new THREE.RingGeometry(.985,1.015,128),basic(color,opacity,true)),role);ring.position.z=.36;group.add(ring);return ring;}

function suppressLegacyImpact(){const scene=bridge()?.threeScene;if(!scene)return;let hidden=0;scene.traverse?.(node=>{if(node?.userData?.nukeRole!=="impact-root"||node.userData?.nukeOverkillPart)return;node.visible=false;hidden++;});const view=viewport();if(view){view.dataset.nukeLegacyVisual=`suppressed-${hidden}`;view.dataset.nukeVisibleRenderer="overkill-only-v1";}}
function makeOverlay(id,z,background){const view=viewport();if(!view)return null;let el=document.getElementById(id);if(el)return el;el=document.createElement("i");el.id=id;el.setAttribute("aria-hidden","true");el.style.cssText=`position:absolute;inset:-8%;z-index:${z};pointer-events:none;opacity:0;${background}`;view.appendChild(el);return el;}
function ensureOverlay(){return makeOverlay("nukeOverkillOverlay",88,"background:radial-gradient(circle at 50% 61%,#fff 0 8%,#fffbd0 17%,rgba(255,182,55,.94) 34%,rgba(255,85,10,.63) 56%,rgba(87,19,4,.28) 78%,transparent 100%);");}
function ensureVignette(){return makeOverlay("nukeOverkillVignette",87,"background:radial-gradient(circle at 50% 56%,transparent 30%,rgba(255,86,0,.12) 52%,rgba(70,15,3,.45) 76%,rgba(3,0,0,.82) 100%);");}
function ensureShockScreen(){const view=viewport();if(!view)return null;let el=document.getElementById("nukeOverkillShockScreen");if(el)return el;el=document.createElement("i");el.id="nukeOverkillShockScreen";el.setAttribute("aria-hidden","true");el.style.cssText="position:absolute;left:50%;top:66%;width:15vmin;aspect-ratio:1;border:5px solid rgba(255,252,225,.96);border-radius:50%;z-index:90;pointer-events:none;opacity:0;transform:translate(-50%,-50%) scale(.12);box-shadow:0 0 28px 10px rgba(255,175,55,.8),inset 0 0 24px rgba(255,255,255,.8)";view.appendChild(el);return el;}
function smokePuff(parent,{left,top,size,color="#574a44",glow="rgba(255,91,20,.18)"}){const p=document.createElement("i");p.style.cssText=`position:absolute;left:${left}%;top:${top}%;width:${size}%;aspect-ratio:1;border-radius:50%;background:radial-gradient(circle at 45% 40%,#7b6559 0 13%,${color} 42%,#332c29 72%,#211d1b 100%);box-shadow:0 0 18px ${glow};transform:translate(-50%,-50%)`;parent.appendChild(p);return p;}
function ensureScreenCloud(){const view=viewport();if(!view)return null;let root=document.getElementById("nukeCinematicScreenCloud");if(root)return root;
  root=document.createElement("div");root.id="nukeCinematicScreenCloud";root.setAttribute("aria-hidden","true");root.style.cssText="position:absolute;left:50%;top:52%;width:min(70vmin,300px);height:min(78vmin,320px);z-index:91;pointer-events:none;opacity:0;transform:translate(-50%,-50%) scale(.55);transform-origin:50% 76%;filter:drop-shadow(0 0 20px rgba(255,86,8,.48)) drop-shadow(0 14px 22px rgba(0,0,0,.5))";
  const cap=document.createElement("div");cap.dataset.part="cap-back";cap.style.cssText="position:absolute;left:5%;top:1%;width:90%;height:39%;border-radius:49% 51% 45% 47% / 54% 57% 43% 46%;background:radial-gradient(ellipse at 50% 72%,rgba(255,109,20,.74) 0 9%,rgba(144,66,34,.6) 20%,rgba(83,67,59,.96) 43%,rgba(52,47,44,.98) 70%,rgba(36,33,31,.96) 100%);overflow:visible";
  smokePuff(cap,{left:9,top:57,size:29,color:"#4a403b"});smokePuff(cap,{left:23,top:32,size:33,color:"#5b4b43"});smokePuff(cap,{left:40,top:19,size:36,color:"#655248"});smokePuff(cap,{left:58,top:17,size:38,color:"#695449"});smokePuff(cap,{left:76,top:31,size:34,color:"#594a43"});smokePuff(cap,{left:91,top:56,size:28,color:"#453d39"});
  const capHot=document.createElement("i");capHot.dataset.part="cap-hot";capHot.style.cssText="position:absolute;left:20%;top:27%;width:60%;height:12%;border-radius:50%;background:radial-gradient(ellipse,#fff9c8 0 4%,#ffc455 11%,#ff6a13 28%,rgba(187,58,17,.58) 54%,transparent 75%);filter:blur(1px);box-shadow:0 0 28px 8px rgba(255,102,14,.42)";
  const stem=document.createElement("div");stem.dataset.part="stem";stem.style.cssText="position:absolute;left:39%;top:32%;width:22%;height:54%;border-radius:42% 48% 34% 38% / 10% 12% 38% 42%;background:radial-gradient(circle at 45% 18%,#ff9a2b 0 3%,#9d4528 10%,transparent 24%),radial-gradient(circle at 56% 42%,#8a4934 0 18%,transparent 33%),radial-gradient(circle at 42% 70%,#62504a 0 21%,transparent 38%),linear-gradient(90deg,#2b2725 0%,#55423a 20%,#c45b29 40%,#ff9e2a 49%,#b34c24 59%,#4b3b36 78%,#282422 100%);box-shadow:0 0 19px rgba(255,91,20,.3);clip-path:polygon(29% 0,72% 0,83% 14%,70% 28%,82% 43%,71% 58%,86% 74%,71% 89%,78% 100%,23% 100%,30% 88%,15% 74%,29% 58%,18% 42%,31% 27%,18% 14%)";
  const fireball=document.createElement("i");fireball.dataset.part="fireball";fireball.style.cssText="position:absolute;left:35%;top:57%;width:30%;aspect-ratio:1;border-radius:50%;background:radial-gradient(circle,#fff 0 8%,#fffbd3 12%,#ffd85b 21%,#ff921d 35%,#ff4d08 53%,rgba(184,35,7,.58) 69%,transparent 82%);box-shadow:0 0 34px 16px rgba(255,119,22,.58);mix-blend-mode:screen";
  const skirt=document.createElement("i");skirt.dataset.part="skirt";skirt.style.cssText="position:absolute;left:24%;top:78%;width:52%;height:16%;border-radius:50%;background:radial-gradient(ellipse,#fff2a1 0 3%,#ff9c2d 12%,#c55427 28%,#66504a 52%,rgba(47,40,37,.65) 69%,transparent 79%);box-shadow:0 0 22px rgba(255,99,18,.35)";
  root.append(cap,stem,skirt,fireball,capHot);view.appendChild(root);return root;
}
function screenBlast(){const flash=ensureOverlay(),vignette=ensureVignette(),shock=ensureShockScreen(),cloud=ensureScreenCloud();
  flash?.getAnimations?.().forEach(a=>a.cancel());flash?.animate([{opacity:0,filter:"brightness(1)"},{opacity:1,filter:"brightness(6)",offset:.018},{opacity:1,filter:"brightness(3.2)",offset:.12},{opacity:.76,filter:"brightness(1.65)",offset:.31},{opacity:.42,filter:"brightness(1.18)",offset:.62},{opacity:0}],{duration:6500,easing:"cubic-bezier(.08,.7,.14,1)"});
  vignette?.getAnimations?.().forEach(a=>a.cancel());vignette?.animate([{opacity:0},{opacity:.68,offset:.14},{opacity:.58,offset:.5},{opacity:.22,offset:.8},{opacity:0}],{duration:7600,easing:"ease-out"});
  shock?.getAnimations?.().forEach(a=>a.cancel());shock?.animate([{opacity:0,transform:"translate(-50%,-50%) scale(.08)"},{opacity:1,transform:"translate(-50%,-50%) scale(.35)",offset:.04},{opacity:.88,transform:"translate(-50%,-50%) scale(1.4)",offset:.25},{opacity:.52,transform:"translate(-50%,-50%) scale(4.2)",offset:.58},{opacity:0,transform:"translate(-50%,-50%) scale(8.5)"}],{duration:4800,easing:"cubic-bezier(.1,.72,.15,1)"});
  cloud?.getAnimations?.().forEach(a=>a.cancel());cloud?.animate([{opacity:0,transform:"translate(-50%,-43%) scale(.38)",filter:"brightness(2.1) saturate(1.3)"},{opacity:.45,transform:"translate(-50%,-47%) scale(.58)",offset:.09},{opacity:.96,transform:"translate(-50%,-50%) scale(.82)",filter:"brightness(1.38) saturate(1.25)",offset:.2},{opacity:1,transform:"translate(-50%,-50%) scale(.94)",filter:"brightness(1.08) saturate(1.12)",offset:.38},{opacity:1,transform:"translate(-50%,-51%) scale(1.02)",offset:.66},{opacity:.7,transform:"translate(-50%,-53%) scale(1.08)",offset:.88},{opacity:0,transform:"translate(-50%,-55%) scale(1.12)"}],{duration:10000,easing:"cubic-bezier(.12,.7,.18,1)"});
}

function presentationAnchor(position){const camera=bridge()?.threeCamera;if(!camera)return new THREE.Vector3(position.x,position.y,0);camera.updateMatrixWorld?.(true);camera.getWorldPosition(tmpCam);tmpDir.set(position.x-tmpCam.x,position.y-tmpCam.y,0);if(tmpDir.lengthSq()<.0001){camera.getWorldDirection(tmpDir);tmpDir.z=0;}if(tmpDir.lengthSq()<.0001)tmpDir.set(0,-1,0);tmpDir.normalize();const distance=clamp(Math.hypot(position.x-tmpCam.x,position.y-tmpCam.y),125,160),anchor=tmpCam.clone().addScaledVector(tmpDir,distance);anchor.z=0;return anchor;}
function spawn(position){suppressLegacyImpact();const scene=bridge()?.threeScene;if(!scene)return;const group=tag(new THREE.Group(),"root"),anchor=presentationAnchor(position);group.position.copy(anchor);scene.add(group);
  const white=sphere(group,7,0xffffff,1,true,"white-core",30),yellow=sphere(group,11,0xffef8d,.95,true,"yellow-core",28),orange=sphere(group,16,0xff7311,.84,true,"orange-fireball",26),red=sphere(group,22,0xe93808,.45,true,"red-fireball",24);for(const m of[white,yellow,orange,red])m.position.z=9;
  const shock1=makeShock(group,"shock-ring-1",0xffffff,.95),shock2=makeShock(group,"shock-ring-2",0xffcf7e,.78),shock3=makeShock(group,"shock-ring-3",0xff7625,.55);
  const dust=tag(new THREE.Mesh(new THREE.RingGeometry(.75,1.22,128),basic(0xaa7041,.42,false)),"dust-ring");dust.position.z=.1;group.add(dust);
  const stemPuffs=[],capPuffs=[];
  for(let i=0;i<12;i++){const p=sphere(group,3.2+(i%4)*.6,0x51453f,0,false,`stem-${i}`,16);p.material=smokeMat(i<4?0x6a4a3e:0x4b4340,.72);p.position.set(Math.sin(i*.91)*(1.2+(i%3)*.35),Math.cos(i*.67)*(1+(i%2)*.4),5+i*3.1);p.scale.set(1.15,1.08,1.35);stemPuffs.push(p);}
  for(let i=0;i<24;i++){const a=i*2.3999632297,rad=4+(i%6)*2.1,p=sphere(group,3.8+(i%5)*.55,0x544945,0,false,`cap-${i}`,16);p.material=smokeMat(i%4===0?0x695248:0x4b4441,.74);p.position.set(Math.cos(a)*rad,Math.sin(a)*rad,43+((i*5)%7)*1.5);p.scale.set(1.35,1.25,1.05);capPuffs.push(p);}
  const crown=sphere(group,7.5,0x504642,0,false,"crown",20);crown.material=smokeMat(0x504642,.62);crown.position.z=48;crown.scale.set(1.55,1.45,.9);
  const hotCrown=sphere(group,5.5,0xff5c12,0,true,"hot-crown",18);hotCrown.position.z=43;hotCrown.scale.set(1.45,1.4,.72);
  const hotColumn=tag(new THREE.Mesh(new THREE.CylinderGeometry(2.8,5.5,38,24,1,true),basic(0xff5c16,.48,true)),"hot-column");hotColumn.rotation.x=Math.PI/2;hotColumn.position.z=19;group.add(hotColumn);
  const light=new THREE.PointLight(0xffc978,1500,700,1);light.position.z=22;group.add(light);
  effects.push({scene,group,born:performance.now(),white,yellow,orange,red,shock1,shock2,shock3,dust,stemPuffs,capPuffs,crown,hotCrown,hotColumn,light});
  const view=viewport();if(view){view.dataset.nukeOverkill="screen-dominating-nuclear-v3";view.dataset.nukeOverkillParts=String(4+4+stemPuffs.length+capPuffs.length+3);view.dataset.nukeOverkillMushroomM="92";view.dataset.nukeOverkillFireballM="110";view.dataset.nukeOverkillAnchor=`${anchor.x.toFixed(2)},${anchor.y.toFixed(2)},${anchor.z.toFixed(2)}`;view.dataset.nukeOverkillComposition="grounded-wide-screen-cloud-v3";view.dataset.nukeScreenCloud="mushroom-fireball-overlay-v1";view.dataset.nukeCloudShape="irregular-filled-cap-v3";}
  screenBlast();
}
function update(item,now){const age=now-item.born,fireT=easeOut(age/1800),shockT=clamp(age/4300,0,1),cloudT=smooth((age-350)/4700),fade=1-clamp((age-5900)/4500,0,1);
  item.white.scale.setScalar(.35+fireT*4.2);item.yellow.scale.setScalar(.4+fireT*3.8);item.orange.scale.setScalar(.45+fireT*3.1);item.red.scale.setScalar(.5+fireT*2.5);
  item.white.material.opacity=Math.max(0,1-age/1500);item.yellow.material.opacity=Math.max(0,.9-age/2800);item.orange.material.opacity=Math.max(0,.76-age/4700);item.red.material.opacity=Math.max(0,.38-age/6000);
  const r1=28+shockT*490,r2=18+clamp((age-200)/4300,0,1)*440,r3=10+clamp((age-430)/4400,0,1)*380;item.shock1.scale.setScalar(r1);item.shock2.scale.setScalar(r2);item.shock3.scale.setScalar(r3);item.dust.scale.setScalar(15+shockT*290);item.shock1.material.opacity=.9*fade;item.shock2.material.opacity=.65*fade;item.shock3.material.opacity=.42*fade;item.dust.material.opacity=.32*fade;
  const smokeOpacity=clamp(cloudT*1.25,0,.72);for(let i=0;i<item.stemPuffs.length;i++){const p=item.stemPuffs[i];p.material.opacity=smokeOpacity*(.72+i*.012);p.position.z+=cloudT*.018;p.scale.multiplyScalar(1.0007);}for(const p of item.capPuffs){p.material.opacity=smokeOpacity*.78;p.position.z+=cloudT*.026;p.scale.multiplyScalar(1.001);}item.crown.material.opacity=smokeOpacity*.52;item.crown.position.z=48+cloudT*7;item.hotCrown.material.opacity=Math.max(0,.5-age/6300);item.hotColumn.material.opacity=Math.max(0,.46-age/6800);item.light.intensity=Math.max(0,1500*(1-age/5900));
  const view=viewport(),screenCloud=document.getElementById("nukeCinematicScreenCloud");if(view){view.dataset.nukeOverkillPhase=age<900?"whiteout":age<2800?"fireball":age<6200?"shockwave+mushroom":"mushroom";view.dataset.nukeOverkillShockM=r1.toFixed(0);view.dataset.nukeOverkillCloud=cloudT.toFixed(3);view.dataset.nukeScreenCloudOpacity=screenCloud?Number(getComputedStyle(screenCloud).opacity).toFixed(3):"0";}
  return age<26000;
}
function routeNukePointer(event){if(event.type!=="pointerdown"||event.button!==0||!isDrone())return;const api=globalThis.__arondightDroneWeapons;if(String(api?.displayMode||"")!=="nuke")return;const target=event.target instanceof Element?event.target:null;if(target?.closest?.(NUKE_BLOCKED_SELECTOR))return;event.preventDefault();event.stopImmediatePropagation();const fired=Boolean(api?.fireNuke?.({clientX:event.clientX,clientY:event.clientY,source:event.pointerType||"pointer"})),view=viewport();if(view){view.dataset.nukeInputRoute="window-capture-fireNuke-v1";view.dataset.nukeInputRouteFired=fired?"1":"0";view.dataset.nukeLegacyMissileBypass="blocked-v1";}}
function frame(now){for(let i=effects.length-1;i>=0;i--){const item=effects[i];if(update(item,now))continue;item.scene?.remove(item.group);item.group.traverse?.(node=>{node.geometry?.dispose?.();const mats=Array.isArray(node.material)?node.material:[node.material];mats.filter(Boolean).forEach(m=>m.dispose?.());});effects.splice(i,1);}requestAnimationFrame(frame);}
function install(){if(installed)return;installed=true;window.addEventListener("pointerdown",routeNukePointer,{capture:true,passive:false});window.addEventListener("arondight:nuke-impact",event=>{const p=event?.detail?.position;if(!Array.isArray(p)||p.length<3)return;spawn(new THREE.Vector3(Number(p[0])||0,Number(p[1])||0,Number(p[2])||0));});requestAnimationFrame(frame);}
install();