import * as THREE from "three";
import {HybridMotorSound} from "./motor_sound.mjs";
import {AUDIO_SETTINGS_EVENT,loadAudioSettings} from "./audio_settings.mjs";
import {VS_PEER_EVENT,VS_POSE_EVENT,VS_FX_EVENT} from "./lan_vs.mjs";

const EYE_Z=1.68;
const HUMAN_RADIUS=.28;
const STALE_MS=3500;
const EARTH_RADIUS_M=6378137;
const LOOK_YAW_PER_PX=.0052;
const LOOK_PITCH_PER_PX=.0045;
const PLAYER_FX_KIND="pistol";
const WORLD_LIFE_FX_KIND="world-life-death-v1";
const clamp=(value,min,max)=>Math.max(min,Math.min(max,Number(value)||0));
const temp=new THREE.Vector3(),temp2=new THREE.Vector3();

let installed=false,lastMode=null,lastWalkShots=0,lastFrame=performance.now(),lastStepAt=-Infinity,lastRemoteStepScan=0;
let humanAnchor={x:0,y:0,z:0,yaw:0},anchorReady=false,lastHumanSample=null,humanVelocity={x:0,y:0,z:0};
let lastSafe=null,escapingBuilding=false,pendingTeleport=null,audioOverride=false;
let patchedBridge=null,lastFxSession=null,applyingRemoteWorldLife=false,hitRouting=false;
let audioCtx=null,noiseBuffer=null,fxMaster=null,lookPointer=null,lookX=0,lookY=0;
let blastScene=null,blastGeometry=null,blastRingGeometry=null;
const remoteAvatars=new Map(),blastPool=[];

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function walk(){return globalThis.__arondightWalkMode||null;}
function currentMode(){return walk()?.mode==="foot"?"foot":"drone";}
function activeSession(){const s=bridge()?.vsSession;return s?.active||s||null;}
function playerSession(){return bridge()?.vsSession||null;}
function selfId(){return String(playerSession()?.getSelfId?.()||activeSession()?.getSelfId?.()||"");}
function radToDeg(value){return Number(value||0)*180/Math.PI;}
function pointInside(x,y,points){let inside=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j],cross=(a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/((b[1]-a[1])||1e-12)+a[0];if(cross)inside=!inside;}return inside;}
function localOffset(){const b=bridge(),o=b?.__vsRespawnLocalOffset;return !b?.active&&Array.isArray(o)&&o.length===2?[Number(o[0])||0,Number(o[1])||0]:[0,0];}
function localToCanonical(position){const o=localOffset();return[(Number(position?.[0])||0)+o[0],(Number(position?.[1])||0)+o[1],Number(position?.[2])||0];}
function canonicalToLocal(position){const o=localOffset();return[(Number(position?.[0])||0)-o[0],(Number(position?.[1])||0)-o[1],Number(position?.[2])||0];}
function metersToLngLat(originLon,originLat,east,north){const latRad=originLat*Math.PI/180;return[originLon+(east/(EARTH_RADIUS_M*Math.max(.01,Math.cos(latRad))))*180/Math.PI,originLat+(north/EARTH_RADIUS_M)*180/Math.PI];}
function lngLatToMeters(originLon,originLat,lon,lat){return[(lon-originLon)*Math.PI/180*EARTH_RADIUS_M*Math.max(.01,Math.cos(originLat*Math.PI/180)),(lat-originLat)*Math.PI/180*EARTH_RADIUS_M];}
function yawQuaternion(yaw){return[0,0,Math.sin((Number(yaw)||0)/2),Math.cos((Number(yaw)||0)/2)];}
function walkYaw(){return Number(viewport()?.dataset.walkYaw)||0;}
function walkPitch(){return Number(viewport()?.dataset.walkPitch)||0;}
function airframe(){const b=bridge(),scene=b?.threeScene;if(!scene)return null;let root=b.airframeFor?.(scene)||b.airframe||null;if(root)return root;scene.traverse?.(node=>{if(!root&&node?.userData?.arondightAirframe)root=node;});return root;}
function airframePose(){const root=airframe();if(!root)return null;root.getWorldPosition(temp);const euler=new THREE.Euler().setFromQuaternion(root.getWorldQuaternion(new THREE.Quaternion()),"XYZ");return{x:temp.x,y:temp.y,z:Math.max(0,temp.z),yaw:euler.z};}
function snapshotHuman(){const w=walk();if(currentMode()==="foot"&&w?.position)return{x:w.position.x,y:w.position.y,z:0,yaw:walkYaw()};return{...humanAnchor};}

function installStyle(){if(document.querySelector("style[data-player-vehicle-runtime]"))return;const style=document.createElement("style");style.dataset.playerVehicleRuntime="fps-v4";style.textContent=`
body.on-foot-mode #footLookZone{display:block}#footLookZone{display:none;position:absolute;z-index:0;right:0;top:max(40px,var(--solo-safe-top,0px));bottom:0;width:58%;pointer-events:auto;touch-action:none;cursor:crosshair;background:transparent}#footLookZone::after{content:"DRAG · LOOK";position:absolute;right:14px;top:10px;color:#d9f5ff66;font:800 7px/1 system-ui;letter-spacing:.10em;pointer-events:none}body.on-foot-mode #footLook,body.on-foot-mode #footFire{z-index:4}body.on-foot-mode #footLook{opacity:.72}.vs-human-avatar{pointer-events:none}
`;document.head.appendChild(style);}
function ensureLookZone(){const hud=document.getElementById("footHud");if(!hud||document.getElementById("footLookZone"))return;const zone=document.createElement("div");zone.id="footLookZone";zone.setAttribute("aria-label","Drag to look in first person");hud.insertBefore(zone,hud.firstChild);zone.addEventListener("pointerdown",event=>{if(currentMode()!=="foot")return;lookPointer=event.pointerId;lookX=event.clientX;lookY=event.clientY;zone.setPointerCapture?.(lookPointer);ensureAudio(true);event.preventDefault();event.stopPropagation();});zone.addEventListener("pointermove",event=>{if(event.pointerId!==lookPointer||currentMode()!=="foot")return;const dx=event.clientX-lookX,dy=event.clientY-lookY;lookX=event.clientX;lookY=event.clientY;const w=walk(),p=w?.position;if(!w||!p)return;const yaw=walkYaw()+dx*LOOK_YAW_PER_PX,pitch=clamp(walkPitch()-dy*LOOK_PITCH_PER_PX,-1.28,1.28);w.setPose?.({x:p.x,y:p.y,yaw,pitch});const v=viewport();if(v){v.dataset.walkLookSurface="drag+stick";v.dataset.walkLookDragEvents=String((Number(v.dataset.walkLookDragEvents)||0)+1);}event.preventDefault();event.stopPropagation();});const release=event=>{if(event.pointerId!==lookPointer)return;lookPointer=null;event.preventDefault();event.stopPropagation();};zone.addEventListener("pointerup",release);zone.addEventListener("pointercancel",release);}

function patchMotorRuntime(){const proto=HybridMotorSound?.prototype;if(!proto||proto.__playerVehicleRuntimePatched)return;const baseUpdate=proto.update;proto.update=function(model,cameraPosition){exposeVehicleModel(model);return baseUpdate.call(this,model,cameraPosition);};proto.__playerVehicleRuntimePatched=true;}
function exposeVehicleModel(model){if(!model||typeof model.reset!=="function"||!model.p)return;const current=globalThis.__arondightVehicleRuntime;if(current?.model===model)return;globalThis.__arondightVehicleRuntime={
  model,
  teleportDrone({x=0,y=0,z=.04,yawDeg=0}={}){model.reset(model.p,{x:Number(x)||0,y:Number(y)||0,z:Number.isFinite(Number(z))?Number(z):.04,roll_deg:0,pitch_deg:0,yaw_deg:Number(yawDeg)||0});return model.state?.()||null;},
  getState(){return model.state?.()||null;}
};const v=viewport();if(v)v.dataset.droneVehicleRuntime="box3d-reset-v1";}
function teleportDrone(anchor,hideAfter=false){const runtime=globalThis.__arondightVehicleRuntime;if(!runtime?.teleportDrone){pendingTeleport={anchor:{...anchor},hideAfter};return false;}runtime.teleportDrone({x:anchor.x,y:anchor.y,z:.04,yawDeg:radToDeg(anchor.yaw)});pendingTeleport=null;setAirframeVisible(!hideAfter);const v=viewport();if(v){v.dataset.dronePhysicalX=Number(anchor.x).toFixed(3);v.dataset.dronePhysicalY=Number(anchor.y).toFixed(3);v.dataset.dronePhysicalReset="1";}return true;}
function setAirframeVisible(visible){const root=airframe();if(root)root.visible=Boolean(visible);}
function killDrone(){const button=document.getElementById("soloKill");try{button?.click?.();}catch{}}

function dispatchAudio(settings){audioOverride=true;try{window.dispatchEvent(new CustomEvent(AUDIO_SETTINGS_EVENT,{detail:settings}));}finally{queueMicrotask(()=>{audioOverride=false;});}}
function suppressDroneAudio(){const settings=loadAudioSettings();dispatchAudio({...settings,droneVolume:0});const v=viewport();if(v){v.dataset.droneAudioSuppressed="1";v.dataset.playerAudioProfile="human-no-drone";}}
function restoreDroneAudio(){dispatchAudio(loadAudioSettings());const v=viewport();if(v){v.dataset.droneAudioSuppressed="0";v.dataset.playerAudioProfile="drone-live";}}

function enterFoot(previous){let anchor=anchorReady?{...humanAnchor}:airframePose();if(!anchor)anchor={x:0,y:0,z:0,yaw:0};if(!anchorReady){humanAnchor={...anchor};anchorReady=true;}killDrone();walk()?.setPose?.({x:anchor.x,y:anchor.y,yaw:anchor.yaw,pitch:0});lastSafe={x:anchor.x,y:anchor.y};escapingBuilding=humanBlocked(anchor.x,anchor.y,true);suppressDroneAudio();teleportDrone(anchor,true);setAirframeVisible(false);const v=viewport();if(v){v.dataset.playerVehicleMode="human";v.dataset.droneVehicleState="stowed";v.dataset.humanVrHeadset="0";v.dataset.droneLaunchFromHuman=previous==="drone"?"return":"initial";}}
function enterDrone(previous){if(previous==="foot"){const p=walk()?.position;humanAnchor={x:Number(p?.x)||0,y:Number(p?.y)||0,z:0,yaw:walkYaw()};anchorReady=true;killDrone();teleportDrone(humanAnchor,false);}else if(!anchorReady){const pose=airframePose();if(pose){humanAnchor={x:pose.x,y:pose.y,z:0,yaw:pose.yaw};anchorReady=true;}}restoreDroneAudio();setAirframeVisible(true);lastSafe=null;escapingBuilding=false;const v=viewport();if(v){v.dataset.playerVehicleMode="drone";v.dataset.droneVehicleState="deployed";v.dataset.humanVrHeadset="1";v.dataset.droneLaunchFromHuman=previous==="foot"?"1":"0";if(anchorReady){v.dataset.humanAnchor=`${humanAnchor.x.toFixed(3)},${humanAnchor.y.toFixed(3)},0.000`;}}}
function syncMode(){const mode=currentMode();if(mode===lastMode)return;const previous=lastMode;lastMode=mode;if(mode==="foot")enterFoot(previous);else enterDrone(previous);const v=viewport();if(v){v.dataset.playerVehicleReplication="human+drone+audio+fx-v1";v.dataset.walkControlProfile="fps-drag-radius-slide-v4";}}

function prismBlocked(x,y){for(const prism of bridge()?.buildingCollisionSnapshot?.prisms||[]){if(Number(prism?.top)<=.25||!Array.isArray(prism.points)||prism.points.length<3)continue;if(pointInside(x,y,prism.points))return true;}return false;}
function vehicleBlocked(x,y){const scene=bridge()?.threeScene;if(!scene)return false;let blocked=false;scene.traverse?.(node=>{if(blocked||node?.visible===false)return;const kind=node?.userData?.worldLifeKind;if(kind!=="car"&&kind!=="bus")return;node.getWorldPosition(temp);const radius=kind==="bus"?2.5:1.25;if(Math.hypot(temp.x-x,temp.y-y)<radius+HUMAN_RADIUS)blocked=true;});if(blocked)return true;for(const r of remoteAvatars.values()){if(!r.root?.visible)continue;r.root.getWorldPosition(temp);if(Math.hypot(temp.x-x,temp.y-y)<.58)return true;}return false;}
function humanBlocked(x,y,ignoreVehicles=false){const samples=[[0,0],[1,0],[-1,0],[0,1],[0,-1],[.707,.707],[.707,-.707],[-.707,.707],[-.707,-.707]];for(const [sx,sy] of samples)if(prismBlocked(x+sx*HUMAN_RADIUS,y+sy*HUMAN_RADIUS))return true;return ignoreVehicles?false:vehicleBlocked(x,y);}
function enforceHumanCollision(){if(currentMode()!=="foot")return;const w=walk(),p=w?.position;if(!w||!p)return;const now={x:p.x,y:p.y};if(!lastSafe){lastSafe={...now};escapingBuilding=humanBlocked(now.x,now.y,true);return;}const blocked=humanBlocked(now.x,now.y);if(escapingBuilding){lastSafe={...now};if(!humanBlocked(now.x,now.y,true))escapingBuilding=false;return;}if(!blocked){lastSafe={...now};return;}const candidates=[{x:now.x,y:lastSafe.y},{x:lastSafe.x,y:now.y}],available=candidates.filter(c=>!humanBlocked(c.x,c.y));let chosen=lastSafe;if(available.length)chosen=available.sort((a,b)=>Math.hypot(b.x-lastSafe.x,b.y-lastSafe.y)-Math.hypot(a.x-lastSafe.x,a.y-lastSafe.y))[0];w.setPose?.({x:chosen.x,y:chosen.y,yaw:walkYaw(),pitch:walkPitch()});lastSafe={...chosen};const v=viewport();if(v){v.dataset.walkCollisionRadiusM=HUMAN_RADIUS.toFixed(2);v.dataset.walkCollisionSlides=String((Number(v.dataset.walkCollisionSlides)||0)+1);}}

function ensureAudio(unlock=false){const AudioCtx=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AudioCtx)return null;if(!audioCtx){try{audioCtx=new AudioCtx({latencyHint:"interactive"});}catch{audioCtx=new AudioCtx();}fxMaster=audioCtx.createDynamicsCompressor();fxMaster.threshold.value=-12;fxMaster.knee.value=18;fxMaster.ratio.value=3.5;fxMaster.attack.value=.002;fxMaster.release.value=.16;fxMaster.connect(audioCtx.destination);noiseBuffer=audioCtx.createBuffer(1,Math.max(1,Math.floor(audioCtx.sampleRate*.35)),audioCtx.sampleRate);const data=noiseBuffer.getChannelData(0);let seed=0x45a391;for(let i=0;i<data.length;i++){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;data[i]=((seed>>>0)/2147483648)-1;}}if(unlock&&audioCtx.state==="suspended")audioCtx.resume().catch(()=>{});return audioCtx;}
function listenerPosition(){if(currentMode()==="foot"&&walk()?.position)return walk().position;const c=bridge()?.threeCamera;if(c)return c.position;return null;}
function spatialGain(position){if(!position)return 1;const listener=listenerPosition();if(!listener)return 1;const p=Array.isArray(position)?position:[position.x,position.y,position.z],d=Math.hypot((p[0]||0)-listener.x,(p[1]||0)-listener.y,(p[2]||0)-listener.z);return 1/(1+.10*d+.018*d*d);}
function settingsGain(kind){const s=loadAudioSettings();if(!s.soundEnabled)return 0;return clamp((kind==="shots"?s.shotsVolume:s.fxVolume)/100,0,1);}
function playPistol(position=null,remote=false){const ctx=ensureAudio(false),volume=settingsGain("shots")*spatialGain(position)*(remote?.72:1);const v=viewport();if(v)v.dataset.walkShotSoundEvents=String((Number(v.dataset.walkShotSoundEvents)||0)+1);if(!ctx||ctx.state!=="running"||!fxMaster||volume<=0)return false;const t=ctx.currentTime,noise=ctx.createBufferSource(),hp=ctx.createBiquadFilter(),ng=ctx.createGain();noise.buffer=noiseBuffer;hp.type="highpass";hp.frequency.value=1050;ng.gain.setValueAtTime(.20*volume,t);ng.gain.exponentialRampToValueAtTime(.0001,t+.075);noise.connect(hp).connect(ng).connect(fxMaster);noise.start(t);noise.stop(t+.085);const body=ctx.createOscillator(),bg=ctx.createGain();body.type="triangle";body.frequency.setValueAtTime(185,t);body.frequency.exponentialRampToValueAtTime(72,t+.07);bg.gain.setValueAtTime(.13*volume,t);bg.gain.exponentialRampToValueAtTime(.0001,t+.09);body.connect(bg).connect(fxMaster);body.start(t);body.stop(t+.095);return true;}
function playStep(position=null,remote=false){const ctx=ensureAudio(false),volume=settingsGain("fx")*spatialGain(position)*(remote?.24:.16);if(!ctx||ctx.state!=="running"||!fxMaster||volume<=0)return;const t=ctx.currentTime,noise=ctx.createBufferSource(),lp=ctx.createBiquadFilter(),g=ctx.createGain();noise.buffer=noiseBuffer;lp.type="lowpass";lp.frequency.value=420;g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+.055);noise.connect(lp).connect(g).connect(fxMaster);noise.start(t);noise.stop(t+.065);}
function playExplosion(position=null,small=false){const ctx=ensureAudio(false),volume=settingsGain("fx")*spatialGain(position)*(small?.38:1);const v=viewport();if(v)v.dataset.playerExplosionSoundEvents=String((Number(v.dataset.playerExplosionSoundEvents)||0)+1);if(!ctx||ctx.state!=="running"||!fxMaster||volume<=0)return;const t=ctx.currentTime,noise=ctx.createBufferSource(),lp=ctx.createBiquadFilter(),g=ctx.createGain();noise.buffer=noiseBuffer;lp.type="lowpass";lp.frequency.setValueAtTime(small?950:620,t);lp.frequency.exponentialRampToValueAtTime(110,t+(small?.16:.42));g.gain.setValueAtTime((small?.10:.24)*volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+(small?.2:.48));noise.connect(lp).connect(g).connect(fxMaster);noise.start(t);noise.stop(t+(small?.22:.5));const o=ctx.createOscillator(),og=ctx.createGain();o.type="sine";o.frequency.setValueAtTime(small?110:74,t);o.frequency.exponentialRampToValueAtTime(28,t+(small?.18:.46));og.gain.setValueAtTime((small?.07:.18)*volume,t);og.gain.exponentialRampToValueAtTime(.0001,t+(small?.22:.5));o.connect(og).connect(fxMaster);o.start(t);o.stop(t+(small?.24:.52));}

function fireDirection(){const yaw=walkYaw(),pitch=walkPitch(),cp=Math.cos(pitch);return[Math.sin(yaw)*cp,Math.cos(yaw)*cp,Math.sin(pitch)];}
function sendFootShot(){const s=playerSession(),w=walk(),p=w?.position;if(!s?.sendFx||!p)return;const from=localToCanonical([p.x,p.y,p.z]),dir=fireDirection(),id=`pistol-${Date.now().toString(36)}-${Math.floor(performance.now()).toString(36)}`,pid=selfId();s.sendFx({type:"shot",id,from,dir,speed:360,...(pid?{playerId:pid}:{}),kind:PLAYER_FX_KIND,t:Date.now()});const v=viewport();if(v)v.dataset.walkReplicatedShots=String((Number(v.dataset.walkReplicatedShots)||0)+1);}
function observeWalkShot(){const v=viewport(),shots=Number(v?.dataset.walkShots||0);if(shots>lastWalkShots&&currentMode()==="foot"){const p=walk()?.position;playPistol(p,false);sendFootShot();if(v)v.dataset.walkShotAudioVisualSync="muzzle+recoil+sound";}lastWalkShots=Math.max(lastWalkShots,shots);}
function updateHumanVelocity(now){const pose=snapshotHuman();if(!lastHumanSample){lastHumanSample={...pose,at:now};humanVelocity={x:0,y:0,z:0};return;}const dt=(now-lastHumanSample.at)/1000;if(dt>.001&&dt<.5){humanVelocity={x:(pose.x-lastHumanSample.x)/dt,y:(pose.y-lastHumanSample.y)/dt,z:0};}lastHumanSample={...pose,at:now};if(currentMode()==="foot"){const speed=Math.hypot(humanVelocity.x,humanVelocity.y),period=clamp(.54-speed*.032,.27,.50);if(speed>.65&&now-lastStepAt>period*1000){lastStepAt=now;playStep([pose.x,pose.y,0],false);const v=viewport();if(v)v.dataset.walkFootsteps=String((Number(v.dataset.walkFootsteps)||0)+1);}}}

function augmentVsPose(){const b=bridge(),s=b?.vsSession,pending=s?.pendingPose;if(!s?.setPose||!pending)return;const human=snapshotHuman(),canonical=localToCanonical([human.x,human.y,0]),velocity=[humanVelocity.x,humanVelocity.y,0],mode=currentMode(),next={...pending,pm:mode,av:canonical,ay:human.yaw,avv:velocity,vr:mode==="drone"?1:0};if(b.active&&Number.isFinite(b.originLon)&&Number.isFinite(b.originLat)){next.ag=metersToLngLat(b.originLon,b.originLat,human.x,human.y);}if(mode==="foot"){next.p=localToCanonical([human.x,human.y,.04]);next.q=yawQuaternion(human.yaw);next.v=velocity;if(next.ag)next.g=[...next.ag];}s.setPose(next);const v=viewport();if(v)v.dataset.playerPoseReplicated=mode;}
function patchPoseBridge(){const b=bridge();if(!b||b===patchedBridge||typeof b.updateVsPose!=="function")return;patchedBridge=b;if(b.__playerVehiclePosePatched)return;const base=b.updateVsPose.bind(b);b.updateVsPose=()=>{const result=base();augmentVsPose();return result;};b.__playerVehiclePosePatched=true;}

function hashColor(id){let h=2166136261;for(const c of String(id||"")){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}const palette=[0x42b7e9,0xe46c4f,0x70b86a,0xe0b34e,0x9b78db,0x48b6a0];return palette[(h>>>0)%palette.length];}
function avatarPart(geometry,material,x,y,z){const mesh=new THREE.Mesh(geometry,material);mesh.position.set(x,y,z);mesh.castShadow=false;mesh.receiveShadow=false;mesh.userData.worldPopulationKind="vs-player";mesh.userData.worldPopulationClone=false;return mesh;}
function createAvatar(id){const scene=bridge()?.threeScene;if(!scene)return null;const color=hashColor(id),cloth=new THREE.MeshStandardMaterial({color,roughness:.72,metalness:.04}),dark=new THREE.MeshStandardMaterial({color:0x252c32,roughness:.82}),skin=new THREE.MeshStandardMaterial({color:0xb98262,roughness:.84}),glass=new THREE.MeshStandardMaterial({color:0x172634,roughness:.22,metalness:.28,emissive:0x113c54,emissiveIntensity:.28}),root=new THREE.Group();root.name=`VS_HUMAN_${id}`;root.userData.vsPlayerId=id;root.userData.vsHumanAvatar=true;const torso=avatarPart(new THREE.BoxGeometry(.40,.24,.62),cloth,0,0,1.08),head=avatarPart(new THREE.SphereGeometry(.19,10,7),skin,0,0,1.58),legL=avatarPart(new THREE.BoxGeometry(.14,.16,.70),dark,-.11,0,.48),legR=avatarPart(new THREE.BoxGeometry(.14,.16,.70),dark,.11,0,.48),armL=avatarPart(new THREE.BoxGeometry(.12,.14,.62),cloth,-.28,0,1.08),armR=avatarPart(new THREE.BoxGeometry(.12,.14,.62),cloth,.28,0,1.08),headset=avatarPart(new THREE.BoxGeometry(.36,.17,.16),glass,0,.13,1.61),strap=avatarPart(new THREE.BoxGeometry(.25,.23,.06),dark,0,-.02,1.63),pack=avatarPart(new THREE.BoxGeometry(.30,.13,.38),dark,0,-.16,1.04);for(const part of[torso,head,legL,legR,armL,armR,headset,strap,pack]){part.userData.vsPlayerId=id;part.userData.worldPopulationId=`vs-human-${id}`;root.add(part);}const hitMat=new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false});hitMat.colorWrite=false;const hitbox=new THREE.Mesh(new THREE.BoxGeometry(.66,.56,1.82),hitMat);hitbox.position.z=.91;hitbox.userData.vsPlayerId=id;hitbox.userData.vsPeerHitProxy=true;hitbox.userData.worldPopulationKind="vs-player";hitbox.userData.worldPopulationId=`vs-human-${id}`;hitbox.userData.worldPopulationClone=false;root.add(hitbox);root.visible=false;scene.add(root);const record={id,root,torso,head,legL,legR,armL,armR,headset,strap,pack,hitbox,mode:"drone",target:new THREE.Vector3(),yaw:0,velocity:new THREE.Vector3(),lastPose:-Infinity,lastStep:-Infinity,phase:0};remoteAvatars.set(id,record);return record;}
function poseAvatarLocal(pose){const b=bridge();if(Array.isArray(pose?.ag)&&pose.ag.length===2&&b?.active&&Number.isFinite(b.originLon)&&Number.isFinite(b.originLat)){const [x,y]=lngLatToMeters(b.originLon,b.originLat,Number(pose.ag[0]),Number(pose.ag[1]));return[x,y,0];}return canonicalToLocal(pose?.av||pose?.p||[0,0,0]);}
function onPose(event){const peerId=String(event?.detail?.peerId||""),pose=event?.detail?.pose;if(!peerId||!pose||!Array.isArray(pose.av)||!(pose.pm==="foot"||pose.pm==="drone"))return;const r=remoteAvatars.get(peerId)||createAvatar(peerId);if(!r)return;const p=poseAvatarLocal(pose);r.target.set(Number(p[0])||0,Number(p[1])||0,0);r.yaw=Number(pose.ay)||0;r.mode=pose.pm;r.velocity.set(Number(pose.avv?.[0])||0,Number(pose.avv?.[1])||0,0);r.lastPose=performance.now();r.headset.visible=pose.vr===1||pose.pm==="drone";r.strap.visible=r.headset.visible;r.pack.visible=pose.pm==="foot";const v=viewport();if(v)v.dataset.vsHumanPoseEvents=String((Number(v.dataset.vsHumanPoseEvents)||0)+1);}
function onPeer(event){const id=String(event?.detail?.peerId||"");if(event?.detail?.type!=="leave"||!id)return;const r=remoteAvatars.get(id);if(r){r.root.parent?.remove(r.root);remoteAvatars.delete(id);}}
function peerDead(id){const marker=document.querySelector(`.vs-player-marker[data-peer-id="${CSS.escape(id)}"]`);return Boolean(marker?.classList.contains("dead"));}
function hidePeerDrone(id,hidden){const b=bridge(),scene=b?.threeScene;if(!scene)return;scene.traverse?.(node=>{if(String(node?.userData?.vsPlayerId||"")!==id)return;if(node?.userData?.vsMultiplayerPeer||node?.userData?.vsLegacyPrimary||node?.userData?.vsPeer)node.visible=!hidden&&node.visible;});if(hidden&&b?.vsPeerMesh&&String(b.vsPeerMesh.userData?.vsPlayerId||"")===id)b.vsPeerMesh.visible=false;}
function renderRemoteAvatars(now,dt){for(const r of remoteAvatars.values()){const stale=now-r.lastPose>STALE_MS,dead=peerDead(r.id);if(stale||dead){r.root.visible=false;continue;}r.root.visible=true;const alpha=1-Math.exp(-dt*14);r.root.position.lerp(r.target,alpha);let d=r.yaw-r.root.rotation.z;d=((d+Math.PI)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)-Math.PI;r.root.rotation.z+=d*alpha;const speed=Math.hypot(r.velocity.x,r.velocity.y),walking=r.mode==="foot"&&speed>.25;r.phase+=dt*(walking?clamp(5+speed*1.1,5,11):2);const swing=walking?Math.sin(r.phase)*clamp(.28+speed*.04,.28,.62):0;r.legL.rotation.x=swing;r.legR.rotation.x=-swing;r.armL.rotation.x=-swing*.75;r.armR.rotation.x=swing*.75;r.headset.visible=r.mode==="drone";r.strap.visible=r.mode==="drone";r.pack.visible=r.mode==="foot";hidePeerDrone(r.id,r.mode==="foot");if(walking&&now-r.lastStep>clamp(520-speed*24,270,500)){r.lastStep=now;playStep(r.root.position,true);}}
  const v=viewport();if(v){v.dataset.vsHumanAvatars=String(remoteAvatars.size);v.dataset.vsVrAvatars=String([...remoteAvatars.values()].filter(r=>r.root.visible&&r.mode==="drone").length);}}

function vsPlayerId(hit){for(let node=hit?.object;node;node=node.parent){const id=String(node.userData?.vsPlayerId||"");if(id)return id;}return"";}
function patchWorldHitRouting(){const b=bridge(),base=b?.registerWorldPopulationHit;if(!b||typeof base!=="function"||base.__playerVehicleHitRouter||!base.__worldLivelinessWrapper)return;const wrapper=hit=>{const id=vsPlayerId(hit);if(id&&!hitRouting&&typeof b.registerVsHit==="function"){hitRouting=true;try{return Boolean(b.registerVsHit(hit));}finally{hitRouting=false;}}return Boolean(base(hit));};wrapper.__playerVehicleHitRouter=true;wrapper.__worldLivelinessWrapper=true;wrapper.__gameplayPolishLiteWrapper=true;b.registerWorldPopulationHit=wrapper;const v=viewport();if(v)v.dataset.walkVsHitRouting="1";}

function patchFxSession(){const session=activeSession();if(!session||session===lastFxSession||typeof session.sendFx!=="function")return;lastFxSession=session;if(session.__playerVehicleFxPatched)return;session.__playerVehicleFxPatched=true;const base=session.sendFx.bind(session);session.sendFx=(packet,options)=>{if(packet?.type===WORLD_LIFE_FX_KIND){if(applyingRemoteWorldLife)return true;const pid=selfId(),next={...packet,type:"impact",kind:WORLD_LIFE_FX_KIND,objectKind:packet.kind,...(pid?{playerId:pid}:{})};return base(next,options);}return base(packet,options);};}
function findWorldLife(id){let found=null;bridge()?.threeScene?.traverse?.(node=>{if(found)return;const nodeId=String(node?.userData?.worldLifeId||node?.userData?.worldPopulationId||"");if(nodeId===String(id||""))found=node;});return found;}
function applyRemoteWorldLife(packet){const b=bridge(),object=findWorldLife(packet?.objectId);if(!b||!object||typeof b.registerWorldPopulationHit!=="function")return false;object.getWorldPosition(temp);applyingRemoteWorldLife=true;try{return Boolean(b.registerWorldPopulationHit({object,point:temp.clone()}));}finally{applyingRemoteWorldLife=false;}}

function ensureBlastPool(){const scene=bridge()?.threeScene;if(!scene)return;if(blastScene!==scene){for(const item of blastPool)item.group.parent?.remove(item.group);blastPool.length=0;blastScene=scene;blastGeometry=new THREE.SphereGeometry(.18,10,7);blastRingGeometry=new THREE.RingGeometry(.45,.72,20);}while(blastPool.length<8){const group=new THREE.Group(),coreMat=new THREE.MeshBasicMaterial({color:0xffd98a,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}),shellMat=new THREE.MeshBasicMaterial({color:0xff6f32,transparent:true,opacity:0,depthWrite:false,side:THREE.BackSide,blending:THREE.AdditiveBlending}),smokeMat=new THREE.MeshBasicMaterial({color:0x514a45,transparent:true,opacity:0,depthWrite:false}),ringMat=new THREE.MeshBasicMaterial({color:0xffb45d,transparent:true,opacity:0,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending}),core=new THREE.Mesh(blastGeometry,coreMat),shell=new THREE.Mesh(blastGeometry,shellMat),smoke=new THREE.Mesh(blastGeometry,smokeMat),ring=new THREE.Mesh(blastRingGeometry,ringMat);ring.rotation.x=Math.PI/2;for(const m of[core,shell,smoke,ring])m.userData.flightFireIgnore=true;group.add(core,shell,smoke,ring);group.visible=false;scene.add(group);blastPool.push({group,core,shell,smoke,ring,born:0,expires:0,small:false});}}
function spawnRoundBlast(position,small=false){ensureBlastPool();if(!blastPool.length)return;const item=blastPool.find(x=>!x.group.visible)||blastPool.reduce((a,b)=>a.born<=b.born?a:b),p=Array.isArray(position)?position:[position?.x,position?.y,position?.z];item.group.position.set(Number(p?.[0])||0,Number(p?.[1])||0,Math.max(.05,Number(p?.[2])||.05));item.born=performance.now();item.expires=item.born+(small?360:900);item.small=small;item.group.visible=true;item.core.material.opacity=.95;item.shell.material.opacity=.55;item.smoke.material.opacity=0;item.ring.material.opacity=.68;item.core.scale.setScalar(small?.25:.45);item.shell.scale.setScalar(small?.35:.62);item.smoke.scale.setScalar(small?.28:.55);item.ring.scale.setScalar(small?.45:.75);const v=viewport();if(v)v.dataset.playerRoundBlastEvents=String((Number(v.dataset.playerRoundBlastEvents)||0)+1);}
function renderBlasts(now){for(const item of blastPool){if(!item.group.visible)continue;if(now>=item.expires){item.group.visible=false;continue;}const t=(now-item.born)/(item.expires-item.born),e=1-(1-t)**3,k=item.small?.45:1;item.core.scale.setScalar(k*(.45+2.7*e));item.shell.scale.setScalar(k*(.65+5.4*e));item.smoke.scale.setScalar(k*(.5+3.8*e));item.smoke.position.z=k*(.12+1.15*t);item.ring.scale.setScalar(k*(.8+7.2*e));item.core.material.opacity=.95*(1-t);item.shell.material.opacity=.46*(1-t)**1.45;item.smoke.material.opacity=.25*Math.sin(Math.PI*t)*(1-.25*t);item.ring.material.opacity=.62*(1-t)**1.8;}}
function remoteFxPosition(packet,key="p"){return canonicalToLocal(packet?.[key]||[0,0,0]);}
function onFx(event){const packet=event?.detail?.packet;if(!packet)return;if(packet.type==="shot"&&packet.kind===PLAYER_FX_KIND){const p=remoteFxPosition(packet,"from");playPistol(p,true);spawnRoundBlast(p,true);const v=viewport();if(v)v.dataset.vsRemotePistolSounds=String((Number(v.dataset.vsRemotePistolSounds)||0)+1);return;}if(packet.type==="impact"&&packet.kind===WORLD_LIFE_FX_KIND){applyRemoteWorldLife(packet);return;}if(packet.type==="explosion"){const p=remoteFxPosition(packet);spawnRoundBlast(p,false);playExplosion(p,false);}else if(packet.type==="impact"){const p=remoteFxPosition(packet);spawnRoundBlast(p,true);playExplosion(p,true);}}
function onWorldExplosion(event){const p=event?.detail?.position;if(!p)return;spawnRoundBlast(p,false);playExplosion(p,false);}

function frame(now=performance.now()){const dt=clamp((now-lastFrame)/1000,0,.05);lastFrame=now;ensureLookZone();patchPoseBridge();patchWorldHitRouting();patchFxSession();syncMode();if(pendingTeleport)teleportDrone(pendingTeleport.anchor,pendingTeleport.hideAfter);if(currentMode()==="foot")setAirframeVisible(false);enforceHumanCollision();updateHumanVelocity(now);observeWalkShot();augmentVsPose();renderRemoteAvatars(now,dt);renderBlasts(now);requestAnimationFrame(frame);}

export function installPlayerVehicleRuntime(){if(installed)return;installed=true;patchMotorRuntime();installStyle();lastWalkShots=Number(viewport()?.dataset.walkShots||0);addEventListener("pointerdown",()=>ensureAudio(true),{capture:true,passive:true});addEventListener("keydown",()=>ensureAudio(true),{capture:true});addEventListener(AUDIO_SETTINGS_EVENT,event=>{if(audioOverride||currentMode()!=="foot"||Number(event.detail?.droneVolume)===0)return;queueMicrotask(suppressDroneAudio);});addEventListener(VS_POSE_EVENT,onPose);addEventListener(VS_PEER_EVENT,onPeer);addEventListener(VS_FX_EVENT,onFx);addEventListener("arondight:world-explosion",onWorldExplosion);const v=viewport();if(v){v.dataset.playerVehicleRuntime="human-drone-v1";v.dataset.walkLookSurface="drag+stick";v.dataset.walkCollisionRadiusM=HUMAN_RADIUS.toFixed(2);v.dataset.walkPistolSound="procedural-synced-v1";}globalThis.__arondightPlayerVehicleRuntime={get mode(){return currentMode();},get humanAnchor(){return{...humanAnchor};},get humanVelocity(){return{...humanVelocity};},get remoteAvatarCount(){return remoteAvatars.size;},sync:syncMode,teleportDrone:anchor=>teleportDrone(anchor||snapshotHuman(),currentMode()==="foot")};requestAnimationFrame(frame);}
