import * as THREE from "three";
import {findXboxGamepad} from "./xbox_gamepad.mjs";
import {loadPhoneControlSettings} from "./drone_control_settings.mjs";
import {VEHICLE_CONTROL_SETTINGS_EVENT,loadVehicleControlSettings,normalizeVehicleControlSettings} from "./vehicle_control_settings.mjs";

const ENTER_RADIUS_M=5.2;
const keys=new Set();
const tmp=new THREE.Vector3();
const forward=new THREE.Vector3();
const target=new THREE.Vector3();
let installed=false,active=false,vehicle=null,heading=0,commandSpeed=0,lastFrame=performance.now(),cameraInstalled=false,baseCameraProvider=null,cameraFireKick=0,cameraFirePhase=0,lastCameraAt=performance.now();
let touchSteer=0,touchPedal=0,handbrake=false,lastNearestScan=-Infinity,nearest=null;
let settings=loadVehicleControlSettings();
const nativeGetGamepads=typeof navigator!=="undefined"&&navigator.getGamepads?navigator.getGamepads.bind(navigator):()=>[];
const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||0));

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function physics(){return globalThis.__arondightWorldRigidBodies||null;}
function walk(){return globalThis.__arondightWalkMode||null;}
function playerDead(){return Boolean(globalThis.__arondightPlayerDamageModel?.dead);}
function quaternionYaw(q){if(!Array.isArray(q)||q.length<4)return 0;const[x,y,z,w]=q.map(Number);return Math.atan2(2*(w*z+x*y),1-2*(y*y+z*z));}
function vehiclePose(){const pose=vehicle?physics()?.pose?.(vehicle.id):null;if(pose?.position)return pose;if(vehicle?.root)return{position:[vehicle.root.position.x,vehicle.root.position.y,vehicle.root.position.z+.42],rotation:[vehicle.root.quaternion.x,vehicle.root.quaternion.y,vehicle.root.quaternion.z,vehicle.root.quaternion.w],velocity:[0,0,0]};return null;}
function vehicleRoots(){const scene=bridge()?.threeScene,out=[];if(!scene)return out;scene.traverse(node=>{if(!node?.isGroup||node.visible===false)return;const kind=String(node.userData?.worldPopulationKind||""),id=String(node.userData?.worldPopulationId||node.userData?.worldProceduralId||"");if((kind==="car"||node.userData?.gtaDrivableVehicle===true)&&id)out.push({id,root:node});});return out;}
function nearestVehicle(now=performance.now()){if(active)return vehicle;if(now-lastNearestScan<240)return nearest;lastNearestScan=now;nearest=null;const w=walk();if(w?.mode!=="foot"||!w.position)return null;let best=ENTER_RADIUS_M;for(const record of vehicleRoots()){record.root.getWorldPosition(tmp);const d=Math.hypot(tmp.x-w.position.x,tmp.y-w.position.y);if(d<best){best=d;nearest={...record,distance:d};}}return nearest;}
function clearFootKeys(){for(const code of["KeyW","KeyA","KeyS","KeyD","ShiftLeft","ShiftRight"])dispatchEvent(new KeyboardEvent("keyup",{code}));}
function suppressFootGamepad(value){try{if(value)Object.defineProperty(navigator,"getGamepads",{configurable:true,value:()=>[]});else delete navigator.getGamepads;}catch{}}
function setDrivingUi(value){document.body.classList.toggle("player-driving",value);const modeButton=document.getElementById("playerModeButton");if(modeButton){modeButton.disabled=value;modeButton.style.opacity=value?".45":"";}const view=viewport();if(view){view.dataset.playerDriveMode=value?"vehicle":"off";view.dataset.playerControlMode=value?"vehicle":(walk()?.mode||"drone");}}
function enter(record=nearestVehicle()){
  if(active||playerDead()||walk()?.mode!=="foot"||!record?.id)return false;const engine=physics();let pose=engine?.pose?.(record.id),root=record.root||vehicleRoots().find(item=>item.id===record.id)?.root||null;if(!pose?.position&&root&&typeof engine?.upsertBody==="function"){root.getWorldPosition(tmp);const q=root.quaternion,yaw=quaternionYaw([q.x,q.y,q.z,q.w]);engine.upsertBody({id:record.id,kind:"car",position:[tmp.x,tmp.y,Math.max(.42,tmp.z+.42)],yaw,halfExtents:[1.78,.82,.42],massKg:1420});pose=engine.pose?.(record.id);}if(!pose?.position)return false;
  vehicle={id:record.id,root};heading=quaternionYaw(pose.rotation);forward.set(Math.cos(heading),Math.sin(heading),0);const velocity=pose.velocity||[0,0,0];commandSpeed=clamp((Number(velocity[0])||0)*forward.x+(Number(velocity[1])||0)*forward.y,-settings.reverseSpeedKmh/3.6,settings.maxSpeedKmh/3.6);vehicle.root&&(vehicle.root.userData.playerDriven=true);clearFootKeys();touchSteer=touchPedal=0;handbrake=false;suppressFootGamepad(true);setDrivingUi(true);active=true;window.dispatchEvent(new CustomEvent("arondight:vehicle-mode",{detail:{active:true,id:vehicle.id}}));return true;
}
function exit({forced=false}={}){
  if(!active)return false;const pose=vehiclePose(),id=vehicle?.id,root=vehicle?.root;if(pose?.position){const sideX=-Math.sin(heading),sideY=Math.cos(heading),x=pose.position[0]+sideX*2.15,y=pose.position[1]+sideY*2.15;walk()?.setPose?.({x,y,yaw:Math.PI/2-heading,pitch:0});}if(root)delete root.userData.playerDriven;physics()?.setDrive?.(id,null);physics()?.clearTarget?.(id);camHeading=null;active=false;vehicle=null;commandSpeed=0;touchSteer=touchPedal=0;handbrake=false;suppressFootGamepad(false);setDrivingUi(false);window.dispatchEvent(new CustomEvent("arondight:vehicle-mode",{detail:{active:false,id,forced}}));return true;
}
function sampleGamepad(){if(loadPhoneControlSettings().xboxControllerEnabled===false)return null;return findXboxGamepad(nativeGetGamepads());}
function button(pad,index){const b=pad?.buttons?.[index];return clamp(typeof b==="number"?b:(b?.value??(b?.pressed?1:0)),0,1);}
function axis(value,dead=.08){const v=clamp(value,-1,1),a=Math.abs(v);return a<=dead?0:Math.sign(v)*(a-dead)/(1-dead);}
function controls(){let steer=(keys.has("KeyD")?1:0)-(keys.has("KeyA")?1:0)+touchSteer,pedal=(keys.has("KeyW")?1:0)-(keys.has("KeyS")?1:0)+touchPedal,brake=handbrake||keys.has("Space");const pad=sampleGamepad();if(pad){steer+=axis(pad.axes?.[0]);pedal+=button(pad,7)-button(pad,6);brake=brake||button(pad,1)>.55;}return{steer:clamp(steer,-1,1)*settings.steeringSensitivityPercent/100,pedal:clamp(pedal,-1,1)*settings.throttleSensitivityPercent/100,brake};}
// Driving: the input goes to the arcade bicycle model inside the physics
// step (world_rigid_body_physics.mjs setDrive) — grip, speed-sensitive
// steering, real collisions. Here we only read the result back.
let camHeading=null;
function updateDrive(now,dt){
  if(!active)return;const pose=vehiclePose();if(!pose?.position||vehicle?.root?.visible===false){exit({forced:true});return;}const input=controls();
  const engine=physics();if(engine?.setDrive)engine.setDrive(vehicle.id,{pedal:input.pedal,steer:-input.steer,handbrake:input.brake,maxSpeed:settings.maxSpeedKmh/3.6,maxReverse:settings.reverseSpeedKmh/3.6});
  const yaw=Number.isFinite(pose.yaw)?pose.yaw:quaternionYaw(pose.rotation);heading=yaw;forward.set(Math.cos(yaw),Math.sin(yaw),0);
  const v=pose.velocity||[0,0,0];commandSpeed=(Number(v[0])||0)*forward.x+(Number(v[1])||0)*forward.y;
  walk()?.setPose?.({x:pose.position[0],y:pose.position[1],yaw:Math.PI/2-heading,pitch:0});const view=viewport();if(view){view.dataset.vehicleDriveId=vehicle.id;view.dataset.vehicleDriveSpeedKmh=(Math.abs(commandSpeed)*3.6).toFixed(1);view.dataset.vehicleDriveSteer=input.steer.toFixed(3);view.dataset.vehicleDriveThrottle=input.pedal.toFixed(3);view.dataset.vehicleDrivePhysics="box3d-arcade-bicycle-grip-v2";view.dataset.vehicleDriveController="keyboard+touch+xbox-v1";}
}
function applyDriveCamera({camera,now}){const pose=vehiclePose();if(!pose?.position)return null;const d=settings.cameraDistanceM,h=settings.cameraHeightM;{const k=1-Math.exp(-6*clamp(((Number(now)||performance.now())-lastCameraAt)/1000,0,.1));if(camHeading===null)camHeading=heading;let e=heading-camHeading;e=Math.atan2(Math.sin(e),Math.cos(e));camHeading+=e*k;}forward.set(Math.cos(camHeading),Math.sin(camHeading),0);target.set(pose.position[0]+forward.x*1.05,pose.position[1]+forward.y*1.05,pose.position[2]+.78);camera.position.set(target.x-forward.x*d,target.y-forward.y*d,target.z+h);camera.up.set(0,0,1);camera.lookAt(target);const dt=clamp(((Number(now)||performance.now())-lastCameraAt)/1000,0,.1);lastCameraAt=Number(now)||performance.now();if(cameraFireKick>.0001){cameraFirePhase+=dt*51;camera.rotateX((-.0022+Math.sin(cameraFirePhase)*.0008)*cameraFireKick);camera.rotateY(Math.sin(cameraFirePhase*1.31)*.0011*cameraFireKick);cameraFireKick*=Math.exp(-15*dt);}camera.fov=72;camera.updateProjectionMatrix?.();camera.updateMatrixWorld?.(true);const view=viewport();if(view){view.dataset.vehicleCamera="collision-guarded-chase-v1";view.dataset.vehicleCameraAnchor=`${target.x.toFixed(3)},${target.y.toFixed(3)},${target.z.toFixed(3)}`;view.dataset.vehicleCameraFireShake="damped-weapon-impulse-v1";view.dataset.vehicleCameraFireKick=cameraFireKick.toFixed(3);}return{active:true,mode:"vehicle",origin:"car-chase",now};}
const driveCameraProvider={isActive:()=>active||Boolean(baseCameraProvider?.isActive?.()),apply:args=>active?applyDriveCamera(args):baseCameraProvider?.apply?.(args)};
function ensureCameraProvider(){if(cameraInstalled)return;const b=bridge(),current=b?.presentationCameraProvider;if(!b||typeof b.attachPresentationCameraProvider!=="function"||!current)return;baseCameraProvider=current;b.attachPresentationCameraProvider(driveCameraProvider);cameraInstalled=true;const v=viewport();if(v)v.dataset.playerCameraStack="walk+vehicle-v1";}
function installStyle(){if(document.querySelector("style[data-player-car-mode]"))return;const style=document.createElement("style");style.dataset.playerCarMode="gta-physical-v1";style.textContent=`
body.player-driving #footHud,body.player-driving #soloLeft,body.player-driving #soloRight,body.player-driving #soloClearance,body.player-driving .solo-action{display:none!important;pointer-events:none!important}#vehicleHud{display:none;position:absolute;inset:0;z-index:12;pointer-events:none;font-family:system-ui,-apple-system,sans-serif}body.player-driving #vehicleHud{display:block}.vehicle-pad{position:absolute;bottom:max(18px,var(--solo-safe-bottom,env(safe-area-inset-bottom)));width:min(23vw,138px);aspect-ratio:1;border-radius:50%;border:1px solid #a9e6ff55;background:#0715228c;box-shadow:inset 0 0 30px #2db7ff22,0 6px 20px #0007;pointer-events:auto;touch-action:none}.vehicle-pad .knob{position:absolute;left:50%;top:50%;width:31%;aspect-ratio:1;border-radius:50%;transform:translate(-50%,-50%);background:#e9f8ffdd;border:1px solid #fff}.vehicle-pad span{position:absolute;left:50%;bottom:-15px;transform:translateX(-50%);color:#eaf8ff;font:900 8px/1 system-ui;letter-spacing:.1em}#vehicleSteer{left:max(14px,var(--solo-safe-left,env(safe-area-inset-left)))}#vehiclePedal{right:max(14px,var(--solo-safe-right,env(safe-area-inset-right)));border-radius:18px;width:min(18vw,108px);aspect-ratio:.72}#vehicleReadout{position:absolute;left:50%;bottom:max(18px,var(--solo-safe-bottom,env(safe-area-inset-bottom)));transform:translateX(-50%);padding:7px 10px;border:1px solid #ffffff2c;border-radius:9px;background:#071522d8;color:#dff5ff;font:900 9px/1 system-ui;letter-spacing:.07em}#driveModeButton[data-near="1"]{border-color:#7de7b988!important;background:#154932e8!important}body.player-driving #driveModeButton{border-color:#ffcf6f88!important;background:#52350fe8!important}@media(max-height:340px){.vehicle-pad{width:min(20vw,112px);bottom:max(12px,var(--solo-safe-bottom,env(safe-area-inset-bottom)))}#vehiclePedal{width:min(15vw,86px)}#vehicleReadout{bottom:max(10px,var(--solo-safe-bottom,env(safe-area-inset-bottom)));font-size:8px}}
`;document.head.appendChild(style);}
function bindPad(el,kind){if(!el||el.dataset.bound)return;el.dataset.bound="1";let pointer=null;const knob=el.querySelector(".knob");const apply=e=>{const r=el.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;if(kind==="steer"){touchSteer=clamp((e.clientX-cx)/(r.width*.38),-1,1);knob.style.left=`${50+touchSteer*31}%`;}else{touchPedal=clamp(-(e.clientY-cy)/(r.height*.40),-1,1);knob.style.top=`${50-touchPedal*31}%`;}e.preventDefault();e.stopPropagation();};el.addEventListener("pointerdown",e=>{pointer=e.pointerId;el.setPointerCapture?.(pointer);apply(e);});el.addEventListener("pointermove",e=>{if(e.pointerId===pointer)apply(e);});const release=e=>{if(e.pointerId!==pointer)return;pointer=null;if(kind==="steer"){touchSteer=0;knob.style.left="50%";}else{touchPedal=0;knob.style.top="50%";}e.preventDefault();e.stopPropagation();};el.addEventListener("pointerup",release);el.addEventListener("pointercancel",release);}
function mountUi(){const view=viewport(),top=document.getElementById("soloTopbarActions")||document.getElementById("soloTopbar");if(view&&!document.getElementById("vehicleHud")){const hud=document.createElement("div");hud.id="vehicleHud";hud.innerHTML='<div id="vehicleSteer" class="vehicle-pad"><div class="knob"></div><span>STEER</span></div><div id="vehiclePedal" class="vehicle-pad"><div class="knob"></div><span>THROTTLE / BRAKE</span></div><div id="vehicleReadout">CAR · 0 km/h · E EXIT</div>';view.appendChild(hud);bindPad(hud.querySelector("#vehicleSteer"),"steer");bindPad(hud.querySelector("#vehiclePedal"),"pedal");}if(top&&!document.getElementById("driveModeButton")){const b=document.createElement("button");b.id="driveModeButton";b.type="button";b.addEventListener("click",()=>active?exit():enter());top.insertBefore(b,document.getElementById("soloCamera")?.parentElement===top?document.getElementById("soloCamera"):null);}}
// Contextual GTA-style button on every device: appears next to a car while
// on foot ("EINSTEIGEN") and stays while driving ("AUSSTEIGEN"). The old
// topbar CAR button is hidden in the flight-first mobile layout.
function mountEnterButton(){const view=viewport();if(!view||document.getElementById("enterCarButton"))return;const b=document.createElement("button");b.id="enterCarButton";b.type="button";b.hidden=true;b.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();active?exit():enter();});view.appendChild(b);
  const style=document.createElement("style");style.dataset.enterCar="contextual-v1";style.textContent=`#enterCarButton{position:absolute;z-index:30;left:50%;transform:translateX(-50%);bottom:calc(max(14px,var(--solo-safe-bottom,env(safe-area-inset-bottom))) + 64px);min-width:150px;height:46px;padding:0 18px;border-radius:14px;font:900 15px/1 "Nunito","Trebuchet MS",system-ui,sans-serif;letter-spacing:.06em;color:#3a2600;background:#ffc93c;border:2.5px solid #fff;box-shadow:0 4px 0 #c48a12;pointer-events:auto;touch-action:manipulation}#enterCarButton[hidden]{display:none!important}#enterCarButton[data-mode="exit"]{background:#ff6b5a;color:#fff;box-shadow:0 4px 0 #b13b2e}html.neon-line-style:not(#ng-a):not(#ng-b):not(#ng-c) #enterCarButton{background:#ffc93c!important;color:#3a2600!important;border:2.5px solid #fff!important;box-shadow:0 4px 0 #c48a12!important}html.neon-line-style:not(#ng-a):not(#ng-b):not(#ng-c) #enterCarButton[data-mode="exit"]{background:#ff6b5a!important;color:#fff!important;box-shadow:0 4px 0 #b13b2e!important}`;document.head.appendChild(style);}
function renderEnterButton(near){const b=document.getElementById("enterCarButton");if(!b)return;const show=!playerDead()&&(active||(Boolean(near)&&walk()?.mode==="foot"));if(b.hidden===show)b.hidden=!show;const mode=active?"exit":"enter";if(b.dataset.mode!==mode){b.dataset.mode=mode;b.textContent=active?"AUSSTEIGEN":"🚗 EINSTEIGEN";}}
function renderUi(now){mountUi();mountEnterButton();const near=nearestVehicle(now),b=document.getElementById("driveModeButton"),readout=document.getElementById("vehicleReadout");if(b){b.dataset.near=!active&&near?"1":"0";b.disabled=playerDead()||(!active&&!near);b.textContent=active?"EXIT CAR":near?"CAR":"CAR —";b.setAttribute("aria-label",active?"Exit vehicle":near?`Enter nearby car ${near.distance.toFixed(1)} meters away`:"No drivable car nearby");}renderEnterButton(near);if(readout&&active)readout.textContent=`CAR · ${Math.round(Math.abs(commandSpeed)*3.6)} km/h · E EXIT`;}
function vehicleWeaponFire(event){if(!active)return;const intensity=clamp(event?.detail?.intensity??.2,0,.8);cameraFireKick=Math.min(.8,cameraFireKick+intensity);const view=viewport();if(view){view.dataset.vehicleCameraFireWeapon=String(event?.detail?.weapon||"unknown");view.dataset.vehicleCameraFireKick=cameraFireKick.toFixed(3);}}
function installInput(){addEventListener("arondight:weapon-fired",vehicleWeaponFire);addEventListener("keydown",event=>{if(event.metaKey||event.ctrlKey||event.altKey)return;if(active&&["KeyW","KeyA","KeyS","KeyD","Space","KeyE","KeyV","ShiftLeft","ShiftRight"].includes(event.code)){event.preventDefault();event.stopImmediatePropagation();if(event.code==="KeyE"){exit();return;}if(event.code==="Space")handbrake=true;else keys.add(event.code);return;}if(!active&&event.code==="KeyE"&&walk()?.mode==="foot"){const near=nearestVehicle();if(near){event.preventDefault();event.stopImmediatePropagation();enter(near);}}},{capture:true});addEventListener("keyup",event=>{keys.delete(event.code);if(event.code==="Space")handbrake=false;},{capture:true});addEventListener(VEHICLE_CONTROL_SETTINGS_EVENT,event=>{settings=normalizeVehicleControlSettings(event.detail?.settings||loadVehicleControlSettings());});addEventListener("arondight:player-death",()=>exit({forced:true}));}
function frame(now=performance.now()){const dt=clamp((now-lastFrame)/1000,0,.05);lastFrame=now;ensureCameraProvider();renderUi(now);updateDrive(now,dt);requestAnimationFrame(frame);}
export function installPlayerCarMode(){if(installed)return globalThis.__arondightVehicleDrive;installed=true;installStyle();installInput();mountUi();const api={enterNearest:()=>enter(nearestVehicle()),exit,get active(){return active;},get vehicleId(){return vehicle?.id||"";},get speedMps(){return Math.abs(commandSpeed);},get signedSpeedMps(){return commandSpeed;},get throttle(){return touchPedal+(keys.has("KeyW")?1:0)-(keys.has("KeyS")?1:0);},get heading(){return heading;},get cameraAnchor(){const pose=vehiclePose();return pose?.position?{x:pose.position[0],y:pose.position[1],z:pose.position[2]+.78}:null;},nearestVehicle};globalThis.__arondightVehicleDrive=api;const view=viewport();if(view){view.dataset.vehicleDriveMode="gta-physical-existing-traffic-v1";view.dataset.vehicleDriveEnterRadiusM=String(ENTER_RADIUS_M);view.dataset.vehicleDriveAvailability="all-procedural-cars+physics-fallback-v2";}requestAnimationFrame(frame);return api;}
installPlayerCarMode();
