import * as THREE from "three";
import {HybridMotorSound} from "./motor_sound.mjs";
import {loadAudioSettings} from "./audio_settings.mjs";
import {VS_PEER_EVENT,VS_POSE_EVENT,VS_FX_EVENT} from "./lan_vs.mjs";
import {COMBAT_AUDIO_BANK_VERSION,playCombatAudio,prepareCombatAudio} from "./combat_audio_bank.mjs";
import {insideEscapeImproves,pointInsidePolygon,sweptPointClear} from "./walk_collision_math.mjs";
import {buildCharacter,animateCharacter,shirtColorFor} from "./character_model.mjs";
import {groundHeightAt} from "./terrain_craters.mjs";
import {vehicleGeometry,vehicleMaterial,wheelGeometry} from "./vehicle_models.mjs";

const HUMAN_RADIUS=.28;
const EYE_Z=1.68;
const GRID_M=12;
const VEHICLE_SCAN_MS=420;
const PEER_SCAN_MS=520;
const GRID_REFRESH_MS=1600;
const POSE_TX_MS=66;
const STALE_MS=3500;
const PLAYER_FX_KIND="pistol";
const WORLD_LIFE_FX_KIND="world-life-death-v1";
const EARTH_RADIUS_M=6378137;
const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,Number(v)||0));
const tmp=new THREE.Vector3(),tmp2=new THREE.Vector3(),forwardAxis=new THREE.Vector3(0,1,0),airframeQuat=new THREE.Quaternion(),airframeEuler=new THREE.Euler();

let installed=false,lastMode=null,lastWalkShots=0,lastFrame=performance.now(),lastPoseTx=-Infinity,lastStepAt=-Infinity;
// The chase camera sits 1.65 m behind the drone; with the pilot only 0.72 m
// behind it, the camera started inside the pilot's own body. The drone now
// launches a few steps in front of the pilot's feet, clear of the camera.
const DRONE_LAUNCH_OFFSET_M=2.9;
let humanAnchor={x:0,y:0,z:0,yaw:0},anchorReady=false,lastHumanSample=null,humanVelocity={x:0,y:0,z:0};
let pendingTeleport=null,airframeRoot=null,airframeScene=null,lastAirframeScan=-Infinity;
let audioCtx=null,fxMaster=null;
let collisionPrisms=null,collisionStamp="",lastGridBuild=-Infinity,lastVehicleScan=-Infinity,lastPeerScan=-Infinity;
let applyingRemoteWorldLife=false,hitRouting=false,lastFxSession=null,patchedBridge=null;
let localAvatar=null,avatarScene=null,muzzleScene=null,muzzleGeo=null,muzzleConeGeo=null,blastScene=null,blastGeo=null,blastRingGeo=null;
let perfStart=performance.now(),perfFrames=0;
const buildingGrid=new Map(),vehicleNodes=[],peerDroneNodes=new Map(),remoteAvatars=new Map(),motorInstances=new Set(),muzzlePool=[],blastPool=[];

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function walk(){return globalThis.__arondightWalkMode||null;}
function currentMode(){return walk()?.mode==="foot"?"foot":"drone";}
function playerSession(){return bridge()?.vsSession||null;}
function activeSession(){const s=playerSession();return s?.active||s||null;}
function selfId(){try{return String(playerSession()?.getSelfId?.()||activeSession()?.getSelfId?.()||"");}catch{return"";}}
function walkYaw(){return Number(viewport()?.dataset.walkYaw)||0;}
function walkPitch(){return Number(viewport()?.dataset.walkPitch)||0;}
function radToDeg(v){return(Number(v)||0)*180/Math.PI;}
function yawQuaternion(yaw){return[0,0,Math.sin((Number(yaw)||0)/2),Math.cos((Number(yaw)||0)/2)];}
function localOffset(){const b=bridge(),o=b?.__vsRespawnLocalOffset;return !b?.active&&Array.isArray(o)&&o.length===2?[Number(o[0])||0,Number(o[1])||0]:[0,0];}
function localToCanonical(position){const o=localOffset();return[(Number(position?.[0])||0)+o[0],(Number(position?.[1])||0)+o[1],Number(position?.[2])||0];}
function canonicalToLocal(position){const o=localOffset();return[(Number(position?.[0])||0)-o[0],(Number(position?.[1])||0)-o[1],Number(position?.[2])||0];}
function metersToLngLat(originLon,originLat,east,north){const latRad=originLat*Math.PI/180;return[originLon+east/(EARTH_RADIUS_M*Math.max(.01,Math.cos(latRad)))*180/Math.PI,originLat+north/EARTH_RADIUS_M*180/Math.PI];}
function lngLatToMeters(originLon,originLat,lon,lat){return[(lon-originLon)*Math.PI/180*EARTH_RADIUS_M*Math.max(.01,Math.cos(originLat*Math.PI/180)),(lat-originLat)*Math.PI/180*EARTH_RADIUS_M];}
function snapshotHuman(){const w=walk();if(currentMode()==="foot"&&w?.position)return{x:w.position.x,y:w.position.y,z:0,yaw:walkYaw()};return{...humanAnchor};}

function airframe(now=performance.now()){
  const b=bridge(),scene=b?.threeScene;if(!scene)return null;
  if(scene!==airframeScene){airframeScene=scene;airframeRoot=null;lastAirframeScan=-Infinity;}
  const direct=b.airframeFor?.(scene)||b.airframe||null;if(direct){airframeRoot=direct;airframeRoot.userData.localDamageTarget="drone";return direct;}
  if(airframeRoot?.parent){airframeRoot.userData.localDamageTarget="drone";return airframeRoot;}
  if(now-lastAirframeScan<1000)return null;lastAirframeScan=now;
  scene.traverse?.(node=>{if(!airframeRoot&&node?.userData?.arondightAirframe)airframeRoot=node;});if(airframeRoot)airframeRoot.userData.localDamageTarget="drone";return airframeRoot;
}
function airframePose(){const root=airframe();if(!root)return null;root.getWorldPosition(tmp);root.getWorldQuaternion(airframeQuat);airframeEuler.setFromQuaternion(airframeQuat,"XYZ");return{x:tmp.x,y:tmp.y,z:Math.max(0,tmp.z),yaw:airframeEuler.z};}
function setAirframeVisible(visible){const root=airframe();if(root)root.visible=Boolean(visible);}

function exposeVehicleModel(model){if(!model||typeof model.reset!=="function"||!model.p)return;const current=globalThis.__arondightVehicleRuntime;if(current?.model===model)return;globalThis.__arondightVehicleRuntime={model,teleportDrone({x=0,y=0,z=.08,yawDeg=0}={}){model.reset(model.p,{x:Number(x)||0,y:Number(y)||0,z:Number.isFinite(Number(z))?Number(z):.08,roll_deg:0,pitch_deg:0,yaw_deg:Number(yawDeg)||0});return model.state?.()||null;},getState(){return model.state?.()||null;}};const v=viewport();if(v)v.dataset.droneVehicleRuntime="box3d-reset-v2";}
function hardMuteMotor(muted){for(const instance of motorInstances){try{if(instance.master&&instance.ctx){instance.master.gain.cancelScheduledValues?.(instance.ctx.currentTime);instance.master.gain.setTargetAtTime(muted?0:.0001,instance.ctx.currentTime,.012);}}catch{}}const v=viewport();if(v)v.dataset.droneAudioHardMuted=muted?"1":"0";}
function patchMotorRuntime(){const proto=HybridMotorSound?.prototype;if(!proto||proto.__playerVehicleRuntimeV2Patched)return;const baseUpdate=proto.update;proto.update=function(model,cameraPosition){motorInstances.add(this);exposeVehicleModel(model);if(currentMode()==="foot"){if(this.master&&this.ctx)this.master.gain.setTargetAtTime(0,this.ctx.currentTime,.010);if(this.viewport){this.viewport.dataset.motorAudioGain="0";this.viewport.dataset.motorAudioHardMuted="1";}return;}return baseUpdate.call(this,model,cameraPosition);};proto.__playerVehicleRuntimeV2Patched=true;}
function teleportDrone(anchor,{hidden=false,launchOffset=false}={}){const runtime=globalThis.__arondightVehicleRuntime;if(!runtime?.teleportDrone){pendingTeleport={anchor:{...anchor},hidden,launchOffset};return false;}const offset=launchOffset?DRONE_LAUNCH_OFFSET_M:0,x=anchor.x+Math.sin(anchor.yaw)*offset,y=anchor.y+Math.cos(anchor.yaw)*offset;runtime.teleportDrone({x,y,z:.08,yawDeg:radToDeg(anchor.yaw)});pendingTeleport=null;setAirframeVisible(!hidden);const v=viewport();if(v){v.dataset.dronePhysicalX=x.toFixed(3);v.dataset.dronePhysicalY=y.toFixed(3);v.dataset.dronePhysicalReset="1";v.dataset.droneLaunchOffsetM=offset.toFixed(2);}return true;}
function killDrone(){try{document.getElementById("soloKill")?.click?.();}catch{}}
// The motor is muted at its own gain stage; the saved mix is never rewritten (a fake droneVolume:0
// broadcast used to land in the settings sliders and was saved with the next slider move).
function suppressDroneAudio(){hardMuteMotor(true);const v=viewport();if(v){v.dataset.droneAudioSuppressed="1";v.dataset.playerAudioProfile="human-hard-muted";}}
function restoreDroneAudio(){hardMuteMotor(false);const v=viewport();if(v){v.dataset.droneAudioSuppressed="0";v.dataset.playerAudioProfile="drone-live";}}

function avatarPart(geometry,material,x,y,z){const mesh=new THREE.Mesh(geometry,material);mesh.position.set(x,y,z);mesh.castShadow=false;mesh.receiveShadow=false;mesh.userData.worldPopulationKind="vs-player";mesh.userData.worldPopulationClone=false;mesh.userData.flightFireIgnore=false;return mesh;}
// Every human (the player as others see him, remote players) is the shared
// articulated character (character_model.mjs) standing on the real terrain.
function buildHumanAvatar(id,{local=false}={}){const scene=bridge()?.threeScene;if(!scene)return null;
  const rig=buildCharacter({outfit:"player",shirt:local?null:shirtColorFor(id),id}),root=rig.root;root.name=local?"LOCAL_HUMAN_VR":`VS_HUMAN_${id}`;root.userData.vsPlayerId=id;root.userData.vsHumanAvatar=true;root.userData.localHumanAvatar=local;if(local)root.userData.localDamageTarget="player";
  root.traverse(part=>{if(!part.isMesh)return;part.userData.vsPlayerId=id;part.userData.worldPopulationId=`vs-human-${id}`;if(local){part.userData.flightFireIgnore=true;part.userData.localDamageTarget="player";}});
  let hitbox=null;if(!local){const hitMat=new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false});hitMat.colorWrite=false;hitbox=new THREE.Mesh(new THREE.BoxGeometry(.66,.56,1.82),hitMat);hitbox.position.z=.91;hitbox.userData.vsPlayerId=id;hitbox.userData.vsPeerHitProxy=true;hitbox.userData.worldPopulationKind="vs-player";hitbox.userData.worldPopulationId=`vs-human-${id}`;hitbox.userData.worldPopulationClone=false;root.add(hitbox);}
  root.visible=false;scene.add(root);const stub=()=>({visible:false,rotation:{x:0}});
  return{id,root,rig,torso:rig.spine,head:rig.head,legL:rig.legs.L.hip,legR:rig.legs.R.hip,armL:rig.arms.L.sh,armR:rig.arms.R.sh,headset:stub(),strap:stub(),pack:stub(),controllerL:stub(),controllerR:stub(),hitbox,mode:"drone",target:new THREE.Vector3(),yaw:0,velocity:new THREE.Vector3(),lastPose:-Infinity,lastStep:-Infinity,phase:0,dead:false,weapon:"none",car:null,carMesh:null,carId:""};}
function hashColor(id){let h=2166136261;for(const c of String(id||"")){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}const palette=[0x42b7e9,0xe46c4f,0x70b86a,0xe0b34e,0x9b78db,0x48b6a0];return palette[(h>>>0)%palette.length];}
function ensureLocalAvatar(){const scene=bridge()?.threeScene;if(!scene)return null;if(scene!==avatarScene){avatarScene=scene;localAvatar=null;for(const r of remoteAvatars.values())r.root.parent?.remove(r.root);remoteAvatars.clear();}if(!localAvatar)localAvatar=buildHumanAvatar(selfId()||"local",{local:true});return localAvatar;}
let lastLocalAvatarAt=performance.now();
function renderLocalAvatar(){const a=ensureLocalAvatar(),v=viewport();if(!a)return;const now=performance.now(),dt=Math.min(.1,(now-lastLocalAvatarAt)/1000);lastLocalAvatarAt=now;if(currentMode()==="drone"&&anchorReady){a.root.position.set(humanAnchor.x,humanAnchor.y,groundHeightAt(humanAnchor.x,humanAnchor.y));a.root.rotation.set(0,0,humanAnchor.yaw);a.root.visible=true;animateCharacter(a.rig,{state:"vr",dt});if(v){v.dataset.localHumanAvatarVisible="1";v.dataset.localHumanVr="1";v.dataset.localHumanAvatar="articulated-v3";}}else{a.root.visible=false;if(v){v.dataset.localHumanAvatarVisible="0";v.dataset.localHumanVr="0";}}}

function enterFoot(previous){let anchor=anchorReady?{...humanAnchor}:airframePose();if(!anchor)anchor={x:0,y:0,z:0,yaw:0};humanAnchor={x:anchor.x,y:anchor.y,z:0,yaw:anchor.yaw};anchorReady=true;suppressDroneAudio();killDrone();teleportDrone(humanAnchor,{hidden:true});setAirframeVisible(false);walk()?.setPose?.({x:humanAnchor.x,y:humanAnchor.y,yaw:humanAnchor.yaw,pitch:0});lastHumanSample=null;const v=viewport();if(v){v.dataset.playerVehicleMode="human";v.dataset.droneVehicleState="stowed";v.dataset.humanVrHeadset="0";v.dataset.droneLaunchFromHuman=previous==="drone"?"return":"initial";}}
function enterDrone(previous){if(previous==="foot"){const p=walk()?.position;humanAnchor={x:Number(p?.x)||0,y:Number(p?.y)||0,z:0,yaw:walkYaw()};anchorReady=true;teleportDrone(humanAnchor,{hidden:false,launchOffset:true});}else if(!anchorReady){const pose=airframePose();if(pose){humanAnchor={x:pose.x-Math.sin(pose.yaw)*DRONE_LAUNCH_OFFSET_M,y:pose.y-Math.cos(pose.yaw)*DRONE_LAUNCH_OFFSET_M,z:0,yaw:pose.yaw};anchorReady=true;}}setAirframeVisible(true);restoreDroneAudio();lastHumanSample=null;const v=viewport();if(v){v.dataset.playerVehicleMode="drone";v.dataset.droneVehicleState="deployed";v.dataset.humanVrHeadset="1";v.dataset.droneLaunchFromHuman=previous==="foot"?"1":"0";if(anchorReady)v.dataset.humanAnchor=`${humanAnchor.x.toFixed(3)},${humanAnchor.y.toFixed(3)},0.000`;}}
function syncMode(){const mode=currentMode();if(mode===lastMode)return;const previous=lastMode;lastMode=mode;if(mode==="foot")enterFoot(previous);else enterDrone(previous);const v=viewport();if(v){v.dataset.playerVehicleReplication="human+drone+audio+fx-v2";v.dataset.walkControlProfile="cod-dynamic-assist-bob-v7";v.dataset.walkCollisionProfile="spatial-grid-swept-v3";}}

function gridKey(gx,gy){return`${gx}:${gy}`;}
function refreshBuildingGrid(now=performance.now()){
  const b=bridge(),snapshot=b?.buildingCollisionSnapshot,prisms=snapshot?.prisms||[],origin=`${Number(b?.originLon)||0}:${Number(b?.originLat)||0}`,stamp=`${origin}:${prisms.length}:${snapshot?.revision??snapshot?.version??""}`;
  if(prisms===collisionPrisms&&stamp===collisionStamp&&now-lastGridBuild<GRID_REFRESH_MS)return;
  collisionPrisms=prisms;collisionStamp=stamp;lastGridBuild=now;buildingGrid.clear();
  for(const prism of prisms){if(Number(prism?.top)<=.25||Number(prism?.base)>1.9||!Array.isArray(prism.points)||prism.points.length<3)continue;/* parts starting above head height (arcades, overhangs, skyways) are walked under */let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const p of prism.points){const x=Number(p?.[0]),y=Number(p?.[1]);if(!Number.isFinite(x)||!Number.isFinite(y))continue;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);}if(!Number.isFinite(minX))continue;const entry={points:prism.points,minX,minY,maxX,maxY},gx0=Math.floor(minX/GRID_M),gx1=Math.floor(maxX/GRID_M),gy0=Math.floor(minY/GRID_M),gy1=Math.floor(maxY/GRID_M);for(let gx=gx0;gx<=gx1;gx++)for(let gy=gy0;gy<=gy1;gy++){const key=gridKey(gx,gy),bucket=buildingGrid.get(key);if(bucket)bucket.push(entry);else buildingGrid.set(key,[entry]);}}
  const v=viewport();if(v){v.dataset.walkCollisionCells=String(buildingGrid.size);v.dataset.walkCollisionPrisms=String(prisms.length);}
}
function buildingsAtPoint(x,y){refreshBuildingGrid();const bucket=buildingGrid.get(gridKey(Math.floor(x/GRID_M),Math.floor(y/GRID_M)))||[];return bucket.filter(p=>x>=p.minX&&x<=p.maxX&&y>=p.minY&&y<=p.maxY&&pointInsidePolygon(x,y,p.points));}
function buildingBlockedPoint(x,y){refreshBuildingGrid();const bucket=buildingGrid.get(gridKey(Math.floor(x/GRID_M),Math.floor(y/GRID_M)))||[];for(const p of bucket)if(x>=p.minX&&x<=p.maxX&&y>=p.minY&&y<=p.maxY&&pointInsidePolygon(x,y,p.points))return true;return false;}
function buildingBlocked(x,y){const r=HUMAN_RADIUS,s=.707*r;for(const [dx,dy] of[[0,0],[r,0],[-r,0],[0,r],[0,-r],[s,s],[s,-s],[-s,s],[-s,-s]])if(buildingBlockedPoint(x+dx,y+dy))return true;return false;}
function refreshVehicleNodes(now=performance.now()){if(now-lastVehicleScan<VEHICLE_SCAN_MS)return;lastVehicleScan=now;vehicleNodes.length=0;const scene=bridge()?.threeScene;if(!scene)return;scene.traverse?.(node=>{if(node?.visible===false)return;const life=String(node?.userData?.worldLifeKind||""),kind=String(node?.userData?.worldPopulationKind||"");if((life==="car"||life==="bus")&&node.children?.length)vehicleNodes.push({node,radius:life==="bus"?2.55:1.30});else if(kind==="car"&&node.children?.length&&!node.userData?.worldLifeId)vehicleNodes.push({node,radius:1.35});});const v=viewport();if(v)v.dataset.walkCollisionVehicles=String(vehicleNodes.length);}
function vehicleBlocked(x,y){refreshVehicleNodes();for(const item of vehicleNodes){if(item.node.visible===false)continue;item.node.getWorldPosition(tmp);if(Math.hypot(tmp.x-x,tmp.y-y)<item.radius+HUMAN_RADIUS)return true;}for(const r of remoteAvatars.values()){if(!r.root.visible)continue;if(Math.hypot(r.root.position.x-x,r.root.position.y-y)<.58)return true;}return false;}
function canOccupyWalkPoint(x,y){return!buildingBlocked(x,y)&&!vehicleBlocked(x,y);}
function walkPathClear(from,to){return sweptPointClear(from,to,(x,y)=>buildingBlocked(x,y),HUMAN_RADIUS*.42);}
function escapeMoveAllowed(from,to){return insideEscapeImproves(from,to,buildingsAtPoint(from.x,from.y).map(entry=>entry.points));}
function resolveWalkMove(from,to){const fromInside=buildingBlocked(from.x,from.y),v=viewport();if(fromInside){if(escapeMoveAllowed(from,to)){if(v)v.dataset.walkCollisionEscape="directed";return{x:to.x,y:to.y};}if(v)v.dataset.walkCollisionEscape="blocked";return{x:from.x,y:from.y};}if(canOccupyWalkPoint(to.x,to.y)&&walkPathClear(from,to))return{x:to.x,y:to.y};const xOnly={x:to.x,y:from.y},yOnly={x:from.x,y:to.y},xFree=canOccupyWalkPoint(xOnly.x,xOnly.y)&&walkPathClear(from,xOnly),yFree=canOccupyWalkPoint(yOnly.x,yOnly.y)&&walkPathClear(from,yOnly);let result={x:from.x,y:from.y};if(xFree&&yFree)result=Math.abs(to.x-from.x)>=Math.abs(to.y-from.y)?xOnly:yOnly;else if(xFree)result=xOnly;else if(yFree)result=yOnly;if(v){v.dataset.walkCollisionSlides=String((Number(v.dataset.walkCollisionSlides)||0)+1);v.dataset.walkCollisionSwept="1";}return result;}

function ensureAudio(unlock=false){const Ctx=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Ctx)return null;if(!audioCtx){try{audioCtx=(globalThis.__sharedAudioContext??=new Ctx({latencyHint:"interactive"}));}catch{audioCtx=(globalThis.__sharedAudioContext??=new Ctx());}fxMaster=audioCtx.createDynamicsCompressor();fxMaster.threshold.value=-12;fxMaster.knee.value=18;fxMaster.ratio.value=3.5;fxMaster.attack.value=.002;fxMaster.release.value=.16;fxMaster.connect(audioCtx.destination);prepareCombatAudio(audioCtx);}if(unlock&&audioCtx.state==="suspended")audioCtx.resume().catch(()=>{});return audioCtx;}
function listenerPosition(){if(currentMode()==="foot"&&walk()?.position)return walk().position;return bridge()?.threeCamera?.position||null;}
function spatialGain(position){if(!position)return 1;const listener=listenerPosition();if(!listener)return 1;const p=Array.isArray(position)?position:[position.x,position.y,position.z],d=Math.hypot((p[0]||0)-listener.x,(p[1]||0)-listener.y,(p[2]||0)-listener.z);return 1/(1+.10*d+.018*d*d);}
function settingsGain(kind){const s=loadAudioSettings();if(!s.soundEnabled)return 0;return clamp((kind==="shots"?s.shotsVolume:s.fxVolume)/100,0,1);}
function synthPistol(volume){if(!audioCtx||audioCtx.state!=="running"||!fxMaster||volume<=0)return false;const played=playCombatAudio(audioCtx,"shot",{destination:fxMaster,gain:.44*volume,minIntervalMs:38}),v=viewport();if(played&&v)v.dataset.walkShotSamplePlays=String((Number(v.dataset.walkShotSamplePlays)||0)+1);return played;}
function playPistol(position=null,remote=false){const ctx=ensureAudio(true),volume=settingsGain("shots")*spatialGain(position)*(remote?.68:1),v=viewport();if(v)v.dataset.walkShotSoundEvents=String((Number(v.dataset.walkShotSoundEvents)||0)+1);if(!ctx||volume<=0)return false;if(ctx.state==="running")synthPistol(volume);else ctx.resume().then(()=>synthPistol(volume)).catch(()=>{});return true;}
function playStep(position=null,remote=false){const ctx=ensureAudio(false),volume=settingsGain("fx")*spatialGain(position)*(remote?.18:.12);if(!ctx||ctx.state!=="running"||!fxMaster||volume<=0)return false;return playCombatAudio(ctx,"step",{destination:fxMaster,gain:volume,minIntervalMs:55});}
function playExplosion(position=null,small=false){const ctx=ensureAudio(false),volume=settingsGain("fx")*spatialGain(position)*(small?.36:1),v=viewport();if(v)v.dataset.playerExplosionSoundEvents=String((Number(v.dataset.playerExplosionSoundEvents)||0)+1);if(!ctx||ctx.state!=="running"||!fxMaster||volume<=0)return false;return playCombatAudio(ctx,"explosion",{destination:fxMaster,gain:(small?.30:.52)*volume,minIntervalMs:70});}

function fireDirection(){const yaw=walkYaw(),pitch=walkPitch(),cp=Math.cos(pitch);return[Math.sin(yaw)*cp,Math.cos(yaw)*cp,Math.sin(pitch)];}
function sendFootShot(){const s=playerSession(),w=walk(),p=w?.position;if(!s?.sendFx||!p)return;const from=localToCanonical([p.x,p.y,EYE_Z-.08]),dir=fireDirection(),id=`pistol-${Date.now().toString(36)}-${Math.floor(performance.now()).toString(36)}`,pid=selfId();s.sendFx({type:"shot",id,from,dir,speed:360,...(pid?{playerId:pid}:{}),kind:PLAYER_FX_KIND,t:Date.now()});const v=viewport();if(v)v.dataset.walkReplicatedShots=String((Number(v.dataset.walkReplicatedShots)||0)+1);}
// Every shot of the local player goes out with its exact trail (muzzle ->
// hit point), weapon and hand: other players see the right gun fire, the
// tracer land where it landed, and hear the right report.
function sendFootTracer(event){const d=event?.detail;const s=playerSession(),pid=selfId();if(!d||!s?.sendFx||currentMode()!=="foot")return;const a=d.start,b=d.end;if(!Array.isArray(a)||!Array.isArray(b))return;const dx=b[0]-a[0],dy=b[1]-a[1],dz=b[2]-a[2],l=Math.hypot(dx,dy,dz)||1;
  s.sendFx({type:"shot",id:`${String(d.weapon||"smg").slice(0,6)}-${Date.now().toString(36)}-${Math.floor(performance.now()%1e6).toString(36)}`,from:localToCanonical(a),to:localToCanonical(b),dir:[dx/l,dy/l,dz/l],speed:300,wp:String(d.weapon||"smg"),hand:Number(d.hand)===1?1:0,...(pid?{playerId:pid}:{}),kind:PLAYER_FX_KIND,t:Date.now()});
  const v=viewport();if(v)v.dataset.walkReplicatedShots=String((Number(v.dataset.walkReplicatedShots)||0)+1);}
function observeWalkShot(){const v=viewport(),shots=Number(v?.dataset.walkShots||0);if(shots>lastWalkShots&&currentMode()==="foot"){const p=walk()?.position;playPistol(p,false);sendFootShot();if(v)v.dataset.walkShotAudioVisualSync="muzzle+recoil+sound";}lastWalkShots=Math.max(lastWalkShots,shots);}
function updateHumanVelocity(now){const pose=snapshotHuman();if(!lastHumanSample){lastHumanSample={...pose,at:now};humanVelocity={x:0,y:0,z:0};return;}const dt=(now-lastHumanSample.at)/1000;if(currentMode()==="foot"&&dt>.001&&dt<.5)humanVelocity={x:(pose.x-lastHumanSample.x)/dt,y:(pose.y-lastHumanSample.y)/dt,z:0};else humanVelocity={x:0,y:0,z:0};lastHumanSample={...pose,at:now};if(currentMode()==="foot"&&!globalThis.__jetMode?.active&&!globalThis.__arondightVehicleDrive?.active){const speed=Math.hypot(humanVelocity.x,humanVelocity.y),period=clamp(.50-speed*.025,.27,.48);if(speed>.55&&now-lastStepAt>period*1000){lastStepAt=now;playStep([pose.x,pose.y,0],false);const v=viewport();if(v)v.dataset.walkFootsteps=String((Number(v.dataset.walkFootsteps)||0)+1);}}}

function augmentVsPose(force=false,now=performance.now()){if(!force&&now-lastPoseTx<POSE_TX_MS)return;const b=bridge(),s=b?.vsSession,pending=s?.pendingPose;if(!s?.setPose||!pending)return;lastPoseTx=now;const human=snapshotHuman(),canonical=localToCanonical([human.x,human.y,0]),mode=currentMode(),velocity=mode==="foot"?[humanVelocity.x,humanVelocity.y,0]:[0,0,0],drive=globalThis.__arondightVehicleDrive,carPose=mode==="foot"&&drive?.active?drive.pose:null,wmode=String(globalThis.__arondightFootWeapons?.mode||"smg"),next={...pending,pm:carPose?.position?"car":mode,av:canonical,ay:human.yaw,avv:velocity,vr:mode==="drone"?1:0,wp:wmode==="glock"?"pistol":wmode==="grenade"?"smg":wmode};
    if(carPose?.position){const q=carPose.rotation||[0,0,0,1],hy=Math.atan2(2*(q[3]*q[2]+q[0]*q[1]),1-2*(q[1]*q[1]+q[2]*q[2]));next.cid=String(drive.vehicleId||"");next.cy=hy;next.cz=carPose.position[2]-groundHeightAt(carPose.position[0],carPose.position[1]);if(b.active&&Number.isFinite(b.originLon)&&Number.isFinite(b.originLat))next.cg=metersToLngLat(b.originLon,b.originLat,carPose.position[0],carPose.position[1]);next.cv=localToCanonical([carPose.position[0],carPose.position[1],0]);}if(b.active&&Number.isFinite(b.originLon)&&Number.isFinite(b.originLat))next.ag=metersToLngLat(b.originLon,b.originLat,human.x,human.y);const jp=mode==="foot"?globalThis.__jetMode?.pose:null;if(jp){next.pm="jet";next.jh=+jp.z.toFixed(1);next.jq=jp.q.map(v=>+(+v).toFixed(4));next.jt=+(+jp.t).toFixed(2);next.jab=jp.ab;next.jgr=jp.gear;next.jpa=jp.para;if(jp.geo)next.jg=jp.geo;next.jv=localToCanonical([jp.x,jp.y,0]);}{const ja=globalThis.__jetMode?.ownedAirframes;if(Array.isArray(ja)&&ja.length)next.ja=ja;}
    if(mode==="foot"){const jz=Number(globalThis.__arondightWalkJump?.z)||0;if(jz>.01)next.jz=+jz.toFixed(2);next.p=localToCanonical([human.x,human.y,.04]);next.q=yawQuaternion(human.yaw);next.v=velocity;if(next.ag)next.g=[...next.ag];}s.setPose(next);const v=viewport();if(v)v.dataset.playerPoseReplicated=mode;}
function patchPoseBridge(){const b=bridge();if(!b||b===patchedBridge||typeof b.updateVsPose!=="function")return;patchedBridge=b;if(b.__playerVehiclePoseV2Patched)return;const base=b.updateVsPose.bind(b);b.updateVsPose=()=>{const result=base();augmentVsPose(true);return result;};b.__playerVehiclePoseV2Patched=true;}
function poseAvatarLocal(pose){const b=bridge();if(Array.isArray(pose?.ag)&&pose.ag.length===2&&b?.active&&Number.isFinite(b.originLon)&&Number.isFinite(b.originLat)){const [x,y]=lngLatToMeters(b.originLon,b.originLat,Number(pose.ag[0]),Number(pose.ag[1]));return[x,y,0];}return canonicalToLocal(pose?.av||pose?.p||[0,0,0]);}
function createRemoteAvatar(id){const r=buildHumanAvatar(id,{local:false});if(r)remoteAvatars.set(id,r);return r;}
function onPose(event){const peerId=String(event?.detail?.peerId||""),pose=event?.detail?.pose;if(!peerId||!pose||!Array.isArray(pose.av)||!(pose.pm==="foot"||pose.pm==="drone"||pose.pm==="car"||pose.pm==="jet"))return;const r=remoteAvatars.get(peerId)||createRemoteAvatar(peerId);if(!r)return;r.lastJz=Number.isFinite(+pose.jz)?Math.max(0,Math.min(2,+pose.jz)):0;const p=poseAvatarLocal(pose);r.target.set(Number(p[0])||0,Number(p[1])||0,0);r.yaw=Number(pose.ay)||0;r.mode=pose.pm;r.velocity.set(Number(pose.avv?.[0])||0,Number(pose.avv?.[1])||0,0);r.lastPose=performance.now();r.weapon=String(pose.wp||"none");
  {const prevCar=r.carId,nowCar=pose.pm==="car"?String(pose.cid||""):"";if(prevCar&&prevCar!==nowCar)globalThis.__arondightProceduralPopulation?.setRemoteDriven?.(prevCar,false);if(nowCar)globalThis.__arondightProceduralPopulation?.setRemoteDriven?.(nowCar,true);r.carId=nowCar;
   if(pose.pm==="car"){const b=bridge();let cx,cy;if(Array.isArray(pose.cg)&&b?.active&&Number.isFinite(b.originLon)){[cx,cy]=lngLatToMeters(b.originLon,b.originLat,Number(pose.cg[0]),Number(pose.cg[1]));}else{const c=canonicalToLocal(pose.cv||pose.av);cx=c[0];cy=c[1];}r.car={x:Number(cx)||0,y:Number(cy)||0,yaw:Number(pose.cy)||0,lift:Number(pose.cz)||.6};}else r.car=null;}
  {const jm=globalThis.__jetMode;if(pose.pm==="jet"){const b=bridge();let jx,jy;if(Array.isArray(pose.jg)&&b?.active&&Number.isFinite(b.originLon)){[jx,jy]=lngLatToMeters(b.originLon,b.originLat,Number(pose.jg[0]),Number(pose.jg[1]));}else{const c=canonicalToLocal(pose.jv||pose.av);jx=c[0];jy=c[1];}jm?.peer?.(peerId,{x:jx,y:jy,z:Number(pose.jh)||0,q:pose.jq,t:pose.jt,ab:pose.jab,gear:pose.jgr,para:pose.jpa});r.inJet=true;}else if(r.inJet){jm?.peer?.(peerId,null);r.inJet=false;}jm?.peerAirframes?.(peerId,Array.isArray(pose.ja)?pose.ja:[]);}
  r.headset.visible=r.strap.visible=r.controllerL.visible=r.controllerR.visible=pose.pm==="drone";r.pack.visible=pose.pm==="foot";const v=viewport();if(v)v.dataset.vsHumanPoseEvents=String((Number(v.dataset.vsHumanPoseEvents)||0)+1);}
function onPeer(event){const id=String(event?.detail?.peerId||"");if(event?.detail?.type!=="leave"||!id)return;const r=remoteAvatars.get(id);if(r){r.root.parent?.remove(r.root);if(r.carMesh){r.carMesh.parent?.remove(r.carMesh);r.carMesh=null;}if(r.carId){globalThis.__arondightProceduralPopulation?.setRemoteDriven?.(r.carId,false);r.carId="";}remoteAvatars.delete(id);}peerDroneNodes.delete(id);globalThis.__jetMode?.peer?.(id,null);globalThis.__jetMode?.peerAirframes?.(id,[]);}
function refreshPeerDrones(now){if(now-lastPeerScan<PEER_SCAN_MS)return;lastPeerScan=now;peerDroneNodes.clear();const scene=bridge()?.threeScene;if(!scene)return;scene.traverse?.(node=>{const id=String(node?.userData?.vsPlayerId||"");if(!id||node.userData?.vsHumanAvatar)return;if(node.userData?.vsMultiplayerPeer||node.userData?.vsLegacyPrimary||node.userData?.vsPeer){const list=peerDroneNodes.get(id)||[];list.push(node);peerDroneNodes.set(id,list);}});}
function ensureRemoteCar(r){if(r.carMesh?.parent)return r.carMesh;const scene=bridge()?.threeScene;if(!scene)return null;const g=new THREE.Group();g.name=`VS_CAR_${r.id}`;const body=new THREE.Mesh(vehicleGeometry("car",shirtColorFor(r.id+"car")),vehicleMaterial);body.castShadow=true;g.add(body);const wg=wheelGeometry();for(const[x,y]of[[1.2,.78],[1.2,-.78],[-1.15,.78],[-1.15,-.78]]){const w=new THREE.Mesh(wg,vehicleMaterial);w.position.set(x,y,.34);g.add(w);}g.traverse(n=>{n.userData.vsPlayerId=r.id;});scene.add(g);r.carMesh=g;return g;}
function renderRemoteAvatars(now,dt){refreshPeerDrones(now);let visible=0,vr=0,cars=0;const alpha=1-Math.exp(-dt*14);for(const r of remoteAvatars.values()){const stale=now-r.lastPose>STALE_MS;if(stale){r.root.visible=false;if(r.carMesh)r.carMesh.visible=false;if(r.carId){globalThis.__arondightProceduralPopulation?.setRemoteDriven?.(r.carId,false);r.carId="";}continue;}visible++;r.root.visible=true;
  if(r.mode==="jet"){r.root.visible=false;if(r.carMesh)r.carMesh.visible=false;for(const node of peerDroneNodes.get(r.id)||[])node.visible=false;continue;}
  const headset=r.mode==="drone";for(const node of peerDroneNodes.get(r.id)||[])node.visible=headset;if(headset)vr++;
  if(r.mode==="car"&&r.car){const c=ensureRemoteCar(r);if(c){cars++;const gz=groundHeightAt(r.car.x,r.car.y);if(!c.visible){c.position.set(r.car.x,r.car.y,gz);c.rotation.set(0,0,r.car.yaw);}c.visible=true;c.position.x+=(r.car.x-c.position.x)*alpha;c.position.y+=(r.car.y-c.position.y)*alpha;c.position.z=groundHeightAt(c.position.x,c.position.y);let dy=r.car.yaw-c.rotation.z;dy=((dy+Math.PI)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)-Math.PI;c.rotation.z+=dy*alpha;
      // driver seat (left-hand drive): character faces the car's +x
      const h=c.rotation.z,fx=Math.cos(h),fy=Math.sin(h);r.root.position.set(c.position.x-fx*.15-fy*.38,c.position.y-fy*.15+fx*.38,c.position.z+.05);r.root.rotation.set(0,0,h-Math.PI/2);animateCharacter(r.rig,{state:"drive",dt});}continue;}
  if(r.carMesh)r.carMesh.visible=false;
  r.root.position.x+=(r.target.x-r.root.position.x)*alpha;r.root.position.y+=(r.target.y-r.root.position.y)*alpha;r.jz=(r.jz||0)+((Number(r.lastJz)||0)-(r.jz||0))*Math.min(1,alpha*1.5);r.root.position.z=groundHeightAt(r.root.position.x,r.root.position.y)+(r.jz||0);
  let d=r.yaw-r.root.rotation.z;d=((d+Math.PI)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)-Math.PI;r.root.rotation.z+=d*alpha;
  const speed=Math.hypot(r.velocity.x,r.velocity.y),walking=r.mode==="foot"&&speed>.22;
  animateCharacter(r.rig,{state:headset?"vr":walking?(speed>3.2?"run":"walk"):"idle",speed:walking?speed:0,weapon:r.mode==="foot"?r.weapon:"none",dt});{const k=now-(r.lastShotAt||-1e9);if(k>=0&&k<120){const kick=Math.sin(Math.PI*k/120)*.22;r.rig.arms.R.sh.rotation.x+=kick;if(r.weapon==="akimbo")r.rig.arms.L.sh.rotation.x+=kick;}}
  if(walking&&now-r.lastStep>Math.max(270,Math.min(480,500-speed*22))){r.lastStep=now;playStep(r.root.position,true);}}
  const v=viewport();if(v){v.dataset.vsHumanAvatars=String(remoteAvatars.size);v.dataset.vsHumanAvatarsVisible=String(visible);v.dataset.vsVrAvatars=String(vr);v.dataset.vsRemoteCars=String(cars);v.dataset.vsAvatarModel="articulated-v3";}}

function vsPlayerId(hit){for(let node=hit?.object;node;node=node.parent){const id=String(node.userData?.vsPlayerId||"");if(id)return id;}return"";}
function patchWorldHitRouting(){const b=bridge(),base=b?.registerWorldPopulationHit;if(!b||typeof base!=="function"||base.__playerVehicleHitRouterV2||!base.__worldLivelinessWrapper)return;const wrapper=hit=>{const id=vsPlayerId(hit);if(id&&!hitRouting&&typeof b.registerVsHit==="function"){hitRouting=true;try{return Boolean(b.registerVsHit(hit));}finally{hitRouting=false;}}return Boolean(base(hit));};wrapper.__playerVehicleHitRouterV2=true;wrapper.__worldLivelinessWrapper=true;wrapper.__gameplayPolishLiteWrapper=true;b.registerWorldPopulationHit=wrapper;const v=viewport();if(v)v.dataset.walkVsHitRouting="1";}
function patchFxSession(){const session=activeSession();if(!session||session===lastFxSession||typeof session.sendFx!=="function")return;lastFxSession=session;if(session.__playerVehicleFxV2Patched)return;session.__playerVehicleFxV2Patched=true;const base=session.sendFx.bind(session);session.sendFx=(packet,options)=>{if(packet?.type===WORLD_LIFE_FX_KIND){if(applyingRemoteWorldLife)return true;const pid=selfId(),next={...packet,type:"impact",kind:WORLD_LIFE_FX_KIND,objectKind:packet.kind,...(pid?{playerId:pid}:{})};return base(next,options);}return base(packet,options);};}
function findWorldLife(id){let found=null;bridge()?.threeScene?.traverse?.(node=>{if(found)return;const nodeId=String(node?.userData?.worldLifeId||node?.userData?.worldPopulationId||"");if(nodeId===String(id||""))found=node;});return found;}
function applyRemoteWorldLife(packet){const b=bridge(),object=findWorldLife(packet?.objectId);if(!b||!object||typeof b.registerWorldPopulationHit!=="function")return false;object.getWorldPosition(tmp);applyingRemoteWorldLife=true;try{return Boolean(b.registerWorldPopulationHit({object,point:tmp.clone()}));}finally{applyingRemoteWorldLife=false;}}

function ensureMuzzlePool(){const scene=bridge()?.threeScene;if(!scene)return;if(scene!==muzzleScene){for(const m of muzzlePool)m.group.parent?.remove(m.group);muzzlePool.length=0;muzzleScene=scene;muzzleGeo=new THREE.SphereGeometry(.045,7,5);muzzleConeGeo=new THREE.ConeGeometry(.065,.19,7);}while(muzzlePool.length<8){const group=new THREE.Group(),mat=new THREE.MeshBasicMaterial({color:0xffd36b,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}),core=new THREE.Mesh(muzzleGeo,mat),cone=new THREE.Mesh(muzzleConeGeo,mat.clone());cone.position.y=.09;for(const m of[core,cone])m.userData.flightFireIgnore=true;group.add(core,cone);group.visible=false;scene.add(group);muzzlePool.push({group,core,cone,born:0,expires:0});}}
function spawnRemoteMuzzle(position,dir){ensureMuzzlePool();if(!muzzlePool.length)return;const item=muzzlePool.find(x=>!x.group.visible)||muzzlePool.reduce((a,b)=>a.born<=b.born?a:b),d=new THREE.Vector3(Number(dir?.[0])||0,Number(dir?.[1])||1,Number(dir?.[2])||0).normalize();item.group.position.set(Number(position?.[0])||0,Number(position?.[1])||0,Number(position?.[2])||0);item.group.quaternion.setFromUnitVectors(forwardAxis,d);item.born=performance.now();item.expires=item.born+85;item.core.material.opacity=.95;item.cone.material.opacity=.8;item.group.visible=true;}
function ensureBlastPool(){const scene=bridge()?.threeScene;if(!scene)return;if(scene!==blastScene){for(const b of blastPool)b.group.parent?.remove(b.group);blastPool.length=0;blastScene=scene;blastGeo=new THREE.SphereGeometry(.18,10,7);blastRingGeo=new THREE.RingGeometry(.45,.72,20);}while(blastPool.length<6){const group=new THREE.Group(),core=new THREE.Mesh(blastGeo,new THREE.MeshBasicMaterial({color:0xffd98a,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending})),shell=new THREE.Mesh(blastGeo,new THREE.MeshBasicMaterial({color:0xff6f32,transparent:true,opacity:0,depthWrite:false,side:THREE.BackSide,blending:THREE.AdditiveBlending})),ring=new THREE.Mesh(blastRingGeo,new THREE.MeshBasicMaterial({color:0xffb45d,transparent:true,opacity:0,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending}));for(const m of[core,shell,ring])m.userData.flightFireIgnore=true;group.add(core,shell,ring);group.visible=false;scene.add(group);blastPool.push({group,core,shell,ring,born:0,expires:0,small:false});}}
function spawnRoundBlast(position,small=false){ensureBlastPool();if(!blastPool.length)return;const item=blastPool.find(x=>!x.group.visible)||blastPool.reduce((a,b)=>a.born<=b.born?a:b);item.group.position.set(Number(position?.[0])||0,Number(position?.[1])||0,Math.max(.05,Number(position?.[2])||.05));item.born=performance.now();item.expires=item.born+(small?320:900);item.small=small;item.group.visible=true;}
function renderFx(now){for(const item of muzzlePool){if(!item.group.visible)continue;if(now>=item.expires){item.group.visible=false;continue;}const t=(now-item.born)/(item.expires-item.born);item.core.material.opacity=.95*(1-t);item.cone.material.opacity=.8*(1-t);item.group.scale.setScalar(.8+.55*Math.sin(Math.PI*t));}for(const item of blastPool){if(!item.group.visible)continue;if(now>=item.expires){item.group.visible=false;continue;}const t=(now-item.born)/(item.expires-item.born),e=1-(1-t)**3,k=item.small?.45:1;item.core.scale.setScalar(k*(.45+2.7*e));item.shell.scale.setScalar(k*(.65+5.2*e));item.ring.scale.setScalar(k*(.8+7.0*e));item.core.material.opacity=.95*(1-t);item.shell.material.opacity=.45*(1-t)**1.45;item.ring.material.opacity=.62*(1-t)**1.8;}}
function remoteFxPosition(packet,key="p"){return canonicalToLocal(packet?.[key]||[0,0,0]);}
let remoteTracers=[];
function spawnRemoteTracer(from,to){const scene=bridge()?.threeScene;if(!scene||!Array.isArray(from)||!Array.isArray(to))return;if(!remoteTracers.length||remoteTracers[0].parent!==scene){remoteTracers=[];const geo=new THREE.CylinderGeometry(.03,.03,1,6),mat=new THREE.MeshBasicMaterial({color:0xffc070,transparent:true,opacity:.9,depthWrite:false,blending:THREE.AdditiveBlending,toneMapped:false});for(let i=0;i<16;i++){const m=new THREE.Mesh(geo,mat.clone());m.visible=false;m.frustumCulled=false;m.userData.flightFireIgnore=true;m.userData.neonSkip=true;scene.add(m);remoteTracers.push(m);}}
  const m=remoteTracers.find(x=>!x.visible)||remoteTracers[0],a=new THREE.Vector3(...from),b=new THREE.Vector3(...to),d=b.clone().sub(a),l=d.length();if(l<.05)return;m.position.copy(a).addScaledVector(d,.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());m.scale.set(1,l,1);m.visible=true;m.userData.born=performance.now();m.material.opacity=.9;}
function stepRemoteTracers(now){for(const m of remoteTracers){if(!m.visible)continue;const t=(now-m.userData.born)/160;if(t>=1){m.visible=false;continue;}m.material.opacity=.9*(1-t);m.scale.x=m.scale.z=1-t*.7;}}
function playRemoteWeapon(position,weapon){const ctx=ensureAudio(false),volume=settingsGain("shots")*spatialGain(position)*.75;if(!ctx||ctx.state!=="running"||!fxMaster||volume<=0)return false;return playCombatAudio(ctx,weapon==="glock"||weapon==="pistol"?"pistol":"shot",{destination:fxMaster,gain:(weapon==="grenade"?.5:.42)*volume,playbackRate:weapon==="grenade"?.62:1,minIntervalMs:30});}
// A car someone left is parked at the same spot for everybody.
function sendCarParked(event){const d=event?.detail,s=playerSession();if(!d?.id||!s?.sendFx||!Number.isFinite(d.x)||!Number.isFinite(d.y))return;s.sendFx({type:"impact",kind:"car-park",objectId:"vehicle-park",id:`park-${Date.now().toString(36)}`,cid:String(d.id).slice(0,64),p:localToCanonical([d.x,d.y,0]),yaw:Number(d.yaw)||0,playerId:selfId()||undefined});}
function onFx(event){const packet=event?.detail?.packet;if(!packet)return;if(String(packet.kind||"").startsWith("world-sync"))return;if(packet.type==="impact"&&packet.kind==="car-park"&&packet.cid){const p=remoteFxPosition(packet);globalThis.__arondightProceduralPopulation?.parkAt?.(String(packet.cid),{x:p[0],y:p[1],yaw:Number(packet.yaw)||0});return;}if(packet.objectId)return;/* module packets (police, military, zombies, jets, people, votes) belong to their modules: never a blast here */if(packet.type==="shot"&&packet.kind===PLAYER_FX_KIND){const p=remoteFxPosition(packet,"from");if(packet.wp)playRemoteWeapon(p,String(packet.wp));else playPistol(p,true);spawnRemoteMuzzle(p,packet.dir);if(Array.isArray(packet.to))spawnRemoteTracer(p,remoteFxPosition(packet,"to"));const av=remoteAvatars.get(String(packet.playerId||event?.detail?.peerId||""));if(av){av.lastShotAt=performance.now();av.weapon=packet.wp==="glock"?"pistol":String(packet.wp||av.weapon);}const v=viewport();if(v)v.dataset.vsRemotePistolSounds=String((Number(v.dataset.vsRemotePistolSounds)||0)+1);return;}if(packet.type==="impact"&&packet.kind===WORLD_LIFE_FX_KIND){applyRemoteWorldLife(packet);return;}if(packet.type==="explosion"){const p=remoteFxPosition(packet);spawnRoundBlast(p,false);playExplosion(p,false);}else if(packet.type==="impact"&&packet.kind!==WORLD_LIFE_FX_KIND){const p=remoteFxPosition(packet);spawnRoundBlast(p,true);playExplosion(p,true);}}
function onWorldExplosion(event){const p=event?.detail?.position;if(!p)return;if(event?.detail?.kind==="nuke")return;playExplosion(p,false);}

function updatePerf(now){perfFrames++;const elapsed=now-perfStart;if(elapsed<1000)return;const fps=perfFrames*1000/elapsed,v=viewport();if(v){v.dataset.walkRuntimeFps=fps.toFixed(1);v.dataset.walkPerfProfile="cached-spatial-no-frame-traverse-v2";}perfStart=now;perfFrames=0;}
let lastIntegrationPatch=-Infinity;function frame(now=performance.now()){const dt=clamp((now-lastFrame)/1000,0,.05);lastFrame=now;stepRemoteTracers(now);if(now-lastIntegrationPatch>=250){lastIntegrationPatch=now;patchPoseBridge();patchWorldHitRouting();patchFxSession();}syncMode();if(pendingTeleport)teleportDrone(pendingTeleport.anchor,{hidden:pendingTeleport.hidden,launchOffset:pendingTeleport.launchOffset});updateHumanVelocity(now);observeWalkShot();augmentVsPose(false,now);renderLocalAvatar();renderRemoteAvatars(now,dt);renderFx(now);updatePerf(now);requestAnimationFrame(frame);}

export function installPlayerVehicleRuntime(){if(installed)return;installed=true;addEventListener("arondight:foot-tracer",sendFootTracer);addEventListener("arondight:car-parked",sendCarParked);patchMotorRuntime();lastWalkShots=Number(viewport()?.dataset.walkShots||0);addEventListener("pointerdown",()=>ensureAudio(true),{capture:true,passive:true});addEventListener("keydown",()=>ensureAudio(true),{capture:true});addEventListener(VS_POSE_EVENT,onPose);addEventListener(VS_PEER_EVENT,onPeer);addEventListener(VS_FX_EVENT,onFx);addEventListener("arondight:world-explosion",onWorldExplosion);const v=viewport();if(v){v.dataset.playerVehicleRuntime="human-drone-v2";v.dataset.playerVehicleDamageTargets="pilot+drone-independent-v1";v.dataset.walkCollisionRadiusM=HUMAN_RADIUS.toFixed(2);v.dataset.walkPistolSound="prebaked-pcm-synced-v3";v.dataset.walkAudioProfile=COMBAT_AUDIO_BANK_VERSION;v.dataset.walkShotSamplePlays="0";v.dataset.combatAudioRuntimeOscillators="0";v.dataset.walkPerfProfile="cached-spatial-no-frame-traverse-v2";}globalThis.__arondightPlayerVehicleRuntime={get mode(){return currentMode();},get humanAnchor(){return{...humanAnchor};},get humanVelocity(){return{...humanVelocity};},get humanMesh(){return ensureLocalAvatar()?.root||null;},get droneMesh(){return airframe();},get dronePose(){return airframePose();},get remoteAvatarCount(){return remoteAvatars.size;},remotePlayers(){const out=[],now=performance.now();for(const r of remoteAvatars.values()){if(now-r.lastPose>STALE_MS||!r.root)continue;const drone=[...(peerDroneNodes.get(r.id)||[])].find(n=>n.visible!==false&&!n.userData?.vsVrHeadset);out.push({id:r.id,mode:r.mode,body:[r.root.position.x,r.root.position.y,r.root.position.z+1],drone:r.mode==="drone"&&drone?.position?[drone.position.x,drone.position.y,drone.position.z]:null});}return out;},sync:syncMode,teleportDrone:anchor=>teleportDrone(anchor||snapshotHuman(),{hidden:currentMode()==="foot"}),resolveWalkMove,canOccupyWalkPoint};requestAnimationFrame(frame);}
