import * as THREE from "three";
import {createPlayerHumanRig,hidePlayerHumanRig,setPlayerHumanVehiclePose} from "./player_human_rig.mjs";
import {findXboxGamepad} from "./xbox_gamepad.mjs";
import {loadPhoneControlSettings} from "./drone_control_settings.mjs";
import {VEHICLE_CONTROL_SETTINGS_EVENT,loadVehicleControlSettings,normalizeVehicleControlSettings} from "./vehicle_control_settings.mjs";

const ENTER_RADIUS_M=4.2;
const DRIVE_OWNER="local-player";
const DRIVE_LEASE_MS=460;
const PLAYER_CAR_MAX_STEER_ANGLE_RAD=.5585053606381855;
const keys=new Set();
const tmp=new THREE.Vector3();
const forward=new THREE.Vector3();
const target=new THREE.Vector3();
const raycaster=new THREE.Raycaster();
const pickNdc=new THREE.Vector2();
let installed=false,active=false,vehicle=null,heading=0,commandSpeed=0,lastFrame=performance.now(),cameraInstalled=false,baseCameraProvider=null;
let localDriverRig=null;
let touchSteer=0,touchPedal=0,touchGas=false,touchBrake=false,handbrake=false,lastNearestScan=-Infinity,nearest=null,lastGamepadInteract=false;
let settings=loadVehicleControlSettings();
const nativeGetGamepads=typeof navigator!=="undefined"&&navigator.getGamepads?navigator.getGamepads.bind(navigator):()=>[];
const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||0));

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function physics(){return globalThis.__arondightWorldRigidBodies||null;}
function walk(){return globalThis.__arondightWalkMode||null;}
function playerDead(){return Boolean(globalThis.__arondightPlayerDamageModel?.dead);}
function quaternionYaw(q){if(!Array.isArray(q)||q.length<4)return 0;const[x,y,z,w]=q.map(Number);return Math.atan2(2*(w*z+x*y),1-2*(y*y+z*z));}
function vehiclePose(){const pose=vehicle?physics()?.pose?.(vehicle.id):null;if(pose?.position)return pose;if(vehicle?.root)return{position:[vehicle.root.position.x,vehicle.root.position.y,vehicle.root.position.z+.42],rotation:[vehicle.root.quaternion.x,vehicle.root.quaternion.y,vehicle.root.quaternion.z,vehicle.root.quaternion.w],velocity:[0,0,0],angularVelocity:[0,0,0]};return null;}
function vehicleRoots(){const scene=bridge()?.threeScene,out=[];if(!scene)return out;scene.traverse(node=>{if(!node?.isGroup||node.visible===false)return;const kind=String(node.userData?.worldPopulationKind||""),id=String(node.userData?.worldPopulationId||node.userData?.worldProceduralId||"");if(kind==="car"&&id&&!node.userData?.remotePlayerDriven)out.push({id,root:node});});return out;}
function authoritativeVehiclePoint(record){const pose=record?.id?physics()?.pose?.(record.id):null;if(pose?.position)return{x:Number(pose.position[0])||0,y:Number(pose.position[1])||0,pose};record?.root?.getWorldPosition?.(tmp);return{x:tmp.x,y:tmp.y,pose:null};}
function nearestVehicle(now=performance.now()){if(active)return vehicle;if(now-lastNearestScan<240)return nearest;lastNearestScan=now;nearest=null;const w=walk();if(w?.mode!=="foot"||!w.position)return null;let best=ENTER_RADIUS_M;for(const record of vehicleRoots()){const point=authoritativeVehiclePoint(record),d=Math.hypot(point.x-w.position.x,point.y-w.position.y);if(d<best){best=d;nearest={...record,distance:d,physicsPose:point.pose};}}return nearest;}
function logicalScreenPoint(clientX,clientY){const view=viewport(),screen=view?.getBoundingClientRect();if(!view||!screen)return null;const width=Math.max(1,view.clientWidth),height=Math.max(1,view.clientHeight),cx=Number(clientX),cy=Number(clientY),rotated=view.dataset.soloOrientation==="css-landscape",x=rotated?cy-screen.top:cx-screen.left,y=rotated?screen.right-cx:cy-screen.top;return{x:clamp(x,0,width),y:clamp(y,0,height),width,height};}
function vehicleAtScreenPoint(clientX,clientY){if(active||walk()?.mode!=="foot")return null;const camera=bridge()?.threeCamera,point=logicalScreenPoint(clientX,clientY),w=walk();if(!camera||!point||!w?.position)return null;const roots=vehicleRoots();if(!roots.length)return null;pickNdc.set(point.x/point.width*2-1,1-point.y/point.height*2);raycaster.setFromCamera(pickNdc,camera);const hits=raycaster.intersectObjects(roots.map(item=>item.root),true);for(const hit of hits){let node=hit.object,id="";while(node&&!id){id=String(node.userData?.worldPopulationId||node.userData?.worldProceduralId||"");node=node.parent;}if(!id)continue;const record=roots.find(item=>item.id===id);if(!record)continue;const physical=authoritativeVehiclePoint(record),distance=Math.hypot(physical.x-w.position.x,physical.y-w.position.y);if(distance<=ENTER_RADIUS_M)return{...record,distance,physicsPose:physical.pose,screenHitDistance:Number(hit.distance)||0};}return null;}
function tryEnterAtScreenPoint(clientX,clientY){const record=vehicleAtScreenPoint(clientX,clientY);if(!record)return false;const ok=enter(record),v=viewport();if(v){v.dataset.vehicleInteract=ok?"screen-car-raycast-enter-v1":"screen-car-raycast-gated-v1";v.dataset.vehicleInteractId=record.id;}return ok;}
function clearFootKeys(){for(const code of["KeyW","KeyA","KeyS","KeyD","ShiftLeft","ShiftRight"])dispatchEvent(new KeyboardEvent("keyup",{code}));}
function resetPads(){touchSteer=0;touchPedal=0;touchGas=false;touchBrake=false;handbrake=false;keys.clear();const knob=document.querySelector("#vehicleSteer .knob");if(knob)knob.style.left="50%";for(const id of["vehicleGas","vehicleBrake"])document.getElementById(id)?.classList.remove("held");const v=viewport();if(v){v.dataset.vehicleInputLifecycle="released";v.dataset.vehicleTouchThrottle="0";}}
function suppressFootGamepad(value){try{if(value)Object.defineProperty(navigator,"getGamepads",{configurable:true,value:()=>[]});else delete navigator.getGamepads;}catch{}}
function setDrivingUi(value){document.body.classList.toggle("player-driving",value);const modeButton=document.getElementById("playerModeButton");if(modeButton){modeButton.disabled=value;modeButton.style.opacity=value?".45":"";}const view=viewport();if(view){view.dataset.playerDriveMode=value?"vehicle":"off";view.dataset.playerControlMode=value?"vehicle":(walk()?.mode||"drone");view.dataset.playerBodyState=value?"vehicle-seated":"foot";}}
function showLocalDriver(root){if(!root)return false;if(!localDriverRig)localDriverRig=createPlayerHumanRig({id:"local-player",color:0x29d6ff});const ok=setPlayerHumanVehiclePose(localDriverRig,root,{driverSide:-1});if(ok){localDriverRig.group.userData.localPlayerVehicleDriver=true;const view=viewport();if(view)view.dataset.vehicleLocalOccupant="full-human-seated-v1";}return ok;}
function hideLocalDriver(){if(localDriverRig)hidePlayerHumanRig(localDriverRig);const view=viewport();if(view)view.dataset.vehicleLocalOccupant="hidden-on-foot-v1";}
function enter(record=nearestVehicle()){
  if(active||playerDead()||walk()?.mode!=="foot"||!record?.id||record.root?.userData?.remotePlayerDriven)return false;const p=physics(),pose=p?.pose?.(record.id);if(!pose?.position)return false;
  vehicle={id:record.id,root:record.root||vehicleRoots().find(item=>item.id===record.id)?.root||null};heading=Number.isFinite(pose.yaw)?pose.yaw:quaternionYaw(pose.rotation);forward.set(Math.cos(heading),Math.sin(heading),0);const velocity=Array.isArray(pose.velocity)?[...pose.velocity]:[0,0,0];if(vehicle.root){vehicle.root.userData.playerDriven=true;vehicle.root.userData.worldTrafficControlOwner=DRIVE_OWNER;}p?.clearTarget?.(vehicle.id,{force:true});p?.setPose?.(vehicle.id,{position:[...pose.position],yaw:heading,velocity,angularVelocity:[0,0,0]});commandSpeed=clamp((Number(velocity[0])||0)*forward.x+(Number(velocity[1])||0)*forward.y,-settings.reverseSpeedKmh/3.6,settings.maxSpeedKmh/3.6);const v=viewport();if(v){v.dataset.vehicleEnterAuthority="box3d-player-handoff-v2";v.dataset.vehicleEnterYawTransfer="linear-preserve+yaw-zero-v1";}clearFootKeys();resetPads();suppressFootGamepad(true);active=true;showLocalDriver(vehicle.root);setDrivingUi(true);window.dispatchEvent(new CustomEvent("arondight:vehicle-mode",{detail:{active:true,id:vehicle.id,owner:DRIVE_OWNER,occupant:"player-human"}}));return true;
}
function exit({forced=false}={}){
  if(!active)return false;const pose=vehiclePose(),id=vehicle?.id,root=vehicle?.root;hideLocalDriver();if(pose?.position){const sideX=-Math.sin(heading),sideY=Math.cos(heading),x=pose.position[0]+sideX*2.15,y=pose.position[1]+sideY*2.15;walk()?.setPose?.({x,y,yaw:Math.PI/2-heading,pitch:0});}if(root){delete root.userData.playerDriven;delete root.userData.worldTrafficControlOwner;if(root.userData.worldParked)root.userData.worldParkedReanchor=true;}physics()?.clearTarget?.(id,{owner:DRIVE_OWNER});active=false;vehicle=null;commandSpeed=0;resetPads();suppressFootGamepad(false);setDrivingUi(false);window.dispatchEvent(new CustomEvent("arondight:vehicle-mode",{detail:{active:false,id,forced,owner:DRIVE_OWNER}}));return true;
}
function sampleGamepad(){if(loadPhoneControlSettings().xboxControllerEnabled===false)return null;return findXboxGamepad(nativeGetGamepads());}
function button(pad,index){const b=pad?.buttons?.[index];return clamp(typeof b==="number"?b:(b?.value??(b?.pressed?1:0)),0,1);}
function axis(value,dead=.08){const v=clamp(value,-1,1),a=Math.abs(v);return a<=dead?0:Math.sign(v)*(a-dead)/(1-dead);}
function pollGamepadInteract(){const pad=sampleGamepad(),held=button(pad,3)>.55;if(held&&!lastGamepadInteract){const record=nearestVehicle();if(active)exit();else if(record)enter(record);const v=viewport();if(v){v.dataset.vehicleInteract="gamepad-standard-button3-y-v1";v.dataset.vehicleInteractButton="3";}}lastGamepadInteract=held;}
function controls(){let steer=(keys.has("KeyD")?1:0)-(keys.has("KeyA")?1:0)+touchSteer,pedal=(keys.has("KeyW")?1:0)-(keys.has("KeyS")?1:0)+touchPedal+(touchGas?1:0)-(touchBrake?1:0),brake=handbrake||keys.has("Space");const pad=sampleGamepad();if(pad){steer+=axis(pad.axes?.[0]);pedal+=button(pad,7)-button(pad,6);brake=brake||button(pad,1)>.55;}return{steer:clamp(steer,-1,1)*settings.steeringSensitivityPercent/100,pedal:clamp(pedal,-1,1)*settings.throttleSensitivityPercent/100,brake};}
function updateDrive(now,dt){
  if(!active)return;const pose=vehiclePose();if(!pose?.position||vehicle?.root?.visible===false){exit({forced:true});return;}const input=controls(),maxForward=settings.maxSpeedKmh/3.6,maxReverse=settings.reverseSpeedKmh/3.6,accel=8.4,decel=11.5;
  if(input.brake)commandSpeed*=Math.exp(-8.5*dt);else if(input.pedal>0)commandSpeed+=input.pedal*accel*dt;else if(input.pedal<0)commandSpeed+=input.pedal*decel*dt;else commandSpeed*=Math.exp(-.72*dt);commandSpeed=clamp(commandSpeed,-maxReverse,maxForward);if(Math.abs(commandSpeed)<.06)commandSpeed=0;
  const bodyYaw=Number.isFinite(pose.yaw)?pose.yaw:quaternionYaw(pose.rotation),travelSign=commandSpeed<0?-1:1;heading=bodyYaw;forward.set(Math.cos(bodyYaw),Math.sin(bodyYaw),0);const distance=commandSpeed===0?0:8+Math.min(13,Math.abs(commandSpeed)*.42);target.set(pose.position[0]+forward.x*distance*travelSign,pose.position[1]+forward.y*distance*travelSign,Math.max(.42,pose.position[2]));
  physics()?.setTarget?.(vehicle.id,{position:[target.x,target.y,target.z],yaw:bodyYaw,speedMps:Math.abs(commandSpeed),signedSpeedMps:commandSpeed,steer:input.steer,maxSteerAngleRad:PLAYER_CAR_MAX_STEER_ANGLE_RAD,response:input.brake?6.2:4.4,maxAccelerationMps2:input.brake?18:11.5,owner:DRIVE_OWNER,priority:100,leaseMs:DRIVE_LEASE_MS});
  walk()?.setPose?.({x:pose.position[0],y:pose.position[1],yaw:Math.PI/2-heading,pitch:0});const view=viewport();if(view){view.dataset.vehicleDriveId=vehicle.id;view.dataset.vehicleDriveSpeedKmh=(Math.abs(commandSpeed)*3.6).toFixed(1);view.dataset.vehicleDriveSteer=input.steer.toFixed(3);view.dataset.vehicleDriveThrottle=input.pedal.toFixed(3);view.dataset.vehicleDrivePhysics="box3d-exclusive-owner+lateral-tire-grip-v2";view.dataset.vehicleDriveOwner=DRIVE_OWNER;view.dataset.vehicleTouchControls="steer+gas+brake-multitouch-v1";view.dataset.vehicleEnterInteraction="screen-raycast+keyboard-e+gamepad-y-v1";view.dataset.vehicleEnterAuthority="box3d-player-handoff-v2";view.dataset.vehicleEnterYawTransfer="linear-preserve+yaw-zero-v1";view.dataset.vehicleDriveLateralSlipMps=Number(pose.lateralSlipMps||0).toFixed(3);view.dataset.vehicleDriveController="keyboard+multitouch+xbox-v4";view.dataset.vehicleDriveHeadingSource="box3d-body-yaw-v1";view.dataset.vehicleDriveSteeringPhysics="box3d-bicycle-yaw-rate-v1";view.dataset.vehicleDriveBodyYaw=bodyYaw.toFixed(4);view.dataset.vehicleDriveTraversal="free-world-box3d-collision-only-v1";}
}
function applyDriveCamera({camera,now}){const pose=vehiclePose();if(!pose?.position)return null;const d=settings.cameraDistanceM,h=settings.cameraHeightM;forward.set(Math.cos(heading),Math.sin(heading),0);target.set(pose.position[0]+forward.x*1.05,pose.position[1]+forward.y*1.05,pose.position[2]+.78);camera.position.set(target.x-forward.x*d,target.y-forward.y*d,target.z+h);camera.up.set(0,0,1);camera.lookAt(target);camera.fov=72;camera.updateProjectionMatrix?.();camera.updateMatrixWorld?.(true);const view=viewport();if(view){view.dataset.vehicleCamera="collision-guarded-chase-v1";view.dataset.vehicleCameraAnchor=`${target.x.toFixed(3)},${target.y.toFixed(3)},${target.z.toFixed(3)}`;}return{active:true,mode:"vehicle",origin:"car-chase",now};}
const driveCameraProvider={isActive:()=>active||Boolean(baseCameraProvider?.isActive?.()),apply:args=>active?applyDriveCamera(args):baseCameraProvider?.apply?.(args)};
function ensureCameraProvider(){if(cameraInstalled)return;const b=bridge(),current=b?.presentationCameraProvider;if(!b||typeof b.attachPresentationCameraProvider!=="function"||!current)return;baseCameraProvider=current;b.attachPresentationCameraProvider(driveCameraProvider);cameraInstalled=true;const v=viewport();if(v)v.dataset.playerCameraStack="walk+vehicle-v1";}
function installStyle(){if(document.querySelector("style[data-player-car-mode]"))return;const style=document.createElement("style");style.dataset.playerCarMode="gta-physical-touch-v3";style.textContent=`
body.player-driving #footHud,body.player-driving #soloLeft,body.player-driving #soloRight,body.player-driving #soloClearance,body.player-driving .solo-action{display:none!important;pointer-events:none!important}#vehicleHud{display:none;position:absolute;inset:0;z-index:10030;pointer-events:none;font-family:system-ui,-apple-system,sans-serif}body.player-driving #vehicleHud{display:block}.vehicle-pad{position:absolute;bottom:max(18px,var(--solo-safe-bottom,env(safe-area-inset-bottom)));width:min(25vw,142px);aspect-ratio:1;border-radius:50%;border:1px solid #a9e6ff66;background:#071522b8;box-shadow:inset 0 0 30px #2db7ff22,0 6px 20px #0007;pointer-events:auto;touch-action:none;-webkit-user-select:none;user-select:none}.vehicle-pad .knob{position:absolute;left:50%;top:50%;width:31%;aspect-ratio:1;border-radius:50%;transform:translate(-50%,-50%);background:#e9f8ffdd;border:1px solid #fff}.vehicle-pad span{position:absolute;left:50%;bottom:-15px;transform:translateX(-50%);color:#eaf8ff;font:900 8px/1 system-ui;letter-spacing:.1em}#vehicleSteer{left:max(14px,var(--solo-safe-left,env(safe-area-inset-left)))}#vehicleTouchPedals{position:absolute;right:max(14px,var(--solo-safe-right,env(safe-area-inset-right)));bottom:max(18px,var(--solo-safe-bottom,env(safe-area-inset-bottom)));display:grid;grid-template-columns:1fr;gap:8px;pointer-events:auto}#vehicleTouchPedals button{width:min(21vw,116px);height:58px;border:1px solid #ffffff45;border-radius:14px;background:#10283ee8;color:#fff;font:950 11px/1 system-ui;letter-spacing:.08em;touch-action:none;-webkit-user-select:none;user-select:none}#vehicleGas{border-color:#70e6a477!important;background:#174c35e8!important}#vehicleBrake{border-color:#ff9a8177!important;background:#52251fe8!important}#vehicleTouchPedals button.held{transform:scale(.96);filter:brightness(1.35);box-shadow:inset 0 0 20px #ffffff24}#vehicleReadout{position:absolute;left:50%;bottom:max(18px,var(--solo-safe-bottom,env(safe-area-inset-bottom)));transform:translateX(-50%);padding:7px 10px;border:1px solid #ffffff2c;border-radius:9px;background:#071522d8;color:#dff5ff;font:900 9px/1 system-ui;letter-spacing:.07em}#driveModeButton[data-near="1"]{border-color:#7de7b988!important;background:#154932e8!important}body.player-driving #driveModeButton{border-color:#ffcf6f88!important;background:#52350fe8!important}@media(max-height:340px){.vehicle-pad{width:min(21vw,116px);bottom:max(10px,var(--solo-safe-bottom,env(safe-area-inset-bottom)))}#vehicleTouchPedals{bottom:max(10px,var(--solo-safe-bottom,env(safe-area-inset-bottom)));gap:5px}#vehicleTouchPedals button{height:46px;width:min(18vw,96px);font-size:9px}#vehicleReadout{bottom:max(8px,var(--solo-safe-bottom,env(safe-area-inset-bottom)));font-size:8px}}
`;document.head.appendChild(style);}
function bindPad(el,kind){if(!el||el.dataset.bound)return;el.dataset.bound="1";let pointer=null;const knob=el.querySelector(".knob");const apply=e=>{if(!active)return;const r=el.getBoundingClientRect(),cx=r.left+r.width/2;if(kind==="steer"){touchSteer=clamp((Number(e.clientX)-cx)/(r.width*.38),-1,1);if(knob)knob.style.left=`${50+touchSteer*31}%`;const v=viewport();if(v)v.dataset.vehicleTouchSteer=touchSteer.toFixed(3);}e.preventDefault();e.stopPropagation();};const release=e=>{if(pointer===null||(e&&e.pointerId!==pointer))return;pointer=null;touchSteer=0;if(knob)knob.style.left="50%";const v=viewport();if(v)v.dataset.vehicleTouchSteer="0.000";e?.preventDefault?.();e?.stopPropagation?.();};el.addEventListener("pointerdown",e=>{if(!active)return;pointer=e.pointerId;apply(e);try{el.setPointerCapture?.(pointer);}catch{}},{passive:false});window.addEventListener("pointermove",e=>{if(e.pointerId===pointer)apply(e);},{capture:true,passive:false});window.addEventListener("pointerup",release,{capture:true,passive:false});window.addEventListener("pointercancel",release,{capture:true,passive:false});el.addEventListener("lostpointercapture",e=>{if(e.pointerId===pointer)release(e);});}
function bindPedalButton(el,which){if(!el||el.dataset.bound)return;el.dataset.bound="1";let pointer=null;const set=value=>{if(which==="gas")touchGas=value;else touchBrake=value;el.classList.toggle("held",value);const v=viewport();if(v)v.dataset.vehicleTouchThrottle=(touchGas?"1":touchBrake?"-1":"0");};const release=e=>{if(pointer===null||(e&&e.pointerId!==pointer))return;pointer=null;set(false);e?.preventDefault?.();e?.stopPropagation?.();};el.addEventListener("pointerdown",e=>{if(!active)return;pointer=e.pointerId;set(true);try{el.setPointerCapture?.(pointer);}catch{}e.preventDefault();e.stopPropagation();},{passive:false});window.addEventListener("pointerup",release,{capture:true,passive:false});window.addEventListener("pointercancel",release,{capture:true,passive:false});el.addEventListener("lostpointercapture",e=>{if(e.pointerId===pointer)release(e);});}
function mountUi(){const view=viewport(),top=document.getElementById("soloTopbarActions")||document.getElementById("soloTopbar");if(view&&!document.getElementById("vehicleHud")){const hud=document.createElement("div");hud.id="vehicleHud";hud.innerHTML='<div id="vehicleSteer" class="vehicle-pad"><div class="knob"></div><span>STEER</span></div><div id="vehicleTouchPedals"><button id="vehicleGas" type="button">GAS</button><button id="vehicleBrake" type="button">BRAKE / R</button></div><div id="vehicleReadout">CAR · 0 km/h · E / Y EXIT</div>';view.appendChild(hud);bindPad(hud.querySelector("#vehicleSteer"),"steer");bindPedalButton(hud.querySelector("#vehicleGas"),"gas");bindPedalButton(hud.querySelector("#vehicleBrake"),"brake");}if(top&&!document.getElementById("driveModeButton")){const b=document.createElement("button");b.id="driveModeButton";b.type="button";b.addEventListener("click",()=>active?exit():enter());top.insertBefore(b,document.getElementById("soloCamera")?.parentElement===top?document.getElementById("soloCamera"):null);}}
function renderUi(now){mountUi();const near=nearestVehicle(now),b=document.getElementById("driveModeButton"),readout=document.getElementById("vehicleReadout");if(b){b.dataset.near=!active&&near?"1":"0";b.disabled=playerDead()||(!active&&!near);b.textContent=active?"EXIT CAR":near?"CAR":"CAR —";b.setAttribute("aria-label",active?"Exit vehicle":near?`Enter nearby car ${near.distance.toFixed(1)} meters away`:"No drivable car nearby");}if(readout&&active)readout.textContent=`CAR · ${Math.round(Math.abs(commandSpeed)*3.6)} km/h · E / Y EXIT`;}
function installInput(){addEventListener("keydown",event=>{if(event.metaKey||event.ctrlKey||event.altKey)return;if(active&&["KeyW","KeyA","KeyS","KeyD","Space","KeyE","KeyV","ShiftLeft","ShiftRight"].includes(event.code)){event.preventDefault();event.stopImmediatePropagation();if(event.code==="KeyE"){exit();return;}if(event.code==="Space")handbrake=true;else keys.add(event.code);return;}if(!active&&event.code==="KeyE"&&walk()?.mode==="foot"){const near=nearestVehicle();if(near){event.preventDefault();event.stopImmediatePropagation();enter(near);}}},{capture:true});addEventListener("keyup",event=>{keys.delete(event.code);if(event.code==="Space")handbrake=false;},{capture:true});addEventListener(VEHICLE_CONTROL_SETTINGS_EVENT,event=>{settings=normalizeVehicleControlSettings(event.detail?.settings||loadVehicleControlSettings());});addEventListener("arondight:player-death",()=>exit({forced:true}));addEventListener("blur",()=>resetPads(),true);addEventListener("pagehide",()=>resetPads(),true);document.addEventListener("visibilitychange",()=>{if(document.hidden)resetPads();},true);}
function frame(now=performance.now()){const dt=clamp((now-lastFrame)/1000,0,.05);lastFrame=now;ensureCameraProvider();renderUi(now);pollGamepadInteract();updateDrive(now,dt);requestAnimationFrame(frame);}
export function installPlayerCarMode(){if(installed)return globalThis.__arondightVehicleDrive;installed=true;installStyle();installInput();mountUi();const api={enterNearest:()=>enter(nearestVehicle()),exit,get active(){return active;},get vehicleId(){return vehicle?.id||"";},get speedMps(){return Math.abs(commandSpeed);},get signedSpeedMps(){return commandSpeed;},get throttle(){return touchPedal+(keys.has("KeyW")?1:0)-(keys.has("KeyS")?1:0);},get heading(){return heading;},get physicsPose(){const pose=vehiclePose();return pose?{position:[...pose.position],rotation:[...(pose.rotation||[0,0,0,1])],velocity:[...(pose.velocity||[0,0,0])],angularVelocity:[...(pose.angularVelocity||[0,0,0])],yaw:Number.isFinite(pose.yaw)?pose.yaw:heading}:null;},get cameraAnchor(){const pose=vehiclePose();return pose?.position?{x:pose.position[0],y:pose.position[1],z:pose.position[2]+.78}:null;},nearestVehicle,vehicleAtScreenPoint,tryEnterAtScreenPoint};globalThis.__arondightVehicleDrive=api;const view=viewport();if(view){view.dataset.vehicleDriveMode="gta-physical-exclusive-authority-v2";view.dataset.vehicleDriveEnterRadiusM=String(ENTER_RADIUS_M);view.dataset.vehicleDriveOwner=DRIVE_OWNER;view.dataset.vehicleTouchControls="steer+gas+brake-multitouch-v1";view.dataset.vehicleEnterInteraction="screen-raycast+keyboard-e+gamepad-y-v1";}requestAnimationFrame(frame);return api;}
installPlayerCarMode();
