import {loadPhoneControlSettings} from "./drone_control_settings.mjs";
import {loadFirstPersonControlSettings,saveFirstPersonControlSettings} from "./first_person_control_settings.mjs";
import {DEFAULT_VEHICLE_CONTROL_SETTINGS,loadVehicleControlSettings,saveVehicleControlSettings} from "./vehicle_control_settings.mjs";

let installed=false;
const $=(root,selector)=>root.querySelector(selector);
function rangeRow(label,key,min,max,step){return `<div class="player-control-row"><label>${label}<output data-out="${key}"></output></label><input data-setting="${key}" type="range" min="${min}" max="${max}" step="${step}"></div>`;}
function toggleRow(label,key){return `<label class="player-control-toggle"><span>${label}</span><input data-setting="${key}" type="checkbox"></label>`;}
function profileSection(kind,title,body){return `<section class="player-control-section" data-profile-section="${kind}"><h4>${title}</h4>${body}</section>`;}
function installStyle(){if(document.querySelector("style[data-player-settings-sections]"))return;const style=document.createElement("style");style.dataset.playerSettingsSections="stacked-v1";style.textContent=`
.player-control-modes,.player-control-section{margin:12px 0;padding:11px;border:1px solid #ffffff22;border-radius:11px;background:#0c1926}.player-control-modes h4,.player-control-section h4{margin:0 0 9px;font:900 12px/1 system-ui;letter-spacing:.10em;color:#75e6b5}.player-mode-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.player-mode-grid button{min-height:36px;border:1px solid #ffffff38;border-radius:8px;background:#162437;color:#fff;font:850 10px/1 system-ui}.player-mode-grid button[data-active="1"]{border-color:#71e5b2;background:#18503d}.player-control-row{margin:10px 0}.player-control-row label{display:flex;justify-content:space-between;gap:10px;margin:0 0 5px;font:750 11px/1.2 system-ui}.player-control-row output{font:900 11px ui-monospace,SFMono-Regular,Menlo,monospace}.player-control-row input[type=range]{width:100%;accent-color:#6be4b0}.player-control-toggle{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:8px 0;border-top:1px solid #ffffff16;font:750 11px/1.2 system-ui}.player-control-toggle input{width:20px;height:20px;accent-color:#6be4b0}.player-control-note{margin:6px 0 0!important;color:#8fa5bd!important;font-size:10px!important}.player-control-section[data-profile-section="vehicle"] h4{color:#ffd37b}.player-control-section[data-profile-section="first-person"] h4{color:#8bdcff}.player-control-hardware{margin-bottom:16px}
`;document.head.appendChild(style);}
function hideLegacy(dialog){const hide=node=>{if(node)node.style.display="none";};hide($(dialog,".phone-settings-profile"));hide($(dialog,"[data-control-description]"));for(const input of dialog.querySelectorAll("[data-slider]"))hide(input.closest(".phone-settings-row"));for(const input of dialog.querySelectorAll("[data-invert-left-horizontal],[data-invert-right-horizontal],[data-invert-right-vertical],[data-lock-left-horizontal],[data-lock-horizontal]"))hide(input.closest(".phone-settings-toggle"));const xbox=$(dialog,"[data-xbox-controller]");if(xbox){hide(xbox.closest(".phone-settings-toggle"));const note=xbox.closest(".phone-settings-toggle")?.nextElementSibling;if(note?.classList.contains("phone-settings-note"))hide(note);}dialog.querySelector("h3")&&(dialog.querySelector("h3").textContent="SETTINGS");}
function relay(dialog,profile,selector,value,type="input"){
  const profileSelect=$(dialog,"[data-control-profile]");if(profileSelect){profileSelect.value=profile;profileSelect.dispatchEvent(new Event("change",{bubbles:true}));}
  const input=$(dialog,selector);if(!input)return false;if(input.type==="checkbox")input.checked=Boolean(value);else input.value=String(value);input.dispatchEvent(new Event(type,{bubbles:true}));return true;
}
function render(section,values,format={}){for(const input of section.querySelectorAll("[data-setting]")){const key=input.dataset.setting,value=values[key];if(input.type==="checkbox")input.checked=Boolean(value);else input.value=String(value??input.value);const out=section.querySelector(`[data-out="${key}"]`);if(out)out.value=format[key]?format[key](value):String(value??"");}}
function wireMirrors(dialog,section,profile,map){for(const input of section.querySelectorAll("[data-setting]")){const key=input.dataset.setting,selector=map[key];if(!selector)continue;input.addEventListener(input.type==="checkbox"?"change":"input",()=>relay(dialog,profile,selector,input.type==="checkbox"?input.checked:input.value,input.type==="checkbox"?"change":"input"));}}
function mount(dialog){if(dialog.dataset.stackedControls==="1")return;dialog.dataset.stackedControls="1";hideLegacy(dialog);const anchor=dialog.querySelector(".phone-settings-titlebar")?.nextSibling;
  const modes=document.createElement("section");modes.className="player-control-modes";modes.innerHTML='<h4>CONTROL MODES</h4><div class="player-mode-grid"><button type="button" data-mode="drone">DRONE</button><button type="button" data-mode="foot">FIRST PERSON</button><button type="button" data-mode="vehicle">CAR</button></div><p class="player-control-note">Mode selection is separate from the independent control profiles below.</p>';dialog.insertBefore(modes,anchor);
  const controls=document.createElement("div");controls.dataset.stackedControlProfiles="1";controls.innerHTML=
    profileSection("drone","DRONE CONTROLS",rangeRow("LEFT STICK FINENESS","leftFineness",1,10,1)+rangeRow("RIGHT STICK FINENESS","rightFineness",1,10,1)+rangeRow("MAX HORIZONTAL SPEED · km/h","maxHorizontalSpeedKmh",10,120,1)+rangeRow("DEFAULT HOVER · m","defaultHoverAgl",.5,50,.1)+toggleRow("INVERT LEFT HORIZONTAL","invertLeftHorizontal")+toggleRow("INVERT RIGHT HORIZONTAL","invertRightHorizontal")+toggleRow("INVERT RIGHT VERTICAL","invertRightVertical")+toggleRow("LOCK LEFT HORIZONTAL","lockLeftHorizontal")+toggleRow("LOCK RIGHT VERTICAL","lockRightHorizontal"))+
    profileSection("first-person","FIRST PERSON CONTROLS",rangeRow("MOVE STICK FINENESS","moveFineness",1,10,1)+rangeRow("LOOK STICK FINENESS","lookFineness",1,10,1)+rangeRow("HORIZONTAL LOOK · %","horizontalLookSensitivityPercent",50,150,1)+rangeRow("VERTICAL LOOK · %","verticalLookSensitivityPercent",50,150,1)+rangeRow("XBOX LOOK DEADZONE · %","lookDeadzonePercent",2,20,1)+rangeRow("AIM ASSIST · %","aimAssistStrengthPercent",0,100,1)+toggleRow("INVERT MOVE HORIZONTAL","invertMoveHorizontal")+toggleRow("INVERT LOOK HORIZONTAL","invertLookHorizontal")+toggleRow("INVERT LOOK VERTICAL","invertLookVertical")+toggleRow("LOCK MOVE HORIZONTAL","lockMoveHorizontal")+toggleRow("LOCK LOOK VERTICAL","lockLookVertical"))+
    profileSection("vehicle","VEHICLE CONTROLS",rangeRow("STEERING SENSITIVITY · %","steeringSensitivityPercent",55,150,1)+rangeRow("THROTTLE SENSITIVITY · %","throttleSensitivityPercent",55,150,1)+rangeRow("MAX SPEED · km/h","maxSpeedKmh",45,180,1)+rangeRow("REVERSE SPEED · km/h","reverseSpeedKmh",15,55,1)+rangeRow("CHASE CAMERA DISTANCE · m","cameraDistanceM",3.5,8,.1)+rangeRow("CHASE CAMERA HEIGHT · m","cameraHeightM",1.35,3.6,.05));dialog.insertBefore(controls,modes.nextSibling);
  const hardware=document.createElement("section");hardware.className="player-control-section player-control-hardware";hardware.innerHTML='<h4>INPUT HARDWARE</h4>'+toggleRow("XBOX CONTROLLER","xboxControllerEnabled")+'<p class="player-control-note">Touch remains active when Xbox is off. Each mode keeps its own curve and sensitivity.</p>';dialog.insertBefore(hardware,controls.nextSibling);
  const drone=controls.querySelector('[data-profile-section="drone"]'),fps=controls.querySelector('[data-profile-section="first-person"]'),car=controls.querySelector('[data-profile-section="vehicle"]');
  wireMirrors(dialog,drone,"drone",{leftFineness:'[data-slider="left"]',rightFineness:'[data-slider="right"]',maxHorizontalSpeedKmh:'[data-slider="speed"]',defaultHoverAgl:'[data-slider="hover"]',invertLeftHorizontal:'[data-invert-left-horizontal]',invertRightHorizontal:'[data-invert-right-horizontal]',invertRightVertical:'[data-invert-right-vertical]',lockLeftHorizontal:'[data-lock-left-horizontal]',lockRightHorizontal:'[data-lock-horizontal]'});
  wireMirrors(dialog,fps,"first-person",{moveFineness:'[data-slider="left"]',lookFineness:'[data-slider="right"]',horizontalLookSensitivityPercent:'[data-slider="look-horizontal"]',verticalLookSensitivityPercent:'[data-slider="look-vertical"]',lookDeadzonePercent:'[data-slider="look-deadzone"]',aimAssistStrengthPercent:'[data-slider="aim-assist"]',invertMoveHorizontal:'[data-invert-left-horizontal]',invertLookHorizontal:'[data-invert-right-horizontal]',invertLookVertical:'[data-invert-right-vertical]',lockMoveHorizontal:'[data-lock-left-horizontal]',lockLookVertical:'[data-lock-horizontal]'});
  for(const input of car.querySelectorAll("[data-setting]"))input.addEventListener("input",()=>saveVehicleControlSettings({...loadVehicleControlSettings(),[input.dataset.setting]:Number(input.value)}));
  const xbox=hardware.querySelector('[data-setting="xboxControllerEnabled"]');xbox.addEventListener("change",()=>{const legacy=$(dialog,"[data-xbox-controller]");if(legacy){legacy.checked=xbox.checked;legacy.dispatchEvent(new Event("change",{bubbles:true}));}});
  const refresh=()=>{const d=loadPhoneControlSettings(),f=loadFirstPersonControlSettings(),v=loadVehicleControlSettings();render(drone,d,{leftFineness:x=>`${x}/10`,rightFineness:x=>`${x}/10`,maxHorizontalSpeedKmh:x=>`${Math.round(x)} km/h`,defaultHoverAgl:x=>`${Number(x).toFixed(1)} m`});render(fps,f,{moveFineness:x=>`${x}/10`,lookFineness:x=>`${x}/10`,horizontalLookSensitivityPercent:x=>`${x}%`,verticalLookSensitivityPercent:x=>`${x}%`,lookDeadzonePercent:x=>`${x}%`,aimAssistStrengthPercent:x=>`${x}%`});render(car,v,{steeringSensitivityPercent:x=>`${x}%`,throttleSensitivityPercent:x=>`${x}%`,maxSpeedKmh:x=>`${x} km/h`,reverseSpeedKmh:x=>`${x} km/h`,cameraDistanceM:x=>`${Number(x).toFixed(1)} m`,cameraHeightM:x=>`${Number(x).toFixed(2)} m`});xbox.checked=d.xboxControllerEnabled!==false;const current=globalThis.__arondightVehicleDrive?.active?"vehicle":globalThis.__arondightWalkMode?.mode||"drone";for(const b of modes.querySelectorAll("[data-mode]"))b.dataset.active=b.dataset.mode===current?"1":"0";};
  for(const b of modes.querySelectorAll("[data-mode]"))b.addEventListener("click",()=>{const mode=b.dataset.mode,drive=globalThis.__arondightVehicleDrive,w=globalThis.__arondightWalkMode;if(mode==="vehicle"){if(w?.mode!=="foot")w?.setMode?.("foot",{reason:"settings-mode"});requestAnimationFrame(()=>drive?.enterNearest?.());}else{if(drive?.active)drive.exit?.();w?.setMode?.(mode,{reason:"settings-mode"});}refresh();});
  dialog.addEventListener("close",refresh);dialog.addEventListener("toggle",refresh);dialog.querySelector("[data-reset]")?.addEventListener("click",()=>{saveVehicleControlSettings(DEFAULT_VEHICLE_CONTROL_SETTINGS);setTimeout(refresh,0);});setInterval(()=>{if(dialog.open)refresh();},500);refresh();
}
function scan(){for(const dialog of document.querySelectorAll("dialog.phone-settings-dialog"))mount(dialog);}
export function installPlayerSettingsSections(){if(installed)return;installed=true;installStyle();scan();new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true});}
installPlayerSettingsSections();
