import * as THREE from "three";
import {HybridMotorSound} from "./motor_sound.mjs";
import {AUDIO_SETTINGS_EVENT,loadAudioSettings} from "./audio_settings.mjs";
import {VS_PEER_EVENT,VS_POSE_EVENT,VS_FX_EVENT} from "./lan_vs.mjs";

const HUMAN_RADIUS=.28;
const EYE_Z=1.68;
const GRID_M=12;
const VEHICLE_SCAN_MS=420;
const PEER_SCAN_MS=520;
const GRID_REFRESH_MS=1600;
const POSE_TX_MS=66;
const STALE_MS=3500;
const PLAYER_FX_KIND="pistol";
const WORLD_LIFE_FX_KIND="world-life-death-v1";
const EARTH_RADIUS_M=6378137;
const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,Number(v)||0));
const tmp=new THREE.Vector3(),tmp2=new THREE.Vector3(),forwardAxis=new THREE.Vector3(0,1,0);

let installed=false,lastMode=null,lastWalkShots=0,lastFrame=performance.now(),lastPoseTx=-Infinity,lastStepAt=-Infinity;
let humanAnchor={x:0,y:0,z:0,yaw:0},anchorReady=false,lastHumanSample=null,humanVelocity={x:0,y:0,z:0};
let pendingTeleport=null,airframeRoot=null,airframeScene=null,lastAirframeScan=-Infinity;
let audioCtx=null,noiseBuffer=null,fxMaster=null,audioOverride=false;
let collisionPrisms=null,collisionStamp="",lastGridBuild=-Infinity,lastVehicleScan=-Infinity,lastPeerScan=-Infinity;
let applyingRemoteWorldLife=false,hitRouting=false,lastFxSession=null,patchedBridge=null;
let localAvatar=null,avatarScene=null,muzzleScene=null,muzzleGeo=null,muzzleConeGeo=null,blastScene=null,blastGeo=null,blastRingGeo=null;
let perfStart=performance.now(),perfFrames=0;
const buildingGrid=new Map(),vehicleNodes=[],peerDroneNodes=new Map(),remoteAvatars=new Map(),motorInstances=new Set(),muzzlePool=[],blastPool=[];

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function walk(){return globalThis.__arondightWalkMode||null;}
function currentMode(){return walk()?.mode==="foot"?"foot":"drone";}
function playerSession(){return bridge()?.vsSession||null;}
function activeSession(){const s=playerSession();return s?.active||s||null;}
function selfId(){try{return String(playerSession()?.getSelfId?.()||activeSession()?.getSelfId?.()||"");}catch{return"";}}
function walkYaw(){return Number(viewport()?.dataset.walkYaw)||0;}
function walkPitch(){return Number(viewport()?.dataset.walkPitch)||0;}
function radToDeg(v){return(Number(v)||0)*180/Math.PI;}
function yawQuaternion(yaw){return[0,0,Math.sin((Number(yaw)||0)/2),Math.cos((Number(yaw)||0)/2)];}
function localOffset(){const b=bridge(),o=b?.__vsRespawnLocalOffset;return !b?.active&&Array.isArray(o)&&o.length===2?[Number(o[0])||0,Number(o[1])||0]:[0,0];}
function localToCanonical(position){const o=localOffset();return[(Number(position?.[0])||0)+o[0],(Number(position?.[1])||0)+o[1],Number(position?.[2])||0];}
function canonicalToLocal(position){const o=localOffset();return[(Number(position?.[0])||0)-o[0],(Number(position?.[1])||0)-o[1],Number(position?.[2])||0];}
function metersToLngLat(originLon,originLat,east,north){const latRad=originLat*Math.PI/180;return[originLon+east/(EARTH_RADIUS_M*Math.max(.01,Math.cos(latRad)))*180/Math.PI,originLat+north/EARTH_RADIUS_M*180/Math.PI];}
function lngLatToMeters(originLon,originLat,lon,lat){return[(lon-originLon)*Math.PI/180*EARTH_RADIUS_M*Math.max(.01,Math.cos(originLat*Math.PI/180)),(lat-originLat)*Math.PI/180*EARTH_RADIUS_M];}
function pointInside(x,y,points){let inside=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j],cross=(a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/((b[1]-a[1])||1e-12)+a[0];if(cross)inside=!inside;}return inside;}
function snapshotHuman(){const w=walk();if(currentMode()==="foot"&&w?.position)return{x:w.position.x,y:w.position.y,z:0,yaw:walkYaw()};return{...humanAnchor};}

function airframe(now=performance.now()){
  const b=bridge(),scene=b?.threeScene;if(!scene)return null;
  if(scene!==airframeScene){airframeScene=scene;airframeRoot=null;lastAirframeScan=-Infinity;}
  const direct=b.airframeFor?.(scene)||b.airframe||null;if(direct){airframeRoot=direct;return direct;}
  if(airframeRoot?.parent)return airframeRoot;
  if(now-lastAirframeScan<1000)return null;lastAirframeScan=now;
  scene.traverse?.(node=>{if(!airframeRoot&&node?.userData?.arondightAirframe)airframeRoot=node;});return airframeRoot;
}
function airframePose(){const root=airframe();if(!root)return null;root.getWorldPosition(tmp);const q=root.getWorldQuaternion(new THREE.Quaternion()),e=new THREE.Euler().setFromQuaternion(q,"XYZ");return{x:tmp.x,y:tmp.y,z:Math.max(0,tmp.z),yaw:e.z};}
function setAirframeVisible(visible){const root=airframe();if(root)root.visible=Boolean(visible);}

function exposeVehicleModel(model){if(!model||typeof model.reset!=="function"||!model.p)return;const current=globalThis.__arondightVehicleRuntime;if(current?.model===model)return;globalThis.__arondightVehicleRuntime={model,teleportDrone({x=0,y=0,z=.08,yawDeg=0}={}){model.reset(model.p,{x:Number(x)||0,y:Number(y)||0,z:Number.isFinite(Number(z))?Number(z):.08,roll_deg:0,pitch_deg:0,yaw_deg:Number(yawDeg)||0});return model.state?.()||null;},getState(){return model.state?.()||null;}};const v=viewport();if(v)v.dataset.droneVehicleRuntime="box3d-reset-v2";}
function hardMuteMotor(muted){for(const instance of motorInstances){try{if(instance.master&&instance.ctx){instance.master.gain.cancelScheduledValues?.(instance.ctx.currentTime);instance.master.gain.setTargetAtTime(muted?0:.0001,instance.ctx.currentTime,.012);}}catch{}}const v=viewport();if(v)v.dataset.droneAudioHardMuted=muted?"1":"0";}
function patchMotorRuntime(){const proto=HybridMotorSound?.prototype;if(!proto||proto.__playerVehicleRuntimeV2Patched)return;const baseUpdate=proto.update;proto.update=function(model,cameraPosition){motorInstances.add(this);exposeVehicleModel(model);if(currentMode()==="foot"){if(this.master&&this.ctx)this.master.gain.setTargetAtTime(0,this.ctx.currentTime,.010);if(this.viewport){this.viewport.dataset.motorAudioGain="0";this.viewport.dataset.motorAudioHardMuted="1";}return;}return baseUpdate.call(this,model,cameraPosition);};proto.__playerVehicleRuntimeV2Patched=true;}
function teleportDrone(anchor,{hidden=false,launchOffset=false}={}){const runtime=globalThis.__arondightVehicleRuntime;if(!runtime?.teleportDrone){pendingTeleport={anchor:{...anchor},hidden,launchOffset};return false;}const offset=launchOffset?.72:0,x=anchor.x+Math.sin(anchor.yaw)*offset,y=anchor.y+Math.cos(anchor.yaw)*offset;runtime.teleportDrone({x,y,z:.08,yawDeg:radToDeg(anchor.yaw)});pendingTeleport=null;setAirframeVisible(!hidden);const v=viewport();if(v){v.dataset.dronePhysicalX=x.toFixed(3);v.dataset.dronePhysicalY=y.toFixed(3);v.dataset.dronePhysicalReset="1";v.dataset.droneLaunchOffsetM=offset.toFixed(2);}return true;}
function killDrone(){try{document.getElementById("soloKill")?.click?.();}catch{}}
function dispatchAudio(settings){audioOverride=true;try{window.dispatchEvent(new CustomEvent(AUDIO_SETTINGS_EVENT,{detail:settings}));}finally{queueMicrotask(()=>{audioOverride=false;});}}
function suppressDroneAudio(){hardMuteMotor(true);const settings=loadAudioSettings();dispatchAudio({...settings,droneVolume:0});const v=viewport();if(v){v.dataset.droneAudioSuppressed="1";v.dataset.playerAudioProfile="human-hard-muted";}}
function restoreDroneAudio(){dispatchAudio(loadAudioSettings());hardMuteMotor(false);const v=viewport();if(v){v.dataset.droneAudioSuppressed="0";v.dataset.playerAudioProfile="drone-live";}}

function avatarPart(geometry,material,x,y,z){const mesh=new THREE.Mesh(geometry,material);mesh.position.set(x,y,z);mesh.castShadow=false;mesh.receiveShadow=false;mesh.userData.worldPopulationKind="vs-player";mesh.userData.worldPopulationClone=false;mesh.userData.flightFireIgnore=false;return mesh;}
function buildHumanAvatar(id,{local=false}={}){const scene=bridge()?.threeScene;if(!scene)return null;const cloth=new THREE.MeshStandardMaterial({color:local?0x314f6b:hashColor(id),roughness:.72,metalness:.04}),dark=new THREE.MeshStandardMaterial({color:0x20272d,roughness:.86}),skin=new THREE.MeshStandardMaterial({color:0xb98262,roughness:.86}),glass=new THREE.MeshStandardMaterial({color:0x101c26,roughness:.18,metalness:.32,emissive:0x0a5c80,emissiveIntensity:.34}),root=new THREE.Group();root.name=local?"LOCAL_HUMAN_VR":`VS_HUMAN_${id}`;root.userData.vsPlayerId=id;root.userData.vsHumanAvatar=true;root.userData.localHumanAvatar=local;const torso=avatarPart(new THREE.BoxGeometry(.42,.25,.66),cloth,0,0,1.08),head=avatarPart(new THREE.SphereGeometry(.19,10,7),skin,0,0,1.58),legL=avatarPart(new THREE.BoxGeometry(.145,.17,.72),dark,-.115,0,.48),legR=avatarPart(new THREE.BoxGeometry(.145,.17,.72),dark,.115,0,.48),armL=avatarPart(new THREE.BoxGeometry(.12,.14,.64),cloth,-.285,.015,1.09),armR=avatarPart(new THREE.BoxGeometry(.12,.14,.64),cloth,.285,.015,1.09),headset=avatarPart(new THREE.BoxGeometry(.37,.18,.17),glass,0,.14,1.61),strap=avatarPart(new THREE.BoxGeometry(.26,.24,.055),dark,0,-.02,1.63),pack=avatarPart(new THREE.BoxGeometry(.31,.14,.40),dark,0,-.17,1.04),controllerL=avatarPart(new THREE.BoxGeometry(.10,.07,.13),dark,-.20,.18,.92),controllerR=avatarPart(new THREE.BoxGeometry(.10,.07,.13),dark,.20,.18,.92);armL.rotation.x=.36;armR.rotation.x=.36;for(const part of[torso,head,legL,legR,armL,armR,headset,strap,pack,controllerL,controllerR]){part.userData.vsPlayerId=id;part.userData.worldPopulationId=`vs-human-${id}`;if(local)part.userData.flightFireIgnore=true;root.add(part);}let hitbox=null;if(!local){const hitMat=new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false});hitMat.colorWrite=false;hitbox=new THREE.Mesh(new THREE.BoxGeometry(.66,.56,1.82),hitMat);hitbox.position.z=.91;hitbox.userData.vsPlayerId=id;hitbox.userData.vsPeerHitProxy=true;hitbox.userData.worldPopulationKind="vs-player";hitbox.userData.worldPopulationId=`vs-human-${id}`;hitbox.userData.worldPopulationClone=false;root.add(hitbox);}root.visible=false;scene.add(root);return{id,root,torso,head,legL,legR,armL,armR,headset,strap,pack,controllerL,controllerR,hitbox,mode:"drone",target:new THREE.Vector3(),yaw:0,velocity:new THREE.Vector3(),lastPose:-Infinity,lastStep:-Infinity,phase:0,dead:false};}
function hashColor(id){let h=2166136261;for(const c of String(id||"")){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}const palette=[0x42b7e9,0xe46c4f,0x70b86a,0xe0b34e,0x9b78db,0x48b6a0];return palette[(h>>>0)%palette.length];}
function ensureLocalAvatar(){const scene=bridge()?.threeScene;if(!scene)return null;if(scene!==avatarScene){avatarScene=scene;localAvatar=null;for(const r of remoteAvatars.values())r.root.parent?.remove(r.root);remoteAvatars.clear();}if(!localAvatar)localAvatar=buildHumanAvatar(selfId()||"local",{local:true});return localAvatar;}
function renderLocalAvatar(){const a=ensureLocalAvatar(),v=viewport();if(!a)return;if(currentMode()==="drone"&&anchorReady){a.root.position.set(humanAnchor.x,humanAnchor.y,0);a.root.rotation.set(0,0,humanAnchor.yaw);a.root.visible=true;a.headset.visible=a.strap.visible=a.controllerL.visible=a.controllerR.visible=true;a.pack.visible=false;if(v){v.dataset.localHumanAvatarVisible="1";v.dataset.localHumanVr="1";v.dataset.localHumanAvatar="mesh-v2";}}else{a.root.visible=false;if(v){v.dataset.localHumanAvatarVisible="0";v.dataset.localHumanVr="0";}}}

function enterFoot(previous){let anchor=anchorReady?{...humanAnchor}:airframePose();if(!anchor)anchor={x:0,y:0,z:0,yaw:0};humanAnchor={x:anchor.x,y:anchor.y,z:0,yaw:anchor.yaw};anchorReady=true;suppressDroneAudio();killDrone();teleportDrone(humanAnchor,{hidden:true});setAirframeVisible(false);walk()?.setPose?.({x:humanAnchor.x,y:humanAnchor.y,yaw:humanAnchor.yaw,pitch:0});lastHumanSample=null;const v=viewport();if(v){v.dataset.playerVehicleMode="human";v.dataset.droneVehicleState="stowed";v.dataset.humanVrHeadset="0";v.dataset.droneLaunchFromHuman=previous==="drone"?"return":"initial";}}
function enterDrone(previous){if(previous==="foot"){const p=walk()?.position;humanAnchor={x:Number(p?.x)||0,y:Number(p?.y)||0,z:0,yaw:walkYaw()};anchorReady=true;teleportDrone(humanAnchor,{hidden:false,launchOffset:true});}else if(!anchorReady){const pose=airframePose();if(pose){humanAnchor={x:pose.x-Math.sin(pose.yaw)*.72,y:pose.y-Math.cos(pose.yaw)*.72,z:0,yaw:pose.yaw};anchorReady=true;}}setAirframeVisible(true);restoreDroneAudio();lastHumanSample=null;const v=viewport();if(v){v.dataset.playerVehicleMode="drone";v.dataset.droneVehicleState="deployed";v.dataset.humanVrHeadset="1";v.dataset.droneLaunchFromHuman=previous==="foot"?"1":"0";if(anchorReady)v.dataset.humanAnchor=`${humanAnchor.x.toFixed(3)},${humanAnchor.y.toFixed(3)},0.000`;}}
function syncMode(){const mode=currentMode();if(mode===lastMode)return;const previous=lastMode;lastMode=mode;if(mode==="foot")enterFoot(previous);else enterDrone(previous);const v=viewport();if(v){v.dataset.playerVehicleReplication="human+drone+audio+fx-v2";v.dataset.walkControlProfile="cod-mobile-direct-v5";v.dataset.walkCollisionProfile="spatial-grid-cached-v2";}}

function gridKey(gx,gy){return`${gx}:${gy}`;}
function refreshBuildingGrid(now=performance.now()){
  const b=bridge(),snapshot=b?.buildingCollisionSnapshot,prisms=snapshot?.prisms||[],origin=`${Number(b?.originLon)||0}:${Number(b?.originLat)||0}`,stamp=`${origin}:${prisms.length}:${snapshot?.revision??snapshot?.version??""}`;
  if(prisms===collisionPrisms&&stamp===collisionStamp&&now-lastGridBuild<GRID_REFRESH_MS)return;
  collisionPrisms=prisms;collisionStamp=stamp;lastGridBuild=now;buildingGrid.clear();
  for(const prism of prisms){if(Number(prism?.top)<=.25||!Array.isArray(prism.points)||prism.points.length<3)continue;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const p of prism.points){const x=Number(p?.[0]),y=Number(p?.[1]);if(!Number.isFinite(x)||!Number.isFinite(y))continue;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);}if(!Number.isFinite(minX))continue;const entry={points:prism.points,minX,minY,maxX,maxY},gx0=Math.floor(minX/GRID_M),gx1=Math.floor(maxX/GRID_M),gy0=Math.floor(minY/GRID_M),gy1=Math.floor(maxY/GRID_M);for(let gx=gx0;gx<=gx1;gx++)for(let gy=gy0;gy<=gy1;gy++){const key=gridKey(gx,gy),bucket=buildingGrid.get(key);if(bucket)bucket.push(entry);else buildingGrid.set(key,[entry]);}}
  const v=viewport();if(v){v.dataset.walkCollisionCells=String(buildingGrid.size);v.dataset.walkCollisionPrisms=String(prisms.length);}
}
function buildingBlockedPoint(x,y){refreshBuildingGrid();const bucket=buildingGrid.get(gridKey(Math.floor(x/GRID_M),Math.floor(y/GRID_M)))||[];for(const p of bucket)if(x>=p.minX&&x<=p.maxX&&y>=p.minY&&y<=p.maxY&&pointInside(x,y,p.points))return true;return false;}
function buildingBlocked(x,y){const r=HUMAN_RADIUS,s=.707*r;for(const [dx,dy] of[[0,0],[r,0],[-r,0],[0,r],[0,-r],[s,s],[s,-s],[-s,s],[-s,-s]])if(buildingBlockedPoint(x+dx,y+dy))return true;return false;}
function refreshVehicleNodes(now=performance.now()){if(now-lastVehicleScan<VEHICLE_SCAN_MS)return;lastVehicleScan=now;vehicleNodes.length=0;const scene=bridge()?.threeScene;if(!scene)return;scene.traverse?.(node=>{if(node?.visible===false)return;const life=String(node?.userData?.worldLifeKind||""),kind=String(node?.userData?.worldPopulationKind||"");if((life==="car"||life==="bus")&&node.children?.length)vehicleNodes.push({node,radius:life==="bus"?2.55:1.30});else if(kind==="car"&&node.children?.length&&!node.userData?.worldLifeId)vehicleNodes.push({node,radius:1.35});});const v=viewport();if(v)v.dataset.walkCollisionVehicles=String(vehicleNodes.length);}
function vehicleBlocked(x,y){refreshVehicleNodes();for(const item of vehicleNodes){if(item.node.visible===false)continue;item.node.getWorldPosition(tmp);if(Math.hypot(tmp.x-x,tmp.y-y)<item.radius+HUMAN_RADIUS)return true;}for(const r of remoteAvatars.values()){if(!r.root.visible)continue;if(Math.hypot(r.root.position.x-x,r.root.position.y-y)<.58)return true;}return false;}
function canOccupyWalkPoint(x,y){return!buildingBlocked(x,y)&&!vehicleBlocked(x,y);}
function resolveWalkMove(from,to){const fromInside=buildingBlocked(from.x,from.y);if(fromInside){const result={x:to.x,y:to.y};const v=viewport();if(v)v.dataset.walkCollisionEscape="1";return result;}if(canOccupyWalkPoint(to.x,to.y))return{x:to.x,y:to.y};const xOnly={x:to.x,y:from.y},yOnly={x:from.x,y:to.y},xFree=canOccupyWalkPoint(xOnly.x,xOnly.y),yFree=canOccupyWalkPoint(yOnly.x,yOnly.y);let result={x:from.x,y:from.y};if(xFree&&yFree)result=Math.abs(to.x-from.x)>=Math.abs(to.y-from.y)?xOnly:yOnly;else if(xFree)result=xOnly;else if(yFree)result=yOnly;const v=viewport();if(v)v.dataset.walkCollisionSlides=String((Number(v.dataset.walkCollisionSlides)||0)+1);return result;}

function ensureAudio(unlock=false){const Ctx=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Ctx)return null;if(!audioCtx){try{audioCtx=new Ctx({latencyHint:"interactive"});}catch{audioCtx=new Ctx();}fxMaster=audioCtx.createDynamicsCompressor();fxMaster.threshold.value=-12;fxMaster.knee.value=18;fxMaster.ratio.value=3.5;fxMaster.attack.value=.002;fxMaster.release.value=.16;fxMaster.connect(audioCtx.destination);noiseBuffer=audioCtx.createBuffer(1,Math.max(1,Math.floor(audioCtx.sampleRate*.42)),audioCtx.sampleRate);const data=noiseBuffer.getChannelData(0);let seed=0x45a391;for(let i=0;i<data.length;i++){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;data[i]=((seed>>>0)/2147483648)-1;}}if(unlock&&audioCtx.state==="suspended")audioCtx.resume().catch(()=>{});return audioCtx;}
function listenerPosition(){if(currentMode()==="foot"&&walk()?.position)return walk().position;return bridge()?.threeCamera?.position||null;}
function spatialGain(position){if(!position)return 1;const listener=listenerPosition();if(!listener)return 1;const p=Array.isArray(position)?position:[position.x,position.y,position.z],d=Math.hypot((p[0]||0)-listener.x,(p[1]||0)-listener.y,(p[2]||0)-listener.z);return 1/(1+.10*d+.018*d*d);}
function settingsGain(kind){const s=loadAudioSettings();if(!s.soundEnabled)return 0;return clamp((kind==="shots"?s.shotsVolume:s.fxVolume)/100,0,1);}
function synthPistol(volume){if(!audioCtx||audioCtx.state!=="running"||!fxMaster||volume<=0)return;const t=audioCtx.currentTime,noise=audioCtx.createBufferSource(),hp=audioCtx.createBiquadFilter(),ng=audioCtx.createGain();noise.buffer=noiseBuffer;hp.type="highpass";hp.frequency.setValueAtTime(1250,t);hp.frequency.exponentialRampToValueAtTime(520,t+.065);ng.gain.setValueAtTime(.23*volume,t);ng.gain.exponentialRampToValueAtTime(.0001,t+.080);noise.connect(hp).connect(ng).connect(fxMaster);noise.start(t);noise.stop(t+.09);const body=audioCtx.createOscillator(),bg=audioCtx.createGain();body.type="triangle";body.frequency.setValueAtTime(205,t);body.frequency.exponentialRampToValueAtTime(64,t+.075);bg.gain.setValueAtTime(.15*volume,t);bg.gain.exponentialRampToValueAtTime(.0001,t+.095);body.connect(bg).connect(fxMaster);body.start(t);body.stop(t+.10);}
function playPistol(position=null,remote=false){const ctx=ensureAudio(true),volume=settingsGain("shots")*spatialGain(position)*(remote?.68:1),v=viewport();if(v)v.dataset.walkShotSoundEvents=String((Number(v.dataset.walkShotSoundEvents)||0)+1);if(!ctx||volume<=0)return false;if(ctx.state==="running")synthPistol(volume);else ctx.resume().then(()=>synthPistol(volume)).catch(()=>{});return true;}
function playStep(position=null,remote=false){const ctx=ensureAudio(false),volume=settingsGain("fx")*spatialGain(position)*(remote?.18:.12);if(!ctx||ctx.state!=="running"||!fxMaster||volume<=0)return;const t=ctx.currentTime,n=ctx.createBufferSource(),lp=ctx.createBiquadFilter(),g=ctx.createGain();n.buffer=noiseBuffer;lp.type="lowpass";lp.frequency.value=360;g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+.05);n.connect(lp).connect(g).connect(fxMaster);n.start(t);n.stop(t+.06);}
function playExplosion(position=null,small=false){const ctx=ensureAudio(false),volume=settingsGain("fx")*spatialGain(position)*(small?.36:1),v=viewport();if(v)v.dataset.playerExplosionSoundEvents=String((Number(v.dataset.playerExplosionSoundEvents)||0)+1);if(!ctx||ctx.state!=="running"||!fxMaster||volume<=0)return;const t=ctx.currentTime,n=ctx.createBufferSource(),lp=ctx.createBiquadFilter(),g=ctx.createGain();n.buffer=noiseBuffer;lp.type="lowpass";lp.frequency.setValueAtTime(small?900:680,t);lp.frequency.exponentialRampToValueAtTime(85,t+(small?.18:.5));g.gain.setValueAtTime((small?.11:.26)*volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+(small?.24:.56));n.connect(lp).connect(g).connect(fxMaster);n.start(t);n.stop(t+(small?.26:.58));const o=ctx.createOscillator(),og=ctx.createGain();o.type="sine";o.frequency.setValueAtTime(small?105:68,t);o.frequency.exponentialRampToValueAtTime(24,t+(small?.20:.52));og.gain.setValueAtTime((small?.08:.20)*volume,t);og.gain.exponentialRampToValueAtTime(.0001,t+(small?.26:.58));o.connect(og).connect(fxMaster);o.start(t);o.stop(t+(small?.28:.60));}

function fireDirection(){const yaw=walkYaw(),pitch=walkPitch(),cp=Math.cos(pitch);return[Math.sin(yaw)*cp,Math.cos(yaw)*cp,Math.sin(pitch)];}
function sendFootShot(){const s=playerSession(),w=walk(),p=w?.position;if(!s?.sendFx||!p)return;const from=localToCanonical([p.x,p.y,EYE_Z-.08]),dir=fireDirection(),id=`pistol-${Date.now().toString(36)}-${Math.floor(performance.now()).toString(36)}`,pid=selfId();s.sendFx({type:"shot",id,from,dir,speed:360,...(pid?{playerId:pid}:{}),kind:PLAYER_FX_KIND,t:Date.now()});const v=viewport();if(v)v.dataset.walkReplicatedShots=String((Number(v.dataset.walkReplicatedShots)||0)+1);}
function observeWalkShot(){const v=viewport(),shots=Number(v?.dataset.walkShots||0);if(shots>lastWalkShots&&currentMode()==="foot"){const p=walk()?.position;playPistol(p,false);sendFootShot();if(v)v.dataset.walkShotAudioVisualSync="muzzle+recoil+sound";}lastWalkShots=Math.max(lastWalkShots,shots);}
function updateHumanVelocity(now){const pose=snapshotHuman();if(!lastHumanSample){lastHumanSample={...pose,at:now};humanVelocity={x:0,y:0,z:0};return;}const dt=(now-lastHumanSample.at)/1000;if(currentMode()==="foot"&&dt>.001&&dt<.5)humanVelocity={x:(pose.x-lastHumanSample.x)/dt,y:(pose.y-lastHumanSample.y)/dt,z:0};else humanVelocity={x:0,y:0,z:0};lastHumanSample={...pose,at:now};if(currentMode()==="foot"){const speed=Math.hypot(humanVelocity.x,humanVelocity.y),period=clamp(.50-speed*.025,.27,.48);if(speed>.55&&now-lastStepAt>period*1000){lastStepAt=now;playStep([pose.x,pose.y,0],false);const v=viewport();if(v)v.dataset.walkFootsteps=String((Number(v.dataset.walkFootsteps)||0)+1);}}}

function augmentVsPose(force=false,now=performance.now()){if(!force&&now-lastPoseTx<POSE_TX_MS)return;const b=bridge(),s=b?.vsSession,pending=s?.pendingPose;if(!s?.setPose||!pending)return;lastPoseTx=now;const human=snapshotHuman(),canonical=localToCanonical([human.x,human.y,0]),mode=currentMode(),velocity=mode==="foot"?[humanVelocity.x,humanVelocity.y,0]:[0,0,0],next={...pending,pm:mode,av:canonical,ay:human.yaw,avv:velocity,vr:mode==="drone"?1:0};if(b.active&&Number.isFinite(b.originLon)&&Number.isFinite(b.originLat))next.ag=metersToLngLat(b.originLon,b.originLat,human.x,human.y);if(mode==="foot"){next.p=localToCanonical([human.x,human.y,.04]);next.q=yawQuaternion(human.yaw);next.v=velocity;if(next.ag)next.g=[...next.ag];}s.setPose(next);const v=viewport();if(v)v.dataset.playerPoseReplicated=mode;}
function patchPoseBridge(){const b=bridge();if(!b||b===patchedBridge||typeof b.updateVsPose!=="function")return;patchedBridge=b;if(b.__playerVehiclePoseV2Patched)return;const base=b.updateVsPose.bind(b);b.updateVsPose=()=>{const result=base();augmentVsPose(true);return result;};b.__playerVehiclePoseV2Patched=true;}
function poseAvatarLocal(pose){const b=bridge();if(Array.isArray(pose?.ag)&&pose.ag.length===2&&b?.active&&Number.isFinite(b.originLon)&&Number.isFinite(b.originLat)){const [x,y]=lngLatToMeters(b.originLon,b.originLat,Number(pose.ag[0]),Number(pose.ag[1]));return[x,y,0];}return canonicalToLocal(pose?.av||pose?.p||[0,0,0]);}
function createRemoteAvatar(id){const r=buildHumanAvatar(id,{local:false});if(r)remoteAvatars.set(id,r);return r;}
function onPose(event){const peerId=String(event?.detail?.peerId||""),pose=event?.detail?.pose;if(!peerId||!pose||!Array.isArray(pose.av)||!(pose.pm==="foot"||pose.pm==="drone"))return;const r=remoteAvatars.get(peerId)||createRemoteAvatar(peerId);if(!r)return;const p=poseAvatarLocal(pose);r.target.set(Number(p[0])||0,Number(p[1])||0,0);r.yaw=Number(pose.ay)||0;r.mode=pose.pm;r.velocity.set(Number(pose.avv?.[0])||0,Number(pose.avv?.[1])||0,0);r.lastPose=performance.now();r.headset.visible=r.strap.visible=r.controllerL.visible=r.controllerR.visible=pose.pm==="drone";r.pack.visible=pose.pm==="foot";const v=viewport();if(v)v.dataset.vsHumanPoseEvents=String((Number(v.dataset.vsHumanPoseEvents)||0)+1);}
function onPeer(event){const id=String(event?.detail?.peerId||"");if(event?.detail?.type!=="leave"||!id)return;const r=remoteAvatars.get(id);if(r){r.root.parent?.remove(r.root);remoteAvatars.delete(id);}peerDroneNodes.delete(id);}
function refreshPeerDrones(now){if(now-lastPeerScan<PEER_SCAN_MS)return;lastPeerScan=now;peerDroneNodes.clear();const scene=bridge()?.threeScene;if(!scene)return;scene.traverse?.(node=>{const id=String(node?.userData?.vsPlayerId||"");if(!id||node.userData?.vsHumanAvatar)return;if(node.userData?.vsMultiplayerPeer||node.userData?.vsLegacyPrimary||node.userData?.vsPeer){const list=peerDroneNodes.get(id)||[];list.push(node);peerDroneNodes.set(id,list);}});}
function renderRemoteAvatars(now,dt){refreshPeerDrones(now);let visible=0,vr=0;for(const r of remoteAvatars.values()){const stale=now-r.lastPose>STALE_MS;if(stale){r.root.visible=false;continue;}visible++;r.root.visible=true;const alpha=1-Math.exp(-dt*14);r.root.position.lerp(r.target,alpha);let d=r.yaw-r.root.rotation.z;d=((d+Math.PI)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)-Math.PI;r.root.rotation.z+=d*alpha;const speed=Math.hypot(r.velocity.x,r.velocity.y),walking=r.mode==="foot"&&speed>.22;r.phase+=dt*(walking?clamp(5+speed*1.1,5,11):2);const swing=walking?Math.sin(r.phase)*clamp(.26+speed*.04,.26,.58):0;r.legL.rotation.x=swing;r.legR.rotation.x=-swing;r.armL.rotation.x=walking?-swing*.65:.36;r.armR.rotation.x=walking?swing*.65:.36;const headset=r.mode==="drone";r.headset.visible=r.strap.visible=r.controllerL.visible=r.controllerR.visible=headset;r.pack.visible=!headset;if(headset)vr++;for(const node of peerDroneNodes.get(r.id)||[])node.visible=headset;if(walking&&now-r.lastStep>clamp(500-speed*22,270,480)){r.lastStep=now;playStep(r.root.position,true);}}const v=viewport();if(v){v.dataset.vsHumanAvatars=String(remoteAvatars.size);v.dataset.vsHumanAvatarsVisible=String(visible);v.dataset.vsVrAvatars=String(vr);}}

function vsPlayerId(hit){for(let node=hit?.object;node;node=node.parent){const id=String(node.userData?.vsPlayerId||"");if(id)return id;}return"";}
function patchWorldHitRouting(){const b=bridge(),base=b?.registerWorldPopulationHit;if(!b||typeof base!=="function"||base.__playerVehicleHitRouterV2||!base.__worldLivelinessWrapper)return;const wrapper=hit=>{const id=vsPlayerId(hit);if(id&&!hitRouting&&typeof b.registerVsHit==="function"){hitRouting=true;try{return Boolean(b.registerVsHit(hit));}finally{hitRouting=false;}}return Boolean(base(hit));};wrapper.__playerVehicleHitRouterV2=true;wrapper.__worldLivelinessWrapper=true;wrapper.__gameplayPolishLiteWrapper=true;b.registerWorldPopulationHit=wrapper;const v=viewport();if(v)v.dataset.walkVsHitRouting="1";}
function patchFxSession(){const session=activeSession();if(!session||session===lastFxSession||typeof session.sendFx!=="function")return;lastFxSession=session;if(session.__playerVehicleFxV2Patched)return;session.__playerVehicleFxV2Patched=true;const base=session.sendFx.bind(session);session.sendFx=(packet,options)=>{if(packet?.type===WORLD_LIFE_FX_KIND){if(applyingRemoteWorldLife)return true;const pid=selfId(),next={...packet,type:"impact",kind:WORLD_LIFE_FX_KIND,objectKind:packet.kind,...(pid?{playerId:pid}:{})};return base(next,options);}return base(packet,options);};}
function findWorldLife(id){let found=null;bridge()?.threeScene?.traverse?.(node=>{if(found)return;const nodeId=String(node?.userData?.worldLifeId||node?.userData?.worldPopulationId||"");if(nodeId===String(id||""))found=node;});return found;}
function applyRemoteWorldLife(packet){const b=bridge(),object=findWorldLife(packet?.objectId);if(!b||!object||typeof b.registerWorldPopulationHit!=="function")return false;object.getWorldPosition(tmp);applyingRemoteWorldLife=true;try{return Boolean(b.registerWorldPopulationHit({object,point:tmp.clone()}));}finally{applyingRemoteWorldLife=false;}}

function ensureMuzzlePool(){const scene=bridge()?.threeScene;if(!scene)return;if(scene!==muzzleScene){for(const m of muzzlePool)m.group.parent?.remove(m.group);muzzlePool.length=0;muzzleScene=scene;muzzleGeo=new THREE.SphereGeometry(.045,7,5);muzzleConeGeo=new THREE.ConeGeometry(.065,.19,7);}while(muzzlePool.length<8){const group=new THREE.Group(),mat=new THREE.MeshBasicMaterial({color:0xffd36b,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}),core=new THREE.Mesh(muzzleGeo,mat),cone=new THREE.Mesh(muzzleConeGeo,mat.clone());cone.position.y=.09;for(const m of[core,cone])m.userData.flightFireIgnore=true;group.add(core,cone);group.visible=false;scene.add(group);muzzlePool.push({group,core,cone,born:0,expires:0});}}
function spawnRemoteMuzzle(position,dir){ensureMuzzlePool();if(!muzzlePool.length)return;const item=muzzlePool.find(x=>!x.group.visible)||muzzlePool.reduce((a,b)=>a.born<=b.born?a:b),d=new THREE.Vector3(Number(dir?.[0])||0,Number(dir?.[1])||1,Number(dir?.[2])||0).normalize();item.group.position.set(Number(position?.[0])||0,Number(position?.[1])||0,Number(position?.[2])||0);item.group.quaternion.setFromUnitVectors(forwardAxis,d);item.born=performance.now();item.expires=item.born+85;item.core.material.opacity=.95;item.cone.material.opacity=.8;item.group.visible=true;}
function ensureBlastPool(){const scene=bridge()?.threeScene;if(!scene)return;if(scene!==blastScene){for(const b of blastPool)b.group.parent?.remove(b.group);blastPool.length=0;blastScene=scene;blastGeo=new THREE.SphereGeometry(.18,10,7);blastRingGeo=new THREE.RingGeometry(.45,.72,20);}while(blastPool.length<6){const group=new THREE.Group(),core=new THREE.Mesh(blastGeo,new THREE.MeshBasicMaterial({color:0xffd98a,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending})),shell=new THREE.Mesh(blastGeo,new THREE.MeshBasicMaterial({color:0xff6f32,transparent:true,opacity:0,depthWrite:false,side:THREE.BackSide,blending:THREE.AdditiveBlending})),ring=new THREE.Mesh(blastRingGeo,new THREE.MeshBasicMaterial({color:0xffb45d,transparent:true,opacity:0,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending}));for(const m of[core,shell,ring])m.userData.flightFireIgnore=true;group.add(core,shell,ring);group.visible=false;scene.add(group);blastPool.push({group,core,shell,ring,born:0,expires:0,small:false});}}
function spawnRoundBlast(position,small=false){ensureBlastPool();if(!blastPool.length)return;const item=blastPool.find(x=>!x.group.visible)||blastPool.reduce((a,b)=>a.born<=b.born?a:b);item.group.position.set(Number(position?.[0])||0,Number(position?.[1])||0,Math.max(.05,Number(position?.[2])||.05));item.born=performance.now();item.expires=item.born+(small?320:900);item.small=small;item.group.visible=true;}
function renderFx(now){for(const item of muzzlePool){if(!item.group.visible)continue;if(now>=item.expires){item.group.visible=false;continue;}const t=(now-item.born)/(item.expires-item.born);item.core.material.opacity=.95*(1-t);item.cone.material.opacity=.8*(1-t);item.group.scale.setScalar(.8+.55*Math.sin(Math.PI*t));}for(const item of blastPool){if(!item.group.visible)continue;if(now>=item.expires){item.group.visible=false;continue;}const t=(now-item.born)/(item.expires-item.born),e=1-(1-t)**3,k=item.small?.45:1;item.core.scale.setScalar(k*(.45+2.7*e));item.shell.scale.setScalar(k*(.65+5.2*e));item.ring.scale.setScalar(k*(.8+7.0*e));item.core.material.opacity=.95*(1-t);item.shell.material.opacity=.45*(1-t)**1.45;item.ring.material.opacity=.62*(1-t)**1.8;}}
function remoteFxPosition(packet,key="p"){return canonicalToLocal(packet?.[key]||[0,0,0]);}
function onFx(event){const packet=event?.detail?.packet;if(!packet)return;if(packet.type==="shot"&&packet.kind===PLAYER_FX_KIND){const p=remoteFxPosition(packet,"from");playPistol(p,true);spawnRemoteMuzzle(p,packet.dir);const v=viewport();if(v)v.dataset.vsRemotePistolSounds=String((Number(v.dataset.vsRemotePistolSounds)||0)+1);return;}if(packet.type==="impact"&&packet.kind===WORLD_LIFE_FX_KIND){applyRemoteWorldLife(packet);return;}if(packet.type==="explosion"){const p=remoteFxPosition(packet);spawnRoundBlast(p,false);playExplosion(p,false);}else if(packet.type==="impact"&&packet.kind!==WORLD_LIFE_FX_KIND){const p=remoteFxPosition(packet);spawnRoundBlast(p,true);playExplosion(p,true);}}
function onWorldExplosion(event){const p=event?.detail?.position;if(!p)return;playExplosion(p,false);}

function updatePerf(now){perfFrames++;const elapsed=now-perfStart;if(elapsed<1000)return;const fps=perfFrames*1000/elapsed,v=viewport();if(v){v.dataset.walkRuntimeFps=fps.toFixed(1);v.dataset.walkPerfProfile="cached-spatial-no-frame-traverse-v2";}perfStart=now;perfFrames=0;}
function frame(now=performance.now()){const dt=clamp((now-lastFrame)/1000,0,.05);lastFrame=now;patchPoseBridge();patchWorldHitRouting();patchFxSession();syncMode();if(pendingTeleport)teleportDrone(pendingTeleport.anchor,{hidden:pendingTeleport.hidden,launchOffset:pendingTeleport.launchOffset});updateHumanVelocity(now);observeWalkShot();augmentVsPose(false,now);renderLocalAvatar();renderRemoteAvatars(now,dt);renderFx(now);updatePerf(now);requestAnimationFrame(frame);}

export function installPlayerVehicleRuntime(){if(installed)return;installed=true;patchMotorRuntime();lastWalkShots=Number(viewport()?.dataset.walkShots||0);addEventListener("pointerdown",()=>ensureAudio(true),{capture:true,passive:true});addEventListener("keydown",()=>ensureAudio(true),{capture:true});addEventListener(AUDIO_SETTINGS_EVENT,event=>{if(audioOverride||currentMode()!=="foot"||Number(event.detail?.droneVolume)===0)return;queueMicrotask(suppressDroneAudio);});addEventListener(VS_POSE_EVENT,onPose);addEventListener(VS_PEER_EVENT,onPeer);addEventListener(VS_FX_EVENT,onFx);addEventListener("arondight:world-explosion",onWorldExplosion);const v=viewport();if(v){v.dataset.playerVehicleRuntime="human-drone-v2";v.dataset.walkCollisionRadiusM=HUMAN_RADIUS.toFixed(2);v.dataset.walkPistolSound="procedural-synced-v2";v.dataset.walkPerfProfile="cached-spatial-no-frame-traverse-v2";}globalThis.__arondightPlayerVehicleRuntime={get mode(){return currentMode();},get humanAnchor(){return{...humanAnchor};},get humanVelocity(){return{...humanVelocity};},get remoteAvatarCount(){return remoteAvatars.size;},sync:syncMode,teleportDrone:anchor=>teleportDrone(anchor||snapshotHuman(),{hidden:currentMode()==="foot"}),resolveWalkMove,canOccupyWalkPoint};requestAnimationFrame(frame);}
