import * as THREE from "three";
let installed=false,sceneRef=null,root=null;
function bridge(){return globalThis.__arondightRealWorld||null;}
function viewport(){return document.getElementById("viewport");}
function mesh(geometry,material,x,y,z=0){const m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);m.userData.flightFireIgnore=true;m.userData.trainingShowcase=true;return m;}
function build(scene){root?.parent?.remove(root);root=new THREE.Group();root.name="TRAINING_SHOWCASE_PLAZA";root.userData.flightFireIgnore=true;const asphalt=new THREE.MeshStandardMaterial({color:0x273039,roughness:.94}),line=new THREE.MeshBasicMaterial({color:0xe8f0f4}),cyan=new THREE.MeshStandardMaterial({color:0x2d9fc3,roughness:.48,metalness:.22,emissive:0x0c3948,emissiveIntensity:.28}),orange=new THREE.MeshStandardMaterial({color:0xd88937,roughness:.55,metalness:.18,emissive:0x48220a,emissiveIntensity:.22}),dark=new THREE.MeshStandardMaterial({color:0x171d22,roughness:.74,metalness:.18}),green=new THREE.MeshStandardMaterial({color:0x3e7e59,roughness:.85}),glass=new THREE.MeshBasicMaterial({color:0x8bdcff,transparent:true,opacity:.34,depthWrite:false});
  const plaza=mesh(new THREE.CylinderGeometry(34,34,.05,48),asphalt,0,0,.025);plaza.rotation.x=Math.PI/2;root.add(plaza);const helipad=mesh(new THREE.RingGeometry(4.4,5.0,40),line,-16,-5,.058);root.add(helipad);for(const [x,y,l,w] of [[0,0,4.8,.16],[-16,-5,.16,4.8],[0,0,.16,4.8]])root.add(mesh(new THREE.BoxGeometry(l,w,.018),line,x+(x===0?0:0),y,.068));
  for(const x of[-4.8,4.8])root.add(mesh(new THREE.BoxGeometry(.13,78,.018),line,x,0,.064));for(let y=-36;y<=36;y+=8)root.add(mesh(new THREE.BoxGeometry(.12,3.5,.02),line,0,y,.065));
  const archYs=[-30,-14,14,30];for(let i=0;i<archYs.length;i++){const y=archYs[i],mat=i%2?cyan:orange;root.add(mesh(new THREE.BoxGeometry(.42,.42,4.2),mat,-6.2,y,2.1),mesh(new THREE.BoxGeometry(.42,.42,4.2),mat,6.2,y,2.1),mesh(new THREE.BoxGeometry(12.8,.42,.34),mat,0,y,4.03));}
  for(const [x,y] of [[-27,-24],[27,-24],[-27,24],[27,24]]){root.add(mesh(new THREE.CylinderGeometry(.11,.15,5.4,8),dark,x,y,2.7));const lamp=mesh(new THREE.SphereGeometry(.28,8,6),glass,x,y,5.45);root.add(lamp);const light=new THREE.PointLight(0x9edfff,2.4,18,2);light.position.set(x,y,5.25);light.userData.flightFireIgnore=true;root.add(light);}
  for(let i=0;i<7;i++){const x=15+(i%2)*4.2,y=-27+Math.floor(i/2)*5.4;const pad=mesh(new THREE.BoxGeometry(3.5,4.5,.025),i%2?dark:green,x,y,.065);root.add(pad);const stripe=mesh(new THREE.BoxGeometry(2.6,.12,.02),line,x,y,.085);root.add(stripe);}const sign=mesh(new THREE.BoxGeometry(8,.18,2.0),cyan,20,-5,1.2);root.add(sign);
  const rangeMat=new THREE.MeshStandardMaterial({color:0x606a70,roughness:.8,metalness:.12});for(let i=0;i<6;i++){const y=-22+i*8,x=-26+(i%2)*2;const target=mesh(new THREE.BoxGeometry(.5,.16,1.45),rangeMat,x,y,.73);root.add(target);root.add(mesh(new THREE.BoxGeometry(3.2,.08,.02),orange,x+2.2,y,.07));}
  const rampMat=new THREE.MeshStandardMaterial({color:0x4b535a,roughness:.7,metalness:.22});for(const y of[-18,18]){const ramp=mesh(new THREE.BoxGeometry(7,4,.22),rampMat,21,y,.18);ramp.rotation.y=-.07;root.add(ramp);}const centerRing=mesh(new THREE.TorusGeometry(9,.08,6,48),cyan,0,0,.09);root.add(centerRing);
  scene.add(root);sceneRef=scene;const view=viewport();if(view){view.dataset.worldTrainingShowcase="walkable-plaza+gates+paddock+range-v1";view.dataset.worldTrainingPromenadeWidthM="9.6";view.dataset.worldTrainingVehiclePaddock="1";}return root;}
function frame(){const b=bridge(),scene=b?.threeScene;if(scene&&scene!==sceneRef)build(scene);if(root){const training=!b?.active&&viewport()?.dataset.worldMode!=="real";root.visible=training;}requestAnimationFrame(frame);}
export function installTrainingShowcase(){if(installed)return;installed=true;requestAnimationFrame(frame);}
installTrainingShowcase();
