import * as THREE from "three";

const RESPAWN_MS=2200;
const $=id=>document.getElementById(id);
const clamp=(x,lo,hi)=>Math.max(lo,Math.min(hi,x));

function installStyle(){
  if($("vsCombatPresentationStyle"))return;
  const style=document.createElement("style");style.id="vsCombatPresentationStyle";style.textContent=`
    #vsCombatHud{display:inline-flex;align-items:center;min-height:28px;padding:4px 8px;border:1px solid #ff476788;border-radius:8px;background:#160a12e8;color:#fff1f4;font:900 10px/1 system-ui,-apple-system,sans-serif;letter-spacing:.045em;text-shadow:0 1px 2px #000;box-shadow:0 0 16px #ff31551c;white-space:nowrap}
    #vsEnemyHud{position:absolute;z-index:13;left:0;top:0;min-width:98px;transform:translate(-50%,-50%);pointer-events:none;filter:drop-shadow(0 2px 5px #000d);will-change:left,top}
    #vsEnemyHud[hidden]{display:none!important}
    #vsEnemyHud .vs-enemy-pointer{height:19px;text-align:center;color:#ff355e;font:900 18px/18px system-ui;text-shadow:0 0 8px #ff244f,0 0 2px #000;transform-origin:50% 50%}
    #vsEnemyHud .vs-enemy-card{padding:4px 6px 5px;border:1px solid #ff5471cc;border-radius:7px;background:#13080dcc;color:#fff;font:900 9px/1.15 system-ui,-apple-system,sans-serif;text-align:center;letter-spacing:.06em;box-shadow:inset 0 0 12px #ff244f18,0 0 9px #0008}
    #vsEnemyHud .vs-enemy-row{display:flex;align-items:center;justify-content:center;gap:5px}.vs-enemy-name{color:#ff6f86}.vs-enemy-distance{color:#fff}
    #vsEnemyHud .vs-enemy-health{height:4px;margin-top:4px;border-radius:99px;background:#390d17;overflow:hidden;box-shadow:0 0 0 1px #ffffff18 inset}#vsEnemyHud .vs-enemy-health>i{display:block;height:100%;width:100%;background:linear-gradient(90deg,#ff244f,#ff8a5a);transition:width .12s linear}
    #vsEnemyHud .vs-enemy-state{margin-top:3px;color:#ffb1bd;font:800 8px/1 system-ui;min-height:8px}
    #vsEnemyHud.offscreen .vs-enemy-card{background:#16090ef2;border-color:#ff6a82}#vsEnemyHud.offscreen .vs-enemy-pointer{font-size:22px}
    #vsEnemyHud.dead{opacity:.88}#vsEnemyHud.dead .vs-enemy-pointer{color:#ffb14d;text-shadow:0 0 8px #ff7b23}#vsEnemyHud.dead .vs-enemy-card{border-color:#ffad52;background:#211204e8}#vsEnemyHud.dead .vs-enemy-name,#vsEnemyHud.dead .vs-enemy-state{color:#ffc372}#vsEnemyHud.dead .vs-enemy-health>i{background:#ff9c38}
    #vsRespawnHud{position:absolute;z-index:14;left:50%;top:46%;transform:translate(-50%,-50%);min-width:190px;padding:12px 16px;border:1px solid #ff5a72;border-radius:12px;background:#13070de8;color:white;text-align:center;pointer-events:none;box-shadow:0 0 36px #ff244f42,0 12px 42px #000b;text-shadow:0 2px 5px #000}
    #vsRespawnHud[hidden]{display:none!important}#vsRespawnHud strong{display:block;color:#ff637b;font:1000 20px/1 system-ui;letter-spacing:.12em}#vsRespawnHud span{display:block;margin-top:6px;font:900 12px/1 system-ui;letter-spacing:.08em;color:#ffe3e8}#vsRespawnHud .vs-respawn-bar{height:5px;margin-top:9px;border-radius:99px;background:#3d1119;overflow:hidden}#vsRespawnHud .vs-respawn-bar>i{display:block;height:100%;width:100%;transform-origin:left center;background:linear-gradient(90deg,#ff3158,#ffd06d)}
    #vsCombatBanner{position:absolute;z-index:15;left:50%;top:23%;transform:translate(-50%,-50%) scale(.92);padding:7px 12px;border-radius:8px;border:1px solid #ff5a72;background:#13070de8;color:#fff;font:1000 14px/1 system-ui;letter-spacing:.1em;opacity:0;pointer-events:none;text-shadow:0 2px 4px #000;transition:opacity .14s ease,transform .14s ease;white-space:nowrap}#vsCombatBanner.show{opacity:1;transform:translate(-50%,-50%) scale(1)}#vsCombatBanner.respawn{border-color:#62e6ad;color:#baffdf;background:#06150fe8}#vsCombatBanner.kill{border-color:#ffb04d;color:#ffe4b2}
    #vsDeathFlash{position:absolute;z-index:12;inset:0;pointer-events:none;opacity:0;background:radial-gradient(circle at 50% 50%,#fff7c4 0 4%,#ff812f88 18%,#ff244f44 46%,transparent 76%)}#vsDeathFlash.fire{animation:vsDeathFlash .58s ease-out}@keyframes vsDeathFlash{0%{opacity:1}35%{opacity:.62}100%{opacity:0}}
  `;document.head.appendChild(style);
}

function installDom(viewport){
  let enemy=$("vsEnemyHud");if(!enemy){enemy=document.createElement("div");enemy.id="vsEnemyHud";enemy.hidden=true;enemy.innerHTML='<div class="vs-enemy-pointer">▲</div><div class="vs-enemy-card"><div class="vs-enemy-row"><b class="vs-enemy-name">ENEMY</b><b class="vs-enemy-distance">-- m</b></div><div class="vs-enemy-health"><i></i></div><div class="vs-enemy-state">TRACK</div></div>';viewport.appendChild(enemy);}
  let respawn=$("vsRespawnHud");if(!respawn){respawn=document.createElement("div");respawn.id="vsRespawnHud";respawn.hidden=true;respawn.innerHTML='<strong>DESTROYED</strong><span>RESPAWN 2.2 s</span><div class="vs-respawn-bar"><i></i></div>';viewport.appendChild(respawn);}
  let banner=$("vsCombatBanner");if(!banner){banner=document.createElement("div");banner.id="vsCombatBanner";viewport.appendChild(banner);}
  let flash=$("vsDeathFlash");if(!flash){flash=document.createElement("div");flash.id="vsDeathFlash";viewport.appendChild(flash);}
  return{enemy,respawn,banner,flash,pointer:enemy.querySelector(".vs-enemy-pointer"),enemyName:enemy.querySelector(".vs-enemy-name"),enemyDistance:enemy.querySelector(".vs-enemy-distance"),enemyHealth:enemy.querySelector(".vs-enemy-health>i"),enemyState:enemy.querySelector(".vs-enemy-state"),respawnText:respawn.querySelector("span"),respawnBar:respawn.querySelector(".vs-respawn-bar>i")};
}

export function installVsCombatPresentation(bridge){
  if(!bridge||bridge.__vsCombatPresentationInstalled)return bridge;
  const viewport=$("viewport");if(!viewport)return bridge;
  bridge.__vsCombatPresentationInstalled=true;viewport.dataset.vsCombatPresentation="1";installStyle();const ui=installDom(viewport);
  const state={localRespawnAt:0,peerRespawnAt:0,bannerTimer:0,audioCtx:null,noiseBuffer:null,projected:new THREE.Vector3(),cameraPos:new THREE.Vector3(),cameraDir:new THREE.Vector3(),target:new THREE.Vector3(),toTarget:new THREE.Vector3()};

  const showBanner=(text,kind="")=>{clearTimeout(state.bannerTimer);ui.banner.textContent=text;ui.banner.className=kind?`show ${kind}`:"show";state.bannerTimer=setTimeout(()=>{ui.banner.className="";},900);};
  const flashDeath=()=>{ui.flash.classList.remove("fire");void ui.flash.offsetWidth;ui.flash.classList.add("fire");};
  const ensureAudio=()=>{if(state.audioCtx)return state.audioCtx;const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return null;try{const ctx=new Ctx(),buffer=ctx.createBuffer(1,Math.max(1,Math.floor(ctx.sampleRate*.42)),ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++){const t=i/data.length;data[i]=(Math.random()*2-1)*Math.pow(1-t,2.2);}state.audioCtx=ctx;state.noiseBuffer=buffer;return ctx;}catch{return null;}};
  const armAudio=()=>{const ctx=ensureAudio();try{if(ctx?.state==="suspended")void ctx.resume();}catch{}};document.addEventListener("pointerdown",armAudio,{capture:true});
  const playExplosionSound=()=>{viewport.dataset.vsExplosionSoundCount=String((Number(viewport.dataset.vsExplosionSoundCount)||0)+1);const ctx=ensureAudio();if(!ctx||!state.noiseBuffer)return;try{if(ctx.state==="suspended")void ctx.resume();const now=ctx.currentTime,noise=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),noiseGain=ctx.createGain(),boom=ctx.createOscillator(),boomGain=ctx.createGain();noise.buffer=state.noiseBuffer;filter.type="lowpass";filter.frequency.setValueAtTime(1150,now);filter.frequency.exponentialRampToValueAtTime(130,now+.40);noiseGain.gain.setValueAtTime(.32,now);noiseGain.gain.exponentialRampToValueAtTime(.001,now+.42);noise.connect(filter).connect(noiseGain).connect(ctx.destination);boom.type="sine";boom.frequency.setValueAtTime(92,now);boom.frequency.exponentialRampToValueAtTime(34,now+.48);boomGain.gain.setValueAtTime(.38,now);boomGain.gain.exponentialRampToValueAtTime(.001,now+.52);boom.connect(boomGain).connect(ctx.destination);noise.start(now);noise.stop(now+.43);boom.start(now);boom.stop(now+.53);}catch{}};

  const enhancePeerMesh=()=>{const group=bridge.vsPeerMesh;if(!group||group.userData.vsCombatVisualEnhanced)return;group.userData.vsCombatVisualEnhanced=true;group.traverse(node=>{if(!node.isMesh||node.userData?.flightFireIgnore)return;const mat=node.material;if(mat?.isMeshStandardMaterial){mat.color.setHex(0xff3158);mat.emissive.setHex(0x7a071d);mat.emissiveIntensity=1.5;mat.roughness=.22;mat.metalness=.18;}});const haloMat=new THREE.MeshBasicMaterial({color:0xff3158,transparent:true,opacity:.92,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide}),halo=new THREE.Mesh(new THREE.TorusGeometry(.30,.013,6,28),haloMat);halo.position.z=.035;halo.renderOrder=9;halo.userData.flightFireIgnore=true;halo.userData.vsPeerHalo=true;group.add(halo);const beaconMat=new THREE.MeshBasicMaterial({color:0xffb15a,transparent:true,opacity:.9,depthWrite:false,blending:THREE.AdditiveBlending}),beacon=new THREE.Mesh(new THREE.SphereGeometry(.035,8,6),beaconMat);beacon.position.z=.19;beacon.renderOrder=10;beacon.userData.flightFireIgnore=true;beacon.userData.vsPeerBeacon=true;group.add(beacon);};

  const updateEnemyHud=()=>{
    enhancePeerMesh();const camera=bridge.threeCamera,target=bridge.vsPeerRenderPosition||bridge.vsPeerTargetPosition||bridge.vsPeerMesh?.position;if(!bridge.vsConnected||!camera||!target){ui.enemy.hidden=true;viewport.dataset.vsEnemyHud="hidden";return;}
    const rect=viewport.getBoundingClientRect();if(!(rect.width>0&&rect.height>0)){ui.enemy.hidden=true;return;}camera.updateMatrixWorld?.();state.target.copy(target);state.projected.copy(state.target).project(camera);camera.getWorldPosition(state.cameraPos);camera.getWorldDirection(state.cameraDir);const front=state.toTarget.copy(state.target).sub(state.cameraPos).dot(state.cameraDir)>0;if(!front){state.projected.x=-state.projected.x;state.projected.y=-state.projected.y;}const onScreen=front&&state.projected.z>=-1&&state.projected.z<=1&&Math.abs(state.projected.x)<=.88&&Math.abs(state.projected.y)<=.78;let x=(state.projected.x*.5+.5)*rect.width,y=(-state.projected.y*.5+.5)*rect.height,angle=0;if(!onScreen){let dx=x-rect.width/2,dy=y-rect.height/2;if(!Number.isFinite(dx)||!Number.isFinite(dy)||Math.hypot(dx,dy)<1){dx=0;dy=-1;}const margin=58,sx=(rect.width/2-margin)/Math.max(1,Math.abs(dx)),sy=(rect.height/2-margin)/Math.max(1,Math.abs(dy)),scale=Math.max(0,Math.min(sx,sy));x=rect.width/2+dx*scale;y=rect.height/2+dy*scale;angle=Math.atan2(dy,dx)*180/Math.PI+90;}ui.enemy.hidden=false;ui.enemy.classList.toggle("offscreen",!onScreen);ui.enemy.classList.toggle("dead",Boolean(bridge.vsPeerDead));ui.enemy.style.left=`${clamp(x,48,Math.max(48,rect.width-48))}px`;ui.enemy.style.top=`${clamp(y,50,Math.max(50,rect.height-50))}px`;ui.pointer.style.transform=`rotate(${onScreen?0:angle}deg)`;const local=bridge.threeScene?bridge.airframeFor?.(bridge.threeScene)?.position:null,distance=Number((local||state.cameraPos)?.distanceTo?.(state.target));const distanceText=Number.isFinite(distance)?`${distance<100?distance.toFixed(1):Math.round(distance)} m`:"-- m";ui.enemyDistance.textContent=distanceText;const hp=clamp(Number(bridge.vsPeerHealth)||0,0,100);ui.enemyHealth.style.width=`${hp}%`;const remaining=state.peerRespawnAt?Math.max(0,state.peerRespawnAt-performance.now()):0;ui.enemyName.textContent=bridge.vsPeerDead?"ENEMY DOWN":"ENEMY";ui.enemyState.textContent=bridge.vsPeerDead?`RESPAWN ${(remaining/1000).toFixed(1)} s`:onScreen?"TARGET":"OFFSCREEN";viewport.dataset.vsEnemyHud=bridge.vsPeerDead?"dead":onScreen?"onscreen":"offscreen";viewport.dataset.vsEnemyDistance=Number.isFinite(distance)?distance.toFixed(2):"";
  };
  const updateRespawnHud=()=>{const now=performance.now();if(bridge.vsLocalDead){if(!state.localRespawnAt)state.localRespawnAt=now+RESPAWN_MS;const remaining=Math.max(0,state.localRespawnAt-now);ui.respawn.hidden=false;ui.respawnText.textContent=`RESPAWN ${(remaining/1000).toFixed(1)} s`;ui.respawnBar.style.transform=`scaleX(${clamp(remaining/RESPAWN_MS,0,1)})`;viewport.dataset.vsRespawnMs=String(Math.ceil(remaining));}else{if(state.localRespawnAt){state.localRespawnAt=0;showBanner("RESPAWNED","respawn");}ui.respawn.hidden=true;viewport.dataset.vsRespawnMs="0";}if(state.peerRespawnAt&&!bridge.vsPeerDead)state.peerRespawnAt=0;};
  const updatePresentation=()=>{updateRespawnHud();updateEnemyHud();};

  const originalEnsure=bridge.ensureVsPeerMesh.bind(bridge);bridge.ensureVsPeerMesh=function(...args){const result=originalEnsure(...args);enhancePeerMesh();return result;};
  const originalUpdate=bridge.updateVsPeerRender.bind(bridge);bridge.updateVsPeerRender=function(...args){const result=originalUpdate(...args);updatePresentation();return result;};
  const originalExplosion=bridge.explodeVsPeer.bind(bridge);bridge.explodeVsPeer=function(...args){const result=originalExplosion(...args);state.peerRespawnAt=performance.now()+RESPAWN_MS;playExplosionSound();showBanner("ENEMY DESTROYED","kill");flashDeath();updatePresentation();return result;};
  const originalApply=bridge.applyVsCombat.bind(bridge);bridge.applyVsCombat=function(packet){const wasLocalDead=this.vsLocalDead,wasPeerDead=this.vsPeerDead;const result=originalApply(packet);if(!wasLocalDead&&this.vsLocalDead){state.localRespawnAt=performance.now()+RESPAWN_MS;playExplosionSound();showBanner("DRONE DESTROYED");flashDeath();}if(wasPeerDead&&!this.vsPeerDead&&packet?.type==="respawn"){state.peerRespawnAt=0;showBanner("ENEMY RESPAWNED","respawn");}updatePresentation();return result;};
  const originalReset=bridge.resetVsCombat.bind(bridge);bridge.resetVsCombat=function(...args){const result=originalReset(...args);state.localRespawnAt=0;state.peerRespawnAt=0;ui.respawn.hidden=true;ui.enemy.hidden=true;updatePresentation();return result;};
  const originalHud=bridge.updateVsCombatHud.bind(bridge);bridge.updateVsCombatHud=function(...args){const result=originalHud(...args),hud=this.vsCombatHud||$("vsCombatHud");if(hud&&!hud.hidden)hud.textContent=`YOU ${this.vsLocalHealth} · ENEMY ${this.vsPeerHealth} · K ${this.vsKills}`;return result;};

  enhancePeerMesh();bridge.updateVsCombatHud();updatePresentation();return bridge;
}
