import * as THREE from "three";

const RESPAWN_MS=2200;
const STALE_PEER_MS=1400;
const PRESENTATION_MS=1000/30;
const PEER_VISUAL_SCALE=4.5;
const BEACON_DOUBLE_TAP_MS=330;
const BEACON_DOUBLE_TAP_PX=36;
let installed=false;
let audioContext=null;
let explosionNoiseBuffer=null;
let marker=null;
let respawnHud=null;
let explosionFlash=null;
let enhancedPeerMesh=null;
let combatHudNode=null;
let combatHudObserver=null;
let previousLocalDead=false;
let previousPeerDead=false;
let localDeathAt=-Infinity;
let peerDeathAt=-Infinity;
let soundEventCount=0;
let audioStartedCount=0;
let lastPresentationMs=-Infinity;
let beaconGroup=null;
let beaconMarker=null;
let beaconState=null;
let hookedBridge=null;
let originalApplyVsCombat=null;
let previousVsConnected=false;
let lastBeaconTapAt=-Infinity;
let lastBeaconTapX=0;
let lastBeaconTapY=0;
let lastBeaconPointerType="";
const worldPosition=new THREE.Vector3();
const cameraPosition=new THREE.Vector3();
const ownPosition=new THREE.Vector3();
const projected=new THREE.Vector3();
const cameraSpace=new THREE.Vector3();
const beaconWorldPosition=new THREE.Vector3();
const beaconProjected=new THREE.Vector3();
const beaconCameraSpace=new THREE.Vector3();
const beaconRaycaster=new THREE.Raycaster();
const beaconNdc=new THREE.Vector2();

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function clamp(value,min,max){return Math.max(min,Math.min(max,value));}

function prepareExplosionNoise(ctx){if(explosionNoiseBuffer||!ctx)return explosionNoiseBuffer;const duration=.82,samples=Math.max(1,Math.floor(ctx.sampleRate*duration)),buffer=ctx.createBuffer(1,samples,ctx.sampleRate),data=buffer.getChannelData(0);let seed=0x45a70d1;for(let i=0;i<samples;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const noise=(seed/0xffffffff)*2-1,t=i/samples;data[i]=noise*Math.pow(1-t,2.35);}explosionNoiseBuffer=buffer;const view=viewport();if(view)view.dataset.vsExplosionAudioReady="1";return buffer;}
function ensureAudio(){const AudioCtor=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AudioCtor)return null;try{audioContext??=new AudioCtor({latencyHint:"interactive"});}catch{return null;}const ready=()=>{prepareExplosionNoise(audioContext);const view=viewport();if(view)view.dataset.vsExplosionAudioState=audioContext.state;};if(audioContext.state==="suspended")audioContext.resume().then(ready).catch(()=>{});else ready();return audioContext;}
function primeAudio(){ensureAudio();}
function playExplosion(local=false){const view=viewport();soundEventCount++;if(view)view.dataset.vsExplosionSoundCount=String(soundEventCount);const ctx=ensureAudio();try{navigator.vibrate?.(local?[70,35,120]:[65]);}catch{}if(!ctx||ctx.state!=="running"||!explosionNoiseBuffer){if(view)view.dataset.vsExplosionAudioState=ctx?.state||"unavailable";return false;}try{const now=ctx.currentTime,duration=.82,noise=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),noiseGain=ctx.createGain();noise.buffer=explosionNoiseBuffer;filter.type="lowpass";filter.frequency.setValueAtTime(local?1150:900,now);filter.frequency.exponentialRampToValueAtTime(120,now+duration);noiseGain.gain.setValueAtTime(.0001,now);noiseGain.gain.exponentialRampToValueAtTime(local?.52:.38,now+.012);noiseGain.gain.exponentialRampToValueAtTime(.0001,now+duration);noise.connect(filter).connect(noiseGain).connect(ctx.destination);const boom=ctx.createOscillator(),boomGain=ctx.createGain();boom.type="sine";boom.frequency.setValueAtTime(local?105:92,now);boom.frequency.exponentialRampToValueAtTime(34,now+.55);boomGain.gain.setValueAtTime(.0001,now);boomGain.gain.exponentialRampToValueAtTime(local?.58:.43,now+.008);boomGain.gain.exponentialRampToValueAtTime(.0001,now+.72);boom.connect(boomGain).connect(ctx.destination);const crack=ctx.createOscillator(),crackGain=ctx.createGain();crack.type="triangle";crack.frequency.setValueAtTime(210,now);crack.frequency.exponentialRampToValueAtTime(58,now+.18);crackGain.gain.setValueAtTime(.0001,now);crackGain.gain.exponentialRampToValueAtTime(.17,now+.004);crackGain.gain.exponentialRampToValueAtTime(.0001,now+.22);crack.connect(crackGain).connect(ctx.destination);noise.start(now);noise.stop(now+duration);boom.start(now);boom.stop(now+.74);crack.start(now);crack.stop(now+.24);audioStartedCount++;if(view){view.dataset.vsExplosionAudioStartedCount=String(audioStartedCount);view.dataset.vsExplosionAudioState=ctx.state;}return true;}catch{return false;}}
function flashExplosion(local=false){if(!explosionFlash)return;explosionFlash.classList.remove("pulse","local");void explosionFlash.offsetWidth;if(local)explosionFlash.classList.add("local");explosionFlash.classList.add("pulse");}
function makeGlowTexture(){const canvas=document.createElement("canvas");canvas.width=128;canvas.height=128;const ctx=canvas.getContext("2d");if(!ctx)return null;const gradient=ctx.createRadialGradient(64,64,4,64,64,62);gradient.addColorStop(0,"rgba(255,235,180,.95)");gradient.addColorStop(.17,"rgba(255,78,44,.72)");gradient.addColorStop(.48,"rgba(255,35,22,.28)");gradient.addColorStop(1,"rgba(255,20,10,0)");ctx.fillStyle=gradient;ctx.fillRect(0,0,128,128);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture;}
function enhancePeerVisual(currentBridge){const peer=currentBridge?.vsPeerMesh;if(!peer||peer===enhancedPeerMesh)return;enhancedPeerMesh=peer;peer.scale.setScalar(PEER_VISUAL_SCALE);peer.userData.vsOpponentVisualScale=PEER_VISUAL_SCALE;const view=viewport();if(view)view.dataset.vsOpponentVisualScale=String(PEER_VISUAL_SCALE);const meshes=[];peer.traverse(node=>{if(node?.isMesh&&!node.userData?.vsCombatOutline)meshes.push(node);});for(const mesh of meshes){const material=mesh.material;if(material?.color?.setHex)material.color.setHex(0xff5a32);if(material?.emissive?.setHex){material.emissive.setHex(0x8a1000);material.emissiveIntensity=1.7;}if(material){material.roughness=.28;material.metalness=.18;}if(mesh.geometry){const outlineMaterial=new THREE.MeshBasicMaterial({color:0xff2416,side:THREE.BackSide,transparent:true,opacity:.7,depthWrite:false});const outline=new THREE.Mesh(mesh.geometry,outlineMaterial);outline.scale.setScalar(1.13);outline.userData.vsCombatOutline=true;outline.userData.flightFireIgnore=true;outline.raycast=()=>{};mesh.add(outline);}}const texture=makeGlowTexture();if(texture){const glow=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,color:0xff4b28,transparent:true,opacity:.42,depthWrite:false,depthTest:true,blending:THREE.AdditiveBlending}));glow.scale.set(.92,.92,.92);glow.position.z=.02;glow.userData.flightFireIgnore=true;glow.raycast=()=>{};peer.add(glow);}}
function ownDroneWorldPosition(currentBridge){const airframe=currentBridge?.airframeFor?.(currentBridge.threeScene)||currentBridge?.airframe;if(airframe?.getWorldPosition){airframe.updateWorldMatrix?.(true,false);airframe.getWorldPosition(ownPosition);return ownPosition;}if(airframe?.position){ownPosition.copy(airframe.position);return ownPosition;}ownPosition.copy(cameraPosition);return ownPosition;}
function respawnRemainingMs(deadSince){return Number.isFinite(deadSince)?Math.max(0,RESPAWN_MS-(performance.now()-deadSince)):0;}
function currentVsFrame(){return String(viewport()?.dataset.vsSharedFrame||"local-metric");}
function clearSharedBeacon(){beaconState=null;if(beaconGroup)beaconGroup.visible=false;if(beaconMarker)beaconMarker.hidden=true;const view=viewport();if(view){delete view.dataset.vsBeacon;delete view.dataset.vsBeaconDistanceM;delete view.dataset.vsBeaconSource;}}
function ensureBeaconVisual(currentBridge){const scene=currentBridge?.threeScene;if(!scene)return null;if(beaconGroup?.parent===scene)return beaconGroup;if(beaconGroup?.parent)beaconGroup.parent.remove(beaconGroup);if(!beaconGroup){const group=new THREE.Group(),ring=new THREE.Mesh(new THREE.TorusGeometry(.52,.055,8,28),new THREE.MeshBasicMaterial({color:0x55e6ff,transparent:true,opacity:.95,depthWrite:false,depthTest:true})),beam=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,5,8),new THREE.MeshBasicMaterial({color:0x55e6ff,transparent:true,opacity:.32,depthWrite:false,depthTest:true})),tip=new THREE.Mesh(new THREE.OctahedronGeometry(.18),new THREE.MeshBasicMaterial({color:0xb9f7ff,transparent:true,opacity:.96,depthWrite:false,depthTest:true}));beam.rotation.x=Math.PI/2;beam.position.z=2.5;tip.position.z=.34;for(const node of [ring,beam,tip]){node.userData.flightFireIgnore=true;node.raycast=()=>{};}group.add(ring,beam,tip);group.visible=false;group.renderOrder=11;group.userData.vsLocationBeacon=true;beaconGroup=group;}scene.add(beaconGroup);return beaconGroup;}
function applySharedBeaconPacket(currentBridge,packet,source="ally"){const p=Array.isArray(packet?.p)?packet.p.map(Number):null;if(!p||p.length!==3||!p.every(Number.isFinite))return false;const packetFrame=typeof packet.f==="string"?packet.f:"",frame=currentVsFrame();if(packetFrame&&frame&&packetFrame!==frame)return false;beaconState={id:String(packet.id||"beacon"),p,source:source==="you"?"you":"ally",frame:packetFrame||frame};const group=ensureBeaconVisual(currentBridge);if(group){group.position.set(...p);group.visible=Boolean(currentBridge?.vsConnected);}updateBeaconPresentation(currentBridge,performance.now());return true;}
function hookBeaconCombat(currentBridge){if(!currentBridge||hookedBridge===currentBridge)return;if(hookedBridge&&originalApplyVsCombat)hookedBridge.applyVsCombat=originalApplyVsCombat;hookedBridge=currentBridge;const original=typeof currentBridge.applyVsCombat==="function"?currentBridge.applyVsCombat.bind(currentBridge):null;originalApplyVsCombat=original;currentBridge.applyVsCombat=(packet,...args)=>{if(packet?.type==="beacon")return applySharedBeaconPacket(currentBridge,packet,"ally");return original?.(packet,...args);};}
function targetFromPointer(currentBridge,event){const view=viewport(),camera=currentBridge?.threeCamera;if(!view||!camera)return null;const rect=view.getBoundingClientRect();if(rect.width<2||rect.height<2)return null;const x=Number(event.clientX)-rect.left,y=Number(event.clientY)-rect.top;if(!Number.isFinite(x)||!Number.isFinite(y)||x<0||x>rect.width||y<0||y>rect.height)return null;beaconNdc.set(x/rect.width*2-1,-(y/rect.height)*2+1);camera.updateMatrixWorld?.(true);beaconRaycaster.setFromCamera(beaconNdc,camera);const ray=beaconRaycaster.ray,visual=currentBridge?.addVisualShotImpact?.(x,y,rect,ray),point=visual?.point;if(point&&[point.x,point.y,point.z].every(Number.isFinite))return[point.x,point.y,point.z];const dz=ray.direction.z;if(!(dz<-.00001))return null;const t=-ray.origin.z/dz;if(!(t>0)||t>1200)return null;return[ray.origin.x+ray.direction.x*t,ray.origin.y+ray.direction.y*t,0];}
function setSharedBeaconFromPointer(event){const currentBridge=bridge();if(!currentBridge?.vsConnected||!currentBridge?.vsSession?.sendCombat)return false;const p=targetFromPointer(currentBridge,event);if(!p)return false;const id=`b-${Date.now().toString(36)}-${Math.floor(performance.now()).toString(36)}`,packet={type:"beacon",id,p,f:currentVsFrame()};if(!currentBridge.vsSession.sendCombat(packet))return false;applySharedBeaconPacket(currentBridge,packet,"you");const view=viewport();if(view)view.dataset.vsBeaconSetCount=String(Number(view.dataset.vsBeaconSetCount||0)+1);try{navigator.vibrate?.(25);}catch{}return true;}
function handleBeaconPointerUp(event){if(viewport()?.dataset.fireTouchGestureArbiter==="1")return;if(!bridge()?.vsConnected)return;const target=event.target;if(target?.closest?.('button,input,select,textarea,a,label,[role="button"],#soloLeft,#soloRight,#soloHeight,#worldLookHud,#vsEnemyMarker,#vsBeaconMarker,.solo-action'))return;if(event.pointerType==="mouse"&&event.button!==0)return;const now=performance.now(),x=Number(event.clientX),y=Number(event.clientY),pointerType=String(event.pointerType||"pointer"),dt=now-lastBeaconTapAt,distance=Math.hypot(x-lastBeaconTapX,y-lastBeaconTapY),doubleTap=pointerType===lastBeaconPointerType&&dt>0&&dt<=BEACON_DOUBLE_TAP_MS&&distance<=BEACON_DOUBLE_TAP_PX;if(doubleTap){lastBeaconTapAt=-Infinity;setSharedBeaconFromPointer(event);return;}lastBeaconTapAt=now;lastBeaconTapX=x;lastBeaconTapY=y;lastBeaconPointerType=pointerType;}
function handleBeaconFireDoubleTap(event){if(!bridge()?.vsConnected)return;const detail=event?.detail||{};const clientX=Number(detail.clientX),clientY=Number(detail.clientY);if(!Number.isFinite(clientX)||!Number.isFinite(clientY))return;setSharedBeaconFromPointer({clientX,clientY,pointerType:String(detail.pointerType||"touch")});}
function updateBeaconPresentation(currentBridge,now){const connected=Boolean(currentBridge?.vsConnected);if(previousVsConnected&&!connected)clearSharedBeacon();previousVsConnected=connected;if(!connected||!beaconState){if(beaconGroup)beaconGroup.visible=false;if(beaconMarker)beaconMarker.hidden=true;return;}const group=ensureBeaconVisual(currentBridge),camera=currentBridge?.threeCamera,view=viewport();if(!group||!camera||!view||!beaconMarker)return;group.position.set(...beaconState.p);group.visible=true;const pulse=1+.08*Math.sin(now*.006);group.scale.setScalar(pulse);const rect=view.getBoundingClientRect();if(rect.width<1||rect.height<1){beaconMarker.hidden=true;return;}beaconWorldPosition.set(...beaconState.p);const distance=Math.max(0,ownDroneWorldPosition(currentBridge).distanceTo(beaconWorldPosition));beaconWorldPosition.z+=.35;camera.updateMatrixWorld?.(true);beaconProjected.copy(beaconWorldPosition).project(camera);beaconCameraSpace.copy(beaconWorldPosition).applyMatrix4(camera.matrixWorldInverse);const inFront=beaconCameraSpace.z<0;let nx=beaconProjected.x,ny=beaconProjected.y;if(!inFront){nx=-nx;ny=-ny;}const marginX=Math.min(70,rect.width*.14),marginY=Math.min(48,rect.height*.17),halfW=Math.max(1,rect.width/2-marginX),halfH=Math.max(1,rect.height/2-marginY);let sx=nx*rect.width/2,sy=-ny*rect.height/2;const scale=Math.min(1,halfW/Math.max(1,Math.abs(sx)),halfH/Math.max(1,Math.abs(sy)));sx*=scale;sy*=scale;const x=rect.width/2+sx,y=rect.height/2+sy,onScreen=inFront&&Math.abs(beaconProjected.x)<.94&&Math.abs(beaconProjected.y)<.88&&beaconProjected.z>-1&&beaconProjected.z<1;beaconMarker.hidden=false;beaconMarker.classList.toggle("offscreen",!onScreen);beaconMarker.style.transform=`translate3d(${x.toFixed(1)}px,${y.toFixed(1)}px,0) translate(-50%,-50%)`;const pointer=beaconMarker.querySelector("i");if(pointer)pointer.style.transform=`rotate(${(Math.atan2(sy,sx)*180/Math.PI+90).toFixed(1)}deg)`;const detail=beaconMarker.querySelector("small");if(detail)detail.textContent=`${beaconState.source==="you"?"YOU":"ALLY"} · ${distance<100?distance.toFixed(1):Math.round(distance)} m`;view.dataset.vsBeacon=onScreen?"onscreen":"offscreen";view.dataset.vsBeaconDistanceM=distance.toFixed(2);view.dataset.vsBeaconSource=beaconState.source;}
function updateEnemyMarker(currentBridge,now){if(!marker)return;const peer=currentBridge?.vsPeerMesh,camera=currentBridge?.threeCamera,view=viewport(),hasPose=Number.isFinite(currentBridge?.vsPeerLastPoseMs),poseAgeMs=hasPose?Math.max(0,now-currentBridge.vsPeerLastPoseMs):Infinity,signalHold=hasPose&&poseAgeMs>=STALE_PEER_MS;if(!currentBridge?.vsConnected||!peer||!camera||!view||(!hasPose&&!currentBridge.vsPeerDead)){marker.hidden=true;return;}const rect=view.getBoundingClientRect();if(rect.width<1||rect.height<1){marker.hidden=true;return;}peer.updateWorldMatrix?.(true,false);camera.updateMatrixWorld?.(true);peer.getWorldPosition(worldPosition);camera.getWorldPosition(cameraPosition);projected.copy(worldPosition).project(camera);cameraSpace.copy(worldPosition).applyMatrix4(camera.matrixWorldInverse);const inFront=cameraSpace.z<0;let nx=projected.x,ny=projected.y;if(!inFront){nx=-nx;ny=-ny;}const marginX=Math.min(74,rect.width*.14),marginY=Math.min(54,rect.height*.18),halfW=Math.max(1,rect.width/2-marginX),halfH=Math.max(1,rect.height/2-marginY);let sx=nx*rect.width/2,sy=-ny*rect.height/2;const scale=Math.min(1,halfW/Math.max(1,Math.abs(sx)),halfH/Math.max(1,Math.abs(sy)));sx*=scale;sy*=scale;const x=rect.width/2+sx,y=rect.height/2+sy,onScreen=inFront&&Math.abs(projected.x)<.92&&Math.abs(projected.y)<.84&&projected.z>-1&&projected.z<1;marker.hidden=false;marker.classList.toggle("offscreen",!onScreen);marker.classList.toggle("dead",Boolean(currentBridge.vsPeerDead));marker.classList.toggle("signal-hold",signalHold&&!currentBridge.vsPeerDead);marker.style.transform=`translate3d(${x.toFixed(1)}px,${y.toFixed(1)}px,0) translate(-50%,-50%)`;const pointer=marker.querySelector(".vs-enemy-pointer");if(pointer)pointer.style.transform=`rotate(${(Math.atan2(sy,sx)*180/Math.PI+90).toFixed(1)}deg)`;const distance=Math.max(0,ownDroneWorldPosition(currentBridge).distanceTo(worldPosition)),health=clamp(Math.round(Number(currentBridge.vsPeerHealth)||0),0,100),label=marker.querySelector("strong"),detail=marker.querySelector("small"),hpFill=marker.querySelector(".vs-enemy-hp>b");if(label)label.textContent=currentBridge.vsPeerDead?"ENEMY DOWN":signalHold?"ENEMY · HOLD":"ENEMY";if(detail){if(currentBridge.vsPeerDead){const remaining=respawnRemainingMs(peerDeathAt);detail.textContent=remaining>0?`RESPAWN ${(remaining/1000).toFixed(1)}s`:"RESPAWNING…";}else detail.textContent=signalHold?`LINK HOLD · ${distance<100?distance.toFixed(1):Math.round(distance)} m`:`HP ${health} · ${distance<100?distance.toFixed(1):Math.round(distance)} m`;}if(hpFill)hpFill.style.transform=`scaleX(${health/100})`;view.dataset.vsEnemyMarker=onScreen?"onscreen":"offscreen";view.dataset.vsEnemyDistanceM=distance.toFixed(2);view.dataset.vsEnemyHealth=String(health);view.dataset.vsEnemySignal=signalHold?"hold":"live";}
function updateRespawnHud(currentBridge){if(!respawnHud)return;const view=viewport();let title="",detail="",state="none",progress=0;if(currentBridge?.vsLocalDead){const remaining=respawnRemainingMs(localDeathAt);title="DESTROYED";detail=remaining>0?`RESPAWN ${(remaining/1000).toFixed(1)}s`:"RESPAWNING…";state="local";progress=remaining/RESPAWN_MS;}else if(currentBridge?.vsPeerDead){const remaining=respawnRemainingMs(peerDeathAt);title="ENEMY DESTROYED";detail=remaining>0?`RESPAWN ${(remaining/1000).toFixed(1)}s`:"RESPAWNING…";state="enemy";progress=remaining/RESPAWN_MS;}respawnHud.hidden=!title;respawnHud.classList.toggle("enemy",state==="enemy");const strong=respawnHud.querySelector("strong"),small=respawnHud.querySelector("span"),fill=respawnHud.querySelector("i");if(strong)strong.textContent=title;if(small)small.textContent=detail;if(fill)fill.style.transform=`scaleX(${clamp(progress,0,1)})`;if(view)view.dataset.vsRespawnState=state;}
function renderPresentation(now=performance.now(),force=false){if(!force&&now-lastPresentationMs<PRESENTATION_MS)return;lastPresentationMs=now;const currentBridge=bridge();if(currentBridge){hookBeaconCombat(currentBridge);enhancePeerVisual(currentBridge);const localDead=Boolean(currentBridge.vsLocalDead),peerDead=Boolean(currentBridge.vsPeerDead);if(localDead&&!previousLocalDead){localDeathAt=performance.now();playExplosion(true);flashExplosion(true);}if(peerDead&&!previousPeerDead){peerDeathAt=performance.now();playExplosion(false);flashExplosion(false);}if(!localDead)localDeathAt=-Infinity;if(!peerDead)peerDeathAt=-Infinity;previousLocalDead=localDead;previousPeerDead=peerDead;updateEnemyMarker(currentBridge,now);updateBeaconPresentation(currentBridge,now);updateRespawnHud(currentBridge);}else{if(marker)marker.hidden=true;if(beaconMarker)beaconMarker.hidden=true;if(respawnHud)respawnHud.hidden=true;}}
function bindCombatHudObserver(){const hud=document.getElementById("vsCombatHud");if(!hud||hud===combatHudNode)return;combatHudObserver?.disconnect();combatHudNode=hud;combatHudObserver=new MutationObserver(()=>{try{renderPresentation(performance.now(),true);}catch(error){const view=viewport();if(view)view.dataset.vsCombatPresentationError=String(error?.message||error);}});combatHudObserver.observe(hud,{childList:true,characterData:true,subtree:true});}
function animationLoop(now){try{bindCombatHudObserver();renderPresentation(now);}catch(error){const view=viewport();if(view)view.dataset.vsCombatPresentationError=String(error?.message||error);}finally{requestAnimationFrame(animationLoop);}}
function attachUi(){const view=viewport();if(!view)return false;if(!marker){marker=document.createElement("div");marker.id="vsEnemyMarker";marker.hidden=true;marker.setAttribute("aria-live","off");marker.innerHTML='<i class="vs-enemy-reticle"></i><i class="vs-enemy-pointer">▲</i><strong>ENEMY</strong><small>HP 100</small><i class="vs-enemy-hp"><b></b></i>';view.appendChild(marker);}if(!respawnHud){respawnHud=document.createElement("div");respawnHud.id="vsRespawnHud";respawnHud.hidden=true;respawnHud.setAttribute("role","status");respawnHud.setAttribute("aria-live","polite");respawnHud.innerHTML='<strong>DESTROYED</strong><span>RESPAWN 2.2s</span><em><i></i></em>';view.appendChild(respawnHud);}if(!explosionFlash){explosionFlash=document.createElement("div");explosionFlash.id="vsExplosionFlash";explosionFlash.setAttribute("aria-hidden","true");view.appendChild(explosionFlash);}if(!beaconMarker){beaconMarker=document.createElement("div");beaconMarker.id="vsBeaconMarker";beaconMarker.hidden=true;beaconMarker.innerHTML='<i>▲</i><strong>TARGET</strong><small>YOU · 0 m</small>';view.appendChild(beaconMarker);}if(view.dataset.vsBeaconTapInstalled!=="1"){view.dataset.vsBeaconTapInstalled="1";view.addEventListener("flightfiredoubletap",handleBeaconFireDoubleTap);view.addEventListener("pointerup",handleBeaconPointerUp,{passive:true});}bindCombatHudObserver();return true;}

export function installVsCombatPresentation(){if(installed)return;installed=true;const style=document.createElement("style");style.dataset.vsCombatPresentation="v4";style.textContent=`
#vsEnemyMarker{position:absolute;z-index:13;left:0;top:0;width:116px;height:64px;pointer-events:none;will-change:transform;filter:drop-shadow(0 2px 3px #000) drop-shadow(0 0 8px #ff321c88);font-family:system-ui,-apple-system,sans-serif;text-align:center;color:#fff;transform-origin:50% 50%}#vsEnemyMarker[hidden]{display:none!important}#vsEnemyMarker .vs-enemy-reticle{position:absolute;left:50%;top:35px;width:28px;height:28px;transform:translate(-50%,-50%) rotate(45deg);border:2px solid #ff4c32;box-shadow:0 0 0 1px #260000,0 0 14px #ff3b22aa,inset 0 0 10px #ff3b2244;background:#2100001f}#vsEnemyMarker strong{position:absolute;left:0;right:0;top:0;font:950 10px/1 system-ui,-apple-system,sans-serif;letter-spacing:.12em;color:#ff765f;text-shadow:0 1px 2px #000,0 0 7px #ff2a18}#vsEnemyMarker small{position:absolute;left:0;right:0;top:13px;font:850 8px/1 system-ui,-apple-system,sans-serif;letter-spacing:.04em;color:#fff;background:#120706e8;border:1px solid #ff543c88;border-radius:7px;padding:3px 4px;white-space:nowrap}#vsEnemyMarker .vs-enemy-hp{position:absolute;left:22px;right:22px;top:27px;height:3px;border-radius:3px;overflow:hidden;background:#3b0808;box-shadow:0 0 0 1px #0009}#vsEnemyMarker .vs-enemy-hp>b{display:block;width:100%;height:100%;transform-origin:left center;background:linear-gradient(90deg,#ff2f20,#ffad4e);box-shadow:0 0 6px #ff3b22}#vsEnemyMarker .vs-enemy-pointer{display:none;position:absolute;left:50%;top:28px;margin-left:-6px;margin-top:-7px;font:900 14px/1 system-ui;color:#ff4a32;text-shadow:0 0 8px #ff2600;transform-origin:50% 50%}#vsEnemyMarker.offscreen{width:106px;height:52px}#vsEnemyMarker.offscreen .vs-enemy-reticle,#vsEnemyMarker.offscreen .vs-enemy-hp{display:none}#vsEnemyMarker.offscreen .vs-enemy-pointer{display:block}#vsEnemyMarker.offscreen strong{top:25px}#vsEnemyMarker.offscreen small{top:36px;background:#160807ef}#vsEnemyMarker.dead strong,#vsEnemyMarker.dead small{color:#ffc070}#vsEnemyMarker.signal-hold strong,#vsEnemyMarker.signal-hold small{color:#ffd36e}#vsEnemyMarker.signal-hold .vs-enemy-reticle{border-color:#ffc44d;box-shadow:0 0 0 1px #2b1b00,0 0 14px #ffb51c99,inset 0 0 10px #ffb51c33}
#vsBeaconMarker{position:absolute;z-index:12;left:0;top:0;width:106px;height:44px;pointer-events:none;will-change:transform;filter:drop-shadow(0 1px 3px #000) drop-shadow(0 0 9px #35dfff99);font-family:system-ui,-apple-system,sans-serif;text-align:center;color:#dffcff}#vsBeaconMarker[hidden]{display:none!important}#vsBeaconMarker strong{display:block;font:950 10px/1 system-ui,-apple-system,sans-serif;letter-spacing:.13em;color:#7eeeff;text-shadow:0 0 8px #2edcff}#vsBeaconMarker small{display:block;margin-top:3px;font:850 8px/1 system-ui,-apple-system,sans-serif;white-space:nowrap;background:#061823e8;border:1px solid #55e6ff88;border-radius:7px;padding:3px 4px}#vsBeaconMarker>i{display:none;position:absolute;left:50%;top:-12px;margin-left:-6px;font:900 14px/1 system-ui;color:#60e9ff;text-shadow:0 0 8px #28dfff;transform-origin:50% 50%}#vsBeaconMarker.offscreen>i{display:block}#vsBeaconMarker.offscreen strong{margin-top:12px}
#vsRespawnHud{position:absolute;z-index:16;left:50%;top:45%;transform:translate(-50%,-50%);min-width:min(72vw,290px);padding:14px 20px;border-radius:14px;border:1px solid #ff5a42aa;background:#180807e8;box-shadow:0 8px 35px #000b,0 0 28px #ff351b38;color:#fff;text-align:center;pointer-events:none;font-family:system-ui,-apple-system,sans-serif}#vsRespawnHud[hidden]{display:none!important}#vsRespawnHud strong{display:block;font:950 25px/.95 system-ui,-apple-system,sans-serif;letter-spacing:.08em;color:#ff6650;text-shadow:0 0 14px #ff2e1d88}#vsRespawnHud span{display:block;margin-top:8px;font:900 13px/1 system-ui,-apple-system,sans-serif;letter-spacing:.12em;color:#fff;font-variant-numeric:tabular-nums}#vsRespawnHud em{display:block;height:4px;margin-top:9px;border-radius:4px;overflow:hidden;background:#3b0d0b}#vsRespawnHud em>i{display:block;width:100%;height:100%;transform-origin:left center;background:linear-gradient(90deg,#ff3824,#ffc35b)}#vsRespawnHud.enemy{top:29%;min-width:min(58vw,240px);padding:10px 16px;background:#0b1119e8;border-color:#ff744f88}#vsRespawnHud.enemy strong{font-size:17px}#vsRespawnHud.enemy span{font-size:10px;margin-top:5px}#vsExplosionFlash{position:absolute;z-index:15;inset:0;pointer-events:none;opacity:0;background:radial-gradient(circle at center,#fff6bd 0%,#ff7a2d55 22%,#ff2a1600 67%);mix-blend-mode:screen}#vsExplosionFlash.pulse{animation:vsExplosionFlash .48s ease-out both}#vsExplosionFlash.local{background:radial-gradient(circle at center,#fff 0%,#ff4c2b99 20%,#a8000038 58%,transparent 78%)}@keyframes vsExplosionFlash{0%{opacity:.92}35%{opacity:.46}100%{opacity:0}}@media(max-height:340px){#vsEnemyMarker{width:102px;height:56px}#vsEnemyMarker strong{font-size:9px}#vsEnemyMarker small{font-size:7px}#vsRespawnHud{top:43%;padding:10px 16px}#vsRespawnHud strong{font-size:20px}#vsRespawnHud span{font-size:11px}}`;
document.head.appendChild(style);if(!attachUi()){const observer=new MutationObserver(()=>{if(attachUi())observer.disconnect();});observer.observe(document.documentElement,{childList:true,subtree:true});}document.addEventListener("pointerdown",primeAudio,{passive:true,capture:true});document.addEventListener("touchstart",primeAudio,{passive:true,capture:true});requestAnimationFrame(animationLoop);}
