import * as THREE from "three";
import {loadAudioSettings} from "./audio_settings.mjs";

const STALE_PEER_MS=1400;
const PRESENTATION_MS=1000/30;
const RESPAWN_RADIUS_MIN_M=12;
const RESPAWN_RADIUS_MAX_M=30;
const INITIAL_SPAWN_RADIUS_M=18;
const EARTH_RADIUS_M=6378137;
const MOBILE_WORLD_COLLISION_SYNC_MS=1400;
const PEER_MATERIAL_REFRESH_MS=300;
const MOBILE_RE=/(?:android|iphone|ipad|ipod|macintosh.*mobile)/i;
let installed=false;
let audioContext=null;
let explosionNoiseBuffer=null;
let marker=null;
let respawnHud=null;
let explosionFlash=null;
let enhancedPeerMesh=null;
let combatHudNode=null;
let combatHudObserver=null;
let previousLocalDead=false;
let previousPeerDead=false;
let soundEventCount=0;
let audioStartedCount=0;
let lastPresentationMs=-Infinity;
let lastPeerMaterialMs=-Infinity;
const worldPosition=new THREE.Vector3();
const cameraPosition=new THREE.Vector3();
const ownPosition=new THREE.Vector3();
const projected=new THREE.Vector3();
const cameraSpace=new THREE.Vector3();

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function clamp(value,min,max){return Math.max(min,Math.min(max,value));}
function setText(node,value){const text=String(value??"");if(node&&node.textContent!==text)node.textContent=text;}
function randomRespawnOffset(){const min2=RESPAWN_RADIUS_MIN_M**2,max2=RESPAWN_RADIUS_MAX_M**2,r=Math.sqrt(min2+Math.random()*(max2-min2)),a=Math.random()*Math.PI*2;return{x:Math.cos(a)*r,y:Math.sin(a)*r,r};}
function metersToLngLat(originLon,originLat,eastM,northM){const latitude=originLat+northM/EARTH_RADIUS_M*180/Math.PI,longitude=originLon+eastM/(EARTH_RADIUS_M*Math.max(.01,Math.cos(originLat*Math.PI/180)))*180/Math.PI;return[longitude,latitude];}

function prepareExplosionNoise(ctx){if(explosionNoiseBuffer||!ctx)return explosionNoiseBuffer;const duration=.82,samples=Math.max(1,Math.floor(ctx.sampleRate*duration)),buffer=ctx.createBuffer(1,samples,ctx.sampleRate),data=buffer.getChannelData(0);let seed=0x45a70d1;for(let i=0;i<samples;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const noise=(seed/0xffffffff)*2-1,t=i/samples;data[i]=noise*Math.pow(1-t,2.35);}explosionNoiseBuffer=buffer;const view=viewport();if(view)view.dataset.vsExplosionAudioReady="1";return buffer;}
function ensureAudio(){const AudioCtor=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AudioCtor)return null;try{audioContext??=new AudioCtor({latencyHint:"interactive"});}catch{return null;}const ready=()=>{prepareExplosionNoise(audioContext);const view=viewport();if(view)view.dataset.vsExplosionAudioState=audioContext.state;};if(audioContext.state==="suspended")audioContext.resume().then(ready).catch(()=>{});else ready();return audioContext;}
function primeAudio(){ensureAudio();}
function playExplosion(local=false){const settings=loadAudioSettings(),level=settings.soundEnabled?settings.fxVolume/100:0;if(level<=0)return false;const view=viewport();soundEventCount++;if(view)view.dataset.vsExplosionSoundCount=String(soundEventCount);const ctx=ensureAudio();try{navigator.vibrate?.(local?[70,35,120]:[65]);}catch{}if(!ctx||ctx.state!=="running"||!explosionNoiseBuffer){if(view)view.dataset.vsExplosionAudioState=ctx?.state||"unavailable";return false;}try{const now=ctx.currentTime,duration=.82,noise=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),noiseGain=ctx.createGain();noise.buffer=explosionNoiseBuffer;filter.type="lowpass";filter.frequency.setValueAtTime(local?1150:900,now);filter.frequency.exponentialRampToValueAtTime(120,now+duration);noiseGain.gain.setValueAtTime(.0001,now);noiseGain.gain.exponentialRampToValueAtTime((local?.52:.38)*level,now+.012);noiseGain.gain.exponentialRampToValueAtTime(.0001,now+duration);noise.connect(filter).connect(noiseGain).connect(ctx.destination);const boom=ctx.createOscillator(),boomGain=ctx.createGain();boom.type="sine";boom.frequency.setValueAtTime(local?105:92,now);boom.frequency.exponentialRampToValueAtTime(34,now+.55);boomGain.gain.setValueAtTime(.0001,now);boomGain.gain.exponentialRampToValueAtTime((local?.58:.43)*level,now+.008);boomGain.gain.exponentialRampToValueAtTime(.0001,now+.72);boom.connect(boomGain).connect(ctx.destination);const crack=ctx.createOscillator(),crackGain=ctx.createGain();crack.type="triangle";crack.frequency.setValueAtTime(210,now);crack.frequency.exponentialRampToValueAtTime(58,now+.18);crackGain.gain.setValueAtTime(.0001,now);crackGain.gain.exponentialRampToValueAtTime(.17*level,now+.004);crackGain.gain.exponentialRampToValueAtTime(.0001,now+.22);crack.connect(crackGain).connect(ctx.destination);noise.start(now);noise.stop(now+duration);boom.start(now);boom.stop(now+.74);crack.start(now);crack.stop(now+.24);audioStartedCount++;if(view){view.dataset.vsExplosionAudioStartedCount=String(audioStartedCount);view.dataset.vsExplosionAudioState=ctx.state;}return true;}catch{return false;}}
function flashExplosion(local=false){if(!explosionFlash)return;explosionFlash.classList.remove("pulse","local");void explosionFlash.offsetWidth;if(local)explosionFlash.classList.add("local");explosionFlash.classList.add("pulse");}
function enhancePeerVisual(currentBridge,now=performance.now()){const peer=currentBridge?.vsPeerMesh;if(!peer)return;if(peer===enhancedPeerMesh&&now-lastPeerMaterialMs<PEER_MATERIAL_REFRESH_MS)return;enhancedPeerMesh=peer;lastPeerMaterialMs=now;for(const child of [...peer.children])if(child?.userData?.vsReadableGlow)child.removeFromParent();peer.traverse(node=>{if(!node?.isMesh||!node.userData?.vsReadableVisual)return;const material=node.material;if(material?.emissive&&material?.color){material.emissive.copy?.(material.color);material.emissiveIntensity=.28;}if(material){material.roughness=.44;material.metalness=.18;}});const view=viewport();if(view)view.dataset.vsPeerVisualStyle="clean-player-color";}
function ownDrone(currentBridge){return currentBridge?.airframeFor?.(currentBridge.threeScene)||currentBridge?.airframe||null;}
function ownDroneWorldPosition(currentBridge){const airframe=ownDrone(currentBridge);if(airframe?.getWorldPosition){airframe.updateWorldMatrix?.(true,false);airframe.getWorldPosition(ownPosition);return ownPosition;}if(airframe?.position){ownPosition.copy(airframe.position);return ownPosition;}ownPosition.copy(cameraPosition);return ownPosition;}
function latchLocalDeath(currentBridge){clearTimeout(currentBridge?.vsRespawnTimer);if(currentBridge)currentBridge.vsRespawnTimer=0;try{document.getElementById("soloKill")?.click();}catch{}try{viewport()?.dispatchEvent(new Event("pointercancel"));}catch{}const airframe=ownDrone(currentBridge);if(airframe)airframe.visible=false;const view=viewport();if(view){view.dataset.vsDeathLatched="1";view.dataset.vsWeaponsLocked="1";}}
function restoreLocalDrone(currentBridge){const airframe=ownDrone(currentBridge);if(airframe)airframe.visible=true;const view=viewport();if(view){delete view.dataset.vsDeathLatched;delete view.dataset.vsWeaponsLocked;}}
function installTrainingOffsetAdapter(currentBridge){if(!currentBridge||currentBridge.__vsRespawnOffsetAdapter)return;currentBridge.__vsRespawnOffsetAdapter=true;currentBridge.__vsRespawnLocalOffset=[0,0];const baseApply=currentBridge.applyVsPose?.bind(currentBridge);if(baseApply)currentBridge.applyVsPose=pose=>{const offset=currentBridge.__vsRespawnLocalOffset;if(!pose?.g&&Array.isArray(pose?.p)&&Array.isArray(offset)&&(offset[0]||offset[1]))pose={...pose,p:[Number(pose.p[0])-offset[0],Number(pose.p[1])-offset[1],Number(pose.p[2])]};return baseApply(pose);};}
function installSessionOffsetAdapter(currentBridge){const session=currentBridge?.vsSession;if(!session||session.__vsRespawnOffsetAdapter||typeof session.setPose!=="function")return;session.__vsRespawnOffsetAdapter=true;const baseSetPose=session.setPose.bind(session);session.setPose=pose=>{const offset=currentBridge.__vsRespawnLocalOffset;if(!pose?.g&&Array.isArray(pose?.p)&&Array.isArray(offset)&&(offset[0]||offset[1]))pose={...pose,p:[Number(pose.p[0])+offset[0],Number(pose.p[1])+offset[1],Number(pose.p[2])]};return baseSetPose(pose);};}
function installMobileWorldPerfGuard(currentBridge){if(!currentBridge||currentBridge.__vsMobileWorldPerfGuard||!MOBILE_RE.test(navigator.userAgent||"")||typeof currentBridge.syncBuildingCollisions!=="function")return;currentBridge.__vsMobileWorldPerfGuard=true;const base=currentBridge.syncBuildingCollisions.bind(currentBridge);let last=-Infinity;currentBridge.syncBuildingCollisions=force=>{const now=performance.now();if(!force&&now-last<MOBILE_WORLD_COLLISION_SYNC_MS)return false;last=now;return base(Boolean(force));};const view=viewport();if(view)view.dataset.vsMobileCollisionSyncMs=String(MOBILE_WORLD_COLLISION_SYNC_MS);}
function relocateRespawnOrigin(currentBridge,offset){const airframe=ownDrone(currentBridge),p=airframe?.position;if(currentBridge?.active&&Number.isFinite(currentBridge.originLon)&&Number.isFinite(currentBridge.originLat)&&p){const [currentLon,currentLat]=metersToLngLat(currentBridge.originLon,currentBridge.originLat,Number(p.x)||0,Number(p.y)||0),[nextLon,nextLat]=metersToLngLat(currentLon,currentLat,offset.x,offset.y);currentBridge.originLon=nextLon;currentBridge.originLat=nextLat;currentBridge.lastMapSyncMs=-Infinity;currentBridge.lastMapView=null;currentBridge.lastViewportSize="";currentBridge.minimapLastQueryMs=-Infinity;currentBridge.minimapLastDrawMs=-Infinity;currentBridge.buildingCollisionDirty=true;currentBridge.clearBuildingCollisions?.();currentBridge.map?.jumpTo?.({center:[nextLon,nextLat]});const view=viewport();if(view){view.dataset.worldLongitude=String(nextLon);view.dataset.worldLatitude=String(nextLat);view.dataset.vsRespawnMode="world-origin";}return;}
  installTrainingOffsetAdapter(currentBridge);installSessionOffsetAdapter(currentBridge);const old=Array.isArray(currentBridge.__vsRespawnLocalOffset)?currentBridge.__vsRespawnLocalOffset:[0,0],x=(Number(p?.x)||0)+old[0]+offset.x,y=(Number(p?.y)||0)+old[1]+offset.y;currentBridge.__vsRespawnLocalOffset=[x,y];const view=viewport();if(view)view.dataset.vsRespawnMode="canonical-offset";
}
function participantIdentity(currentBridge){const session=currentBridge?.vsSession,active=session?.active||session,view=viewport(),self=String(session?.getSelfId?.()||active?.getSelfId?.()||view?.dataset.vsSelfId||"");let peers=[];try{peers=session?.getPeerIds?.()||active?.getPeerIds?.()||[];}catch{}if(!Array.isArray(peers)||!peers.length){const primary=String(active?.primaryPeerId||active?.peerId||"");if(primary)peers=[primary];}const ids=[self,...peers.map(String)].filter(Boolean).filter((id,index,list)=>list.indexOf(id)===index).sort();return{self,ids};}
function ensureInitialSpawnSeparation(currentBridge){if(!currentBridge?.vsConnected){currentBridge.__vsInitialSpawnApplied=false;return false;}if(currentBridge.__vsInitialSpawnApplied)return false;const{self,ids}=participantIdentity(currentBridge);if(!self||ids.length<2)return false;const index=Math.max(0,ids.indexOf(self)),angle=-Math.PI/2+index*Math.PI*2/ids.length,offset={x:Math.cos(angle)*INITIAL_SPAWN_RADIUS_M,y:Math.sin(angle)*INITIAL_SPAWN_RADIUS_M,r:INITIAL_SPAWN_RADIUS_M};currentBridge.__vsInitialSpawnApplied=true;relocateRespawnOrigin(currentBridge,offset);document.getElementById("soloReset")?.click();installSessionOffsetAdapter(currentBridge);currentBridge.vsLocalPoseSample=null;const view=viewport();if(view){view.dataset.vsInitialSpawnSeparated="1";view.dataset.vsInitialSpawnPlayers=String(ids.length);view.dataset.vsInitialSpawnOffsetM=`${offset.x.toFixed(2)},${offset.y.toFixed(2)}`;view.dataset.vsInitialSpawnSeparationM=String(INITIAL_SPAWN_RADIUS_M*2);}return true;}
function requestLocalRespawn(){const currentBridge=bridge();if(!currentBridge?.vsLocalDead)return false;clearTimeout(currentBridge.vsRespawnTimer);currentBridge.vsRespawnTimer=0;const offset=randomRespawnOffset();relocateRespawnOrigin(currentBridge,offset);document.getElementById("soloReset")?.click();installSessionOffsetAdapter(currentBridge);currentBridge.vsLocalDead=false;currentBridge.vsLocalHealth=100;currentBridge.vsLocalPoseSample=null;currentBridge.updateVsCombatHud?.(true);currentBridge.vsSession?.sendCombat?.({type:"respawn",hp:100});restoreLocalDrone(currentBridge);const view=viewport();if(view){view.dataset.vsManualRespawns=String((Number(view.dataset.vsManualRespawns)||0)+1);view.dataset.vsRespawnRadiusM=offset.r.toFixed(2);view.dataset.vsRespawnOffsetM=`${offset.x.toFixed(2)},${offset.y.toFixed(2)}`;}renderPresentation(performance.now(),true);return true;}
function updateEnemyMarker(currentBridge,now){if(!marker)return;const peer=currentBridge?.vsPeerMesh,camera=currentBridge?.threeCamera,view=viewport(),fresh=Number.isFinite(currentBridge?.vsPeerLastPoseMs)&&now-currentBridge.vsPeerLastPoseMs<STALE_PEER_MS;if(!currentBridge?.vsConnected||!peer||!camera||!view||(!fresh&&!currentBridge.vsPeerDead)){marker.hidden=true;return;}const rect=view.getBoundingClientRect();if(rect.width<1||rect.height<1){marker.hidden=true;return;}peer.updateWorldMatrix?.(true,false);camera.updateMatrixWorld?.(true);peer.getWorldPosition(worldPosition);camera.getWorldPosition(cameraPosition);projected.copy(worldPosition).project(camera);cameraSpace.copy(worldPosition).applyMatrix4(camera.matrixWorldInverse);const inFront=cameraSpace.z<0;let nx=projected.x,ny=projected.y;if(!inFront){nx=-nx;ny=-ny;}const marginX=Math.min(52,rect.width*.10),marginY=Math.min(42,rect.height*.14),halfW=Math.max(1,rect.width/2-marginX),halfH=Math.max(1,rect.height/2-marginY);let sx=nx*rect.width/2,sy=-ny*rect.height/2;const scale=Math.min(1,halfW/Math.max(1,Math.abs(sx)),halfH/Math.max(1,Math.abs(sy)));sx*=scale;sy*=scale;const x=rect.width/2+sx,y=rect.height/2+sy,onScreen=inFront&&Math.abs(projected.x)<.94&&Math.abs(projected.y)<.88&&projected.z>-1&&projected.z<1;marker.hidden=false;marker.classList.toggle("offscreen",!onScreen);marker.classList.toggle("dead",Boolean(currentBridge.vsPeerDead));marker.style.transform=`translate3d(${x.toFixed(1)}px,${y.toFixed(1)}px,0) translate(-50%,-50%)`;const pointer=marker.querySelector(".vs-enemy-pointer");if(pointer)pointer.style.transform=`rotate(${(Math.atan2(sy,sx)*180/Math.PI+90).toFixed(1)}deg)`;const distance=Math.max(0,ownDroneWorldPosition(currentBridge).distanceTo(worldPosition)),health=clamp(Math.round(Number(currentBridge.vsPeerHealth)||0),0,100),label=marker.querySelector("strong"),detail=marker.querySelector("small"),hpFill=marker.querySelector(".vs-enemy-hp>b");setText(label,currentBridge.vsPeerDead?"DOWN":"ENEMY");setText(detail,currentBridge.vsPeerDead?"WAITING RESET":`${health} HP · ${distance<100?distance.toFixed(0):Math.round(distance)} m`);if(hpFill)hpFill.style.transform=`scaleX(${health/100})`;view.dataset.vsEnemyMarker=onScreen?"onscreen":"offscreen";view.dataset.vsEnemyDistanceM=distance.toFixed(2);view.dataset.vsEnemyHealth=String(health);}
function updateRespawnHud(currentBridge){if(!respawnHud)return;const view=viewport(),local=Boolean(currentBridge?.vsLocalDead),enemy=!local&&Boolean(currentBridge?.vsPeerDead),state=local?"local":enemy?"enemy":"none";respawnHud.hidden=state==="none";respawnHud.classList.toggle("enemy",enemy);respawnHud.classList.toggle("local",local);const strong=respawnHud.querySelector("strong"),small=respawnHud.querySelector("span"),button=respawnHud.querySelector("button");if(local){setText(strong,"DESTROYED");setText(small,"RESET SIM TO RESPAWN NEARBY");}else if(enemy){setText(strong,"ENEMY DESTROYED");setText(small,"WAITING FOR RESET");}if(button)button.hidden=!local;if(view)view.dataset.vsRespawnState=state;}
function renderPresentation(now=performance.now(),force=false){if(!force&&now-lastPresentationMs<PRESENTATION_MS)return;lastPresentationMs=now;const currentBridge=bridge();if(currentBridge){installTrainingOffsetAdapter(currentBridge);installSessionOffsetAdapter(currentBridge);installMobileWorldPerfGuard(currentBridge);ensureInitialSpawnSeparation(currentBridge);enhancePeerVisual(currentBridge,now);const localDead=Boolean(currentBridge.vsLocalDead),peerDead=Boolean(currentBridge.vsPeerDead);if(localDead&&!previousLocalDead){latchLocalDeath(currentBridge);playExplosion(true);flashExplosion(true);}if(peerDead&&!previousPeerDead){playExplosion(false);flashExplosion(false);}if(!localDead&&previousLocalDead)restoreLocalDrone(currentBridge);previousLocalDead=localDead;previousPeerDead=peerDead;updateEnemyMarker(currentBridge,now);updateRespawnHud(currentBridge);}else{if(marker)marker.hidden=true;if(respawnHud)respawnHud.hidden=true;}}
function bindCombatHudObserver(){const hud=document.getElementById("vsCombatHud");if(!hud||hud===combatHudNode)return;combatHudObserver?.disconnect();combatHudNode=hud;combatHudObserver=new MutationObserver(()=>{try{renderPresentation(performance.now(),true);}catch(error){const view=viewport();if(view)view.dataset.vsCombatPresentationError=String(error?.message||error);}});combatHudObserver.observe(hud,{childList:true,characterData:true,subtree:true});}
function animationLoop(now){try{bindCombatHudObserver();renderPresentation(now);}catch(error){const view=viewport();if(view)view.dataset.vsCombatPresentationError=String(error?.message||error);}finally{requestAnimationFrame(animationLoop);}}
function attachUi(){const view=viewport();if(!view)return false;if(!marker){marker=document.createElement("div");marker.id="vsEnemyMarker";marker.hidden=true;marker.setAttribute("aria-live","off");marker.innerHTML='<i class="vs-enemy-reticle"></i><i class="vs-enemy-pointer">▲</i><strong>ENEMY</strong><small>100 HP</small><i class="vs-enemy-hp"><b></b></i>';view.appendChild(marker);}if(!respawnHud){respawnHud=document.createElement("div");respawnHud.id="vsRespawnHud";respawnHud.hidden=true;respawnHud.setAttribute("role","status");respawnHud.setAttribute("aria-live","polite");respawnHud.innerHTML='<strong>DESTROYED</strong><span>RESET SIM TO RESPAWN NEARBY</span><button type="button">RESET SIM</button>';respawnHud.querySelector("button")?.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();requestLocalRespawn();});view.appendChild(respawnHud);}if(!explosionFlash){explosionFlash=document.createElement("div");explosionFlash.id="vsExplosionFlash";explosionFlash.setAttribute("aria-hidden","true");view.appendChild(explosionFlash);}bindCombatHudObserver();return true;}

export function installVsCombatPresentation(){if(installed)return;installed=true;const style=document.createElement("style");style.dataset.vsCombatPresentation="v5";style.textContent=`
#vsEnemyMarker{position:absolute;z-index:13;left:0;top:0;width:86px;height:72px;pointer-events:none;will-change:transform;filter:drop-shadow(0 1px 1px #0009);font-family:system-ui,-apple-system,sans-serif;text-align:center;color:#fff;transform-origin:50% 50%}#vsEnemyMarker[hidden]{display:none!important}#vsEnemyMarker .vs-enemy-reticle{position:absolute;left:50%;top:50%;width:30px;height:30px;transform:translate(-50%,-50%) rotate(45deg);border:.75px solid #ff775fcc;border-radius:1px;box-shadow:0 0 3px #ff3b2238;background:transparent}#vsEnemyMarker strong{position:absolute;left:0;right:0;top:1px;font:900 8px/1 system-ui,-apple-system,sans-serif;letter-spacing:.10em;color:#ff967e;text-shadow:0 1px 2px #000}#vsEnemyMarker small{position:absolute;left:-10px;right:-10px;top:58px;font:750 7px/1 system-ui,-apple-system,sans-serif;letter-spacing:.02em;color:#f8f8f8;white-space:nowrap;text-shadow:0 1px 2px #000}#vsEnemyMarker .vs-enemy-hp{position:absolute;left:28px;right:28px;top:68px;height:1px;overflow:hidden;background:#3b080888}#vsEnemyMarker .vs-enemy-hp>b{display:block;width:100%;height:100%;transform-origin:left center;background:#ff694f}#vsEnemyMarker .vs-enemy-pointer{display:none;position:absolute;left:50%;top:20px;margin-left:-5px;margin-top:-6px;font:800 12px/1 system-ui;color:#ff765f;text-shadow:0 1px 3px #000;transform-origin:50% 50%}#vsEnemyMarker.offscreen{width:76px;height:40px}#vsEnemyMarker.offscreen .vs-enemy-reticle,#vsEnemyMarker.offscreen .vs-enemy-hp{display:none}#vsEnemyMarker.offscreen .vs-enemy-pointer{display:block}#vsEnemyMarker.offscreen strong{top:22px}#vsEnemyMarker.offscreen small{top:31px}#vsEnemyMarker.dead{opacity:.72}#vsEnemyMarker.dead strong,#vsEnemyMarker.dead small{color:#ffc070}
#vsRespawnHud{position:absolute;z-index:18;left:50%;top:50%;transform:translate(-50%,-50%);min-width:min(78vw,330px);padding:20px 24px;border-radius:16px;border:1px solid #ff5a42bb;background:#130504f2;box-shadow:0 12px 44px #000d,0 0 34px #ff351b33;color:#fff;text-align:center;pointer-events:none;font-family:system-ui,-apple-system,sans-serif}#vsRespawnHud[hidden]{display:none!important}#vsRespawnHud strong{display:block;font:950 29px/.95 system-ui,-apple-system,sans-serif;letter-spacing:.09em;color:#ff6650;text-shadow:0 0 16px #ff2e1d88}#vsRespawnHud span{display:block;margin-top:9px;font:850 11px/1.25 system-ui,-apple-system,sans-serif;letter-spacing:.10em;color:#fff}#vsRespawnHud button{margin-top:15px;min-width:150px;padding:11px 18px;border-radius:999px;border:1px solid #ffc3b6;background:#d53c27;color:#fff;font:900 13px/1 system-ui,-apple-system,sans-serif;letter-spacing:.06em;pointer-events:auto;touch-action:manipulation;box-shadow:0 5px 18px #0008}#vsRespawnHud button[hidden]{display:none!important}#vsRespawnHud.enemy{top:28%;min-width:min(56vw,230px);padding:10px 14px;background:#091018e8;border-color:#ff744f66;box-shadow:0 5px 20px #0009}#vsRespawnHud.enemy strong{font-size:16px}#vsRespawnHud.enemy span{font-size:9px;margin-top:5px;color:#d8e1e8}#vsExplosionFlash{position:absolute;z-index:15;inset:0;pointer-events:none;opacity:0;background:radial-gradient(circle at center,#fff6bd 0%,#ff7a2d55 22%,#ff2a1600 67%);mix-blend-mode:screen}#vsExplosionFlash.pulse{animation:vsExplosionFlash .48s ease-out both}#vsExplosionFlash.local{background:radial-gradient(circle at center,#fff 0%,#ff4c2b99 20%,#a8000038 58%,transparent 78%)}@keyframes vsExplosionFlash{0%{opacity:.92}35%{opacity:.46}100%{opacity:0}}@media(max-height:340px){#vsEnemyMarker{width:78px;height:64px}#vsEnemyMarker .vs-enemy-reticle{width:27px;height:27px}#vsEnemyMarker small{top:52px}#vsEnemyMarker .vs-enemy-hp{top:61px}#vsRespawnHud{padding:14px 18px}#vsRespawnHud strong{font-size:23px}#vsRespawnHud span{font-size:9px}#vsRespawnHud button{margin-top:10px;padding:9px 16px}}
`;
document.head.appendChild(style);if(!attachUi()){const observer=new MutationObserver(()=>{if(attachUi())observer.disconnect();});observer.observe(document.documentElement,{childList:true,subtree:true});}document.addEventListener("pointerdown",primeAudio,{passive:true,capture:true});document.addEventListener("touchstart",primeAudio,{passive:true,capture:true});requestAnimationFrame(animationLoop);}
