import * as THREE from "three";
import {VsPoseTimeline} from "./vs_pose_sync.mjs";
import {VS_PEER_EVENT,VS_POSE_EVENT,VS_GAME_EVENT,VS_FX_EVENT} from "./lan_vs.mjs";

const VISUAL_SCALE=12;
const HITBOX_PADDING=1.16;
const STALE_MS=3000;
const MAX_PLAYERS=9;
const PALETTE=[0x29d6ff,0xff6b35,0x8cf43f,0xff4fd8,0xffd83d,0x9b7bff,0x24e6a1,0xff405f,0x43a8ff,0xff9f1c,0x7ce7ff,0xd6ff4b];
const peers=new Map(),health=new Map(),seenHits=new Set(),seenStates=new Set();
const tempPosition=new THREE.Vector3(),tempCamera=new THREE.Vector3(),tempProjected=new THREE.Vector3(),tempCameraSpace=new THREE.Vector3();
let installed=false,lastSession=null,selfId="",authorityId="",primaryId="",shotSeq=0,kills=0,deaths=0,lastLocalDead=false,lastRender=0,raf=0;
let style=null,tracerGeometry=null,explosionGeometry=null;
const remoteTracers=[],remoteExplosions=[];

function bridge(){return globalThis.__arondightRealWorld||null;}
function viewport(){return document.getElementById("viewport");}
function session(){return bridge()?.vsSession||null;}
function activeSession(){return session()?.active||session()||null;}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function hashId(id){let h=2166136261;for(const c of String(id||"")){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function assignments(){const ids=[selfId,...peers.keys()].filter(Boolean).sort(),used=new Set(),out=new Map();for(const id of ids){let i=hashId(id)%PALETTE.length;while(used.has(i))i=(i+1)%PALETTE.length;used.add(i);out.set(id,PALETTE[i]);}return out;}
function colorFor(id){return assignments().get(id)||PALETTE[hashId(id)%PALETTE.length];}
function cssColor(hex){return`#${Number(hex||0).toString(16).padStart(6,"0")}`;}
function localOffset(){const b=bridge(),o=b?.__vsRespawnLocalOffset;return !b?.active&&Array.isArray(o)&&o.length===2?[Number(o[0])||0,Number(o[1])||0]:[0,0];}
function canonicalToLocal(p){const o=localOffset();return[Number(p?.[0])||0-o[0],Number(p?.[1])||0-o[1],Number(p?.[2])||0];}
function localToCanonical(p){const o=localOffset();return[Number(p?.[0])||0+o[0],Number(p?.[1])||0+o[1],Number(p?.[2])||0];}
function participantIds(){return[selfId,...peers.keys()].filter(Boolean).sort();}
function updateIdentity(){const s=session(),a=activeSession();selfId=String(s?.getSelfId?.()||a?.getSelfId?.()||selfId||"");authorityId=String(s?.getAuthorityId?.()||a?.getAuthorityId?.()||participantIds()[0]||"");primaryId=String(a?.primaryPeerId||a?.peerId||primaryId||"");if(selfId&&!health.has(selfId))health.set(selfId,100);const view=viewport();if(view){view.dataset.vsSelfId=selfId;view.dataset.vsAuthorityId=authorityId;view.dataset.vsPeerCount=String(peers.size);view.dataset.vsPlayerCount=String(Math.min(MAX_PLAYERS,peers.size+1));view.dataset.vsLocalColor=cssColor(colorFor(selfId));view.dataset.vsPlayerColors=JSON.stringify(Object.fromEntries([...assignments()].map(([id,c])=>[id,cssColor(c)])));}}
function applyMaterialColor(root,color){root?.traverse?.(node=>{if(!node?.isMesh||node.userData?.vsCombatHitbox)return;const m=node.material;if(m?.color?.setHex)m.color.setHex(color);if(m?.emissive?.setHex){m.emissive.setHex(color);m.emissiveIntensity=Math.max(Number(m.emissiveIntensity)||0,1.6);}});root?.traverse?.(node=>{if(node?.isSprite&&node.material?.color?.setHex)node.material.color.setHex(color);});}
function refreshColors(){const map=assignments();for(const r of peers.values()){r.color=map.get(r.id)||r.color;applyMaterialColor(r.mesh,r.color);if(r.marker)r.marker.style.setProperty("--vs-player-color",cssColor(r.color));}const b=bridge(),own=b?.airframeFor?.(b.threeScene)||b?.airframe;if(own&&selfId)applyMaterialColor(own,map.get(selfId)||colorFor(selfId));if(b?.vsPeerMesh&&primaryId){b.vsPeerMesh.userData.vsPlayerId=primaryId;b.vsPeerMesh.userData.vsPlayerColor=map.get(primaryId)||colorFor(primaryId);applyMaterialColor(b.vsPeerMesh,b.vsPeerMesh.userData.vsPlayerColor);}}
function makeMarker(record){const view=viewport();if(!view)return null;const el=document.createElement("div");el.className="vs-player-marker";el.dataset.peerId=record.id;el.innerHTML='<i></i><strong>ENEMY</strong><small></small>';el.style.setProperty("--vs-player-color",cssColor(record.color));view.appendChild(el);return el;}
function createPeerMesh(record){const b=bridge(),scene=b?.threeScene;if(!scene)return null;const group=new THREE.Group(),material=new THREE.MeshStandardMaterial({color:record.color,emissive:record.color,emissiveIntensity:1.7,roughness:.24,metalness:.18});group.scale.setScalar(VISUAL_SCALE);const body=new THREE.Mesh(new THREE.BoxGeometry(.22,.34,.07),material);body.userData.flightFireIgnore=true;group.add(body);for(const[x,y]of[[-.19,-.19],[.19,-.19],[-.19,.19],[.19,.19]]){const arm=new THREE.Mesh(new THREE.BoxGeometry(.025,.26,.025),material);arm.position.set(x*.5,y*.5,0);arm.rotation.z=(x*y>0?1:-1)*Math.PI/4;arm.userData.flightFireIgnore=true;group.add(arm);}const hitMaterial=new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false,depthTest:false});hitMaterial.colorWrite=false;const hitbox=new THREE.Mesh(new THREE.BoxGeometry(.32*HITBOX_PADDING,.44*HITBOX_PADDING,.10*HITBOX_PADDING),hitMaterial);hitbox.userData.vsCombatHitbox=true;hitbox.userData.vsPlayerId=record.id;hitbox.userData.vsPeerHitProxy=true;group.add(hitbox);group.userData.vsPlayerId=record.id;group.userData.vsPlayerColor=record.color;group.userData.vsMultiplayerPeer=true;group.visible=false;scene.add(group);return group;}
function recordFor(id){id=String(id||"");if(!id||id===selfId)return null;let r=peers.get(id);if(!r){r={id,timeline:new VsPoseTimeline(),mesh:null,marker:null,lastPoseMs:-Infinity,health:100,dead:false,color:colorFor(id)};peers.set(id,r);health.set(id,100);r.marker=makeMarker(r);refreshColors();}return r;}
function removePeer(id){const r=peers.get(String(id||""));if(!r)return;r.mesh?.parent?.remove(r.mesh);r.marker?.remove();peers.delete(r.id);health.delete(r.id);refreshColors();}
function posePosition(pose){const b=bridge();if(Array.isArray(pose?.g)&&pose.g.length===2&&Number.isFinite(b?.originLon)&&Number.isFinite(b?.originLat)){const earth=6378137,lat0=b.originLat*Math.PI/180,north=(Number(pose.g[1])-b.originLat)*Math.PI/180*earth,east=(Number(pose.g[0])-b.originLon)*Math.PI/180*earth*Math.max(.01,Math.cos(lat0));return[east,north,Number(pose.p?.[2])||0];}return canonicalToLocal(pose?.p);}
function onPoseEvent(event){updateIdentity();const {peerId,pose}=event.detail||{};if(!peerId||!pose)return;const r=recordFor(peerId);if(!r)return;const p=posePosition(pose),packet={...pose,p};if(r.timeline.push(packet,performance.now()))r.lastPoseMs=performance.now();}
function setPrimaryCompatibility(record){const b=bridge();if(!b||record.id!==primaryId)return;if(b.vsPeerMesh&&record.mesh!==b.vsPeerMesh){if(record.mesh&&!record.mesh.userData?.vsLegacyPrimary)record.mesh.parent?.remove(record.mesh);record.mesh=b.vsPeerMesh;record.mesh.userData.vsLegacyPrimary=true;record.mesh.userData.vsPlayerId=record.id;record.mesh.userData.vsPlayerColor=record.color;applyMaterialColor(record.mesh,record.color);}b.vsPeerHealth=record.health;b.vsPeerDead=record.dead;}
function renderMarker(r,camera,view,now){const marker=r.marker;if(!marker||!r.mesh||r.dead||now-r.lastPoseMs>STALE_MS){if(marker)marker.hidden=true;return;}const rect=view.getBoundingClientRect();if(rect.width<1||rect.height<1){marker.hidden=true;return;}r.mesh.getWorldPosition(tempPosition);camera.getWorldPosition(tempCamera);tempProjected.copy(tempPosition).project(camera);tempCameraSpace.copy(tempPosition).applyMatrix4(camera.matrixWorldInverse);const inFront=tempCameraSpace.z<0;let nx=tempProjected.x,ny=tempProjected.y;if(!inFront){nx=-nx;ny=-ny;}const marginX=Math.min(42,rect.width*.08),marginY=Math.min(34,rect.height*.11),halfW=Math.max(1,rect.width/2-marginX),halfH=Math.max(1,rect.height/2-marginY),sx0=nx*rect.width/2,sy0=-ny*rect.height/2,scale=Math.min(1,halfW/Math.max(1,Math.abs(sx0)),halfH/Math.max(1,Math.abs(sy0))),x=rect.width/2+sx0*scale,y=rect.height/2+sy0*scale,onScreen=inFront&&Math.abs(tempProjected.x)<.96&&Math.abs(tempProjected.y)<.90&&tempProjected.z>-1&&tempProjected.z<1;marker.hidden=false;marker.classList.toggle("offscreen",!onScreen);marker.style.transform=`translate3d(${x.toFixed(1)}px,${y.toFixed(1)}px,0) translate(-50%,-50%)`;const own=bridge()?.airframeFor?.(bridge()?.threeScene)||bridge()?.airframe,distance=own?.position?own.position.distanceTo(tempPosition):0;marker.querySelector("strong").textContent=`P${participantIds().indexOf(r.id)+1}`;marker.querySelector("small").textContent=`${r.health} · ${distance<100?distance.toFixed(0):Math.round(distance)}m`;}
function ensureFxPools(){const scene=bridge()?.threeScene;if(!scene||tracerGeometry)return;tracerGeometry=new THREE.CylinderGeometry(.018,.018,1,6);explosionGeometry=new THREE.SphereGeometry(.12,7,5);for(let i=0;i<40;i++){const m=new THREE.MeshBasicMaterial({color:0xffd36a,transparent:true,opacity:.9,depthWrite:false,blending:THREE.AdditiveBlending}),mesh=new THREE.Mesh(tracerGeometry,m);mesh.visible=false;mesh.renderOrder=15;mesh.userData.flightFireIgnore=true;scene.add(mesh);remoteTracers.push({mesh,active:false,velocity:new THREE.Vector3(),born:0,expires:0});}for(let i=0;i<20;i++){const m=new THREE.MeshBasicMaterial({color:0xff5d2f,transparent:true,opacity:.9,depthWrite:false,blending:THREE.AdditiveBlending}),mesh=new THREE.Mesh(explosionGeometry,m);mesh.visible=false;mesh.renderOrder=16;mesh.userData.flightFireIgnore=true;scene.add(mesh);remoteExplosions.push({mesh,born:0,expires:0});}}
function spawnRemoteShot(packet,peerId){ensureFxPools();const item=remoteTracers.find(x=>!x.active)||remoteTracers[hashId(packet.id)%remoteTracers.length];item.active=true;item.born=performance.now();item.expires=item.born+1600;item.mesh.material.color.setHex(colorFor(packet.playerId||peerId));const p=canonicalToLocal(packet.from),d=packet.dir;item.mesh.position.set(...p);item.velocity.set(Number(d[0])||0,Number(d[1])||0,Number(d[2])||0).normalize().multiplyScalar(clamp(Number(packet.speed)||210,1,500));item.mesh.visible=true;}
function spawnExplosion(packet){ensureFxPools();const item=remoteExplosions.find(x=>!x.mesh.visible)||remoteExplosions[hashId(packet.id)%remoteExplosions.length],p=canonicalToLocal(packet.p);item.born=performance.now();item.expires=item.born+780;item.mesh.position.set(...p);item.mesh.scale.setScalar(1);item.mesh.material.opacity=.95;item.mesh.visible=true;}
function renderFx(now,dt){for(const item of remoteTracers){if(!item.active)continue;if(now>=item.expires){item.active=false;item.mesh.visible=false;continue;}item.mesh.position.addScaledVector(item.velocity,dt);const dir=item.velocity.clone().normalize();item.mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir);item.mesh.scale.set(1,2.2,1);}for(const item of remoteExplosions){if(!item.mesh.visible)continue;if(now>=item.expires){item.mesh.visible=false;continue;}const t=(now-item.born)/(item.expires-item.born);item.mesh.scale.setScalar(.8+7*t);item.mesh.material.opacity=Math.max(0,.95*(1-t));}}
function sendState(playerId,hp,killed,by="",id=""){const s=session(),packet={type:"state",playerId,hp,killed,by,id:id||`state-${Date.now().toString(36)}`};applyState(packet);s?.sendGame?.(packet);if(killed){const r=playerId===selfId?null:peers.get(playerId),b=bridge(),own=b?.airframeFor?.(b.threeScene)||b?.airframe,p=playerId===selfId?own?.position:r?.mesh?.position;if(p){const fx={type:"explosion",id:`boom-${packet.id}`,p:localToCanonical([p.x,p.y,p.z]),playerId};s?.sendFx?.(fx);spawnExplosion(fx);}}}
function authorityHit(packet){if(authorityId!==selfId||!packet||seenHits.has(packet.id))return;seenHits.add(packet.id);while(seenHits.size>512)seenHits.delete(seenHits.values().next().value);const target=String(packet.target||""),shooter=String(packet.shooter||"");if(!participantIds().includes(target)||!participantIds().includes(shooter))return;const old=health.get(target)??100;if(old<=0)return;const hp=Math.max(0,old-Math.round(clamp(Number(packet.damage)||25,1,100))),killed=hp===0;health.set(target,hp);sendState(target,hp,killed,shooter,packet.id);}
function applyState(packet){if(!packet||seenStates.has(`${packet.id}:${packet.playerId}:${packet.hp}`))return;seenStates.add(`${packet.id}:${packet.playerId}:${packet.hp}`);while(seenStates.size>1024)seenStates.delete(seenStates.values().next().value);const id=String(packet.playerId||""),hp=clamp(Math.round(Number(packet.hp)||0),0,100),killed=Boolean(packet.killed);health.set(id,hp);if(id===selfId){const b=bridge();if(b){const wasDead=Boolean(b.vsLocalDead);b.vsLocalHealth=hp;b.vsLocalDead=killed;if(killed&&!wasDead){deaths++;lastLocalDead=true;}b.updateVsCombatHud?.(true);}return;}const r=recordFor(id);if(!r)return;const wasDead=r.dead;r.health=hp;r.dead=killed;if(killed&&!wasDead&&packet.by===selfId)kills++;setPrimaryCompatibility(r);}
function onGameEvent(event){updateIdentity();const packet=event.detail?.packet;if(!packet)return;if(packet.type==="hit-request"){authorityHit(packet);return;}if(packet.type==="state"){applyState(packet);return;}if(packet.type==="respawn-request"&&authorityId===selfId){const id=String(packet.playerId||"");if(participantIds().includes(id)){health.set(id,100);const state={type:"respawn",playerId:id,hp:100};applyRespawn(state);session()?.sendGame?.(state);}return;}if(packet.type==="respawn")applyRespawn(packet);}
function applyRespawn(packet){const id=String(packet?.playerId||"");if(!id)return;health.set(id,100);if(id===selfId){const b=bridge();if(b){b.vsLocalHealth=100;b.vsLocalDead=false;b.updateVsCombatHud?.(true);}return;}const r=recordFor(id);if(r){r.health=100;r.dead=false;setPrimaryCompatibility(r);}}
function onFxEvent(event){const packet=event.detail?.packet,peerId=event.detail?.peerId;if(!packet)return;if(packet.type==="shot")spawnRemoteShot(packet,peerId);else if(packet.type==="explosion")spawnExplosion(packet);}
function onPeerEvent(event){updateIdentity();const detail=event.detail||{},id=String(detail.peerId||"");if(detail.type==="join"){recordFor(id);health.set(id,health.get(id)??100);refreshColors();if(authorityId===selfId)for(const playerId of participantIds()){const hp=health.get(playerId)??100;session()?.sendGame?.({type:"state",playerId,hp,killed:hp<=0,by:"",id:`sync-${Date.now().toString(36)}-${hashId(playerId)}`});}}else if(detail.type==="leave")removePeer(id);updateIdentity();}
function targetFromHit(hit){for(let node=hit?.object;node;node=node.parent){const id=String(node.userData?.vsPlayerId||"");if(id&&id!==selfId)return id;}const b=bridge();if(primaryId&&b?.vsPeerMesh){for(let node=hit?.object;node;node=node.parent)if(node===b.vsPeerMesh)return primaryId;}return"";}
function installBridgeHooks(){const b=bridge();if(!b||b.__vsMultiplayerHooks)return;b.__vsMultiplayerHooks=true;const baseRegister=b.registerVsHit?.bind(b);b.registerVsHit=hit=>{updateIdentity();const target=targetFromHit(hit);if(!target||!session()?.sendGame)return baseRegister?.(hit)||false;const id=`hit-${Date.now().toString(36)}-${(++shotSeq).toString(36)}`,packet={type:"hit-request",id,shooter:selfId,target,damage:25};if(authorityId===selfId)authorityHit(packet);else if(authorityId)session()?.sendGame?.(packet,{target:authorityId});return true;};b.broadcastVsShot=({from,dir,speed=210}={})=>{updateIdentity();if(!selfId||!session()?.sendFx||!Array.isArray(from)||!Array.isArray(dir))return false;const packet={type:"shot",id:`shot-${Date.now().toString(36)}-${(++shotSeq).toString(36)}`,from:localToCanonical(from),dir:dir.map(Number),speed:Number(speed)||210,playerId:selfId,t:Date.now()};session().sendFx(packet);return true;};b.broadcastVsImpact=({p}={})=>{if(!session()?.sendFx||!Array.isArray(p))return false;return session().sendFx({type:"impact",id:`impact-${Date.now().toString(36)}-${(++shotSeq).toString(36)}`,p:localToCanonical(p),playerId:selfId});};}
function updateSessionHooks(){const s=session();if(s===lastSession)return;lastSession=s;updateIdentity();installBridgeHooks();refreshColors();}
function updateHud(){const b=bridge(),hud=document.getElementById("vsCombatHud");if(!hud||!b?.vsConnected)return;const hp=health.get(selfId)??b.vsLocalHealth??100;hud.hidden=false;hud.textContent=`HP ${hp} · P ${peers.size+1} · K ${kills}`;const button=document.getElementById("lanVsButton");if(button&&peers.size)button.textContent=`MATES ${peers.size} ✓`;}
function render(now=performance.now()){raf=requestAnimationFrame(render);const dt=Math.min(.05,Math.max(0,(now-lastRender)/1000||0));lastRender=now;updateSessionHooks();updateIdentity();const b=bridge(),camera=b?.threeCamera,view=viewport();if(!b?.threeScene||!camera||!view){return;}document.body.classList.toggle("vs-multiplayer",peers.size>0);refreshColors();for(const r of peers.values()){if(r.id===primaryId&&b.vsPeerMesh){r.mesh=b.vsPeerMesh;setPrimaryCompatibility(r);}else if(!r.mesh)r.mesh=createPeerMesh(r);if(!r.mesh)continue;const sample=r.timeline.sample(now);if(sample&&!r.dead&&now-r.lastPoseMs<=STALE_MS){r.mesh.position.set(...sample.p);r.mesh.quaternion.set(...sample.q);r.mesh.visible=true;}else if(r.dead||now-r.lastPoseMs>STALE_MS)r.mesh.visible=false;renderMarker(r,camera,view,now);}renderFx(now,dt);updateHud();if(b.vsLocalDead&&!lastLocalDead)lastLocalDead=true;else if(!b.vsLocalDead&&lastLocalDead){lastLocalDead=false;if(selfId){const req={type:"respawn-request",playerId:selfId};if(authorityId===selfId){applyRespawn({type:"respawn",playerId:selfId,hp:100});session()?.sendGame?.({type:"respawn",playerId:selfId,hp:100});}else if(authorityId)session()?.sendGame?.(req,{target:authorityId});}}}

export function installVsMultiplayer(){if(installed)return;installed=true;style=document.createElement("style");style.textContent=`body.vs-multiplayer #vsEnemyMarker{display:none!important}.vs-player-marker{--vs-player-color:#fff;position:absolute;z-index:14;left:0;top:0;min-width:38px;padding:2px 5px 2px 12px;border-radius:7px;background:#071522a6;color:#fff;font:800 8px/1.05 system-ui,-apple-system,sans-serif;letter-spacing:.02em;pointer-events:none;box-shadow:0 0 0 1px color-mix(in srgb,var(--vs-player-color) 45%,transparent)}.vs-player-marker i{position:absolute;left:4px;top:50%;width:4px;height:4px;margin-top:-2px;border-radius:50%;background:var(--vs-player-color);box-shadow:0 0 6px var(--vs-player-color)}.vs-player-marker strong{display:block;font-size:7px;color:var(--vs-player-color)}.vs-player-marker small{display:block;font-size:7px;opacity:.8}.vs-player-marker.offscreen{opacity:.76}`;document.head.appendChild(style);globalThis.addEventListener(VS_PEER_EVENT,onPeerEvent);globalThis.addEventListener(VS_POSE_EVENT,onPoseEvent);globalThis.addEventListener(VS_GAME_EVENT,onGameEvent);globalThis.addEventListener(VS_FX_EVENT,onFxEvent);raf=requestAnimationFrame(render);}
