import * as THREE from "three";

const PISTOL_INTERVAL_MS=165;
const MG_INTERVAL_MS=96;
const direction=new THREE.Vector3();
let installed=false,sceneRef=null,weapon="pistol",gunRef=null,mgGroup=null,baselineParts=[],firing=false,lastShot=-Infinity,audioCtx=null,patchedWalkApi=null,rawGetGamepads=null,gamepadFilterInstalled=false;

function bridge(){return globalThis.__arondightRealWorld||null;}
function viewport(){return document.getElementById("viewport");}
function walk(){return globalThis.__arondightWalkMode||null;}
function combat(){return globalThis.__arondightBox3dCombat||null;}
function mat(color,{metalness=.4,roughness=.45}={}){return new THREE.MeshStandardMaterial({color,metalness,roughness,depthTest:false,depthWrite:false});}
function part(geometry,material,x,y,z,rx=0,ry=0,rz=0){const m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);m.rotation.set(rx,ry,rz);m.frustumCulled=false;m.renderOrder=10003;m.userData.flightFireIgnore=true;m.userData.walkWeaponPart=true;m.userData.walkMachineGunPart=true;return m;}
function attachWeaponVisuals(gun){if(!gun||gun===gunRef&&mgGroup)return;gunRef=gun;baselineParts=gun.children.filter(child=>!child.userData?.walkArmHotfix&&!child.userData?.walkMachineGunPart);if(!gun.userData.walkMachineGunVisual){const metal=mat(0x252b30,{metalness:.72,roughness:.3}),dark=mat(0x111518,{metalness:.18,roughness:.66}),edge=mat(0x616b73,{metalness:.76,roughness:.3});mgGroup=new THREE.Group();mgGroup.name="WALK_MACHINEGUN_3D";mgGroup.userData.flightFireIgnore=true;mgGroup.userData.walkMachineGunVisual=true;mgGroup.add(part(new THREE.BoxGeometry(.105,.092,.48),metal,0,.015,-.20));mgGroup.add(part(new THREE.BoxGeometry(.085,.08,.34),dark,0,-.045,.06,.12));mgGroup.add(part(new THREE.BoxGeometry(.07,.055,.22),dark,0,-.11,.14,-.35));mgGroup.add(part(new THREE.CylinderGeometry(.018,.018,.50,12),edge,0,.015,-.57,Math.PI/2));mgGroup.add(part(new THREE.BoxGeometry(.085,.03,.13),edge,0,.070,-.18));mgGroup.add(part(new THREE.BoxGeometry(.055,.04,.17),dark,0,-.02,.31,.20));const flash=part(new THREE.SphereGeometry(.045,7,5),new THREE.MeshBasicMaterial({color:0xffd36a,transparent:true,opacity:.95,depthTest:false,depthWrite:false}),0,.015,-.84);flash.name="WALK_MG_MUZZLE";flash.visible=false;mgGroup.add(flash);gun.add(mgGroup);gun.userData.walkMachineGunVisual="compact-rifle-v1";}else mgGroup=gun.getObjectByName?.("WALK_MACHINEGUN_3D")||gun.children.find(x=>x.userData?.walkMachineGunVisual);syncWeaponVisual();}
function syncWeaponVisual(){if(!gunRef)return;for(const child of baselineParts)child.visible=weapon==="pistol";if(mgGroup)mgGroup.visible=weapon==="mg";const v=viewport();if(v){v.dataset.walkWeaponMode=weapon;v.dataset.walkWeaponVisual=weapon==="mg"?"compact-rifle-v1":"pistol-hand-arm-v3";}const button=document.getElementById("footWeapon");if(button)button.textContent=weapon==="mg"?"MG":"PISTOL";}
function setWeapon(next){weapon=next==="mg"?"mg":"pistol";firing=false;syncWeaponVisual();try{localStorage.setItem("arondight45WalkWeaponV1",weapon);}catch{}return weapon;}
function toggleWeapon(){return setWeapon(weapon==="pistol"?"mg":"pistol");}
function loadWeapon(){try{return localStorage.getItem("arondight45WalkWeaponV1")==="mg"?"mg":"pistol";}catch{return"pistol";}}
function ensureUi(){const hud=document.getElementById("footHud");if(!hud)return;let button=document.getElementById("footWeapon");if(!button){const style=document.createElement("style");style.textContent="#footWeapon{position:absolute;right:calc(max(12px,var(--solo-safe-right,env(safe-area-inset-right))) + min(18vw,104px) + 27px);bottom:max(102px,calc(var(--solo-safe-bottom,env(safe-area-inset-bottom)) + 96px));z-index:5;pointer-events:auto;touch-action:manipulation;border:1px solid #ffffff55;border-radius:9px;background:#0a1824dd;color:#eef8ff;padding:6px 9px;font:900 9px/1 system-ui;letter-spacing:.06em}body:not(.on-foot-mode) #footWeapon{display:none}";document.head.appendChild(style);button=document.createElement("button");button.id="footWeapon";button.type="button";button.addEventListener("pointerdown",e=>{e.preventDefault();e.stopPropagation();toggleWeapon();});hud.appendChild(button);}button.textContent=weapon==="mg"?"MG":"PISTOL";}
function ensureAudio(){if(audioCtx)return audioCtx;const Ctx=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Ctx)return null;try{audioCtx=new Ctx({latencyHint:"interactive"});}catch{}return audioCtx;}
function shotSound(){const ctx=ensureAudio();if(!ctx)return;try{if(ctx.state==="suspended")ctx.resume();const t=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter();o.type=weapon==="mg"?"square":"sawtooth";o.frequency.setValueAtTime(weapon==="mg"?260:215,t);o.frequency.exponentialRampToValueAtTime(weapon==="mg"?85:62,t+(weapon==="mg"?.055:.08));f.type="bandpass";f.frequency.value=weapon==="mg"?900:720;f.Q.value=.7;g.gain.setValueAtTime(weapon==="mg"?.055:.07,t);g.gain.exponentialRampToValueAtTime(.0001,t+(weapon==="mg"?.065:.095));o.connect(f).connect(g).connect(ctx.destination);o.start(t);o.stop(t+.11);}catch{}}
function currentDirection(){const v=viewport(),yaw=Number(v?.dataset.walkYaw)||0,pitch=Number(v?.dataset.walkPitch)||0,cp=Math.cos(pitch);return direction.set(Math.sin(yaw)*cp,Math.cos(yaw)*cp,Math.sin(pitch)).normalize();}
function flashMuzzle(){const flash=mgGroup?.getObjectByName?.("WALK_MG_MUZZLE");if(flash)flash.visible=true;}
function fireWeapon(now=performance.now()){if(walk()?.mode!=="foot")return false;const interval=weapon==="mg"?MG_INTERVAL_MS:PISTOL_INTERVAL_MS;if(now-lastShot<interval)return false;const origin=walk()?.position,physics=combat();if(!origin||!physics?.fire)return false;lastShot=now;const dir=currentDirection(),speed=weapon==="mg"?430:360,damage=weapon==="mg"?50:60;physics.fire({origin:[origin.x,origin.y,origin.z],direction:[dir.x,dir.y,dir.z],speed,source:"walk",weapon,damage,replicate:true});const v=viewport();if(v){v.dataset.walkShots=String((Number(v.dataset.walkShots)||0)+1);v.dataset.walkPhysicsShots=String((Number(v.dataset.walkPhysicsShots)||0)+1);v.dataset.walkShotSoundEvents=String((Number(v.dataset.walkShotSoundEvents)||0)+1);v.dataset.walkShotAudioVisualSync="muzzle+recoil+sound";v.dataset.walkWeaponMode=weapon;v.dataset.walkProjectileModel="box3d-isBullet-ccd-v1";if(weapon==="mg")v.dataset.walkMgShots=String((Number(v.dataset.walkMgShots)||0)+1);}if(weapon==="mg")flashMuzzle();shotSound();return true;}

function gamepadButtonValue(button){return Math.max(0,Math.min(1,Number(typeof button==="number"?button:(button?.value??(button?.pressed?1:0)))||0));}
function rawPads(){try{return Array.from(rawGetGamepads?.()||[]);}catch{return[];}}
function activeRawPad(){return rawPads().find(p=>p?.connected&&(p.mapping==="standard"||/xbox|xinput|045e/i.test(String(p.id||""))))||null;}
function filteredPad(pad){if(!pad)return pad;const buttons=Array.from(pad.buttons||[],(b,i)=>i===7?{pressed:false,touched:false,value:0}:b);return{id:pad.id,index:pad.index,connected:pad.connected,timestamp:pad.timestamp,mapping:pad.mapping,axes:pad.axes,buttons,vibrationActuator:pad.vibrationActuator,hapticActuators:pad.hapticActuators};}
function installGamepadFireIsolation(){if(gamepadFilterInstalled)return;const nativeGet=navigator.getGamepads?.bind(navigator);if(!nativeGet)return;rawGetGamepads=nativeGet;try{Object.defineProperty(navigator,"getGamepads",{configurable:true,value:()=>{const pads=rawPads();if(walk()?.mode!=="foot"||!combat()?.fire)return pads;return pads.map(filteredPad);}});gamepadFilterInstalled=true;const v=viewport();if(v)v.dataset.walkGamepadFireRoute="box3d-direct-v1";}catch{const v=viewport();if(v)v.dataset.walkGamepadFireRoute="native-unfiltered";}}
function pollGamepadFire(now){if(walk()?.mode!=="foot"||!rawGetGamepads)return;const pad=activeRawPad(),trigger=gamepadButtonValue(pad?.buttons?.[7]);if(trigger>.5)fireWeapon(now);}
function patchWalkFireApi(){const w=walk();if(!w||w===patchedWalkApi)return;try{w.fire=fireWeapon;patchedWalkApi=w;const v=viewport();if(v)v.dataset.walkFireApi="box3d-direct-v1";}catch{}}

function installInput(){window.addEventListener("pointerdown",e=>{if(walk()?.mode!=="foot")return;const target=e.target instanceof Element?e.target:null;if(target?.closest("#footWeapon"))return;const fire=target?.closest("#footFire"),view=viewport(),lockedMouse=e.pointerType==="mouse"&&document.pointerLockElement===view&&Boolean(target&&view?.contains(target));if(!fire&&!lockedMouse)return;firing=true;fireWeapon();e.preventDefault();e.stopImmediatePropagation();},{capture:true,passive:false});for(const type of["pointerup","pointercancel"])window.addEventListener(type,e=>{if(!firing)return;firing=false;e.preventDefault();e.stopImmediatePropagation();},{capture:true,passive:false});window.addEventListener("keydown",e=>{if(walk()?.mode!=="foot"||e.repeat)return;if(e.code==="KeyQ"){toggleWeapon();e.preventDefault();e.stopPropagation();}}, {capture:true});}
function frame(now=performance.now()){const scene=bridge()?.threeScene;if(scene&&scene!==sceneRef){sceneRef=scene;gunRef=scene.getObjectByName?.("WALK_PISTOL_3D")||null;if(gunRef)attachWeaponVisuals(gunRef);}ensureUi();patchWalkFireApi();pollGamepadFire(now);if(gunRef&&!gunRef.parent){gunRef=null;mgGroup=null;baselineParts=[];}if(!gunRef&&scene){gunRef=scene.getObjectByName?.("WALK_PISTOL_3D")||null;if(gunRef)attachWeaponVisuals(gunRef);}if(firing&&weapon==="mg")fireWeapon(now);if(mgGroup&&weapon==="mg"){const age=now-lastShot,flash=mgGroup.getObjectByName?.("WALK_MG_MUZZLE");if(flash)flash.visible=age>=0&&age<48;mgGroup.position.z=age>=0&&age<70?Math.sin(age/70*Math.PI)*.035:0;}const v=viewport();if(v){v.dataset.walkWeaponMode=weapon;v.dataset.walkWeaponCandidates="0";v.dataset.walkWeaponCandidateIndex="box3d-bodies-v1";v.dataset.walkMgFireIntervalMs=String(MG_INTERVAL_MS);v.dataset.walkWeaponSystem="pistol+box3d-auto-mg-v3";}requestAnimationFrame(frame);}

export function installWalkWeaponSystem(){if(installed)return;installed=true;weapon=loadWeapon();installGamepadFireIsolation();installInput();ensureUi();const v=viewport();if(v){v.dataset.walkWeaponSystem="pistol+box3d-auto-mg-v3";v.dataset.walkProjectileModel="box3d-isBullet-ccd-v1";}requestAnimationFrame(frame);}

installWalkWeaponSystem();
