import * as THREE from "three";

const MG_INTERVAL_MS=96;
const MG_RANGE_M=190;
const candidateMeshes=new Set();
const raycaster=new THREE.Raycaster(),direction=new THREE.Vector3(),normal=new THREE.Vector3(0,0,1);
let installed=false,sceneRef=null,baseAdd=null,weapon="pistol",gunRef=null,mgGroup=null,baselineParts=[],firing=false,lastMgShot=-Infinity,lastFrame=performance.now(),audioCtx=null;

function bridge(){return globalThis.__arondightRealWorld||null;}
function viewport(){return document.getElementById("viewport");}
function walk(){return globalThis.__arondightWalkMode||null;}
function visibleInHierarchy(node){for(let n=node;n;n=n.parent)if(n.visible===false)return false;return true;}
function combatMesh(node){return Boolean(node?.isMesh&&(node.userData?.worldLifeKind||node.userData?.worldPopulationKind)&&!node.userData?.worldPopulationClone&&!node.userData?.flightFireIgnore);}
function indexNode(node){if(!node)return;if(combatMesh(node))candidateMeshes.add(node);if(node.name==="WALK_PISTOL_3D")attachWeaponVisuals(node);}
function indexSubtree(root){root?.traverse?.(indexNode);}
function patchScene(scene){if(!scene||scene===sceneRef)return;sceneRef=scene;candidateMeshes.clear();indexSubtree(scene);if(!scene.__walkWeaponAddPatched){baseAdd=scene.add;scene.add=function(...objects){const out=baseAdd.apply(this,objects);for(const object of objects)indexSubtree(object);return out;};scene.__walkWeaponAddPatched=true;}const v=viewport();if(v){v.dataset.walkWeaponCandidateIndex="scene-add+boot-v1";v.dataset.walkWeaponCandidates=String(candidateMeshes.size);}}
function mat(color,{metalness=.4,roughness=.45}={}){return new THREE.MeshStandardMaterial({color,metalness,roughness,depthTest:false,depthWrite:false});}
function part(geometry,material,x,y,z,rx=0,ry=0,rz=0){const m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);m.rotation.set(rx,ry,rz);m.frustumCulled=false;m.renderOrder=10003;m.userData.flightFireIgnore=true;m.userData.walkWeaponPart=true;m.userData.walkMachineGunPart=true;return m;}
function attachWeaponVisuals(gun){if(!gun||gun===gunRef&&mgGroup)return;gunRef=gun;baselineParts=gun.children.filter(child=>!child.userData?.walkArmHotfix&&!child.userData?.walkMachineGunPart);if(!gun.userData.walkMachineGunVisual){const metal=mat(0x252b30,{metalness:.72,roughness:.3}),dark=mat(0x111518,{metalness:.18,roughness:.66}),edge=mat(0x616b73,{metalness:.76,roughness:.3});mgGroup=new THREE.Group();mgGroup.name="WALK_MACHINEGUN_3D";mgGroup.userData.flightFireIgnore=true;mgGroup.userData.walkMachineGunVisual=true;mgGroup.add(part(new THREE.BoxGeometry(.105,.092,.48),metal,0,.015,-.20));mgGroup.add(part(new THREE.BoxGeometry(.085,.08,.34),dark,0,-.045,.06,.12));mgGroup.add(part(new THREE.BoxGeometry(.07,.055,.22),dark,0,-.11,.14,-.35));mgGroup.add(part(new THREE.CylinderGeometry(.018,.018,.50,12),edge,0,.015,-.57,Math.PI/2));mgGroup.add(part(new THREE.BoxGeometry(.085,.03,.13),edge,0,.070,-.18));mgGroup.add(part(new THREE.BoxGeometry(.055,.04,.17),dark,0,-.02,.31,.20));const flash=part(new THREE.SphereGeometry(.045,7,5),new THREE.MeshBasicMaterial({color:0xffd36a,transparent:true,opacity:.95,depthTest:false,depthWrite:false}),0,.015,-.84);flash.name="WALK_MG_MUZZLE";flash.visible=false;mgGroup.add(flash);gun.add(mgGroup);gun.userData.walkMachineGunVisual="compact-rifle-v1";}else mgGroup=gun.getObjectByName?.("WALK_MACHINEGUN_3D")||gun.children.find(x=>x.userData?.walkMachineGunVisual);syncWeaponVisual();}
function syncWeaponVisual(){if(!gunRef)return;for(const child of baselineParts)child.visible=weapon==="pistol";if(mgGroup)mgGroup.visible=weapon==="mg";const v=viewport();if(v){v.dataset.walkWeaponMode=weapon;v.dataset.walkWeaponVisual=weapon==="mg"?"compact-rifle-v1":"pistol-hand-arm-v3";}const button=document.getElementById("footWeapon");if(button)button.textContent=weapon==="mg"?"MG":"PISTOL";}
function setWeapon(next){weapon=next==="mg"?"mg":"pistol";firing=false;syncWeaponVisual();try{localStorage.setItem("arondight45WalkWeaponV1",weapon);}catch{}return weapon;}
function toggleWeapon(){return setWeapon(weapon==="pistol"?"mg":"pistol");}
function loadWeapon(){try{return localStorage.getItem("arondight45WalkWeaponV1")==="mg"?"mg":"pistol";}catch{return"pistol";}}
function ensureUi(){const hud=document.getElementById("footHud");if(!hud)return;let button=document.getElementById("footWeapon");if(!button){const style=document.createElement("style");style.textContent="#footWeapon{position:absolute;right:calc(max(12px,var(--solo-safe-right,env(safe-area-inset-right))) + min(18vw,104px) + 27px);bottom:max(102px,calc(var(--solo-safe-bottom,env(safe-area-inset-bottom)) + 96px));z-index:5;pointer-events:auto;touch-action:manipulation;border:1px solid #ffffff55;border-radius:9px;background:#0a1824dd;color:#eef8ff;padding:6px 9px;font:900 9px/1 system-ui;letter-spacing:.06em}body:not(.on-foot-mode) #footWeapon{display:none}";document.head.appendChild(style);button=document.createElement("button");button.id="footWeapon";button.type="button";button.addEventListener("pointerdown",e=>{e.preventDefault();e.stopPropagation();toggleWeapon();});hud.appendChild(button);}button.textContent=weapon==="mg"?"MG":"PISTOL";}
function ensureAudio(){if(audioCtx)return audioCtx;const Ctx=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Ctx)return null;try{audioCtx=new Ctx({latencyHint:"interactive"});}catch{}return audioCtx;}
function mgSound(){const ctx=ensureAudio();if(!ctx)return;try{if(ctx.state==="suspended")ctx.resume();const t=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter();o.type="square";o.frequency.setValueAtTime(260,t);o.frequency.exponentialRampToValueAtTime(85,t+.055);f.type="bandpass";f.frequency.value=900;f.Q.value=.7;g.gain.setValueAtTime(.055,t);g.gain.exponentialRampToValueAtTime(.0001,t+.065);o.connect(f).connect(g).connect(ctx.destination);o.start(t);o.stop(t+.07);}catch{}}
function currentDirection(){const v=viewport(),yaw=Number(v?.dataset.walkYaw)||0,pitch=Number(v?.dataset.walkPitch)||0,cp=Math.cos(pitch);return direction.set(Math.sin(yaw)*cp,Math.cos(yaw)*cp,Math.sin(pitch)).normalize();}
function dynamicHit(origin,dir){raycaster.set(origin,dir);raycaster.far=MG_RANGE_M;const active=[];for(const mesh of [...candidateMeshes]){if(!mesh?.parent){candidateMeshes.delete(mesh);continue;}if(visibleInHierarchy(mesh))active.push(mesh);}const hits=raycaster.intersectObjects(active,false);return hits[0]||null;}
function staticImpact(origin,dir){const b=bridge(),v=viewport(),rect=v?.getBoundingClientRect();if(!b?.active||!rect||typeof b.addVisualShotImpact!=="function")return null;return b.addVisualShotImpact(rect.width/2,rect.height/2,rect,{origin,direction:dir});}
function flashMuzzle(){const flash=mgGroup?.getObjectByName?.("WALK_MG_MUZZLE");if(flash)flash.visible=true;}
function fireMg(now=performance.now()){if(weapon!=="mg"||walk()?.mode!=="foot"||now-lastMgShot<MG_INTERVAL_MS)return false;const b=bridge(),origin=walk()?.position;if(!b?.threeScene||!origin)return false;lastMgShot=now;const dir=currentDirection(),hit=dynamicHit(origin,dir);let handled=false;if(hit&&typeof b.registerWorldPopulationHit==="function")handled=Boolean(b.registerWorldPopulationHit(hit));if(!handled)staticImpact(origin,dir);const v=viewport();if(v){v.dataset.walkShots=String((Number(v.dataset.walkShots)||0)+1);v.dataset.walkShotSoundEvents=String((Number(v.dataset.walkShotSoundEvents)||0)+1);v.dataset.walkShotAudioVisualSync="muzzle+recoil+sound";v.dataset.walkWeaponMode="mg";v.dataset.walkMgShots=String((Number(v.dataset.walkMgShots)||0)+1);}flashMuzzle();mgSound();return true;}
function installInput(){window.addEventListener("pointerdown",e=>{if(weapon!=="mg"||walk()?.mode!=="foot")return;const target=e.target instanceof Element?e.target:null;if(target?.closest("#footWeapon"))return;const fire=target?.closest("#footFire"),view=viewport(),lockedMouse=e.pointerType==="mouse"&&document.pointerLockElement===view&&target===view;if(!fire&&!lockedMouse)return;firing=true;fireMg();e.preventDefault();e.stopImmediatePropagation();},{capture:true,passive:false});for(const type of["pointerup","pointercancel"])window.addEventListener(type,e=>{if(!firing)return;firing=false;if(weapon==="mg"){e.preventDefault();e.stopImmediatePropagation();}},{capture:true,passive:false});window.addEventListener("keydown",e=>{if(walk()?.mode!=="foot"||e.repeat)return;if(e.code==="KeyQ"){toggleWeapon();e.preventDefault();e.stopPropagation();}}, {capture:true});}
function frame(now=performance.now()){const dt=Math.min(.05,Math.max(0,(now-lastFrame)/1000));lastFrame=now;const scene=bridge()?.threeScene;if(scene&&scene!==sceneRef)patchScene(scene);ensureUi();if(gunRef&&!gunRef.parent){gunRef=null;mgGroup=null;baselineParts=[];}if(!gunRef&&scene)gunRef=scene.getObjectByName?.("WALK_PISTOL_3D")||null;if(gunRef&&!mgGroup)attachWeaponVisuals(gunRef);if(firing)fireMg(now);if(mgGroup&&weapon==="mg"){const age=now-lastMgShot,flash=mgGroup.getObjectByName?.("WALK_MG_MUZZLE");if(flash)flash.visible=age>=0&&age<48;mgGroup.position.z=age>=0&&age<70?Math.sin(age/70*Math.PI)*.035:0;}const v=viewport();if(v){v.dataset.walkWeaponMode=weapon;v.dataset.walkWeaponCandidates=String(candidateMeshes.size);v.dataset.walkMgFireIntervalMs=String(MG_INTERVAL_MS);v.dataset.walkWeaponSystem="pistol+cached-auto-mg-v1";}requestAnimationFrame(frame);}

export function installWalkWeaponSystem(){if(installed)return;installed=true;weapon=loadWeapon();installInput();const scene=bridge()?.threeScene;if(scene)patchScene(scene);ensureUi();const v=viewport();if(v)v.dataset.walkWeaponSystem="pistol+cached-auto-mg-v1";requestAnimationFrame(frame);}

installWalkWeaponSystem();
