import * as THREE from "three";

const DYNAMIC_KINDS=new Set(["car","person","life-car","life-person","bus","bird"]);
const PERSON_KINDS=new Set(["person","life-person"]);
const AUDIO_SETTINGS_KEY="arondight45AudioSettingsV1";
const PANIC_RADIUS_M=32;
const PANIC_MS=5600;
const FLEE_MPS=4.2;
const SIDEWALK_EXTRA_M=1.35;
const PLAYER_MAX_HP=100;
const TARGET_HP=Object.freeze({person:100,car:180,bus:320,bird:1});
const TARGET_DAMAGE=Object.freeze({person:45,car:30,bus:26,bird:1});
const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,Number(v)||0));

let installed=false,lastFrame=performance.now(),lastWalkShots=0,audioCtx=null,audioUnlocked=false,shotObserver=null;
let sceneRef=null,baseSceneAdd=null,wrappedHit=null,damageRouting=false,localPlayerHp=PLAYER_MAX_HP;
const dynamicRoots=new Set(),ragdollRoots=new Set(),metaByRoot=new WeakMap(),damageByRoot=new WeakMap();
const tmp=new THREE.Vector3();

function bridge(){return globalThis.__arondightRealWorld||null;}
function viewport(){return document.getElementById("viewport");}
function sourceId(node){return String(node?.userData?.worldLifeId||node?.userData?.worldPopulationId||"");}
function rawKind(node){return String(node?.userData?.worldLifeKind||node?.userData?.worldPopulationKind||"");}
function normalizedKind(node){const life=String(node?.userData?.worldLifeKind||"");if(life)return life;const kind=String(node?.userData?.worldPopulationKind||"");return kind.startsWith("life-")?kind.slice(5):kind;}
function hashText(text){let h=2166136261;for(const c of String(text||"")){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function audioSettings(){try{const raw=localStorage.getItem(AUDIO_SETTINGS_KEY),v=raw?JSON.parse(raw):{};return{enabled:v.soundEnabled!==false,volume:clamp(v.fxVolume??100,0,100)/100};}catch{return{enabled:true,volume:1};}}
function unlockAudio(){audioUnlocked=true;const Ctx=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Ctx)return;try{audioCtx??=new Ctx({latencyHint:"interactive"});if(audioCtx.state==="suspended")audioCtx.resume().catch(()=>{});}catch{}}
function scream(strength=1){const settings=audioSettings();if(!audioUnlocked||!settings.enabled||settings.volume<=0||!audioCtx)return;if(audioCtx.state==="suspended"){audioCtx.resume().then(()=>scream(strength)).catch(()=>{});return;}if(audioCtx.state!=="running")return;try{const t=audioCtx.currentTime,d=.46+Math.random()*.16,master=audioCtx.createGain(),formant=audioCtx.createBiquadFilter(),o1=audioCtx.createOscillator(),o2=audioCtx.createOscillator();master.gain.setValueAtTime(.0001,t);master.gain.exponentialRampToValueAtTime(.070*settings.volume*strength,t+.018);master.gain.exponentialRampToValueAtTime(.0001,t+d);formant.type="bandpass";formant.frequency.setValueAtTime(920+Math.random()*230,t);formant.Q.value=1.0;o1.type="sawtooth";o2.type="triangle";o1.frequency.setValueAtTime(690+Math.random()*120,t);o1.frequency.exponentialRampToValueAtTime(300+Math.random()*70,t+d);o2.frequency.setValueAtTime(1040+Math.random()*160,t);o2.frequency.exponentialRampToValueAtTime(430+Math.random()*90,t+d);o1.connect(formant);o2.connect(formant);formant.connect(master).connect(audioCtx.destination);o1.start(t);o2.start(t);o1.stop(t+d+.03);o2.stop(t+d+.03);}catch{}}

function capturePalette(root){const counts=new Map();let skin=null,capsule=null;root?.traverse?.(node=>{if(!node?.isMesh)return;const color=node.material?.color?.getHex?.();if(!Number.isFinite(color))return;counts.set(color,(counts.get(color)||0)+1);const type=String(node.geometry?.type||"");if(type.includes("Sphere"))skin=color;if(type.includes("Capsule"))capsule=color;});const ranked=[...counts].sort((a,b)=>b[1]-a[1]).map(([color])=>color);if(!ranked.length)return null;const shirt=capsule??ranked.find(c=>c!==skin)??ranked[0],pants=ranked.find(c=>c!==shirt&&c!==skin)??0x293847;return{shirt,skin:skin??0xd4a07d,pants};}
function sourceIndex(root){const id=sourceId(root),m=id.match(/-(\d+)$/);if(m)return Number(m[1]);return Number(root?.userData?.worldPopulationIndex)||0;}
function sideIdentity(root){const id=sourceId(root),kind=rawKind(root),index=sourceIndex(root),seedKind=kind==="life-person"?"life-person":"person";return{key:`${seedKind}:${id||index}`,sign:hashText(`${seedKind}:${index}`)&1?1:-1};}
function metaFor(root){let meta=metaByRoot.get(root);if(meta)return meta;const side=sideIdentity(root);meta={palette:capturePalette(root),sideKey:side.key,sideSign:side.sign,panic:null,lastPatchedX:NaN,lastPatchedY:NaN,lastOffsetX:0,lastOffsetY:0,hiddenAt:null};metaByRoot.set(root,meta);return meta;}
function refreshSide(root,meta){const side=sideIdentity(root);if(side.key!==meta.sideKey){meta.sideKey=side.key;meta.sideSign=side.sign;}}

function weaponMesh(geometry,material,position,rotation=[0,0,0]){const m=new THREE.Mesh(geometry,material);m.position.set(...position);m.rotation.set(...rotation);m.frustumCulled=false;m.renderOrder=10002;m.userData.flightFireIgnore=true;m.userData.walkWeaponPart=true;m.userData.walkArmHotfix=true;return m;}
function patchWeaponObject(gun){if(!gun||gun.userData.walkWeaponVisualHotfix)return;for(const child of[...gun.children]){const hex=child?.material?.color?.getHex?.();if(hex===0xb97855)gun.remove(child);}const skin=new THREE.MeshStandardMaterial({color:0xc58a67,roughness:.78,metalness:0,depthTest:false,depthWrite:false}),hand=weaponMesh(new THREE.CapsuleGeometry(.040,.085,4,8),skin,[.018,-.175,.035],[.12,0,-.08]),wrist=weaponMesh(new THREE.CapsuleGeometry(.043,.075,4,8),skin,[.035,-.245,.090],[.62,0,.08]),forearm=weaponMesh(new THREE.CapsuleGeometry(.048,.19,4,8),skin,[.055,-.335,.175],[.72,0,.10]);hand.scale.set(1.05,.90,1.0);gun.add(hand,wrist,forearm);gun.userData.walkWeaponVisualHotfix=true;gun.userData.walkWeaponVisual="pistol-hand-arm-v2";const v=viewport();if(v)v.dataset.walkWeaponVisual="pistol-hand-arm-v2";}
function indexNode(node){if(!node)return;if(node.name==="WALK_PISTOL_3D")patchWeaponObject(node);if(node.userData?.worldRagdollRoot)ragdollRoots.add(node);const kind=rawKind(node);if(node.isMesh&&DYNAMIC_KINDS.has(kind)){node.frustumCulled=false;node.userData.walkNearCullProtected=true;}if(node.children?.length&&DYNAMIC_KINDS.has(kind)){node.userData.walkNearCullProtected=true;dynamicRoots.add(node);metaFor(node);}}
function indexSubtree(root){root?.traverse?.(indexNode);}
function patchScene(scene){if(!scene||scene===sceneRef)return;sceneRef=scene;dynamicRoots.clear();ragdollRoots.clear();indexSubtree(scene);if(!scene.__walkRealityAddPatched){baseSceneAdd=scene.add;scene.add=function(...objects){const result=baseSceneAdd.apply(this,objects);for(const object of objects)indexSubtree(object);return result;};scene.__walkRealityAddPatched=true;}const v=viewport();if(v){v.dataset.walkDynamicCull="event-indexed-v2";v.dataset.walkDynamicRoots=String(dynamicRoots.size);v.dataset.worldRealityIndex="scene-add+one-boot-scan-v2";}}

function parseWalkPosition(){const raw=String(viewport()?.dataset.walkPosition||"").split(",").map(Number);return raw.length>=2&&raw.every(Number.isFinite)?{x:raw[0],y:raw[1]}:null;}
function isPersonRoot(root){return PERSON_KINDS.has(rawKind(root))||normalizedKind(root)==="person";}
function reactToGunshot(){const shot=parseWalkPosition();if(!shot)return;const now=performance.now(),near=[];for(const root of dynamicRoots){if(!root?.parent||root.visible===false||!isPersonRoot(root))continue;root.getWorldPosition(tmp);const dx=tmp.x-shot.x,dy=tmp.y-shot.y,dist=Math.hypot(dx,dy);if(dist>PANIC_RADIUS_M)continue;const meta=metaFor(root),inv=1/Math.max(.35,dist),panic=meta.panic||{x:0,y:0,lastScream:-Infinity};panic.dirX=dx*inv;panic.dirY=dy*inv;if(dist<1){const a=(hashText(sourceId(root))%6283)/1000;panic.dirX=Math.cos(a);panic.dirY=Math.sin(a);}panic.until=now+PANIC_MS;panic.speed=FLEE_MPS+(1-dist/PANIC_RADIUS_M)*1.6;meta.panic=panic;near.push({root,dist,panic});}near.sort((a,b)=>a.dist-b.dist);let screamed=0;for(const item of near){if(screamed>=2)break;if(now-item.panic.lastScream<2400)continue;item.panic.lastScream=now;scream(item.dist<9?1:.78);screamed++;}const v=viewport();if(v){v.dataset.worldPeoplePanic=String(near.length);v.dataset.worldPeopleReaction="sidewalk+flee+scream-v2";}}
function applyPersonReality(root,now,dt){if(root.visible===false)return;const meta=metaFor(root);refreshSide(root,meta);const repeated=Number.isFinite(meta.lastPatchedX)&&Math.hypot(root.position.x-meta.lastPatchedX,root.position.y-meta.lastPatchedY)<.004;if(repeated){root.position.x-=meta.lastOffsetX;root.position.y-=meta.lastOffsetY;}const yaw=Number(root.rotation.z)||0,side=meta.sideSign*SIDEWALK_EXTRA_M,sideX=-Math.sin(yaw)*side,sideY=Math.cos(yaw)*side;let panicX=0,panicY=0;if(meta.panic){const p=meta.panic;if(now<p.until){p.x=(Number(p.x)||0)+(Number(p.dirX)||0)*(Number(p.speed)||FLEE_MPS)*dt;p.y=(Number(p.y)||0)+(Number(p.dirY)||0)*(Number(p.speed)||FLEE_MPS)*dt;root.rotation.z=Math.atan2(Number(p.dirY)||0,Number(p.dirX)||1);}else{const decay=Math.exp(-.18*dt);p.x*=decay;p.y*=decay;if(Math.hypot(p.x,p.y)<.025)meta.panic=null;}panicX=Number(p.x)||0;panicY=Number(p.y)||0;}meta.lastOffsetX=sideX+panicX;meta.lastOffsetY=sideY+panicY;root.position.x+=meta.lastOffsetX;root.position.y+=meta.lastOffsetY;meta.lastPatchedX=root.position.x;meta.lastPatchedY=root.position.y;}
function applyWorldReality(now,dt){let active=0,people=0;for(const root of dynamicRoots){if(!root?.parent){dynamicRoots.delete(root);continue;}const meta=metaFor(root);if(root.visible===false){if(meta.hiddenAt===null)meta.hiddenAt=now;continue;}if(meta.hiddenAt!==null){if(now-meta.hiddenAt>1200)damageByRoot.delete(root);meta.hiddenAt=null;}active++;if(isPersonRoot(root)){people++;applyPersonReality(root,now,dt);}}const v=viewport();if(v){v.dataset.walkDynamicRoots=String(dynamicRoots.size);v.dataset.worldRealityActive=String(active);v.dataset.worldRealityPeople=String(people);v.dataset.worldPedestrianPlacement="road-edge-sidewalk-v2";}}

function rootFromHit(hit){let node=hit?.object||null,best=null;while(node){const kind=rawKind(node);if(DYNAMIC_KINDS.has(kind)&&node.children?.length)best=node;node=node.parent;}if(best)return best;node=hit?.object||null;while(node){if(DYNAMIC_KINDS.has(rawKind(node)))return node;node=node.parent;}return null;}
function headshot(hit,kind){if(kind!=="person")return false;const type=String(hit?.object?.geometry?.type||"");return type.includes("Sphere")||String(hit?.object?.name||"").toLowerCase().includes("head");}
function incrementDamageTelemetry(root,kind,hp,maxHp,damage){const v=viewport();if(!v)return;const life=Boolean(root?.userData?.worldLifeId);if(life){v.dataset.worldLifeHits=String((Number(v.dataset.worldLifeHits)||0)+1);v.dataset.worldLifeLastHit=kind;}else{v.dataset.worldPopulationHits=String((Number(v.dataset.worldPopulationHits)||0)+1);v.dataset.worldPopulationLastHit=kind;}v.dataset.worldObjectHp=String(hp);v.dataset.worldObjectMaxHp=String(maxHp);v.dataset.worldObjectDamage=String(damage);v.dataset.worldObjectKind=kind;v.dataset.worldDamageModel="pistol-hp-v2";}
function applyPaletteToRagdoll(id,palette){if(!id||!palette)return false;for(const root of ragdollRoots){if(root?.visible===false||String(root.userData?.worldRagdollId||"")!==id)continue;root.traverse(node=>{if(!node?.isMesh||!node.material?.color)return;const kind=String(node.userData?.ragdollKind||"");if(kind==="shirt")node.material.color.setHex(palette.shirt);else if(kind==="pants")node.material.color.setHex(palette.pants);else if(kind==="skin"||kind==="head")node.material.color.setHex(palette.skin);});root.userData.walkSourcePaletteId=id;const v=viewport();if(v)v.dataset.worldRagdollPalette="source-preserved-event-v2";return true;}return false;}
function routeDamage(hit,base){const root=rootFromHit(hit);if(!root)return Boolean(base(hit));const kind=normalizedKind(root),maxHp=TARGET_HP[kind];if(!maxHp)return Boolean(base(hit));let state=damageByRoot.get(root);if(!state||state.maxHp!==maxHp)state={hp:maxHp,maxHp};const damage=headshot(hit,kind)?maxHp:TARGET_DAMAGE[kind],next=Math.max(0,state.hp-damage);state.hp=next;damageByRoot.set(root,state);const meta=metaFor(root),id=sourceId(root);if(next>0){incrementDamageTelemetry(root,kind,next,maxHp,damage);if(kind==="person"){scream(1.0);const p=parseWalkPosition();if(p){root.getWorldPosition(tmp);const dx=tmp.x-p.x,dy=tmp.y-p.y,d=Math.hypot(dx,dy)||1;meta.panic={...(meta.panic||{}),dirX:dx/d,dirY:dy/d,until:performance.now()+PANIC_MS,speed:FLEE_MPS+1,x:Number(meta.panic?.x)||0,y:Number(meta.panic?.y)||0,lastScream:performance.now()};}}return true;}const palette=meta.palette,handled=Boolean(base(hit));if(kind==="person"&&handled){if(!applyPaletteToRagdoll(id,palette))queueMicrotask(()=>applyPaletteToRagdoll(id,palette));}const v=viewport();if(v){v.dataset.worldObjectHp="0";v.dataset.worldObjectMaxHp=String(maxHp);v.dataset.worldObjectDamage=String(damage);v.dataset.worldObjectKind=kind;v.dataset.worldDamageModel="pistol-hp-v2";}return handled;}
function patchDamageModel(){const b=bridge(),current=b?.registerWorldPopulationHit;if(!b||typeof current!=="function"||current===wrappedHit||current.__realityDamageTop)return;const base=current.bind(b),wrapper=hit=>{if(damageRouting)return Boolean(base(hit));damageRouting=true;try{return routeDamage(hit,base);}finally{damageRouting=false;}};wrapper.__realityDamageTop=true;wrappedHit=wrapper;b.registerWorldPopulationHit=wrapper;const v=viewport();if(v){v.dataset.worldDamageModel="pistol-hp-v2";v.dataset.walkPistolDamage="45";v.dataset.worldCarHp="180";v.dataset.worldBusHp="320";}}

function currentPlayerHp(){const b=bridge(),v=viewport(),remote=b?.vsLocalHealth,self=v?.dataset.selfHp;if(remote!==undefined&&remote!==null&&Number.isFinite(Number(remote)))return clamp(Number(remote),0,PLAYER_MAX_HP);if(self!==undefined&&self!==null&&Number.isFinite(Number(self)))return clamp(Number(self),0,PLAYER_MAX_HP);return localPlayerHp;}
function damageLocalPlayer(amount=25,source="world"){const b=bridge(),v=viewport(),old=currentPlayerHp(),hp=Math.max(0,old-Math.max(0,Number(amount)||0));localPlayerHp=hp;if(b){b.vsLocalHealth=hp;b.vsLocalDead=hp<=0;b.updateVsCombatHud?.(true);}if(v){v.dataset.selfHp=String(hp);v.dataset.playerHp=String(hp);v.dataset.playerDead=hp<=0?"1":"0";v.dataset.playerLastDamage=String(source);}return hp;}
function syncPlayerHealth(){const v=viewport(),b=bridge();if(!v)return;const hp=currentPlayerHp();localPlayerHp=hp;v.dataset.playerHp=String(hp);v.dataset.playerMaxHp=String(PLAYER_MAX_HP);v.dataset.playerDamageModel="shared-hp-v2";v.dataset.playerDead=hp<=0?"1":"0";if(b&&b.vsLocalHealth!==undefined&&b.vsLocalHealth!==null&&Number.isFinite(Number(b.vsLocalHealth))&&Number(b.vsLocalHealth)!==hp)b.vsLocalHealth=hp;}
function installPlayerDamageApi(){globalThis.__arondightPlayerDamageModel={maxHp:PLAYER_MAX_HP,get hp(){return currentPlayerHp();},damage:damageLocalPlayer,reset(){const b=bridge(),v=viewport();localPlayerHp=PLAYER_MAX_HP;if(b){b.vsLocalHealth=PLAYER_MAX_HP;b.vsLocalDead=false;b.updateVsCombatHud?.(true);}if(v){v.dataset.selfHp=String(PLAYER_MAX_HP);v.dataset.playerHp=String(PLAYER_MAX_HP);v.dataset.playerDead="0";}return PLAYER_MAX_HP;}};addEventListener("arondight:player-damage",event=>damageLocalPlayer(event?.detail?.damage??25,event?.detail?.source||"event"));}

function installLocationAutoApply(){document.addEventListener("change",event=>{const select=event.target instanceof Element?event.target.closest("[data-world-location-select]"):null;if(!select||select.value==="custom")return;const root=select.closest("[data-world-location-selector]");queueMicrotask(()=>root?.querySelector("[data-world-location-apply]")?.click());const v=viewport();if(v)v.dataset.worldLocationSwitch="auto-apply-v2";},{capture:true});}
function observeShots(){const v=viewport();if(!v||shotObserver)return false;lastWalkShots=Number(v.dataset.walkShots)||0;shotObserver=new MutationObserver(()=>{const shots=Number(v.dataset.walkShots)||0;if(shots>lastWalkShots)for(let n=lastWalkShots;n<shots;n++)reactToGunshot();lastWalkShots=shots;});shotObserver.observe(v,{attributes:true,attributeFilter:["data-walk-shots"]});return true;}
function frame(now=performance.now()){const dt=clamp((now-lastFrame)/1000,0,.05);lastFrame=now;const scene=bridge()?.threeScene;if(scene&&scene!==sceneRef)patchScene(scene);observeShots();patchDamageModel();syncPlayerHealth();applyWorldReality(now,dt);requestAnimationFrame(frame);}

export function installWalkWorldExperienceHotfix(){if(installed)return;installed=true;addEventListener("pointerdown",unlockAudio,{capture:true,passive:true});addEventListener("keydown",unlockAudio,{capture:true});installLocationAutoApply();installPlayerDamageApi();observeShots();const v=viewport();if(v)v.dataset.worldRealityRuntime="event-indexed-no-periodic-traverse-v2";setTimeout(()=>requestAnimationFrame(frame),0);}

installWalkWorldExperienceHotfix();
