import {wantedPoliceArrivalDelayMs,wantedPoliceEngageDelayMs,wantedPoliceFireRangeM} from "./wanted_system_logic.mjs";
let installed=false;
const seenSpawnSerial=new Map();
function viewport(){return document.getElementById("viewport");}
function stageSpawn(drone,stars,now){const serial=Number(drone.spawnSerial)||0,previous=seenSpawnSerial.get(drone.index);if(previous===serial)return false;seenSpawnSerial.set(drone.index,serial);const arrival=wantedPoliceArrivalDelayMs(stars),revealAt=(Number(drone.spawnedAt)||now)+arrival;drone.dispatchRevealAt=revealAt;drone.engageAt=Math.max(Number(drone.engageAt)||0,revealAt+wantedPoliceEngageDelayMs(stars));drone.nextShotAt=Math.max(Number(drone.nextShotAt)||0,drone.engageAt+drone.index*120);if(drone.root)drone.root.visible=false;if(drone.hitbox)drone.hitbox.visible=false;return true;}
function renderInboundHud(now,inbound){const hud=document.getElementById("wantedHud");if(!hud||inbound.length===0)return;const next=Math.max(0,Math.min(...inbound.map(drone=>drone.dispatchRevealAt-now))),title=hud.querySelector("strong"),detail=hud.querySelector("small");hud.dataset.phase="pursuit";if(title)title.textContent="POLICE DISPATCH";if(detail)detail.textContent=`${inbound.length} DRONE${inbound.length===1?"":"S"} INBOUND · ${(next/1000).toFixed(1)} s`;}
function frame(now=performance.now()){const api=globalThis.__arondightWantedSystem,state=api?.state,stars=Number(state?.stars)||0;let inbound=[];if(api&&stars>0){for(const drone of api.drones||[]){if(!drone?.active)continue;stageSpawn(drone,stars,now);const revealAt=Number(drone.dispatchRevealAt)||0;if(revealAt>now){if(drone.root)drone.root.visible=false;if(drone.hitbox)drone.hitbox.visible=false;drone.seesPlayer=false;inbound.push(drone);}else if(!drone.retreating&&!drone.empDisabled){if(drone.root)drone.root.visible=true;if(drone.hitbox)drone.hitbox.visible=true;}}}
  const view=viewport();if(view){const fireRange=stars?wantedPoliceFireRangeM(stars):0,arrival=stars?wantedPoliceArrivalDelayMs(stars):0;view.dataset.wantedSystem="heat+fair-physics-police-drones-v5";view.dataset.wantedPoliceSpawn="delayed-dispatch-far-inbound-v4";view.dataset.wantedPoliceInitialArrivalMs=String(Math.round(arrival));view.dataset.wantedPoliceInboundHidden=String(inbound.length);view.dataset.wantedPoliceFireRangeM=fireRange.toFixed(1);view.dataset.wantedPoliceTargeting="controlled-target+fresh-los+hard-range-v2";view.dataset.wantedPoliceGhostHits="blocked-v1";view.dataset.wantedPoliceDamageRouting="controlled-target-only-v1";}
  renderInboundHud(now,inbound);requestAnimationFrame(frame);}
export function installWantedDispatchGuard(){if(installed)return;installed=true;requestAnimationFrame(frame);}
installWantedDispatchGuard();
