import {wantedLineBlockedByPrisms} from "./wanted_system_logic.mjs";
let installed=false,lastStars=0,firstDispatchSuppressed=false,targetContractPatched=false;
function viewport(){return document.getElementById("viewport");}
function physics(){return globalThis.__arondightWorldRigidBodies||null;}
function wanted(){return globalThis.__arondightWantedSystem||null;}
function patchActiveTargetContract(){if(targetContractPatched)return;const vitals=globalThis.__arondightPlayerVitals;if(!vitals||typeof vitals.damageTargets!=="function")return;const base=vitals.damageTargets.bind(vitals);vitals.damageTargets=()=>{const list=base(),drive=Boolean(globalThis.__arondightVehicleDrive?.active),foot=globalThis.__arondightWalkMode?.mode==="foot",kind=drive||foot?"player":"drone";return list.filter(target=>target?.kind===kind);};targetContractPatched=true;const v=viewport();if(v)v.dataset.wantedDamageTargetContract="active-player-mode-only-v2";}
function suppressInstantFirstWave(now){const api=wanted(),state=api?.state;if(!api||!state||firstDispatchSuppressed||state.stars<=0||state.waveNumber<1||state.policeActive<=0)return;let removed=0;for(const drone of api.drones||[]){if(!drone?.active)continue;drone.active=false;drone.root&&(drone.root.visible=false);drone.hitbox&&(drone.hitbox.visible=false);drone.tracer&&(drone.tracer.visible=false);drone.seesPlayer=false;drone.targetKind="";drone.nextShotAt=Infinity;drone.destroyedUntil=now;physics()?.removeBody?.(`police-drone-${drone.index}`);removed++;}if(removed){firstDispatchSuppressed=true;const v=viewport();if(v){v.dataset.wantedInitialDispatchDelay="physical-inbound-v1";v.dataset.wantedInitialInstantSpawnsPrevented=String(removed);}}}
function guardTargeting(now){const api=wanted(),state=api?.state;if(!api||!state||state.stars<=0)return;const drive=Boolean(globalThis.__arondightVehicleDrive?.active),desired=drive||globalThis.__arondightWalkMode?.mode==="foot"?"player":"drone",maxRange=28+state.stars*2,prisms=globalThis.__arondightRealWorld?.buildingCollisionSnapshot?.prisms||[];for(const drone of api.drones||[]){if(!drone?.active||drone.empDisabled||drone.retreating)continue;const wrong=drone.targetKind&&drone.targetKind!==desired,far=Number(drone.distance)>maxRange,blocked=drone.targetPosition&&wantedLineBlockedByPrisms(drone.root.position,drone.targetPosition,prisms);if(wrong||far||blocked){drone.seesPlayer=false;if(wrong)drone.targetKind="";drone.nextShotAt=Math.max(Number(drone.nextShotAt)||0,now+420);}}const v=viewport();if(v){v.dataset.wantedPoliceHardAttackRangeM=String(maxRange);v.dataset.wantedPoliceShotLos="sensor+frame-guard-v2";v.dataset.wantedPoliceTargeting="active-mode-only+range+los-v2";}}
function renderDispatchHud(now){const api=wanted(),state=api?.state,hud=document.getElementById("wantedHud");if(!hud||!state||state.stars<=0||state.policeActive>0||!Number.isFinite(state.nextWaveAt)||state.nextWaveAt<=now)return;const title=hud.querySelector("strong"),detail=hud.querySelector("small"),remaining=Math.max(0,state.nextWaveAt-now);hud.dataset.phase="searching";if(title)title.textContent=firstDispatchSuppressed?"POLICE DISPATCH":"REINFORCEMENTS";if(detail)detail.textContent=`DRONES INBOUND · ${(remaining/1000).toFixed(1)} s`;}
function frame(now=performance.now()){patchActiveTargetContract();const state=wanted()?.state,stars=Number(state?.stars)||0;if(lastStars<=0&&stars>0)firstDispatchSuppressed=false;if(stars<=0)firstDispatchSuppressed=false;suppressInstantFirstWave(now);guardTargeting(now);renderDispatchHud(now);lastStars=stars;requestAnimationFrame(frame);}
export function installWantedDispatchGuard(){if(installed)return;installed=true;const v=viewport();if(v)v.dataset.wantedDispatchGuard="latency+active-target+range-los-v2";requestAnimationFrame(frame);}
installWantedDispatchGuard();
