import {createWorldBuildingCollisionBodies,destroyWorldBuildingCollisionBodies,normalizeBuildingCollisionSnapshot} from "./world_building_collision_physics.mjs";

export const WORLD_PHYSICS_CATEGORIES=Object.freeze({terrain:1n,vehicle:2n,drone:4n});
const ALL_DYNAMIC=WORLD_PHYSICS_CATEGORIES.vehicle|WORLD_PHYSICS_CATEGORIES.drone;
const clamp=(value,min,max)=>Math.max(min,Math.min(max,Number(value)||0));
const wrap=value=>{let angle=(Number(value)||0)%(Math.PI*2);if(angle>Math.PI)angle-=Math.PI*2;if(angle<-Math.PI)angle+=Math.PI*2;return angle;};
const length3=value=>Math.hypot(Number(value?.[0])||0,Number(value?.[1])||0,Number(value?.[2])||0);
const yawQuaternion=yaw=>[0,0,Math.sin((Number(yaw)||0)/2),Math.cos((Number(yaw)||0)/2)];
const quaternionYaw=q=>Math.atan2(2*((Number(q?.[3])||1)*(Number(q?.[2])||0)+(Number(q?.[0])||0)*(Number(q?.[1])||0)),1-2*((Number(q?.[1])||0)**2+(Number(q?.[2])||0)**2));
const shapeKey=id=>`${Number(id?.index1)||0}:${Number(id?.world0)||0}:${Number(id?.generation)||0}`;

function finiteVector(value,length=3){return Array.isArray(value)&&value.length===length&&value.every(Number.isFinite);}
function limitedVector(value,maxLength){const vector=[Number(value?.[0])||0,Number(value?.[1])||0,Number(value?.[2])||0],magnitude=length3(vector),limit=Math.max(0,Number(maxLength)||0);if(limit&&magnitude>limit){const scale=limit/magnitude;return vector.map(component=>component*scale);}return vector;}

export class WorldRigidBodyPhysics{
  constructor(b3,{buildingSnapshot=null,onImpact=null}={}){
    if(!b3?.b3CreateWorld||!b3?.b3CreateBody)throw Error("Box3D runtime is required");this.b3=b3;this.onImpact=typeof onImpact==="function"?onImpact:null;this.records=new Map();this.shapeRecords=new Map();this.impactCount=0;this.stepCount=0;this.buildingState=null;this.buildingSnapshot=normalizeBuildingCollisionSnapshot(null);this.eventsBuffer=typeof b3.createEventsBuffer==="function"?b3.createEventsBuffer():null;this.hitEvent=typeof b3.createContactHitEvent==="function"?b3.createContactHitEvent():null;
    const worldDef=b3.b3DefaultWorldDef();worldDef.gravity=[0,0,-9.80665];worldDef.enableSleep=true;worldDef.enableContinuous=true;worldDef.hitEventThreshold=1.25;this.world=b3.b3CreateWorld(worldDef);
    const groundDef=b3.b3DefaultBodyDef();groundDef.position=[0,0,-.08];const ground=b3.b3CreateBody(this.world,groundDef),shapeDef=b3.b3DefaultShapeDef();shapeDef.baseMaterial.friction=.82;shapeDef.baseMaterial.restitution=.025;shapeDef.filter={categoryBits:WORLD_PHYSICS_CATEGORIES.terrain,maskBits:ALL_DYNAMIC,groupIndex:0};b3.b3CreateBoxShape(ground,shapeDef,10000,10000,.08);this.ground=ground;this.syncBuildings(buildingSnapshot);
  }
  syncBuildings(value){const snapshot=normalizeBuildingCollisionSnapshot(value);if(snapshot.hash===this.buildingSnapshot.hash&&snapshot.prismCount===this.buildingSnapshot.prismCount)return false;destroyWorldBuildingCollisionBodies(this.b3,this.buildingState);this.buildingSnapshot=snapshot;this.buildingState=createWorldBuildingCollisionBodies(this.b3,this.world,snapshot,{categoryBits:WORLD_PHYSICS_CATEGORIES.terrain,maskBits:ALL_DYNAMIC,rangefinderCategoryBits:0n,launchExclusionPoint:[Infinity,Infinity]});return true;}
  addBody({id,kind="vehicle",position=[0,0,0],yaw=0,halfExtents=[1,.5,.5],massKg=1000,gravityScale,linearDamping,angularDamping}={}){
    const key=String(id||"");if(!key||!finiteVector(position)||!finiteVector(halfExtents)||halfExtents.some(value=>!(value>.02)))return null;this.removeBody(key);const drone=kind==="drone"||kind==="police-drone",category=drone?WORLD_PHYSICS_CATEGORIES.drone:WORLD_PHYSICS_CATEGORIES.vehicle,b3=this.b3,bodyDef=b3.b3DefaultBodyDef(),resolvedGravityScale=Number.isFinite(gravityScale)?gravityScale:drone?0:1;bodyDef.type=b3.b3BodyType.b3_dynamicBody;bodyDef.position=[...position];bodyDef.rotation=yawQuaternion(yaw);bodyDef.linearDamping=Number.isFinite(linearDamping)?linearDamping:drone? .42:.16;bodyDef.angularDamping=Number.isFinite(angularDamping)?angularDamping:drone?1.15:.78;bodyDef.gravityScale=resolvedGravityScale;bodyDef.enableSleep=false;bodyDef.isBullet=true;const body=b3.b3CreateBody(this.world,bodyDef),shapeDef=b3.b3DefaultShapeDef(),volume=8*halfExtents[0]*halfExtents[1]*halfExtents[2];shapeDef.density=Math.max(.01,(Number(massKg)||1)/Math.max(.01,volume));shapeDef.baseMaterial.friction=drone? .48:.18;shapeDef.baseMaterial.restitution=drone? .12:.035;shapeDef.enableContactEvents=true;shapeDef.enableHitEvents=true;shapeDef.filter={categoryBits:category,maskBits:WORLD_PHYSICS_CATEGORIES.terrain|ALL_DYNAMIC,groupIndex:0};const shape=b3.b3CreateBoxShape(body,shapeDef,...halfExtents);
    const record={id:key,kind:String(kind||"vehicle"),body,shape,halfExtents:[...halfExtents],massKg:Math.max(.1,Number(massKg)||1),gravityScale:resolvedGravityScale,drone,target:null,pendingImpulse:[0,0,0],impulsePoint:null,preVelocity:[0,0,0],lastVelocity:[0,0,0],lastImpactAt:-Infinity,impactCount:0};this.records.set(key,record);this.shapeRecords.set(shapeKey(shape),record);return record;
  }
  removeBody(id){const key=String(id||""),record=this.records.get(key);if(!record)return false;this.records.delete(key);this.shapeRecords.delete(shapeKey(record.shape));if(record.body&&this.b3.b3Body_IsValid(record.body))this.b3.b3DestroyBody(record.body);return true;}
  setTarget(id,{position,speedMps=0,response=3.2,maxAccelerationMps2,yaw=null}={}){const record=this.records.get(String(id||""));if(!record||!finiteVector(position))return false;record.target={position:[...position],speedMps:Math.max(0,Number(speedMps)||0),response:clamp(response,.2,10),maxAccelerationMps2:clamp(maxAccelerationMps2??(record.drone?13:6),.5,30),yaw:Number.isFinite(yaw)?Number(yaw):null};return true;}
  clearTarget(id){const record=this.records.get(String(id||""));if(!record)return false;record.target=null;return true;}
  setGravityScale(id,gravityScale=1){const record=this.records.get(String(id||"")),value=Number(gravityScale);if(!record||!Number.isFinite(value)||typeof this.b3.b3Body_SetGravityScale!=="function")return false;record.gravityScale=clamp(value,0,4);this.b3.b3Body_SetGravityScale(record.body,record.gravityScale);this.b3.b3Body_SetAwake?.(record.body,true);return true;}
  applyImpulse(id,impulse,{point=null}={}){const record=this.records.get(String(id||""));if(!record||!finiteVector(impulse))return false;const bounded=limitedVector(impulse,record.massKg*(record.drone?8:3));for(let index=0;index<3;index++)record.pendingImpulse[index]+=bounded[index];record.impulsePoint=finiteVector(point)?[...point]:null;return true;}
  pose(id){const record=this.records.get(String(id||""));if(!record||!this.b3.b3Body_IsValid(record.body))return null;const position=this.b3.b3Body_GetPosition([0,0,0],record.body),rotation=this.b3.b3Body_GetRotation([0,0,0,1],record.body),velocity=this.b3.b3Body_GetLinearVelocity([0,0,0],record.body),angularVelocity=this.b3.b3Body_GetAngularVelocity([0,0,0],record.body);return{position:[...position],rotation:[...rotation],velocity:[...velocity],angularVelocity:[...angularVelocity],yaw:quaternionYaw(rotation)};}
  controlBody(record,dt){
    const b3=this.b3,body=record.body,position=b3.b3Body_GetPosition([0,0,0],body),velocity=b3.b3Body_GetLinearVelocity([0,0,0],body),angular=b3.b3Body_GetAngularVelocity([0,0,0],body);record.preVelocity=[...velocity];
    if(record.target){const offset=record.target.position.map((value,index)=>value-position[index]),horizontal=Math.hypot(offset[0],offset[1]),distance=record.drone?length3(offset):horizontal;if(distance>.03){const targetYaw=record.target.yaw??Math.atan2(offset[1],offset[0]),vertical=record.drone?offset[2]/Math.max(.01,distance):0,horizontalScale=record.drone?Math.sqrt(Math.max(0,1-vertical*vertical)):1,desired=[Math.cos(targetYaw)*record.target.speedMps*horizontalScale,Math.sin(targetYaw)*record.target.speedMps*horizontalScale,vertical*record.target.speedMps],gain=record.target.response,maxForce=record.massKg*record.target.maxAccelerationMps2,force=limitedVector([(desired[0]-velocity[0])*record.massKg*gain,(desired[1]-velocity[1])*record.massKg*gain,record.drone?(desired[2]-velocity[2])*record.massKg*gain:0],maxForce);b3.b3Body_ApplyForceToCenter(body,force,true);const rotation=b3.b3Body_GetRotation([0,0,0,1],body),yawError=wrap(targetYaw-quaternionYaw(rotation)),torqueZ=clamp((yawError*7-angular[2]*2.8)*record.massKg,-record.massKg*12,record.massKg*12);if(record.drone){const[qx,qy,qz,qw]=rotation,upX=2*(qx*qz+qw*qy),upY=2*(qy*qz-qw*qx),torqueX=clamp((upY*10-angular[0]*3.4)*record.massKg,-record.massKg*12,record.massKg*12),torqueY=clamp((-upX*10-angular[1]*3.4)*record.massKg,-record.massKg*12,record.massKg*12);b3.b3Body_ApplyTorque(body,[torqueX,torqueY,torqueZ],true);}else b3.b3Body_ApplyTorque(body,[0,0,torqueZ],true);}}
    if(length3(record.pendingImpulse)>.0001){const force=record.pendingImpulse.map(value=>value/Math.max(.001,dt));if(record.impulsePoint)b3.b3Body_ApplyForce(body,force,record.impulsePoint,true);else b3.b3Body_ApplyForceToCenter(body,force,true);record.pendingImpulse=[0,0,0];record.impulsePoint=null;}
  }
  step(dt=1/60,subSteps=4,now=performance.now?.()??Date.now()){
    const delta=clamp(dt,.001,.04);for(const record of this.records.values())this.controlBody(record,delta);this.b3.b3World_Step(this.world,delta,Math.max(1,Math.min(8,Math.floor(Number(subSteps)||4))));this.stepCount++;
    let nativeHitCount=0;if(this.eventsBuffer&&this.hitEvent&&typeof this.b3.getEvents==="function"){this.b3.getEvents(this.eventsBuffer,this.world);nativeHitCount=this.b3.getNumContactHitEvents(this.eventsBuffer);for(let index=0;index<nativeHitCount;index++){this.b3.getContactHitEventAt(this.hitEvent,this.eventsBuffer,index);const speed=Math.abs(Number(this.hitEvent.approachSpeed)||0),hitRecords=new Set([this.shapeRecords.get(shapeKey(this.hitEvent.shapeIdA)),this.shapeRecords.get(shapeKey(this.hitEvent.shapeIdB))]);for(const record of hitRecords){if(!record||now-record.lastImpactAt<=120)continue;record.lastImpactAt=now;record.impactCount++;this.impactCount++;const pose=this.pose(record.id),detail={id:record.id,kind:record.kind,deltaVelocityMps:speed,approachSpeedMps:speed,energyJ:.5*record.massKg*speed*speed,position:[...this.hitEvent.point],normal:[...this.hitEvent.normal],velocity:pose?.velocity||[0,0,0],nativeContactEvent:true};this.onImpact?.(detail);}}}
    for(const record of this.records.values()){const velocity=this.b3.b3Body_GetLinearVelocity([0,0,0],record.body),change=Math.hypot(velocity[0]-record.preVelocity[0],velocity[1]-record.preVelocity[1],velocity[2]-record.preVelocity[2]),threshold=record.drone?1.05:1.45;if(!this.eventsBuffer&&change>=threshold&&now-record.lastImpactAt>180){record.lastImpactAt=now;record.impactCount++;this.impactCount++;const pose=this.pose(record.id),detail={id:record.id,kind:record.kind,deltaVelocityMps:change,energyJ:.5*record.massKg*change*change,position:pose?.position||[0,0,0],velocity:pose?.velocity||velocity,nativeContactEvent:false};this.onImpact?.(detail);}record.lastVelocity=[...velocity];}return this.stepCount;
  }
  destroy(){for(const id of[...this.records.keys()])this.removeBody(id);destroyWorldBuildingCollisionBodies(this.b3,this.buildingState);this.buildingState=null;if(this.eventsBuffer)this.b3.destroyEventsBuffer?.(this.eventsBuffer);this.eventsBuffer=null;this.hitEvent=null;if(this.world&&this.b3.b3World_IsValid?.(this.world)!==false)this.b3.b3DestroyWorld(this.world);this.world=null;}
}
