import {WorldRigidBodyPhysics} from "./world_rigid_body_physics.mjs";

const FIXED_DT=1/60;
const MAX_STEPS_PER_FRAME=3;
const pendingBodies=new Map(),pendingTargets=new Map(),targetLeases=new Map();
let engine=null,lastFrame=performance.now(),accumulator=0,lastBuildingSync=-Infinity,lastTelemetry=-Infinity,bootError="",targetRejects=0;

function viewport(){return document.getElementById("viewport");}
function bridge(){return globalThis.__arondightRealWorld||null;}
function clamp(value,min,max){return Math.max(min,Math.min(max,Number(value)||0));}
function ownerPriority(owner,explicit){if(Number.isFinite(Number(explicit)))return clamp(explicit,0,1000);const name=String(owner||"");if(name==="local-player")return 100;if(name.startsWith("remote-player:"))return 90;if(name.startsWith("network-authority:"))return 80;if(name==="world-ai")return 10;return 20;}
function targetPayload(target={}){const payload={...target,position:Array.isArray(target.position)?[...target.position]:target.position};delete payload.owner;delete payload.priority;delete payload.leaseMs;return payload;}
function leaseFor(key,target={}){const now=performance.now(),owner=String(target.owner||"world-ai"),priority=ownerPriority(owner,target.priority),leaseMs=clamp(target.leaseMs??(owner==="world-ai"?0:420),0,5000),current=targetLeases.get(key);if(current&&current.owner!==owner&&current.expiresAt>now&&current.priority>priority){targetRejects++;const v=viewport();if(v){v.dataset.worldPhysicsTargetRejects=String(targetRejects);v.dataset.worldPhysicsTargetBlocked=`${owner}->${current.owner}`;}return null;}const lease={owner,priority,expiresAt:now+leaseMs};targetLeases.set(key,lease);return lease;}
function ensureEngine(){
  if(engine)return engine;const b3=globalThis.__arondightBox3dRuntime?.b3;if(!b3)return null;
  try{engine=new WorldRigidBodyPhysics(b3,{buildingSnapshot:bridge()?.buildingCollisionSnapshot,onImpact:detail=>{globalThis.dispatchEvent(new CustomEvent("arondight:world-physics-impact",{detail}));const v=viewport();if(v){v.dataset.worldPhysicsImpacts=String(engine?.impactCount||0);v.dataset.worldPhysicsLastImpact=detail.kind;v.dataset.worldPhysicsLastImpactMps=detail.deltaVelocityMps.toFixed(2);}}});for(const config of pendingBodies.values())engine.addBody(config);for(const[id,target]of pendingTargets)engine.setTarget(id,target);bootError="";}catch(error){bootError=String(error?.message||error);const v=viewport();if(v)v.dataset.worldRigidBodyError=bootError;return null;}return engine;
}
function upsertBody(config={}){const id=String(config.id||"");if(!id)return false;pendingBodies.set(id,{...config,id});const current=ensureEngine();if(current&&!current.records.has(id))current.addBody(pendingBodies.get(id));const target=pendingTargets.get(id);if(current&&target)current.setTarget(id,target);return true;}
function setTarget(id,target={}){const key=String(id||"");if(!key)return false;const lease=leaseFor(key,target);if(!lease)return true;const payload=targetPayload(target);pendingTargets.set(key,payload);const v=viewport();if(v){v.dataset.worldPhysicsControlAuthority="leased-owner-v2";v.dataset.worldPhysicsLastTargetOwner=lease.owner;}return ensureEngine()?.setTarget(key,payload)??true;}
function clearTarget(id,{owner=null,force=false}={}){const key=String(id||""),lease=targetLeases.get(key),now=performance.now();if(owner&&!force&&lease&&lease.expiresAt>now&&lease.owner!==String(owner))return false;pendingTargets.delete(key);targetLeases.delete(key);return ensureEngine()?.clearTarget(key)??false;}
function setPose(id,pose={}){const key=String(id||""),config=pendingBodies.get(key),position=pose?.position;if(!key||!config||!Array.isArray(position)||position.length!==3||!position.every(Number.isFinite))return false;const now=performance.now(),force=pose?.force===true,owner=String(pose?.owner||""),activeLease=targetLeases.get(key);let lease=null;if(force){targetLeases.delete(key);}else if(owner){lease=leaseFor(key,pose);if(!lease)return false;}else if(activeLease&&activeLease.expiresAt>now){targetRejects++;const v=viewport();if(v){v.dataset.worldPhysicsPoseRejects=String((Number(v.dataset.worldPhysicsPoseRejects)||0)+1);v.dataset.worldPhysicsPoseBlocked=`unowned->${activeLease.owner}`;v.dataset.worldPhysicsPoseBlockedId=key;}return false;}const payload=targetPayload(pose),current=ensureEngine();if(!current?.setPose(key,payload))return false;pendingBodies.set(key,{...config,position:[...position],...(Number.isFinite(pose.yaw)?{yaw:Number(pose.yaw)}:{})});const v=viewport();if(v){v.dataset.worldPhysicsLastPoseOwner=force?"force":owner||"unowned";v.dataset.worldPhysicsLastPoseId=key;v.dataset.worldPhysicsLastPoseYaw=Number.isFinite(pose.yaw)?Number(pose.yaw).toFixed(6):"keep";}return true;}
function setGravityScale(id,gravityScale=1){const key=String(id||""),value=Number(gravityScale),config=pendingBodies.get(key);if(!key||!Number.isFinite(value)||!config)return false;pendingBodies.set(key,{...config,gravityScale:value});return ensureEngine()?.setGravityScale(key,value)??true;}
function removeBody(id){const key=String(id||"");pendingBodies.delete(key);pendingTargets.delete(key);targetLeases.delete(key);return ensureEngine()?.removeBody(key)??false;}
function applyImpulse(id,impulse,options){return ensureEngine()?.applyImpulse(String(id||""),impulse,options)??false;}
function pose(id){return ensureEngine()?.pose(String(id||""))||null;}
function targetOwner(id){const lease=targetLeases.get(String(id||""));return lease&&lease.expiresAt>performance.now()?lease.owner:"";}

function updateTelemetry(now){if(now-lastTelemetry<250)return;lastTelemetry=now;const v=viewport(),current=engine;if(!v)return;const records=current?[...current.records.values()]:[],vehicles=records.filter(record=>!record.drone).length,drones=records.length-vehicles,leased=[...targetLeases.values()].filter(item=>item.expiresAt>now);v.dataset.worldRigidBodyPhysics=current?"box3d-dynamic-forces-v1":bootError?"error":"waiting-box3d";v.dataset.worldPhysicsBodies=String(records.length);v.dataset.worldPhysicsVehicles=String(vehicles);v.dataset.worldPhysicsDrones=String(drones);v.dataset.worldPhysicsImpacts=String(current?.impactCount||0);v.dataset.worldPhysicsSteps=String(current?.stepCount||0);v.dataset.worldPhysicsBuildingPrisms=String(current?.buildingState?.shapeCount||0);v.dataset.worldPhysicsContinuous="1";v.dataset.worldPhysicsControl="force+torque+impulse";v.dataset.worldPhysicsControlAuthority="leased-owner-v2";v.dataset.worldPhysicsControlDetail="force+torque+impulse+target+pose-authority-lease-v3";v.dataset.worldPhysicsLeasedTargets=String(leased.length);v.dataset.worldPhysicsTargetRejects=String(targetRejects);v.dataset.worldPhysicsGravityScale="runtime-v1";}
function frame(now=performance.now()){
  requestAnimationFrame(frame);const current=ensureEngine(),elapsed=Math.max(0,Math.min(.10,(now-lastFrame)/1000));lastFrame=now;if(!current){updateTelemetry(now);return;}if(now-lastBuildingSync>350){lastBuildingSync=now;current.syncBuildings(bridge()?.buildingCollisionSnapshot);}if(current.records.size){accumulator=Math.min(.075,accumulator+elapsed);let steps=0;while(accumulator>=FIXED_DT&&steps<MAX_STEPS_PER_FRAME){current.step(FIXED_DT,4,now);accumulator-=FIXED_DT;steps++;}}else accumulator=0;updateTelemetry(now);
}

export const worldRigidBodyRuntime=Object.freeze({upsertBody,setTarget,clearTarget,setPose,setGravityScale,removeBody,applyImpulse,pose,targetOwner,get ready(){return Boolean(ensureEngine());},get engine(){return ensureEngine();}});
globalThis.__arondightWorldRigidBodies=worldRigidBodyRuntime;
requestAnimationFrame(frame);
