import * as THREE from "three";
import {VS_FX_EVENT} from "./lan_vs.mjs";
import {AUDIO_SETTINGS_EVENT,loadAudioSettings,normalizeAudioSettings} from "./audio_settings.mjs";
import {spawnWorldPersonRagdoll} from "./world_person_ragdoll.mjs";
import {spawnWorldCarExplosion} from "./world_car_explosion.mjs";
import {buildTrafficRoute,collectRenderedDrivableRoads,makeBuildingsOpaque} from "./world_traffic_routes.mjs";
import {syncWorldBuildingDepthOcclusion} from "./world_building_depth_occlusion.mjs";

const MOBILE_RE=/(?:android|iphone|ipad|ipod|macintosh.*mobile)/i;
const ROUTE_REFRESH_MS=1800;
const ROUTE_STALE_MS=18000;
const ROUTE_DROP_MS=90000;
const MAX_ROUTE_POOL=72;
const WORLD_SYNC_MS=220;
const WORLD_SYNC_STALE_MS=1200;
const CAR_RESPAWN_MS=16000;
const PERSON_RESPAWN_MS=10000;
const RESPAWN_CLEARANCE_M=34;
const RESPAWN_FORCE_DELAY_MS=18000;
const MOBILE=MOBILE_RE.test(globalThis.navigator?.userAgent||"");
const CAR_COUNT=MOBILE?12:20;
const PERSON_COUNT=MOBILE?14:24;
const BLOOD_POOL_SIZE=MOBILE?32:48;
const BLOOD_BURST_COUNT=MOBILE?7:10;
const cars=[],people=[],routes=[],routeCache=new Map();
const pendingDead=new Map(),explosions=[],bloodParticles=[],seenWorldFx=new Set();
let installed=false,lastRouteRefresh=-Infinity,lastOriginKey="",raf=0,explosionGeometry=null,bloodGeometry=null,worldRoom=null,worldAction=null,lastWorldSyncMs=-Infinity,worldSyncSeq=0,lastWorldRxSeq=0,lastWorldRxAt=-Infinity,lastFrameMs=performance.now();
let audioContext=null,audioMaster=null,audioNoiseBuffer=null,audioSettings=loadAudioSettings(),bloodSeq=0;
const temp=new THREE.Vector3(),cameraPos=new THREE.Vector3(),impactDir=new THREE.Vector3(),netTarget=new THREE.Vector3(),bloodDir=new THREE.Vector3(),bloodSpread=new THREE.Vector3();
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));

function bridge(){return globalThis.__arondightRealWorld||null;}
function viewport(){return document.getElementById("viewport");}
function session(){return bridge()?.vsSession||null;}
function rawSession(){const s=session();return s?.active||s||null;}
function rawRoom(){const s=rawSession();return s?.room||null;}
function selfId(){const s=rawSession();try{return String(s?.getSelfId?.()||s?.room?.getSelfId?.()||"");}catch{return"";}}
function authorityId(){const s=rawSession();try{return String(s?.getAuthorityId?.()||s?.room?.getAuthorityId?.()||"");}catch{return"";}}
function peerCount(){const s=rawSession();try{return Number(s?.peerCount)||s?.getPeerIds?.().length||0;}catch{return 0;}}
function isAuthority(){const peers=peerCount();if(!peers)return true;const self=selfId(),authority=authorityId();return Boolean(self&&authority&&self===authority);}
function hashText(text){let h=2166136261;for(const c of String(text||"")){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function lngLatToMeters(lon0,lat0,lon,lat){const earth=6378137,north=(lat-lat0)*Math.PI/180*earth,east=(lon-lon0)*Math.PI/180*earth*Math.max(.01,Math.cos(lat0*Math.PI/180));return[east,north];}
function metersToLngLat(lon0,lat0,east,north){const earth=6378137,latitude=lat0+north/earth*180/Math.PI,longitude=lon0+east/(earth*Math.max(.01,Math.cos(lat0*Math.PI/180)))*180/Math.PI;return[longitude,latitude];}
function fallbackRoads(b){const out=[];for(const feature of b?.minimapFeatures||[]){if(feature?.kind!=="road")continue;for(const path of feature.paths||[])if(path?.length>=2)out.push({path,roadClass:String(feature.roadClass||"road")});}return out;}
function boundRouteKeys(){return new Set([...cars,...people].map(record=>record.routeKey).filter(Boolean));}
function refreshRoutes(now){
  const b=bridge();if(!b?.active||!Number.isFinite(b.originLon)||!Number.isFinite(b.originLat))return;
  const view=viewport(),originKey=`${b.originLon.toFixed(6)}:${b.originLat.toFixed(6)}`;
  if(now-lastRouteRefresh<ROUTE_REFRESH_MS&&originKey===lastOriginKey)return;lastRouteRefresh=now;
  const opaqueLayers=makeBuildingsOpaque(b.map),depthOccluders=syncWorldBuildingDepthOcclusion(b);if(view){view.dataset.worldBuildingsOpaque="1";view.dataset.worldBuildingsSolidified=String(opaqueLayers);view.dataset.worldBuildingDepthOccluders=String(depthOccluders);}
  if(originKey!==lastOriginKey&&routeCache.size){for(const [key,old] of routeCache){const rebuilt=buildTrafficRoute(old.geoPath,{originLon:b.originLon,originLat:b.originLat,roadClass:old.roadClass,lastSeen:old.lastSeen});if(rebuilt)routeCache.set(key,rebuilt);}}lastOriginKey=originKey;
  let candidates=[];try{candidates=collectRenderedDrivableRoads(b.map);}catch(error){console.warn("WORLD traffic road query warning:",error);}if(!candidates.length)candidates=fallbackRoads(b);
  const seen=new Set();for(const candidate of candidates){const route=buildTrafficRoute(candidate.path,{originLon:b.originLon,originLat:b.originLat,roadClass:candidate.roadClass,lastSeen:now});if(!route||seen.has(route.key))continue;seen.add(route.key);routeCache.set(route.key,route);}
  const bound=boundRouteKeys();for(const [key,route] of routeCache)if(now-route.lastSeen>ROUTE_DROP_MS&&!bound.has(key))routeCache.delete(key);
  const fresh=[...routeCache.values()].filter(route=>now-route.lastSeen<=ROUTE_STALE_MS),pool=(fresh.length?fresh:[...routeCache.values()]).sort((a,c)=>a.key.localeCompare(c.key)).slice(0,MAX_ROUTE_POOL);routes.splice(0,routes.length,...pool);
  if(view){view.dataset.worldTrafficRoutes=String(routes.length);view.dataset.worldTrafficCachedRoutes=String(routeCache.size);view.dataset.worldTrafficStable="1";view.dataset.worldCars=String(CAR_COUNT);view.dataset.worldPeople=String(PERSON_COUNT);view.dataset.worldPopulationDensity="enhanced";}
}
function sampleRoute(route,distance,laneOffset=0){if(!route?.segments?.length)return null;const period=route.length*2,cycle=((distance%period)+period)%period,reverse=cycle>route.length,d=reverse?period-cycle:cycle;let segment=route.segments.at(-1);for(const s of route.segments)if(d<=s.start+s.d){segment=s;break;}const t=Math.max(0,Math.min(1,(d-segment.start)/segment.d)),x=segment.a[0]+segment.dx*t,y=segment.a[1]+segment.dy*t,nx=-segment.dy/segment.d,ny=segment.dx/segment.d,lane=laneOffset;return{x:x+nx*lane,y:y+ny*lane,yaw:Math.atan2(segment.dy,segment.dx)+(reverse?Math.PI:0),reverse};}
function laneOffset(route,record,person=false){if(person)return record.side;const cls=String(route?.roadClass||""),magnitude=/motorway|trunk|primary|secondary/.test(cls)?1.15:/service|minor|living/.test(cls)?0.62:0.82;return(record.laneSign||1)*magnitude;}
function makeCar(index){const group=new THREE.Group(),seed=hashText(`car:${index}`),color=[0xd53d32,0x2f82d7,0xd9b53b,0xe7e7e7,0x24282d,0x45a85a][seed%6],bodyMat=new THREE.MeshStandardMaterial({color,roughness:.38,metalness:.35}),glassMat=new THREE.MeshStandardMaterial({color:0x18364f,roughness:.18,metalness:.2});const body=new THREE.Mesh(new THREE.BoxGeometry(3.8,1.75,.72),bodyMat);body.position.z=.48;const roof=new THREE.Mesh(new THREE.BoxGeometry(2.0,1.52,.58),glassMat);roof.position.set(-.15,0,1.03);for(const mesh of[body,roof]){mesh.castShadow=true;mesh.userData.worldPopulationKind="car";}group.add(body,roof);group.userData.worldPopulationKind="car";group.visible=false;bridge()?.threeScene?.add(group);return{id:"",kind:"car",index,color,group,routeKey:"",speed:7+(seed%70)/10,phase01:(seed%10000)/10000,laneSign:seed&1?1:-1,deadUntil:0,deadStarted:0,forceRespawnAt:0,netTarget:new THREE.Vector3(),netYaw:0,netSeenAt:-Infinity,netId:""};}
function makePerson(index){const group=new THREE.Group(),seed=hashText(`person:${index}`),shirt=new THREE.MeshStandardMaterial({color:[0x32a4d8,0xd85a42,0x5cbb57,0xd4b640,0x835dcc][seed%5],roughness:.7}),skin=new THREE.MeshStandardMaterial({color:0xd6a27e,roughness:.8}),body=new THREE.Mesh(new THREE.CapsuleGeometry(.20,.70,3,6),shirt),head=new THREE.Mesh(new THREE.SphereGeometry(.19,7,5),skin);body.position.z=.58;head.position.z=1.18;for(const mesh of[body,head])mesh.userData.worldPopulationKind="person";group.add(body,head);group.userData.worldPopulationKind="person";group.visible=false;bridge()?.threeScene?.add(group);return{id:"",kind:"person",index,group,routeKey:"",speed:1.1+(seed%55)/100,phase01:(seed%8000)/8000,side:(seed&1?1:-1)*2.55,deadUntil:0,deadStarted:0,forceRespawnAt:0,netTarget:new THREE.Vector3(),netYaw:0,netSeenAt:-Infinity,netId:""};}
function ensurePools(){const scene=bridge()?.threeScene;if(!scene)return;while(cars.length<CAR_COUNT)cars.push(makeCar(cars.length));while(people.length<PERSON_COUNT)people.push(makePerson(people.length));if(!explosionGeometry){explosionGeometry=new THREE.SphereGeometry(.16,7,5);for(let i=0;i<16;i++){const material=new THREE.MeshBasicMaterial({color:i%2?0xff5a27:0xffc45a,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}),mesh=new THREE.Mesh(explosionGeometry,material);mesh.visible=false;mesh.renderOrder=17;mesh.userData.flightFireIgnore=true;scene.add(mesh);explosions.push({mesh,born:0,expires:0});}}if(!bloodGeometry){bloodGeometry=new THREE.SphereGeometry(.026,5,4);for(let i=0;i<BLOOD_POOL_SIZE;i++){const material=new THREE.MeshBasicMaterial({color:i%3===0?0x6f0000:0xb20b0b,transparent:true,opacity:0,depthWrite:false}),mesh=new THREE.Mesh(bloodGeometry,material);mesh.visible=false;mesh.renderOrder=18;mesh.frustumCulled=false;mesh.userData.flightFireIgnore=true;mesh.userData.worldBloodParticle=true;scene.add(mesh);bloodParticles.push({mesh,velocity:new THREE.Vector3(),born:0,expires:0});}const view=viewport();if(view)view.dataset.worldBloodPool=String(BLOOD_POOL_SIZE);}}
function setIdentity(record,id,routeKey=""){record.id=String(id||"");if(routeKey)record.routeKey=routeKey;record.group.userData.worldPopulationId=record.id;record.group.traverse(node=>{if(node?.isMesh){node.userData.worldPopulationId=record.id;node.userData.worldPopulationKind=record.kind;}});}
function assign(record,route,slot){if(!route){record.id="";record.group.visible=false;return;}setIdentity(record,`${record.kind}-${route.key}-${slot}`,route.key);const dead=pendingDead.get(record.id);if(dead)record.deadUntil=Math.max(record.deadUntil,dead);}
function routeFor(record,person=false){let route=routeCache.get(record.routeKey);if(route)return route;if(!routes.length)return null;route=routes[(record.index*7+(person?3:0))%routes.length];assign(record,route,record.index);return route;}
function spawnExplosion(position){ensurePools();const item=explosions.find(x=>!x.mesh.visible)||explosions[hashText(`${position.x}:${position.y}`)%explosions.length];item.born=performance.now();item.expires=item.born+900;item.mesh.position.copy(position);item.mesh.scale.setScalar(1);item.mesh.material.opacity=.95;item.mesh.visible=true;}
function nextRandom(){bloodSeq=(Math.imul((bloodSeq||0)+0x6d2b79f5,1664525)+1013904223)>>>0;return bloodSeq/0xffffffff;}
function spawnBloodBurst(position,impulse=[1,0,1]){ensurePools();if(!position||!bloodParticles.length)return;bloodDir.set(Number(impulse?.[0])||1,Number(impulse?.[1])||0,Number(impulse?.[2])||1);if(bloodDir.lengthSq()<1e-6)bloodDir.set(1,0,1);bloodDir.normalize();const now=performance.now();for(let i=0;i<BLOOD_BURST_COUNT;i++){const item=bloodParticles.find(x=>!x.mesh.visible)||bloodParticles[(bloodSeq+i)%bloodParticles.length],spreadX=(nextRandom()-.5)*2.4,spreadY=(nextRandom()-.5)*2.4,spreadZ=.8+nextRandom()*2.1,speed=.8+nextRandom()*1.8;item.mesh.position.set(position.x,position.y,position.z+.72);bloodSpread.set(spreadX,spreadY,spreadZ);item.velocity.copy(bloodDir).multiplyScalar(speed).add(bloodSpread);item.mesh.scale.setScalar(.7+nextRandom()*1.2);item.mesh.material.opacity=.78;item.mesh.visible=true;item.born=now;item.expires=now+520+nextRandom()*420;}const view=viewport();if(view)view.dataset.worldBloodBursts=String((Number(view.dataset.worldBloodBursts)||0)+1);}
function updateBlood(now,dt){for(const item of bloodParticles){if(!item.mesh.visible)continue;if(now>=item.expires||item.mesh.position.z<=.018){item.mesh.visible=false;item.mesh.material.opacity=0;continue;}item.velocity.z-=9.80665*dt;item.mesh.position.addScaledVector(item.velocity,dt);const life=Math.max(1,item.expires-item.born),t=(now-item.born)/life;item.mesh.material.opacity=Math.max(0,.78*(1-t));}}
function applyAudioSettings(value=loadAudioSettings()){audioSettings=normalizeAudioSettings(value);if(audioMaster&&audioContext)audioMaster.gain.setTargetAtTime(audioSettings.soundEnabled?1:0,audioContext.currentTime,.012);const view=viewport();if(view){view.dataset.worldFxAudioEnabled=audioSettings.soundEnabled?"1":"0";view.dataset.worldFxVolumePct=String(audioSettings.fxVolume);}return audioSettings;}
function ensureAudio(){if(audioContext)return audioContext;const Ctx=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Ctx)return null;try{audioContext=new Ctx({latencyHint:"interactive"});audioMaster=audioContext.createGain();audioMaster.gain.value=audioSettings.soundEnabled?1:0;audioMaster.connect(audioContext.destination);audioNoiseBuffer=audioContext.createBuffer(1,Math.max(1,Math.floor(audioContext.sampleRate*.95)),audioContext.sampleRate);const data=audioNoiseBuffer.getChannelData(0);let seed=0x51a77e;for(let i=0;i<data.length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;data[i]=(seed/0xffffffff*2-1)*(1-i/data.length*.28);}return audioContext;}catch{return null;}}
function primeAudio(){const ctx=ensureAudio();if(ctx?.state==="suspended")ctx.resume().catch(()=>{});}
function distanceGain(position){const camera=bridge()?.threeCamera;if(!camera?.getWorldPosition||!position)return 1;camera.getWorldPosition(cameraPos);const d=cameraPos.distanceTo(position);return clamp(1-(d-18)/180,.14,1);}
function playCarExplosionSound(position){if(!audioSettings.soundEnabled||audioSettings.fxVolume<=0)return false;const ctx=ensureAudio(),level=audioSettings.fxVolume/100*distanceGain(position);if(!ctx||!audioMaster||!audioNoiseBuffer)return false;try{if(ctx.state==="suspended")ctx.resume().catch(()=>{});const t=ctx.currentTime,src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();src.buffer=audioNoiseBuffer;filter.type="lowpass";filter.frequency.setValueAtTime(1250,t);filter.frequency.exponentialRampToValueAtTime(110,t+.8);gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(.48*level,t+.008);gain.gain.exponentialRampToValueAtTime(.0001,t+.86);src.connect(filter).connect(gain).connect(audioMaster);const boom=ctx.createOscillator(),boomGain=ctx.createGain();boom.type="sine";boom.frequency.setValueAtTime(102,t);boom.frequency.exponentialRampToValueAtTime(31,t+.62);boomGain.gain.setValueAtTime(.0001,t);boomGain.gain.exponentialRampToValueAtTime(.62*level,t+.006);boomGain.gain.exponentialRampToValueAtTime(.0001,t+.72);boom.connect(boomGain).connect(audioMaster);const crack=ctx.createOscillator(),crackGain=ctx.createGain();crack.type="triangle";crack.frequency.setValueAtTime(240,t);crack.frequency.exponentialRampToValueAtTime(62,t+.2);crackGain.gain.setValueAtTime(.0001,t);crackGain.gain.exponentialRampToValueAtTime(.18*level,t+.003);crackGain.gain.exponentialRampToValueAtTime(.0001,t+.24);crack.connect(crackGain).connect(audioMaster);src.start(t);src.stop(t+.9);boom.start(t);boom.stop(t+.74);crack.start(t);crack.stop(t+.26);const view=viewport();if(view)view.dataset.worldCarExplosionSoundCount=String((Number(view.dataset.worldCarExplosionSoundCount)||0)+1);return true;}catch{return false;}}
function playPersonGroan(position){if(!audioSettings.soundEnabled||audioSettings.fxVolume<=0)return false;const ctx=ensureAudio(),level=audioSettings.fxVolume/100*distanceGain(position);if(!ctx||!audioMaster||!audioNoiseBuffer)return false;try{if(ctx.state==="suspended")ctx.resume().catch(()=>{});const t=ctx.currentTime,voice=ctx.createOscillator(),voiceGain=ctx.createGain(),vibrato=ctx.createOscillator(),vibratoGain=ctx.createGain();voice.type="triangle";voice.frequency.setValueAtTime(176,t);voice.frequency.exponentialRampToValueAtTime(108,t+.48);vibrato.type="sine";vibrato.frequency.value=12;vibratoGain.gain.value=6;vibrato.connect(vibratoGain).connect(voice.frequency);voiceGain.gain.setValueAtTime(.0001,t);voiceGain.gain.exponentialRampToValueAtTime(.11*level,t+.018);voiceGain.gain.exponentialRampToValueAtTime(.075*level,t+.19);voiceGain.gain.exponentialRampToValueAtTime(.0001,t+.53);voice.connect(voiceGain).connect(audioMaster);const breath=ctx.createBufferSource(),breathFilter=ctx.createBiquadFilter(),breathGain=ctx.createGain();breath.buffer=audioNoiseBuffer;breathFilter.type="bandpass";breathFilter.frequency.value=520;breathFilter.Q.value=.8;breathGain.gain.setValueAtTime(.035*level,t);breathGain.gain.exponentialRampToValueAtTime(.0001,t+.24);breath.connect(breathFilter).connect(breathGain).connect(audioMaster);voice.start(t);voice.stop(t+.55);vibrato.start(t);vibrato.stop(t+.55);breath.start(t);breath.stop(t+.25);const view=viewport();if(view)view.dataset.worldPersonGroanCount=String((Number(view.dataset.worldPersonGroanCount)||0)+1);return true;}catch{return false;}}
function personImpulseAt(position){const camera=bridge()?.threeCamera;if(camera?.getWorldPosition){camera.getWorldPosition(cameraPos);impactDir.copy(position).sub(cameraPos);if(impactDir.lengthSq()<1e-6)impactDir.set(1,0,0);impactDir.normalize().multiplyScalar(4.6);}else impactDir.set(2.8,0,0);impactDir.z=Math.max(2.2,impactDir.z+2.0);return[impactDir.x,impactDir.y,impactDir.z];}
function spawnPersonDeath(record,position,impulse=null,yaw=null){if(!record&&!position)return false;const p=position||temp,angle=Number.isFinite(Number(yaw))?Number(yaw):Number(record?.group?.rotation?.z)||0,kick=Array.isArray(impulse)?impulse:personImpulseAt(p),id=String(record?.id||"");spawnBloodBurst(p,kick);playPersonGroan(p);return spawnWorldPersonRagdoll({position:[p.x,p.y,p.z],yaw:angle,impulse:kick,seed:id||`${p.x}:${p.y}`,id});}
function carVelocity(record,yaw=record?.group?.rotation?.z||0){return[Math.cos(yaw)*(record?.speed||0),Math.sin(yaw)*(record?.speed||0),0];}
function spawnCarDeath(record,position,yaw=record?.group?.rotation?.z||0,velocity=null,color=record?.color||0x777777){const p=position||temp,v=Array.isArray(velocity)?velocity:carVelocity(record,yaw);spawnExplosion(p);playCarExplosionSound(p);spawnWorldCarExplosion({position:[p.x,p.y,p.z],yaw,velocity:v,color,seed:record?.id||`${p.x}:${p.y}`,id:record?.id||""});return v;}
function markDead(record,{network=false}={}){if(!record||!record.id)return false;const now=Date.now(),ttl=record.kind==="car"?CAR_RESPAWN_MS:PERSON_RESPAWN_MS;record.deadStarted=now;record.deadUntil=Math.max(record.deadUntil,now+ttl);record.forceRespawnAt=record.deadUntil+RESPAWN_FORCE_DELAY_MS;pendingDead.set(record.id,record.deadUntil);record.group.getWorldPosition(temp);const p=[temp.x,temp.y,temp.z],yaw=Number(record.group.rotation.z)||0;let impulse=null,velocity=null;if(record.kind==="car")velocity=spawnCarDeath(record,temp,yaw);else{impulse=personImpulseAt(temp);spawnPersonDeath(record,temp,impulse,yaw);}record.group.visible=false;if(network){const s=session(),packet={type:record.kind==="car"?"explosion":"impact",id:`world-${record.id}-${now.toString(36)}`,p,objectId:record.id,kind:record.kind,yaw};if(record.kind==="person")packet.impulse=impulse;else{packet.velocity=velocity;packet.color=record.color;}s?.sendFx?.(packet);}return true;}
function recordById(id){return cars.find(x=>x.id===id)||people.find(x=>x.id===id)||null;}
function rememberFx(id){id=String(id||"");if(!id||seenWorldFx.has(id))return false;seenWorldFx.add(id);if(seenWorldFx.size>512)seenWorldFx.delete(seenWorldFx.values().next().value);return true;}
function handleRemoteFx(event){const packet=event.detail?.packet,id=String(packet?.objectId||"");if(!id||!/^car-|^person-/.test(id)||!rememberFx(packet?.id))return;const ttl=String(packet.kind)==="person"?PERSON_RESPAWN_MS:CAR_RESPAWN_MS,pending=Date.now()+ttl,record=recordById(id),wasAlive=!record||Date.now()>=record.deadUntil;if(record){record.deadStarted=Date.now();record.deadUntil=Math.max(record.deadUntil,pending);record.forceRespawnAt=record.deadUntil+RESPAWN_FORCE_DELAY_MS;record.group.visible=false;}pendingDead.set(id,pending);if(packet.type==="explosion"&&Array.isArray(packet.p)&&wasAlive){temp.set(Number(packet.p[0])||0,Number(packet.p[1])||0,Number(packet.p[2])||0);spawnExplosion(temp);playCarExplosionSound(temp);spawnWorldCarExplosion({position:[temp.x,temp.y,temp.z],yaw:Number(packet.yaw)||0,velocity:Array.isArray(packet.velocity)?packet.velocity:[0,0,0],color:Number(packet.color)||record?.color||0x777777,seed:id,id});}else if(packet.type==="impact"&&String(packet.kind)==="person"&&Array.isArray(packet.p)&&wasAlive){temp.set(Number(packet.p[0])||0,Number(packet.p[1])||0,Number(packet.p[2])||0);const impulse=Array.isArray(packet.impulse)?packet.impulse:[2.8,0,2.2];spawnBloodBurst(temp,impulse);playPersonGroan(temp);spawnWorldPersonRagdoll({position:[temp.x,temp.y,temp.z],yaw:Number(packet.yaw)||0,impulse,seed:id,id});}}
function offscreenEnough(record){const camera=bridge()?.threeCamera;if(!camera?.getWorldPosition)return true;camera.getWorldPosition(cameraPos);return cameraPos.distanceTo(record.group.position)>=RESPAWN_CLEARANCE_M;}
function respawnAllowed(record,nowEpoch){if(nowEpoch<record.deadUntil)return false;if(!record.deadStarted)return true;if(nowEpoch>=record.forceRespawnAt||offscreenEnough(record)){record.deadStarted=0;record.deadUntil=0;record.forceRespawnAt=0;pendingDead.delete(record.id);return true;}record.deadUntil=nowEpoch+900;return false;}
function deterministicPosition(record,route,epochSeconds,person=false){const distance=epochSeconds*record.speed+route.length*record.phase01;return sampleRoute(route,distance,laneOffset(route,record,person));}
function angleLerp(a,b,t){let d=(b-a+Math.PI)%(Math.PI*2)-Math.PI;if(d< -Math.PI)d+=Math.PI*2;return a+d*t;}
function updateRecord(record,nowMs,epochSeconds,person=false){const nowEpoch=Date.now(),networkFollower=peerCount()>0&&!isAuthority()&&nowMs-lastWorldRxAt<WORLD_SYNC_STALE_MS&&record.netSeenAt===lastWorldRxAt;if(networkFollower){if(nowEpoch<record.deadUntil){record.group.visible=false;return;}const alpha=1-Math.exp(-Math.min(.05,Math.max(.001,(nowMs-(record.lastRenderMs||nowMs))/1000))*12);record.lastRenderMs=nowMs;record.group.position.lerp(record.netTarget,alpha);record.group.rotation.z=angleLerp(record.group.rotation.z,record.netYaw,alpha);record.group.visible=Boolean(bridge()?.active);return;}const route=routeFor(record,person);if(!route){record.group.visible=false;return;}const sample=deterministicPosition(record,route,epochSeconds,person);if(!sample){record.group.visible=false;return;}record.group.position.set(sample.x,sample.y,0);record.group.rotation.x=0;record.group.rotation.z=sample.yaw;if(!respawnAllowed(record,nowEpoch)){record.group.visible=false;return;}record.group.visible=Boolean(bridge()?.active);}
function updateExplosions(now){for(const item of explosions){if(!item.mesh.visible)continue;if(now>=item.expires){item.mesh.visible=false;continue;}const t=(now-item.born)/(item.expires-item.born);item.mesh.scale.setScalar(.8+8*t);item.mesh.material.opacity=Math.max(0,.95*(1-t));}}
function ensureWorldAction(){const room=rawRoom();if(room===worldRoom)return;worldRoom=room;worldAction=null;lastWorldRxSeq=0;if(!room?.makeAction)return;try{const action=room.makeAction("world-population");if(!action?.send)return;worldAction=action;action.onMessage=(packet,{peerId}={})=>handleWorldState(packet,peerId);}catch(error){console.warn("WORLD population sync unavailable:",error);}}
function compactGeo(record,b){const [lon,lat]=metersToLngLat(b.originLon,b.originLat,record.group.position.x,record.group.position.y);return[Number(lon.toFixed(7)),Number(lat.toFixed(7))];}
function sendWorldState(now){if(!worldAction||!isAuthority()||peerCount()<1||now-lastWorldSyncMs<WORLD_SYNC_MS)return;const b=bridge();if(!Number.isFinite(b?.originLon)||!Number.isFinite(b?.originLat))return;lastWorldSyncMs=now;const objects=[];for(const record of[...cars,...people]){if(!record.id)continue;objects.push({i:record.index,k:record.kind==="car"?"c":"p",id:record.id,g:compactGeo(record,b),y:Number((record.group.rotation.z||0).toFixed(5)),d:Math.max(0,Math.round(record.deadUntil))});}try{Promise.resolve(worldAction.send({v:1,seq:++worldSyncSeq,t:Date.now(),objects})).catch(()=>{});const view=viewport();if(view){view.dataset.worldTrafficAuthority="1";view.dataset.worldTrafficSyncSeq=String(worldSyncSeq);}}catch{}}
function handleWorldState(packet,peerId){if(!packet||packet.v!==1||!Array.isArray(packet.objects)||packet.objects.length>CAR_COUNT+PERSON_COUNT+4)return;const auth=authorityId();if(auth&&String(peerId||"")!==auth)return;const seq=Number(packet.seq)||0;if(seq&&seq<=lastWorldRxSeq)return;lastWorldRxSeq=seq;const b=bridge();if(!Number.isFinite(b?.originLon)||!Number.isFinite(b?.originLat))return;lastWorldRxAt=performance.now();for(const item of packet.objects){const list=item?.k==="c"?cars:item?.k==="p"?people:null,index=Number(item?.i);if(!list||!Number.isInteger(index)||index<0||index>=list.length||!Array.isArray(item.g)||item.g.length!==2)continue;const lon=Number(item.g[0]),lat=Number(item.g[1]);if(!Number.isFinite(lon)||!Number.isFinite(lat))continue;const record=list[index],local=lngLatToMeters(b.originLon,b.originLat,lon,lat),id=String(item.id||"");if(id&&id!==record.id){const parts=id.split("-");setIdentity(record,id,parts.length>=3?parts.slice(1,-1).join("-"):record.routeKey);}record.netTarget.set(local[0],local[1],0);record.netYaw=Number(item.y)||0;record.netSeenAt=lastWorldRxAt;const dead=Number(item.d)||0;if(dead>record.deadUntil)record.deadUntil=dead;}const view=viewport();if(view){view.dataset.worldTrafficAuthority="0";view.dataset.worldTrafficRemoteSync=String(lastWorldRxSeq);}}
function frame(now=performance.now()){raf=requestAnimationFrame(frame);const b=bridge();if(!b?.threeScene){lastFrameMs=now;return;}ensurePools();ensureWorldAction();refreshRoutes(now);const epoch=Date.now()/1000,dt=Math.min(.05,Math.max(0,(now-lastFrameMs)/1000||0));lastFrameMs=now;for(const car of cars)updateRecord(car,now,epoch,false);for(const person of people)updateRecord(person,now,epoch,true);sendWorldState(now);updateExplosions(now);updateBlood(now,dt);}
function installHitHook(){const b=bridge();if(!b)return;if(!b.__worldPopulationHitHook){b.__worldPopulationHitHook=true;b.registerWorldPopulationHit=hit=>{let node=hit?.object;while(node&&!node.userData?.worldPopulationId)node=node.parent;if(!node)return false;const record=recordById(String(node.userData.worldPopulationId||""));if(!record||Date.now()<record.deadUntil)return Boolean(record);markDead(record,{network:true});const view=viewport();if(view){view.dataset.worldPopulationHits=String((Number(view.dataset.worldPopulationHits)||0)+1);view.dataset.worldPopulationLastHit=record.kind;}return true;};}if(!b.__worldPopulationRegisterShim&&typeof b.registerVsHit==="function"){b.__worldPopulationRegisterShim=true;const base=b.registerVsHit.bind(b);b.registerVsHit=hit=>b.registerWorldPopulationHit?.(hit)||base(hit);}}
function hookLoop(){installHitHook();setTimeout(hookLoop,500);}

export function installWorldPopulation(){if(installed)return;installed=true;applyAudioSettings(audioSettings);globalThis.addEventListener(VS_FX_EVENT,handleRemoteFx);globalThis.addEventListener(AUDIO_SETTINGS_EVENT,event=>applyAudioSettings(event.detail));document.addEventListener("pointerdown",primeAudio,{passive:true,capture:true});document.addEventListener("touchstart",primeAudio,{passive:true,capture:true});hookLoop();raf=requestAnimationFrame(frame);}
