import * as THREE from "three";
import {VS_FX_EVENT} from "./lan_vs.mjs";

const MOBILE_RE=/(?:android|iphone|ipad|ipod|macintosh.*mobile)/i;
const ROUTE_REFRESH_MS=2200;
const CAR_RESPAWN_MS=16000;
const PERSON_RESPAWN_MS=10000;
const CAR_COUNT=MOBILE_RE.test(navigator.userAgent||"")?8:14;
const PERSON_COUNT=MOBILE_RE.test(navigator.userAgent||"")?8:14;
const cars=[],people=[],routes=[];
const pendingDead=new Map(),explosions=[];
let installed=false,lastRouteRefresh=-Infinity,lastOriginKey="",raf=0,explosionGeometry=null;
const temp=new THREE.Vector3();

function bridge(){return globalThis.__arondightRealWorld||null;}
function viewport(){return document.getElementById("viewport");}
function session(){return bridge()?.vsSession||null;}
function hashText(text){let h=2166136261;for(const c of String(text||"")){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function lngLatToMeters(lon0,lat0,lon,lat){const earth=6378137,north=(lat-lat0)*Math.PI/180*earth,east=(lon-lon0)*Math.PI/180*earth*Math.max(.01,Math.cos(lat0*Math.PI/180));return[east,north];}
function routeKey(path){return`r${hashText(path.map(p=>`${Number(p[0]).toFixed(5)},${Number(p[1]).toFixed(5)}`).join(";" )).toString(36)}`;}
function buildRoute(path,b){const points=path.map(([lon,lat])=>lngLatToMeters(b.originLon,b.originLat,Number(lon),Number(lat))).filter(p=>p.every(Number.isFinite)),segments=[];let length=0;for(let i=0;i<points.length-1;i++){const a=points[i],c=points[i+1],dx=c[0]-a[0],dy=c[1]-a[1],d=Math.hypot(dx,dy);if(d<1)continue;segments.push({a,c,dx,dy,d,start:length});length+=d;}return length>=18&&segments.length?{key:routeKey(path),points,segments,length}:null;}
function refreshRoutes(now){const b=bridge();if(!b?.active||!Number.isFinite(b.originLon)||!Number.isFinite(b.originLat)||!Array.isArray(b.minimapFeatures))return;const originKey=`${b.originLon.toFixed(6)}:${b.originLat.toFixed(6)}`;if(originKey===lastOriginKey&&now-lastRouteRefresh<ROUTE_REFRESH_MS)return;lastRouteRefresh=now;lastOriginKey=originKey;const next=[];for(const feature of b.minimapFeatures){if(feature?.kind!=="road")continue;for(const path of feature.paths||[]){const r=buildRoute(path,b);if(r)next.push(r);}}next.sort((a,c)=>a.key.localeCompare(c.key));routes.splice(0,routes.length,...next.slice(0,48));const view=viewport();if(view){view.dataset.worldTrafficRoutes=String(routes.length);view.dataset.worldCars=String(CAR_COUNT);view.dataset.worldPeople=String(PERSON_COUNT);}}
function sampleRoute(route,distance,laneOffset=0){if(!route?.segments?.length)return null;let d=((distance%route.length)+route.length)%route.length,segment=route.segments.at(-1);for(const s of route.segments)if(d<=s.start+s.d){segment=s;break;}const t=Math.max(0,Math.min(1,(d-segment.start)/segment.d)),x=segment.a[0]+segment.dx*t,y=segment.a[1]+segment.dy*t,nx=-segment.dy/segment.d,ny=segment.dx/segment.d;return{x:x+nx*laneOffset,y:y+ny*laneOffset,yaw:Math.atan2(segment.dy,segment.dx)};}
function makeCar(index){const group=new THREE.Group(),seed=hashText(`car:${index}`),color=[0xd53d32,0x2f82d7,0xd9b53b,0xe7e7e7,0x24282d,0x45a85a][seed%6],bodyMat=new THREE.MeshStandardMaterial({color,roughness:.38,metalness:.35}),glassMat=new THREE.MeshStandardMaterial({color:0x18364f,roughness:.18,metalness:.2});const body=new THREE.Mesh(new THREE.BoxGeometry(3.8,1.75,.72),bodyMat);body.position.z=.48;const roof=new THREE.Mesh(new THREE.BoxGeometry(2.0,1.52,.58),glassMat);roof.position.set(-.15,0,1.03);for(const mesh of[body,roof]){mesh.castShadow=true;mesh.userData.worldPopulationKind="car";}group.add(body,roof);group.userData.worldPopulationKind="car";group.visible=false;bridge()?.threeScene?.add(group);return{id:"",kind:"car",index,group,routeKey:"",speed:7+(seed%70)/10,phase:(seed%10000)/100,lane:(seed&1?1:-1)*1.45,deadUntil:0,deadAt:0};}
function makePerson(index){const group=new THREE.Group(),seed=hashText(`person:${index}`),shirt=new THREE.MeshStandardMaterial({color:[0x32a4d8,0xd85a42,0x5cbb57,0xd4b640,0x835dcc][seed%5],roughness:.7}),skin=new THREE.MeshStandardMaterial({color:0xd6a27e,roughness:.8}),body=new THREE.Mesh(new THREE.CapsuleGeometry(.20,.70,3,6),shirt),head=new THREE.Mesh(new THREE.SphereGeometry(.19,7,5),skin);body.position.z=.58;head.position.z=1.18;for(const mesh of[body,head])mesh.userData.worldPopulationKind="person";group.add(body,head);group.userData.worldPopulationKind="person";group.visible=false;bridge()?.threeScene?.add(group);return{id:"",kind:"person",index,group,routeKey:"",speed:1.1+(seed%55)/100,phase:(seed%8000)/100,side:(seed&1?1:-1)*3.05,deadUntil:0,deadAt:0};}
function ensurePools(){const scene=bridge()?.threeScene;if(!scene)return;while(cars.length<CAR_COUNT)cars.push(makeCar(cars.length));while(people.length<PERSON_COUNT)people.push(makePerson(people.length));if(!explosionGeometry){explosionGeometry=new THREE.SphereGeometry(.16,7,5);for(let i=0;i<16;i++){const material=new THREE.MeshBasicMaterial({color:i%2?0xff5a27:0xffc45a,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}),mesh=new THREE.Mesh(explosionGeometry,material);mesh.visible=false;mesh.renderOrder=17;mesh.userData.flightFireIgnore=true;scene.add(mesh);explosions.push({mesh,born:0,expires:0});}}}
function assign(record,route,slot){if(!route){record.id="";record.group.visible=false;return;}record.routeKey=route.key;record.id=`${record.kind}-${route.key}-${slot}`;record.group.userData.worldPopulationId=record.id;record.group.traverse(node=>{if(node?.isMesh){node.userData.worldPopulationId=record.id;node.userData.worldPopulationKind=record.kind;}});const dead=pendingDead.get(record.id);if(dead)record.deadUntil=Math.max(record.deadUntil,dead);}
function spawnExplosion(position){ensurePools();const item=explosions.find(x=>!x.mesh.visible)||explosions[hashText(`${position.x}:${position.y}`)%explosions.length];item.born=performance.now();item.expires=item.born+900;item.mesh.position.copy(position);item.mesh.scale.setScalar(1);item.mesh.material.opacity=.95;item.mesh.visible=true;}
function markDead(record,{network=false}={}){if(!record||!record.id)return false;const now=Date.now(),ttl=record.kind==="car"?CAR_RESPAWN_MS:PERSON_RESPAWN_MS;record.deadUntil=Math.max(record.deadUntil,now+ttl);record.deadAt=performance.now();pendingDead.set(record.id,record.deadUntil);record.group.getWorldPosition(temp);const p=[temp.x,temp.y,temp.z];if(record.kind==="car")spawnExplosion(temp);if(network){const s=session(),packet={type:record.kind==="car"?"explosion":"impact",id:`world-${record.id}-${now.toString(36)}`,p,objectId:record.id,kind:record.kind};s?.sendFx?.(packet);}return true;}
function recordById(id){return cars.find(x=>x.id===id)||people.find(x=>x.id===id)||null;}
function handleRemoteFx(event){const packet=event.detail?.packet,id=String(packet?.objectId||"");if(!id||!/^car-|^person-/.test(id))return;const ttl=String(packet.kind)==="person"?PERSON_RESPAWN_MS:CAR_RESPAWN_MS,pending=Date.now()+ttl;pendingDead.set(id,pending);const record=recordById(id);if(record){record.deadUntil=Math.max(record.deadUntil,pending);record.deadAt=performance.now();}if(packet.type==="explosion"&&Array.isArray(packet.p)){temp.set(Number(packet.p[0])||0,Number(packet.p[1])||0,Number(packet.p[2])||0);spawnExplosion(temp);}}
function updateRecord(record,nowMs,epochSeconds,person=false){if(!routes.length){record.group.visible=false;return;}const route=routes[(record.index*7+(person?3:0))%routes.length];if(record.routeKey!==route.key||!record.id)assign(record,route,record.index);if(Date.now()<record.deadUntil){if(record.kind==="person"&&nowMs-record.deadAt<850){record.group.visible=true;record.group.rotation.x=Math.min(Math.PI/2,(nowMs-record.deadAt)/850*Math.PI/2);}else record.group.visible=false;return;}record.group.rotation.x=0;pendingDead.delete(record.id);const distance=epochSeconds*record.speed+record.phase,lane=person?record.side:record.lane,sample=sampleRoute(route,distance,lane);if(!sample){record.group.visible=false;return;}record.group.position.set(sample.x,sample.y,0);record.group.rotation.z=sample.yaw;record.group.visible=Boolean(bridge()?.active);}
function updateExplosions(now){for(const item of explosions){if(!item.mesh.visible)continue;if(now>=item.expires){item.mesh.visible=false;continue;}const t=(now-item.born)/(item.expires-item.born);item.mesh.scale.setScalar(.8+8*t);item.mesh.material.opacity=Math.max(0,.95*(1-t));}}
function frame(now=performance.now()){raf=requestAnimationFrame(frame);const b=bridge();if(!b?.threeScene){return;}ensurePools();refreshRoutes(now);const epoch=Date.now()/1000;for(const car of cars)updateRecord(car,now,epoch,false);for(const person of people)updateRecord(person,now,epoch,true);updateExplosions(now);}
function installHitHook(){const b=bridge();if(!b||b.__worldPopulationHitHook)return;b.__worldPopulationHitHook=true;b.registerWorldPopulationHit=hit=>{let node=hit?.object;while(node&&!node.userData?.worldPopulationId)node=node.parent;if(!node)return false;const record=recordById(String(node.userData.worldPopulationId||""));if(!record||Date.now()<record.deadUntil)return Boolean(record);markDead(record,{network:true});const view=viewport();if(view){view.dataset.worldPopulationHits=String((Number(view.dataset.worldPopulationHits)||0)+1);view.dataset.worldPopulationLastHit=record.kind;}return true;};}
function hookLoop(){installHitHook();setTimeout(hookLoop,500);}

export function installWorldPopulation(){if(installed)return;installed=true;globalThis.addEventListener(VS_FX_EVENT,handleRemoteFx);hookLoop();raf=requestAnimationFrame(frame);}
