import * as THREE from "three";

const TRACKED_KINDS=new Set(["car","person","life-car","life-person","bus","bird"]),SHOW_MARGIN=.22,HIDE_MARGIN=.28,TELEPORT_M=7.5,FAR_RELEASE_M=110;
let installed=false,sceneRef=null,baseAdd=null,lastOriginKey="";
const roots=new Set(),stateByRoot=new WeakMap(),idToRoot=new Map(),worldPos=new THREE.Vector3(),clip=new THREE.Vector3(),cameraPos=new THREE.Vector3();
const bridge=()=>globalThis.__arondightRealWorld||null,viewport=()=>document.getElementById("viewport"),rawKind=node=>String(node?.userData?.worldLifeKind||node?.userData?.worldPopulationKind||""),sourceId=node=>String(node?.userData?.worldLifeId||node?.userData?.worldPopulationId||""),trackedRoot=node=>Boolean(node?.children?.length&&TRACKED_KINDS.has(rawKind(node))),camera=()=>bridge()?.threeCamera||null;
function originKey(){const b=bridge();return Number.isFinite(b?.originLon)&&Number.isFinite(b?.originLat)?`${b.originLon.toFixed(6)}:${b.originLat.toFixed(6)}`:"";}
function distanceToCamera(root){const c=camera();if(!c?.getWorldPosition)return Infinity;c.getWorldPosition(cameraPos);root.getWorldPosition(worldPos);return cameraPos.distanceTo(worldPos);}
function onScreen(root,margin=.2){const c=camera();if(!c||!root?.parent)return false;c.updateMatrixWorld?.(true);root.updateWorldMatrix?.(true,false);root.getWorldPosition(worldPos);clip.copy(worldPos).project(c);return Number.isFinite(clip.x)&&Number.isFinite(clip.y)&&Number.isFinite(clip.z)&&clip.z>=-1.15&&clip.z<=1.15&&Math.abs(clip.x)<=1+margin&&Math.abs(clip.y)<=1+margin;}
const forcedHide=(root,now=performance.now())=>Number(root?.userData?.worldContinuityForceHideUntil||0)>now;
function instrument(root){if(!trackedRoot(root)||root.userData?.worldContinuityGuard)return;root.userData.worldContinuityGuard="frustum-hysteresis-v2";const initial=Boolean(root.visible),state={internal:initial,requested:initial,everVisible:initial,deferShow:false,deferHide:false,last:new THREE.Vector3().copy(root.position),pending:new THREE.Vector3().copy(root.position),pendingTeleport:false,lastWasOnScreen:false};stateByRoot.set(root,state);roots.add(root);const id=sourceId(root);if(id)idToRoot.set(id,root);try{Object.defineProperty(root,"visible",{configurable:true,enumerable:true,get(){return state.internal;},set(next){const wanted=Boolean(next);state.requested=wanted;if(wanted===state.internal){if(wanted)state.deferHide=false;else state.deferShow=false;return;}const now=performance.now();if(!wanted&&state.internal&&!forcedHide(root,now)&&onScreen(root,HIDE_MARGIN)){state.deferHide=true;state.deferShow=false;return;}if(wanted&&!state.internal&&!state.everVisible&&onScreen(root,SHOW_MARGIN)&&distanceToCamera(root)<FAR_RELEASE_M){state.deferShow=true;state.deferHide=false;return;}state.internal=wanted;state.deferShow=false;state.deferHide=false;if(wanted)state.everVisible=true;}});}catch{roots.delete(root);stateByRoot.delete(root);}}
function indexNode(node){if(!node)return;if(trackedRoot(node))instrument(node);if(node.name==="WORLD_LIVELINESS_TREES"||node.name==="WORLD_LIVELINESS_LAMPS")node.traverse?.(child=>{if(child?.isInstancedMesh||child?.isMesh){child.frustumCulled=false;child.userData.worldContinuityStatic=true;}});if(node.userData?.worldRagdollRoot){const source=idToRoot.get(String(node.userData.worldRagdollId||""));if(source){source.userData.worldContinuityForceHideUntil=performance.now()+1800;const state=stateByRoot.get(source);if(state){state.internal=false;state.requested=false;state.deferHide=false;}}}}
const indexSubtree=root=>root?.traverse?.(indexNode);
function patchScene(scene){if(!scene||scene===sceneRef)return;sceneRef=scene;roots.clear();idToRoot.clear();indexSubtree(scene);if(!scene.__worldContinuityAddPatched){baseAdd=scene.add;scene.add=function(...objects){const out=baseAdd.apply(this,objects);for(const object of objects)indexSubtree(object);return out;};scene.__worldContinuityAddPatched=true;}const v=viewport();if(v){v.dataset.worldVisibilityContinuity="frustum-hysteresis-v2";v.dataset.worldContinuityRoots=String(roots.size);}}
function resetForOriginChange(){for(const root of roots){const state=stateByRoot.get(root);if(!state)continue;state.pendingTeleport=false;state.deferHide=false;state.deferShow=false;state.last.copy(root.position);state.pending.copy(root.position);state.lastWasOnScreen=onScreen(root,SHOW_MARGIN);}const v=viewport();if(v)v.dataset.worldContinuityOriginResets=String((Number(v.dataset.worldContinuityOriginResets)||0)+1);}
function updateRoot(root){const state=stateByRoot.get(root);if(!state||!root?.parent)return;const visibleNow=state.internal,jump=root.position.distanceTo(state.last);if(visibleNow&&!forcedHide(root)&&jump>TELEPORT_M&&state.lastWasOnScreen){state.pending.copy(root.position);state.pendingTeleport=true;root.position.copy(state.last);}else if(state.pendingTeleport){if(!onScreen(root,HIDE_MARGIN)){root.position.copy(state.pending);state.last.copy(root.position);state.pendingTeleport=false;}else root.position.copy(state.last);}else state.last.copy(root.position);if(state.deferShow&&!onScreen(root,SHOW_MARGIN)){state.internal=true;state.everVisible=true;state.deferShow=false;}if(state.deferHide&&state.requested===false&&(!onScreen(root,HIDE_MARGIN)||forcedHide(root))){state.internal=false;state.deferHide=false;}state.lastWasOnScreen=state.internal&&onScreen(root,SHOW_MARGIN);}
function stabilizeStaticDecor(){for(const name of["WORLD_LIVELINESS_TREES","WORLD_LIVELINESS_LAMPS"]){const root=sceneRef?.getObjectByName?.(name);root?.traverse?.(node=>{if(node?.isInstancedMesh||node?.isMesh)node.frustumCulled=false;});}}
function frame(){const scene=bridge()?.threeScene;if(scene&&scene!==sceneRef)patchScene(scene);const key=originKey();if(key&&lastOriginKey&&key!==lastOriginKey)resetForOriginChange();if(key)lastOriginKey=key;let active=0,deferred=0,teleports=0;for(const root of [...roots]){if(!root?.parent){roots.delete(root);continue;}updateRoot(root);const state=stateByRoot.get(root);if(state?.internal)active++;if(state?.deferShow||state?.deferHide)deferred++;if(state?.pendingTeleport)teleports++;}stabilizeStaticDecor();const v=viewport();if(v){v.dataset.worldContinuityRoots=String(roots.size);v.dataset.worldContinuityActive=String(active);v.dataset.worldContinuityDeferred=String(deferred);v.dataset.worldContinuityTeleports=String(teleports);v.dataset.worldTreePersistence="no-frustum-drop-v1";}requestAnimationFrame(frame);}
export function installWorldVisibilityContinuity(){if(installed)return;installed=true;const scene=bridge()?.threeScene;if(scene)patchScene(scene);const v=viewport();if(v)v.dataset.worldVisibilityContinuity="frustum-hysteresis-v2";requestAnimationFrame(frame);}
installWorldVisibilityContinuity();
