import * as THREE from "three";
import {VS_FX_EVENT} from "./lan_vs.mjs";
import {spawnWorldPersonRagdoll} from "./world_person_ragdoll.mjs";
import {spawnWorldCarExplosion} from "./world_car_explosion.mjs";
import {makeBuildingsOpaque} from "./world_traffic_routes.mjs";
import {syncWorldBuildingDepthOcclusion} from "./world_building_depth_occlusion.mjs";

const MOBILE=/(?:android|iphone|ipad|ipod|macintosh.*mobile)/i.test(globalThis.navigator?.userAgent||"");
const CAR_COUNT=MOBILE?14:24;
const PERSON_COUNT=MOBILE?18:30;
const BUS_COUNT=MOBILE?3:5;
const BIRD_COUNT=MOBILE?10:16;
const TREE_COUNT=MOBILE?16:28;
const LAMP_COUNT=MOBILE?12:20;
const MAINTENANCE_MS=1800;
const IMAGERY_STORAGE="arondight45WorldImageryV1";
const IMAGERY_DEFAULT_OFF_MIGRATION="arondight45WorldImageryDefaultOffV3";
const FX_TYPE="world-procedural-death-v1";
const EARTH_RADIUS_M=6378137;

const records=[],byId=new Map();
const tmp=new THREE.Vector3(),cameraPos=new THREE.Vector3(),matrix=new THREE.Matrix4(),quat=new THREE.Quaternion(),scale=new THREE.Vector3(1,1,1);
let installed=false,boundScene=null,root=null,decorRoot=null,lightRoot=null,treeTrunks=null,treeCrowns=null,lampPoles=null,lampHeads=null;
let worldKey="",worldSeed=0,anchorX=0,anchorY=0,lastOriginLon=NaN,lastOriginLat=NaN,lastMaintenance=-Infinity,worldVisibleLatched=false,mapStyledFor=null;
let hitBridge=null,lastFrame=performance.now(),forceImageryOff=false;

function bridge(){return globalThis.__arondightRealWorld||null;}
function viewport(){return document.getElementById("viewport");}
function hashText(text){let h=2166136261;for(const c of String(text||"")){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function u(seed,salt){return hashText(`${seed}:${salt}`)/4294967295;}
function range(seed,salt,a,b){return a+(b-a)*u(seed,salt);}
function mod(x,m){return((x%m)+m)%m;}
function lngLatToMeters(lon0,lat0,lon,lat){const north=(lat-lat0)*Math.PI/180*EARTH_RADIUS_M,east=(lon-lon0)*Math.PI/180*EARTH_RADIUS_M*Math.max(.01,Math.cos(lat0*Math.PI/180));return[east,north];}
function worldVisible(){const b=bridge(),v=viewport();if(b?.active){worldVisibleLatched=true;return true;}if(worldVisibleLatched&&v?.dataset?.worldMode==="real")return true;worldVisibleLatched=false;return false;}

function migrateSatelliteDefaultOff(){try{if(localStorage.getItem(IMAGERY_DEFAULT_OFF_MIGRATION)!=="1"){localStorage.setItem(IMAGERY_STORAGE,"0");localStorage.setItem(IMAGERY_DEFAULT_OFF_MIGRATION,"1");forceImageryOff=true;}const v=viewport();if(v){v.dataset.worldSatelliteDefault="off";v.dataset.worldImageryDefault="0";}}catch{}}
function syncSatelliteMigration(){migrateSatelliteDefaultOff();if(!forceImageryOff)return;const b=bridge();if(!b)return;b.setImageryEnabled?.(false);forceImageryOff=false;}
migrateSatelliteDefaultOff();

const shared={};
function mat(color,roughness=.7,metalness=.04){return new THREE.MeshStandardMaterial({color,roughness,metalness});}
function zCylinder(rt,rb,h,segments=8){const g=new THREE.CylinderGeometry(rt,rb,h,segments);g.rotateX(Math.PI/2);return g;}
function ensureShared(){if(shared.carBody)return;shared.carBody=new THREE.BoxGeometry(3.55,1.62,.55);shared.carCabin=new THREE.BoxGeometry(1.75,1.44,.55);shared.busBody=new THREE.BoxGeometry(8,2.34,2.2);shared.busWindow=new THREE.BoxGeometry(5.9,2.37,.66);shared.wheel=new THREE.CylinderGeometry(.3,.3,.18,8);shared.busWheel=new THREE.CylinderGeometry(.4,.4,.22,10);shared.torso=zCylinder(.2,.29,.7,7);shared.leg=new THREE.BoxGeometry(.14,.15,.62);shared.arm=new THREE.BoxGeometry(.12,.12,.58);shared.head=new THREE.SphereGeometry(.19,8,6);shared.bird=new THREE.BufferGeometry();shared.bird.setAttribute("position",new THREE.BufferAttribute(new Float32Array([-.08,.38,0,-.78,-.12,.02,-.08,.02,.02,.08,.38,0,.08,.02,.02,.78,-.12,.02,-.08,.38,0,.08,.38,0,0,-.46,.04]),3));shared.bird.computeVertexNormals();shared.carMats=[0xc7473a,0x3079b7,0xc59b36,0xd7d9d8,0x3d4348,0x4d8b62,0x71588f].map(c=>mat(c,.42,.2));shared.busMats=[0x236da8,0xb84b40,0xc49a38,0x3f7d5c].map(c=>mat(c,.48,.12));shared.window=mat(0x263b46,.26,.1);shared.wheelMat=mat(0x202327,.88,.02);shared.shirts=[0x397da1,0xa9574a,0x5c8f62,0xb38f43,0x75659b,0xad7040,0x3f8b86].map(c=>mat(c,.82));shared.pants=[0x26313a,0x3a4146,0x403b36,0x263a50].map(c=>mat(c,.9));shared.skins=[0xe2b391,0xc5906d,0xa76f50,0x75452f,0xd1a07e].map(c=>mat(c,.88));shared.birds=[0x2f3942,0x56626a,0x806e53,0xc3c6c4,0x415666].map(c=>new THREE.MeshStandardMaterial({color:c,roughness:.85,side:THREE.DoubleSide}));}
function tag(mesh,record){mesh.userData.worldPopulationKind=record.kind;mesh.userData.worldPopulationId=record.id;mesh.userData.worldProceduralId=record.id;mesh.userData.worldPopulationClone=false;}
function retag(record){record.group.userData.worldPopulationKind=record.kind;record.group.userData.worldPopulationId=record.id;record.group.userData.worldProceduralId=record.id;record.group.traverse(node=>{if(node?.isMesh)tag(node,record);});}
function baseRecord(kind,index,group,color=0){return{kind,index,group,color,id:"",seed:0,motion:null,deadUntil:0,speed:0};}
function makeCar(index){ensureShared();const s=hashText(`car:${index}`),group=new THREE.Group(),bodyMat=shared.carMats[s%shared.carMats.length],body=new THREE.Mesh(shared.carBody,bodyMat),cab=new THREE.Mesh(shared.carCabin,shared.window),r=baseRecord("car",index,group,bodyMat.color.getHex());body.position.z=.48;cab.position.set(-.1,0,.93);group.add(body,cab);for(const x of[-1.18,1.18])for(const y of[-.86,.86]){const wheel=new THREE.Mesh(shared.wheel,shared.wheelMat);wheel.position.set(x,y,.28);group.add(wheel);}return r;}
function makeBus(index){ensureShared();const s=hashText(`bus:${index}`),group=new THREE.Group(),bodyMat=shared.busMats[s%shared.busMats.length],body=new THREE.Mesh(shared.busBody,bodyMat),windows=new THREE.Mesh(shared.busWindow,shared.window),r=baseRecord("bus",index,group,bodyMat.color.getHex());body.position.z=1.2;windows.position.set(.05,0,1.68);group.add(body,windows);for(const x of[-2.55,2.55])for(const y of[-1.22,1.22]){const wheel=new THREE.Mesh(shared.busWheel,shared.wheelMat);wheel.position.set(x,y,.42);group.add(wheel);}return r;}
function makePerson(index){ensureShared();const s=hashText(`person:${index}`),group=new THREE.Group(),shirt=shared.shirts[s%shared.shirts.length],pants=shared.pants[(s>>>2)%shared.pants.length],skin=shared.skins[(s>>>4)%shared.skins.length],torso=new THREE.Mesh(shared.torso,shirt),head=new THREE.Mesh(shared.head,skin),r=baseRecord("person",index,group,shirt.color.getHex());torso.position.z=1.05;head.position.z=1.58;group.add(torso,head);for(const y of[-.11,.11]){const leg=new THREE.Mesh(shared.leg,pants);leg.position.set(0,y,.48);group.add(leg);}for(const y of[-.31,.31]){const arm=new THREE.Mesh(shared.arm,shirt);arm.position.set(0,y,1.07);group.add(arm);}return r;}
function makeBird(index){ensureShared();const s=hashText(`bird:${index}`),group=new THREE.Group(),mesh=new THREE.Mesh(shared.bird,shared.birds[s%shared.birds.length]),r=baseRecord("bird",index,group,mesh.material.color.getHex());mesh.scale.setScalar(.48+(s%14)/100);group.add(mesh);return r;}

function createDecor(scene){const trunk=zCylinder(.1,.15,2.3,7),crown=new THREE.DodecahedronGeometry(.92,0),pole=zCylinder(.035,.055,3.7,6),head=new THREE.SphereGeometry(.11,7,5);treeTrunks=new THREE.InstancedMesh(trunk,mat(0x6a523d,.95),TREE_COUNT);treeCrowns=new THREE.InstancedMesh(crown,mat(0x4f8658,.92),TREE_COUNT);lampPoles=new THREE.InstancedMesh(pole,mat(0x4b5358,.55,.35),LAMP_COUNT);lampHeads=new THREE.InstancedMesh(head,new THREE.MeshStandardMaterial({color:0xe4d3a3,roughness:.38,emissive:0x8f6f35,emissiveIntensity:.15}),LAMP_COUNT);decorRoot=new THREE.Group();decorRoot.name="WORLD_PROCEDURAL_DECOR";decorRoot.add(treeTrunks,treeCrowns,lampPoles,lampHeads);for(const m of[treeTrunks,treeCrowns,lampPoles,lampHeads])m.userData.flightFireIgnore=true;scene.add(decorRoot);}
function createLights(scene){lightRoot=new THREE.Group();lightRoot.name="WORLD_PROCEDURAL_LIGHTS";const hemi=new THREE.HemisphereLight(0xd8e7ef,0x5e5446,.26),sun=new THREE.DirectionalLight(0xffe6c5,.34);sun.position.set(-70,-40,110);lightRoot.add(hemi,sun);scene.add(lightRoot);}
function setInstance(mesh,i,x,y,z,s=1){matrix.compose(tmp.set(x,y,z),quat.identity(),scale.set(s,s,s));mesh.setMatrixAt(i,matrix);}
function positionDecor(){if(!worldSeed||!treeTrunks)return;for(let i=0;i<TREE_COUNT;i++){const s=hashText(`${worldSeed}:tree:${i}`),x=anchorX+range(s,1,-82,82),y=anchorY+range(s,2,-82,82),sc=range(s,3,.78,1.18);setInstance(treeTrunks,i,x,y,1.15,sc);setInstance(treeCrowns,i,x,y,2.75,sc*1.12);}treeTrunks.instanceMatrix.needsUpdate=true;treeCrowns.instanceMatrix.needsUpdate=true;for(let i=0;i<LAMP_COUNT;i++){const s=hashText(`${worldSeed}:lamp:${i}`),axis=u(s,1)>.5,x=anchorX+(axis?range(s,2,-78,78):(u(s,3)>.5?42:-42)),y=anchorY+(axis?(u(s,3)>.5?42:-42):range(s,2,-78,78));setInstance(lampPoles,i,x,y,1.85);setInstance(lampHeads,i,x,y,3.72);}lampPoles.instanceMatrix.needsUpdate=true;lampHeads.instanceMatrix.needsUpdate=true;}

function ensureScene(){const scene=bridge()?.threeScene;if(!scene)return false;if(scene===boundScene&&root)return true;boundScene=scene;records.splice(0);byId.clear();worldKey="";worldSeed=0;root=new THREE.Group();root.name="WORLD_PROCEDURAL_POPULATION";scene.add(root);createDecor(scene);createLights(scene);for(let i=0;i<CAR_COUNT;i++)records.push(makeCar(i));for(let i=0;i<PERSON_COUNT;i++)records.push(makePerson(i));for(let i=0;i<BUS_COUNT;i++)records.push(makeBus(i));for(let i=0;i<BIRD_COUNT;i++)records.push(makeBird(i));for(const record of records){record.group.visible=false;root.add(record.group);}return true;}
function motionFor(record){const s=record.seed,person=record.kind==="person",bus=record.kind==="bus";if(record.kind==="bird")return{cx:range(s,1,-35,35),cy:range(s,2,-35,35),rx:range(s,3,20,62),ry:range(s,4,16,52),z:range(s,5,9,24),omega:range(s,6,.16,.34),phase:range(s,7,0,Math.PI*2)};return{cx:range(s,1,-42,42),cy:range(s,2,-42,42),hx:person?range(s,3,10,28):bus?range(s,3,44,68):range(s,3,28,58),hy:person?range(s,4,8,24):bus?range(s,4,32,56):range(s,4,22,48),angle:range(s,5,-Math.PI,Math.PI),phase:range(s,6,0,1),speed:person?range(s,7,1.0,1.65):bus?range(s,7,5.0,7.6):range(s,7,7.4,13.2)};}
function configureWorld(){const b=bridge();if(!Number.isFinite(b?.originLon)||!Number.isFinite(b?.originLat))return false;const bucketLat=Math.round(b.originLat*1000)/1000,bucketLon=Math.round(b.originLon*1000)/1000,key=`${bucketLat.toFixed(3)}:${bucketLon.toFixed(3)}`,[east,north]=lngLatToMeters(b.originLon,b.originLat,bucketLon,bucketLat);anchorX=east;anchorY=north;lastOriginLon=b.originLon;lastOriginLat=b.originLat;if(key===worldKey)return true;worldKey=key;worldSeed=hashText(`arondight-world-pop:${key}`);byId.clear();for(const record of records){record.seed=hashText(`${worldSeed}:${record.kind}:${record.index}`);record.id=`${record.kind}-proc-${worldSeed.toString(36)}-${record.index}`;record.motion=motionFor(record);record.speed=record.motion.speed||0;record.deadUntil=0;retag(record);byId.set(record.id,record);}positionDecor();const v=viewport();if(v){v.dataset.worldProceduralSeed=worldSeed.toString(36);v.dataset.worldPopulationArchitecture="procedural-deterministic-v1";v.dataset.worldLifeArchitecture="procedural-deterministic-v1";v.dataset.worldTrafficContinuity="deterministic-no-despawn-v1";v.dataset.worldCars=String(CAR_COUNT);v.dataset.worldPeople=String(PERSON_COUNT);v.dataset.worldLifeExtraCars=String(CAR_COUNT);v.dataset.worldLifeExtraPeople=String(PERSON_COUNT);v.dataset.worldLifeBuses=String(BUS_COUNT);v.dataset.worldLifeBirds=String(BIRD_COUNT);v.dataset.worldLifeShootable="1";v.dataset.worldTrafficRoutes="1";v.dataset.worldLifeRoutes="1";}return true;}
function refreshAnchor(){const b=bridge();if(!Number.isFinite(b?.originLon)||!Number.isFinite(b?.originLat))return;if(b.originLon===lastOriginLon&&b.originLat===lastOriginLat)return;configureWorld();positionDecor();}

function rectSample(m,t){const w=2*m.hx,h=2*m.hy,per=2*(w+h),d=mod(t*m.speed+m.phase*per,per);let x,y,dx,dy;if(d<w){x=-m.hx+d;y=-m.hy;dx=1;dy=0;}else if(d<w+h){x=m.hx;y=-m.hy+(d-w);dx=0;dy=1;}else if(d<2*w+h){x=m.hx-(d-w-h);y=m.hy;dx=-1;dy=0;}else{x=-m.hx;y=m.hy-(d-2*w-h);dx=0;dy=-1;}const c=Math.cos(m.angle),s=Math.sin(m.angle),rx=x*c-y*s,ry=x*s+y*c,rdx=dx*c-dy*s,rdy=dx*s+dy*c;return{x:anchorX+m.cx+rx,y:anchorY+m.cy+ry,yaw:Math.atan2(rdy,rdx)};}
function respawnAllowed(record){if(!record.deadUntil)return true;const now=Date.now();if(now<record.deadUntil)return false;const camera=bridge()?.threeCamera;if(!camera?.getWorldPosition)return false;camera.getWorldPosition(cameraPos);const clearance=record.kind==="bird"?70:55;if(cameraPos.distanceTo(record.group.position)<clearance)return false;record.deadUntil=0;return true;}
function updateRecord(record,epoch){if(!respawnAllowed(record)){record.group.visible=false;return;}if(record.kind==="bird"){const m=record.motion,a=epoch*m.omega+m.phase,flap=.82+.2*Math.sin(epoch*10+record.index);record.group.position.set(anchorX+m.cx+Math.cos(a)*m.rx,anchorY+m.cy+Math.sin(a*.94)*m.ry,m.z+Math.sin(a*2.3+record.index)*2.1);record.group.rotation.set(.08*Math.sin(a*3),0,a+Math.PI/2);record.group.scale.set(1,flap,1);record.group.visible=true;return;}const p=rectSample(record.motion,epoch),z=record.kind==="person"?.01*Math.sin(epoch*6+record.index):0;record.group.position.set(p.x,p.y,z);record.group.rotation.set(0,0,p.yaw);record.group.visible=true;}

function styleMap(){const b=bridge(),map=b?.map;if(!b?.active||!map?.getStyle||!map?.setPaintProperty||mapStyledFor===map)return;let changed=0;for(const layer of map.getStyle()?.layers||[]){const id=String(layer?.id||"").toLowerCase(),source=String(layer?.["source-layer"]||"").toLowerCase();try{if(layer.type==="fill-extrusion"&&(source==="building"||id.includes("building"))){map.setPaintProperty(layer.id,"fill-extrusion-opacity",.98);changed++;}}catch{}}mapStyledFor=map;const v=viewport();if(v){v.dataset.worldVisualPalette="natural-v2";v.dataset.worldVisualPaletteLayers=String(changed);}}
function maintain(now){const b=bridge();if(!b?.active||now-lastMaintenance<MAINTENANCE_MS)return;lastMaintenance=now;try{const opaque=makeBuildingsOpaque(b.map),depth=syncWorldBuildingDepthOcclusion(b),v=viewport();styleMap();if(v){v.dataset.worldBuildingsOpaque="1";v.dataset.worldBuildingsSolidified=String(opaque);v.dataset.worldBuildingDepthOccluders=String(depth);}}catch{}}

function nodeRecord(hit){for(let n=hit?.object;n;n=n.parent){const id=String(n.userData?.worldProceduralId||n.userData?.worldPopulationId||"");if(id&&byId.has(id))return byId.get(id);}return null;}
function sendDeath(record){try{bridge()?.vsSession?.sendFx?.({type:FX_TYPE,id:`${record.id}-${Date.now().toString(36)}`,objectId:record.id,kind:record.kind,p:[record.group.position.x,record.group.position.y,record.group.position.z],yaw:record.group.rotation.z});}catch{}}
function killRecord(record,{network=true}={}){if(!record||record.deadUntil)return false;record.group.getWorldPosition(tmp);const now=Date.now(),angle=range(record.seed,21,-Math.PI,Math.PI);if(record.kind==="person"){record.deadUntil=now+10000;spawnWorldPersonRagdoll({position:[tmp.x,tmp.y,Math.max(.8,tmp.z+.7)],yaw:record.group.rotation.z,impulse:[Math.cos(angle)*2.5,Math.sin(angle)*2.5,2.6],seed:record.id,id:record.id});}else if(record.kind==="car"||record.kind==="bus"){record.deadUntil=now+(record.kind==="bus"?20000:16000);spawnWorldCarExplosion({position:[tmp.x,tmp.y,record.kind==="bus"?1.2:.45],yaw:record.group.rotation.z,velocity:[Math.cos(record.group.rotation.z)*record.speed,Math.sin(record.group.rotation.z)*record.speed,0],color:record.color,seed:record.id,id:record.id});}else record.deadUntil=now+9000;record.group.visible=false;if(network)sendDeath(record);const v=viewport();if(v){v.dataset.worldLifeHits=String((Number(v.dataset.worldLifeHits)||0)+1);v.dataset.worldPopulationHits=String((Number(v.dataset.worldPopulationHits)||0)+1);v.dataset.worldLifeLastHit=record.kind;v.dataset.worldPopulationLastHit=record.kind;}return true;}
function handleProceduralHit(hit){const record=nodeRecord(hit);if(!record)return false;if(!record.deadUntil)killRecord(record);return true;}
function ensureHitBridge(){const b=bridge();if(!b||hitBridge===b)return;const base=typeof b.registerWorldPopulationHit==="function"?b.registerWorldPopulationHit.bind(b):null;const dispatcher=hit=>handleProceduralHit(hit)||(base?Boolean(base(hit)):false);dispatcher.__proceduralPopulationProvider=true;dispatcher.__worldLivelinessWrapper=true;dispatcher.__gameplayPolishLiteWrapper=true;b.__proceduralPopulationHit=handleProceduralHit;b.registerWorldPopulationHit=dispatcher;hitBridge=b;}
function handleRemoteFx(event){const packet=event?.detail?.packet;if(packet?.type!==FX_TYPE)return;const record=byId.get(String(packet.objectId||""));if(record&&!record.deadUntil)killRecord(record,{network:false});}

function frame(now=performance.now()){requestAnimationFrame(frame);const dt=Math.min(.05,Math.max(0,(now-lastFrame)/1000||0));lastFrame=now;void dt;syncSatelliteMigration();if(!ensureScene())return;ensureHitBridge();const visible=worldVisible();root.visible=visible;decorRoot.visible=visible;lightRoot.visible=visible;if(!visible)return;if(!configureWorld())return;refreshAnchor();maintain(now);const epoch=Date.now()/1000;let alive=0;for(const record of records){updateRecord(record,epoch);if(record.group.visible)alive++;}const v=viewport();if(v){v.dataset.worldLifeVisible=String(alive);v.dataset.worldLifeTotal=String(records.length);v.dataset.worldProceduralPopulation="1";}}

export function installWorldProceduralPopulation(){if(installed)return;installed=true;globalThis.addEventListener(VS_FX_EVENT,handleRemoteFx);requestAnimationFrame(frame);}

installWorldProceduralPopulation();
