import {AUDIO_SETTINGS_EVENT,loadAudioSettings,normalizeAudioSettings} from "./audio_settings.mjs";

let installed=false,ctx=null,master=null,noiseLong=null,noiseShort=null,settings=loadAudioSettings(),lastShots=0,lastImpacts=0,observer=null,painSeq=0;
function viewport(){return globalThis.document?.getElementById?.("viewport")||null;}
function level(kind){if(!settings.soundEnabled)return 0;return Math.max(0,Math.min(1,(kind==="shot"?settings.shotsVolume:settings.fxVolume)/100));}
function ensureAudio(){if(ctx)return ctx;const Ctx=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Ctx)return null;ctx=new Ctx();master=ctx.createGain();master.gain.value=settings.soundEnabled?1:0;master.connect(ctx.destination);noiseShort=ctx.createBuffer(1,Math.max(1,Math.floor(ctx.sampleRate*.09)),ctx.sampleRate);noiseLong=ctx.createBuffer(1,Math.max(1,Math.floor(ctx.sampleRate*.65)),ctx.sampleRate);for(const buffer of[noiseShort,noiseLong]){const data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);}return ctx;}
function resume(){const c=ensureAudio();try{if(c?.state==="suspended")void c.resume();}catch{}return c;}
function connectNoise(buffer,t,filterType,f0,f1,g0,duration){const c=resume();if(!c||!master||!buffer)return;const src=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain();src.buffer=buffer;filter.type=filterType;filter.frequency.setValueAtTime(Math.max(20,f0),t);filter.frequency.exponentialRampToValueAtTime(Math.max(20,f1),t+duration);filter.Q.value=.62;gain.gain.setValueAtTime(Math.max(.0001,g0),t);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);src.connect(filter).connect(gain).connect(master);src.start(t);src.stop(t+duration+.01);}
function tone(type,f0,f1,g0,t,duration,delay=0){const c=resume();if(!c||!master)return;const osc=c.createOscillator(),gain=c.createGain(),start=t+delay;osc.type=type;osc.frequency.setValueAtTime(Math.max(20,f0),start);osc.frequency.exponentialRampToValueAtTime(Math.max(20,f1),start+duration);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(Math.max(.0002,g0),start+.006);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);osc.connect(gain).connect(master);osc.start(start);osc.stop(start+duration+.01);}
function bump(name){const view=viewport();if(view)view.dataset[name]=String((Number(view.dataset[name])||0)+1);}
export function playEnhancedShotSound(){const l=level("shot"),c=resume();if(!l||!c)return false;try{const t=c.currentTime;connectNoise(noiseShort,t,"highpass",5200,900,.22*l,.075);connectNoise(noiseLong,t+.012,"bandpass",1150,360,.11*l,.19);tone("triangle",190,68,.105*l,t,.085);tone("square",3300,1250,.026*l,t,.038);tone("sine",620,240,.028*l,t,.11,.016);bump("worldAudioEnhancedShots");return true;}catch{return false;}}
export function playBulletImpactSound(){const l=level("fx"),c=resume();if(!l||!c)return false;try{const t=c.currentTime,variant=(Number(viewport()?.dataset.fireProjectileImpacts)||0)%3;connectNoise(noiseShort,t,"bandpass",variant===0?2400:variant===1?1650:3100,650,.12*l,.06);tone("triangle",variant===2?720:520,180,.032*l,t,.07);bump("worldAudioBulletImpacts");return true;}catch{return false;}}
export function playWorldCarExplosionSound(){const l=level("fx"),c=resume();if(!l||!c)return false;try{const t=c.currentTime;connectNoise(noiseLong,t,"lowpass",1800,95,.32*l,.58);connectNoise(noiseShort,t,"highpass",4700,1100,.13*l,.085);tone("sine",92,31,.23*l,t,.42);tone("triangle",185,58,.11*l,t,.31,.025);for(let i=0;i<4;i++){const base=360+i*105+(Math.random()-.5)*70;tone("square",base,base*.55,.022*l,t,.12+i*.025,.07+i*.045);}bump("worldAudioCarExplosions");return true;}catch{return false;}}
export function playWorldPedestrianPainSound(){const l=level("fx"),c=resume();if(!l||!c)return false;try{const t=c.currentTime,variant=(painSeq++ + Math.floor(Math.random()*5))%5,f0=[145,178,126,162,138][variant],f1=[82,96,70,88,76][variant],duration=[.31,.24,.38,.28,.42][variant],formant=[620,780,520,690,570][variant];const osc=c.createOscillator(),filter=c.createBiquadFilter(),gain=c.createGain();osc.type=variant%2?"sawtooth":"triangle";osc.frequency.setValueAtTime(f0,t);osc.frequency.exponentialRampToValueAtTime(f1,t+duration);filter.type="bandpass";filter.frequency.setValueAtTime(formant,t);filter.Q.value=1.15;gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(.07*l,t+.025);gain.gain.setValueAtTime(.052*l,t+duration*.5);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);osc.connect(filter).connect(gain).connect(master);osc.start(t);osc.stop(t+duration+.015);tone("sine",f0*.52,f1*.48,.022*l,t,duration*.9,.018);bump("worldAudioPedestrianPain");const view=viewport();if(view)view.dataset.worldAudioPedestrianPainVariant=String(variant);return true;}catch{return false;}}
function syncCounters(){const view=viewport();if(!view)return;const shots=Number(view.dataset.fireShots)||0,impacts=Number(view.dataset.fireProjectileImpacts)||0;if(shots>lastShots){for(let i=lastShots;i<shots;i++)playEnhancedShotSound();lastShots=shots;}else if(shots<lastShots)lastShots=shots;if(impacts>lastImpacts){for(let i=lastImpacts;i<impacts;i++)playBulletImpactSound();lastImpacts=impacts;}else if(impacts<lastImpacts)lastImpacts=impacts;}
function bindViewport(){const view=viewport();if(!view||observer)return;lastShots=Number(view.dataset.fireShots)||0;lastImpacts=Number(view.dataset.fireProjectileImpacts)||0;observer=new MutationObserver(syncCounters);observer.observe(view,{attributes:true,attributeFilter:["data-fire-shots","data-fire-projectile-impacts"]});view.dataset.worldCombatAudio="armed";}
export function installWorldCombatAudioFx(){if(installed)return;installed=true;globalThis.addEventListener?.(AUDIO_SETTINGS_EVENT,event=>{settings=normalizeAudioSettings(event.detail||loadAudioSettings());if(master&&ctx)master.gain.setTargetAtTime(settings.soundEnabled?1:0,ctx.currentTime,.012);});const unlock=()=>resume();globalThis.addEventListener?.("pointerdown",unlock,{passive:true});globalThis.addEventListener?.("keydown",unlock,{passive:true});bindViewport();if(!observer)globalThis.setTimeout?.(bindViewport,250);}
export function worldCombatAudioState(){return{installed,contextState:ctx?.state||"none",shots:lastShots,impacts:lastImpacts};}
