import {XBOX_CONTROL_SCHEMES,loadXboxControlScheme,saveXboxControlScheme} from "./xbox_gamepad.mjs";
import {structuralMutation} from "./dom_mutation_filter.mjs";

let installed=false,lastScheme="",lastAim=null,cachedHelp=null,cachedSelect=null,cachedCross=null;
function viewport(){return document.getElementById("viewport");}
function helpText(scheme){return scheme===XBOX_CONTROL_SCHEMES.AIM?"AIM · LS MOVE · RS STEER · LT/RT ALT −/+ · HOLD LB AIM/LOOK · RB FIRE · A ARM · Y WEAPON · VIEW CAM · ↓ ON FOOT · ↑ STRIKE · MENU":"CLASSIC · LS MOVE · RS STEER · LT/RT ALT −/+ · RB FIRE · A ARM · Y WEAPON · VIEW CAM · ↓ ON FOOT · ↑ STRIKE · MENU";}
function mountSettings(){const dialog=document.querySelector(".phone-settings-dialog");if(!dialog||dialog.querySelector("[data-xbox-scheme]"))return;const actions=dialog.querySelector(".phone-settings-actions"),section=document.createElement("section");section.className="xbox-control-mode-settings";section.innerHTML=`<h4>XBOX FLIGHT</h4><label>CONTROL SCHEME<select data-xbox-scheme><option value="classic">CLASSIC · DIRECT RIGHT STICK</option><option value="aim">AIM · HOLD LB FOR LOOK</option></select></label><p class="phone-settings-note">CLASSIC keeps the original direct flight feel. AIM shows the centre crosshair only while LB is held.</p>`;dialog.insertBefore(section,actions||null);const select=section.querySelector("[data-xbox-scheme]");select.value=loadXboxControlScheme();select.addEventListener("change",()=>{saveXboxControlScheme(select.value);lastScheme=select.value;sync(true);});}
function sync(force=false){const view=viewport(),scheme=force||!lastScheme?loadXboxControlScheme():lastScheme,onFoot=document.body.classList.contains("on-foot-mode"),aim=scheme===XBOX_CONTROL_SCHEMES.AIM&&!onFoot&&view?.dataset.gamepadAim==="1";if(force||scheme!==lastScheme){lastScheme=scheme;if(view)view.dataset.xboxControlScheme=scheme;cachedHelp=document.getElementById("soloGamepadHelp");cachedSelect=document.querySelector("[data-xbox-scheme]");cachedCross=view?.querySelector(".xbox-crosshair")||null;const expectedHelp=helpText(scheme);if(cachedHelp&&cachedHelp.textContent!==expectedHelp)cachedHelp.textContent=expectedHelp;if(cachedSelect&&cachedSelect.value!==scheme)cachedSelect.value=scheme;}if(force||aim!==lastAim){lastAim=aim;document.body.classList.toggle("xbox-aim-active",aim);cachedCross??=view?.querySelector(".xbox-crosshair")||null;cachedCross?.classList.toggle("active",aim);if(view)view.dataset.xboxAimCrosshair=aim?"1":"0";}}
function frame(){sync();requestAnimationFrame(frame);}
export function installXboxControlMode(){if(installed)return;installed=true;const style=document.createElement("style");style.dataset.xboxControlMode="v1";style.textContent=`body:not(.xbox-aim-active) #viewport .xbox-crosshair{display:none!important}body.xbox-aim-active #viewport .xbox-crosshair{display:block!important}.xbox-control-mode-settings select{width:100%;box-sizing:border-box;border:1px solid #ffffff33;border-radius:8px;background:#0a1725;color:#eef8ff;padding:8px 9px;font:750 12px system-ui,-apple-system,sans-serif}`;document.head.appendChild(style);sync(true);new MutationObserver(l=>{if(!structuralMutation(l))return;mountSettings();cachedHelp=document.getElementById("soloGamepadHelp");cachedSelect=document.querySelector("[data-xbox-scheme]");cachedCross=viewport()?.querySelector(".xbox-crosshair")||null;}).observe(document.documentElement,{subtree:true,childList:true});mountSettings();requestAnimationFrame(frame);}
installXboxControlMode();
