import {XBOX_CONTROL_SCHEMES,loadXboxControlScheme,saveXboxControlScheme} from "./xbox_gamepad.mjs";

let installed=false,lastScheme="",lastAim=null;
function viewport(){return document.getElementById("viewport");}
function helpText(scheme){return scheme===XBOX_CONTROL_SCHEMES.AIM?"AIM · LS MOVE · RS STEER · LT/RT ALT −/+ · HOLD LB AIM/LOOK · RB FIRE · A ARM · B KILL · X CAM · Y RESET · VIEW EXIT · MENU SETTINGS":"CLASSIC · LS MOVE · RS STEER · LT/RT ALT −/+ · RB FIRE · A ARM · B KILL · X CAM · Y RESET · VIEW EXIT · MENU SETTINGS";}
function mountSettings(){const dialog=document.querySelector(".phone-settings-dialog");if(!dialog||dialog.querySelector("[data-xbox-scheme]"))return;const actions=dialog.querySelector(".phone-settings-actions"),section=document.createElement("section");section.className="xbox-control-mode-settings";section.innerHTML=`<h4>XBOX FLIGHT</h4><label>CONTROL SCHEME<select data-xbox-scheme><option value="classic">CLASSIC · DIRECT RIGHT STICK</option><option value="aim">AIM · HOLD LB FOR LOOK</option></select></label><p class="phone-settings-note">CLASSIC keeps the original direct flight feel. AIM shows the centre crosshair only while LB is held.</p>`;dialog.insertBefore(section,actions||null);const select=section.querySelector("[data-xbox-scheme]");select.value=loadXboxControlScheme();select.addEventListener("change",()=>{saveXboxControlScheme(select.value);sync(true);});}
function sync(force=false){const view=viewport(),scheme=loadXboxControlScheme(),onFoot=document.body.classList.contains("on-foot-mode"),aim=scheme===XBOX_CONTROL_SCHEMES.AIM&&!onFoot&&view?.dataset.gamepadAim==="1";if(force||scheme!==lastScheme){lastScheme=scheme;if(view)view.dataset.xboxControlScheme=scheme;}const help=document.getElementById("soloGamepadHelp"),expectedHelp=helpText(scheme);if(help&&help.textContent!==expectedHelp)help.textContent=expectedHelp;const select=document.querySelector("[data-xbox-scheme]");if(select&&select.value!==scheme)select.value=scheme;if(force||aim!==lastAim){lastAim=aim;document.body.classList.toggle("xbox-aim-active",aim);const cross=view?.querySelector(".xbox-crosshair");cross?.classList.toggle("active",aim);if(view)view.dataset.xboxAimCrosshair=aim?"1":"0";}mountSettings();}
function frame(){sync();requestAnimationFrame(frame);}
export function installXboxControlMode(){if(installed)return;installed=true;const style=document.createElement("style");style.dataset.xboxControlMode="v1";style.textContent=`body:not(.xbox-aim-active) #viewport .xbox-crosshair{display:none!important}body.xbox-aim-active #viewport .xbox-crosshair{display:block!important}.xbox-control-mode-settings select{width:100%;box-sizing:border-box;border:1px solid #ffffff33;border-radius:8px;background:#0a1725;color:#eef8ff;padding:8px 9px;font:750 12px system-ui,-apple-system,sans-serif}`;document.head.appendChild(style);sync(true);new MutationObserver(()=>mountSettings()).observe(document.documentElement,{subtree:true,childList:true});requestAnimationFrame(frame);}
installXboxControlMode();
