from pathlib import Path
p=Path('sim/real_world_bootstrap.mjs');s=p.read_text()
s=s.replace('import {fpvTargetDistanceMeters,forwardTarget} from "./world_camera_math.mjs";','import {fpvTargetDistanceMeters,forwardTarget} from "./world_camera_math.mjs";\nimport {LanVsSession,nearbyRoomKey} from "./lan_vs.mjs";',1)
s=s.replace('this.installUi();this.installLookHud();this.installFreeLookSurface();window.addEventListener(CAMERA_SETTINGS_EVENT','this.vsSession=null;this.vsPeerMesh=null;this.vsConnected=false;this.installUi();this.installLookHud();this.installFreeLookSurface();this.installVsUi();window.addEventListener(CAMERA_SETTINGS_EVENT',1)
marker='  installLookHud(){'
method=r'''  installVsUi(){
    const viewport=$("viewport");if(!viewport||$("lanVsButton"))return;const button=document.createElement("button");button.id="lanVsButton";button.type="button";button.textContent="FIND MATE · VS";button.style.cssText="position:absolute;z-index:6;left:max(10px,env(safe-area-inset-left));bottom:max(12px,calc(env(safe-area-inset-bottom) + 8px));padding:9px 12px;border:1px solid #70ddff88;border-radius:10px;background:#071522e8;color:#dff7ff;font:800 10px system-ui;letter-spacing:.05em;touch-action:manipulation";viewport.appendChild(button);const status=document.createElement("div");status.id="lanVsStatus";status.style.cssText="position:absolute;z-index:6;left:max(10px,env(safe-area-inset-left));bottom:max(52px,calc(env(safe-area-inset-bottom) + 48px));padding:5px 8px;border-radius:8px;background:#071522d9;color:#aeeaff;font:800 9px system-ui;display:none";viewport.appendChild(status);button.onclick=()=>this.toggleVs();
  }
  async toggleVs(){
    if(this.vsSession){this.stopVs();return;}const button=$("lanVsButton"),status=$("lanVsStatus");if(button)button.textContent="FINDING MATE…";if(status){status.style.display="block";status.textContent="Nearby VS matchmaking…";}let lat=Number(this.lastLocation?.coords?.latitude??this.originLat),lon=Number(this.lastLocation?.coords?.longitude??this.originLon);if(!Number.isFinite(lat)||!Number.isFinite(lon)){try{this.lastLocation=await geolocate();lat=Number(this.lastLocation.coords.latitude);lon=Number(this.lastLocation.coords.longitude);}catch{if(button)button.textContent="FIND MATE · VS";if(status)status.textContent="GPS is needed to find a nearby mate";return;}}const session=new LanVsSession({onPeer:()=>{this.vsConnected=true;if(button)button.textContent="VS · CONNECTED";if(status)status.textContent="Mate found · direct P2P";this.ensureVsPeerMesh();},onPose:pose=>this.applyVsPose(pose),onLeave:()=>{this.vsConnected=false;if(button)button.textContent="FINDING MATE…";if(status)status.textContent="Mate left · searching…";if(this.vsPeerMesh)this.vsPeerMesh.visible=false;},onError:error=>{if(button)button.textContent="FIND MATE · VS";if(status)status.textContent=`VS unavailable · ${error?.message||error}`;}});this.vsSession=session;try{await session.start(nearbyRoomKey(lat,lon));}catch{if(this.vsSession===session)this.vsSession=null;}
  }
  stopVs(){this.vsSession?.stop();this.vsSession=null;this.vsConnected=false;if(this.vsPeerMesh)this.vsPeerMesh.visible=false;const b=$("lanVsButton"),s=$("lanVsStatus");if(b)b.textContent="FIND MATE · VS";if(s)s.style.display="none";}
  ensureVsPeerMesh(){if(this.vsPeerMesh||!this.threeScene)return;const group=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:0x36e6ff,roughness:.35,metalness:.35});group.add(new THREE.Mesh(new THREE.BoxGeometry(.22,.34,.07),mat));for(const [x,y] of [[-.19,-.19],[.19,-.19],[-.19,.19],[.19,.19]]){const arm=new THREE.Mesh(new THREE.BoxGeometry(.025,.26,.025),mat);arm.position.set(x*.5,y*.5,0);arm.rotation.z=(x*y>0?1:-1)*Math.PI/4;group.add(arm);}group.visible=false;group.renderOrder=5;this.threeScene.add(group);this.vsPeerMesh=group;}
  applyVsPose(pose){if(!pose||!Array.isArray(pose.p)||pose.p.length<3)return;this.ensureVsPeerMesh();if(!this.vsPeerMesh)return;let [x,y,z]=pose.p.map(Number);if(Array.isArray(pose.g)&&pose.g.length===2&&Number.isFinite(this.originLon)&&Number.isFinite(this.originLat)){const local=lngLatToMeters(this.originLon,this.originLat,Number(pose.g[0]),Number(pose.g[1]));x=local[0];y=local[1];}if(![x,y,z].every(Number.isFinite))return;this.vsPeerMesh.position.set(x,y,z);const q=pose.q;if(Array.isArray(q)&&q.length===4&&q.every(Number.isFinite))this.vsPeerMesh.quaternion.set(q[0],q[1],q[2],q[3]);this.vsPeerMesh.visible=true;}
  updateVsPose(){if(!this.vsSession||!this.airframe)return;const p=this.airframe.position,q=this.airframe.quaternion;if(!p||!q)return;const pose={p:[p.x,p.y,p.z],q:[q.x,q.y,q.z,q.w],t:performance.now()};if(this.active&&Number.isFinite(this.originLon)&&Number.isFinite(this.originLat))pose.g=metersToLngLat(this.originLon,this.originLat,p.x,p.y);this.vsSession.setPose(pose);}
'''
if 'installVsUi(){' not in s:s=s.replace(marker,method+marker,1)
s=s.replace('renderFrame(renderer,scene,camera){\n    this.attachThree(renderer,scene,camera);','renderFrame(renderer,scene,camera){\n    this.attachThree(renderer,scene,camera);this.updateVsPose();',1)
p.write_text(s)
