from pathlib import Path
import re

path=Path('tests/android_render_browser_smoke.mjs')
text=path.read_text()

before_old='const before=await page.evaluate(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld,flight=b.threeRenderer.domElement,map=b.map.getCanvas(),flightAttrs=b.threeRenderer.getContext().getContextAttributes(),mapGl=map.getContext("webgl2")||map.getContext("webgl"),mapAttrs=mapGl?.getContextAttributes?.()||{};return{platform:v.dataset.renderPlatform,stable:v.dataset.presentationStableBackbuffer,software:Boolean(globalThis.__arondightDiagnostics?.presentationSoftwareRaster),flightDesync:flightAttrs?.desynchronized===true,mapDesync:mapAttrs?.desynchronized===true,declaredFlight:v.dataset.presentationCanvasDesynchronized,declaredMap:v.dataset.worldMapCanvasDesynchronized,flightSize:[flight.width,flight.height],mapSize:[map.width,map.height],mapRatio:map.width/Math.max(1,map.clientWidth),ratio:b.threeRenderer.getPixelRatio(),resizes:Number(v.dataset.presentationBackbufferResizes||0),terrain:v.dataset.worldTerrainStatus,terrainTriangles:Number(v.dataset.worldTerrainTriangles||0),worldFrames:Number(v.dataset.worldThreeFrames||0),presentationDraws:Number(v.dataset.presentationDraws||0)};});'
after_old='const after=await page.evaluate(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld,flight=b.threeRenderer.domElement,map=b.map.getCanvas();return{flightSize:[flight.width,flight.height],mapSize:[map.width,map.height],mapRatio:map.width/Math.max(1,map.clientWidth),ratio:b.threeRenderer.getPixelRatio(),resizes:Number(v.dataset.presentationBackbufferResizes||0),quality:v.dataset.presentationQualityMode,perf:v.dataset.worldPerfMode,worldFrames:Number(v.dataset.worldThreeFrames||0),presentationDraws:Number(v.dataset.presentationDraws||0)};});'

helper='''const stableCompositorSnapshot=async()=>page.evaluate(async()=>{\n  const deadline=performance.now()+10000;\n  for(;;){\n    const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld,mapObject=b?.map,renderer=b?.threeRenderer;\n    const ready=document.body.classList.contains("solo-flight")&&v?.dataset.worldMode==="real"&&v?.dataset.worldTerrainStatus==="box3d-active"&&Boolean(b?.active)&&!b?.loading&&Boolean(mapObject?.getCanvas)&&Boolean(renderer?.domElement)&&Number(v?.dataset.worldThreeFrames||0)>=1&&Number(v?.dataset.presentationDraws||0)>=10;\n    if(ready){\n      await new Promise(requestAnimationFrame);\n      if(globalThis.__arondightRealWorld===b&&b.map===mapObject&&b.threeRenderer===renderer&&b.active&&!b.loading){\n        const flight=renderer.domElement,map=mapObject.getCanvas(),flightAttrs=renderer.getContext().getContextAttributes(),mapGl=map.getContext("webgl2")||map.getContext("webgl"),mapAttrs=mapGl?.getContextAttributes?.()||{};\n        return{platform:v.dataset.renderPlatform,stable:v.dataset.presentationStableBackbuffer,software:Boolean(globalThis.__arondightDiagnostics?.presentationSoftwareRaster),flightDesync:flightAttrs?.desynchronized===true,mapDesync:mapAttrs?.desynchronized===true,declaredFlight:v.dataset.presentationCanvasDesynchronized,declaredMap:v.dataset.worldMapCanvasDesynchronized,flightSize:[flight.width,flight.height],mapSize:[map.width,map.height],mapRatio:map.width/Math.max(1,map.clientWidth),ratio:renderer.getPixelRatio(),resizes:Number(v.dataset.presentationBackbufferResizes||0),terrain:v.dataset.worldTerrainStatus,terrainTriangles:Number(v.dataset.worldTerrainTriangles||0),worldFrames:Number(v.dataset.worldThreeFrames||0),presentationDraws:Number(v.dataset.presentationDraws||0),quality:v.dataset.presentationQualityMode,perf:v.dataset.worldPerfMode};\n      }\n    }\n    if(performance.now()>=deadline)throw new Error(`Honor stable compositor snapshot timeout: ${JSON.stringify({active:Boolean(b?.active),loading:Boolean(b?.loading),map:Boolean(b?.map),renderer:Boolean(b?.threeRenderer),terrain:v?.dataset.worldTerrainStatus||"",worldFrames:v?.dataset.worldThreeFrames||"",presentationDraws:v?.dataset.presentationDraws||""})}`);\n    await new Promise(requestAnimationFrame);\n  }\n});\n'''
anchor='page.on("requestfailed",request=>failed.push(`${request.failure()?.errorText||"FAILED"} ${request.url()}`));page.on("pageerror",error=>consoleErrors.push(`PAGEERROR ${error.message}`));page.on("console",message=>{if(message.type()==="error"||message.type()==="warning")consoleErrors.push(`${message.type().toUpperCase()} ${message.text()}`);});\n'

for label,old in [('helper anchor',anchor),('before snapshot',before_old),('after snapshot',after_old)]:
    if text.count(old)!=1: raise SystemExit(f'{label}: expected 1 match, found {text.count(old)}')
if 'stableCompositorSnapshot' in text: raise SystemExit('stableCompositorSnapshot already present')
if text.count('import puppeteer from "puppeteer-core";')!=1: raise SystemExit('puppeteer import anchor mismatch')
text=text.replace('import puppeteer from "puppeteer-core";','import puppeteer from "puppeteer-core";\nimport {deflateSync} from "node:zlib";',1)

fixture_pattern=r'^const imageryTile=.*?,vectorTile=Buffer\.from\("1a0f0a086275696c64696e672880207802","hex"\),demTile=.*?,failed=\[\],consoleErrors=\[\];$'
fixture_replacement='''const crc32=buffer=>{let crc=0xffffffff;for(const byte of buffer){crc^=byte;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return(crc^0xffffffff)>>>0;};\nconst pngChunk=(type,data)=>{const name=Buffer.from(type,"ascii"),chunk=Buffer.alloc(12+data.length);chunk.writeUInt32BE(data.length,0);name.copy(chunk,4);data.copy(chunk,8);chunk.writeUInt32BE(crc32(Buffer.concat([name,data])),8+data.length);return chunk;};\nconst solidPng=(width,height,r,g,b,a=255)=>{const signature=Buffer.from([137,80,78,71,13,10,26,10]),ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(width,0);ihdr.writeUInt32BE(height,4);ihdr[8]=8;ihdr[9]=6;const stride=1+width*4,raw=Buffer.alloc(stride*height);for(let y=0;y<height;y++){const row=y*stride;raw[row]=0;for(let x=0;x<width;x++){const p=row+1+x*4;raw[p]=r;raw[p+1]=g;raw[p+2]=b;raw[p+3]=a;}}return Buffer.concat([signature,pngChunk("IHDR",ihdr),pngChunk("IDAT",deflateSync(raw)),pngChunk("IEND",Buffer.alloc(0))]);};\n// Terrarium RGB 128,20,0 = 20.0 m MSL exactly. Both fixtures are valid CRC-checked PNGs generated by Node.\nconst imageryTile=solidPng(256,256,74,102,82),vectorTile=Buffer.from("1a0f0a086275696c64696e672880207802","hex"),demTile=solidPng(512,512,128,20,0),failed=[],consoleErrors=[];'''
text,replacements=re.subn(fixture_pattern,fixture_replacement,text,count=1,flags=re.M)
if replacements!=1: raise SystemExit(f'image fixture line replacement count={replacements}, expected 1')

text=text.replace(anchor,anchor+helper,1)
text=text.replace(before_old,'const before=await stableCompositorSnapshot();',1)
text=text.replace(after_old,'const after=await stableCompositorSnapshot();',1)
if 'b.map.getCanvas()' in text: raise SystemExit('unsafe direct b.map.getCanvas() remains')
if 'Buffer.from("iVBOR' in text: raise SystemExit('legacy embedded PNG fixture remains')
path.write_text(text)
print('patched Honor fixtures to generated valid PNGs and stable same-instance compositor snapshots')
