from pathlib import Path

path=Path('tests/android_render_browser_smoke.mjs')
text=path.read_text()

before_old='const before=await page.evaluate(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld,flight=b.threeRenderer.domElement,map=b.map.getCanvas(),flightAttrs=b.threeRenderer.getContext().getContextAttributes(),mapGl=map.getContext("webgl2")||map.getContext("webgl"),mapAttrs=mapGl?.getContextAttributes?.()||{};return{platform:v.dataset.renderPlatform,stable:v.dataset.presentationStableBackbuffer,software:Boolean(globalThis.__arondightDiagnostics?.presentationSoftwareRaster),flightDesync:flightAttrs?.desynchronized===true,mapDesync:mapAttrs?.desynchronized===true,declaredFlight:v.dataset.presentationCanvasDesynchronized,declaredMap:v.dataset.worldMapCanvasDesynchronized,flightSize:[flight.width,flight.height],mapSize:[map.width,map.height],mapRatio:map.width/Math.max(1,map.clientWidth),ratio:b.threeRenderer.getPixelRatio(),resizes:Number(v.dataset.presentationBackbufferResizes||0),terrain:v.dataset.worldTerrainStatus,terrainTriangles:Number(v.dataset.worldTerrainTriangles||0),worldFrames:Number(v.dataset.worldThreeFrames||0),presentationDraws:Number(v.dataset.presentationDraws||0)};});'
after_old='const after=await page.evaluate(()=>{const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld,flight=b.threeRenderer.domElement,map=b.map.getCanvas();return{flightSize:[flight.width,flight.height],mapSize:[map.width,map.height],mapRatio:map.width/Math.max(1,map.clientWidth),ratio:b.threeRenderer.getPixelRatio(),resizes:Number(v.dataset.presentationBackbufferResizes||0),quality:v.dataset.presentationQualityMode,perf:v.dataset.worldPerfMode,worldFrames:Number(v.dataset.worldThreeFrames||0),presentationDraws:Number(v.dataset.presentationDraws||0)};});'

helper='''const stableCompositorSnapshot=async()=>page.evaluate(async()=>{\n  const deadline=performance.now()+10000;\n  for(;;){\n    const v=document.querySelector("#viewport"),b=globalThis.__arondightRealWorld,mapObject=b?.map,renderer=b?.threeRenderer;\n    const ready=document.body.classList.contains("solo-flight")&&v?.dataset.worldMode==="real"&&v?.dataset.worldTerrainStatus==="box3d-active"&&Boolean(b?.active)&&!b?.loading&&Boolean(mapObject?.getCanvas)&&Boolean(renderer?.domElement)&&Number(v?.dataset.worldThreeFrames||0)>=1&&Number(v?.dataset.presentationDraws||0)>=10;\n    if(ready){\n      await new Promise(requestAnimationFrame);\n      if(globalThis.__arondightRealWorld===b&&b.map===mapObject&&b.threeRenderer===renderer&&b.active&&!b.loading){\n        const flight=renderer.domElement,map=mapObject.getCanvas(),flightAttrs=renderer.getContext().getContextAttributes(),mapGl=map.getContext("webgl2")||map.getContext("webgl"),mapAttrs=mapGl?.getContextAttributes?.()||{};\n        return{platform:v.dataset.renderPlatform,stable:v.dataset.presentationStableBackbuffer,software:Boolean(globalThis.__arondightDiagnostics?.presentationSoftwareRaster),flightDesync:flightAttrs?.desynchronized===true,mapDesync:mapAttrs?.desynchronized===true,declaredFlight:v.dataset.presentationCanvasDesynchronized,declaredMap:v.dataset.worldMapCanvasDesynchronized,flightSize:[flight.width,flight.height],mapSize:[map.width,map.height],mapRatio:map.width/Math.max(1,map.clientWidth),ratio:renderer.getPixelRatio(),resizes:Number(v.dataset.presentationBackbufferResizes||0),terrain:v.dataset.worldTerrainStatus,terrainTriangles:Number(v.dataset.worldTerrainTriangles||0),worldFrames:Number(v.dataset.worldThreeFrames||0),presentationDraws:Number(v.dataset.presentationDraws||0),quality:v.dataset.presentationQualityMode,perf:v.dataset.worldPerfMode};\n      }\n    }\n    if(performance.now()>=deadline)throw new Error(`Honor stable compositor snapshot timeout: ${JSON.stringify({active:Boolean(b?.active),loading:Boolean(b?.loading),map:Boolean(b?.map),renderer:Boolean(b?.threeRenderer),terrain:v?.dataset.worldTerrainStatus||"",worldFrames:v?.dataset.worldThreeFrames||"",presentationDraws:v?.dataset.presentationDraws||""})}`);\n    await new Promise(requestAnimationFrame);\n  }\n});\n'''
anchor='page.on("requestfailed",request=>failed.push(`${request.failure()?.errorText||"FAILED"} ${request.url()}`));page.on("pageerror",error=>consoleErrors.push(`PAGEERROR ${error.message}`));page.on("console",message=>{if(message.type()==="error"||message.type()==="warning")consoleErrors.push(`${message.type().toUpperCase()} ${message.text()}`);});\n'

for label,old in [('helper anchor',anchor),('before snapshot',before_old),('after snapshot',after_old)]:
    if text.count(old)!=1: raise SystemExit(f'{label}: expected 1 match, found {text.count(old)}')
if 'stableCompositorSnapshot' in text: raise SystemExit('stableCompositorSnapshot already present')
text=text.replace(anchor,anchor+helper,1)
text=text.replace(before_old,'const before=await stableCompositorSnapshot();',1)
text=text.replace(after_old,'const after=await stableCompositorSnapshot();',1)
if 'b.map.getCanvas()' in text: raise SystemExit('unsafe direct b.map.getCanvas() remains')
path.write_text(text)
print('patched Honor compositor sampling to stable same-instance snapshots')
