name: Deploy static site (no-queue, fast)

on:
  push:
    branches: [ "main" ]
    # Optional: only run when site changes
    # paths:
    #   - 'dist/**'
    #   - '.github/workflows/pages.yml'
  workflow_dispatch:

concurrency:
  group: gh-pages-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write  # we push to gh-pages

env:
  SITE_DIR: dist  # set to "." if you publish repo root

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: false

      - name: Resolve site dir + disable Jekyll
        id: site
        run: |
          DIR="${SITE_DIR}"
          [ -d "$DIR" ] || DIR="."
          echo "dir=$DIR" >> "$GITHUB_OUTPUT"
          mkdir -p "$DIR"
          # .nojekyll avoids any build step and speeds publishing
          touch "$DIR/.nojekyll"

      - name: Deploy to gh-pages (single commit)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ steps.site.outputs.dir }}
          force_orphan: true      # keeps branch history tiny = faster
          # cname: example.com     # uncomment if you use a custom domain
